### DISCUSSION TITLE
Active Directory not works

### DISCUSSION THREAD

**Discussion by rocklee44** [authelia/authelia#3410] [Q&A] [answered]
Hi all,
I'm using Authelia v4.35.0 docker-compose Lite , I'm trying to config auth with Active Directory but it doesn't work, here my config
```
configuration.yml
authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: activedirectory
    url: ldap://192.168.7.103:389
    timeout: 5s
    start_tls: false
    tls:
      server_name: dc.mydomain.com
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: OU=Central Management,DC=mydomain,DC=com
    username_attribute: sAMAccountName
    additional_users_dn: ou=Users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    permit_referrals: false
    user: CN=ldapuser,OU=Users,OU=ICT,OU=SGN,OU=Central Management,DC=mydomain,DC=com
    password: *******
```

This is log
```
time="2022-05-20T15:25:37+07:00" level=debug msg="Mark 1FA authentication attempt made by user 'user1'" method=POST path=/api/firstfactor remote_ip=192.168.14.26
time="2022-05-20T15:25:37+07:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'user1': user not found" method=POST path=/api/firstfactor remote_ip=192.168.14.26 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:198           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:53 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:53 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.8/router.go:414                             (*Router).Handler\ngithub.com/valyala/fasthttp@v1.35.0/http.go:153                             (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.35.0/server.go:2338                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.35.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.35.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571
```

Of course, domain user user1 & ldapuser are existed and can login normally.
```
ldapsearch -h 192.168.7.103 -p 389 -b 'OU=Central Management,DC=mydomain,DC=com' -D 'CN=ldapuser,OU=Users,OU=ICT,OU=SGN,OU=Central Management,DC=mydomain,DC=com' -w '*********' "(&(sAMAccountName=user1)(objectClass=person))"
......
# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```
Please give me some advice , thank you very much.
