### DISCUSSION TITLE
O365 Notification Provider Error

### DISCUSSION THREAD

**Discussion by ghxstxch** [authelia/authelia#3504] [Q&A] [answered]
### Description
When attempting to use an O365 email for the notification provider, with or without setting up an app password, it errors out with below log errors. Authelia then quits, as expected.

### Expected Behaviour

Should work a la setting up notification provider via gmail

### Reproduction Steps

1. Followed [this guide](https://www.youtube.com/watch?v=IWNypK2WxB0), which worked up until this issue with O365, spitting out the below log error. 

### Additional Information

`time="2022-06-10T16:57:24-05:00" level=warning msg="Notifier SMTP client encountered error during cleanup: use of closed network connection"
time="2022-06-10T16:57:24-05:00"
 level=error msg="Failure running the notification provider startup check: 535 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [XXXXXX.namprd16.prod.outlook.com]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:106 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:78 cmdRootRun\ngithub.com/spf13/cobra@v1.4.0/command.go:860 (*Command).execute\ngithub.com/spf13/cobra@v1.4.0/command.go:974 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.4.0/command.go:902 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10 main\nruntime/proc.go:250 main\nruntime/asm_amd64.s:1571 goexit"`

Configuration.yml: 
```yaml
notifier:
  disable_startup_check: false
  smtp:
    username: me@domain.com
    password: APP-PASSWORD
    host: smtp.office365.com
    port: 587
    sender: auth@domain.com
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: true
      minimum_version: TLS1.2
```

Environment is Docker through Unraid.

Please let me know what else I can provide, I'd be more than happy to provide anything to get this up and running.
