### DISCUSSION TITLE
ACL config question

### DISCUSSION THREAD

**Discussion by YouveGotMeowxy** [authelia/authelia#3546] [Q&A]
I basically just want all users to use two factor for my  subdomains. With my current config, it seems that for s**ome of the subdomains it works correctly**, while **some give me a "forbidden to user" error,** even when I've logged into Authelia and selected to Remember the user, so that I stay logged in, and this is what's got me faclempt. :P

The error (happens on a couple of sub domains I've noticed so far):

```
today at 12:58:41 AM{"level":"info","method":"GET","msg":"Access to https://gotify.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"re.dac.ted","time":"2022-06-19T00:58:41-05:00"}
today at 12:58:41 AM{"level":"info","method":"GET","msg":"Access to https://phpmyadmin.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"re.dac.ted","time":"2022-06-19T00:58:41-05:00"}
```

My config:

```
access_control:
  default_policy: deny

  networks:
    - name: internal
      networks: '10.0.0.0/16' # Docker network

  rules:
    - domain: '*.redacted.rocks'
      policy: two_factor
      networks: 'internal'
      subject:
        - ['user:kacey', 'user:bob']
        - ['group:admin', 'group:family']
```

I've also tried without the "subject" key/values entirely (actually, originally it didnt have those, and I added them to try and work past this issue).

What am I doing wrong?

**Comment by nightah** [comment]
I think you've misinterpreted how the [subject option](https://www.authelia.com/configuration/security/access-control/#subject) works.

In your example, your rule assumes accepts either a user of [kacey **AND** bob] (not kacey or bob) or a group of [admin **AND** family] so the specific user needs to be part of both the admin and family group (which I suspect kacey probably is not).

This is probably the actual rule you want:

```yaml
  rules:
    - domain: '*.redacted.rocks'
      policy: two_factor
      networks: 'internal'
      subject:
        - 'user:kacey'
        - 'user:bob'
        - 'group:admin'
        - 'group:family'
```

The above rule evaluates the subject and as long as a user meets one of the above criteria they will be allowed access (it's described in detail with examples on the docs site I linked).

**Reply by YouveGotMeowxy** [reply]
thank you @nightah , kacey is in both groups, however, the users did need to be on separate lines.

As a test though I went ahead and placed all 4 on their own line, restarted the Authelia container, and revisited the 2 pages (subdomains) mentioned and unfortunately I'm still getting the exact same error.

**Reply by YouveGotMeowxy** [reply]
Just tested with a bunch of other subdomains as well: :/

```
today at 2:00:10 AM{"level":"info","method":"GET","msg":"Access to https://crowdsec-dashboard.redacted.rocks/robots.txt is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:10-05:00"}
today at 2:00:10 AM{"level":"info","method":"GET","msg":"Access to https://crowdsec-dashboard.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:10-05:00"}
today at 2:00:10 AM{"level":"info","method":"GET","msg":"Access to https://crowdsec-dashboard.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:10-05:00"}
today at 2:00:14 AM{"level":"info","method":"GET","msg":"Access to https://nzbhydra.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:14-05:00"}
today at 2:00:14 AM{"level":"info","method":"GET","msg":"Access to https://nzbhydra.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:14-05:00"}
today at 2:00:20 AM{"level":"info","method":"GET","msg":"Access to https://radarr.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:20-05:00"}
today at 2:00:20 AM{"level":"info","method":"GET","msg":"Access to https://radarr.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:20-05:00"}
today at 2:00:21 AM{"level":"info","method":"GET","msg":"Access to https://sonarr.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:21-05:00"}
today at 2:00:21 AM{"level":"info","method":"GET","msg":"Access to https://sonarr.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:21-05:00"}
today at 2:00:21 AM{"level":"info","method":"GET","msg":"Access to https://lidarr.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:21-05:00"}
today at 2:00:22 AM{"level":"info","method":"GET","msg":"Access to https://lidarr.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:22-05:00"}
today at 2:00:22 AM{"level":"info","method":"GET","msg":"Access to https://bazarr.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:22-05:00"}
today at 2:00:23 AM{"level":"info","method":"GET","msg":"Access to https://bazarr.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"71.255.255.169","time":"2022-06-19T02:00:23-05:00"}
```

**Reply by nightah** [reply]
So the issue is that where you're testing from isn't in the `10.0.0.0/16` subnet, remember all elements of the rule must match otherwise it will be denied.
Also, you left your IP address in the log lines so you may or may not want to redact that.

**Reply by YouveGotMeowxy** [reply]
> So the issue is that where you're testing from isn't in the `10.0.0.0/16` subnet, remember all elements of the rule must match otherwise it will be denied

I'm still learning this Authelia curve, so I'm not 100 percent clear on everything yet, lol. So far all I've added in the subnet is the docker network(s) subnet so the containers can all talk to each other. Beyond that I don't really know what to add? Other than the containers needing to communicate with each other, I just visit the domains as anyone would. Right now from my home computer, but could also be from anywhere; a friends house, my mobile phone while I'm out, etc. What else would I put in to make it work?

> Also, you left your IP address in the log lines so you may or may not want to redact that.

I replaced the middle 2 octets with 255, but ty for pointing it out just in case I hadn't. :)

Now, I haven't 100% verified this yet, but so far it *seems* like maybe this is happening only on the domains that I've disabled the built-in logins to, so that I can use Authelia in place of them; I wonder if that's somehow the issue? For example, I use Dozzle, which has no built in login mechanism, and I use Portainer, which I have NOT disabled it's built-in login mechanism yet (I have to do a double login; authelia and then Portainers) and I can still access those; but for sites like the *arrs, phpmyadmin, etc. I disabled/turned off their built-in login mechanisms, and those seem to be the ones I'm getting that user error with?

I could be off on that, but I'm just thinking out loud.

**Reply by YouveGotMeowxy** [reply]
Ok, apologies for the comment spam, lol, but I tested the login mech thing I mentioned and that didnt seem to have anythign to do with it.

Then, I added my exact home IP like this:

```
  networks:
    - name: 'internal'
      networks: '10.0.0.0/16'
    - name: 'known'
      networks: '71.225.255.169' # My Home IP

  rules:
    - domain: '*.redacted.rocks'
      policy: two_factor
      networks:
        - 'internal'
        - 'known'
 ```

and it works. My question is, if I have to add exact IP's, how would I be able to use my sites if I'm 'just anywhere in the world?'

**Reply by james-d-elliott** [reply]
You don't have to add exact IP's specifically, you can add a range such as 192.168.0.0/24, but if the detected remote_ip doesn't match it wont match that rule.

> how would I be able to use my sites if I'm 'just anywhere in the world?'

You just need a rule that matches the less specific scenario. For example this will bypass anything where the remote_ip is detected in the 10.0.0.0/16 range with the hostname exampleapp.redacted.rocks, however if it isn't it'll require two_factor for exampleapp.redacted.rocks otherwise.

```yaml
  networks:
    - name: 'internal'
      networks: '10.0.0.0/16'
  rules:
    - domain: 'exampleapp.redacted.rocks'
      policy: bypass
      networks: 
      - internal
    - domain: '*.redacted.rocks'
      policy: two_factor
```

**Reply by nightah** [reply]
Yep, pretty much how @james-d-elliott has summarised.

If you want those services to be accessible anywhere in the world with all the other criteria defined, just remove the `networks:` option on the rule. This effectively means that as long as the user is bob or kacey, or any body part of the admin or family group will have access to all those resources after they have performed 2FA.

Usually, the `networks` option is utilised to bypass authentication for specific internal trusted networks or it can also be utilised to have an extra security check (trusted networks only) for specific applications that require elevated security.

**Reply by YouveGotMeowxy** [reply]
Ty both so much for the help.

So this is what I'm thinking so far:

```
  default_policy: deny

  networks:
    - name: 'docker'
      networks: '10.0.0.0/16'       # Docker internal networks
    - name: 'local'
      networks: '192.168.0.0/24' # LAN

  rules:
    - domain: '*.redacted.rocks'
      policy: bypass
      networks:
        - 'docker'
        - 'local'
    - domain: '*.redacted.rocks'
      policy: two_factor
```

My logic is this:

- free access to all docker/LAN traffic so the containers can freely do any API stuff and what not amongst themselves.
- and then any traffic outside of the docker network/LAN require full-on two factor.

does this look right?
