### DISCUSSION TITLE
any one successfully integrate with owncloud?

### DISCUSSION THREAD

**Discussion by chain710** [authelia/authelia#3681] [Q&A]
authelia config:
```yaml
    clients:
      - id: owncloud
        secret: secret
        public: false
        authorization_policy: two_factor
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://owncloud.my.local/apps/openidconnect/redirect
        userinfo_signing_algorithm: none
```

owncloud config:
```
  array (
    'provider-url' => 'https://auth.my.lan',
    'client-id' => 'owncloud',
    'client-secret' => 'secret',
    'loginButtonName' => 'OpenId Connect',
  ),
```

then open owncloud login page, click "Openid Connect", got internal error

owncloud log, found "Error decoding JSON from token header":
```
{"reqId":"mEhVE5eyQWzuiAzsHtnI","level":3,"time":"2022-07-10T14:38:39+00:00","remoteAddr":"192.168.1.51","user":"user","app":"no app in context","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"JuliusPC\\\\OpenIDConnectClientException\",\"Message\":\"Error decoding JSON from token header\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/lib\\\/SessionVerifier.php(122): JuliusPC\\\\OpenIDConnectClient->verifyJWTsignature()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/lib\\\/Application.php(81): OCA\\\\OpenIdConnect\\\\SessionVerifier->verifySession()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/appinfo\\\/app.php(28): OCA\\\\OpenIdConnect\\\\Application->boot()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/appinfo\\\/app.php(29): OC_App::{closure}(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(253): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(192): OC_App::requireAppFile()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(125): OC_App::loadApp()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(898): OC_App::loadApps()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/openidconnect\\\/vendor\\\/juliuspc\\\/openid-connect-php\\\/src\\\/OpenIDConnectClient.php\",\"Line\":1016}"}
{"reqId":"mEhVE5eyQWzuiAzsHtnI","level":2,"time":"2022-07-10T14:38:39+00:00","remoteAddr":"192.168.1.51","user":"user","app":"core","method":"GET","url":"\/apps\/files\/","message":"Could not load app \"openidconnect\", see exception above"}
```
