### DISCUSSION TITLE
How to configure NTP for Authelia

### DISCUSSION THREAD

**Discussion by jlgarnier** [authelia/authelia#3685] [Q&A] [answered]
Hi Community!
I've set up an instance of Authelia + Redis, using the simple compose file hereunder (stack created with Portainer):
```
# from https://shownotes.opensourceisawesome.com/authelia-authentication/

version: '3.3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia-app
    volumes:
      - /srv/dev-disk-by-label-omvdata/docker/authelia/config:/config
    ports:
      - 8091:9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=$TIMEZONE
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: authelia-redis
    volumes:
      - /srv/dev-disk-by-label-omvdata/docker/authelia/redis:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=$TIMEZONE
```

TIMEZONE here is Europe/Paris and the initial stack crashed with the following error:
```
time="2022-07-11T13:51:54+02:00" level=fatal msg="The following providers had fatal failures during startup: ntp" stack="github.com/authelia/authelia/v4/internal/commands/root.go:177 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:77  cmdRootRun\ngithub.com/spf13/cobra@v1.5.0/command.go:876                  (*Command).execute\ngithub.com/spf13/cobra@v1.5.0/command.go:990                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.5.0/command.go:918                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1571                                      goexit"
```

I then added the following lines to the configuration.yml file:
```
ntp:
  address: "time.cloudflare.com:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false
```
and the stack crashes with **exactly the same error**. The documentation says "In the instance of inability to contact the NTP server Authelia will just log an error and will continue to run", while mine just stops, doesn't publish ports and is then not reachable.

I'm a bit lost then and I'm wondering whether the app image is corrupted or if my timezone could raise this issue. Did anyone encounter such an issue?

Any help will be appreciated!
