### DISCUSSION TITLE
panic: Unable to parse database: yaml: line 12: could not find expected ':'

### DISCUSSION THREAD

**Discussion by MrDuartePT** [authelia/authelia#3722] [Q&A] [answered]
After change the default configuration yaml and the users_database.yaml to my needs I am having this error:
```
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	github.com/authelia/authelia/v4/cmd/authelia/main.go:10 +0x24
time="2022-07-18T19:35:13+01:00" level=info msg="Authelia v4.36.2 is starting"
time="2022-07-18T19:35:13+01:00" level=info msg="Log severity set to debug"
panic: Unable to parse database: yaml: line 12: could not find expected ':'

goroutine 1 [running]:
github.com/authelia/authelia/v4/internal/authentication.NewFileUserProvider(0x4000393c50)
	github.com/authelia/authelia/v4/internal/authentication/file_user_provider.go:53 +0x130
github.com/authelia/authelia/v4/internal/commands.getProviders()
	github.com/authelia/authelia/v4/internal/commands/helpers.go:47 +0x170
github.com/authelia/authelia/v4/internal/commands.cmdRootRun(0x40002ee780?, {0x4000098ae0?, 0x2?, 0x2?})
	github.com/authelia/authelia/v4/internal/commands/root.go:62 +0x1e4
github.com/spf13/cobra.(*Command).execute(0x40002ee780, {0x40000320a0, 0x2, 0x2})
	github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x40002ee780)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
```

My configuration.yaml (the keys and domains are not real):
```
---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: onerandomkey
default_redirection_url: https://auth.domain.tk

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
theme: dark

totp:
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64


access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: sub.domain.tk
      policy: two_factor
    - domain: sub2.domain.tk
      policy: bypass

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: domain.tk # Should match whatever your root protected domain is

#  redis:
#    host: redis
#    port: 6379
#    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
#    # password: authelia

regulation:
  max_retries: 5
  find_time: 120
  ban_time: 300

storage:
  encryption_key: onerandomkey
  local:
    path: /config/db.sqlite3

notifier:
   smtp:
     username: mymail@gmail.com
# This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_>
     password: somepassword
     host: smtp.gmail.com
     port: 587
     sender: autheliasupport@mrduarte.tk
...
```

**Comment by james-d-elliott** [comment]
Not likely a bug, please show the database file it's complaining about.

**Reply by MrDuartePT** [reply]
Sorry I put the wrong label i using the local database the problem can be the db.sqlite3 was not created, I can create a blank file and restart the container.(Edit: I created the file nothing change)
Where is my user_database, can be the cause of the problem:

````
Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  mrduarte:
    displayname: "Gonçalo Duarte"
    password:= 
    email: email@gmail.com
    groups:
      - admins
      - dev

...`
```

**Comment by james-d-elliott** [comment, marked as answer]
Try with this file:

```yaml
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  mrduarte:
    displayname: "Gonçalo Duarte"
    # Password is password123
    password: "$6$rounds=50000$ZWNsNWJtOTl1Q09U$Sg2k9gg7DPdjJAnlznFKx/U3sPXO/uisnKFTlrjsMoaE.3cm1K1AcEmwJ6K5cCEPyJppOrMOCTr8BDPznlfk2/"
    email: email@gmail.com
    groups:
      - admins
      - dev
...
```
