### DISCUSSION TITLE
Authelia gives 401 on PROPFIND request

### DISCUSSION THREAD

**Discussion by stenterstal** [authelia/authelia#3753] [Q&A] [answered]
## Bug Report

[Possibly related to #2923](https://github.com/authelia/authelia/issues/2923)

**[!] I have replaced my domains url in the logs with domain.tld**

### Description

I'm using Authelia with Traefik v2 reverse proxy and Cloudflare.

I have Authelia setup to protect my Cal|CardDAV web portal, but to bypass all traffic that syncs the calendars and agenda. All normal requests (GET|POST etc.) work fine but Authelia gives a 401 on the PROPFIND requests (see logs and configuration below).

In Issue #2923 it is said that when you don't pass any methods it should not block any (I haven't specified any specific methods)

Also the [access control documentation](https://www.authelia.com/configuration/security/access-control/#methods) reads that RFC4918 (eg. PROPFIND) are valid methods to specify under access control, but when PROPFIND is used the following line shows up in the log;
```
time="2022-07-25T15:43:19+02:00" level=error msg="Configuration: Method PROPFIND for rule #8 domain: [dav.domain.tld] is invalid, must be one of the following methods: GET, HEAD, POST, PUT, PATCH, DELETE, TRACE, CONNECT, OPTIONS"
```

### Expected Behaviour

I would expect Authelia to bypass PROPFIND requests when no specific methods are specified in the log as described in #2923
OR
I would expect Authelia to bypass PROPFIND requests when specified under the methods as [described in the documentation](https://www.authelia.com/configuration/security/access-control/#methods)

### Reproduction Steps

1. Use the specified authelia access control config
2. Use [baikal docker container](https://github.com/ckulka/baikal-docker) for the Cal|CardDAV server
3. Intialize baikal
4. Add CalDAV account to a DAV Client or manually make a PROPFIND request to `https://dav.domain.tld/dav.php/calendars/<user>/default/`
5. PROPFIND will return with a `401 Unauthorized`
6. Authelia docker log;
```
time="2022-07-25T15:54:03+02:00" level=debug msg="Check authorization of subject username= groups= ip=172.71.102.13 and object https://dav.domain.tld/dav.php/calendars/sten/default/ (method PROPFIND)."
```
7. Traefik access log;
```
{"ClientAddr":"172.71.102.155:16750","DownstreamStatus":401,"RequestAddr":"dav.domain.tld","RequestMethod":"PROPFIND","RequestPath":"/dav.php/calendars/sten/default/","RequestScheme":"https","level":"info","msg":"","time":"2022-07-25T13:30:57Z"}
```

#### Authelia access control config
```
access_control:
  default_policy: deny:
  rules:
    # Bypass all routes starting with /dav.php
    - domain: 'dav.domain.tld'
      policy: bypass
      resources:
      - '.*/dav.php.*'
      # You can't do this!!
      # methods:
      # - PROPFIND
      # ...
    # Block the web portal
    - domain: 'dav.domain.tld'
      policy: two_factor
```

**Comment by james-d-elliott** [comment]
Update.

**Comment by james-d-elliott** [comment]
Code:

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/access_control.go#L104

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/access_control.go#L145-L151

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/const.go#L301-L304

Message that should be displayed but isn't: 

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/const.go#L207-L208

**Comment by stenterstal** [comment]
I updated to docker master tag (updated 8hrs ago, log says; Authelia untagged-v4.36.2 (master, c128945)) and I still have the same errors/problem.

Strange thing I found is that when adding PROPFIND under methods I still get the before mentioned error line, but when changing it to "testmethod" I get the mentioned error message that wasn't displayed before.

```
time="2022-07-25T23:39:10+02:00" level=error msg="Configuration: access control: rule #8 (domain 'dav.domain.tld'): 'methods' option 'testmethod' is invalid: must be one of 'GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'TRACE', 'CONNECT', 'OPTIONS', 'COPY', 'LOCK', 'MKCOL', 'MOVE', 'PROPFIND', 'PROPPATCH', 'UNLOCK'"
```

PROPFIND is still getting 401 even when adding no methods section in config

**Comment by james-d-elliott** [comment]
'testmethod' is not a valid method. Show the complete unedited (feel free to perform one replace all for a single string with `example.com`, and replace  any IP's) trace logs (of both the config error with PROPFIND, and the 401 response which we log).

**Comment by stenterstal** [comment]
I understand that 'testmethod' is not valid, only tried it because that way correct error message shows.

I'm not getting config errors any longer with PROPFIND defined in the methods but still getting 401.

To rule out any misconfiguration on my end I tried removing and adding my DAV account to my phone again to no avail.

### Authelia console
```
time="2022-07-26T13:04:07+02:00" level=debug msg="Check authorization of subject username= groups= ip=172.71.94.113 and object https://dav.domain.tld/ (method PROPFIND)."
time="2022-07-26T13:04:07+02:00" level=info msg="Access to https://dav.domain.tld/ (method PROPFIND) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://auth.domain.tld/?rd=https%3A%2F%2Fdav.domain.tld%2F&rm=PROPFIND" method=GET path=/api/verify remote_ip=172.71.94.113
```

### Traefik access log
```
{"ClientAddr":"172.71.94.113:57176","DownstreamStatus":401,"RequestAddr":"dav.domain.tld","RequestMethod":"PROPFIND","RequestPath":"/","RequestScheme":"https","level":"info","msg":"","time":"2022-07-26T11:04:07Z"}
```

### Authelia access control config
```
access_control:
  default_policy: deny
  rules:
    - domain: 'dav.domain.tld'
      policy: bypass
      resources:
      - '.*/dav.php.*'
      methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PROPFIND
    - domain: 'dav.domain.tld'
      policy: two_factor
```

**Comment by nightah** [comment, marked as answer]
The logs are telling you that the PROPFIND method is being sent to the root path `/`.

Whereas your bypass is set on the following path `'.*/dav.php.*'`.

**Reply by stenterstal** [reply]
I also get 401's on this line, which does gets included in the regex:
```
{"ClientAddr":"141.101.107.83:39550","DownstreamStatus":401,"RequestAddr":"dav.domain.tld","RequestMethod":"PROPFIND","RequestPath":"/dav.php/calendars/sten/default/","RequestScheme":"https","level":"info","msg":"","time":"2022-07-28T10:58:15Z"}
```

With config
```
access_control:
  default_policy: deny
  rules:
    - domain: 'dav.domain.tld'
      policy: bypass
      resources:
      - '^/dav.php/.*$'
    - domain: 'dav.domain.tld'
      policy: two_factor
```

**Reply by stenterstal** [reply]
Even getting a 401 with a the bypass on the whole subdomain
```
access_control:
  default_policy: deny
  rules:
    - domain: 'dav.domain.tld'
      policy: bypass
```

**Reply by james-d-elliott** [reply]
There are no logs in Authelia that you provided that indicates this. That log message does not appear to be anything related to Authelia. Authelia WILL log any 401 response, and will log ALL responses when trace is enabled. Seems like an issue with the backend.

**Comment by james-d-elliott** [comment]
I'm converting this to a discussion since it's evidently a support query rather than a bug/fr.

**Comment by BobWs** [comment]
Hi, 
I was wondering if this problem is solved? Can't seem to find a anwser in the above discussion.
I'm having a sumilar problem with the same Baikal docker container. The WebAdmin page works with Authelia but none of the Calendar / Contacts clients work anymore when using Authelia portal.
I have setup docker Authelia + NPM to act as proxy portal.

**authelia config:**
```
access_control:
  default_policy: deny
  rules:
    - domain: "dav.domain.tld"
      resources:
      - "^/dav.php/.*$"
      - "^/principals/.*$"
      - "^/api([/?].*)?$"
      policy: bypass      
    - domain: "dav.domain.tld"
      policy: two_factor
```
**NPM endpoint config**
```
location /authelia {
internal;
set $upstream_authelia http://192.168.178.111:9091/api/verify;
proxy_pass_request_body off;
proxy_pass $upstream_authelia;    
proxy_set_header Content-Length "";

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
client_body_buffer_size 128k;
proxy_set_header Host $host;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr; 
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 4 32k;

send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;
}

location / {
set $upstream_app $forward_scheme://$server:$port;
proxy_pass $upstream_app;

auth_request /authelia;
auth_request_set $target_url https://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $email $upstream_http_remote_email;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Email $email;
proxy_set_header Remote-Groups $groups;

error_page 401 =302 https://auth.domain.tld/?rd=$target_url;

client_body_buffer_size 128k;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

set_real_ip_from 172.20.0.0/16;
set_real_ip_from 192.168.178.0/24;
real_ip_header CF-Connecting-IP;
real_ip_recursive on;

}
```
Any help would be appreciated
TIA

**Reply by james-d-elliott** [reply]
Yes the question was answered, there was never actually a problem. We just didn't allow rules which defined the PROPINFO method so we added that feature. If you want help we'll need log of the request being denied by Authelia.

**Reply by BobWs** [reply]
This is the log for davserver:
```
time="2024-02-13T10:25:32+01:00" level=info msg="Access to https://dav.domain.tld/dav.php/principals/Bob/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T10:25:32+01:00" level=info msg="Access to https://dav.domain.tld/dav.php/principals/Bob/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T10:25:32+01:00" level=info msg="Access to https://dav.domain.tld/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T10:25:32+01:00" level=info msg="Access to https://dav.domain.tld/principals/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T10:26:14+01:00" level=info msg="Access to https://dav.domain.tld/dav.php/principals/Bob/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.154
time="2024-02-13T10:26:14+01:00" level=info msg="Access to https://dav.domain.tld/dav.php/principals/Bob/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.154
```
This is the log when trying using Authelia as portal for a docker webdav server:
```
time="2024-02-13T11:08:49+01:00" level=warning msg="https://webdav.domain.tld/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=192.168.178.151
time="2024-02-13T11:12:15+01:00" level=info msg="Access to https://webdav.domain.tld/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T11:12:22+01:00" level=warning msg="https://webdav.domain.tld/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=192.168.178.151
time="2024-02-13T11:15:36+01:00" level=warning msg="Session destroyed for user 'admin' after exceeding configured session inactivity and not being marked as remembered" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T11:15:36+01:00" level=info msg="Access to https://webdav.domain.tld/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T11:15:40+01:00" level=warning msg="https://webdav.domain.tld/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=192.168.178.151
```
This is the log when using Authelia with docker Vaultwarden for the admin page:
```
time="2024-02-13T12:46:58+01:00" level=info msg="Access to https://vault.domain.tld/vw_static/admin.js (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T12:47:07+01:00" level=info msg="Access to https://vault.domain.tld/vw_static/admin.js (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
time="2024-02-13T12:47:07+01:00" level=info msg="Access to https://vault.domain.tld/vw_static/admin.css (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.178.151
```
None of them are working as supposed to. Authelia login is working but that all the redirect don't work!

The rules in authelia config:
```
access_control:
  default_policy: deny
  rules:
    - domain: 
        - "auth.domain.tld"
      policy: bypass
    - domain: "*.domain.tld"
      resources:
        - "^/api([/?].*)?$"
        - "^/identity.*$"
        - "^/triggers.*$"
        - "^/meshagents.*$"
        - "^/meshsettings.*$"
        - "^/agent.*$"
        - "^/control.*$"
        - "^/meshrelay.*$"
        - "^/wl.*$"
        - "^/dav.php/addressbooks/.*$"
        - "^/dav.php/calendars/.*$"
        - "^/dav.php/.*$"       
      policy: bypass
    - domain: "vault.domain.tld"
      resources:
        - "^*/admin.*$"
      policy: two_factor
    - domain:
        - "vault.domain.tld"
      policy: bypass 
```
All the log shows acces deny for `user <anonymous>` but I'm using ldap settings for the users that are registered.

**Reply by BobWs** [reply]
Authelia login test via the url: https://auth.domain.tld
![Screen_Shot 1](https://github.com/authelia/authelia/assets/5485820/f308e8dc-9878-4c2f-a677-c65e2ea972b5)
![Screen_Shot 2](https://github.com/authelia/authelia/assets/5485820/80855575-944d-430a-b6d3-5f989e9a4550)
![Screen_Shot 3](https://github.com/authelia/authelia/assets/5485820/9045b8b4-569a-485d-a02b-75435bf29abc)

**Reply by james-d-elliott** [reply]
Have you restarted Authelia? What happens if you just bypass everything? Seems like your not including the whole rules section, not editing the correct config, or restarting to me though I've not carefully checked it.

**Reply by BobWs** [reply]
yes and yes I do restart the container after every change I make in the config file. Above I have posted my rules section to inspect...

**Reply by BobWs** [reply]
For example when I use the rule with the added resources Authelia is not working to protect the given pages.
```
access_control:
  default_policy: deny
  rules:
    - domain: 
        - "auth.domain.tld"
      policy: bypass
    - domain: "dav.domain.tld"
      resources:
        - "^/api([/?].*)?$"
        - "^/dav.php/.*$"
        - "^/dav.php/addressbooks/.*$"
        - "^/dav.php/calendars/.*$"
        - "^/dav.php/principals/.*$"       
      policy: bypass
    - domain: "vault.domain.tld"
      resources:
        - "^*/admin/.*$"
      policy: two_factor
    - domain:
        - "vault.domain.tld"
      policy: bypass 
    - domain:
        - "webdav.domain.tld"
      policy: two_factor       
    - domain: "blog.domain.tld"
      resources:
        - "^*/ghost/#/signin/.*$"
      policy: two_factor
    - domain:
        - "blog.domain.tld"
      policy: bypass 
```

But when I set the rule to only the subdomain (example), the it is working.
```
access_control:
  default_policy: deny
  rules:       
    - domain:
        - "blog.domain.tld"
      policy: two_factor 
```
But that is noy what I want for Authelia. I only want to protect the webadmin pages for some specific apps.
In case of the webdav rule I can login via the Authelia login screen but then it ends in a loop.
