### DISCUSSION TITLE
webauthn/register page do not open

### DISCUSSION THREAD

**Discussion by varazir** [authelia/authelia#3786] [Q&A] [answered]
### Description

When trying to register a device I get a "http" url that don't work, I get a white page.
Chrome redirects me to https url. 

### Expected Behaviour

I would get a QR code to register my device 

### Reproduction Steps

1) I login to authelia webb gui
2) click on Register device 

### Additional Information

```yaml
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
```
