### DISCUSSION TITLE
Access rules when using LDAP

### DISCUSSION THREAD

**Discussion by pwlgrzs** [authelia/authelia#3851] [Q&A] [answered]
Hello,

I am having some issues with setting up a domain specific access rules with Active Directory groups. I've made 2 following rules (note they're listed in config in this specific order):

```
  - domain:
      - "2fa.domain.com"
    policy: one_factor
    subject:
    - 'group:Authelia-2FAuth-Access'
  - domain:
      - "*.domain.com"
      - "domain.com"
    policy: two_factor
    subject: 
    - 'group:Authelia-GeneralAccess'
```

2fa.domain.com is not authelia, it's a different app.

users_filter and groups_filter are done according to documentation (https://www.authelia.com/reference/guides/ldap/#implementation-guide).
Group name in subject - group are noted exactly as in AD.
When inspecting logs I can see user is read with group memberships and Authelia-2FAuth-Access group is not listed.

`time="2022-08-16T11:53:27+02:00" level=debug msg="Check authorization of subject username=USER groups=GROUP1,GROUP2,GROUP3,Authelia-GeneralAccess ip=X.X.X.X and object https://auth.domain.com/api/logout (method POST)."`

What happens:
User is in Authelia-GeneralAccess but not Authelia-2FAuth-Access.
I am able to log in to 2fa.domain.com and two_factor policy is applied.

What I would expect:
Scenario 1:
User is in Authelia-GeneralAccess but not Authelia-2FAuth-Access.
I am not able to log in to 2fa.domain.com.
Scenario 2:
User is in Authelia-GeneralAccess and Authelia-2FAuth-Access.
I am able to log in to 2fa.domain.com with one_factor policy.

**Comment by pwlgrzs** [comment]
I have returned to the docs and amended my rules to actually match **AND** rules as follows:

```
  - domain:
      - "2fa.domain.com"
    policy: one_factor
    subject:
    - ['group:Authelia-2FAuth-Access', 'group:Authelia-GeneralAccess']
  - domain:
      - "2fa.domain.com"
    policy: deny
  - domain:
      - "*.domain.com"
      - "domain.com"
    policy: two_factor
```

It seems to yield expected results now in scenario "user not in group AND group". Is this how it should be configured or is there a better approach?
