### DISCUSSION TITLE
Cannot access localhost:9091 - try to get it working with nginx

### DISCUSSION THREAD

**Discussion by timaschew** [authelia/authelia#3886] [Q&A] [answered]
I'm using [dokku](https://dokku.com) which allows me to deploy from git / Dockerfile to my server. It uses nginx, letsecnrypt and is creating for each of my app a subdomain. I really like it. But I would like to enable 2FA for some of my apps.

Nginx is installed on the host, the apps are running inside docker.
I've tried to follow the docs: https://www.authelia.com/integration/proxies/nginx/#authelia-locationconf
but it doesn't work. I'm using this docker-compose.yml part: https://github.com/authelia/authelia/blob/68f6afd6ac4c71d4d033b07f146e87c9eb355d19/examples/compose/local/docker-compose.yml#L2-L31 and a minor modified example config. But I cannot access authelia even from my host. If I do a `curl localhost:9091` it shows me connection refused. The logs show this:

```
docker-compose up
Creating network "authelia_net" with driver "bridge"
Creating authelia ... done
Attaching to authelia
authelia    | time="2022-08-25T00:20:34+02:00" level=info msg="Authelia v4.36.4 is starting"
authelia    | time="2022-08-25T00:20:34+02:00" level=info msg="Log severity set to info"
authelia    | time="2022-08-25T00:20:34+02:00" level=info msg="Storage schema is being checked for updates"
authelia    | time="2022-08-25T00:20:34+02:00" level=info msg="Storage schema is already up to date"
authelia    | time="2022-08-25T00:20:34+02:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
```

Here is my authelia config:

```
theme: dark
jwt_secret: ***

server:
  host: 0.0.0.0
  port: 9091

totp:
  issuer: auth.MYDOMAIN

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: paperless.MYDOMAIN
      policy: two_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: MYDOMAIN.de

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: ***
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```

```
users:
  devil:
    displayname: "Timaschew"
    password: "$argon2id$v=19$m=16,t=2,p=1$MTIzNDU2Nzg$lvTv6X1S1cUgQ0HEg/o4hLz7gYwanVhsWoqdoOrUzsg"
    email: my@email.com
    groups:
      - admins
      - dev
```

version of docker and nginx:
```
docker-compose --version
docker-compose version 1.29.2, build 5becea4c

docker --version
Docker version 20.10.9, build c2ea9bc

nginx -V
nginx version: nginx/1.18.0
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-q9LD4J/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module
```
