### DISCUSSION TITLE
blank screen after succesfull login

### DISCUSSION THREAD

**Discussion by bambam247** [authelia/authelia#3891] [Q&A]
Ive been trying for days now to implement authelia in my kubernetes cluster + NGINX ingress as a simple way to still allow outside access to intranet sites with no authorization mechanisms of their own.
It seems that the LDAP configuration is correct, as I get notified of incorrect credentials. 
On succesfull login I see some of the requests to the upstream application come back successfully in developertools (eg. icons, ccs etc.) however the page itsself remains blank.

Expect result would be for the backend application to load a fully functional page

In some cases UI shows loading throbber and alert message;
`There was an issue retrieving global configuration`

upstream ingress annotations
```
annotations:
  cert-manager.io/issuer: letsencrypt-prod
  kubernetes.io/ingress.class: nginx
  kubernetes.io/tls-acme: "true"
  nginx.ingress.kubernetes.io/auth-method: GET
  nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
  nginx.ingress.kubernetes.io/auth-signin: https://auth.mymojo.nl?rm=$request_method
  nginx.ingress.kubernetes.io/auth-snippet: |
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Scheme $scheme;
    auth_request_set $target_url https://$http_host$request_uri;
    auth_request_set $user $upstream_http_remote_user;
    auth_request_set $groups $upstream_http_remote_groups;
    auth_request_set $name $upstream_http_remote_name;
    auth_request_set $email $upstream_http_remote_email;
    proxy_set_header Remote-User $user;
    proxy_set_header Remote-Groups $groups;
    proxy_set_header Remote-Name $name;
    proxy_set_header Remote-Email $email;
    error_page 401 =302 https://auth.mymojo.nl?rd=$target_url;
  nginx.ingress.kubernetes.io/auth-url: http://mmj-authelia.kube-system.svc.cluster.local/api/verify
```

authelia log;
```
level=debug msg="Mark 1FA authentication attempt made by user 'tony.wijnhard'" method=POST path=/api/firstfactor remote_ip=10.0.1.1
level=debug msg="Successful 1FA authentication attempt made by user 'tony.wijnhard'" method=POST path=/api/firstfactor remote_ip=10.0.1.1
level=debug msg="Check authorization of subject username=tony.wijnhard groups=Domain Admins,MMJ-VPNUSERS,MMJ-INT-DEVELOPER,MMJ-ADMIN,MMJ-CLOUD,pcs ip=10.0.1.1 and object https://intranet.mymojo.nl/ (method GET)."
level=debug msg="No matching rule for subject username=tony.wijnhard groups=Domain Admins,MMJ-VPNUSERS,MMJ-INT-DEVELOPER,MMJ-ADMIN,MMJ-CLOUD,pcs ip=10.0.1.1 and url https://intranet.mymojo.nl/... Applying default policy."
level=debug msg="Required level for the URL https://intranet.mymojo.nl/ is 3" method=POST path=/api/firstfactor remote_ip=10.0.1.1
level=debug msg="Redirection URL https://intranet.mymojo.nl/ is safe" method=POST path=/api/firstfactor remote_ip=10.0.1.1
```

configmap;
```
default_redirection_url: https://www.mymojo.nl
default_2fa_method: ""
server:
  host: 0.0.0.0
  port: 9091
  asset_path: ""
  headers:
    csp_template: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
log:
  level: debug
  format: text
  file_path: ""
  keep_stdout: true
totp:
  disable: false
  issuer: mymojo.nl
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s
ntp:
  address: time.cloudflare.com:123
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  ldap:
    implementation: activedirectory
    url: ldaps://mmj-msad-01
    timeout: 5s
    start_tls: false
    tls:
      server_name: 
      minimum_version: TLS1.2
      skip_verify: true
    base_dn: CN=Users,DC=mymojo,DC=nl
    permit_referrals: true
    permit_unauthenticated_bind: false
    user: CN=MMJ-READER,CN=Users,DC=mymojo,DC=nl
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: authelia_session
  domain: mymojo.nl
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
regulation: 
  ban_time: 5m
  find_time: 2m
  max_retries: 3
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
access_control:
  default_policy: deny
  rules:
    - policy: one_factor
      domain:
        - 'intranet.mymojo.nl'
      subject:
        - ['user:tony.wijnhard']
        - ['group:MMJ-ADMIN']
      resources:
        - '^/api.*'
    - policy: bypass
      domain:
        - 'www.mymojo.nl'
```

**Comment by james-d-elliott** [comment]
Hey lets see if we can figure this out. I'd like you to follow the following process:

1. Ensure you're not logged into authelia via visiting the `/logout` url, for example if your authelia is at `https://auth.example.com` visit `https://auth.example.com/logout`.
2. Visit https://www.authelia.com/r/har
3. Follow steps 1-5.
4. For step 6:
    1. Visit the URL of the _protected application_, i.e. _NOT the  Authelia URL_.
    2. Login.
5. Follow step 7.
6. Carefully read the [sanitization](https://www.authelia.com/reference/guides/http-archive-file/#sanitization) section.

**Comment by bambam247** [comment]
Hi there,

Attached you will find the har dump you requested. Im observing;
- The 2 last calls are returning with 403
- The first view calls after successful login seem to retrieve the domain icon some js and a css file from the upstream host as expected.
- proxy itsself seems oke, turning off authelia by rule results in the upstream site being served fully without requiring authentication as expected
- The default upstream domain (which does not exist) returns 401 after succesfull login as expected
- Performing the logout as you requested results in the browser redirecting back to the login screen and seemingly trying to login again on its own, in a loop. After a few times of which the login actually succeeds and i am presented with the "authenticated" screen

thanks for taking your time to look into this with me

[auth.mymojo.nl.har.txt](https://github.com/authelia/authelia/files/9431901/auth.mymojo.nl.har.txt)

**Comment by james-d-elliott** [comment]
Use the annotations in the integration docs and report back. There's nothing obvious in the HAR to show what's going on.

https://www.authelia.com/integration/kubernetes/nginx-ingress/#nginx-ingress-controller-ingress-nginx

**Comment by bambam247** [comment]
I wasnt able to make sense of this either but I still like the solution so I eventually had to reach out, your time is much appreciated!

On topic, behavior;
time="2022-08-26T13:28:46Z" level=debug msg="No matching rule for subject username=tony.wijnhard groups=Domain Admins,MMJ-VPNUSERS,MMJ-INT-DEVELOPER,MMJ-ADMIN,MMJ-CLOUD,pcs ip=10.0.1.1 and url https://intranet.mymojo.nl/... Applying default policy."

and 

time="2022-08-26T13:31:01Z" level=debug msg="Required level for the URL https://intranet.mymojo.nl/ is 3" method=POST path=/api/firstfactor remote_ip=192.168.250.21
time="2022-08-26T13:31:01Z" level=debug msg="Redirection URL https://intranet.mymojo.nl/ is safe" method=POST path=/api/firstfactor remote_ip=192.168.250.21

what im interested in is;
- what is required to reach level 3 for a URL, what does this level describe?
- how do I configure what level is required?
- why it is not matching a rule for my username and thus applying the default policy of denying, while I do have a matching rule for my username namely
  access_control:
    default_policy: deny
    rules:
      - policy: one_factor
        domain:
          - 'intranet.mymojo.nl'
        subject:
          - ['user:tony.wijnhard']
          - ['group:MMJ-ADMIN']
 
 Is the rule maybe not configured correctly?

Also im noticing that signing out causes the ui to loop a few times but never really signing out. Appearantly because for signing out it is looking to retrieve "api/user/info" and "api/configuration" which return 403 and therefor return the ui to login (with auth cookie) so it tries to authenticate with it again, and so on. 

Im opeing a fresh incognito window everytime to test.

**Comment by bambam247** [comment]
looks to be cors issue:
Access to manifest at 'https://auth.mymojo.nl/?rm=GET&rd=https://intranet.mymojo.nl%2FContent%2FImages%2FIcons%2Fmanifest.json%3Fh%3DDmoSjQqByGr1aINOqvSg9w' (redirected from 'https://intranet.mymojo.nl/Content/Images/Icons/manifest.json?h=DmoSjQqByGr1aINOqvSg9w') from origin 'https://intranet.mymojo.nl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Solved it by updating upstream app annotations to;
```
annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-signin: https://auth.mymojo.nl?rm=$request_method
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
      **proxy_set_header Access-Control-Allow-Origin mymojo.nl;**
    nginx.ingress.kubernetes.io/auth-url: http://mmj-authelia.kube-system.svc.cluster.local/api/verify
    **nginx.ingress.kubernetes.io/enable-cors: "true"**
```

After succesfull login;
- ccs, json etc retrieved from upstream application
- blank page
- 403 POST @ https://auth.mymojo.nl/api/user/info
- 403 GET @ https://auth.mymojo.nl/api/configuration


These can also be found in the har dump
