### DISCUSSION TITLE
panic: Unable to parse database: yaml: unmarshal errors:

### DISCUSSION THREAD

**Discussion by mmol67** [authelia/authelia#3986] [General]
Hello, I'm having this error when trying to get docker authelia up.
```
panic: Unable to parse database: yaml: unmarshal errors:
  line 3: cannot unmarshal !!str `miguel` into authentication.UserDetailsModel
  line 4: cannot unmarshal !!str `$argon2...` into authentication.UserDetailsModel
  line 5: cannot unmarshal !!str `migue...` into authentication.UserDetailsModel
  line 6: cannot unmarshal !!seq into authentication.UserDetailsModel
```
from my docker compose yalm
```
  authelia:
    image: ghcr.io/authelia/authelia:4.34.6
    #image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    user: "1000:1000"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /mnt/storage/docker/authelia:/config
    restart: unless-stopped
```

My users_database.yml
```
  miguel:
  dispalyname: "miguel"
  password: $argon2id$v=blahblah.......
  email: miguel@miemailserver.com
  groups: []
```

And my config
```
server:
  host: 0.0.0.0
  port: 9091
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: "authelia"
log:
  level: info
  file_path: /config/logs/authelia.log
jwt_secret: wowverylongsechet
default_redirection_url: https://mydomain.com
duo_api:
  hostname: api-somecode.duosecurity.com
  integration_key: akeygotfromduo
  secret_key: anotherkeygotfromduo
authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 8
access_control:
  default_policy: deny
  rules:
    - domain:
      - midomain.com
      - "*.midomain.com"
      policy: two_factor
session:
  name: authelia_session
  secret: anothersecret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: midomain.com
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: verylongone
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  smtp:
    username: miguel@mimailserver.com
    password: mypass
    host: smtp.mymailserver.com
    port: 587
    sender:miguel@mimailserver.com
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
```

What I'm doing wrong?

**Comment by james-d-elliott** [comment]
The indentation in the examples is important: https://www.authelia.com/reference/guides/passwords/#yaml-format

Also looks like you're missing the `users:` key at the  very top.

```yaml
users:
  miguel:
    dispalyname: "miguel"
    password: $argon2id$v=blahblah.......
    email: miguel@miemailserver.com
    groups: []
```
