### DISCUSSION TITLE
Access Control: Combining domain_regex with networks seems not working

### DISCUSSION THREAD

**Discussion by Cartache** [authelia/authelia#3996] [Q&A] [answered]
### Description
Using acceess control (network / domain_regex) rules separately works perfectly, when trying to combine the same rules in a signe does not seem to work.

If I limit access to ressources for a specific ip range and want to limit further this access to specific ressources, I am rediected to Authelia requesting authentication.

### Expected Behaviour

Bypass Authelia when both criteria match.

### Reproduction Steps

```
access_control:
  default_policy: deny
  networks:
  - name: home
    networks:
    - 192.168.1.0/24  
  rules:
      - domain_regex:
        - '^(xxx|yyy|zzz)\.domain\.name$'
        networks:
            - home
        policy: bypass
```
