### DISCUSSION TITLE
Unable to redirect to login portal

### DISCUSSION THREAD

**Discussion by erkerb4** [authelia/authelia#4036] [Q&A] [answered]
Hello,

I would like to first thank you for such a great solution! 

I'm trying to use Authelia + Traefik solution running on a Docker Swarm cluster. I am attempting to leverage authelia's login portal for multiple applications running in the Docker Swarm cluster. Most applications are available on a specific prefix "/code-[username]/". 

My setup of traefik + authelia closely mimics what has been demonstrated in the [authelia lite documentation](https://www.authelia.com/integration/deployment/docker/#lite). For user authentication, I am utilizing LDAP, and I have the following ACLs created for user-specific applications:

```
access_control:
  default_policy: deny
  rules:
    - domain: dev.fabrikam.net
      policy: one_factor
      subject:
        - 'group:testgrp-a'
        - 'group:testgrp-u'
      resources:
      - '^/viz([/?].*)?$'     ---> This is Fixed
      - '^/code-(?P<User>\w+)([/?].*)?$'     --> unique for each user
```

And I have the following middlewares configured:

```
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fdev.fabrikam.net%2Fauth%2F"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
```

When I visit https://dev.fabrikam.net/code-erkerb/ _(erkerb user is from ldap, and belongs to testgrp-a)_ ,I am prompted with a "403 Forbidden" message, instead of a login portal. However, If I visit the authelia portal manually _(https://dev.fabrikam.net/auth/)_ and authenticate, then I can reach the application ( _no 403 message_). At the current state, the automatic forward to the login portal is not working for me. 

## LOGS

<details><summary>forwardauth address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fdev.fabrikam.net%2Fauth%2F </summary>
<p>

```
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=trace msg="Headers=GET /api/verify?rd=https%3A%2F%2Fdev.fabrikam.net%2Fauth%2F HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42\r\nHost: authelia:9091\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: en-US,en;q=0.9\r\nCache-Control: max-age=0\r\nCookie: authelia_session=MbXmjmwnC%SJ2rugId9xEHAuhd0BN$Mu\r\nDnt: 1\r\nSec-Ch-Ua: \"Microsoft Edge\";v=\"105\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"105\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Windows\"\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: none\r\nSec-Fetch-User: ?1\r\nUpgrade-Insecure-Requests: 1\r\nX-Forwarded-For: 192.165.0.2\r\nX-Forwarded-Host: dev.fabrikam.net\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: 82f2dd481878\r\nX-Forwarded-Uri: /code-erkerb/login\r\nX-Real-Ip: 192.165.0.2\r\n\r\n" method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=trace msg="Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL" method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=debug msg="Check authorization of subject username= groups= ip=192.165.0.2 and object https://dev.fabrikam.net/code-erkerb/login (method GET)."
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=trace msg="ACL MISS Position 1 for subject username= groups= ip=192.165.0.2 and object https://dev.fabrikam.net/code-erkerb/login (Method GET)"
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=debug msg="No matching rule for subject username= groups= ip=192.165.0.2 and url https://dev.fabrikam.net/code-erkerb/login... Applying default policy."
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=info msg="Access to https://dev.fabrikam.net/code-erkerb/login is forbidden to user " method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.9rsccsfmbs82@node    | time="2022-09-19T14:44:34-04:00" level=trace msg="Replied (status=403)" method=GET path=/api/verify remote_ip=192.165.0.2
```

</p>
</details>

Interestingly, if I use the basic authentication in the middleware, I do not experience the issue: 

```
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?auth=basic"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
```

When i visit the application _(https://dev.fabrikam.net/code-erkerb/)_, I am prompted for authentication. After entering my credentials, the application displays the application without issues.

## LOGS

<details><summary>forwardauth address http://authelia:9091/api/verify?auth=basic</summary>
<p>

```
fe_authelia.1.12df3bhrma37@node    | time="2022-09-19T14:50:31-04:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.12df3bhrma37@node    | time="2022-09-19T14:50:31-04:00" level=trace msg="Headers=GET /api/verify?auth=basic HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42\r\nHost: authelia:9091\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: en-US,en;q=0.9\r\nCookie: authelia_session=MbXmjmwnC%SJ2rugId9xEHAuhd0BN$Mu\r\nDnt: 1\r\nSec-Ch-Ua: \"Microsoft Edge\";v=\"105\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"105\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Windows\"\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: none\r\nSec-Fetch-User: ?1\r\nUpgrade-Insecure-Requests: 1\r\nX-Forwarded-For: 192.165.0.2\r\nX-Forwarded-Host: dev.fabrikam.net\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: 6e4e97f11f46\r\nX-Forwarded-Uri: /code-erkerb/\r\nX-Real-Ip: 192.165.0.2\r\n\r\n" method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.12df3bhrma37@node    | time="2022-09-19T14:50:31-04:00" level=trace msg="Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL" method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.12df3bhrma37@node    | time="2022-09-19T14:50:31-04:00" level=error msg="Error caught when verifying user authorization: basic auth requested via query arg, but no value provided via Authorization header" method=GET path=/api/verify remote_ip=192.165.0.2 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:462 VerifyGET.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54       (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16      SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.12/router.go:414                        (*Router).Handler\ngithub.com/valyala/fasthttp@v1.40.0/http.go:154                         (*Response).StatusCode\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:22   StripPath.func1.1\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2311                      (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:224                   (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:196                   (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                goexit"
fe_authelia.1.12df3bhrma37@node    | time="2022-09-19T14:50:31-04:00" level=info msg="Access to https://dev.fabrikam.net/code-erkerb/ is not authorized to user <anonymous>, sending 401 response with basic auth header" method=GET path=/api/verify remote_ip=192.165.0.2
fe_authelia.1.12df3bhrma37@node    | time="2022-09-19T14:50:31-04:00" level=trace msg="Replied (status=401)" method=GET path=/api/verify remote_ip=192.165.0.2
```

</p>
</details>

I am not sure what I am doing wrong here. 

Here are the snippets in case if you'd like to review my configuration or replicate the behavior: 

## authelia + traefik

<details><summary>docker.compose.yaml</summary>
<p>

```
---                                               
version: "3.9"

secrets:
 JWT_SECRET:
   file: /mnt/cephfs/.frontend/.secrets/.JWT_SECRET
 SESSION_SECRET:
   file: /mnt/cephfs/.frontend/.secrets/.SESSION_SECRET
 STORAGE_ENCRYPTION_KEY:
   file: /mnt/cephfs/.frontend/.secrets/.STORAGE_ENCRYPTION_KEY
 LDAP_PASSWORD:
   file: /mnt/cephfs/.frontend/.secrets/.LDAP_PASSWORD

services:
  authelia:
    image: authelia/authelia:4.36.8
    deploy:
      placement:
        constraints:
          - node.role==manager 
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 96m
        reservations:
          cpus: '0.3'
          memory: 32m
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=backend-dev"
        - "traefik.http.routers.authelia.entrypoints=websecure"
        - "traefik.http.routers.authelia.rule=Host(`dev.fabrikam.net`) && PathPrefix(`/auth`)"
        - "traefik.http.routers.authelia.tls=true"
        - "traefik.http.routers.authelia.service=auth"
        - "traefik.http.services.auth.loadbalancer.server.port=9091"
    volumes:
      - "/mnt/cephfs/.frontend/authelia:/config"
    secrets:
      - JWT_SECRET
      - SESSION_SECRET
      - STORAGE_ENCRYPTION_KEY
      - LDAP_PASSWORD
    environment:
      - TZ=America/New_York
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/JWT_SECRET
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/SESSION_SECRET
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/STORAGE_ENCRYPTION_KEY
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/LDAP_PASSWORD
    networks:
      - backend-dev

  traefik:
    image: traefik:v2.8.5
    read_only: true
    depends_on:
      - authelia
    deploy:
      placement:
        constraints:
          - node.role==manager 
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 96m
        reservations:
          cpus: '0.3'
          memory: 32m
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.rule=Host(`dev.fabrikam.net`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.services.dashboard.loadbalancer.server.port=888"
        - "traefik.docker.network=backend-dev"
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fdev.fabrikam.net%2Fauth%2F"
#        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?auth=basic"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
    command:
#      - "--log.level=DEBUG"
      - "--accesslog"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=tcp://<host-IP>:2376"
      - "--providers.docker.tls.ca=/docker-certs/ca.pem"
      - "--providers.docker.tls.cert=/docker-certs/host-cert.pem"
      - "--providers.docker.tls.key=/docker-certs/host-key.pem"
      - "--providers.docker.network=backend-dev"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/config"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/docker/certs:/docker-certs:ro"
      - "/mnt/cephfs/.frontend/traefik/config:/config:ro"
      - "/mnt/cephfs/.frontend/traefik/certs:/certs:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend-dev

  visualizer:
    image: dockersamples/visualizer:latest
    read_only: true
    environment:
      - "CTX_ROOT=/viz"
    deploy:
      placement:
        constraints:
          - node.role==manager 
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 96m
        reservations:
          cpus: '0.1'
          memory: 32m
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.viz.entrypoints=websecure"
      - "traefik.http.routers.viz.tls=true"
      - "traefik.http.routers.viz.rule=Host(`dev.fabrikam.net`) && PathPrefix(`/viz`)"
      - "traefik.docker.network=backend-dev"
      - "traefik.http.routers.viz.service=viz"
      - "traefik.http.services.viz.loadbalancer.server.port=8080"
      - "traefik.http.routers.viz.middlewares=authelia@docker"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend-dev

networks:
  frontend:
    external: true
    name: frontend
  backend-dev:
    external: true
    name: backend-dev
```
</p>
</details>

## authelia configuration file

<details><summary>configuration.yml</summary>
<p>

```
---
###############################################################
#                   Authelia configuration                    #
###############################################################

default_redirection_url: https://dev.fabrikam.net/auth/

server:
  host: 0.0.0.0
  port: 9091
  path: "auth"  
log:
  level: trace

authentication_backend:
  ldap:
   ...

access_control:
  default_policy: deny
  rules:
    - domain: dev.fabrikam.net
      policy: one_factor
      subject:
        - 'group:testgrp-a'
        - 'group:testgrp-u'
      resources:
      - '^/viz([/?].*)?$'
      - '^/code-(?P<User>\w+)([/?].*)?$'

session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m  
  domain: fabrikam.net

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
```

</p>
</details>

## IDE Example running on a prefix

<details><summary>docker-compose.yaml</summary>
<p>

```
---
    version: "3.9"
    
    services:
      code-erkerb:
        image: codercom/code-server:4.7.0
        user: $(id -u):$(id -g) 
        deploy:
          labels:
          - "traefik.enable=true"
          - "traefik.docker.network=backend-dev"
    
          - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
          - "traefik.http.middlewares.pathstrip-erkerb.stripprefix.prefixes=/code-erkerb"
          - "traefik.http.middlewares.pathstrip-erkerb.stripprefix.forceslash=true"
    
          - "traefik.http.routers.https-user-dev-erkerb.entrypoints=websecure"
          - "traefik.http.routers.https-user-dev-erkerb.tls=true"
          - "traefik.http.routers.https-user-dev-erkerb.rule=Host(`dev.fabrikam.net`) && PathPrefix(`/code-erkerb`)"
          - "traefik.http.routers.https-user-dev-erkerb.service=user-dev-erkerb"
          - "traefik.http.services.user-dev-erkerb.loadbalancer.server.port=8080"
          - "traefik.http.routers.https-user-dev-erkerb.middlewares=authelia@docker,pathstrip-erkerb"
    
        volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "$HOME/project:/home/coder/project"
        - "$HOME/code-config:/home/coder/.config"
        networks:
        - backend-dev
    
    networks:
      backend-dev:
        external: true
        name: backend-dev
```

</p>
</details>
