### DISCUSSION TITLE
Guacamole passthrough authent

### DISCUSSION THREAD

**Discussion by stanthewizzard** [authelia/authelia#4046] [Q&A]
Hello

With
https://www.authelia.com/integration/openid-connect/apache-guacamole/

I'm unable to login via SSO to Guacamole

Help would be appreciated :)
Thanks

**Comment by WindoC** [comment]
Fail too.

Error:
Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.

Seem it is something missing in Guacamole SSO flow?

**Reply by james-d-elliott** [reply]
They don't include the state parameter by default, that's why it's included in the guide as it is. It's a workaround for a badly implemented OIDC Client.

**Reply by WindoC** [reply]
What is the workaround? Modify the code? Can you give me some idea? thanks!

**Reply by james-d-elliott** [reply]
The following config snippet from the above link should be useful: `openid-authorization-endpoint: https://auth.example.com/api/oidc/authorization?state=1234abcedfdhf` as it forcibly includes the state parameter.

**Reply by WindoC** [reply]
Wow, that work! Thanks!

**Reply by stanthewizzard** [reply]
I have this
```
      - id: guacamole
        description: Apache Guacamole
        secret: UY0doeecmXXXXXXXXXWtMMFvHohNNCkeZr7qsIouc
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - https://guacamole.xxxxx.com
        scopes:
          - openid
          - profile
          - groups
          - email
        response_types:
          - id_token
        grant_types:
          - implicit
        userinfo_signing_algorithm: none
```

and this
```
openid-client-id: guacamole
openid-scope: openid profile groups email
openid-issuer: https://auth.xxxx.com
openid-jwks-endpoint: https://auth.xxxx.com/jwks.json
openid-authorization-endpoint: https://auth.xxxx.com/api/oidc/authorization?state=1234abcedfdhf
openid-redirect-uri: https://guacamole.xxxx.com
openid-username-claim-type: preferred_username
openid-groups-claim-type: groups
```

Still no sso
What did I do wrong ?
Thank you
