### DISCUSSION TITLE
policy change not working

### DISCUSSION THREAD

**Discussion by titro** [authelia/authelia#4065] [General]
Hi all,

i make my first experiences with authelia but a very simple scenario is not working:
```

   rules:
    - domain: 'sub1.domain.de'
      policy: two_factor  
    - domain: 'sub2.domain.de'
      policy: one_factor
```

Authelia is asking for a 2nd factor for sub2 in this example. Changes are not considered. I'm running this on docker with redis and restart the whole stack after edit of the configuration.yml

Is the config elsewhere cached or any hints, why it's not working?

Log only writes:
```
time="2022-09-24T10:19:42Z" level=debug msg="Mark 1FA authentication attempt made by user 'authelia'" method=POST path=/api/firstfactor remote_ip=XXX
time="2022-09-24T10:19:42Z" level=debug msg="Successful 1FA authentication attempt made by user 'authelia'" method=POST path=/api/firstfactor remote_ip=XXX
```
