### DISCUSSION TITLE
431 Request Header Fields Too Large

### DISCUSSION THREAD

**Discussion by blakeashleyjr** [authelia/authelia#4086] [Q&A] [answered]
Hello and thanks for an amazing tool!

I am having issues getting Authelia to working with Traefik. It was working for a minute, but I am not sure what changed. It may be a simple configuration error. 

I get a ```431 Request Header Fields Too Large``` whenever I visit any page that should be protected by Authelia. I've tried bumping up the default bumper (4096) to an a much higher numer (over 200,000) and it still errors out.

Version: Authelia v4.36.8

When I check the logs, I see this:

```
level=info msg="Access to https://domain.redacted.com/?rd=https%3A%2F%2Fdomain.redacted.com%2F%3Frd%3Dhttps%253A%252F%252Fdomain.redacted.com%252F%253Frd%253Dhttps%25253A%25252F%25252Fdomain.redacted.com%25252F%25253Frd%25253Dhttps%2525253A%2525252F%2525252Fdomain.redacted.com%2525252F%2525253Frd%2525253Dhttps%252525253A%252525252F%252525252Fdomain.redacted.com%252525252F%252525253Frd%252525253Dhttps%25252525253A%25252525252F%25252525252Fdomain.redacted.com%25252525252F%25252525253Frd%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fdomain.redacted.com%2525252525252F%2525252525253Frd%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fdomain.redacted.com%252525252525252F%252525252525253Frd%252525252525253Dhttps%25252525252525253A%25252525252525252F%25252525252525252Fdomain.redacted.com%25252525252525252F%25252525252525253Frd%25252525252525253Dhttps%2525252525252525253A%2525252525252525252F%2525252525252525252Fdomain.redacted.com%2525252525252525252F%2525252525252525253Frd%2525252525252525253Dhttps%252525252525252525253A%252525252525252525252F%252525252525252525252Fdomain.redacted.com%252525252525252525252F%252525252525252525253Frd%252525252525252525253Dhttps%25252525252525252525253A%25252525252525252525252F%25252525252525252525252Fdomain.redacted.com%25252525252525252525252F%25252525252525252525253Frd%25252525252525252525253Dhttps%2525252525252525252525253A%2525252525252525252525252F%2525252525252525252525252Fdomain.redacted.com%2525252525252525252525252F%2525252525252525252525253Frd%2525252525252525252525253Dhttps%252525252525252525252525253A%252525252525252525252525252F%252525252525252525252525252Fdomain.redacted.com%252525252525252525252525252F%252525252525252525252525253Frd%252525252525252525252525253Dhttps%25252525252525252525252525253A%25252525252525252525252525252F%25252525252525252525252525252Fdomain.redacted.com%25252525252525252525252525252F%25252525252525252525252525253Frd%25252525252525252525252525253Dhttps%2525252525252525252525252525253A%2525252525252525252525252525252F%2525252525252525252525252525252Fdomain.redacted.com%2525252525252525252525252525252F%2525252525252525252525252525253Frd%2525252525252525252525252525253Dhttps%252525252525252525252525252525253A%252525252525252525252525252525252F%252525252525252525252525252525252Fdestination.redacted.com%252525252525252525252525252525252F%25252525252525252525252525252526rm%2525252525252525252525252525253DGET%252525252525252525252525252526rm%25252525252525252525252525253DGET%2525252525252525252525252526rm%252525252525252525252525253DGET%25252525252525252525252526rm%2525252525252525252525253DGET%252525252525252525252526rm%25252525252525252525253DGET%2525252525252525252526rm%252525252525252525253DGET%25252525252525252526rm%2525252525252525253DGET%252525252525252526rm%25252525252525253DGET%2525252525252526rm%252525252525253DGET%25252525252526rm%2525252525253DGET%252525252526rm%25252525253DGET%2525252526rm%252525253DGET%25252526rm%2525253DGET%252526rm%25253DGET%2526rm%253DGET%26rm%3DGET&rm=GET (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://domain.redacted.com/?rd=https%3A%2F%2Fdomain.redacted.com%2F%3Frd%3Dhttps%253A%252F%252Fdomain.redacted.com%252F%253Frd%253Dhttps%25253A%25252F%25252Fdomain.redacted.com%25252F%25253Frd%25253Dhttps%2525253A%2525252F%2525252Fdomain.redacted.com%2525252F%2525253Frd%2525253Dhttps%252525253A%252525252F%252525252Fdomain.redacted.com%252525252F%252525253Frd%252525253Dhttps%25252525253A%25252525252F%25252525252Fdomain.redacted.com%25252525252F%25252525253Frd%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fdomain.redacted.com%2525252525252F%2525252525253Frd%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fdomain.redacted.com%252525252525252F%252525252525253Frd%252525252525253Dhttps%25252525252525253A%25252525252525252F%25252525252525252Fdomain.redacted.com%25252525252525252F%25252525252525253Frd%25252525252525253Dhttps%2525252525252525253A%2525252525252525252F%2525252525252525252Fdomain.redacted.com%2525252525252525252F%2525252525252525253Frd%2525252525252525253Dhttps%252525252525252525253A%252525252525252525252F%252525252525252525252Fdomain.redacted.com%252525252525252525252F%252525252525252525253Frd%252525252525252525253Dhttps%25252525252525252525253A%25252525252525252525252F%25252525252525252525252Fdomain.redacted.com%25252525252525252525252F%25252525252525252525253Frd%25252525252525252525253Dhttps%2525252525252525252525253A%2525252525252525252525252F%2525252525252525252525252Fdomain.redacted.com%2525252525252525252525252F%2525252525252525252525253Frd%2525252525252525252525253Dhttps%252525252525252525252525253A%252525252525252525252525252F%252525252525252525252525252Fdomain.redacted.com%252525252525252525252525252F%252525252525252525252525253Frd%252525252525252525252525253Dhttps%25252525252525252525252525253A%25252525252525252525252525252F%25252525252525252525252525252Fdomain.redacted.com%25252525252525252525252525252F%25252525252525252525252525253Frd%25252525252525252525252525253Dhttps%2525252525252525252525252525253A%2525252525252525252525252525252F%2525252525252525252525252525252Fdomain.redacted.com%2525252525252525252525252525252F%2525252525252525252525252525253Frd%2525252525252525252525252525253Dhttps%252525252525252525252525252525253A%252525252525252525252525252525252F%252525252525252525252525252525252Fdomain.redacted.com%252525252525252525252525252525252F%252525252525252525252525252525253Frd%252525252525252525252525252525253Dhttps%25252525252525252525252525252525253A%25252525252525252525252525252525252F%25252525252525252525252525252525252Fdestination.redacted.com%25252525252525252525252525252525252F%2525252525252525252525252525252526rm%252525252525252525252525252525253DGET%25252525252525252525252525252526rm%2525252525252525252525252525253DGET%252525252525252525252525252526rm%25252525252525252525252525253DGET%2525252525252525252525252526rm%252525252525252525252525253DGET%25252525252525252525252526rm%2525252525252525252525253DGET%252525252525252525252526rm%25252525252525252525253DGET%2525252525252525252526rm%252525252525252525253DGET%25252525252525252526rm%2525252525252525253DGET%252525252525252526rm%25252525252525253DGET%2525252525252526rm%252525252525253DGET%25252525252526rm%2525252525253DGET%252525252526rm%25252525253DGET%2525252526rm%252525253DGET%25252526rm%2525253DGET%252526rm%25253DGET%2526rm%253DGET%26rm%3DGET&rm=GET" method=GET path=/api/verify remote_ip=$IPREDACTED

time="2022-09-26T11:01:26-07:00" level=error msg="Request from client exceeded the server buffer sizes." error="error when reading request headers: small read buffer. Increase ReadBufferSize. Buffer size=4092, contents: \"GET /api/verify?rd=https%3A%2F%2Fdomain.redacted.com%2F HTTP/1.1\\r\\nHost: authelia:9091\\r\\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0\\r\\nAccept: text/html,application/\"...\"52525252525253DGET%252525252525252526rm%25252525252525253DGET%2525252525252526rm%252525252525253DGET%25252525252526rm%2525252525253DGET%252525252526rm%25252525253DGET%2525252526rm%252525253DGET%252525\"" method=GET path=/ remote_ip=$IPREDACTED stack="github.com/authelia/authelia/v4/internal/server/handlers.go:72 handleError.func2\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2800             (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2239             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:224          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:196          (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                       goexit" status_code=431
```

Here is my configuration:

Relevant part of middlewares.yml:
```    middlewares-authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https%3A%2F%2F$DOMAINNAME%2F
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
```
Relevant part of docker-compose.yml
```services:



  ############################# FRONTENDS

  # Traefik 2 - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:latest
    depends_on:
      - authelia
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --providers.file.filename=/rules/middlewares.yml
      - --global.sendAnonymousUsage=false
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.forwardedHeaders.trustedIPs=$CLOUDFLARE_IPS,$LOCAL_IPS
      - --entryPoints.traefik.address=:8080
      # - --entryPoints.ping.address=:8081
      - --api=true
      # - --api.insecure=true
      - --api.dashboard=true
      #- --ping=true
      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.filePath=/logs/traefik.log
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
      - --providers.docker=true
      #- --providers.docker.endpoint=unix:///var/run/docker.sock # Use Docker Socket Proxy instead for improved security
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      # Automatically set Host rule for services
      # - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)
      - --providers.docker.exposedByDefault=false
      - --entrypoints.https.http.middlewares=chain-authelia@file
      - --entrypoints.https.http.tls.options=tls-opts@file
      # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=$DOMAINNAME
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME
      - --entrypoints.https.http.tls.domains[1].main=$HOST.$DOMAINNAME # Pulls main cert for second domain
      - --entrypoints.https.http.tls.domains[1].sans=*.$HOST.$DOMAINNAME # Pulls wildcard cert for second domain
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      # - --providers.file.directory=/rules
      - --providers.file.watch=false # Only works on top level files in the rules folder
      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90 
      # - --metrics.prometheus=true
      # - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
    networks:
      t2_proxy:
         ipv4_address: 192.168.90.254 # You can specify a static IP
      socket_proxy:
    #healthcheck:
    #  test: ["CMD", "traefik", "healthcheck", "--ping"]
    #  interval: 5s
    #  retries: 3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      # - target: 8080 # insecure api wont work
      #   published: 8080
      #   protocol: tcp
      #   mode: host
    volumes:
      - $DOCKERDIR/appdata/traefik2/rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - $DOCKERDIR/appdata/traefik2/acme/acme.json:/acme.json
      - $DOCKERDIR/logs/$HOST/traefik:/logs 
    environment:
      - TZ=$TZ
      # - CF_API_EMAIL_FILE=/run/secrets/cf_email
      # - CF_API_KEY_FILE=/run/secrets/cf_api_key
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
      # - HTPASSWD_FILE=/run/secrets/htpasswd e.
      - DOMAINNAME
      - Host
    # secrets:
    #   - cf_email
    #   - cf_api_key
    #   - htpasswd
    labels:
      #- "autoheal=true"
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$HOST.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" 
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[1].main=$HOST.$DOMAINNAME" 
      - "traefik.http.routers.traefik-rtr.tls.domains[1].sans=*.$HOST.$DOMAINNAME" 
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Healthcheck/ping
      #- "traefik.http.routers.ping.rule=Host(`traefik.$DOMAINNAME`) && Path(`/ping`)"
      #- "traefik.http.routers.ping.tls=true"
      #- "traefik.http.routers.ping.service=ping@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file

  # Authelia
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: always
    depends_on:
      - lldap
    networks:
      t2_proxy:
      ldap:
        ipv4_address: 192.168.92.3
    ports:
      - "127.0.0.1:9091:9091"
    volumes:
      - $DOCKERDIR/appdata/authelia:/config
    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      # - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/authentication_backend_ldap_password
      # - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      # - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      # - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      # - authentication_backend_ldap_password
      # - authelia_storage_mysql_password
      # - authelia_notifier_smtp_password
      # - authelia_duo_api_secret_key
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`auth.$DOMAINNAME`)"
      - "traefik.http.routers.authelia-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
      # - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=http://$DOMAINNAME/"
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2F$DOMAINNAME%2F'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      # - 'traefik.http.middlewares.authelia-basic.forwardAuth.address=http://authelia:9091/api/verify?auth=basic'
      # - 'traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader=true'
      # - 'traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
```

Relevant part of Authelia configuration.yml:

```
server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 4092
    write: 4092

log:
  level: debug

totp:
  issuer: authelia.com
  period: 30
  skew: 1

ntp:
  address: "time.cloudflare.com:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  # file:
  #   path: /config/users_database.yml
  #   password:
  #     algorithm: argon2id
  #     iterations: 1
  #     salt_length: 16
  #     parallelism: 8
  #     memory: 1024 # blocks this much of the RAM. Tune this.
    #Password reset through authelia works normally.
  password_reset:
    disable: false
  # How often authelia should check if there is an user update in LDAP
  refresh_interval: 15s
  ldap:
    implementation: custom
    # Pattern is ldap://HOSTNAME-OR-IP:PORT
    # Normal ldap port is 389, standard in LLDAP is 3890
    url: ldap://192.168.92.2:3890
    # The dial timeout for LDAP.
    timeout: 15s
    # Use StartTLS with the LDAP connection, TLS not supported right now
    start_tls: false
    tls:
      skip_verify: true
      minimum_version: TLS1.2
      # Set base dn, like dc=google,dc.com
    base_dn: dc=REDACTED,dc=REDACTED
    username_attribute: uid
    # You need to set this to ou=people, because all users are stored in this ou!
    additional_users_dn: ou=people
    # To allow sign in both with username and email, one can use a filter like
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: (&({username_attribute}={input})(objectClass=person))
    # Set this to ou=groups, because all groups are stored in this ou
    additional_groups_dn: ou=groups
    # Only this filter is supported right now
    groups_filter: (member={dn})
    # The attribute holding the name of the group.
    group_name_attribute: cn
    # Email attribute
    mail_attribute: mail
    # The attribute holding the display name of the user. This will be used to greet an authenticated user.
    display_name_attribute: displayName
    # The username and password of the admin user.
    # "admin" should be the admin username you set in the LLDAP configuration
    user: uid=REDACTED,ou=people,dc=REDACTED,dc=REDACTED
    # Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    password: REDACTED

access_control:
  default_policy: deny
  rules:
    - domain:
        - "*REDACTED"
        - "REDACTED"
      policy: two_factor
    - domain: auth.REDACTED
      policy: bypass

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: authelia_session_secret_file # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: REDACTED # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: REDACTED
  local:
    path: /config/db.sqlite3
```

I have searched all over and found no issue related to this one (that I can tell.)

Thank you for your help!
