### DISCUSSION TITLE
Authelia with Traefik - Periodical "i/o timeout" errors in log

### DISCUSSION THREAD

**Discussion by stepanov1975** [authelia/authelia#4136] [Q&A] [answered]
Hi,

I have Authelia and Traefik installed in Docker
I am seeing the following errors in the log
What can the problem be?

```
{"error":"read tcp 172.19.0.5:9091-\u003e172.19.0.2:38696: i/o timeout","level":"error","method":"GET","msg":"Request timeout occurred while handling request from client.","path":"/","remote_ip":"172.19.0.2","stack":[{"File":"github.com/authelia/authelia/v4/internal/server/handlers.go","Line":72,"Name":"handleError.func2"},{"File":"github.com/valyala/fasthttp@v1.40.0/server.go","Line":2800,"Name":"(*Server).writeErrorResponse"},{"File":"github.com/valyala/fasthttp@v1.40.0/server.go","Line":2239,"Name":"(*Server).serveConn"},{"File":"github.com/valyala/fasthttp@v1.40.0/workerpool.go","Line":224,"Name":"(*workerPool).workerFunc"},{"File":"github.com/valyala/fasthttp@v1.40.0/workerpool.go","Line":196,"Name":"(*workerPool).getCh.func1"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"status_code":408,"time":"2022-10-05T14:49:40+03:00"}
```
172.19.0.5 - authelia IP
172.19.0.2 - traefik IP
docker-compose
```
version: '3'

services:

########################### Traefik ###########################
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    #sysctls:
    #  - net.core.rmem_max=4194304
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=redacted
      - CF_DNS_API_TOKEN=redacted
      - TZ=Asia/Jerusalem
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker_installs/traefik_authelia/traefik_config:/traefik_config
      - /docker_installs/traefik_authelia/traefik_cert:/traefik_cert
      - /docker_installs/traefik_authelia/traefik_static:/traefik_static:ro
      - /docker_installs/traefik_authelia/traefik_logs:/logs
    command:
      - --configFile=/traefik_static/traefik.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.rule=Host(`traefik-dashboard.edited.work`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=redacted"

#################################### Authelia ####################################
  authelia:
    image: authelia/authelia
    container_name: authelia
    security_opt:
      - no-new-privileges:true
    depends_on:
      - traefik
      - redis
    volumes:
      - /docker_installs/traefik_authelia/authelia_config:/config
      - /docker_installs/traefik_authelia/authelia_logs:/logs
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.edited.work`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.middlewares=default-headers@file'
    restart: unless-stopped
    environment:
      - TZ=Asia/Jerusalem
    healthcheck:
      disable: false
#################### Rsdis foe Authelia ################################
  redis:
    image: redis:alpine
    container_name: authelia_redis
    security_opt:
      - no-new-privileges:true
    volumes:
      - /docker_installs/traefik_authelia/authelia_redis:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Asia/Jerusalem
    command: redis-server --appendonly yes

#Networks
networks:
  default:
    enable_ipv6: false
```

**Comment by james-d-elliott** [comment, marked as answer]
Try adjusting the authelia server timeout values.

**Reply by stepanov1975** [reply]
> Try adjusting the authelia server timeout values.

@james-d-elliott 
Thank you for the replay. Which one?

**Reply by james-d-elliott** [reply]
read and write, we're increasing the default to 6s for both in the next  release

**Reply by Quiksmage** [reply]
Hi, I'm having what I think is this same issue. I've set my read/write timeouts to the following, but it didn't seem to help. Is there anything else I should try or do you need my full configuration? 

```
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  ## Server Timeouts
  timeouts:
     read: 15s
     write: 15s
     idle: 30s
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
```

`time="2023-01-26T00:03:05-08:00" level=error msg="Request timeout occurred while handling request from client." error="read tcp 172.18.0.30:9091->172.18.0.4:51214: i/o timeout" method=GET path=/ remote_ip=172.18.0.4 stack="github.com/authelia/authelia/v4/internal/server/handlers.go:71 handleError.func2\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2824             (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2266             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196          (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                       goexit" status_code=408`
