### DISCUSSION TITLE
how to configure oidc for sftpgo?

### DISCUSSION THREAD

**Discussion by abe520** [authelia/authelia#4150] [Q&A] [answered]
how to configure oidc for sftpgo(admin)?

**Comment by james-d-elliott** [comment]
Post the authelia config and sftpgo config you've used and the issue you're having including logs from both sftpgo and authelia.

**Reply by abe520** [reply]
> 发布您使用的 authelia 配置和 sftpgo 配置以及您遇到的问题，包括来自 sftpgo 和 authelia 的日志。
sftpgo log
````

{"level":"info","time":"2022-10-10T00:45:53.517","sender":"httpd","local_addr":"192.168.19.12:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.1.11:42372","request_id":"20b4daf65651/54IjRiA4x3-000001","uri":"http://sftpgo.33.me/web/admin/login","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","resp_status":200,"resp_size":5810,"elapsed_ms":1}
{"level":"info","time":"2022-10-10T00:45:54.739","sender":"httpd","local_addr":"192.168.19.12:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.1.11:42372","request_id":"20b4daf65651/54IjRiA4x3-000002","uri":"http://sftpgo.33.me/web/admin/oidclogin","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","resp_status":302,"resp_size":279,"elapsed_ms":0}
````
authelia log
````
timeout","level":"error","method":"GET","msg":"Request timeout occurred while handling request from client.","path":"/","remote_ip":"192.168.1.11","stack":[{"File":"github.com/authelia/authelia/v4/internal/server/handlers.go","Line":72,"Name":"handleError.func2"},{"File":"github.com/valyala/fasthttp@v1.39.0/server.go","Line":2794,"Name":"(*Server).writeErrorResponse"},{"File":"github.com/valyala/fasthttp@v1.39.0/server.go","Line":2233,"Name":"(*Server).serveConn"},{"File":"github.com/valyala/fasthttp@v1.39.0/workerpool.go","Line":224,"Name":"(*workerPool).workerFunc"},{"File":"github.com/valyala/fasthttp@v1.39.0/workerpool.go","Line":196,"Name":"(*workerPool).getCh.func1"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"status_code":408,"time":"2022-10-10T00:46:09+08:00"}
{"error":"read tcp 192.168.19.7:9091-\u003e192.168.1.11:36224: i/o timeout","level":"error","method":"GET","msg":"Request timeout occurred while handling request from client.","path":"/","remote_ip":"192.168.1.11","stack":[{"File":"github.com/authelia/authelia/v4/internal/server/handlers.go","Line":72,"Name":"handleError.func2"},{"File":"github.com/valyala/fasthttp@v1.39.0/server.go","Line":2794,"Name":"(*Server).writeErrorResponse"},{"File":"github.com/valyala/fasthttp@v1.39.0/server.go","Line":2233,"Name":"(*Server).serveConn"},{"File":"github.com/valyala/fasthttp@v1.39.0/workerpool.go","Line":224,"Name":"(*workerPool).workerFunc"},{"File":"github.com/valyala/fasthttp@v1.39.0/workerpool.go","Line":196,"Name":"(*workerPool).getCh.func1"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"status_code":408,"time":"2022-10-10T00:48:25+08:00"}
````
sftpgo config
````
        "oidc": {
          "client_id": "sftpgo",
          "client_secret": "bjjNiw122nBfYtA4PMy9e3TcxJja2uiN",
          "config_url": "https://authelia.33.me",
          "redirect_base_url": "https://sftpgo.33.me",
          "scopes": [
            "openid",
            "profile",
            "email"
          ],
          "username_field": "preferred_username",
          "role_field": "admin",
          "implicit_roles": false,
          "custom_fields": []
        },
````
authelia config
````
      - id: sftpgo
        description: sftpgo
        secret: bjjNiw122nBfYtA4PMy9e3TcxJja2uiN
        public: false
        authorization_policy: one_factor
        audience: []
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://sftpgo.33.me/web/oidc/redirect
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
````
I can't use sftpgo through oidc
