### DISCUSSION TITLE
Synology DSM (and apps) with Authelia

### DISCUSSION THREAD

**Discussion by helmut72** [authelia/authelia#4160] [Show and tell]
If someone also need this setup. This example makes the following assumptions:

```
Synology Root URL: https://dsm.example.com
Authelia Root URL: https://auth.example.com
Client ID: diskstation
Client Secret: diskstation_client_secret
```

In DSM go to Control Panel -> Domain/LDAP -> SSO-Client. Enable OpenID Connect SSO service and use these settings:

```
Profile: OIDC
Name: Authelia (or anything else, it's just the non-technical display name)
Wellknown URL: https://auth.example.com/.well-known/openid-configuration
Application ID: diskstation
Application key: diskstation_client_secret
Redirect URL: https://dsm.example.com
Authorization Scope: openid profile groups email
Username claim: preferred_username
```

In Authelia use this configuration:

```
      - id: diskstation
        description: Diskstation
        secret: diskstation_client_secret
        public: false
        authorization_policy: one_factor
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://dsm.example.com
```

Both, Synology DSM and Authelia runs behind a reverse proxy. Synology DSM is connected to the same LDAP server that also Authelia use. I think my biggest mistake was an empty Authorization Scope field in DSM.
