### DISCUSSION TITLE
Need help troubleshooting login errors

### DISCUSSION THREAD

**Discussion by CVJoint** [authelia/authelia#4195] [Q&A]
I've been using Authelia + Traefik for a while, but have recently run into some issues that are difficult to troubleshoot.

When trying to log in, I frequently see one of these issues:
 - "There was an issue retrieving user preferences"
 - "There was an issue retrieving global configuration"

I've tried various configurations, but can't seem to get consistent results. Sometimes when I have my access_control set to one_factor I'm able to be redirected successfully, but the cookie is not saved or something and I will need to log in again, sometimes I have to try logging in two times in a row as it doesn't recognize me.

In my latest attempt, looking at the logs, I see that it calls my user "anonymous":

```
time="2022-09-10T09:50:58-04:00" level=info msg="Access to https://destination.domain.com/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://authelia.domain.com?rd=https%3A%2F%2Fdestination.domain.com%2F&rm=GET" method=GET path=/api/verify remote_ip=my ip
time="2022-09-10T09:51:11-04:00" level=warning msg="https://destination.domain.com/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=my ip
```

I've tried to search for what could cause these errors but haven't found any references. I have the same trouble in the firefox and chrome browsers, and on both windows and mac PCs at various locations. Any help would be appreciated.

Here's my configuration.yml:

```yaml
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################
theme: dark
jwt_secret: my_secret
default_redirection_url: https://authelia.domain.com
default_2fa_method: "mobile_push"
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
log:
  level: info
totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: false
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
duo_api:
  disable: false
  hostname: api-hostname.duosecurity.com
  integration_key: my_key
  secret_key: my_secret
  enable_self_enrollment: false
ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3
access_control:
  default_policy: deny
  rules:
    - domain: authelia.domain.com
      policy: bypass
    - domain: "*.domain.com"
      policy: two_factor
      subject: "group:admins"
session:
  name: authelia_session
  domain: domain.com
  same_site: none
  secret: my_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
 redis:
    host: redis
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: 64_char_string
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  smtp:
    host: smtp.gmail.com
    port: 587
    timeout: 5s
    username: my_user@gmail.com
    password: my_pass
    sender: "Authelia <my_e-mail>"
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
```
