### DISCUSSION TITLE
Configuration.yml for authelia 4.37

### DISCUSSION THREAD

**Discussion by Alderaaan** [authelia/authelia#4317] [Q&A] [answered]
Hi,
I tried to upgrade my authelia from 4.23 to 4.33 and I'm blocked with the database configuration.
I made some changes on the configuration file to correspond with the news fonctions of 4.33, but the storage seem to be a problem.
```yaml
storage:
  encryption_key: xxx
  postgres:
    host: authalie-db
    port: 5432
    database: authelia
    username: authelia
    password: authelia
```
And the logs are 
```
time="2022-11-02T00:30:28Z" level=error msg="Configuration: storage: mysql: 'host' configuration option must be provided"
time="2022-11-02T00:30:28Z" level=error msg="Configuration: storage: mysql: 'username' and 'password' configuration options must be provided"
time="2022-11-02T00:30:28Z" level=error msg="Configuration: storage: mysql: 'database' configuration option must be provided"
time="2022-11-02T00:30:28Z" level=error msg="Configuration: storage: 'encryption_key' configuration option must be provided"
time="2022-11-02T00:30:28Z" level=fatal msg="Can't continue due to the errors loading the configuration"
```
Any ideas ?
Tks for the help.

**Comment by james-d-elliott** [comment, marked as answer]
Show your environment variables, and show your config properly quoted as code using the ` character like this:

![image](https://user-images.githubusercontent.com/3903683/199386939-da15447e-b7ce-4250-86cc-9d518c57319e.png)

Which will output similar to this:

```yaml
storage:
  encryption_key: ....
```

Additionally here is the commented examples relevant to your issue:
- https://github.com/authelia/authelia/blob/master/config.template.yml#L860-L867
- https://github.com/authelia/authelia/blob/master/config.template.yml#L986-L1090

Which would become (note commented config options start with `# ` or a hash followed by one space which you must remove both the hash and the extra space, a `## ` indicates that line is a comment inside the configuration itself):

```yaml
##
## Storage Provider Configuration
##
## The available providers are: `local`, `mysql`, `postgres`. You must use one and only one of these providers.
storage:
  ## The encryption key that is used to encrypt sensitive information in the database. Must be a string with a minimum
  ## length of 20. Please see the docs if you configure this with an undesirable key and need to change it.
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  postgres:
    host: 127.0.0.1
    port: 5432
    database: authelia
    schema: public
    username: authelia
    ## Password can also be set using a secret: https://www.authelia.com/c/secrets
    password: mypassword
    timeout: 5s
```

**Reply by Alderaaan** [reply]
hi,
Tks for the links. I was already seem the examples, and same issue...
I changed the title, because is not 4.33, but 4.37.

I copy / past the code, but same error.
```
time="2022-11-02T14:46:27Z" level=error msg="Configuration: storage: mysql: option 'host' is required"
time="2022-11-02T14:46:27Z" level=error msg="Configuration: storage: mysql: option 'username' and 'password' are required"
time="2022-11-02T14:46:27Z" level=error msg="Configuration: storage: mysql: option 'database' is required"
time="2022-11-02T14:46:27Z" level=fatal msg="Can't continue due to the errors loading the configuration"
```
I don't understand where is the problem...

```yaml
###############################################################
#                   Authelia configuration #
###############################################################
theme: light
default_redirection_url: https://authelia.xxx

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# I used this site to generate the secret: https://www.grc.com/passwords.htm
# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
#default_redirection_url: https://authelia.alderaan.ovh

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
duo_api:
  hostname: api-xxx.duosecurity.com
  integration_key: xxx
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE

## The available providers are: `file`, `ldap`. You must use only one of these providers.
authentication_backend:

  ## Password Reset Options.
  password_reset:
    ## Disable both the HTML element and the API for reset password functionality.
    disable: false
  refresh_interval: 5m
#  ldap:
#    implementation: activedirectory
#    url: ldap://192/168.3.53
#    start_tls: false
#    tls:
#      skip_verify: true
#      minimum_version: TLS1.2
#    base_dn: dc=ldap,dc=xxx,dc=xxx
#    additional_users_dn: ou=users
#    users_filter: (&({username_attribute}={input})(objectClass=person))
#    additional_groups_dn: ou=users
#    groups_filter: (&(member={dn})(objectclass=groupOfNames))
#    user: cn=admin,dc=ldap,dc=alderaan,dc=ovh
#    password: 

  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: sha512
      iterations: 1000
      salt_length: 16
      parallelism: 8
      memory: 128 # blocks this much of the RAM. Tune this.

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
#  networks:
#    - name: internal
#      networks:
#        - 192.168.3.0/24

  rules:
    - domain: authelia.xxx
      policy: bypass

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Used a different secret, but the same site as jwt_secret above.
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: xxx # Should match whatever your root protected domain is

# Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
#  redis:
#    host: redis
#    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  ## The encryption key that is used to encrypt sensitive information in the database. Must be a string with a minimum
  ## length of 20. Please see the docs if you configure this with an undesirable key and need to change it.
  encryption_key: xxx
  postgres:
    host: authelia-db
    port: 5432
    database: authelia
    schema: public
    username: authelia
    ## Password can also be set using a secret: https://www.authelia.com/c/secrets
    password: authelia
    timeout: 5s

notifier:
  smtp:
    username: xxx
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: smtp.xxx
    port: 587 #465
    disable_require_tls: true
    sender: xxx
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
  #filesystem:
  #  filename: /config/notification.txt
```

**Reply by james-d-elliott** [reply]
Where are your environment variables?

**Reply by Alderaaan** [reply]
I deploy my docker with ~/docker/docker-compose.yml
I use some env variables, but only for the clock

```
  authelia-db:
    image: postgres:12
    container_name: authelia-db
    networks:
      - proxy

    environment:
      POSTGRES_DB: authelia
      POSTGRES_PASSWORD: '/run/secrets/authelia_storage_mysql_password'
      POSTGRES_USER: authelia

    restart: unless-stopped
    ports:
      - "5438:5432"
    volumes:
      - authelia-db:/var/lib/postgresql/data
    secrets:
      - authelia_storage_mysql_password

  authelia:
    image: authelia/authelia:4.37
    container_name: authelia
    volumes:
      - /home/pi/docker/authelia:/config

    depends_on:
      - authelia-db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.xxx`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - "traefik.http.routers.authelia.middlewares=chain-authelia@file"
#      - "traefik.http.routers.authelia.service=authelia"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"

    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key

    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
```
