### DISCUSSION TITLE
Simple Bypass Rules Not Working

### DISCUSSION THREAD

**Discussion by blakeashleyjr** [authelia/authelia#4388] [Q&A] [answered]
Hello!

I am going crazy staring at a few lines of my Authelia config:

```
access_control:
  default_policy: deny
  rules:
    - domain: subdomain.example.com
      policy: bypass
```

I still get redirected to login. Any ideas?

Here are the logs:

```
time="2022-11-15T10:22:43-08:00" level=info msg="Access to https://subdomain.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.example.com/?rd=https%3A%2F%2Fsubdomain.example.com%2F&rm=GET" method=GET path=/api/verify remote_ip=111.111.111.111
```
