### DISCUSSION TITLE
Changing exposed port in Docker but `9091` remains exposed

### DISCUSSION THREAD

**Discussion by natelandau** [authelia/authelia#4412] [Q&A] [answered]
Authelia is amazing. I've spent the better part of two days trying to troubleshoot an issue.  I know I'm straying from the conventional use-case, but I hope someone here can point me in the right direction.

I am attempting to run two instances of Authelia on the same machine via Docker Compose. Until [multi-domains are supported](https://www.authelia.com/roadmap/active/multi-domain-protection/) this is the best way I could think of to have a single instance of Traefik with two FQDNs run with Authelia protection.

In the first instance (`authelia_one`) I expose port `9091` and it works fine
In the second instance (`authelia_two`) I expose port `9092` and it won't start b/c somehow it's still trying to expose port `9091`

How can I fix this problem?  Or, is there a better way to have Authelia manage two FQDNs on the same Traefik instance?

My compose file has the following:

```yaml
    authelia_one:
        restart: unless-stopped
        container_name: "authelia_one"
        image: "authelia/authelia:latest"
        env_file: .env
        environment:
           ...
        command:
            - "authelia"
            - "--config=/config/config.yml"
        expose:
            - 9091
        volumes:
            ...
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.authelia_one.rule=Host(`auth.{{ domain_name_one }}`)"
            - "traefik.http.routers.authelia_one.entrypoints=web,websecure"
            - "traefik.http.routers.authelia_one.tls.certresolver=letsencrypt"

    authelia_two:
        restart: unless-stopped
        container_name: "authelia_two"
        image: "authelia/authelia:latest"
        env_file: .env
        environment:
           ...
        command:
            - "authelia"
            - "--config=/config/config.yml"
        expose:
            - 9092
        volumes:
            ...
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.authelia_one.rule=Host(`auth.{{ domain_name_two }}`)"
            - "traefik.http.routers.authelia_one.entrypoints=web,websecure"
            - "traefik.http.routers.authelia_one.tls.certresolver=letsencrypt"
````

and my config files for each version show different ports

```yaml
# authelia_one
server:
    host: 0.0.0.0
    port: 9091

#authelia_two
server:
    host: 0.0.0.0
    port: 9092
```

When I run both containers, authelia_one starts without a problem.  authelia_two, on the other hand, won't start.  Docker gives me this error: `Error response from daemon: Address already in use`

When I run `docker compose inspect authelia_two` I see the following.  Note that `9091` is exposed along with `9092` even though I clearly specified only `9092` in the compose file.

```json
  "Config": {
    "Hostname": "866f616fe577",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": true,
    "AttachStderr": true,
    "ExposedPorts": {
      "9091/tcp": {},
      "9092/tcp": {}
```

**Comment by james-d-elliott** [comment, marked as answer]
We embed an expose inside the container itself (in the Dockerfile) on port 9091. So that one will always be present.

> In the second instance (authelia_two) I expose port 9092 and it won't start b/c somehow it's still trying to expose port 9091

I don't see that being possible. Can you show authelia logs via `docker logs -f authelia_two` which back this up?

> I am attempting to run two instances of Authelia on the same machine via Docker Compose. Until [multi-domains are supported](https://www.authelia.com/roadmap/active/multi-domain-protection/) this is the best way I could think of to have a single instance of Traefik with two FQDNs run with Authelia protection.

This does not explain why you'd use separate ports honestly. You can just use the same port unless I'm missing something.

**Comment by natelandau** [comment]
Thanks for your reply.  I can't post docker logs because the container never runs and no logs are generated.  Here is the response when trying to start the container

```
❯ sudo docker compose up authelia_two
[+] Running 1/0
 ⠿ Container traefik  Running                                                                                                                                                       0.0s
Attaching to authelia_two
Error response from daemon: Address already in use
```

From my understanding, this error `Error response from daemon: Address already in use` is Docker's way of keeping two containers from starting which would both use the same port on the host. 

Why embed the EXPOSE for port 9091 in the container itself when that can easily be specified in a docker-compose.yml file or on the command line?  Not arguing with the practice, just hoping to learn.

thanks again.

**Reply by natelandau** [reply]
realized I never responded directly to the question of why not just have them point to the same port.

Two reasons (given my limited understanding)

1. Docker won't start two containers which map the same port
2. The Traefik Middleware specifies a port. Perhaps I'm just following a bad example here and don't need the port.

```yaml
        mw-authelia-one:
            forwardAuth:
                address: "http://authelia_one:9091/api/verify?rd=https%3A%2F%2Fauth.{{ domain_name_one }}%2F"
                trustForwardHeader: true
                authResponseHeaders:
                    - "Remote-User"
                    - "Remote-Groups"
                    - "Remote-Email"
                    - "Remote-Name"

        mw-authelia-two:
            forwardAuth:
                address: "http://authelia_two:9092/api/verify?rd=https%3A%2F%2Fauth.{{ domain_name_two }}%2F"
                trustForwardHeader: true
                authResponseHeaders:
                    - "Remote-User"
                    - "Remote-Groups"
                    - "Remote-Email"
                    - "Remote-Name"
```

**Reply by james-d-elliott** [reply]
> Thanks for your reply. I can't post docker logs because the container never runs and no logs are generated. Here is the response when trying to start the container

So you change the port to `9092` and docker complains that the port is already in use? I can't replicate this.

```yaml
  authelia:
    container_name: authelia
    image: ${AUTHELIA_REGISTRY:-docker.io}/${AUTHELIA_IMAGE:-authelia/authelia}${AUTHELIA_TAG:-:master}
    restart: unless-stopped
    networks:
      net:
        aliases:
          - "authelia.internal"
    expose:
      - 9092
    environment:
      TZ: "${TZ}"
      AUTHELIA_SERVER_PORT: 9092
    volumes:
      - ${PWD}/data/authelia/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.test.example.com`)"
      - "traefik.http.routers.auth.entryPoints=websecure"
      - "traefik.http.routers.auth.tls=true"
```

> Why embed the EXPOSE for port 9091 in the container itself when that can easily be specified in a docker-compose.yml file or on the command line? Not arguing with the practice, just hoping to learn.

Standard practice. It communicates to services like traefik that the port is being listened on. This allows users to configure the container much more easily. As there is very little benefit to removing it and removing it would be a breaking change it's unlikely we will anytime soon.

> Docker won't start two containers which map the same port

It will. Each container is a unique host. Unless you're using host networking or maybe macvlan. Just use bridge networking. 

> The Traefik Middleware specifies a port. Perhaps I'm just following a bad example here and don't need the port.

You can use the same port for both. Since you're doing internal docker networking traefik can communicate with multiple containers on the  same port since internally they're separate IP addresses. 

> Attaching to authelia_two
> Error response from daemon: Address already in use

As far as I am aware this is a docker error and effectively is not an error that we could possibly cause (even intentionally). However I could be wrong.
