### DISCUSSION TITLE
Authelia pod keeps crashing because of failed storage migration

### DISCUSSION THREAD

**Discussion by slax81** [authelia/authelia#4421] [Q&A] [answered]
### Version

v4.37.0

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.8.0

### Description

On node reboot, authelia pod keeps crashing - won't start anymore because of failed storage migration. It stops because some webauthn backup db table already exists, but I don't even have webauthn setup. Using internal file base sqllite user database.

### Reproduction

Kubernetes node was rebooted

### Expectations

Deployment should continue running normally as when deployed

### Configuration (Authelia)

```yaml
---
theme: light
default_redirection_url: https://mydomain.com
default_2fa_method: ''
server:
  host: 0.0.0.0
  port: 9091
  asset_path: ''
  headers:
    csp_template: ''
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: 6s
    write: 6s
    idle: 30s
  enable_pprof: false
  enable_expvars: false
log:
  level: info
  format: text
  file_path: ''
  keep_stdout: true
totp:
  disable: true
  issuer: myissuer
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: true
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s
ntp:
  address: time.cloudflare.com:1234
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  file:
    path: /config/users_database.yml
    watch: true
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16
      scrypt:
        iterations: 16
        block_size: 8
        parallelism: 1
        key_length: 32
        salt_length: 16
      pbkdf2:
        variant: 'sha512'
        iterations: 310000
        salt_length: 16
      sha2crypt:
        variant: 'sha512'
        iterations: '50000'
        salt_length: 16
      bcrypt:
        variant: 'standard'
        cost: 12
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: 'authelia_session'
  domain: 'mydomain.com'
  same_site: 'lax'
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
regulation: 
  ban_time: 5m
  find_time: 2m
  max_retries: 3
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
access_control:
  default_policy: one_factor
...
```

### Logs (Authelia)

```shell
time="2022-11-22T14:14:39Z" level=info msg="Authelia v4.37.0 is starting"
time="2022-11-22T14:14:39Z" level=info msg="Log severity set to info"
time="2022-11-22T14:14:39Z" level=info msg="Storage schema is being checked for updates"
time="2022-11-22T14:14:39Z" level=info msg="Storage schema migration from 1 to 6 is being attempted"
time="2022-11-22T14:14:39Z" level=error msg="Failure running the storage provider startup check: error during schema migrate: error applying migration version 2 to version 1 for rollback: schema migration 2 (Webauthn) failed: there is already another table or index with this name: _bkp_DOWN_V0002_totp_configurations. rollback caused by: schema migration 2 (Webauthn) failed: there is already another table or index with this name: _bkp_UP_V0002_totp_configurations" stack="github.com/authelia/authelia/v4/internal/commands/root.go:277 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.0/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.0/command.go:1040                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.0/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
time="2022-11-22T14:14:39Z" level=fatal msg="The following providers had fatal failures during startup: storage" stack="github.com/authelia/authelia/v4/internal/commands/root.go:305 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.0/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.0/command.go:1040                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.0/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
time="2022-11-22T14:19:48Z" level=warning msg="Configuration: access control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
