### DISCUSSION TITLE
Redirection URL is not safe

### DISCUSSION THREAD

**Discussion by derzico** [authelia/authelia#4574] [Q&A] [answered]
Hey there,

I want to use NGINX with authelia.
I have set everything up and can connect to the auth portal.
But if I want to login, I will not be redirected.

`level=debug msg="Redirection URL https://xxx.de/ is not safe"`

My auth nginx site is like this:

```
server {
    listen 80;
    server_name auth.xxx.de;

    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name auth.xxx.de;

    ssl_certificate /etc/letsencrypt/live/auth.xxx.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/auth.xxx.de/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    set $upstream http://127.0.0.1:9091;

    location / {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass $upstream;
    }

    location /api/verify {
        proxy_pass $upstream;
    }
}

```
And for my site, which i want to access the nginx config is like that:

```
server {
    listen 80;
    server_name public.xxx.de;

    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name public.xxx.de;

    ssl_certificate /etc/letsencrypt/live/public.xxx.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/public.xxx.de/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;

    include /etc/nginx/snippets/authelia-location.conf;

    set $upstream http://127.0.0.1:8087;

    location / {
        include /etc/nginx/snippets/proxy.conf;
        include /etc/nginx/snippets/authelia-authrequest.conf;
        proxy_pass $upstream;
    }
}
```

Authelia config is like this:

```
---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: xxx
default_redirection_url: https://auth.xxx.de

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE

totp:
  issuer: authelia.com

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: auth.xxx.de
      policy: bypass
    - domain: public.xxx.de
      policy: one_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: xxx
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

  #  redis:
     # host: localhost
     # port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: xxx
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    # username: test
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: password
    host: 192.168.2.17
    port: 25
    sender: auth@xxx.de
    disable_require_tls: true

...
```

Authelia is installed via a Docker container and the port has been made public, nginx is installed via apt package.
It would be really kind, if you could help me :)

**Comment by james-d-elliott** [comment, marked as answer]
```
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: xxx
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is
```

Fix the domain here, needs to be xxx.de
