### DISCUSSION TITLE
Weird Authentication Loop

### DISCUSSION THREAD

**Discussion by wisbit** [authelia/authelia#4591] [Q&A] [answered]
Hi all,

I have been having issues recently to access a server behind authelia.
There is only one user defined. 
I am absolutely sure of the password.

If I setup a 2FA policy, this is what I get:
```
time="2022-12-16T21:09:49+01:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:port"
time="2022-12-16T21:09:58+01:00" level=debug msg="Credentials validation of user "user" is ok" method=POST path=/api/firstfactor remote_ip=12.34.56.78
time="2022-12-16T21:09:58+01:00" level=debug msg="Mark authentication attempt made by user "user" " method=POST path=/api/firstfactor remote_ip=12.34.56.78
time="2022-12-16T21:09:58+01:00" level=debug msg="Required level for the URL https://sub.domain.com/ is 2" method=POST path=/api/firstfactor remote_ip=12.34.56.78
time="2022-12-16T21:09:58+01:00" level=warning msg="https://sub.domain.com/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=12.34.56.78
```
In effect the login screen is refreshed, url : authelia.mydomain.com/?rd=https%3A%2F%2Fmysub.mydomain.com%2F
If I setup a 1FA I get this:
```
time="2022-12-16T21:09:49+01:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:port"
time="2022-12-16T21:09:58+01:00" level=debug msg="Credentials validation of user "user" is ok" method=POST path=/api/firstfactor remote_ip=12.34.56.78
time="2022-12-16T21:09:58+01:00" level=debug msg="Mark authentication attempt made by user "user" " method=POST path=/api/firstfactor remote_ip=12.34.56.78
time="2022-12-16T21:32:13+01:00" level=debug msg="Required level for the URL https://mysub.mydomain.com/ is 1" method=POST path=/api/firstfactor remote_ip=12.34.56.78
time="2022-12-16T21:32:13+01:00" level=debug msg="Redirection URL https://mysub.mydomain.com/ is safe" method=POST path=/api/firstfactor remote_ip=12.34.56.78
time="2022-12-16T21:32:14+01:00" level=info msg="Access to https://mysub.mydomain.com/ is not authorized to user , redirecting to https://authelia.mydomain.com?rd=https%3A%2F%2Fmysub.mydomain.comg%2F" method=GET path=/api/verify remote_ip=12.34.56.78
```
in effect, it redirects to authelia.mydomain.com

And this is my configuration:
```
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug

default_redirection_url: https://authelia.mydomain.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

duo_api:
  hostname: api-123456789.duosecurity.com
  integration_key: ABABABABABBABABABABABBABABA
  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
  # secret_key: SECRET_KEY_GOES_HERE # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE


authentication_backend:
  file:
    #disable_reset_password: true
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

access_control:
  default_policy: deny
  rules:
    - domain: authelia.mydomain.com
      policy: bypass
    - domain:
        - "*.mydomain.com"
        - "mydomain.com"
      policy: one_factor     /*or two_factor*/
    - domain:
        - "*.mydomain.com"
        - "mydomain.com"
      policy: bypass
      networks:
        - localsubnet/24
        - wansubnet/24
        - serversubnet/24

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: mydomain.com # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: email_adress
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: PASSWORD_GOES_HERE # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: email_domain
    port: 587 # Or 465
    sender: email_adress

  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
#  filesystem:
#    filename: /config/notification.txt
```

I would love to have some pointers into solving this thing.
Cheers.

W.
