### DISCUSSION TITLE
Big mess after update - Fatal failure / storage

### DISCUSSION THREAD

**Discussion by wisbit** [authelia/authelia#4593] [Q&A] [answered]
Hi all,

I was on version 4.21.0 and I had an issue logging in, i was being looped to the logging screen. In any case after updating, I can't even display the login page. 
I got error messages saying that lots of elements of my configuration were deprecated. I tried to fix things but so far it's not working.
I also had to change the CMOS battery.

This is the Authelia log:
```
time="2022-12-18T10:22:17+01:00" level=fatal msg="The following providers had fatal failures during startup: storage" stack="github.com/authelia/authelia/v4/internal/commands/root.go:309 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                 

(*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
```

That's all I get. And browser side, nothing loads. from wan or lan.

And this is my configuration
```
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
# port: 9091      ---- DEPRECATED
#  log_level: debug ----- DEPRECATED

server:
  port: 9091
log:
  level: debug

default_redirection_url: https://authelia.mydomain.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

duo_api:
  hostname: api-123456789.duosecurity.com
  integration_key: ABABABABABBABABABABABBABABA
  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
  # secret_key: SECRET_KEY_GOES_HERE # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE


authentication_backend:
  file:
    #disable_reset_password: true
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

# ADDED THIS FROM AUTHELIA WEBSITE TO TRY FIXING NTP ISSUE
ntp:
  address: "time.cloudflare.com:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false



access_control:
  default_policy: deny
  rules:
    - domain: authelia.mydomain.com
      policy: bypass
    - domain:
        - "*.mydomain.com"
        - "mydomain.com"
      policy: one_factor     /*or two_factor*/
    - domain:
        - "*.mydomain.com"
        - "mydomain.com"
      policy: bypass
      networks:
        - localsubnet/24
        - wansubnet/24
        - serversubnet/24

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: mydomain.com # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
    encryption_key: AUTHELIA_STORAGE_ENCRYPTION_KEY    # ADDED THIS BECAUSE LOG SAID IT WAS COMPULSORY
    local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: email_adress
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: PASSWORD_GOES_HERE # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: email_domain
    port: 587 # Or 465
    sender: email_adress

  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
#  filesystem:
#    filename: /config/notification.txt
```

I just can't figure out what to do next.
Cheers for any help.
