### DISCUSSION TITLE
Access Control

### DISCUSSION THREAD

**Discussion by wisbit** [authelia/authelia#4594] [Q&A] [answered]
Would someone be ok to spend a minute explaining me this section that I find confusing.

```
access_control:
  default_policy: deny
  rules:
    - domain: authelia.mydomain.com
      policy: bypass
    - domain:
        - "*.mydomain.com"
        - "mydomain.com"
      policy: two_factor
    - domain:
        - "*.mydomain.com"
        - "mydomain.com"
      policy: bypass
      networks:
        - home_subnet/24
        - wan_subnet/24
        - Home_router_tun0_subnet/24
```

So the way I understand this is the following.
1. check if access request comes from "authelia.mydomain.org", in that case, move on, no check.
2. check if access request comes from either mydomain.com or any sub.mydomain.com, in that case ==> 2FA
3. check if access request comes from ... well and that's where I am confused ... same dom/subdom, and check on IP subnet, in that case ==> bypass... 

is there a reason in the third policy that the actual policy (bypass) is located between the domain segment and networks segments ? 

It's working and does the job... I think, because if I access from local network I still get to go through authentication
but, is it properly done ? Am I missing something ?

Cheers for any info.
