### DISCUSSION TITLE
Is it technically possible to protect a single port at LAN-level?

### DISCUSSION THREAD

**Discussion by Redsandro** [authelia/authelia#4610] [Q&A]
An average Authelia setup requires one to understand a lot of concepts at the same time. I'm trying to learn Authelia and start small. 

Imagine I have a _"Hello World"_ html running on port 80 of an nginx-container on a Raspberry Pi in the LAN at `192.168.0.100`. Can I use Authelia to protect and expose that port to people in the LAN?

I have Authelia running at port 9091 and authentication is working. I can't figure out how to 'go to' port 80.

```yml
version: "3.7"

networks:
    authelia:

services:
  authelia:
    image: authelia/authelia:latest
    volumes:
      - ./config:/config
    ports:
      - 9091:9091
    networks:
      - authelia

  client:
    image: nginx
    volumes: # Hello world
      - ./html:/usr/share/nginx/html
    networks:
      - authelia
```

```yml
# https://www.authelia.com/docs/configuration/access-control.html#access-control-list
access_control:
  default_policy: one_factor
  networks:
    - name: internal
      networks:
        - '192.168.0.0/24'
  rules:
    - domain: 192.168.0.100:80
      policy: one_factor
      networks:
        - internal
```
