### DISCUSSION TITLE
Document CORS configuration

### DISCUSSION THREAD

**Discussion by NiceGuyIT** [authelia/authelia#4629] [Q&A] [answered]
## Feature Request

Please document an example CORS policy, for example different situations.

### Description

I have Wiki.js configured with Authelia, Traefik and Cloudflare. Everything is working but there was one error in the browser console logs about a request being blocked due to CORS policy. This happens on every refresh of the page, even after being authenticated. TBH I don't know why it fails for this specific URL, and only this URL.

Here are the browser console logs.

```text
09:11:46.492 Access to manifest at 'https://authelia.example.com/?rd=https%3A%2F%2Fwikijs.example.com%2F_assets%2Fmanifest.json&rm=GET' (redirected from 'https://wikijs.example.com/_assets/manifest.json') from origin 'https://wikijs.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
09:11:46.492 GET https://authelia.example.com/?rd=https%3A%2F%2Fwikijs.example.com%2F_assets%2Fmanifest.json&rm=GET net::ERR_FAILED
```

Here are the corresponding server logs. It should be noted the "Access to ... (method GET) is not authorized to user" message appears in several issues, notably issue #1195 and #1348.

```text
Apr 08 09:11:46 nb-01 authelia[16388]: time="2021-04-08T09:12:14-04:00" level=info msg="Access to https://wikijs.example.com/ (method GET) is not authorized to user <anonymous>, redirecting to https://authelia.example.com/?rd=https%3A%2F%2Fwikijs.example.com%2F&rm=GET" method=GET path=/api/verify remote_ip=0.0.0.0
Apr 08 09:11:46 nb-01 traefik[15070]: time="2021-04-08T09:12:14-04:00" level=debug msg="Remote error http://localhost:9091/api/verify?rd=https://authelia.example.com/. StatusCode: 302" middlewareName=authelia@file middlewareType=ForwardedAuthType
```

To fix this, Traefik was configured with the `Vary` header along with the origin list. This was needed only for the Authelia router.

```toml
# Configure CORS
[http.middlewares.cors-headers.headers]
    accessControlAllowOriginList = [ "https://wikijs.example.com", "https://authelia.example.com", ]
    addVaryHeader = true

[http.routers.authelia]
	entrypoints = [ "web-secure" ]
	service = "authelia"
	rule = "Host(`authelia.example.com`)"
	# CORS headers are needed to prevent this error.
	#   No 'Access-Control-Allow-Origin' header is present on the requested resource.
	middlewares = [ "cloudflare-ips", "cors-headers", ]
	[http.routers.authelia.tls]
		certResolver = "cloudflare"

[http.routers.wikijs]
	entrypoints = [ "web-secure" ]
	service = "wikijs" 
	rule = "Host(`wikijs.example.com`) && HeadersRegexp(`X-Forwarded-For`, `[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}`)"
	# wikijs.example.com is proxied by cloudflare
	middlewares = [ "cloudflare-ips", "authelia", "authelia-headers", ]
	[http.routers.wikijs.tls]
		certResolver = "cloudflare"
```

### Use Case

This improves documentation for those who actually RTFM. The Traefik 2.x example does not mention CORS. `insecureSNI` is mentioned in issue #1195 and was removed from Traefik.

### Versions

`authelia version`:

```text
Authelia version v4.27.4, build 6ea62657d90ce480780befdc4284bf0d79be1e07
```

`traefik version`:

```text
Version:      2.3.6
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-17T16:34:27Z
OS/Arch:      linux/amd64
```
