### DISCUSSION TITLE
Authelia auto-start on UnRAID server fails every time

### DISCUSSION THREAD

**Discussion by APT256** [authelia/authelia#4791] [Q&A]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

1.32.0

### Description

I have successfully installed the SWAG Docker image on my UnRAID 6.11.5 system. I have configured it to auto-start, but it never does. If I manually tell it to start, it starts fine. It looks like it might have a conflict with something else at startup? Any ideas on how I can troubleshoot this would be appreciated.

Jon

### Reproduction

Restart UnRAID, go to the Docker tab and verify that SWAG is not running (even though it is configured to load at startup.

### Expectations

Because it is configured to load at startup, it should automatically start.

### Configuration (Authelia)

```yaml
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: "kYp3s6v8y/B?E(H+"
default_redirection_url: https://xxx.xxx.xxx/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 8192
  write_buffer_size: 8192
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info

totp:
  issuer: jon.irish
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  ldap:
    implementation: activedirectory
    url: ldap://xx.xxx.xxx:389
    start_tls: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: DC=xxx,DC=xxx,DC=xxx
    username_attribute: sAMAccountName
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2)(!pwdLastSet=0))
    #additional_groups_dn: OU=Groups
    groups_filter: (&(member:1.2.840.113556.1.4.1941:={dn})(objectClass=group)(objectCategory=group))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayname
    user: CN=xxx,CN=xxx,DC=xx,DC=xxx,DC=xxx
    password: xxxxxxxxxxxxxxxx

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 
        - "auth.xxx.xxx"
      policy: bypass
    ## catch-all
    - domain:
        - "*.xxx.xxx"
      subject: 
        - "group:admins"
      policy: one_factor

session:
  name: authelia_session
  domain: xxx.xxx
  same_site: lax
  secret: "xxxxxxxxxxxxxxxx"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M
  redis:
    host: redis
    port: 6379
    password: "xxxxxxxxxxxxxxxx"
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: "xxxxxxxxxxxxxxxx"
  mysql:
    host: mariadb
    port: 3306
    database: authelia
    username: authelia
    password: "xxxxxxxxxxxxxxxx"
  
notifier:
  disable_startup_check: false
  smtp:
    username: xxx@xxx.xxx
    password: "xxxxxxxxxxxxxxxx"
    host: smtp.xxx.com
    port: 587
    sender: authelia@xxx.xxx
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: test@xxx.xxx
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
...
```

### Logs (Authelia)

```shell
time="2023-01-18T10:03:56-06:00" level=info msg="Storage schema is being checked for updates"
time="2023-01-18T10:03:56-06:00" level=info msg="Storage schema is already up to date"
time="2023-01-18T10:03:56-06:00" level=error msg="Your LDAP Server supports TLS but you don't appear to be utilizing it. We strongly recommend using the scheme 'ldaps://' or enabling the StartTLS option to secure connections with your LDAP Server." stack="github.com/authelia/authelia/v4/internal/commands/root.go:323 doStartupCheck\ngithub.com/authelia/authelia/v4/internal/commands/root.go:286 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
time="2023-01-18T10:03:57-06:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
```

### Logs (Proxy / Application)

```shell
cont-init: info: /etc/cont-init.d/50-certbot exited 0
cont-init: info: running /etc/cont-init.d/55-permissions
cont-init: info: /etc/cont-init.d/55-permissions exited 0
cont-init: info: running /etc/cont-init.d/60-renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Unsafe permissions on credentials configuration file: /config/dns-conf/cloudflare.ini
Failed to renew certificate jon.irish with error: Unable to determine zone_id for irishtech.biz using zone names: ['irishtech.biz', 'biz']. Please confirm that the domain name has been entered correctly and is already associated with the supplied Cloudflare account.
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/jon.irish/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
cont-init: info: /etc/cont-init.d/60-renew exited 0
cont-init: info: running /etc/cont-init.d/70-outdated
cont-init: info: /etc/cont-init.d/70-outdated exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mod-universal-docker-setup: starting
s6-rc: info: service init-mod-swag-cloudflare-real-ip-setup: starting
s6-rc: info: service init-mod-universal-docker-setup successfully started
s6-rc: info: service init-mod-swag-auto-proxy-setup: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mod-swag-cloudflare-real-ip-setup successfully started
s6-rc: info: service init-mod-swag-auto-proxy-setup successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun fail2ban (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=itsme@xxx.xxx
STAGING=false

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for xxx.xxx will be requested
EXTRA_DOMAINS entered, processing
Extra domains processed are:  -d *.xxx.xxx
E-mail address entered: itsme@xxx.xxx
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
The cert is either expired or it expires within the next day. Attempting to renew. This could take up to 10 minutes.
<------------------------------------------------->

<------------------------------------------------->
cronjob running on Wed Jan 18 09:15:49 CST 2023
Running certbot renew

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/jon.irish.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewing an existing certificate for *.jon.irish and 2 more domains

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[custom-init] No custom files found, skipping...
**** installing docker and docker compose ****
**** docker and docker-compose already installed, skipping ****
**** Remote docker service dockersocket will be used ****
**** Using preset proxy conf for netdata ****
**** Enabling Authelia for netdata ****
**** No preset proxy conf found for SearXNG, generating from scratch ****
**** Setting upstream address SearXNG for SearXNG ****
**** Setting port 8080 for SearXNG ****
**** Setting proto http for SearXNG ****
**** Setting url SearXNG.* for SearXNG ****
**** Enabling Authelia for SearXNG ****
**** No preset proxy conf found for UptimeKuma, generating from scratch ****
**** Setting upstream address UptimeKuma for UptimeKuma ****
**** Setting port 3001 for UptimeKuma ****
**** Setting proto http for UptimeKuma ****
**** Setting url UptimeKuma.* for UptimeKuma ****
**** Enabling Authelia for UptimeKuma ****
**** Using preset proxy conf for vaultwarden ****
**** Enabling Authelia for vaultwarden ****
[ls.io-init] done.
Server ready
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
