### DISCUSSION TITLE
Page auto refresh when login to minio admin console with authelia

### DISCUSSION THREAD

**Discussion by catfishlty** [authelia/authelia#4799] [Q&A] [answered]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

https://hub.docker.com/layers/jc21/nginx-proxy-manager/latest/images/sha256-78e8921a7dac14fc8f3ba74f71bb06b91328ae0cf4d9bd1d49d6854c889218e0?context=explore

### Description

1. add protected minio admin console domain `admin-minio.example.com` to authelia configuration.yml->access_control->rules->domain, and add policy `one_factor`
2. setup `Nginx Proxy Manager`, add custom ssl cert and custom nginx conf base on authelia document.

When login to minio admin login page, it show up normally, then type in user/pass and login, the page auto refresh and then goto minio admin login page again. I'm pretty sure the config for minio and authelia is correct. Other domain site can works fine under the config.

## Deployed by docker compose

1. deploy `jc21/nginx-proxy-manager:latest`
```yml
version: '3'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    hostname: npm.internal
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /root/data/npm:/data
      - /root/data/letsencrypt:/etc/letsencrypt
      - /root/data/nginx/snippets:/config/nginx/snippets:ro
    networks:
      local_net:
        aliases:
          - npm.example.com
          - auth.example.com
networks:
  local_net:
    external: true
```
2. deploy `authelia/authelia:latest`
```yml
version: '3'
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    hostname: auth.internal
    ports:
      - 9091:9091
    volumes:
      - /root/data/authelia:/data
      - /root/data/authelia/config:/config
    environment:
      - TZ=Asia/Shanghai
    networks:
      local_net:
        aliases:
          - auth.internal
networks:
  local_net:
    external: true
```
```yml
...
access_control:
  default_policy: deny
  rules:
    - domain: 
        - auth.example.com
        - npm.example.com
      policy: bypass
    - domain:
        - admin-minio.example.com
      policy: bypass
      resources:
        - 'manifest.json'
    - domain: 
        - minio.example.com
        - admin-minio.example.com
      policy: one_factor
...
```

3. deploy `minio/minio:RELEASE.2023-01-18T04-36-38Z`
```yml
version: '3.0'
services:
  minio:
    image: minio/minio:RELEASE.2023-01-18T04-36-38Z
    container_name: minio
    hostname: minio.internal
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address ":9001" --address ":9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: test12345678
    logging:
      options:
        max-size: "2000M"
        max-file: "10"
      driver: json-file
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /root/data/minio:/data
    networks:
      local_net:
        aliases:
          - "minio.internal"
networks:
  local_net:
    external: true
```
4. add proxy settings in Nginx Proxy Manager and authelia settings.
`auth.example.com` -> `http://authelia:9091`
`admin-minio.example.com` -> `http://minio:9001`

5. access to `admin-minio.example.com`, login page show up, type in username/password, then click login button, the page seems login successful, but then it refresh quickly and go to login page again.

### Configuration (Authelia)

```yaml
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: <encrypted>
default_redirection_url: http://auth.example.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

totp:
  disable: false
  issuer: example.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

access_control:
  default_policy: deny
  rules:
    - domain: 
        - auth.example.com
        - npm.example.com
      policy: bypass
    - domain:
        - admin-minio.example.com
      policy: bypass
      resources:
        - 'manifest.json'
    - domain: 
        - admin-minio.example.com
      policy: one_factor

authentication_backend:
  ldap:
    implementation: custom
    url: ldap://ldap.example.com:3890
    timeout: 5s
    start_tls: false
    base_dn: DC=example,DC=com
    additional_users_dn: ou=people
    #users_filter: (|({username_attribute}={input})({mail_attribute}={input}))
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: cn
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: uid=service,ou=people,DC=example,DC=com
    password: 12345678

session:
  name: authelia_session
  secret: <encrypted>
  expiration: 3600  # 1 hour
  inactivity: 600  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: <encrypted>
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```

### Logs (Authelia)

```shell
time="2023-01-19T17:31:53+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method POST)."
time="2023-01-19T17:31:56+08:00" level=info msg="Access to https://admin-minio.example.com/manifest.json (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.18.0.1
time="2023-01-19T17:31:56+08:00" level=debug msg="Check authorization of subject username= groups= ip=172.18.0.1 and object https://admin-minio.example.com/manifest.json (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/styles/fonts/Lato/Lato-Bold.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/styles/fonts/Lato/Lato-Regular.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/videoBG.17363418b3c2246a0e27.mp4 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Bold.ec64ea577b0349e055ad.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Light.2d5198822ab091ce4305.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Black.15ca31c0a2a68f76d2d1.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=info msg="Access to https://admin-minio.example.com/manifest.json (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.18.0.1
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username= groups= ip=172.18.0.1 and object https://admin-minio.example.com/manifest.json (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/check-version (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Regular.c8ba52b05a9ef10f4758.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/buckets (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/login (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/admin/site-replication (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/subnet/info (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/session (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method POST)."
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
First of all as you clearly mentioned other apps are working fine. I can't see any authentication logs from Authelia here so it's quite difficult to conclude this is actually a bug since you only partially included logs. How are you authenticating?

I can't replicate the `Access to https://admin-minio.mydomain.com/manifest.json (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.18.0.1` log with the information provided. When running the following command it matches the first instance of the rule:

```bash
authelia access-control check-policy --config /config/configuration.yml --method GET --url https://admin-minio.mydomain.com/manifest.json --verbose
```

I have no confidence that you properly followed the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide as you didn't follow the rest of the template. Please update this discussion with this information requested.

**Reply by catfishlty** [reply]
Thanks for your quick reply, and sorry for that I didn't completely followed the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) and I'll edit it in the content.

In the description, I didn't write down the right description about the log you shown in the comment.

In the authelia configuration, I add these code to do some testing, and forgot to remove. If you delete it, this log can be seen.
```yml
    - domain:
        - admin-minio.example.com
      policy: bypass
      resources:
        - 'manifest.json'
```

**Reply by catfishlty** [reply]
>  How are you authenticating?

About this question, I just do these tasks:
1. add `minio.example.com` to `access_control` in config files.
2. add `minio.example.com` to Nginx Proxy Manager to support self-signed ssl cert, and apply `authelia` custom nginx config.
Here's the Nginx Proxy Manager config for this domain:

![1674130115](https://user-images.githubusercontent.com/12734411/213439615-39f96a8c-eda8-4546-9293-0a6e320125e7.png)

![1674130129](https://user-images.githubusercontent.com/12734411/213439630-c3205482-5a3b-498d-a00b-34550c3b1740.png)

![1674130171](https://user-images.githubusercontent.com/12734411/213439639-7867d2d4-88c8-4771-8a66-985fb3d0cb7a.png)

```
include /config/nginx/snippets/authelia-location.conf;

location / {
    include /config/nginx/snippets/proxy.conf;
    include /config/nginx/snippets/authelia-authrequest.conf;
    proxy_pass $forward_scheme://$server:$port;
}
```

After some more tesing, I found that if I remove this nginx custom nginx config, it means I only use Nginx Proxy Manager to do https proxy, it can works fine too. So I suspect that this problem is caused by `authelia`.

**Reply by james-d-elliott** [reply]
What is the behaviour and logs like when you leave the manifest.json ignore there? It's safe to ignore this file.

**Reply by catfishlty** [reply]
> What is the behaviour and logs like when you leave the manifest.json ignore there? It's safe to ignore this file.

Sorry, this `manifest.json` ignored config may mislead you. Plz leave it, it's just my test data. Ignoring it or not didn't change the behaviour on web page. 
Only 2 differences:
1. no `5xx` error in chrome debug network tab
6. no `time="2023-01-19T17:31:55+08:00" level=info msg="Access to https://admin-minio.example.com/manifest.json (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.18.0.1` log in Authelia Container logs.

All steps of the behaviour: (already login to Authelia)
1. go to Minio Login Page
2.  Type in user/pass then Click Login
3.  rapidly shown console page with less than 1 second
4.  go to Minio Login Page.

If possible, I'll add gifs later.

**Reply by james-d-elliott** [reply]
And maybe the logs in authelia for that behavior , also are you using OIDC or the redirection / forward auth?

**Reply by catfishlty** [reply]
> And maybe the logs in authelia for that behavior , also are you using OIDC or the redirection / forward auth?

I'm only using redirection / forward auth? Because I can't setup OIDC auth for `Minio` correctly.

**Reply by catfishlty** [reply]
Sorry for late reply.
Here's the steps when I access to minio admin login page.
1. go to `admin-minio.example.com`, auto redirect to `auth.example.com`
![1675049736](https://user-images.githubusercontent.com/12734411/215394989-4eeadacd-55c2-4ce4-8c74-70b73eb7bb8f.png)

2. login to `auth.example.com`, then redirect to `admin-minio.example.com`
![1675049792](https://user-images.githubusercontent.com/12734411/215395012-ceb971e6-5659-4ca5-8ed5-e8f58a5a6405.png)

3. login to `admin-minio.example.com`, the page auto refresh. I can only make this gif with this size, if you need, I'll work out how to make a full screen size gif.
![1675049815](https://user-images.githubusercontent.com/12734411/215395041-dbdc8e0d-9c94-440e-ba01-e677eaf63c04.gif)

BTW, I can make sure the account/password are correct.

Thanks~

**Reply by james-d-elliott** [reply]
Can you please set the log level to debug and show the logs from the time you start the container to the time this issue occurs.........

**Reply by catfishlty** [reply]
```
time="2023-01-30T16:51:22+08:00" level=info msg="Shutting down"
time="2023-01-30T16:51:23+08:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-30T16:51:23+08:00" level=info msg="Log severity set to debug"
time="2023-01-30T16:51:23+08:00" level=debug msg="Registering client gitea with policy one_factor (one_factor)"
time="2023-01-30T16:51:23+08:00" level=debug msg="Registering client outline with policy one_factor (one_factor)"
time="2023-01-30T16:51:23+08:00" level=info msg="Storage schema is being checked for updates"
time="2023-01-30T16:51:23+08:00" level=info msg="Storage schema is already up to date"
time="2023-01-30T16:51:23+08:00" level=debug msg="LDAP Supported OIDs. Control Types: none. Extensions: 1.3.6.1.4.1.4203.1.11.1"
time="2023-01-30T16:51:23+08:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2023-01-30T16:51:27+08:00" level=debug msg="Check authorization of subject username= groups= ip=172.18.0.1 and object https://admin-minio.example.com/ (method GET)."
time="2023-01-30T16:51:27+08:00" level=info msg="Access to https://admin-minio.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.18.0.1
time="2023-01-30T16:51:31+08:00" level=debug msg="Mark 1FA authentication attempt made by user 'service'" method=POST path=/api/firstfactor remote_ip=172.18.0.1
time="2023-01-30T16:51:31+08:00" level=debug msg="Successful 1FA authentication attempt made by user 'service'" method=POST path=/api/firstfactor remote_ip=172.18.0.1
time="2023-01-30T16:51:31+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/ (method )."
time="2023-01-30T16:51:31+08:00" level=debug msg="Required level for the URL https://admin-minio.example.com/ is 1" method=POST path=/api/firstfactor remote_ip=172.18.0.1
time="2023-01-30T16:51:31+08:00" level=debug msg="Redirection URL https://admin-minio.example.com/ is safe" method=POST path=/api/firstfactor remote_ip=172.18.0.1
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/ (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/session (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Regular.c8ba52b05a9ef10f4758.woff2 (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/login (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username= groups= ip=172.18.0.1 and object https://admin-minio.example.com/manifest.json (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Regular.c8ba52b05a9ef10f4758.woff2 (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/videoBG.17363418b3c2246a0e27.mp4 (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/check-version (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Black.15ca31c0a2a68f76d2d1.woff2 (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Light.2d5198822ab091ce4305.woff2 (method GET)."
time="2023-01-30T16:51:32+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Bold.ec64ea577b0349e055ad.woff2 (method GET)."
time="2023-01-30T16:51:33+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/videoBG.17363418b3c2246a0e27.mp4 (method GET)."
time="2023-01-30T16:51:35+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method POST)."
time="2023-01-30T16:51:36+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method POST)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method POST)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/session (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/subnet/info (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/admin/site-replication (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/login (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Regular.c8ba52b05a9ef10f4758.woff2 (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/videoBG.17363418b3c2246a0e27.mp4 (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/login (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/api/v1/check-version (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Black.15ca31c0a2a68f76d2d1.woff2 (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Bold.ec64ea577b0349e055ad.woff2 (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/Inter-Light.2d5198822ab091ce4305.woff2 (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.example.com/static/media/videoBG.17363418b3c2246a0e27.mp4 (method GET)."
time="2023-01-30T16:51:37+08:00" level=debug msg="Check authorization of subject username= groups= ip=172.18.0.1 and object https://admin-minio.example.com/manifest.json (method GET)."
```

For your reference, Thanks

**Comment by james-d-elliott** [comment, marked as answer]
Looks like minio is not including the cookie for the request to `manifest.json`, you can confirm this using browser dev tools. Add an exclusion like previously suggested (at the top of the rules list):

```yaml
- domain: admin-minio.example.com
  policy: bypass
  resources:
    - '^/manifest\.json$'
```
