### DISCUSSION TITLE
Non standard https port; CSP blocks resource at base domain.

### DISCUSSION THREAD

**Discussion by Gandalf-the-Blue** [authelia/authelia#4958] [Q&A]
Hi,

I'm trying to run authelia on a non-standard https port @ https://authelia.example.tld:600. I'm using the latest docker image with swag as a reverse proxy. I am able to log in to the authelia portal with username and password and when the notification is sent to the file, it does not include the port in the url, which if I fix by hand before navigating to the url, nothing loads and the inspector shows this - 

Content Security Policy: The page’s settings blocked the loading of a resource at https://authelia.example.tld/ (“base-uri”). 

Loading module from “https://authelia.example.tld:600/one-time-password/static/js/index.fad9e36b.js” was blocked because of a disallowed MIME type (“text/html”).

Loading failed for the module with source “https://authelia.example.tld:600/one-time-password/static/js/index.fad9e36b.js”.

The resource from “https://authelia.example.tld:600/one-time-password/static/css/index.40feef90.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

The first error "Content Security Policy: The page’s settings blocked the loading of a resource at https://authelia.example.tld/ (“base-uri”). " is also present when logging in via first factor but everything still seems to work.

I read through previous question - https://github.com/authelia/authelia/issues/2765 - but this maintains that the issue is resolved.

What am I missing here?

**Comment by Gandalf-the-Blue** [comment]
I'm using authelia v4.37.5
Swag 2.3.0-ls182

My conf files are as below -

```
server:
  host: 0.0.0.0
  port: 9091
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: authelia
log:
  level: info
  format: json
  file_path: /config/logs/authelia.log
jwt_secret:  <secret>
theme: dark
default_redirection_url: https://authelia.example.tld:600
totp:
  disable: false
  issuer: authelia.com
  algorithm: sha256
  digits: 6
  period: 30
  skew: 1
authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 8
access_control:
  default_policy: bypass
  rules:
    - domain:
      - 'domain1.example.tld:600'
      - 'domain2.example.tld:600'
      - 'domain3.example.tld:600'
      policy: two_factor
session:
  name: authelia_session
  secret: <secret>
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: example.tld
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: <secret>
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
```

My proxy.conf file is

```
## Version 2023/02/12
# make sure that your authelia container is named authelia
# make sure that your dns has a cname set for authelia
# the default authelia-server and authelia-location confs included with swag rely on
# a built-in subfolder proxy at "/authelia" and enabling this proxy conf is not necessary.
# But if you'd like to use authelia via subdomain, you can enable this proxy and set
# the $authelia_backed variable in the authelia-server.conf.

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name authelia.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app authelia;
        set $upstream_port 9091;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location ~ (/authelia)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app authelia;
        set $upstream_port 9091;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        
    }

    location ~ (/authelia)?/metrics {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # block metrics access by default because it is unprotected
        # you can comment out the next line to enable remote metrics
        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app authelia;
        set $upstream_port 9091;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```
