### DISCUSSION TITLE
Help with CORS in OIDC setup (with caddy v2) - preflight redirect instead of 204

### DISCUSSION THREAD

**Discussion by C8opmBM** [authelia/authelia#5009] [Q&A]
I've been struggling to find a solution to this, to no end.

So I have outline setup with OIDC.
The main subdomain `wiki.domain` needs to make requests to `wikidata.domain` in order to upload images.

I've setup cors policy in caddy v2, but all the time I have this error in browser.

`Access to XMLHttpRequest at 'https://wikidata.domain.net/outline' from origin 'https://wiki.domain.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

I've configured it correctly with cors snippet, it should respond with 204 but somehow it still redirects

My caddy snippet:
```
(cors) {
        @cors_preflight{args.0} method OPTIONS
        @cors{args.0} header Origin {args.0}

        handle @cors_preflight{args.0} {
                header {
                        Access-Control-Allow-Origin "{args.0}"
                        Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS"
                        Access-Control-Allow-Headers *
                        Access-Control-Max-Age "3600"
                        defer
                }
                respond "" 204
        }

        handle @cors{args.0} {
                header {
                        Access-Control-Allow-Origin "{args.0}"
                        Access-Control-Expose-Headers *
                        defer
                }
        }
}

auth.{$DOMAIN} {
        import cors https://wiki.{$DOMAIN}
        import cors https://wikidata.{$DOMAIN}
        reverse_proxy authelia:9091
}
```

If I bypass for internal ip for wiki.domain and wikidata.domain in authelia, the uploads work, so this makes me think the issue is with authelia rather than my cors reverse proxy setup 

```
  - name: internal
    networks:
    - '172.20.0.0/16'
    - '192.168.0.0/18'
  rules:
    - domain: ['wiki.domain.net', 'wikidata.domain.net']
      networks:
        - 'internal'
      policy: bypass
```
Could you point me in the right direction?

My identity providers cors setting (I've tried with "*" as well), doesnt work.
```
identity_providers:
  oidc:
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
      allowed_origins_from_client_redirect_uris: false
```
Authelia log during request:

`time="2023-03-01T20:55:12+02:00" level=info msg="Access to https://wikidata.domain.net/outline (method OPTIONS) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.domain.net/?rd=https%3A%2F%2Fwikidata.domain.net%2Foutline&rm=OPTIONS" method=GET path=/api/verify remote_ip=192.168.1.153`

I also found this at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests

```
Credentialed requests and wildcards
When responding to a credentialed request:

The server must not specify the "*" wildcard for the Access-Control-Allow-Origin response-header value, but must instead specify an explicit origin; for example: Access-Control-Allow-Origin: https://example.com
The server must not specify the "*" wildcard for the Access-Control-Allow-Headers response-header value, but must instead specify an explicit list of header names; for example, Access-Control-Allow-Headers: X-PINGOTHER, Content-Type
The server must not specify the "*" wildcard for the Access-Control-Allow-Methods response-header value, but must instead specify an explicit list of method names; for example, Access-Control-Allow-Methods: POST, GET
The server must not specify the "*" wildcard for the Access-Control-Expose-Headers response-header value, but must instead specify an explicit list of header names; for example, Access-Control-Expose-Headers: Content-Encoding, Kuma-Revision
```
However I do not know how should I adapt this.
Any insights?

**Comment by james-d-elliott** [comment]
The issue is most likely that the preflight doesn't include credentials (cookie header). This either needs to be fixed by the app developer or you need to setup a  bypass rule the preflight requests.

**Comment by C8opmBM** [comment]
Thanks James, I've tried also to include the suggested doc setup, but it does not work.

```
access_control:
  rules:
    - domain: ['wiki.domain.net', 'wikidata.domain.net']
      methods:
        - OPTIONS
      policy: bypass
```

It only works if I bypass them completely (as mentioned above, tested with bypass on local networks).
Any other suggestion?
