### DISCUSSION TITLE
Applying the authelia@docker middleware returns a 404.

### DISCUSSION THREAD

**Discussion by iamscottcab** [authelia/authelia#5022] [Q&A] [answered]
I have the following traefik compose file.

```
version: '3'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik/:ro
      - ../../volumes/traefik/acme:/acme:rw
    networks:
      traefik:
      traefik-ext:
          ipv4_address: ${TRAEFIK_IPV4_ADDRESS}
    labels:
      traefik.enable: true
      # Http Setup
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.routers.traefik.rule: Host(`${TRAEFIK_DOMAIN}`)
      traefik.http.routers.traefik.middlewares: https-redirect@file
      # Https Setup
      traefik.http.routers.traefik-secure.entrypoints: websecure
      traefik.http.routers.traefik-secure.rule: Host(`${TRAEFIK_DOMAIN}`)
      traefik.http.routers.traefik-secure.tls: true
      traefik.http.routers.traefik-secure.tls.certresolver: letsencrypt
      traefik.http.routers.traefik-secure.tls.domains[0].main: ${TRAEFIK_MAIN_DOMAIN}
      traefik.http.routers.traefik-secure.tls.domains[0].sans: ${TRAEFIK_SANS_DOMAINS}
      traefik.http.routers.traefik-secure.service: api@internal

networks:
  traefik:
    name: traefik
    driver: bridge
  traefik-ext:
    name: traefik-ext
    driver: macvlan
    driver_opts:
      parent: ${TRAEFIK_PARENT_INTERFACE}
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET}
          gateway: ${TRAEFIK_GATEWAY}
```

And the relevant authelia compose:
```
version: '3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ../../volumes/authelia:/config
    expose: 
      - 9091
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.rule: Host(`${AUTHELIA_DOMAIN}`)
      traefik.http.routers.authelia.entrypoints: websecure
      traefik.http.routers.authelia.tls: true
      traefik.http.routers.authelia.tls.certresolver: letsencrypt
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/authz/forward-auth?authelia_url=https://${AUTHELIA_DOMAIN}
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
    environment:
      TZ: My/Locale

networks:
  traefik:
    external: true
```

I can hit `auth.my.domain` just fine and log in and out. My middleware appears green in the Traefik dashboard as valid however whenever I do something like `traefik.http.routers.secure.middlewares=authelia@docker` traefik just returns a 404.

Neither my Traefik or Authelia containers log anything (if I just run them with `docker compose up`) and I am not exactly sure what to debug next. Any help would be greatly appreciated.
