### DISCUSSION TITLE
Access control through headers

### DISCUSSION THREAD

**Discussion by schklom** [authelia/authelia#5069] [Ideas]
Some projects use headers to authenticate users. For example, Radarr and Sonarr allow access to their API using either a query parameter (http://site.com/api/...?apikey=mykey) or a header (`X-API-Key: mykey`).

It would be good to add headers to access control in Authelia.
What I mean could look like the following, where only queries to `^/groups/dev/.*$` with `X-API-Key` set to `mykey`, or queries with `X-API-Key` set to `mykey2`, would be allowed
```yaml
access_control:
  rules:
    - domain: dev.example.com
      policy: bypass
      resources:
        - - header: X-API-Key
            value: mykey
            query: '^/groups/dev/.*$'
        - - header: X-API-Key
            value: mykey2
```
and a similar logic to https://www.authelia.com/configuration/security/access-control/#query could be used.

I'm sure there is a better way to do this, but this is all i can think of tonight :P

Edit: forgot about `policy`
