### DISCUSSION TITLE
Cloudflare and Authelia configuration.

### DISCUSSION THREAD

**Discussion by tserversbfs** [authelia/authelia#5109] [Q&A] [answered]
level=error msg="Configuration: identity_providers: oidc: option 'issuer_private_key' is required"

I have followed the docs and just closed avbout 15 tabs. lol. "redirect_urls" is commented out as authleia didn't like it being there. 

Any help would be ap[reciated. Thanks in advance.

```
identity_providers:
  oidc:
    clients:
      - id: cloudflare
        description: CloudFlair ZeroTrust
        secret: GTdt6q6EWiocqANjs
        public: false
        authorization_policy: two_factor
#        redirect_urls:
#        - https://mylazytime.cloudflareaccess.com/cdn-cgi/access/callback
        scopes:
        - openid
        - profile
        - email
        userinfo_signing_algorithm: none
 #       issuer_private_key:
```
link to docs: https://www.authelia.com/integration/openid-connect/cloudflare-zerotrust/
