### DISCUSSION TITLE
Basic Authentication

### DISCUSSION THREAD

**Discussion by pppaapp** [authelia/authelia#5131] [Q&A] [answered]
hi

My English is terrible. 
Please understand me.

I installed ingress-nginx and authelia on kubernetes.

Part of the contents of `configuration.yml`.

```yaml
access_control:
  default_policy: deny
  rules:
    - domain: send.example.com
      policy: bypass
      resources:
        - '^(\/api)?\/download\/'
        - '^\/api\/metadata\/'
        - '\.(js|css|jpg|png|svg|woff2|txt)$'
      methods:
        - GET
        - HEAD
    - domain: send.example.com
      policy: one_factor
      subject:
        - ['group:admins']
```

I want https://send.example.com/download/abcde to be accessible without a login.

This is It works as intended.

```yaml
annotations:
    nginx.ingress.kubernetes.io/auth-method: GET
     nginx.ingress.kubernetes.io/auth-url: http://authelia-service.authelia.svc.cluster.local/api/verify
     nginx.ingress.kubernetes.io/auth-signin: https://authelia.example.com?rm=$request_method
     nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
     nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Method $request_method;
```

But when I set it to Basic Authentication, it doesn't work as I intended

Requires authentication at `https://send.example.com/download/abcd`

I want this url to be accessible without authentication

```yaml
annotations:
     nginx.ingress.kubernetes.io/auth-url: http://authelia-service.authelia.svc.cluster.local/api/verify?auth=basic
     nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
```

How do I modify my settings?

Please help me

**Comment by james-d-elliott** [comment, marked as answer]
If you want it accessible WITHOUT authentication, disable the annotations or add a bypass rule, that's not what basic auth is for.

**Reply by pppaapp** [reply]
I want to access the URL `https://send.example.com/download/*` without authentication.

like I set to bypass in `configuration.yml`.

Is this impossible?

**Reply by james-d-elliott** [reply]
The [Access Control Documentation](https://www.authelia.com/configuration/security/access-control/) covers configuring the access control rules in-depth. It's possible.

**Reply by pppaapp** [reply]
Yes, so I set it up like this

```yaml
access_control:
  default_policy: deny
  rules:
    - domain: send.example.com
      policy: bypass
      resources:
        - '^(\/api)?\/download\/'
        - '^\/api\/metadata\/'
        - '\.(js|css|jpg|png|svg|woff2|txt)$'
      methods:
        - GET
        - HEAD
```

Basic authentication ignores this.
