### DISCUSSION TITLE
ingress-nginx invalid redirect?

### DISCUSSION THREAD

**Discussion by pppaapp** [authelia/authelia#5135] [Q&A] [answered]
I'm using kubernetes and ingress-nginx.

And the settings are as follows

```yaml
    server:
      host: 0.0.0.0
      port: 9091
      path: "ssoauth"
```

```yaml
  annotations:
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-url: http://authelia-service.authelia.svc.cluster.local/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://send.example.com/ssoauth?rm=$request_method
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
```

Redirect is invalid

![CleanShot 2023-03-28 at 10 24 05](https://user-images.githubusercontent.com/31263588/228103379-cc73900e-55b3-40c6-8c61-dc32b7341b2f.gif)

The URL `https://send.example.com/ssoauth?rm=get&rd=https://send.example.com%2F/` is not valid.

How can I modify my settings to redirect to the correct URL, `https://send.example.com/ssoauth?rm=get&rd=https%3A%2F%2Fsend.example.com%2F`?

**Comment by pppaapp** [comment]
If I don't use subpath like `/ssoauth` it works fine.

But I want to use a subpath.

**Comment by james-d-elliott** [comment, marked as answer]
You need to include the trailing slash in the URL for starters (at least I believe that's the case).

i.e.  `nginx.ingress.kubernetes.io/auth-signin: https://send.example.com/ssoauth/?rm=$request_method`

Also looks like a bug in ingress-nginx preventing the url from being escaped properly in the query params:

- https://github.com/kubernetes/ingress-nginx/blob/main/internal/ingress/controller/template/template.go#L1181
- https://github.com/kubernetes/ingress-nginx/blob/04b4f9cf425b72b7b68e01b98f91fba5d24065d3/internal/ingress/controller/template/template.go#L1181

You can probably manually override this by including the `&rd=https%3A%2F%2Fsend.example.com%2F` in the `auth-signin` annotation. This is however beyond our support capabilities.

**Reply by pppaapp** [reply]
Added a slash to the trailing URL

```yaml
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://authelia-service.authelia.svc.cluster.local/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://send.example.com/ssoauth/?rm=$request_method
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
```

![CleanShot 2023-03-28 at 11 18 30](https://user-images.githubusercontent.com/31263588/228110505-6effa993-3b0c-4991-b575-22cc8afcead0.gif)

And I tried it, but this is what happens

Are this a bug that should be fixed in kubernetes/ingress-nginx?

**Reply by james-d-elliott** [reply]
I may be wrong about the trailing slash, must only be relevant for the root URL. For further assistance you'll have to show your browser in English and/or provide a HAR.

**Reply by pppaapp** [reply]
What is HAR?

**Reply by james-d-elliott** [reply]
Carefully read this: https://www.authelia.com/reference/guides/http-archive-file/

If you want to submit it privately you'll need to use the chat.

**Reply by james-d-elliott** [reply]
Also we'd need authelia logs in addition to this.

**Reply by pppaapp** [reply]
[1.zip](https://github.com/authelia/authelia/files/11085577/1.zip)

This log has the following settings

```yaml
    server:
      host: 0.0.0.0
      port: 9091
      path: "ssoauth"
```

```yaml
  annotations:
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-url: http://authelia-service.authelia.svc.cluster.local/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://send.example.com/ssoauth?rm=$request_method
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
```

---


And sorry

I made a mistake

```yaml
    server:
      host: 0.0.0.0
      port: 9091
      path: "ssoauth"
```

```yaml
  annotations:
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-url: http://authelia-service.authelia.svc.cluster.local/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://send.example.com/ssoauth/?rm=$request_method
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
```

The above setup is fine and works fine.

This issue has been resolved.

Thanks
