### DISCUSSION TITLE
Apply more specific rule below a wildcard rule.

### DISCUSSION THREAD

**Discussion by Questlog** [authelia/authelia#5162] [Q&A] [answered]
Hey, I would like to have a two_factor policy for all my subdomains. But one subdomain should be only accessible for users of a particular group. 

I tried it with the following config, but it is always matching the wildcard and let all users access the jupyter subdomain. 
I have the feeling that this is not possible after reading the docs. The sequential order is ignored, since it is using a subject. So it also checks the second rule, that passes.

```yaml
access_control: 
  default_policy: deny
  rules:
    - domain: jupyter.example.com
      policy: two_factor
      subject: 'group:dev'
    - domain: "*.example.com"
      policy: two_factor
      subject: 'group:user'
```

My next idea was to change the wildcard into a regex to filter the "jupyter" subdomain. But that brought up an issue with go not supporting negative lookaheads:

```yaml
access_control: 
  default_policy: deny
  rules:
    - domain: jupyter.example.com
      policy: two_factor
      subject: 'group:dev'
    - domain_regex: '^(?!jupyter).+\.example\.com'
      policy: two_factor
      subject: 'group:user'
```

```
error decoding 'access_control.rules[1].domain_regex[0]': could not decode '^(?!jupyter).+\.example\.com' to a regexp.Regexp: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```
