### DISCUSSION TITLE
Exception in Rule or Reverse regexp

### DISCUSSION THREAD

**Discussion by ghostersk** [authelia/authelia#5206] [Q&A] [answered]
I am trying to secure my webserver with growing amount of sites.
Until now I was using Bypass as default policy and set two_factor for what I needed.
However not i have some sites what I need to block, but I know only things what need to be without authelia...

I tried to use revers regexp but that breaks authelia as it is not recognized by it.
Also I have tried few things like "except" or  "not_resources" in the policy but this does not seem to be available in authelia.

For example I want to allow only these:

  rules:
    - domain: meshcentra.mydomain.com
      policy: bypass
      resources:
        - "^/meshagents.*$"
        - "^/meshsettings.*$"
        - "^/agent.*$"
        - "^/control.*$"
        - "^/meshrelay.*$"
        - "^/sharing.*$"
        - "^/scripts.*$"
        - "^/styles.*$"
        - "^/images.*$"
        - "^/favicon.*$"

Than again I have some site like Email, where I want to allow all except /admin or /admin/.... where this is often on many my hosted sites.
I tried to use negating regexp, but as I mentioned this does not seem to be recognized by Authelia
     
resources:
        - "^(?!/admin[/?]).*"

**Comment by james-d-elliott** [comment]
Several ways to achieve this, and yes we don't support reverse regex because go doesn't support it for good reason if you ask me.

```
default_policy: deny
rules:
- domain: meshcentra.mydomain.com
  policy: bypass
  resources:
  - "^/meshagents.$"
  - "^/meshsettings.$"
  - "^/agent.$"
  - "^/control.$"
  - "^/meshrelay.$"
  - "^/sharing.$"
  - "^/scripts.$"
  - "^/styles.$"
  - "^/images.$"
  - "^/favicon.$"
- domain: meshcentra.mydomain.com
  policy: two_factor
```

```
rules:
- domain: meshcentra.mydomain.com
  policy: bypass
  resources:
  - "^/meshagents.$"
  - "^/meshsettings.$"
  - "^/agent.$"
  - "^/control.$"
  - "^/meshrelay.$"
  - "^/sharing.$"
  - "^/scripts.$"
  - "^/styles.$"
  - "^/images.$"
  - "^/favicon.$"
- domain: meshcentra.mydomain.com
  policy: deny
```

```
default_policy: deny
rules:
- domain: meshcentra.mydomain.com
  policy: bypass
  resources:
  - "^/meshagents.$"
  - "^/meshsettings.$"
  - "^/agent.$"
  - "^/control.$"
  - "^/meshrelay.$"
  - "^/sharing.$"
  - "^/scripts.$"
  - "^/styles.$"
  - "^/images.$"
  - "^/favicon.$"
```
