### DISCUSSION TITLE
how do you configure Authelia to identify and allow/restrict access to a domain/resources using the 'Authorization Bearer Token' header?

### DISCUSSION THREAD

**Discussion by ismaelmdesousa** [authelia/authelia#5245] [Q&A] [answered]
I'm using Authelia with Nginx-proxy-manager and Identity Providers, everything is working, doing the authentication flow and getting the access token. My question is about the access_control, I know that the cookie is used to identify the user, but how do you configure Authelia to identify and allow/restrict access to a domain/resources using the 'Authorization Bearer Token' header?

The example below works using cookie to identify the user

access_control example
```yaml
rules:
  - domain: 'api.example.com'
    policy: one_factor
    subject:
    - ['group:admins']
  - domain: 'api.example.com'
    policy: one_factor
    subject:
    - ['group:operators']
    methods:
    - GET
```
