### DISCUSSION TITLE
Unexpected failure running Authelia

### DISCUSSION THREAD

**Discussion by RobertBrown3** [authelia/authelia#5288] [Q&A] [answered]
ng it to restart constantly.

I have created the three files necessary to run Authelia: the docker-compose.yml file. the user_database.yml file, and the configuration.yml file. All files are based on the examples provided on Authelia's website. The contents of my configuration.yml file are provided below. Information deemed too sensitive to share is marked as <redacted>:

```
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091

jwt_secret: <redacted>
log:
  level: debug

default_redirection_url: https://auth.solishome.net
totp:
  issuer: soliannet.net
  period: 30
  skew: 1

#duo_api:     ## You can use this api if you want push notifications of auth attempts
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  secret_key: yet-another-long-string-of-characters-and-numbers-and-symbols

authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
      
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "auth.soliannet.net"
		...Some other domains...
      policy: bypass
    - domain:
        - "vault.soli.net"
      policy: one_factor
    - domain:
        - "a2factor.domain.org"
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: <redacted>
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: soliannet.net 

  redis:
    host: authelia_redis_1
    port: 6379
 
regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m
  
theme: dark

storage:
  encryption_key: <redacted>
  local:
    path: /config/db.sqlite3

notifier:
#  filesystem:
#    filename: /config/notification.txt
  smtp:
    username: <redacted>
    password: <redacted>
    host: <redacted>
    port: 587
    sender: <redacted>
    subject: "[Authelia] {title}"
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: <redacted>
      skip_verify: false
      minimum_version: TLS1.2

```
when calling "docker-compose up" (no -d so I can see the log output), I am seeing the following output:

```
authelia    | time="2023-04-18T20:15:32-04:00" level=debug msg="Notifier SMTP client connected successfully"
authelia    | time="2023-04-18T20:15:32-04:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: mail.noip.com), attempting"
authelia    | time="2023-04-18T20:15:33-04:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
authelia    | time="2023-04-18T20:15:33-04:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: PLAIN LOGIN"
authelia    | time="2023-04-18T20:15:33-04:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
authelia    | time="2023-04-18T20:15:33-04:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
authelia    | time="2023-04-18T20:15:33-04:00" level=fatal msg="The following providers had fatal failures during startup: user" stack="github.com/authelia/authelia/v4/internal/commands/root.go:309 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
authelia exited with code 1

```
Because I have the restart for Authelia set to "unless-stopped" in my docker-compose.yml file, the container keeps restarting, and every few seconds it keeps exiting with the same message,

I do not understand what is causing this message, and while there are questions answered about some failures on the Internet, I am seeing nothing that addresses this failure. I suspect it is being caused by some error in my configuration (which is why I included the configuration.yml file) but this (somewhat cryptic) failure message does not give any clue as to what that error could be.

Can someone explain to me what is causing this failure, and give some idea how to fix it?
