### DISCUSSION TITLE
Can't get resources Policy to work on PrivateBin Links

### DISCUSSION THREAD

**Discussion by Ichnafi** [authelia/authelia#5305] [Q&A] [answered]
Hello fellas,

### Environment
- Docker
- Traefik
- Authelia
- PasteBin

### What I would like to achieve

1. Openin my PasteBin instance on my domain https://bin.domain.tld , authelia-Login is  mandatory, since I don't want to make it internet wide usable. It's for me.
2. Enter some data and let PrivateBin create a link, I can send to someone. 
3. The recepient can open the link without beeing forced to log in with authelia 

### How the links I will send to people look like
A typical PrivateBin Link will look like this:
https://subdomain.domain.tld/?e9bc79fc20eee125#J3GwZk6hAnbKvZM21sKuEVyMgaYJv9jFHjEddrDmqh3h

### What's the problem
One always has to login with authelia

### What I configured
I tried to approach the problem by using the "resources" policy in access-rules to catch if a created link should be opened or not.
But regardless what I tried, I (or other people) will always get prompted for authelia authentification.
My access-rule looks like this:
```
access_control:
  default_policy: deny
  rules:
    # Authelia accessible for everyone
    - domain: authelia.domain.tld
      policy: bypass
	  
    # People who have a link, dont need to authenticate
    - domain: bin.domain.tld
      policy: bypass
      resources:
        - '^\/\?[a-z0-9]{16}#.+$'
	
    # creating a link will need authentification
    - domain: bin.domain.tld
      policy: two_factor
		
``` 
Then I test this regex on regex101.com it matches averything after bin.domain.tld, but I still get the authelia login page.

Can anyone provide me with some help or point out if this is even possible?
Since I'm no native english speaker I hope I made clear, what I try to achieve here.

**Comment by james-d-elliott** [comment, marked as answer]
Fragments (everything INCLUDING AND AFTER the `#`) are entirely client side, no server ever see's that in the request.

**Reply by Ichnafi** [reply]
Hell @james-d-elliott,
thank you for you answer. How blind i was. The # ins an anchor tag (that seems to be misused in this application), that will not be seen by the server.

Thanks to your hint, I got it working now, but it was kind of struggle.
the biggest Problem is the kind of regex authelia uses. I did not find any direct documentation about it, so I had to go trail&error on the escaping of chars.
Obviosly one don't hat to escape a "/", but a "?" has to be escaped. Should be made clearer in the documentation (or i completly missed the part).

### My solution that made PrivateBin working for me
(except the "comment" function, since this is a POST to "/"...,)

I have to "bypass" the following resources, so people can open a paste-link without the need of authorisation against authelia:
```
- domain: bin.domain.tld
      policy: bypass
      resources:
        - '^/\?[a-z0-9]{16}'
        - '^/css/.*'
        - '^/js/.*'
        - '^/i18n/.*'
        - '^/img/.*'
        - '^/manifest.json'
        - '^/\?pasteid.*$'
```

Thank You again james
