### DISCUSSION TITLE
Authelia is working but spammed error in log

### DISCUSSION THREAD

**Discussion by pinkfloydFR** [authelia/authelia#5344] [Q&A] [answered]
Hi,

I currently have a working authelia docker with a traefik docker with Ubuntu Server 22.04.
All docker are up to date.

authelia docker : 172.16.0.4
traefik docker : 172.16.0.24

```
docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }} {{range .NetworkSettings.Networks}} {{.IPAddress}}{{end}}' ;
traefik  172.16.0.24
authelia_redis_pf  172.16.0.7
authelia_redis_df  172.16.0.5
authelia_pf  172.16.64.2 172.16.0.22
authelia_df  172.16.48.2 172.16.0.4
```

![image](https://user-images.githubusercontent.com/49475899/235387287-65c2ff0d-a760-4473-a300-16c81d2c820f.png)

My authelia is working fine, BUT my log is spammed with this message : 

**error="read tcp 172.16.0.4:9091->172.16.0.24:40282: i/o timeout" method=GET path=/ remote_ip=172.16.0.24**

Complete message : 

```
time="2023-05-01T02:48:35+02:00" level=error msg="Request timeout occurred while handling request from client." 
error="read tcp 172.16.0.4:9091->172.16.0.24:40282: i/o timeout" method=GET path=/ remote_ip=172.16.0.24
stack="github.com/authelia/authelia/v4/internal/server/handlers.go:71
handleError.func2\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2824
(*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2266
(*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224
(*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196
(*workerPool).getCh.func1\nruntime/asm_amd64.s:1594
```

Here is my authelia config yaml 👍 
```
---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: xxxxx
default_redirection_url: https://home.MYDOMAIN.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: error

totp:
  issuer: authelia_df

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: two_factor
  rules:
  [...]
    - domain: "*"
      networks:
        - 192.168.0.0/24
        - 172.17.0.0/24
        - 172.16.0.0/24
      policy: bypass

session:
  name: authelia_df_session
  secret: xxxxxx
  expiration: 3600  # 1 hour
  inactivity: 3600  # 5 minutes
  remember_me_duration: 1M  # 1 month
  domain: MYDOMAIN.com  # Should match whatever your root protected domain is

  redis:
    host: authelia_redis_df
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: XXXX
  local:
    path: /config/db.sqlite3
```

Here is my authelia docker compose :
```
version: '3.3'
services:

  authelia_df:
    image: authelia/authelia
    container_name: authelia_df
    volumes:
      - $PWD/df_config:/config
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - PUID=1018
      - PGID=1020
      - TZ=Europe/Paris
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia_df.rule=Host(`authelia_df.MYDOMAIN.com`)'
      - 'traefik.http.routers.authelia_df.entrypoints=websecure'
      - 'traefik.http.routers.authelia_df.tls=true'
      - 'traefik.http.routers.authelia_df.middlewares=secure-headers@file'
      - 'traefik.http.middlewares.authelia_df.forwardauth.address=http://authelia_df:9091/api/verify?rd=https://authelia_df.MYDOMAIN.com'
      - 'traefik.http.middlewares.authelia_df.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia_df.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - 'traefik.http.services.authelia_df.loadbalancer.server.port=9091'
    networks:
      - authelia_df
      - traefik
```

Strange fact : 
the port tried to be contacted change everytime : 
error="read tcp 172.16.0.4:9091->172.16.0.24:40282: i/o timeout"
error="read tcp 172.16.0.4:9091->172.16.0.24:53632: i/o timeout"
error="read tcp 172.16.0.4:9091->172.16.0.24:38120: i/o timeout"

don't know if this normal too.

How can i correct this ? Thanks a lot !

**Comment by james-d-elliott** [comment, marked as answer]
This indicates a foreign client is taking longer than the configured server timeout to send the content of their request. Likely causes for this error showing up are:

- A overly restrictive read timeout configured for the server.
- Bad actors sending large payloads or taking a long time to send them.
- Clients sending large payloads (legitimate) or taking a long time to send them.
- The request being interrupted by another party i.e. a firewall or proxy.

Things to look at further:

- Configuration Settings (detailed below).
- Determine the service at the IP on the RIGHT side, most likely your proxy, if not find out what it is. If it is the proxy determine if there are any logs correlating with the ports on the RIGHT side.
- Proxy Logs (try setting the log level to debug).
- What the client browser is doing if you can adequately replicate it reliably i.e. look at the following things:
    - Console in the Browser Dev Tools
    - Network tab in the Browser Dev Tools

By default the server read timeout is 6s or 2s depending on version, and can be configured by looking at the server configuration guide:

https://www.authelia.com/configuration/miscellaneous/server/

This has also been asked before: https://github.com/authelia/authelia/discussions?discussions_q=read+tcp+i%2Fo+timeout

**Comment by pinkfloydFR** [comment]
Thanks for the response ! Will try to change the timeout.

And sorry, despite my search, doesn't found the already asked !

**Reply by james-d-elliott** [reply]
Yeah it's not a problem, only one of those question results actually is relevant, also I mainly included it as a means to maybe helping you in the future to find what you're looking for. If you look at my search terms it probably makes it clearer how you messed up the search. At least I think it should?

I have also updated the response to include some likely causes.

**Reply by pinkfloydFR** [reply]
Thanks, will analyse later with your tips !

**Comment by pinkfloydFR** [comment]
Tried : 
```
 timeouts:
    read: 15s
    write: 15s
    idle: 30s
```
But problem not solved, and it's strange cause each docker are on the same machine, and tested in local, so the timeouts should not be reached...

I know that : 
'That would indicate the body of the request is taking longer than 15s to send, or the connection was abruptly closed by the client during transmission. You may want to look at the traefik logs as it may shed light.

This behavior shouldn't adversely affect anything, should just protect you from bad requests.'

As my traefik log show no error, there is not option to hide this message from authelia ?

Thanks again btw !
