### DISCUSSION TITLE
How to protect a directory and restrict access by groups

### DISCUSSION THREAD

**Discussion by yremac** [authelia/authelia#5398] [Q&A]
I want to protect voultwarden's 2fa /admin directory and restrict access to everyone except the admins group, but with my attempts to set the admins group, other users can still access even without 2fa configured.  If I configure for the entire domain, then everything works as it should

**Comment by james-d-elliott** [comment]
Three rules, the first rule is your rule allowing the admins access for the resource path, second is denying it for everyone, third is the rule which applies to everything else.

**Reply by yremac** [reply]
Thank you, using this configuration, I managed to close access to /admin for everyone, except for the admins group

```
 - domain: bitw.example.com
      resources:
        - "^*/admin.*$"
      policy: two_factor
      subject:
        - "group:admins"

    - domain: bitw.example.com
      resources:
        - "^*/admin.*$"
      policy: deny

    - domain: bitw.example.com
      policy: bypass

```
