### DISCUSSION TITLE
Samba Authentication Backend

### DISCUSSION THREAD

**Discussion by JoaoCeni** [authelia/authelia#5434] [Troubleshooting] [answered]
I can't make authelia authenticate users from specific groups, only user from specific OUs.

I am using Authelia docker image sha256:35d46b7d27f78ebdfc8b043137f3d4afce4c7628e9113da8beaf65fe87883f03 (latest as of right now)

My infrastructure uses a SAMBA ldap server for folder shares and active directory.

a sample of my configuration.yml of the relative section

```
authentication_backend:
  disable_reset_password: true
  refresh_interval: 5m
  ldap:
    implementation: activedirectory
    url: ldap://x.x.x.x:xxxx
    timeout: 5s
    start_tls: false
    tls:
      server_name: ldap.xdomain.local
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: DC=xdomain,DC=local
    username_attribute: sAMAccountName
    additional_users_dn: OU=AUTHELIA,OU=SYSTEMS
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(pwdLastSet=0)))
    additional_groups_dn: OU=AUTHELIA,OU=SYSTEMS
    groups_filter: (&(member={dn})(|(sAMAccountType=268435456)(sAMAccountType=536870912)))
    group_name_attribute: sAMAccountName
    mail_attribute: mail
    display_name_attribute: displayName
    user: cn=authelia_ldap_example_user,ou=authelia,ou=systems,dc=xdomain,dc=local
    password: xxxsafepasswordxxx
```

    
Now, with this config, users that are located at OU=AUTHELIA,OU=SYSTEMS,DC=xdomain,DC=local are able to login normally.
The problem is, I have a group named GRP_AUTHELIA under the same path, and I can't for the life of me make authelia recognize it's members to login aswell.

I tried an outrageous number of combinations of different values for "additional_groups_dn", "groups_filter" and "group_name_attribute" following [this](https://www.authelia.com/configuration/first-factor/ldap/#groups-filter-replacements), [this](https://www.authelia.com/reference/guides/ldap/) and [this](https://github.com/authelia/authelia/blob/master/config.template.yml). Including using `group_name_attribute: cn` `additional_groups_dn: CN=GRP_AUTHELIA,OU=AUTHELIA,OU=SYSTEMS`

Users that are members of GRP_AUTHELIA just can't login, unless I place them at OU=AUTHELIA,OU=SYSTEMS,DC=xdomain,DC=local ;/

Authelia logs always give me this:

time="2023-05-13T13:07:16-04:00" level=debug msg="Mark 1FA authentication attempt made by user 'exampleuser'" method=POST path=/api/firstfactor remote_ip=xxx.xxx.xxx.xxx

time="2023-05-13T13:07:16-04:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'exampleuser': user not found" method=POST path=/api/firstfactor remote_ip=xxx.xxx.xxx.xxx stack="github.com/authelia/authelia/v4/internal/handlers/response.go:266           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:54 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54           (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                            (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                             (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                    goexit"

On the same infrasctructure I host a nextcloud connected to the same ldap, it uses the following to find users from the GRP_NCEXMAPLE located at :OU=NC,OU=SYSTEMS,DC=xdomain,DC=local
`(&(&(|(objectclass=person))(|(|(memberof=CN=GRP_NCEXAMPLE,OU=NC,OU=SYSTEMS,DC=xdomain,DC=local)(primaryGroupID=10166))))(samaccountname=%uid))`
