### DISCUSSION TITLE
There was an issue resetting the password

### DISCUSSION THREAD

**Discussion by Junto026** [authelia/authelia#5519] [Q&A] [answered]
The error occurs after receiving the password when trying to enter a new one.

I'm not doing anything fancy so I suspect I'm missing a dependent configuration. I'm using file authentication_backend.  The same browser/session is being used for both requesting the reset email and entering the new password.  

My issue and log error message is the same as this issue https://github.com/authelia/authelia/issues/3516.

> 2023-06-04 11:15:03 time="2023-06-04T11:15:03-04:00" level=error msg="no identity verification process has been initiated" method=POST path=/api/reset-password remote_ip=192.168.32.1 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:65          (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/handler_reset_password_step2.go:20 ResetPasswordPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                    (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                   SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                   SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                   SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                     (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                      (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                                   (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                                (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                                (*workerPool).getCh.func1\nruntime/asm_arm64.s:1172                                                             goexit"

Authelia webGUI can be reached at authelia.<redacted>.cloud.  And here is my session configuration section:

```
session:
  name: authelia_session ## The name of the session cookie.
  domain: <redacted>.cloud
  same_site: lax ## Sets the Cookie SameSite value. Possible options are none, lax, or strict.
  secret: <redacted> ## The secret to encrypt the session data. This is only used with Redis / Redis Sentinel.
  expiration: 1h ## The time before the cookie expires and the session is destroyed if remember me IS NOT selected.
  inactivity: 15m
  remember_me_duration: -1 ## 1M default; Value of -1 disables remember me.
```

**Comment by james-d-elliott** [comment]
Looks like the domain doesn't match the authelia domain and/or is not a suffix of it.

**Comment by Junto026** [comment]
The Authelia domain is Authelia.redacted.cloud.  My session section just has the top-level redacted.cloud written.  Does it need to be set up differently?

**Reply by james-d-elliott** [reply]
Sounds right. You may need to show more comprehensive logs then, you said it was `authelia.cloud`. Full debug or trace logs, make sure to follow the log sanitization guide. Assuming you're only using `https` as noted in the requirements?

**Comment by Junto026** [comment]
Here is a log run for ~1m, then I tried doing a password reset around 2023-06-09T00:20:50-04:00 which showed "There was an issue resetting the password" on the webGUI.  

I then clicked the button on the webGUI two more times after that (at 2023-06-09T00:21:13-04:00 and 2023-06-09T00:21:20-04:00), which is when the log message from my original post shows up.  So, the message in my OP only shows up after the first attempt to submit a new password.

[authelia.log](https://github.com/authelia/authelia/files/11702294/authelia.log)

**Comment by Junto026** [comment]
Oh, and I've made everything I possibly can HTTPS with LetsEncrypt certificates.  There is some protected apps that only do HTTP.

HTTPS --> Home Router --> NGINX on Host (adds XFF) --> NGINX in Docker --> Usually HTTPS Proxy Pass to protected app, sometimes HTTP when the protected app doesn't support it.

**Comment by Junto026** [comment]
Upon closer inspection, the original error message I posted above is a red herring.  What is actually happening is that Authelia is exiting with error code 137 and restarting.  Then if you the user re-submits the new password a second time, it complains that no password reset process was initiated (since it just restarted).

So the exiting with code 137 needs to be looked into.  I have log set to trace but I'm not seeing anything indicating the cause of the error.  Where else could I look?

![Screen Shot 2023-06-20 at 1 23 16 PM](https://github.com/authelia/authelia/assets/88695895/9ba5d59b-283f-4fc8-b365-8b6dfff843c9)

**Reply by james-d-elliott** [reply]
We never exit with that  code, sounds like something external is killing it.

**Reply by james-d-elliott** [reply]
Maybe show your auth backend config?

**Reply by Junto026** [reply]
Oh interesting, not the response I expected but very helpful.  I'm using Docker Desktop for MacOS and it looks like Docker is killing the Authelia each time I try to reset a password.  Some googling says it can be caused if a container consumes more memory than it is allowed.  There might be other causes too.  I'll have to look through the Docker logs.

When I have time I'll try to identify the cause and report back here.  In the meantime here is my configuration.yml, in case something jumps out to a seasoned eye.

[configuration-sanitized.yml.txt](https://github.com/authelia/authelia/files/11818651/configuration-sanitized.yml.txt)

**Reply by james-d-elliott** [reply, marked as answer]
Looks like you've mixed the legacy config options with the modern docs. Try adjusting your password config:

```yaml
  file: 
  ## File (Authentication Provider)
    path: /config/users_database.yml
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16
```

Or:

```yaml
  file: 
  ## File (Authentication Provider)
    path: /config/users_database.yml
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: argon2id
      iterations: 3
      memory: 64
      parallelism: 4
      key_length: 32
      salt_length: 16
```
