### DISCUSSION TITLE
Generic access_control

### DISCUSSION THREAD

**Discussion by c-dst** [authelia/authelia#5550] [Q&A] [answered]
Hi, 

I am looking to create a generic access control list for users. 
Which allows different users to have access to a domain but only a restricted part of the URL path. 

Example: User 1 (login : `user1`) should only be able to access `https://my.mydomain.tld/user1/`

I have several users, and I don't want to create an acl for every user, so is it possible to declare a generic acl like :

```
 - domain: 
     - my.mydomain.tld 
   policy: one_factor 
   resources: 
     - '^/{{ username }}/.*$' 
   subject: 
     - "user:{{ username}}"
```

Where `{{ username }}` would be a template representing the authenticated username. 

Thanks. 
--
Chris.
