### DISCUSSION TITLE
local storage profider not working, keeps asking for postgres options

### DISCUSSION THREAD

**Discussion by marlop352** [authelia/authelia#5606] [Troubleshooting] [answered]
on a RPi4 with an aarch64 OS with this docker compose:
```
---
version: "3.8"
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:master
    expose:
      - 9091
    volumes:
      - './config:/config'
      - './secrets:/secrets'
    networks:
      - rede
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /secrets/STORAGE_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY


networks:
  rede:
    name: rede
    external: true
```

and this config file:
```
---
theme: dark
default_redirection_url: https://www.domain.com/
default_2fa_method: "totp"

server:
  address: 'tcp://0.0.0.0:9091'
  asset_path: /config/assets/
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false

log:
  level: debug
  format: json
  file_path: /config/logs/authelia.%d.log
  keep_stdout: false

telemetry:
  metrics:
    enabled: false
    address: tcp://0.0.0.0:9959

totp:
  disable: false
  issuer: domain.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 0
  secret_size: 32

webauthn:
  disable: false
  timeout: 60s
  display_name: domain
  attestation_conveyance_preference: indirect
  user_verification: required

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  file:
    path: /config/users_database.yaml
    watch: true
    password:
      algorithm: bcrypt
      bcrypt:
        variant: standard
        cost: 12

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: deny
  networks:
    - name: net
      networks:
        - 192.168.0.0/24
  rules:
    - domain: '*.domain.com'
      policy: bypass
      networks:
        - net
    - domain: '*.domain.com'
      subject:
        - 'group:admins'
      policy: two_factor

session:
  name: domain_auth_session
  domain: domain.com
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me: 1M

regulation:
  max_retries: 5
  find_time: 5m
  ban_time: 15m

storage:
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
```

I'm getting this error:
```
time="2023-06-25T16:20:13-03:00" level=error msg="Configuration: storage: postgres: option 'address' is required"
time="2023-06-25T16:20:13-03:00" level=error msg="Configuration: storage: postgres: option 'username' and 'password' are required"
time="2023-06-25T16:20:13-03:00" level=error msg="Configuration: storage: postgres: option 'database' is required"
time="2023-06-25T16:20:13-03:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

my directory structure is this:
```
.
├── config
│   ├── configuration.yml
│   └── users_database.yaml
├── docker-compose.yml
└── secrets
    ├── JWT_SECRET
    ├── SESSION_SECRET
    ├── STORAGE_ENCRYPTION_KEY
    └── STORAGE_PASSWORD
```

(I'm also having the same problem with authelia/authelia:latest)
Am I overlooking something dumb or is this a bug?
