### DISCUSSION TITLE
LDAP Result Code 49 \"Invalid Credentials\": 80090308

### DISCUSSION THREAD

**Discussion by NebojsaMart** [authelia/authelia#5688] [General]
Hello Authelia,
we really like using Authelia, but now we are trying to integrate Authelia with our Azure Secure LDAP and getting continuously  the LDAP Result Code 49 \"Invalid Credentials\": 80090308 ERROR, I have tried everything to troubleshoot it but without success, the deployment is done via Helm chart the official one, I will post our yaml setup here can someone tell me what am I missing here. 

```yaml
 values:
    domain: example.localhost
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
      pod:
        extraVolumeMounts:
          - mountPath: /config/users_database.yml
            subPath: users_database.yml
            name: users-database
        extraVolumes:
          - name: users-database
            configMap:
              name: users-database
    configMap:
      theme: light
      access_control:
        default_policy: one_factor
      session:
        redis:
          host: redis-authelia-master
      storage:
        postgres:
          enabled: false
        local:
          enabled: true
      authentication_backend:
        password_reset:
          disable: true
        ldap:
          enabled: true
          enabledSecret: true
          implementation: activedirectory
          url: ldaps://ldap.example.com
          tls:
            server_name: example.com
            skip_verify: false
            minimum_version: TLS1.2
            maximum_version: TLS1.3
            certificate_chain: |
              -----BEGIN CERTIFICATE-----
              -----END CERTIFICATE-----
              -----BEGIN CERTIFICATE-----
              -----END CERTIFICATE-----
            private_key: |
              -----BEGIN RSA PRIVATE KEY-----
              -----END RSA PRIVATE KEY-----
          base_dn: dc=example,dc=com
          username_attribute: sAMAccountName
          additional_users_dn: OU=Users
          mail_attribute: mail
          users_filter: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
          additional_groups_dn: OU=Groups
          groups_filter: (&(objectCategory=person)(objectClass=user))
          display_name_attribute: displayname
          group_name_attribute: cn
          user: cn=authelia,dc=example,dc=com
        file:
          enabled: false
      notifier:
        smtp:
          enabled: false
        filesystem:
          enabled: true
    secret:
      mountPath: /secrets
      excludeVolumeAndMounts: false
      ldap:
        key: LDAP_PASSWORD
        value: supersecret
        filename: LDAP_PASSWORD
        path: LDAP_PASSWORD
```

**Comment by james-d-elliott** [comment]
Can you use `ldapsearch` with the same bind username and password successfully?

**Reply by NebojsaMart** [reply]
Hi Thanks for the reply, when I do the ldapsearch im getting the following: 

ldapsearch -x -b "dc=examaple,dc=com" -H ldaps://ip

ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)

But the interesting thing is that i can connect to it with the Apache directory studio, which is working fine.

**Reply by james-d-elliott** [reply]
How are you validating the credentials you're using? It's the server responding with the credentials error. I don't see a password defined, assuming it's via a secret?

**Reply by NebojsaMart** [reply]
Regarding the ldapsearch command im adding the password after it takes 10 min until it brings the ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1).

In the Kubernetes cluster from the authelia pod Im getting the following:
```
│ time="2023-07-18T11:09:03Z" level=info msg="Authelia v4.37.5 is starting"                                                                                                                                       │
│ time="2023-07-18T11:09:03Z" level=info msg="Log severity set to info"                                                                                                                                           │
│ time="2023-07-18T11:09:03Z" level=info msg="Storage schema is being checked for updates"                                                                                                                        │
│ time="2023-07-18T11:09:03Z" level=info msg="Storage schema migration from 0 to 7 is being attempted"                                                                                                            │
│ time="2023-07-18T11:09:03Z" level=info msg="Storage schema migration from 0 to 7 is complete"                                                                                                                   │
│ time="2023-07-18T11:09:04Z" level=error msg="Failure running the user provider startup check: bind failed with error: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C090439, comment: A │
│ cceptSecurityContext error, data 52e, v4563\x00" stack="github.com/authelia/authelia/v4/internal/commands/root.go:287 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun │
│ \ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go │
│ :968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594      │
│                                  goexit"                                                                                                                                                                        │
│ time="2023-07-18T11:09:04Z" level=fatal msg="The following providers had fatal failures during startup: user" stack="github.com/authelia/authelia/v4/internal/commands/root.go:309 doStartupChecks\ngithub.com/ │
│ authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                  │
│ (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                  │
│                           main\nruntime/asm_amd64.s:1594   
```

On the yaml Helm chart  I tried to add the password as following:
```yaml
    secret:
      mountPath: /secrets
      excludeVolumeAndMounts: false
      ldap:
        key: LDAP_PASSWORD
        value: supersecret <---- putting the password here 
        filename: LDAP_PASSWORD
        path: LDAP_PASSWORD
```
I even tried to add it directly as follow:

user: cn=authelia,dc=example,dc=com
password: mypassword

bouth didnt work, so im not quite sure what to do next.
