### DISCUSSION TITLE
Authelia not redirecting properly after auth in Firefox

### DISCUSSION THREAD

**Discussion by ADeadPixel** [authelia/authelia#5700] [Troubleshooting] [answered]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

2.9.22

### Issue / Context
Howdy, I am unable to get past Authelia if I use Firefox. I am currently rebuilding my server (long story) and I'm at the point where I'm standing up a lot of my docker containers. I added Authelia on my last installation pretty late in the game and it was a real blessing so I figured I would re-add it on this new server in the beginning. I get it setup no problem and I even implemented the recommend mounted paths which really cleans up the NGINX configuration in NPM. Everything is going well until I start testing Authelia in-front of the containers. Nothing I test is working. I thought I messed something up in the config (it wouldn't be the first time) so I dove in. Well , I tore my hair out for a few hours until I realized I didn't try a different browser yet. I loaded up Chrome and it worked first try... I have dug through my config and other misc settings but I cannot find anything that would lead to Chrome working when Firefox fails. 

I'm by no means an expert on this but I think that this may be a bug somewhere.

I'm using the stock .conf files provided in the Authelia documentation (with the server IP and auth CNAME replaced of course). I'm also replicating the NGINX configuration implementation as shown in the docs and it is working in Chrome.

I've attached my config and the logs below showing the difference between a firefox attempt and a chrome attempt.

I am wondering if this could be an issue with my csp setting in my config but according to the docs it shouldn't be an issue and I can't find others having this issue.

I'm not sure if it is related but my TOTP also does not work (regardless of browser). I'm using Bitwarden.

### Reproduction

- Setup clean Authelia installation
- Configure snippets in NPM based on documentation with updates relevant to your system
- Run Authelia and put in the NGINX config in NPM for Authelia and the service to be protected
- Try to get authenticated/authorized in Firefox -> Denied
- Try to get authenticated/authorized in Chrome - Passed

### Expectations

Authelia should work regardless of browser

### Configuration (Authelia)

```yaml
# yamllint disable rule:comments-indentation
###############################################################################
#                           Authelia Configuration                            #
###############################################################################
theme: dark

jwt_secret: [REDACTED]

default_redirection_url: http://www.example.com/ (I have this set to my actual domain in my real config)

default_2fa_method: totp

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

  tls:
    key: ""
    certificate: ""
    client_certificates: []

  headers:
    # I think the firefox issue may be here
    csp_template: ""

log:
  level: debug

telemetry:
  metrics:
    enabled: false
    address: tcp://0.0.0.0:9959

totp:
  disable: false
  issuer: auth.example.com (I have this set to my actual domain in my real config)
  algorithm: sha256
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

duo_api:
  disable: true
  hostname: api-123456789.example.com
  integration_key: ABCDEF
  secret_key: 1234567890abcdefghifjkl
  enable_self_enrollment: false

ntp:
  address: "server 0.north-america.pool.ntp.org"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m

  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
    
  zxcvbn:
    enabled: false
    min_score: 3

access_control:
  default_policy: deny
  networks:
  - name: internal
    networks:
    ## Primary Network
    - '192.168.1.0/24'
    ## Guest Network
    - '192.168.10.0/24'
    ## VM Network
    - '192.168.50.0/24'

  rules:
  # - domain: '*.example.com/ (I have this set to my actual domain in my real config)'
  #   policy: bypass
  #   networks: 
  #     - 'internal'
  - domain: 'auth.example.com/ (I have this set to my actual domain in my real config)'
    policy: bypass
  - domain: '*.example.com/ (I have this set to my actual domain in my real config)'
    policy: one_factor
    subject:
      - 'group:admins'
  - domain: '*.example.com/ (I have this set to my actual domain in my real config)'
    policy: one_factor
    subject:
      - 'group:family'
 
session:
  name: authelia_session
  domain: example.com (I have this set to my actual domain in my real config)
  same_site: lax
  secret: [REDACTED]
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M

  redis:
    host: redis (this is actually an IP address not a docker hostname)
    port: 6379
    password: [REDACTED]
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  #shortened for testing purposes
  max_retries: 5
  find_time: 5m
  ban_time: 10m

storage:
  encryption_key: [REDACTED]
  mysql:
    host: mysql (this is actually an IP address not a docker hostname)
    port: 3306
    database: authelia
    username: [REDACTED]
    password: [REDACTED]
    #timeout: 5s

notifier:
  disable_startup_check: false
  smtp:
    host: [REDACTED]
    port: 587
    username: [REDACTED]
    password: [REDACTED]
    sender: [REDACTED]
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false

    tls:
      skip_verify: false    
      minimum_version: TLS1.2

...
```

### Logs (Authelia)

```shell
### Authelia Log - Using Firefox
time="2023-07-20T10:51:01-05:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-07-20T10:51:01-05:00" level=info msg="Log severity set to debug"
time="2023-07-20T10:51:01-05:00" level=info msg="Storage schema is being checked for updates"
time="2023-07-20T10:51:01-05:00" level=info msg="Storage schema is already up to date"
time="2023-07-20T10:51:01-05:00" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:587"
time="2023-07-20T10:51:01-05:00" level=debug msg="Notifier SMTP client connected successfully"
time="2023-07-20T10:51:01-05:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: smtp.gmail.com), attempting"
time="2023-07-20T10:51:01-05:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2023-07-20T10:51:01-05:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"
time="2023-07-20T10:51:01-05:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2023-07-20T10:51:01-05:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2023-07-20T10:51:01-05:00" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
time="2023-07-20T10:51:01-05:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2023-07-20T10:51:12-05:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.1.253 and object https://destination.example.com/ (method GET)."
time="2023-07-20T10:51:12-05:00" level=info msg="Access to https://destination.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.1.253
time="2023-07-20T10:51:13-05:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.1.253 and object https://destination.example.com/sw.js (method GET)."
time="2023-07-20T10:51:13-05:00" level=info msg="Access to https://destination.example.com/sw.js (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.1.253
time="2023-07-20T10:51:25-05:00" level=debug msg="Mark 1FA authentication attempt made by user 'ADeadPixel'" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:51:25-05:00" level=debug msg="Successful 1FA authentication attempt made by user 'ADeadPixel'" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:51:25-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.1 and object https://destination.example.com/ (method )."
time="2023-07-20T10:51:25-05:00" level=debug msg="Required level for the URL https://destination.example.com/ is 1" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:51:25-05:00" level=debug msg="Redirection URL https://destination.example.com/ is safe" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:51:26-05:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.1.253 and object https://destination.example.com/ (method GET)."
time="2023-07-20T10:51:26-05:00" level=info msg="Access to https://destination.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.1.253
time="2023-07-20T10:51:27-05:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.1.253 and object https://destination.example.com/sw.js (method GET)."
time="2023-07-20T10:51:27-05:00" level=info msg="Access to https://destination.example.com/sw.js (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.1.253


### Authelia Log - Using Chrome
time="2023-07-20T10:54:53-05:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-07-20T10:54:53-05:00" level=info msg="Log severity set to debug"
time="2023-07-20T10:54:53-05:00" level=info msg="Storage schema is being checked for updates"
time="2023-07-20T10:54:53-05:00" level=info msg="Storage schema is already up to date"
time="2023-07-20T10:54:53-05:00" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:587"
time="2023-07-20T10:54:53-05:00" level=debug msg="Notifier SMTP client connected successfully"
time="2023-07-20T10:54:53-05:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: smtp.gmail.com), attempting"
time="2023-07-20T10:54:53-05:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2023-07-20T10:54:53-05:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"
time="2023-07-20T10:54:53-05:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2023-07-20T10:54:53-05:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2023-07-20T10:54:53-05:00" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
time="2023-07-20T10:54:53-05:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2023-07-20T10:55:14-05:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.1.253 and object https://destination.example.com/ (method GET)."
time="2023-07-20T10:55:14-05:00" level=info msg="Access to https://destination.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=192.168.1.253
time="2023-07-20T10:55:22-05:00" level=debug msg="Mark 1FA authentication attempt made by user 'ADeadPixel'" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:55:22-05:00" level=debug msg="Successful 1FA authentication attempt made by user 'ADeadPixel'" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:55:22-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.1 and object https://destination.example.com/ (method )."
time="2023-07-20T10:55:22-05:00" level=debug msg="Required level for the URL https://destination.example.com/ is 1" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:55:22-05:00" level=debug msg="Redirection URL https://destination.example.com/ is safe" method=POST path=/api/firstfactor remote_ip=192.168.1.1
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/ (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/login (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/logo_stacked.svg (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/api/v1/auth/me (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/api/v1/status (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/api/v1/backdrops (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/api/v1/auth/me (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/api/v1/settings/public (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/site.webmanifest (method GET)."
time="2023-07-20T10:55:23-05:00" level=debug msg="Check authorization of subject username=ADeadPixel groups=admins ip=192.168.1.253 and object https://destination.example.com/android-chrome-192x192.png (method GET)."
```

### Logs (Proxy / Application)

```shell
Nothing to note
```

### Documentation

NPM Guide: https://www.authelia.com/integration/proxies/nginx-proxy-manager/

NGINX Snippets: https://www.authelia.com/integration/proxies/nginx/#supporting-configuration-snippets

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
