### DISCUSSION TITLE
WebAuthnUser does not have an ID

### DISCUSSION THREAD

**Discussion by aumer-amr** [authelia/authelia#5710] [Troubleshooting] [answered]
### Version

untagged-v4.37.5
tag: master@sha256:a3647c3dd136402745c7639e446944004145630c822f27e22f999c414c234d2f

### Deployment Method

Kubernetes

### Reverse Proxy

NGINX

### Reverse Proxy Version

4.7.1

### Description

It's currently impossible to register a new device on the latest chrome & edge (maybe webauthn has been updated?)
When clicking the link from the email  `https://auth.domain.tld/webauthn/register?token=<jwt-token>`, the error `You cancelled the attestation request.` popups immediately indicating an FailureUserConsent. 

The finish callback on the registration page after clicking the link from the email returns an object with this information:
```
        {
            "challenge": "8LQOpss5pvIzZ5CZUDzuhH7f9RM4c8QTLyewncCFxvM=",
            "rp": {
                "name": "aumer.dev",
                "id": "auth.domain.tld"
            },
            "user": {
                "name": "aumer",
                "displayName": "Aumer",
                "id": ""
            },
            "pubKeyCredParams": [
                {
                    "type": "public-key",
                    "alg": -7
                },
                {
                    "type": "public-key",
                    "alg": -35
                },
                {
                    "type": "public-key",
                    "alg": -36
                },
                {
                    "type": "public-key",
                    "alg": -257
                },
                {
                    "type": "public-key",
                    "alg": -258
                },
                {
                    "type": "public-key",
                    "alg": -259
                },
                {
                    "type": "public-key",
                    "alg": -37
                },
                {
                    "type": "public-key",
                    "alg": -38
                },
                {
                    "type": "public-key",
                    "alg": -39
                },
                {
                    "type": "public-key",
                    "alg": -8
                }
            ],
            "authenticatorSelection": {
                "authenticatorAttachment": "cross-platform",
                "requireResidentKey": false,
                "userVerification": "discouraged"
            },
            "timeout": 60000,
            "attestation": "none"
        }
```

I noticed the `id` in the user object was empty, and looking at w3c if I [https://w3c.github.io/webauthn/#user-handle](https://w3c.github.io/webauthn/#user-handle) if I understand correctly this is a required field. 

Using the browsers console I was able to call the same function but with an id I grabbed from the example you get using [https://demo.yubico.com/webauthn-technical/registration](https://demo.yubico.com/webauthn-technical/registration). The function getBytesFromBase64 is yoinked from here [https://github.com/authelia/authelia/blob/efc19f270be969448ed74ab408cd298b47addf6c/web/src/utils/Base64.ts#L181](https://github.com/authelia/authelia/blob/efc19f270be969448ed74ab408cd298b47addf6c/web/src/utils/Base64.ts#L181)
```
        await navigator.credentials.create({
            publicKey: {
            "challenge": getBytesFromBase64("8LQOpss5pvIzZ5CZUDzuhH7f9RM4c8QTLyewncCFxvM="),
            "rp": {
                "name": "aumer.dev",
                "id": "auth.domain.tld"
            },
            "user": {
                "name": "aumer",
                "displayName": "Aumer",
                "id": getBytesFromBase64("bjd/FNPOlv81kHdE2zqe7AFUqx2G0aa+pVIoJQalUUg=")
            },
            "pubKeyCredParams": [
                {
                    "type": "public-key",
                    "alg": -7
                },
                {
                    "type": "public-key",
                    "alg": -35
                },
                {
                    "type": "public-key",
                    "alg": -36
                },
                {
                    "type": "public-key",
                    "alg": -257
                },
                {
                    "type": "public-key",
                    "alg": -258
                },
                {
                    "type": "public-key",
                    "alg": -259
                },
                {
                    "type": "public-key",
                    "alg": -37
                },
                {
                    "type": "public-key",
                    "alg": -38
                },
                {
                    "type": "public-key",
                    "alg": -39
                },
                {
                    "type": "public-key",
                    "alg": -8
                }
            ],
            "authenticatorSelection": {
                "authenticatorAttachment": "cross-platform",
                "requireResidentKey": false,
                "userVerification": "discouraged"
            },
            "timeout": 60000,
            "attestation": "none"
        }});
```
After this call in the console I successfully get the popup to use my security key.

I think the id would be required to add [here](https://github.com/authelia/authelia/blame/566a0d7fc71b450123ad33d350cd3890d311da82/internal/handlers/webauthn.go#L17) so it is put into the user object 

### Reproduction

1. Login with an user without an webauthn device linked to it (preferable a fresh user)
2. Click `Register device` and you should see the message `An email has been sent to your address to complete the process`
3. Click on the link inside the email which looks like `https://auth.domain.tld/webauthn/register?token=<jwt-token>`
4. The page should say `Touch your security key` however in the top right an error popup saying `You cancelled the attestation request`

### Expectations

I expect the popup to show that ask for my permission to use my security key, so I can successfully register it into my authelia account.

### Configuration (Authelia)

```yaml
configuration.yaml:
---
storage:
  encryption_key: ${SECRET_AUTHELIA_STORAGE_KEY}
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
  rules:
    - domain: "echo-server.${SECRET_DOMAIN}"
      policy: two_factor
      subject:
        - ["group:admins"]

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signing_algorithm: none

env:
---
AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN: ou=groups
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN: ou=people
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: ${SECRET_AUTHELIA_BASE_DN}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_DISPLAY_NAME_ATTRIBUTE: displayName
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER: (member={dn})
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUP_NAME_ATTRIBUTE: cn
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION: custom
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_MAIL_ATTRIBUTE: mail
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_START_TLS: "false"
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TIMEOUT: 5s
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_URL: ldap://lldap.system.svc.cluster.local:389
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERNAME_ATTRIBUTE: uid
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER: (&({username_attribute}={input})(objectClass=person))
      AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE: "true"
      AUTHELIA_AUTHENTICATION_BACKEND_REFRESH_INTERVAL: 1m
      AUTHELIA_DEFAULT_REDIRECTION_URL: https://auth.${SECRET_DOMAIN}
      AUTHELIA_DUO_API_DISABLE: "true"
      AUTHELIA_LOG_LEVEL: debug
      AUTHELIA_NOTIFIER_SMTP_HOST: smtp.gmail.com
      AUTHELIA_NOTIFIER_SMTP_PORT: "465"
      AUTHELIA_SERVER_DISABLE_HEALTHCHECK: "true"
      AUTHELIA_SERVER_PORT: &port 80
      AUTHELIA_SESSION_DOMAIN: ${SECRET_DOMAIN}
      AUTHELIA_SESSION_NAME: authelia-home-ops
      AUTHELIA_STORAGE_LOCAL_PATH: /data/db.sqlite3
      AUTHELIA_TELEMETRY_METRICS_ADDRESS: tcp://0.0.0.0:8080
      AUTHELIA_TELEMETRY_METRICS_ENABLED: "true"
      AUTHELIA_THEME: dark
      AUTHELIA_TOTP_ISSUER: authelia.com
      AUTHELIA_WEBAUTHN_DISABLE: "false"
      AUTHELIA_WEBAUTHN_DISPLAY_NAME: ${SECRET_DOMAIN}
      AUTHELIA_WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE: none
      AUTHELIA_WEBAUTHN_USER_VERIFICATION: discouraged
      SECRET_DOMAIN: ${SECRET_DOMAIN}
# App
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "{{ .lldap_user_dn }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .lldap_password }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .authelia_oidc_hmac_secret }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .authelia_oidc_issuer_private_key }}"
        AUTHELIA_JWT_SECRET: "{{ .authelia_jwt_secret }}"
        AUTHELIA_SESSION_SECRET: "{{ .authelia_session_secret }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .authelia_storage_encryption_key }}"
        AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .authelia_smtp_username }}"
        AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .authelia_smtp_password }}"
        AUTHELIA_NOTIFIER_SMTP_SENDER: "{{ .authelia_smtp_sender }}"
        # Clients
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .authelia_grafana_oauth_client_secret }}"
```

### Logs (Authelia)

```shell
kubectl logs --tail=1000 authelia-7647f8c7ff-94r4c -n system
---
chown: /config/configuration.yaml: Read-only file system
time="2023-07-25T17:19:34Z" level=warning msg="Configuration: configuration key 'server.port' is deprecated in 4.38.0 and has been replaced by 'server.address' when combined with the 'server.host' in the format of 'tcp://<host>:<port>': this should be automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2023-07-25T17:19:34Z" level=warning msg="Configuration: configuration key 'log_level' is deprecated in 4.30.0 and has been replaced by 'log.level': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2023-07-25T17:19:34Z" level=warning msg="Configuration: identity_providers: oidc: client 'grafana': option 'secret' is plaintext but it should be a hashed value as plaintext values are deprecated and will be removed when oidc becomes stable"
time="2023-07-25T17:19:34Z" level=info msg="Authelia untagged-v4.37.5 (master, 90d1901) is starting"
time="2023-07-25T17:19:34Z" level=info msg="Log severity set to debug"
time="2023-07-25T17:19:34Z" level=debug msg="Registering client grafana with policy two_factor (two_factor)"
time="2023-07-25T17:19:34Z" level=info msg="Storage schema is being checked for updates"
time="2023-07-25T17:19:34Z" level=info msg="Storage schema is already up to date"
time="2023-07-25T17:19:34Z" level=debug msg="LDAP Supported OIDs. Control Types: none. Extensions: 1.3.6.1.4.1.4203.1.11.1"
time="2023-07-25T17:19:40Z" level=warning msg="Could not read from the NTP server socket to validate the system time is properly synchronized: read udp 10.42.1.81:41347->162.159.200.1:123: i/o timeout"
time="2023-07-25T17:19:40Z" level=info msg="Listening for non-TLS connections on '[::]:80' path '/'" server=main service=server
time="2023-07-25T17:19:40Z" level=info msg="Startup complete"
time="2023-07-25T17:19:40Z" level=info msg="Listening for non-TLS connections on '[::]:8080' path '/metrics'" server=metrics service=server
time="2023-07-25T17:21:30Z" level=debug msg="Mark 1FA authentication attempt made by user 'aumer'" method=POST path=/api/firstfactor remote_ip=x.x.x.x
time="2023-07-25T17:21:30Z" level=debug msg="Successful 1FA authentication attempt made by user 'aumer'" method=POST path=/api/firstfactor remote_ip=x.x.x.x
time="2023-07-25T17:21:32Z" level=debug msg="Sending an email to user aumer (aumer@aumer.dev) to confirm identity for registering a device." method=POST path=/api/secondfactor/webauthn/identity/start remote_ip=x.x.x.x
```

### Documentation

https://w3c.github.io/webauthn/#user-handle
https://w3c.github.io/webauthn/#dictionary-user-credential-params
