### DISCUSSION TITLE
Redirection to login page after a sucessful login

### DISCUSSION THREAD

**Discussion by leruaa** [authelia/authelia#5792] [Troubleshooting]
Hi,

I use Authelia with Traefik on Docker for a while now and everything was woriking fine until recently.

Now when I try to login to my code-server instance, I'm being redirected to the login page. There are the Authelia logs :

```
time="2023-08-05T22:44:49+02:00" level=debug msg="Check authorization of subject username= groups= ip=90.xx.xx.xx and object https://code.example.com/ (method GET)."
time="2023-08-05T22:44:49+02:00" level=info msg="Access to https://code.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.example.com/?rd=https%3A%2F%2Fcode.example.com%2F&rm=GET" method=GET path=/api/verify remote_ip=90.xx.xx.xx
time="2023-08-05T22:45:15+02:00" level=debug msg="Mark 1FA authentication attempt made by user 'luke'" method=POST path=/api/firstfactor remote_ip=90.xx.xx.xx
time="2023-08-05T22:45:15+02:00" level=debug msg="Successful 1FA authentication attempt made by user 'luke'" method=POST path=/api/firstfactor remote_ip=90.xx.xx.xx
time="2023-08-05T22:45:15+02:00" level=debug msg="Check authorization of subject username=luke groups=admins,dev ip=90.xx.xx.xx and object https://code.example.com/ (method GET)."
time="2023-08-05T22:45:15+02:00" level=debug msg="Required level for the URL https://code.example.com/ is 1" method=POST path=/api/firstfactor remote_ip=90.xx.xx.xx
time="2023-08-05T22:45:15+02:00" level=debug msg="Redirection URL https://code.example.com/ is safe" method=POST path=/api/firstfactor remote_ip=90.xx.xx.xx
time="2023-08-05T22:45:16+02:00" level=debug msg="Check authorization of subject username=luke groups=admins,dev ip=90.xx.xx.xx and object https://code.example.com/ (method GET)."
time="2023-08-05T22:45:16+02:00" level=debug msg="Check authorization of subject username= groups= ip=90.xx.xx.xx and object https://code.example.com/?folder=/workspaces (method GET)."
time="2023-08-05T22:45:16+02:00" level=info msg="Access to https://code.example.com/?folder=/workspaces (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.example.com/?rd=https%3A%2F%2Fcode.example.com%2F%3Ffolder%3D%2Fworkspaces&rm=GET" method=GET path=/api/verify remote_ip=90.xx.xx.xx
```

Looking at `https://code.example.com/?folder=/workspaces` in Firefox dev tools I see this in the response cookies :

```
{
	"authelia_session": {
		"domain": "example.com",
		"expires": "2023-09-04T20:45:16.000Z",
		"httpOnly": true,
		"path": "/",
		"samesite": "Lax",
		"secure": true,
		"value": "MTp!RNT6$I!Gj0d$hxRmGszP1m3uO6D8"
	}
}
```

There is my Authelia config:

```
---
###############################################################
#                   Authelia configuration                    #
###############################################################

default_redirection_url: https://public.example.com
theme: auto

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: n.example.com
      policy: bypass
    - domain: media.example.com
      policy: bypass
    - domain: tasks.example.com
      policy: bypass
    - domain: rss.example.com
      policy: bypass
    - domain: code.example.com
      domain_regex: '^[0-9]+\.code\.example\.com$'
      policy: one_factor
    - domain: photos.example.com
      policy: one_factor

session:
  name: authelia_session
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
...
```
Authelia middleware in Traefik:
```
http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.example.com%2F
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
```

The thing is, my Docker containers are updated automatically and I don't know exactly when it stopped working.

Thanks in advance for your answers :)
