### DISCUSSION TITLE
Not redirecting to authentication -> 401 Unauthorized

### DISCUSSION THREAD

**Discussion by lucyannofrota** [authelia/authelia#5898] [Troubleshooting]
For some reason, the authentication window is been bypassed and I getting `401 Unauthorized` directly.

It seems to be well configured with traefik and works well if I authenticate the session at `auth.mydomain.com` first, and then try to access `secure.mydomain.com`.

I don't think this is a bug, but I can't find the solution.

My `docker-compose.yml`:
```
services:

  whoami_unsecure:
    networks:
      - proxy-internal
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`unsecure.mydomain.com`)
      - traefik.http.routers.whoami.entrypoints=web-secure
      - traefik.http.routers.whoami.tls.certresolver=myresolver     
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.middlewares=authelia@docker
     
  whoami_secure:
    networks:
      - proxy-internal
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoamis.rule=Host(`secure.mydomain.com`)
      - traefik.http.routers.whoamis.entrypoints=web-secure
      - traefik.http.routers.whoamis.tls.certresolver=myresolver
      - traefik.http.routers.whoamis.tls=true
      - traefik.http.routers.whoamis.middlewares=authelia@docker


  ################
  ### authelia ###
  ################

  authelia:
    networks:
      - proxy-internal
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.mydomain.com`)
      - traefik.http.routers.authelia.entrypoints=web-secure
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=myresolver
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.mydomain.com
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
```

My `configuration.yml`:

```
---
jwt_secret: <random_key1>
default_redirection_url: https://auth.mydomain.com

log:
  level: debug

totp:
  issuer: mydomain.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: unsecure.mydomain.com
      policy: bypass
    - domain: secure.mydomain.com
      policy: one_factor
    # - domain: "*.mydomain.com"
    #   policy: two_factor

session:
  name: authelia_session
  domain: mydomain.com
  same_site: lax
  secret: <random_key2>
  expiration: 1h
  inactivity: 5m
  remember_me_duration:  1M

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: <random_key3>
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt

```

Container log:
````
level=info msg="Authelia v4.37.5 is starting"
level=info msg="Log severity set to debug"
level=info msg="Storage schema is being checked for updates"
level=info msg="Storage schema is already up to date"
level=debug msg="notification provider: startup check skipped as it is disabled"
level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
level=debug msg="Check authorization of subject username= groups= ip=192.168.16.1 and object https://secure.mydomain.com/ (method GET)."
level=error msg="Configured Portal URL 'https://auth.' does not appear to be able to write cookies for the 'mydomain.com' domain" method=GET path=/api/verify remote_ip=192.168.16.1 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:215 handleUnauthorized\ngithub.com/authelia/authelia/v4/internal/handlers/handler_verify.go:490 VerifyGET.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54       (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16      SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:427                        (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                         (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                      (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                   (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                   (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                goexit"
level=debug msg="Check authorization of subject username= groups= ip=192.168.16.1 and object https://secure.mydomain.com/favicon.ico (method GET)."
level=error msg="Configured Portal URL 'https://auth.' does not appear to be able to write cookies for the 'mydomain.com' domain" method=GET path=/api/verify remote_ip=192.168.16.1 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:215 handleUnauthorized\ngithub.com/authelia/authelia/v4/internal/handlers/handler_verify.go:490 VerifyGET.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54       (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16      SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:427                        (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                         (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                      (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                   (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                   (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                goexit"
````

Here are some related issues/discussions that I found:
#4442, #4989, #4287

Although the problem seems to be the same as the ones above, I think I missed something else.
