### DISCUSSION TITLE
Authelia on subpath with Traefik

### DISCUSSION THREAD

**Discussion by papalozarou** [authelia/authelia#5899] [Troubleshooting] [answered]
Am tearing my hair out trying to get Authelia to work on a subpath, `/auth`, with Traefik. I've tried a number of different combinations but keep getting stuck with either:

1. `my.domain.com/auth` displaying the login page correctly but protected urls redirecting to `my.domain.com//?rd=https…` not `my.domain.com/auth?rd=https…`; and
2. `my.domain.com/auth` returning a 404 error, but protected urls redirecting correctly to `my.domain.com/auth?rd=https…` which also 404s.

In the first instance manually inserting `/auth` in the url will also redirect back to `my.domain.com//?rd=https…`.

My docker compose is below, where `${H_URL}` is `my.domain.com` and `${H_AUTH_URL}` is `my.domain.com/auth`. I have tried changing to just `Path` and `PathPrefix` in the docker labels of `authelia`, which gives me the second scenario above. Using `Host` and `PathPRefix` as below, I get the first scenario.

```
 traefik:
    image: traefik:latest
    […]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.traefik.rule=Host(`${H_URL}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=middleware-compression@file"
      - "traefik.http.routers.traefik.middlewares=middleware-rate-limit@file"
      - "traefik.http.routers.traefik.middlewares=middleware-security-headers@file"
      - "traefik.http.routers.traefik.middlewares=middleware-authentication@docker"
[…]
authelia:
    image: authelia/authelia:4.37.5
    […]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.authelia.rule=Host(`${H_URL}`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.authelia.middlewares=middleware-compression@file"
      - "traefik.http.routers.authelia.middlewares=middleware-rate-limit@file"
      - "traefik.http.routers.authelia.middlewares=middleware-security-headers@file"
      - "traefik.http.middlewares.middleware-authentication.forwardauth.address=http://authelia:9091/api/verify?rd=https://${H_AUTH_URL}"
      - "traefik.http.middlewares.middleware-authentication.forwardauth.authresponseheaders=Remote-User, Remote-Groups"
      - "traefik.http.middlewares.middleware-authentication.forwardauth.trustforwardheader=true"
```

Relevant bits of my authelia config:

```
server: 
  host: 0.0.0.0
  port: 9091
  path: "auth"
[…]
access_control:
  default_policy: deny
  rules:
    - domain: "my.domain.com"
      resources: 
        - "^/auth([/?].*)?$"
      policy: bypass
    - domain: "*.domain.com"
      policy: two_factor
```

I am probably missing something really simple so any help appreciated.
