### DISCUSSION TITLE
Traefik middleware forwardauth with Authelia & High availability

### DISCUSSION THREAD

**Discussion by kminhtri** [authelia/authelia#5927] [Q&A] [answered]
Hello,

I am trying to put Authelia with High Availability using the load balancer from Traefik. Here the config yml:
```yaml
http:
  routers:
      authelia:
        rule: Host(`auth.example.tld`)
        entryPoints: https
        service: authelia@file
        middlewares: securityHeaders@file
  services:
    authelia:
      loadBalancer:
        healthCheck:
          path: /api/health
          interval: "60s"
          timeout: "5s"
        servers:
          - url: http://192.168.0.1:9091/
          - url: http://192.168.0.2:9091/
 ```

Looks to works correctly, but when I want to use in a traefik middleware with forwardauth:

```yaml
   auth:
      forwardauth:
        address: https://auth.example.tld/api/verify?rd=https://auth.example.tld/
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
 ```

Authelia gives us a 403 status, I don't know how to handle High Availability in this case. Here some logs from Authelia and Traefik :
**Authelia logs :**
`level=info msg="Access to https://auth.example.tld/api/verify?rd=https://auth.example.tld/ is forbidden to user " method=GET path=/api/verify remote_ip=172.18.0.1
 traefik authelia load balancer "authforward"`

**Traefik logs :**
`time="2023-08-29T19:54:57+02:00" level=debug msg="Remote error https://auth.example.tld/api/verify?rd=https://auth.example.tld/. StatusCode: 403" middlewareType=ForwardedAuthType middlewareName=auth@file`

Thank you for your light and your answer 👍
