### DISCUSSION TITLE
Can't load secrets from the .env file

### DISCUSSION THREAD

**Discussion by stantios** [authelia/authelia#5928] [Q&A] [answered]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.7.4

### Description

I tried to spin up Authelia with docker-compose but it didn't wokr due to secrets not being configured. I ahve specified my secrets in a .env file and linked the correct environment variable in the configuration.yml but it still does not work.

I have masked the encryption key in the config file with '$hidden' and secret paths in the Authelia log with 'hidden_value' for security reasons.

### Reproduction

1. Crea

### Configuration (Authelia)

```yaml
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

theme: dark

jwt_secret: $AUTHELIA_JWT_SECRET_FILE

default_redirection_url: 'https://auth.example.com'

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: auth.example.com
      policy: bypass
    - domain: portainer.example.com
      policy: two_factor

session:
  name: authelia_session
  secret: $AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: example.com

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: $hidden
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.txt
```

### Logs (Authelia)

```shell
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'session.secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'jwt_secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'notifier.smtp.password': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret into key 'jwt_secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: option 'jwt_secret' is required"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: notifier: please ensure only one of the 'smtp' or 'filesystem' notifier is configured"
time="2023-08-29T14:36:30+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'session.secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'jwt_secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'notifier.smtp.password': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret into key 'jwt_secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: option 'jwt_secret' is required"
time="2023-08-29T14:36:30+01:00" level=error msg="Configuration: notifier: please ensure only one of the 'smtp' or 'filesystem' notifier is configured"
time="2023-08-29T14:36:30+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'session.secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'jwt_secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'notifier.smtp.password': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret into key 'jwt_secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: option 'jwt_secret' is required"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: notifier: please ensure only one of the 'smtp' or 'filesystem' notifier is configured"
time="2023-08-29T14:36:31+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'session.secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'jwt_secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'notifier.smtp.password': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret into key 'jwt_secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: option 'jwt_secret' is required"
time="2023-08-29T14:36:31+01:00" level=error msg="Configuration: notifier: please ensure only one of the 'smtp' or 'filesystem' notifier is configured"
time="2023-08-29T14:36:31+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2023-08-29T14:36:32+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'session.secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:32+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'jwt_secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:32+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'notifier.smtp.password': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:32+01:00" level=error msg="Configuration: secrets: error loading secret into key 'jwt_secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:32+01:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:32+01:00" level=error msg="Configuration: option 'jwt_secret' is required"
time="2023-08-29T14:36:32+01:00" level=error msg="Configuration: notifier: please ensure only one of the 'smtp' or 'filesystem' notifier is configured"
time="2023-08-29T14:36:32+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2023-08-29T14:36:34+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'session.secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:34+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'jwt_secret': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:34+01:00" level=error msg="Configuration: secrets: error loading secret path 'hidden_value' into key 'notifier.smtp.password': open 'hidden_value': no such file or directory"
time="2023-08-29T14:36:34+01:00" level=error msg="Configuration: secrets: error loading secret into key 'jwt_secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:34+01:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources"
time="2023-08-29T14:36:34+01:00" level=error msg="Configuration: option 'jwt_secret' is required"
time="2023-08-29T14:36:34+01:00" level=error msg="Configuration: notifier: please ensure only one of the 'smtp' or 'filesystem' notifier is configured"
time="2023-08-29T14:36:34+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

### Logs (Proxy / Application)

```shell
This is not relevant.
```

### Documentation

None.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
