### DISCUSSION TITLE
Memory Usage and occasional spikes and OOM kills

### DISCUSSION THREAD

**Discussion by prologic** [authelia/authelia#5939] [Troubleshooting] [answered]
Hi Team,

I'm trying to understand Authelia's memory usage and requirements here.

AFAICT Authelia seems to have a steady state of around ~25MB of memory with some occasional slight increasees, but not much.

However, I've observed a couple of things:

- I've had to keep increasing the memory limits of ht container all the way to 512M !
- Because I kept seeing the container get OOM killed

See attached for some really crazy spikes in memory utilization at times I can't explain.

<img width="1202" alt="Screenshot 2023-09-02 at 15 55 27" src="https://github.com/authelia/authelia/assets/1290234/1b1263e4-6965-4836-a487-1a9a8956a40d">

The only thing I can think of is if the Authelia binary is fork/exec ing out to some other large binary?

Can anyone help explain this? It would be nice to have a steady stable Authelia sitting at around ~25-30MB of memory.

cheers
James

**Comment by prologic** [comment]
For context and clarity, this is how I run Authelia (in Docker):

```yaml
---
version: "3.8"

services:
  authelia:
    image: authelia/authelia
    command: --config /config/config.yml
    user: nobody
    configs:
      - source: config
        target: /config/config.yml
      - source: users
        target: /config/users.yml
    environment:
      - TZ=xxx
    volumes:
      - authelia:/data
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname == node5.mydomain.tld
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.auth_authelia.loadbalancer.server.port=9091"
        - "traefik.http.routers.auth_authelia.rule=Host(`auth.mydomain.tld`)"
        - "traefik.http.routers.auth_authelia.priority=2"
        - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.mydomain.tld'
        - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
        - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
      restart_policy:
        condition: any
   
configs:
  config:
    file: ./configs/auth/config.yml
  users:
    file: ./configs/auth/users.yml

networks:
  traefik:
    external: true

volumes:
  authelia:
    driver: local
```
