### DISCUSSION TITLE
LDAP Result Code 32 "No Such Object" - Bare-Metal

### DISCUSSION THREAD

**Discussion by boristhefirst** [authelia/authelia#5960] [Q&A] [answered]
I've installed Authelia (4.37.5 from apt source list repository) for the first time using Bare-Metal deployment. I believe that I'll succeed to deploy behind haproxy.
After I've cleared initial configuration issues my first attempt to authenticate was actually direct to Authelia host from browser testing one_factor and two_factor with ldap authentication background for first factor in active directory mode and the result is Incorrect user or password.

I've seen that discussion but my case is different
https://github.com/authelia/authelia/issues/2652 

My ldap config (showing the rules for access and session section if something there):
```
ldap:
    implementation: activedirectory
    url: ldap://DC.example.inter-medial-domain-name.com:389
    timeout: 5s
    start_tls: true
    tls:
      skip_verify: true
      minimum_version: TLS1.2
      maximum_version: TLS1.3
    base_dn: dc=example,dc=inter-medial-domain-name,dc=com
    username_attribute: sAMAccountName
    additional_users_dn: "OU=users"
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(pwdLastSet=0)))
    additional_groups_dn: OU=Groups,dc=example,dc=inter-medial-domain-name,dc=com
    groups_filter: (&(member={dn})(|(sAMAccountType=268435456)(sAMAccountType=536870912)))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    permit_referrals: false
    user: CN=admin,CN=Users,DC=example,DC=inter-medial-domain-name,DC=com
    password: admin_password

access_control:
  default_policy: deny
  networks:
    networks:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  rules:
  - domain: "auth.example.com" #authelia host
    policy: bypass
  - domain: "xyz.example.com"
    policy: one_factor
	
  - domain:
    - "abcdef.example.com"
    - "defabc.example.com"
    - "abcdef.example.inter-medial-domain-name.com"
    - "defabc.example.inter-medial-domain-name.com"
    resources:
      - "^/abc.*$"
      - "^/ABC.*$"
      - "^/abcd.*$"
      - "^/abcd-efgh.*$"
      - "^/abcd-Efgh.*$"
      - "^/efg.*$"
      - "^/EFG$.*$"
      - "^/egh.*$"
      - "^/EGH$.*$"
    subject:
    - ["user:john.smith"]
    - ["user:peter.pan"]
    policy: one_factor
  - domain:
    - "abcdef.example.com"
    - "defabc.example.com"
    - "abcdef.example.inter-medial-domain-name.com"
    - "defabc.example.inter-medial-domain-name.com"
    resources:
      - "^/abc.*$"
      - "^/ABC.*$"
      - "^/abcd.*$"
      - "^/abcd-efgh.*$"
      - "^/abcd-Efgh.*$"
      - "^/efg.*$"
      - "^/EFG$.*$"
      - "^/egh.*$"
      - "^/EGH$.*$"
    subject:
    - "user:Migration"
    policy: two_factor
	
session:
  name: authelia_session
  domain: example.com
  same_site: lax
  secret: "session_secret"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  redis:
    host: 127.0.0.1
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
``` 

The user I'm trying to authenticate is definitely existing. Here is the error:
```
time="2023-09-05T09:29:54+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'Migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-05T09:29:54+01:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'Migration': cannot find user DN of user 'Migration'. Cause: LDAP Result Code 32 \"No Such Object\": 0000208D: NameErr: DSID-03100245, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=example,DC=inter-medial-domain-name,DC=com'\n\x00" method=POST path=/api/firstfactor remote_ip=192.168.1.18 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:266           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:54 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54           (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                            (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                             (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                    goexit"
``` 

I've got and the security logs at the opposite side from the domain controller if needed.
```
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          9/5/2023 9:29:54 AM
Event ID:      4634
Task Category: Logoff
Level:         Information
Keywords:      Audit Success
User:          N/A
Computer:      DC.example.inter-medial-domain-name.com
Description:
An account was logged off.

Subject:
	Security ID:		EXAMPLE\admin
	Account Name:		admin
	Account Domain:		EXAMPLE
	Logon ID:		0x13E3CAA50

Logon Type:			3

This event is generated when a logon session is destroyed. It may be positively correlated with a logon event using the Logon ID value. Logon IDs are only unique between reboots on the same computer.
---
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          9/5/2023 9:29:54 AM
Event ID:      4672
Task Category: Special Logon
Level:         Information
Keywords:      Audit Success
User:          N/A
Computer:      DC.example.DC=inter-medial-domain-name.com
Description:
Special privileges assigned to new logon.

Subject:
	Security ID:		EXAMPLE\admin
	Account Name:		admin
	Account Domain:		EXAMPLE
	Logon ID:		0x13E3CAA50

Privileges:		SeSecurityPrivilege
			SeTakeOwnershipPrivilege
			SeLoadDriverPrivilege
			SeBackupPrivilege
			SeRestorePrivilege
			SeDebugPrivilege
			SeSystemEnvironmentPrivilege
			SeEnableDelegationPrivilege
			SeImpersonatePrivilege
			SeDelegateSessionUserImpersonatePrivilege
---
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          9/5/2023 9:29:54 AM
Event ID:      4624
Task Category: Logon
Level:         Information
Keywords:      Audit Success
User:          N/A
Computer:      DC.example.inter-medial-domain-name.com
Description:
An account was successfully logged on.

Subject:
	Security ID:		SYSTEM
	Account Name:		DC$
	Account Domain:		EXAMPLE
	Logon ID:		0x3E7

Logon Information:
	Logon Type:		3
	Restricted Admin Mode:	-
	Virtual Account:		No
	Elevated Token:		Yes

Impersonation Level:		Impersonation

New Logon:
	Security ID:		EXAMPLE\admin
	Account Name:		admin
	Account Domain:		EXAMPLE
	Logon ID:		0x13E3CAA50
	Linked Logon ID:		0x0
	Network Account Name:	-
	Network Account Domain:	-
	Logon GUID:		{00000000-0000-0000-0000-000000000000}

Process Information:
	Process ID:		0x34c
	Process Name:		C:\Windows\System32\lsass.exe

Network Information:
	Workstation Name:	DC
	Source Network Address:	xx.xxx.xxx.xx # authelia host quering ip address
	Source Port:		51936

Detailed Authentication Information:
	Logon Process:		Advapi  
	Authentication Package:	MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon session is created. It is generated on the computer that was accessed.

The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).

The New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.

The network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.

The impersonation level field indicates the extent to which a process in the logon session can impersonate.

The authentication information fields provide detailed information about this specific logon request.
	- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.
	- Transited services indicate which intermediate services have participated in this logon request.
	- Package name indicates which sub-protocol was used among the NTLM protocols.
	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.
---
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          9/5/2023 9:29:54 AM
Event ID:      4648
Task Category: Logon
Level:         Information
Keywords:      Audit Success
User:          N/A
Computer:      DC.example.predomain.com
Description:
A logon was attempted using explicit credentials.

Subject:
	Security ID:		SYSTEM
	Account Name:		DC$
	Account Domain:		EXAMPLE
	Logon ID:		0x3E7
	Logon GUID:		{82a51dba-435e-2692-6811-9e37e0530069}

Account Whose Credentials Were Used:
	Account Name:		admin
	Account Domain:		EXAMPLE
	Logon GUID:		{00000000-0000-0000-0000-000000000000}

Target Server:
	Target Server Name:	localhost
	Additional Information:	localhost

Process Information:
	Process ID:		0x34c
	Process Name:		C:\Windows\System32\lsass.exe

Network Information:
	Network Address:	xx.xxx.xxx.xx  # authelia host quering ip address
	Port:			51936

This event is generated when a process attempts to log on an account by explicitly specifying that account’s credentials.  This most commonly occurs in batch-type configurations such as scheduled tasks, or when using the RUNAS command.
---
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          9/5/2023 9:29:54 AM
Event ID:      4776
Task Category: Credential Validation
Level:         Information
Keywords:      Audit Success
User:          N/A
Computer:      DC.example.inter-medial-domain-name.com
Description:
The computer attempted to validate the credentials for an account.

Authentication Package:	MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
Logon Account:	admin
Source Workstation:	DC
Error Code:	0x0
``` 

My request
What I should do to make it work.

Thank you!

**Comment by james-d-elliott** [comment]
What's the distinguished name of the tested user?

Edit: actually the likely issue is `OU=users` which cannot exist in Microsoft AD (without modifying the schema in ways that will likely seriously break it).

**Comment by boristhefirst** [comment]
> What's the distinguished name of the tested user?

> Edit: actually the likely issue is OU=users which cannot exist in Microsoft AD (without modifying the schema in ways that will likely seriously break it).

The distinguished name of the tested user is CN=Migration,CN=Users,DC=example,DC=inter-medial-domain-name,DC=com

Applying the powershell output

```
PS C:\Windows\system32> Get-ADUser -Identity Migration

DistinguishedName : CN=Migration,CN=Users,DC=example,DC=inter-medial-domain-name,DC=com
Enabled           : True
GivenName         : Migration
Name              : Migration
ObjectClass       : user
ObjectGUID        : ed5606bd-1fff-49ee-8a35-xxxxxxxxxxxx
SamAccountName    : migration
SID               : S-1-5-21-969755314-1530668300-xxxxxxxxxx-xxxxx
Surname           :
UserPrincipalName : migration@example.inter-medial-domain-name.com
``` 

Edit: This OU-users is existing indeed. : I've just checked that. There are some base users and groups there like Administrator account Domain Admins group etc. Actually I've removed the user 'Migration' deliberately there because of following the configuration manual in the Authelia site about authentication_backend: and ldap.

**Reply by james-d-elliott** [reply, marked as answer]
You just need to fix up the `additional_users_dn` then and it will likely be fine.

**Comment by boristhefirst** [comment]
> You just need to fix up the additional_users_dn then and it will likely be fine

Thank you!
I've just commented `additional_users_dn` and the configuration is working without it because it's not required. Still error `Incorrect username or password!`
But I'm one step forward.

The error now is different: 
```
time="2023-09-05T11:44:25+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-05T11:44:25+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-05T11:44:25+01:00" level=error msg="Could not obtain profile details during 1FA authentication for user 'migration': unable to retrieve groups of user 'migration'. Cause: LDAP Result Code 32 \"No Such Object\": 0000208D: NameErr: DSID-03100245, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=example,DC=inter-medial-domain-name,DC=com'\n\x00" method=POST path=/api/firstfactor remote_ip=192.168.1.18 stack="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:113 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54            (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25           SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35           SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16           SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                             (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                              (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                     goexit"
``` 

Edit: May be my `additional_groups_dn: OU=Groups,dc=example,dc=inter-medial-domain-name,dc=com` is wrong.
There is no OU=Groups in my test AD
Should I change it or just to remove from the configuration `additional_groups_dn: OU=Groups,dc=example,dc=inter-medial-domain-name,dc=com` ?

**Reply by james-d-elliott** [reply]
You need to configure the attributes to match actual paths. Both the `additional_groups_dn` and the `additional_users_dn` have the `base_dn` appended to them. Making your search `OU=Groups,dc=example,dc=inter-medial-domain-name,dc=com,dc=example,dc=inter-medial-domain-name,dc=com` and I'm 99% sure just like the Users OU, the Groups OU is not a valid OU in Microsoft AD. Check its distinguished name, it's probably a CN as well. If you do a search for all objects in the base. Note how both of these will return no objects:

```
Get-ADObject -Filter * -SearchBase "OU=Groups,dc=example,dc=inter-medial-domain-name,dc=com"
Get-ADObject -Filter * -SearchBase "OU=Users,dc=example,dc=inter-medial-domain-name,dc=com"
```

But these will: 

```
Get-ADObject -Filter * -SearchBase "CN=Groups,dc=example,dc=inter-medial-domain-name,dc=com"
Get-ADObject -Filter * -SearchBase "CN=Users,dc=example,dc=inter-medial-domain-name,dc=com"
```

**Comment by boristhefirst** [comment]
Thank you!
I'm a little bit exited.
I've removed at all `additional_users_dn` & `additional_groups_dn` from the configuration.
No errors in the log. But two_factors window didn't appear.

Now the log looks like this:
```
time="2023-09-05T12:07:31+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-05T12:07:31+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-05T12:07:39+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.199.18
time="2023-09-05T12:07:39+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-05T12:07:42+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-05T12:07:42+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
```

But I would like to go further and to see the challenge for totp creation.
I'm still testing directly from browser to Auhtelia host. No errors but two_factor windows is not appearing.
What should I do to continue succesfully?
Should I put Authelia behind proxy to blink two_factor window?

Edit: I have in the configuration `default_redirection_url: https://abcdef.example.com/`.

**Reply by james-d-elliott** [reply]
What appears when you login then?

**Reply by boristhefirst** [reply]
Appears nothing. Not exactly nothing. Remains Authelia logon screen.
First of all no errors in the debug log (looks like in my previous message) indicating that first factor of the authentication to AD ldap is successful.
I'm using the default light theme. The username and the doted password are remaining in the fields.
The username field is with light blue background. Different than the color of SIGN IN button.
This is related probably with the rules in the `access_control`. I've applied in the first post of the thread.
So I think that I have to figure out the ordering of the rules and the arrangement inside rules blocks.
It will be great if you could suggest something!
Thank you!

**Reply by james-d-elliott** [reply]
There are no logs related to the access control section. Look at the browser console to see if it's logging anything. Please also show screenshot of what you see.

**Reply by boristhefirst** [reply]
I've set this configuration for logging `file_path: /var/log/authelia/test_authelia.log`.
I've noticed that system events for restarting the Authelia daemon are written to `/var/log/syslog`.
There is no events about access control section in `file_path: /var/log/authelia/test_authelia.log` & `/var/log/syslog`.
I don't know how to set log configuration so that all logs to be written in one log file.

Last events from `/var/log/authelia/test_authelia.log`:
```
time="2023-09-06T16:15:51+01:00" level=info msg="Storage schema is being checked for updates"
time="2023-09-06T16:15:51+01:00" level=info msg="Storage schema is already up to date"
time="2023-09-06T18:15:51+03:00" level=debug msg="LDAP Supported OIDs. Control Types: 1.2.840.113556.1.4.319, 1.2.840.113556.1.4.801, 1.2.840.113556.1.4.473, 1.2.840.113556.1.4.528, 1.2.840.113556.1.4.417, 1.2.840.113556.1.4.619, 1.2.840.113556.1.4.841, 1.2.840.113556.1.4.529, 1.2.840.113556.1.4.805, 1.2.840.113556.1.4.521, 1.2.840.113556.1.4.970, 1.2.840.113556.1.4.1338, 1.2.840.113556.1.4.474, 1.2.840.113556.1.4.1339, 1.2.840.113556.1.4.1340, 1.2.840.113556.1.4.1413, 2.16.840.1.113730.3.4.9, 2.16.840.1.113730.3.4.10, 1.2.840.113556.1.4.1504, 1.2.840.113556.1.4.1852, 1.2.840.113556.1.4.802, 1.2.840.113556.1.4.1907, 1.2.840.113556.1.4.1948, 1.2.840.113556.1.4.1974, 1.2.840.113556.1.4.1341, 1.2.840.113556.1.4.2026, 1.2.840.113556.1.4.2064, 1.2.840.113556.1.4.2065, 1.2.840.113556.1.4.2066, 1.2.840.113556.1.4.2090, 1.2.840.113556.1.4.2205, 1.2.840.113556.1.4.2204, 1.2.840.113556.1.4.2206, 1.2.840.113556.1.4.2211, 1.2.840.113556.1.4.2239, 1.2.840.113556.1.4.2255, 1.2.840.113556.1.4.2256, 1.2.840.113556.1.4.2309. Extensions: 1.3.6.1.4.1.1466.20037, 1.3.6.1.4.1.1466.101.119.1, 1.2.840.113556.1.4.1781, 1.3.6.1.4.1.4203.1.11.3, 1.2.840.113556.1.4.2212"
time="2023-09-06T16:15:51+01:00" level=debug msg="Notifier SMTP client attempting connection to xx.xxx.xxx.xx:25"
time="2023-09-06T16:15:51+01:00" level=debug msg="Notifier SMTP client connected successfully"
time="2023-09-06T16:15:51+01:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: true, ServerName: xx.xxx.xxx.xx), attempting"
time="2023-09-06T16:15:51+01:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2023-09-06T16:15:51+01:00" level=debug msg="Notifier SMTP config has no password specified so authentication is being skipped"
time="2023-09-06T16:15:56+01:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2023-09-06T20:26:27+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-06T20:26:27+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-06T20:26:29+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.199.18
time="2023-09-06T20:26:29+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-06T20:26:30+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.199.18
time="2023-09-06T20:26:30+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-07T09:41:46+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
time="2023-09-07T09:41:46+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'migration'" method=POST path=/api/firstfactor remote_ip=192.168.1.18
``` 

Last events from `/var/log/syslog` related with Authelia
```
Sep  7 09:41:46 auth authelia[6769]: [mysql] 2023/09/07 09:41:46 packets.go:122: closing bad idle connection: connection reset by peer
Sep  7 09:41:46 auth authelia[6769]: [mysql] 2023/09/07 09:41:46 connection.go:173: driver: bad connection
``` 

There is may be some problem with the storage. I'm using mariadb (mysql)
```
storage:
  encryption_key: "storage_encryption_key"
  mysql:
    host: 127.0.0.1
    port: 3306
    database: authelia
    username: authelia
    password: "authelia_dbadmin_password"
    timeout: 5s
``` 
Edit: screenshot
![authelia_login](https://github.com/authelia/authelia/assets/143560141/91d7eca3-9c57-4b36-bb32-05da7093713b)
