### DISCUSSION TITLE
new installation isnt working

### DISCUSSION THREAD

**Discussion by Zeitungsleser** [authelia/authelia#6006] [Q&A] [answered]
Hi,
I want to use authelia but run into some problems. I use the authelia/authelia:master docker image. The docker container is starting, but when I try to visit the web interface, it shows a loading screen and the error prompt "There was an issue fetching the current user state" in the upper right corner of my browser. In my docker logs, I see this error message:
```
level=error msg="Error occurred retrieving user session" error="unable to retrieve domain session: %!w(<nil>)" method=GET path=/api/state remote_ip=172.17.0.1 stack="github.com/authelia/authelia/v4/internal/handlers/handler_state.go:16  StateGET\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54      handleRouter.(*BridgeBuilder).Build.func4.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25     SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:51     SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16     SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.20/router.go:420                       (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 handleRouter.LogRequest.func36\ngithub.com/valyala/fasthttp@v1.48.0/server.go:2363                     (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.48.0/workerpool.go:224                  (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.48.0/workerpool.go:196                  (*workerPool).getCh.func1\nruntime/asm_amd64.s:1650                                               goexit"
```
My authelia config is:
```
theme: light
jwt_secret: ***
default_redirection_url: localhost:8007
default_2fa_method: ""
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
    client_certificates: []
  headers:
    csp_template: ""
log:
  level: debug
authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16
      scrypt:
        iterations: 16
        block_size: 8
        parallelism: 1
        key_length: 32
        salt_length: 16
      pbkdf2:
        variant: sha512
        iterations: 310000
        salt_length: 16
      sha2crypt:
        variant: sha512
        iterations: 50000
        salt_length: 16
      bcrypt:
        variant: standard
        cost: 12
access_control:
  default_policy: one_factor
session:
  name: authelia_session
  domain: 127.0.0.1
storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3
notifier:
  filesystem:
    filename: /config/notification.txt
```
