### DISCUSSION TITLE
Unlimited session time for specific users / domains / resources?

### DISCUSSION THREAD

**Discussion by level20peon** [authelia/authelia#6119] [Q&A] [answered]
There are a couple of services that I use with limited interfaces (i.e. PWA, or something running on integrated devices without a real input interface) which makes logging in a little bit fiddly at times. For those devices I would like to generate an unlimited session once I logged in on them properly. Now, I can differentiate those devices by either the user or the domain or the resource, so it would be nice to be able to define an unlimited "remember_me_duration" for those for example.

Is there any way to single out those devices and give them an unlimited session time?

**Comment by james-d-elliott** [comment, marked as answer]
Sorry for the late response.

There will be a way to do this per-domain in 4.38, but this only applies if one domain is not the suffix of another domain. This is done based on a session cookie, so authelia at the path it is being served must be able to write a session cookie for the domain.

Examples of bad domain combination is `app.example.com` and `example.com`, example of a good one is `app.example.com` and `another.example.com` but authelia must be served at a subpath of those domains such as `app.example.com/authelia` and `another.example.com/authelia` (at the time of it creating the cookie), or a subdomain of those domains for example `auth.app.example.com` and `auth.another.example.com`. Alternatively `example1.com` and `example2.com` where authelia is `auth.example1.com` and `auth.example2.com`.

In addition no SSO will exist between those separate domains.

**Comment by level20peon** [comment]
My setup is mixed like this:
example.com
auth.example.com (<- authelia)
app.example.com
example.com/app (<- some of those need unlimited session time)

So, as per your answer this won't be possible to implement for me with 4.38 using the layout I just described, right?

**Reply by james-d-elliott** [reply]
Correct it will not unfortunately. The only work around would be completely separating all applications and serving authelia as a subpath. I don't know for sure but I think juggling all of those cookies will become problematic and unwieldy to track. I can link to this in FR I'm about to create so I can consider it in that phase of development, and maybe get a clearer picture.

I suspect the limitation is going to be that even if we add additional cookies to handle this specific case they'll be available on all subdomains. But maybe there is a useful pattern I've not considered.

**Comment by level20peon** [comment]
Well I also could do something like unlimited.example.com and move all of those apps there. But this also is not part of the design you described, right?

**Reply by james-d-elliott** [reply]
The only way that would work is if none of your other domains are the suffix of `unlimited.example.com`, so `example.com` wouldn't work as it is a suffix of `unlimited.example.com`. The reason is that `unlimited.example.com` has access to cookies made for `example.com`, meaning that there is a high likelihood of confusion when it comes to determining which cookie to use. 

I do have an idea for this but it has not been tested and I've not had time. Essentially how we'd likely have to accomplish this is as follows:

```yaml
session:
  cookies:
  - domain: 'example.com'
    authelia_url: 'https://auth.example.com'
    default_redirection_url: 'https://www.example.com'
    name: 'authelia_session'
    same_site: 'lax'
    inactivity: '5m'
    expiration: '1h'
    remember_me: '1d'
    ## Parts below this line are the parts we'd have to add, everything above is from existing 4.38 pre-releases.
    extra:
    - name: 'anything_other_than_authelia_session'
      domains:
      - unlimited.example.com
      same_site: 'lax'
      inactivity: '10y'
      expiration: '10y'
      remember_me: '10y'
```

The problem with this approach is that given a user is authenticated already with the `authelia_session` cookie we'd have to write one via a short redirect for `anything_other_than_authelia_session`. Alternatively maybe we can add a response header the proxy would be responsible for writing. It just feels very cumbersome to manage properly.
