### DISCUSSION TITLE
Trouble setting up SMTP Notifications with local IPS Shaw Server

### DISCUSSION THREAD

**Discussion by Smithoo4** [authelia/authelia#6138] [Troubleshooting] [answered]
I have an e-mail account from my local IPS Shaw that I use for sending out notification. However, I can not get it to work with Authelia.

Here is a link to Shaw's documentation for using their server to send e-mail: [https://support.shaw.ca/t5/internet-articles/how-to-set-up-your-shaw-email/ta-p/6497](url) 

The following is what I have for an Authelia configuration so far: 

```
notifier:
  disable_startup_check: false
  smtp:
    disable_html_emails: false
    disable_require_tls: true
    disable_starttls: false
    host: mail.shaw.ca
    password: *******
    port: 587
    sender: username@shaw.ca
    startup_check_address: username@shaw.ca
    username: username
```  
With this, I get the following error:
```
  level=error msg="error performing DATA with the SMTP server: 550 <username@shaw.ca> message rejected. AUP#SNDR" method=POST path=/api/reset-password/identity/start remote_ip=0.0.0.0 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:65       (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:106 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                 (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                  (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                   (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                                (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                             (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                             (*workerPool).getCh.func1\nruntime/asm_arm64.s:1172                                                          goexit"
```
I don't believe the issues is with the IPS as I have got it to work with msmtp and Nextcloud.

/etc/msmtprc:
```
defaults
aliases /etc/aliases
auth on
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt

account default
from username@shaw.ca
host smtp.shaw.ca
password *******
port 587
tls_starttls on
user username
```
Nextcloud:

![image](https://github.com/authelia/authelia/assets/13087392/b0765d70-de8b-4bc0-aecf-40ad97c109a1)

Any suggestion on how to get this working? Thank you for your help.
