### DISCUSSION TITLE
UI/UX: TOTP enrollment process doesn't allow to easily display/copy the TOTP secret.

### DISCUSSION THREAD

**Discussion by dumbasPL** [authelia/authelia#6219] [Pre-Release Feedback]
When trying to register a one-time password the `QR Code` toggle is disabled and there is no way to show the TOTP secret. This used to work in `4.37` but doesn't in `4.38.0-beta3`.

Temporary workaround: use the "Copy link address" feature of the browser to extract the secret from the TOTP URL.

simplified configuration used for testing:
```yaml
server:
  address: 'tcp://:9091/'
  tls:
    key: /config/private.pem
    certificate: /config/public.crt
log:
  level: info
  format: text
theme: dark
totp:
  issuer: test.local
access_control:
  default_policy: two_factor
notifier:
  filesystem:
    filename: /config/notification.txt
storage:
  encryption_key: <REDACTED>
  local:
    path: /config/db.sqlite3
session:
  name: authelia_session
  secret: <REDACTED>
  inactivity: 7d
  expiration: 1d
  remember_me: 1M
  cookies:
    - domain: test.local
      authelia_url: https://auth.test.local:9091/
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
identity_validation:
  reset_password:
    jwt_secret: <REDACTED>
```

related #1509

PS: WebAuthn works perfectly though, thank you for implementing multiple keys support :heart:
