### DISCUSSION TITLE
Setting up SMTP notifier via environment variables only?

### DISCUSSION THREAD

**Discussion by jedahan** [authelia/authelia#6220] [General]
I'd like to run authelia via docker compose, and was hoping I could get SMTP notifier working, but it looks like the default config is set to filesystem if no pre-made config is loaded. Below is the config I'd like to use, is there a way to achieve smtp notifier without having to fill out an entire new yaml and keep it up to date?

If not, should I request a feature in the issue tracker? Thanks

```yaml
# authelia.yaml
version: "3.8"

secrets:
  JWT_SECRET:
    file: ../secrets/authelia/JWT_SECRET
  SESSION_SECRET:
    file: ../secrets/authelia/SESSION_SECRET
  STORAGE_PASSWORD:
    file: ../secrets/authelia/STORAGE_PASSWORD
  STORAGE_ENCRYPTION_KEY:
    file: ../secrets/authelia/STORAGE_ENCRYPTION_KEY
  SMTP_PASSWORD:
    file: ../secrets/smtp/SMTP_PASSWORD
  SMTP_HOST:
    file: ../secrets/smtp/SMTP_HOST
  SMTP_PORT:
    file: ../secrets/smtp/SMTP_PORT
  SMTP_USERNAME:
    file: ../secrets/smtp/SMTP_USERNAME

services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:4.37
    userns_mode: keep-id
    depends_on:
      - postgres
      - secrets
      - caddy
    restart: unless-stopped
    expose:
      - 9091
    secrets: [JWT_SECRET, SESSION_SECRET, STORAGE_PASSWORD, STORAGE_ENCRYPTION_KEY, SMTP_PASSWORD, SMTP_HOST, SMTP_PORT, SMTP_USERNAME]
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY

      AUTHELIA_STORAGE_POSTGRES_DATABASE: authelia
      AUTHELIA_STORAGE_POSTGRES_ADDRESS: postgres
      AUTHELIA_STORAGE_POSTGRES_USERNAME_FILE: /run/secrets/SMTP_USERNAME
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/STORAGE_PASSWORD

      AUTHELIA_DEFAULT_REDIRECTION_URL: https://${DOMAIN}
      AUTHELIA_TOTP_ISSUER: ${DOMAIN}
      AUTHELIA_WEBAUTHN_DISPLAY_NAME: ${DOMAIN}

      AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY: two_factor

      AUTHELIA_NOTIFIER: smtp
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/SMTP_PASSWORD
      AUTHELIA_NOTIFIER_SMTP_HOST_FILE: /run/secrets/SMTP_HOST
      AUTHELIA_NOTIFIER_SMTP_PORT_FILE: /run/secrets/SMTP_PORT
      AUTHELIA_NOTIFIER_SMTP_USERNAME: "authelia@${DOMAIN}"
      AUTHELIA_NOTIFIER_SMTP_SENDER: "Authelia <authelia@${DOMAIN}>"

    volumes:
      - ../data/authelia/config:/config

  postgres:
    image: postgres:16.0-alpine
    depends_on:
      - secrets
      - caddy
    secrets: [STORAGE_PASSWORD]
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/STORAGE_PASSWORD
      POSTGRES_DB: authelia
      POSTGRES_USER: authelia
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # setup a reverse proxy for caddy
  caddy:
    volumes:
      - ./authelia/Proxyfile:/etc/caddy.d/authelia:ro

  # backup the authelia config
  backup:
    volumes:
      - ../data/authelia/config:/mnt/backup/src/authelia/config:ro

  # generate all these secrets if they are empty on start
  secrets:
    volumes:
      - ../secrets/authelia/JWT_SECRET:/secrets/authelia/JWT_SECRET
      - ../secrets/authelia/SESSION_SECRET:/secrets/authelia/SESSION_SECRET
      - ../secrets/authelia/STORAGE_PASSWORD:/secrets/authelia/STORAGE_PASSWORD
      - ../secrets/authelia/STORAGE_ENCRYPTION_KEY:/secrets/authelia/STORAGE_ENCRYPTION_KEY

volumes:
  postgres-data:
  authelia-config:
```
