### DISCUSSION TITLE
bypass rule isn't working

### DISCUSSION THREAD

**Discussion by jbeck22** [authelia/authelia#6274] [Q&A] [answered]
I see the following in my logs

`time="2023-11-13T17:04:26-05:00" level=info msg="Access to https://xxxxxxxxxxx/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.71.22.141`

I accessing this page from my laptop on my network. Currently I have an IP address of 192.168.1.x

Here is part of my configuration file that I'm using and all I want to do is bypass authelia if i'm at home or on my VPN

```
access_control:
  default_policy: deny

  networks:
  - name: internal
    networks:
      - '71.135.203.245/32'
      - '172.16.0.0/12'
      - '192.168.0.0/24'
      - '192.168.1.0/24'
      - '172.69.0.0/24'
      - '172.18.0.0/24'

  rules:
      ## bypass api / triggers
    - domain: "*.atlbecks.com"
      resources:
        - "^/api([/?].*)?$"
      policy: bypass
      networks:
        - '192.168.0.0/24'
        - '172.18.0.0/24'
```

Can anyone help point me in the right direction?  I have struggling with this for a LONG time.

**Comment by james-d-elliott** [comment, marked as answer]
The remote IP doesn't match the rule.

**Comment by jbeck22** [comment]
I’ve added that subnet and restarted the docket container.  Same results:

```
  access_control:
    default_policy: deny
  
    networks:
    - name: internal
      networks:
        - '71.135.203.245/32'
        - '172.16.0.0/12'
        - '192.168.0.0/24'
        - '192.168.1.0/24'
        - '172.69.0.0/24'
        - '172.18.0.0/24'
        - '172.0.0.0/24'
  
    rules:
        ## bypass api / triggers
      - domain: "*.atlbecks.com"
        resources:
          - "^/api([/?].*)?$"
        policy: bypass
        networks:
          - '192.168.0.0/24'
          - '172.18.0.0/24'
          - '172.0.0.0/24'

```
