### DISCUSSION TITLE
Set up Authelia as OIDC Provider for a custom app.

### DISCUSSION THREAD

**Discussion by drogerie21** [authelia/authelia#6302] [Q&A] [answered]
Hi, 
i want to use authelia as OIDC Provider for a custom app
im trying to set up an authorization code flow on my client app that uses the oidc-client-ts library. Authelia and the custom app is running in docker together with a traefik reverse proxy. 

This is my docker-compose file:

```
version: '3'
volumes:
  traefik-ssl-certs:
    driver: local
  data:
    driver: local
    
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./authelia:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.test.subdomain.com`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.certresolver=staging'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.test.subdomain.com/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Europe/Vienna
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    ports:
      # The HTTP port
      - '80:80'
      # The HTTPS port
      - '443:443'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
  test-app:
    image: test-app:2.2
    container_name: test-app
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.test-app.rule=Host(`app.test.subdomain.com`)'
      - 'traefik.http.routers.test-app.entrypoints=websecure'
      - 'traefik.http.routers.test-app.tls=true'
      - 'traefik.http.routers.test-app.tls.certresolver=staging'
      - 'traefik.http.routers.test-app.middlewares=authelia@docker'
```

and thats the relevant oidc section in my configuration file:
`identity_providers:
  oidc:
    
    hmac_secret: 'hmac-secret'    
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----      
      -----END RSA PRIVATE KEY-----
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
          - https://test.subdomain.com
          - https://app.test.subdomain.com
    clients:
    - id: test-app
      description: Test-App
      secret: 'secret' # digest of JQtoSdevHdKQJKXwsq6hGAZe5RMAwZElr-1kczALDCdc2gusxgh0fQqNSzeKEzSfvM0kwsPRdRQcYhdzztEO
      public: false
      authorization_policy: one_factor
      redirect_uris:
        - https://app.test.subdomain.com
      scopes:
        - openid
        - profile
        - groups
        - email
      userinfo_signing_algorithm: none`

This are my oidc-settings for the oidc-client-library:
```    
const oidcSettings = {
      authority: 'https://auth.test.subdomain.com/api/oidc/authorization',
      client_id: 'test-app',
      redirect_uri: 'https://app.test.subdomain.com/oidc-callback',
      client_secret: 'secret',
      response_type: 'code',
      scope: 'openid profile email',
    };
```

My Problem: i get stuck on an CORS error on the first request to get the open-id configuration. This is the error i get:

/#/:1 Access to fetch at 'https://auth.test.subdomain.com/api/oidc/authorization/.well-known/openid-configuration' from origin 'https://app.test.subdomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

As you cann see allowed endpoints for the oidc is set in the configuration. what i´m doing wrong here?
