### DISCUSSION TITLE
sub-domains with different ldap users_filter to prevent redirection loop

### DISCUSSION THREAD

**Discussion by piengeng** [authelia/authelia#6307] [Q&A] [answered]
the problems:
all users able to login via ldap
only limit specific sub domain eg. `pihole`.eg.com by settings the domain and the subject's group:`pihole` within rules

user with group `pihole` is able to login and redirect properly, however every other users without the group `pihole` will login and the browser will be in some sort of redirection loop as it's not within the `pihole` group. have to manually go to authelia url without `rd` and click logout so that the browser stop redirecting on the previous tab.

one possible solution, is to create another instance of authelia with a different port, is there another way without adding another authelia instance?

**Comment by james-d-elliott** [comment]
Show the logs and the ACL config. Also which proxy are you using?

**Reply by piengeng** [reply]
Auth:
```yaml
authentication_backend:                                                                                                         
  ...                                                                                                          
  ldap:                                                                                                                         
    url: ldaps://demo.eg.com                                                                                                  
    base_dn: dc=eg,dc=com                                                                                                   
    ...
    users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson)(|(memberof=cn=pihole_admin,ou=groups,dc=eg,dc=com
)(memberof=cn=rspamd_admin,ou=groups,dc=eg,dc=com)(memberof=cn=superuser,ou=groups,dc=eg,dc=com)))                            
    ...
    groups_filter: (&(uniqueMember={dn})(objectClass=groupOfUniqueNames))                                                       
    ...
```
ACL:
```yaml
access_control:                                                                                                                 
  default_policy: deny                                                                                                          
  networks:                                                                                                                     
    - name: internal                                                                                                            
      networks:                                                                                                                 
        - 192.168.1.0/24                                                                                                        
  rules:                                                                                                                        
    - domain: 'pihole.eg.com'                                                                                                  
      policy: one_factor                                                                                                        
      subject:                                                                                                                  
        - 'group:pihole_admin'                                                                                                  
        - 'group:superuser'                                                                                                     
    - domain: 'rspamd.eg.com'                                                                                                  
      policy: one_factor
      subject:
        - 'group:rspamd_admin'
        - 'group:superuser'
```
haproxy:
```
frontend part
  acl hdr-xff_exists req.hdr(X-Forwarded-For) -m found
  http-request set-header X-Forwarded-For %[src] if !hdr-xff_exists 
  acl protected-frontends hdr(host) -m reg -i ^(?i)(pihole|rspamd|memberof)\.eg\.com
  acl host-pihole hdr(host) -i pihole.eg.com
  acl host-rspamd hdr(host) -i rspamd.eg.com
  http-request set-var(req.scheme) str(https) if { ssl_fc }
  http-request set-var(req.scheme) str(http) if !{ ssl_fc }
  http-request set-var(req.questionmark) str(?) if { query -m found }
  http-request set-header X-Real-IP %[src]
  http-request set-header X-Forwarded-Method %[var(req.method)]
  http-request set-header X-Forwarded-Proto %[var(req.scheme)]
  http-request set-header X-Forwarded-Host %[req.hdr(Host)]
  http-request set-header X-Forwarded-Uri %[path]%[var(req.questionmark)]%[query]
  http-request lua.auth-request be_authelia /api/verify if protected-frontends
  # Redirect protected-frontends to Authelia if not authenticated
  http-request redirect location https://authelia.eg.com/?rd=%[var(req.scheme)]://%[base]%[var(req.questionmark)]%[query] if pr
otected-frontends !{ var(txn.auth_response_successful) -m bool } 

  use_backend be_pihole if host-pihole
  use_backend be_rspamd if host-rspamd
```

screencap:

https://github.com/authelia/authelia/assets/8223560/fa584910-33be-4f5e-85a7-a2784e7f6a40
