### DISCUSSION TITLE
Struggling to get authelia working with Bitnami Redis Sentinel

### DISCUSSION THREAD

**Discussion by 2fst4u** [authelia/authelia#6440] [Q&A]
Not worthy of an issue because this is entirely my inability to make it work, but does anyone have any idea how to get authelia to talk to the Bitnami Redis Sentinel configuration? I'm on Kubernetes using the Authelia Helm chart.

I really didn't want to use Bitnami but short of completely engineering a Sentinel cluster from scratch it seemed like a decent option, however Authelia complains `Redis connection error: redis: all sentinels specified in configuration are unreachable"`. I'm also using the Bitnami Redis helm chart.

The Bitnami Redis service is a bit weird, and the instructions say to find the master node but I don't understand how, or why. What if the master has already failed over and it's no longer the master anymore? Anyway, I can't figure out what to put for the `host` value in the Authelia Helm, or the `nodes`. No matter the combination I get the above error.

**Comment by 2fst4u** [comment]
I swear I'd tried this combination of values before, but this just made it work:

```
session:

        redis:
          enabled: true
          enabledSecret: true
          host: redis.database.svc.cluster.local # the default service name when sentinel is enabled (note my namespace is different to Authelia docs)
          port: 26379

          high_availability:
            enabled: true
            enabledSecret: true

            sentinel_name: mymaster # the default bitnami name
            nodes: 
              - host: redis-node-0.redis.database.svc.cluster.local # default node names with my namespace
                port: 26379
              - host: redis-node-1.redis.database.svc.cluster.local
                port: 26379
              - host: redis-node-2.redis.database.svc.cluster.local
                port: 26379

```

Anyway, documenting here for posterity.

**Reply by Trogie** [reply]
and where did you specify the password? I specified additionalSecrets but still get the `Redis connection error`

**Reply by james-d-elliott** [reply]
```yaml
session:
  redis:
    username: 'authelia'
    password: 'authelia'     
    high_availability:
      sentinel_username: 'sentinel_user'
      sentinel_password: 'sentinel_specific_pass'
```
