### DISCUSSION TITLE
Redis connection error

### DISCUSSION THREAD

**Discussion by mailliwal** [authelia/authelia#6507] [Q&A] [answered]
`authelia  | time="2024-01-06T00:45:26+08:00" level=fatal msg="Redis connection error: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?"`

Redis section is existed in configuraion.yml & REDIS_PASSWORD is existed on docker-compose.yaml of Redis.

May I know how to solve it ?

Thanks

**Comment by james-d-elliott** [comment]
You need to configure the password option.

**Reply by mailliwal** [reply]
Hi,

Here is my configuration file.

**- configuration.yml**
```
  redis:
    host: authelia_redis
    port: 6379
    password: REDIS_PWD
    database_index: 0
```

**- docker-compose.yaml of REDIS**
```
    environment:
      - REDIS_PASSWORD=REDIS_PWD
```
