### DISCUSSION TITLE
Big redis db/dump?

### DISCUSSION THREAD

**Discussion by voruti** [authelia/authelia#6508] [Q&A] [answered]
Using `image: authelia/authelia:4.37.5`.

My redis db is 317 MB in size. `redis-cli INFO` outputs:
```
...
# Keyspace
db0:keys=588570,expires=588570,avg_ttl=28961729886
```
My sessions are configured as:
```yml
session:
  # secret: set by secret file
  inactivity: 3d
  expiration: 1y
  remember_me_duration: -1 # disabled because it would disable the inactivity timeout
  domain: <redacted>

  redis:
    host: redis
    port: 6379
    # password: set by secret file
```
The regular redis dump slows down my server, because it's so huge.

Any idea why there are so many keys? Do they get deleted, after they are invalid (3 days of inactivity)? Why is the TTL so high (900 years if I read that correct)?
