### DISCUSSION TITLE
bug: infinite startup on v4.38.0-beta3

### DISCUSSION THREAD

**Discussion by georglauterbach** [authelia/authelia#6677] [Pre-Release Feedback]
### Version

v4.37.5

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.7.10

### Description

When running `ghcr.io/authelia/authelia:v4.38.0-beta3`, the pod seems to be stuck after

```ini
time="2024-02-11T02:27:24Z" level=debug msg="Process user information" gid=65534 name=nobody uid=65534 username=nobody
time="2024-02-11T02:27:24Z" level=info msg="Authelia untagged-v4.37.5 (v4.38.0-beta3, 7c764f2) is starting"
time="2024-02-11T02:27:24Z" level=info msg="Log severity set to trace"
time="2024-02-11T02:27:24Z" level=trace msg="Starting scan of directory  for certificates"
time="2024-02-11T02:27:24Z" level=debug msg="Registering client gitlab with policy two_factor (two_factor)"
time="2024-02-11T02:27:24Z" level=debug msg="Registering client cloudflare-zero-trust with policy two_factor (two_factor)"
time="2024-02-11T02:27:24Z" level=debug msg="Registering client nextcloud with policy two_factor (two_factor)"
time="2024-02-11T02:27:24Z" level=info msg="Storage schema is being checked for updates"
time="2024-02-11T02:27:24Z" level=info msg="Storage schema is already up to date"
```

The pod does not continue with starting and I do not see the message "Startup complete".

### Reproduction

I am not sure whether this is a fault on my side with Kubernetes, but I cannot figure out why I am stuck... :( The deployment itself is straightforward; secrets are supplied via ENVs. The pod runs as user 65534:65534.

### Expectations

I expect the pod to finish initialization or show an error.

### Configuration (Authelia)

```yaml
theme: auto
default_2fa_method: webauthn

server:
  address: tcp4://0.0.0.0:8080
  disable_healthcheck: true

log:
  level: trace
  format: text

telemetry:
  metrics:
    enabled: false

totp:
  disable: true

webauthn:
  disable: false
  timeout: 30s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

duo_api:
  hostname: REDACTED
  integration_key: REDACTED
  enable_self_enrollment: false
  #secret_key: AUTHELIA_DUO_API_SECRET_KEY

ntp:
  address: udp4://time.cloudflare.com:123
  version: 4
  max_desync: 2s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 6h
  file:
    path: /config/users-database.yml
    watch: false
    search:
      email: true
      case_insensitive: false
    password:
      algorithm: argon2id
      iterations: 1
      parallelism: 6
      salt_length: 16
      memory: 128

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - '10.10.0.0/16'
        - '10.100.0.0/16'
  rules: REDACTED

session:
  name: authelia_session
  same_site: strict
  expiration: 3h
  inactivity: 1h
  #secret: AUTHELIA_SESSION_SECRET

  cookies:
    - domain: REDACTED
      authelia_url: https://auth.REDACTED
      default_redirection_url: REDACTED

  redis:
    host: REDACTED
    port: 6379
    username: default
    password: authelia

regulation:
  ban_time: 10d
  find_time: 6h
  max_retries: 3

storage:
  #encryption_key: AUTHELIA_STORAGE_ENCRYPTION_KEY
  postgres:
    address: REDACTED:5432
    database: authelia
    schema: public
    username: authelia
    #password: AUTHELIA_STORAGE_POSTGRES_PASSWORD

notifier:
  disable_startup_check: false
  smtp:
    address: REDACTED:465
    timeout: 10s
    subject: '[Authelia] {title}'
    sender: REDACTED
    username: REDACTED
    #password: AUTHELIA_NOTIFIER_SMTP_PASSWORD
    identifier: REDACTED
    startup_check_address: REDACTED
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: REDACTED
      skip_verify: false
      minimum_version: TLS1.3

identity_providers:
  oidc:
    #hmac_secret: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET

    issuer_private_keys:
      - key: |
          -----BEGIN RSA PRIVATE KEY-----REDACTED

    enable_client_debug_messages: false

    lifespans:
      access_token: 2h
      authorize_code: 2m
      id_token: 2h
      refresh_token: 3h

    cors:
      allowed_origins_from_client_redirect_uris: true

    clients:
      # https://www.authelia.com/integration/openid-connect/gitlab/
      - REDACTED
```

### Build Information

```shell
Last Tag: v4.37.5
State: untagged clean
Branch: v4.38.0-beta3
Commit: 7c764f2b9457dd5ddc3d52804751cd5ef05782a0
Build Number: 26767
Build OS: linux
Build Arch: amd64
Build Date: Sun, 11 Feb 2024 11:12:03 +1100
Extra:

Go:
    Version: go1.21.4
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
    Settings:
        -buildmode: pie
        -compiler: gc
        -trimpath: true
        CGO_ENABLED: 1
        GOARCH: amd64
        GOOS: linux
        GOAMD64: v1
        vcs: git
        vcs.revision: 7c764f2b9457dd5ddc3d52804751cd5ef05782a0
        vcs.time: 2024-02-11T00:11:14Z
        vcs.modified: true
    Dependencies:
        github.com/Azure/go-ntlmssp@v0.0.0-20221128193559-754e69321358 (h1:mFRzDkZVAjdal+s7s0MwaRv9igoPqLRdzOLzw/8Xvq8=)
        github.com/Gurpartap/logrus-stack@v0.0.0-20170710170904-89c00d8a28f4 (h1:vdT7QwBhJJEVNFMBNhRSFDRCB6O16T28VhvqRgqFyn8=)
        github.com/andybalholm/brotli@v1.0.5 (h1:8uQZIdzKmjc/iuPu7O2ioW48L81FgatrcpfFmiq/cCs=)
        github.com/asaskevich/govalidator@v0.0.0-20210307081110-f21760c49a8d (h1:Byv0BzEl3/e6D5CLfI0j/7hiIEtvGVFPCZ7Ei2oq8iQ=)
        github.com/authelia/jsonschema@v0.1.7 (h1:RbtTeTG7GiWIrx2A+3O+b33jr/mLlSmqGYyk1w5gLNA=)
        github.com/authelia/otp@v1.0.0 (h1:X6YeBMb16CkW8fFpLBQc0ams+Ed0zw1R/5pfih/1vLU=)
        github.com/beorn7/perks@v1.0.1 (h1:VlbKKnNfV8bJzeqoa4cOKqO6bYr3WgKZxO8Z16+hsOM=)
        github.com/boombuler/barcode@v1.0.1 (h1:NDBbPmhS+EqABEs5Kg3n/5ZNjy73Pz7SIV+KCeqyXcs=)
        github.com/cespare/xxhash/v2@v2.2.0 (h1:DC2CZ1Ep5Y4k3ZQ899DldepgrayRUGE6BBZ/cd9Cj44=)
        github.com/cristalhq/jwt/v4@v4.0.2 (h1:g/AD3h0VicDamtlM70GWGElp8kssQEv+5wYd7L9WOhU=)
        github.com/davecgh/go-spew@v1.1.1 (h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=)
        github.com/dgraph-io/ristretto@v0.1.1 (h1:6CWw5tJNgpegArSHpNHJKldNeq03FQCwYvfMVWajOK8=)
        github.com/dgryski/go-rendezvous@v0.0.0-20200823014737-9f7001d12a5f (h1:lO4WD4F/rVNCu3HqELle0jiPLLBs70cWOduZpkS1E78=)
        github.com/dlclark/regexp2@v1.4.0 (h1:F1rxgk7p4uKjwIQxBs9oAXe5CqrXlCduYEJvrF4u93E=)
        github.com/duosecurity/duo_api_golang@v0.0.0-20230418202038-096d3306c029 (h1:MDyoHXcEq2ZjPFeWrdof3GPBJohXIoL62eVxK/hjhy4=)
        github.com/dustin/go-humanize@v1.0.0 (h1:VSnTsYCnlFHaM2/igO1h6X3HA71jcobQuxemgkq4zYo=)
        github.com/facebookgo/stack@v0.0.0-20160209184415-751773369052 (h1:JWuenKqqX8nojtoVVWjGfOF9635RETekkoH6Cc9SX0A=)
        github.com/fasthttp/router@v1.4.22 (h1:qwWcYBbndVDwts4dKaz+A2ehsnbKilmiP6pUhXBfYKo=)
        github.com/fasthttp/session/v2@v2.5.3 (h1:WaiftRzSaGA4JfJGjMcGacbRLQse/Y/QKOcxR++K1yM=)
        github.com/fsnotify/fsnotify@v1.7.0 (h1:8JEhPFa5W2WU7YfeZzPNqzMP6Lwt7L2715Ggo0nosvA=)
        github.com/fxamacker/cbor/v2@v2.5.0 (h1:oHsG0V/Q6E/wqTS2O1Cozzsy69nqCiguo5Q1a1ADivE=)
        github.com/go-asn1-ber/asn1-ber@v1.5.5 (h1:MNHlNMBDgEKD4TcKr36vQN68BA00aDfjIt3/bD50WnA=)
        github.com/go-crypt/crypt@v0.2.14 (h1:+zfd2HTjmFn+6A1JvdmV+U8kV/zLHrFHeCJgc04RVFo=)
        github.com/go-crypt/x@v0.2.8 (h1:S2pV5b8ww+jdXmaSqMmvv4Aq0Gjy/4Eyzd6Sdxo5abQ=)
        github.com/go-ldap/ldap/v3@v3.4.6 (h1:ert95MdbiG7aWo/oPYp9btL3KJlMPKnP58r09rI8T+A=)
        github.com/go-sql-driver/mysql@v1.7.1 (h1:lUIinVbN1DY0xBg0eMOzmmtGoHwWBbvnWubQUrtU8EI=)
        github.com/go-webauthn/webauthn@v0.10.0 (h1:yuW2e1tXnRAwAvKrR4q4LQmc6XtCMH639/ypZGhZCwk=)
        github.com/go-webauthn/x@v0.1.6 (h1:QNAX+AWeqRt9loE8mULeWJCqhVG5D/jvdmJ47fIWCkQ=)
        github.com/golang-jwt/jwt/v5@v5.2.0 (h1:d/ix8ftRUorsN+5eMIlF4T6J8CAt9rch3My2winC1Jw=)
        github.com/golang/glog@v1.1.2 (h1:DVjP2PbBOzHyzA+dn3WhHIq4NdVu3Q+pvivFICf/7fo=)
        github.com/golang/mock@v1.6.0 (h1:ErTB+efbowRARo13NNdxyJji2egdxLGQhRaY+DUumQc=)
        github.com/golang/protobuf@v1.5.3 (h1:KhyjKVUg7Usr/dYsdSqoFveMYd5ko72D+zANwlG1mmg=)
        github.com/google/go-tpm@v0.9.0 (h1:sQF6YqWMi+SCXpsmS3fd21oPy/vSddwZry4JnmltHVk=)
        github.com/google/uuid@v1.5.0 (h1:1p67kYwdtXjb0gL0BPiP1Av9wiZPo5A8z2cWkTZ+eyU=)
        github.com/hashicorp/go-cleanhttp@v0.5.2 (h1:035FKYIWjmULyFRBKPs8TBQoi0x6d9G4xc9neXJWAZQ=)
        github.com/hashicorp/go-retryablehttp@v0.7.5 (h1:bJj+Pj19UZMIweq/iie+1u5YCdGrnxCT9yvm0e+Nd5M=)
        github.com/iancoleman/orderedmap@v0.3.0 (h1:5cbR2grmZR/DiVt+VJopEhtVs9YGInGIxAoMJn+Ichc=)
        github.com/jackc/pgpassfile@v1.0.0 (h1:/6Hmqy13Ss2zCq62VdNG8tM1wchn8zjSGOBJ6icpsIM=)
        github.com/jackc/pgservicefile@v0.0.0-20221227161230-091c0ba34f0a (h1:bbPeKD0xmW/Y25WS6cokEszi5g+S0QxI/d45PkRi7Nk=)
        github.com/jackc/pgx/v5@v5.5.2 (h1:iLlpgp4Cp/gC9Xuscl7lFL1PhhW+ZLtXZcrfCt4C3tA=)
        github.com/jackc/puddle/v2@v2.2.1 (h1:RhxXJtFG022u4ibrCSMSiu5aOq1i77R3OHKNJj77OAk=)
        github.com/jmoiron/sqlx@v1.3.5 (h1:vFFPA71p1o5gAeqtEAwLU4dnX2napprKtHr7PYIcN3g=)
        github.com/klauspost/compress@v1.17.0 (h1:Rnbp4K9EjcDuVuHtd0dgA4qNuv9yKDYKK1ulpJwgrqM=)
        github.com/knadh/koanf/maps@v0.1.1 (h1:G5TjmUh2D7G2YWf5SQQqSiHRJEjaicvU0KpypqB3NIs=)
        github.com/knadh/koanf/parsers/yaml@v0.1.0 (h1:ZZ8/iGfRLvKSaMEECEBPM1HQslrZADk8fP1XFUxVI5w=)
        github.com/knadh/koanf/providers/confmap@v0.1.0 (h1:gOkxhHkemwG4LezxxN8DMOFopOPghxRVp7JbIvdvqzU=)
        github.com/knadh/koanf/providers/env@v0.1.0 (h1:LqKteXqfOWyx5Ab9VfGHmjY9BvRXi+clwyZozgVRiKg=)
        github.com/knadh/koanf/providers/posflag@v0.1.0 (h1:mKJlLrKPcAP7Ootf4pBZWJ6J+4wHYujwipe7Ie3qW6U=)
        github.com/knadh/koanf/v2@v2.0.1 (h1:1dYGITt1I23x8cfx8ZnldtezdyaZtfAuRtIFOiRzK7g=)
        github.com/mattn/go-sqlite3@v1.14.19 (h1:fhGleo2h1p8tVChob4I9HpmVFIAkKGpiukdrgQbWfGI=)
        github.com/matttproud/golang_protobuf_extensions/v2@v2.0.0 (h1:jWpvCLoY8Z/e3VKvlsiIGKtc+UG6U5vzxaoagmhXfyg=)
        github.com/mitchellh/copystructure@v1.2.0 (h1:vpKXTN4ewci03Vljg/q9QvCGUDttBOGBIa15WveJJGw=)
        github.com/mitchellh/mapstructure@v1.5.0 (h1:jeMsZIYE/09sWLaz43PL7Gy6RuMjD2eJVyuac5Z2hdY=)
        github.com/mitchellh/reflectwalk@v1.0.2 (h1:G2LzWKi524PWgd3mLHV8Y5k7s6XUvT0Gef6zxSIeXaQ=)
        github.com/mohae/deepcopy@v0.0.0-20170929034955-c48cc78d4826 (h1:RWengNIwukTxcDr9M+97sNutRR1RKhG96O6jWumTTnw=)
        github.com/ory/fosite@v0.44.0 (h1:Z3UjyO11/wlIoa3BotOqcTkfm7kUNA8F7dd8mOMfx0o=)
        github.com/ory/go-convenience@v0.1.0 (h1:zouLKfF2GoSGnJwGq+PE/nJAE6dj2Zj5QlTgmMTsTS8=)
        github.com/ory/herodot@v0.10.3-0.20230807143059-27cd6936499b (h1:AEUyF55UrqTuhJh72I9azACdJrRrDBBjK/XWgVxuQvY=)
        github.com/ory/x@v0.0.610 (h1:SY1X5jfJVq45zeZEIc1XWqlE+lna+rMjeLxMoRdx0bY=)
        github.com/pborman/uuid@v1.2.1 (h1:+ZZIw58t/ozdjRaXh/3awHfmWRbzYxJoAdNJxe/3pvw=)
        github.com/philhofer/fwd@v1.1.2 (h1:bnDivRJ1EWPjUIRXV5KfORO897HTbpFAQddBdE8t7Gw=)
        github.com/pkg/errors@v0.9.1 (h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=)
        github.com/pmezard/go-difflib@v1.0.0 (h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=)
        github.com/prometheus/client_golang@v1.18.0 (h1:HzFfmkOzH5Q8L8G+kSJKUx5dtG87sewO+FoDDqP5Tbk=)
        github.com/prometheus/client_model@v0.5.0 (h1:VQw1hfvPvk3Uv6Qf29VrPF32JB6rtbgI6cYPYQjL0Qw=)
        github.com/prometheus/common@v0.45.0 (h1:2BGz0eBc2hdMDLnO/8n0jeB3oPrt2D08CekT0lneoxM=)
        github.com/prometheus/procfs@v0.12.0 (h1:jluTpSng7V9hY0O2R9DzzJHYb2xULk9VTR1V1R/k6Bo=)
        github.com/redis/go-redis/v9@v9.3.0 (h1:RiVDjmig62jIWp7Kk4XVLs0hzV6pI3PyTnnL0cnn0u0=)
        github.com/savsgio/gotils@v0.0.0-20230208104028-c358bd845dee (h1:8Iv5m6xEo1NR1AvpV+7XmhI4r39LGNzwUL4YpMuL5vk=)
        github.com/sirupsen/logrus@v1.9.3 (h1:dueUQJ1C2q9oE3F7wvmSGAaVtTmUizReu6fjN8uqzbQ=)
        github.com/spf13/cobra@v1.8.0 (h1:7aJaZx1B85qltLMc546zn58BxxfZdR/W22ej9CFoEf0=)
        github.com/spf13/pflag@v1.0.5 (h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=)
        github.com/stretchr/testify@v1.8.4 (h1:CcVxjf3Q8PM0mHUKJCdn+eZZtm5yQwehR5yeSVQQcUk=)
        github.com/tinylib/msgp@v1.1.9 (h1:SHf3yoO2sGA0veCJeCBYLHuttAVFHGm2RHgNodW7wQU=)
        github.com/trustelem/zxcvbn@v1.0.1 (h1:mp4JFtzdDYGj9WYSD3KQSkwwUumWNFzXaAjckaTYpsc=)
        github.com/valyala/bytebufferpool@v1.0.0 (h1:GqA5TC/0021Y/b9FG4Oi9Mr3q7XYx6KllzawFIhcdPw=)
        github.com/valyala/fasthttp@v1.51.0 (h1:8b30A5JlZ6C7AS81RsWjYMQmrZG6feChmgAolCl1SqA=)
        github.com/wneessen/go-mail@v0.4.0 (h1:Oo4HLIV8My7G9JuZkoOX6eipXQD+ACvIqURYeIzUc88=)
        github.com/x448/float16@v0.8.4 (h1:qLwI1I70+NjRFUR3zs1JPUCgaCXSh3SW62uAKT1mSBM=)
        golang.org/x/crypto@v0.18.0 (h1:PGVlW0xEltQnzFZ55hkuX5+KLyrMYhHld1YHO4AKcdc=)
        golang.org/x/net@v0.20.0 (h1:aCL9BSgETF1k+blQaYUBx9hJ9LOGP3gAVemcZlf1Kpo=)
        golang.org/x/oauth2@v0.14.0 (h1:P0Vrf/2538nmC0H+pEQ3MNFRRnVR7RlqyVw+bvm26z0=)
        golang.org/x/sync@v0.6.0 (h1:5BMeUDZ7vkXGfEr1x9B4bRcTH4lpkTkpdh0T/J+qjbQ=)
        golang.org/x/sys@v0.16.0 (h1:xWw16ngr6ZMtmxDyKyIgsE93KNKz5HKmMa3b8ALHidU=)
        golang.org/x/term@v0.16.0 (h1:m+B6fahuftsE9qjo0VWp2FW0mB3MTJvR0BaMQrq0pmE=)
        golang.org/x/text@v0.14.0 (h1:ScX5w1eTa3QqT8oi6+ziP7dTV1S2+ALU0bI+0zXKWiQ=)
        google.golang.org/genproto/googleapis/rpc@v0.0.0-20231106174013-bbf56f31fb17 (h1:Jyp0Hsi0bmHXG6k9eATXoYtjd6e2UzZ1SCn/wIupY14=)
        google.golang.org/grpc@v1.59.0 (h1:Z5Iec2pjwb+LEOqzpB2MR12/eKFhDPhuqW91O+4bwUk=)
        google.golang.org/protobuf@v1.31.0 (h1:g0LDEJHgrBl9N9r17Ru3sqWhkIx2NB67okBHPwC7hs8=)
        gopkg.in/square/go-jose.v2@v2.6.0 (h1:NGk74WTnPKBNUhNzQX7PYcTLUjoq7mzKk2OKbvwk2iI=)
        gopkg.in/yaml.v3@v3.0.1 (h1:fxVm/GzAzEWqLHuvctI91KS9hhNmmWOoWu0XTYJS7CA=)
```

### Logs (Authelia)

```shell
time="2024-02-11T02:27:24Z" level=debug msg="Process user information" gid=65534 name=nobody uid=65534 username=nobody
time="2024-02-11T02:27:24Z" level=info msg="Authelia untagged-v4.37.5 (v4.38.0-beta3, 7c764f2) is starting"
time="2024-02-11T02:27:24Z" level=info msg="Log severity set to trace"
time="2024-02-11T02:27:24Z" level=trace msg="Starting scan of directory  for certificates"
time="2024-02-11T02:27:24Z" level=debug msg="Registering client gitlab with policy two_factor (two_factor)"
time="2024-02-11T02:27:24Z" level=debug msg="Registering client cloudflare-zero-trust with policy two_factor (two_factor)"
time="2024-02-11T02:27:24Z" level=debug msg="Registering client nextcloud with policy two_factor (two_factor)"
time="2024-02-11T02:27:24Z" level=info msg="Storage schema is being checked for updates"
time="2024-02-11T02:27:24Z" level=info msg="Storage schema is already up to date"
```

### Logs (Proxy / Application)

```shell
N/A
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
In the future please follow the pre-release instructions in the pre-release feedback section. I've added some additional trace logging to the startup checks (image should be updated in a few mins with a commit sha of `70c064c4582a66bfb490c44ebdfd8dd79cc63c9e`) which may shed some light on what's going on. I suspect it's stalling on connecting to the NTP server due to a bad ndots configuration.

**Reply by james-d-elliott** [reply]
Try the new build it should give more context in where it's getting to (and what's going on).

**Reply by georglauterbach** [reply]
I apologize for not seeing these instructions; it was half past 3 and my concentration was low. I tried to fetch the image with the SHA256 `70c064c4582a66bfb490c44ebdfd8dd79cc63c9e` but could not make it work with this SHA256 - it also looks a bit short for such a hash, doesn't it?

I will try `ndots` in a second and report back.

**Reply by georglauterbach** [reply]
I was able to pin it down as I found the image you were referring to (`merge-v4.38`): it seems there is something I am still doing wrong when it comes to configuring the `notification.smtp` section. The following **works**:

```yaml
notifier:
  disable_startup_check: false
  smtp:
    address: submission://<MY MAIL SERVER ADDRESS>:587
    timeout: 10s
    username: <USERNAME>
    #password: AUTHELIA_NOTIFIER_SMTP_PASSWORD
    sender: Authelia <<USERNAME>>
    identifier: <MY MAIL SERVER ADDRESS>
    subject: '[Authelia] {title}'
    startup_check_address: <USERNAME>
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: <MY MAIL SERVER ADDRESS>
      skip_verify: false
      minimum_version: TLS1.3
```

We can see that we use port 587 which is `submission` (using STARTTLS). When I switch to `submissions` (port 465) with:

```yaml
    address: submissions://<MY MAIL SERVER ADDRESS>:465
```

my mail server logs:

```txt
postfix/submissions/smtpd[9725]: SSL_accept error from unknown[<AUTHELIA LOCAL ADDR>]: Broken pipe
postfix/submissions/smtpd[9725]: lost connection after CONNECT from unknown[<AUTHELIA LOCAL ADDR>]
postfix/submissions/smtpd[9725]: disconnect from unknown[<AUTHELIA LOCAL ADDR>] commands=0/0
```

For reference, the logs when using `submission` read

```txt
postfix/submission/smtpd[9889]: connect from unknown[<AUTHELIA LOCAL ADDR>]
postfix/submission/smtpd[9889]: Anonymous TLS connection established from unknown[<AUTHELIA LOCAL ADDR>]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (secp384r1) server-digest SHA384
postfix/submission/smtpd[9889]: disconnect from unknown[<AUTHELIA LOCAL ADDR>] ehlo=2 starttls=1 quit=1 commands=4
```
