### DISCUSSION TITLE
Request timeout occurred while handling request from client.

### DISCUSSION THREAD

**Discussion by milkas9** [authelia/authelia#6700] [Troubleshooting] [answered]
My Authelia setup is working fine. However, I am seeing a lot of this in the log and it is bugging me. Can anybody help?
I am using Taefik and all domain are through Cloudflare proxy.

<img width="1243" alt="Screenshot 2024-02-17 at 9 31 09 in the morning" src="https://github.com/authelia/authelia/assets/11433046/2c6eeca1-966b-4c6f-9e27-504e7ebff4c8">

```
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: light
jwt_secret: <redacted>
default_redirection_url: <redacted>

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers.read: 4096
  buffers.write: 4096
  # timeouts.read: 10s
  # timeouts.write: 10s
  # timeouts.idle: 20s
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info
  format: text
  file_path: "/config/authelia.log"
  keep_stdout: true

totp:
  disable: false
  issuer: <redacted>
  algorithm: sha512
  period: 30
  skew: 1
webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s


authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: <redacted>
      policy: bypass
    ## Special rule for app
    - domain: <redacted>
      query:
      - - operator: pattern
          key: <redacted>
          value: <redacted>
        - operator: equal
          key: <redacted>
          value: <redacted>
      policy: bypass
    - domain: <redacted>
      query:
      - - operator: pattern
          key: <redacted>
          value: <redacted>
        - operator: equal
          key: <redacted>
          value: <redacted>
      policy: bypass
    - domain: <redacted>
      methods: "GET"
      resources: <redacted>
      policy: bypass
    ## catch-all
    - domain: <redacted>
      subject: "group:admins"
      policy: two_factor

session:
  name: authelia_session
  domain: <redacted>
  same_site: lax
  secret: <redacted>
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  redis:
    host: <redacted>
    port: 6379
    password: <redacted>
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: "<redacted>"
  mysql:
    host: <redacted>
    port: 3306
    database: authelia
    username: <redacted>
    password: <redacted>

notifier:
  disable_startup_check: false
  smtp:
    username: <redacted>
    password: <redacted>
    host: <redacted>
    port: 587
    sender: <redacted>
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: <redacted>
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2

identity_providers:
  oidc:
    hmac_secret: <redacted>
    issuer_certificate_chain: |
      <redacted>
    issuer_private_key: |
      <redacted>
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - <redacted>
      allowed_origins_from_client_redirect_uris: false
    clients:
    - id: <redacted>
      description: <redacted>
      secret: <redacted>
      public: false
      authorization_policy: two_factor
      redirect_uris:
        - <redacted>
      scopes:
        - openid
        - profile
        - email
      grant_types:
        - authorization_code
      userinfo_signing_algorithm: none
    
    
    - id: <redacted>
      description: <redacted>
      secret: <redacted>
      public: false
      authorization_policy: two_factor
      redirect_uris:
        - <redacted>
      scopes:
        - openid
        - profile
        - groups
        - email
      userinfo_signing_algorithm: none
```
