### DISCUSSION TITLE
Access rules not applied after PROXY protocol

### DISCUSSION THREAD

**Discussion by karlis-vagalis** [authelia/authelia#6734] [Q&A] [answered]
Hello,

I have encountered a weird issue, which has appeared after introducing proxy_protocol on NGINX (SWAG flavour) in front of the Authelia instance. Short overview: Haproxy -> NGINX -> sudomains, incl. Authelia

I had completely perfectly working Authelia instance before and now, when accessing some subdomain, which is protected by Authelia, the access rules defined in the configuration are not applied anymore, for example, when accessing the subdomain from external ip, which requires authentication, the user is not required to authenticate anymore and is forwarded directly.

I do not think this is a reverse proxy misconfiguration, because Authelia with trace log enabled shows the requests to `/authelia/api/verify` endpoint with correct external ip address for `remote_ip` attribute, so the headers on NGINX seem to be set properly. How can I see more details on what is causing the issue? Does anybody have any ideas?

Thanks a lot in advance!

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Given the context you've provided, it seems like the issue might be related to how Authelia is interpreting the headers forwarded by NGINX, especially considering the introduction of `proxy_protocol`. When `proxy_protocol` is enabled, it alters the way the original client IP is forwarded to the backend services, which can affect how Authelia processes access rules based on IP addresses.

Here are a few steps and considerations to help diagnose and potentially resolve the issue:

1. **Verify Forwarded Headers**: Ensure that NGINX is correctly setting the necessary headers for Authelia to function, particularly `X-Forwarded-For` for the client's IP address. Authelia relies on these headers to apply access control rules. The headers should match exactly with the URL displayed in the user's browser for the protected application. [Source](https://www.authelia.com/integration/proxies/introduction)

2. **Trusted Proxies Configuration**: When using `proxy_protocol`, ensure that Authelia and any intermediate proxies (like HAProxy) are configured to trust the forwarded headers from NGINX. This might involve setting up trusted proxies within Authelia's configuration to ensure it accepts the forwarded headers as legitimate. [Source](https://www.authelia.com/integration/proxies/nginx)

3. **Check Authelia's Access Control Rules**: Review the access control rules defined in Authelia's configuration. Ensure they are correctly set up to require authentication for the subdomains in question. Misconfiguration here could lead to unexpected behavior. [Source](https://github.com/authelia/authelia/discussions/5520)

4. **Review Proxy Protocol Configuration**: Double-check the `proxy_protocol` configuration on both HAProxy and NGINX to ensure it's correctly implemented. Incorrect implementation can lead to issues with IP forwarding and, subsequently, access control based on IP addresses. [Source](https://www.authelia.com/integration/proxies/haproxy)

5. **Authelia Logs**: Since you mentioned that Authelia's trace log shows the correct external IP address, it would be helpful to look for any logs that indicate why the access rules are not being applied as expected. Look for any errors or warnings that might give clues.

6. **Network Configuration**: Ensure that the network configuration between HAProxy, NGINX, and Authelia does not strip or alter headers in a way that would affect Authelia's ability to enforce access rules.

If after checking these areas the issue persists, it might be beneficial to provide more detailed logs from Authelia, NGINX, and HAProxy (ensuring sensitive information is redacted) for a deeper analysis. Additionally, reviewing the exact `proxy_protocol` configuration lines in both HAProxy and NGINX could reveal potential misconfigurations.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment]
Showing the trace logs may yield more information, I suspect it's a bug with nginx or incompatibility with the auth_request module and PROXY protocol. I'd also suggest showing your ACLs and an example app that no longer works (nginx config).

**Comment by karlis-vagalis** [comment]
Here are the logs from Authelia, which indicate correct external ip address making the requests:

```json
{"level":"trace","method":"GET","msg":"Request hit","path":"/authelia/api/verify","remote_ip":"80.186.81.95","time":"2024-02-26T13:32:04+01:00"}
{"level":"trace","method":"GET","msg":"Replied (status=200)","path":"/authelia/api/verify","remote_ip":"80.186.81.95","time":"2024-02-26T13:32:04+01:00"}
```

We can see, that for whatever reason the authelia responds to those remote addresses with 200 code instead of 401.

NGINX headers for proxy are set in `http` block with:
```
...
set_real_ip_from 172.23.0.0/16;
real_ip_header proxy_protocol;
real_ip_recursive on;
...
```

Here is `authelia-location.conf`
```nginx
## Version 2023/04/27 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx/authelia-location.conf.sample
# Make sure that your authelia container is in the same user defined bridge network and is named authelia
# Rename /config/nginx/proxy-confs/authelia.subdomain.conf.sample to /config/nginx/proxy-confs/authelia.subdomain.conf
# Make sure that the authelia configuration.yml has 'path: "authelia"' defined

## Send a subrequest to Authelia to verify if the user is authenticated and has permission to access the resource
auth_request /authelia/api/verify;
## If the subreqest returns 200 pass to the backend, if the subrequest returns 401 redirect to the portal
error_page 401 = @authelia_proxy_signin;

## Translate the user information response headers from the auth subrequest into variables
auth_request_set $email $upstream_http_remote_email;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $user $upstream_http_remote_user;

## Inject the user information into the request made to the actual upstream
proxy_set_header Remote-Email $email;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name $name;
proxy_set_header Remote-User $user;

## Translate the Set-Cookie response header from the auth subrequest into a variable
auth_request_set $set_cookie $upstream_http_set_cookie;

## Translate the Location response header from the auth subrequest into a variable
auth_request_set $signin_url $upstream_http_location;
```

Here is `authelia-server.conf`
```nginx
## Version 2023/04/27 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx/authelia-server.conf.sample
# Make sure that your authelia container is in the same user defined bridge network and is named authelia
# Rename /config/nginx/proxy-confs/authelia.subdomain.conf.sample to /config/nginx/proxy-confs/authelia.subdomain.conf
# Make sure that the authelia configuration.yml has 'path: "authelia"' defined

# location for authelia subfolder requests
location ^~ /authelia {
    auth_request off; # requests to this subfolder must be accessible without authentication
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_authelia authelia;
    proxy_pass http://$upstream_authelia:9091;
}

# location for authelia auth requests
location = /authelia/api/verify {
    internal;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_authelia authelia;
    proxy_pass http://$upstream_authelia:9091;

    ## Include the Set-Cookie header if present
    auth_request_set $set_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $set_cookie;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
}

# virtual location for authelia 401 redirects
location @authelia_proxy_signin {
    internal;

    ## Include the Set-Cookie header if present
    auth_request_set $set_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $set_cookie;

    ## Set the $target_url variable based on the original request
    set_escape_uri $target_url $scheme://$http_host$request_uri;

    ## Translate the Location response header from the auth subrequest into a variable
    auth_request_set $signin_url $upstream_http_location;

    if ($signin_url = '') {
        ## Set the $signin_url variable
        set $signin_url https://auth.example.com/authelia/?rd=$target_url;
    }

    ## Redirect to login
    return 302 $signin_url;
}
```

And this is the server block for a example subdomain:
``` nginx
server {

    listen 443 ssl http2 proxy_protocol;
    listen [::]:443 ssl http2 proxy_protocol;

    server_name test.* ;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app container;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}

```

**Comment by james-d-elliott** [comment]
If those are your only logs you've misconfigured your proxy/authelia most likely. Show the server section of authelia? i.e. https://www.authelia.com/configuration/miscellaneous/server/

**Comment by karlis-vagalis** [comment]
Here it is. This deviates from official documentation, because I am already running 4.38beta

```yaml
##
## Server Configuration
##
server:
  ## The address to listen on.
  address: tcp://0.0.0.0:9091
  ## Set the path on disk to Authelia assets.
  ## Useful to allow overriding of specific static assets.
  # asset_path: /config/assets/
  ## Disables writing the health check vars to /app/.healthcheck.env which m>
  ## This is disabled by default if either /app/.healthcheck.env or /app/hea>
  disable_healthcheck: false
  ## Authelia by default doesn't accept TLS communication on the server port>
  tls:
    ## The path to the DER base64/PEM format private key.
    key: ""
    ## The path to the DER base64/PEM format public certificate.
    certificate: ""
    ## The list of certificates for client authentication.
    client_certificates: []
  ## Server headers configuration/customization.
  headers:
    ## The CSP Template. Read the docs.
    csp_template: ""
  ## Server Buffers configuration.
  # buffers:
    ## Buffers usually should be configured to be the same value.
    ## Explanation at https://www.authelia.com/c/server#buffer-sizes
    ## Read buffer size adjusts the server's max incoming request size in by>
    ## Write buffer size does the same for outgoing responses.
    ## Read buffer.
    # read: 4096
    ## Write buffer.
    # write: 4096

  ## Server Timeouts configuration.
  # timeouts:
    ## Read timeout.
    # read: 6s
    ## Write timeout.
    # write: 6s
    ## Idle timeout.
    # idle: 30s
  ## Server Endpoints configuration.
  ## This section is considered advanced and it SHOULD NOT be configured unl>
  endpoints:
    ## Enables the pprof endpoint.
    enable_pprof: false
    ## Enables the expvars endpoint.
    enable_expvars: false
## Configure the authz endpoints.
    # authz:
    #   forward-auth:
    #     implementation: 'ForwardAuth'
    #     authn_strategies: []
    #   ext-authz:
    #     implementation: 'ExtAuthz'
    #     authn_strategies: []
    #   auth-request:
    #     implementation: 'AuthRequest'
    #     authn_strategies: []
    #   legacy:
    #     implementation: 'Legacy'
    #     authn_strategies: []

```
