### DISCUSSION TITLE
Possible to allow user access based on matched username with Named Domain Regex?

### DISCUSSION THREAD

**Discussion by dohsimpson** [authelia/authelia#6749] [Q&A] [answered]
I'm a bit confused when reading the doc regarding [Named Domain Regex](https://github.com/authelia/authelia/issues). In particular, would it be possible to make use of the matched group (e.g. username) in other fields such as `subject`, so that we can grant access to that user to their respective `USERNAME.example.com` domain?

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Based on the information provided in the context, it is indeed possible to utilize matched groups, such as a username, in fields like `subject` to dynamically grant access to users for domains that match their username. This functionality is facilitated through the use of named regex groups within the domain_regex criteria and can be applied in the access control configuration.

For instance, you can define a domain_regex that captures the username from the domain and then use this captured username in the subject field to specify that only the user with that username should have access. This is particularly useful for creating generic access control rules that apply to multiple users without the need to explicitly define an access control list (ACL) for each user.

An example provided in the context demonstrates how to match a user's username in the domain and grant access based on that:

```yaml
access_control:
  rules:
    - domain_regex:
        - '^user-(?P<User>\\w+)\\.example\\.com$'
      policy: one_factor
```

In this example, the `(?P<User>\\w+)` part is a named regex group that captures the username. This captured username can then be used to dynamically apply access control policies based on the user's identity.

It's important to note that while the specific use of matched groups in other fields like `subject` was not directly mentioned in the provided context, the concept of named regex groups and their application in dynamic access control scenarios is supported. This allows for flexible and dynamic access control configurations that can adapt to various user-specific scenarios without requiring manual updates to the ACL for each new user.

For more detailed information on configuring access control and utilizing named regex groups in Authelia, you can refer to the official documentation:
- Access Control: https://www.authelia.com/configuration/security/access-control
- Named Regex Groups: https://www.authelia.com/configuration/security/access-control/#named-regex-groups

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment]
Other than the escapes the AI nailed it:

```yaml
access_control:
  rules:
    - domain_regex:
        - '^user-(?P<User>\w+)\.example\.com$'
      policy: one_factor
```

**Reply by james-d-elliott** [reply]
Basically this pattern will match `user-john.example.com` if the username is `john`.

**Comment by dohsimpson** [comment]
Thanks for the reply! If I understand correctly, in this example:

```
access_control:
  rules:
    - domain_regex:
        - '^user-(?P<User>\w+)\.example\.com$'
      policy: one_factor
```

This will only allow matched user to access this site.

If I specify `subject` under this rule as well, would those subjects be allowed access as well?

**Reply by james-d-elliott** [reply]
What would be the use case for specifying subjects at the same time as the regex groups?

**Reply by dohsimpson** [reply]
In my case, I would like to have the user able to access a url with their username, and I would like the admin group to have access to that url as well.

**Reply by james-d-elliott** [reply, marked as answer]
You'd define a separate rule for that. Otherwise user-john.example.com would never match the admin fred so it'd never give him access.

```yaml
access_control:
  rules:
    - domain_regex:
        - '^user-\w+\.example\.com$'
      subject:
        - ['group:admins']
      policy: one_factor
    - domain_regex:
        - '^user-(?P<User>\w+)\.example\.com$'
      policy: one_factor
```
