### DISCUSSION TITLE
Two Authelia Servers; Same Subdomain

### DISCUSSION THREAD

**Discussion by threehappypenguins** [authelia/authelia#6908] [Q&A] [answered]
As was explained in this post [here](https://github.com/authelia/authelia/issues/6841), I'm looking to find a way to be able to stay signed into both subdomains simultaneously without getting signed out when I sign in the other. I use nginx proxy manager. I have been told that I need to do this with Redis. So far, I have a docker container of authelia with:

```
session:
  name: authelia_session
  secret: mysupersecret
  expiration: 86400
  inactivity: 86400
  remember_me_duration:  1M
  domain: mydomain.com
  redis:
    host: redis-container
    port: 6379
```

And I've spun up a docker container for redis that's connected to the same docker network as authelia:

version: '3'

```
services:
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - docker_default

networks:
  docker_default:
    external: true
    name: docker_default
```

Now, I think I need to connect to port 6379 remotely from outside of the network from my authelia container running on another computer. But I'm trying to do it securely. Any ideas? Or am I going about this all incorrectly?

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

To achieve simultaneous sign-in across subdomains without getting signed out when signing into another, using Redis for session storage with Authelia is indeed a good approach. Your current setup with Authelia and Redis in Docker containers connected to the same network is correct. However, to securely connect to the Redis container from an Authelia instance running on another computer, you should consider the following:

1. **Avoid Exposing Redis Port Publicly**: Directly exposing Redis's port (6379) to the internet is not recommended due to security concerns. Instead, ensure that the port is only accessible within your internal network or Docker network.

2. **Use a Secure Connection**: If your Authelia instances need to access Redis across different hosts securely, consider setting up a VPN or an SSH tunnel to securely route the traffic through the encrypted connection. This way, you can avoid exposing Redis directly to the public internet.

3. **Redis Authentication and TLS**: Ensure that Redis is configured with a strong password, and consider enabling TLS for Redis connections to encrypt the data in transit. Starting with Redis version 6, it supports SSL/TLS encryption.

4. **Network Configuration**: Ensure that your Docker networks and firewall rules are configured to allow connections between the Authelia containers and the Redis container securely. You might need to adjust your Docker network settings or firewall rules to allow these connections only from specific sources.

5. **Redis Configuration in Authelia**: On the Authelia instance running on another computer, ensure that the Redis configuration points to the correct hostname or IP address of the Redis container, and the port is correctly specified. Use the secure method you've chosen (VPN or SSH tunnel) to refer to the Redis host.

Example Redis configuration in Authelia (adjust the `host` to match your secure connection setup):

```yaml
session:
  name: authelia_session
  secret: mysupersecret
  expiration: 86400
  inactivity: 86400
  remember_me_duration: 1M
  domain: mydomain.com
  redis:
    host: redis-container # Adjust this to the secure endpoint
    port: 6379
    # If you've set up a password for Redis:
    password: your_redis_password
    # If using TLS (adjust according to your setup):
    tls:
      server_name: redis-server
      skip_verify: false
```

Remember, the security of your setup is paramount. Ensure that any method used to connect to Redis remotely is secure and that only authorized Authelia instances can access the Redis service.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
