### DISCUSSION TITLE
Remember me not working after container restart

### DISCUSSION THREAD

**Discussion by Boerny41** [authelia/authelia#6911] [Q&A] [answered]
Remember me always forgets my login information after the container gets restarted. I was not able to find any it mentioned anywhere and I'm not sure it it's a bug, intended or misconfiguration by myself.

Currently running authelia 4.38.2 on docker with Nginx proxy manager v. 2.11.1 however this issue is not depended on these versions.

Below is the session section my my configuration.yml. I've tried different values like 20d, 3M, 1y but nothing actually worked. Below that I'll post my docker compose file.
```
session:
  name: myAutheliaName
  secret: mySecret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: myDomain.xx  # Should match whatever your root protected domain is
  remember_me_duration:  8M
```

```
version: '3'
services:
  authelia:
    container_name: authelia    
    image: authelia/authelia:latest
    ports:
      - myPort:9091
    volumes:
      - /home/myUsername/authelia:/config
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entryPoints: https
    restart: unless-stopped
    environment:
      - TZ=myTimezone

networks:
    default:
      name: myNetwork
      external: true
```

**Comment by glime-ai** [comment, marked as answer]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

The issue you're experiencing with the "Remember Me" feature forgetting your login information after a container restart is likely due to the use of an in-memory session provider. When Authelia is configured to use the default in-memory session provider, all session information is stored in the memory of the Authelia container. Therefore, when the container is restarted, all session data is lost, including the "Remember Me" sessions.

To resolve this issue, you should configure Authelia to use a persistent session provider, such as Redis. This will ensure that session data is stored outside of the container and persists across restarts.

Here's a brief guide on how to configure Redis as the session provider for Authelia:

1. **Add a Redis service to your Docker Compose file**: You need to run a Redis container alongside Authelia. You can add a Redis service to your `docker-compose.yml` file. Here's an example snippet:

```yaml
services:
  redis:
    image: redis:alpine
    container_name: authelia-redis
    volumes:
      - /home/myUsername/redis:/data
```

2. **Configure Authelia to use Redis for sessions**: Modify your `configuration.yml` to use Redis as the session provider. Here's how you can adjust the session section:

```yaml
session:
  name: myAutheliaName
  secret: mySecret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: myDomain.xx  # Should match whatever your root protected domain is
  remember_me_duration: 8M
  redis:
    host: authelia-redis
    port: 6379
```

Make sure that the `host` in the Redis configuration matches the `container_name` of the Redis service in your `docker-compose.yml`.

3. **Restart your Docker containers**: After making these changes, restart your Docker containers to apply the new configuration.

By configuring Authelia to use Redis for session storage, your sessions, including "Remember Me" data, will persist across container restarts, addressing the issue you've encountered.

For more detailed information on configuring session providers in Authelia, please refer to the official documentation:
- Session Configuration: https://www.authelia.com/configuration/session/introduction
- Redis as a Session Provider: https://www.authelia.com/configuration/session/redis/

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
