### DISCUSSION TITLE
Windows 11 Desktop Bitwarden App FIDO2 WebAuthn Stuck on "Loading"

### DISCUSSION THREAD

**Discussion by qymab** [authelia/authelia#6925] [Troubleshooting] [answered]
I have a similar issue to the one described in [this discussion](https://github.com/dani-garcia/vaultwarden/discussions/2111). I have removed all headers and confirmed that the app from the Microsoft Store and the direct download have the same [problems](https://github.com/dani-garcia/vaultwarden/discussions/3708). I'm using Authelia and Traefik.

My findings so far:

If I change the middlewares from ```chain-authelia``` to ```chain-no-auth```, which has this chain:

```chain-no-auth.yml```:
```yaml
http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-compress
```

```chain-authelia.yml```:
```yaml
http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authelia
          - middlewares-compress
```

``` middlewares-secure-headers.yml```:
```yaml
http:
  middlewares:
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - X-Forwarded-Host
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
```

The only difference is the ```middlewares-authelia```. With ```chain-no-auth```, WebAuthn works fine. Therefore, I think the fault isn't in Traefik.

This is the ```middlewares-authelia.yml```:
```yaml
http:
  middlewares:
    middlewares-authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://auth.domain.com
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
```

And this is the Authelia configuration:
```yaml
default_redirection_url: https://auth.domain.com

server:
  host: 0.0.0.0
  port: 9091

totp:
  issuer: authelia.com
  period: 30
  skew: 1

access_control:
  default_policy: deny
  rules:
    - domain: 'auth.domain.com'
      policy: bypass
    - domain: 'traefik.domain.com'
      policy: two_factor
      subject:
        - 'group:admins'
    - domain: 'traefik.domain.com'
      policy: deny
    - domain: 'vaultwarden.domain.com'
      policy: two_factor
      resources:
        - '^/admin([/?].*)?$'
      subject:
        - 'group:admins'
    - domain: 'vaultwarden.domain.com'
      resources:
        - '^/admin([/?].*)?$'
      policy: deny
    - domain: 'vaultwarden.domain.com'
      policy: bypass
      resources:
        - '^/api([/?].*)?$'
        - '^/notifications([/?].*)?$'
        - '^/identity([/?].*)?$'
    - domain: '*.domain.com'
      policy: two_factor
    - domain: 'domain.com'
      policy: two_factor
```

Any pointers on what I should check next?
