### DISCUSSION TITLE
Access to Favicon etc

### DISCUSSION THREAD

**Discussion by RefineryX** [authelia/authelia#6926] [Q&A]
I am seeing a few 302 error in my logs, specifically relating to Safari unable to get access to the following resources.

```
msg=Access to https://sub.mydomain.com/apple-touch-icon-precomposed.png (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.mydomain.com/?rd=https%3A%2F%2Fsub.mydomain.com%2Fapple-touch-icon-precomposed.png&rm=GET
```

Other items it's giving the same error for:
```
/apple-touch-icon-precomposed.png
/assets/safari-pinned-tab.svg
/apple-touch-icon-180x180.png
/apple-touch-icon.png
/favicon.ico
```

In my config file, I have the following 
```
access_control:

  ## Default policy (applied if no other policies)
  default_policy: deny

  rules:

    # Catch all - Rule applied to admin
    - domain: '*.mydomain.com'
      policy: one_factor
      subject:
        - 'user:admin'

```
I have some links bookmarked in Safari but unable to see any of their icons etc. Anyone know how I resolve this? Like allowing it to gain access to these images but still protecting the domain.

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

To resolve the issue of Safari being unable to access specific resources like icons and images on your domain due to 302 errors, you can add specific bypass rules for these resources in your Authelia configuration. This approach allows these resources to be accessed without authentication, preventing the 302 redirect to the login page for these specific paths while keeping the rest of the domain protected.

You can add the following rules to your `access_control` configuration to bypass authentication for the mentioned resources:

```yaml
access_control:
  default_policy: deny
  rules:
    # Bypass rule for specific resources
    - domain: '*.mydomain.com'
      resources:
        - '^/apple-touch-icon-precomposed\\.png$'
        - '^/assets/safari-pinned-tab\\.svg$'
        - '^/apple-touch-icon-180x180\\.png$'
        - '^/apple-touch-icon\\.png$'
        - '^/favicon\\.ico$'
      policy: bypass

    # Catch all - Rule applied to admin
    - domain: '*.mydomain.com'
      policy: one_factor
      subject:
        - 'user:admin'
```

This configuration specifies that requests to the listed resources should bypass authentication (`policy: bypass`), while the rest of the domain is protected and requires one factor authentication for the admin user. Make sure to place the bypass rules before any broader rules to ensure they are matched first, as Authelia processes the rules in sequential order.

Remember to reload or restart Authelia after updating the configuration to apply the changes.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment]
The bot is mostly correct::

```yaml
access_control:
  default_policy: deny
  rules:
    # Bypass rule for specific resources
    - domain: '*.mydomain.com'
      resources:
        - '^/apple-touch-icon-precomposed\.png$'
        - '^/assets/safari-pinned-tab\.svg$'
        - '^/apple-touch-icon-180x180\.png$'
        - '^/apple-touch-icon\.png$'
        - '^/favicon\.ico$'
      policy: bypass

    # Catch all - Rule applied to admin
    - domain: '*.mydomain.com'
      policy: one_factor
      subject:
        - **'user:admin'**
```
