### DISCUSSION TITLE
Generic access control for user based subdomains?

### DISCUSSION THREAD

**Discussion by OCram85** [authelia/authelia#6931] [Q&A] [answered]
Hey folks,
just started using authelia in my environment. Is there a way to define a generic access control for the following pattern to allow a user accessing his personal instance but no other?

>To avoid editing and repeating the access control policies like this I would like to find a generic approach:

Users: 
-  UserA
- UserB
- UserN
- ...

Access Control:

```yaml
access_control:
  rules:
    - domain: 'instance-<USER>.mydomain.com'
    policy: 'one_factor'
    subject:
      - ['user:<User>']
```

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Yes, you can achieve a generic access control configuration by utilizing named regex groups in the `resources` section of your access control configuration. This approach allows you to dynamically match the URL path to the authenticated username, thus enabling a more scalable and maintainable setup without the need to explicitly define access control rules for each user.

Here's an example of how you might configure this:

```yaml
access_control:
  rules:
    - domain: 'my.mydomain.tld'
      policy: one_factor
      resources:
        - '^/{{username}}/.*$'
      subject:
        - 'user:{{username}}'
```

In this configuration, `{{username}}` acts as a placeholder for the authenticated user's username. This way, when a user accesses a path that matches their username, the rule applies, granting them access based on the specified policy.

Please note, the exact syntax for implementing named regex groups and referencing them in the `subject` might vary and the example provided here is illustrative. Authelia's documentation or support channels should provide the most accurate and up-to-date syntax.

For more detailed information on configuring access control and utilizing regex in Authelia, refer to the official documentation: https://www.authelia.com/configuration/security/access-control/#resources

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment, marked as answer]
See [domain_regex](https://www.authelia.com/configuration/security/access-control/#domain_regex) as this is the method for achieving this.

Example (where the `\w+` pattern matches the expected username, see the [Regex 101](https://regex101.com/) golang flavour):

```yaml
access_control:
  rules:
  - domain_regex:
    - '^instance-(?P<User>\w+)\.example\.com$'
    policy: 'one_factor'
```
