### DISCUSSION TITLE
How to persist sessions?

### DISCUSSION THREAD

**Discussion by wsw70** [authelia/authelia#6953] [Q&A] [answered]
I noticed that all my session tokens are invalidated when I restart Authelia. 
Is there a way to persist them between restarts? (so that users do not need to re-authenticate)

**Comment by glime-ai** [comment, marked as answer]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Yes, there is a way to persist session tokens between Authelia restarts to prevent users from needing to re-authenticate. The issue you're experiencing is likely due to Authelia's default session provider being in-memory. When using the in-memory session provider, all session information is stored in the memory of the Authelia container. Therefore, when the container is restarted, all session data, including session tokens, is lost.

To resolve this issue and ensure session persistence across restarts, you should configure Authelia to use a persistent session provider, such as Redis. Redis is a stateless session provider that stores session data outside of the container, allowing it to persist across container restarts.

Here's a brief guide on how to configure Redis as the session provider for Authelia:

1. **Add a Redis service to your Docker Compose file**: You need to run a Redis container alongside Authelia. You can add a Redis service to your `docker-compose.yml` file. Here's an example snippet:
   ```yaml
   services:
     redis:
       image: redis:alpine
       container_name: authelia-redis
       volumes:
         - /path/to/redis/data:/data
   ```

2. **Configure Authelia to use Redis for sessions**: Modify your `configuration.yml` to use Redis as the session provider. Here's how you can adjust the session section:
   ```yaml
   session:
     name: authelia_session
     secret: your_session_secret
     expiration: 1h  # 1 hour
     inactivity: 5m  # 5 minutes
     domain: your_domain.com
     remember_me_duration: 1M
     redis:
       host: authelia-redis
       port: 6379
   ```
   Make sure that the host in the Redis configuration matches the `container_name` of the Redis service in your `docker-compose.yml`.

3. **Restart your Docker containers**: After making these changes, restart your Docker containers to apply the new configuration.

By configuring Authelia to use Redis for session storage, your sessions, including "Remember Me" data, will persist across container restarts, addressing the issue you've encountered.

For more detailed information on configuring session providers in Authelia, please refer to the official documentation:
- Session Configuration: https://www.authelia.com/configuration/session/introduction
- Redis as a Session Provider: https://www.authelia.com/configuration/session/redis/

This solution should help you achieve session persistence across Authelia restarts.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
