### DISCUSSION TITLE
Allow specifying cookies config with environment variables

### DISCUSSION THREAD

**Discussion by jonasgeiler** [authelia/authelia#6994] [Ideas]
### Description

Right now the only way to configure the cookies is to use a config file, and since the cookies are required to be configured this is basically makes a config file the only possible configuration method and environment variables / secrets only useful **_on top_** of a config file.
Earlier versions of Authelia allowed me to completely configure everything using environment variables, which was super convenient since I could put those in my docker-compose.yml file, but with the deprecation of environment variables like `AUTHELIA_SESSION_DOMAIN` this isn't possible anymore and it sucks...

I have looked into the configuration library Authelia uses, `koanf`, and it actually supports configuring maps and arrays with environment variables, which would look like this: 
```env
AUTHELIA_COOKIES=[map[domain:example.com authelia_url:https://auth.example.com]]
```
Unfortunately Authelia doesn't seem to use this feature of `koanf` at this point in time :/

So, TL;DR: my feature request is to add support for setting maps and arrays in environment variables by using the `koanf` feature mentioned above.

### Use Case

Completely configure Authelia in a docker-compose.yml file, like below, without the need to manually create and maintain a config file:
```yaml
authelia:
  image: authelia/authelia:4.38.6
  container_name: authelia
  volumes:
    - authelia_config:/config
  environment:
    # ... a bunch of other envs ...
    AUTHELIA_COOKIES: '[map[domain:example.com authelia_url:https://auth.example.com]]'
    # ... a bunch of other envs ...
```

### Documentation

- https://github.com/knadh/koanf#reading-environment-variables
- https://github.com/knadh/koanf/blob/master/parsers/dotenv/dotenv_test.go

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Based on the information provided and the context from the sources, it appears that your request to configure Authelia entirely through environment variables, specifically for maps and arrays like the `cookies` configuration, is currently not supported due to limitations in how Authelia processes environment variables. The Authelia team has discussed similar requests and has decided against implementing a custom environment parser for complex configurations due to the potential for misconfiguration and maintenance challenges. This decision is reflected in the response to a feature request on their GitHub issue tracker, where they express a preference for using file-based configurations with templating engines for more complex setups.

However, Authelia does support a form of environment variable configuration for simpler settings, as detailed in the documentation. For secrets and other sensitive information, Authelia allows environment variables to point to files containing the sensitive data, which is a security best practice.

For your specific use case of wanting to configure `cookies` and other complex settings entirely through environment variables, the recommended approach would be to utilize the file-based configuration alongside the templating features that Authelia is planning to introduce. These features are intended to offer more flexibility in configuration by allowing environment variables within the configuration files themselves.

While this does not fully address your request for direct environment variable configuration for complex types, it represents the current stance and available features of Authelia as of the latest information available.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment]
I believe it is a lot harder than it sounds, in fact if it supports it then it should effectively already be working. See the example: https://github.com/james-d-elliott/koanf-example

These tests fail to produce any usable result, but feel free to suggest any edits, if we get it working in any usable way we'd consider it. The only complication is if we feel it's something we can provide support for at that point 

Per #3249 and #6574 it's just not practical for us to maintain something like this if we have to implement a parsing syntax for it.

**Comment by jonasgeiler** [comment]
@james-d-elliott Okay so I've looked into it further and also tried to get your example working for an hour or two but without success... I think those weird arrays and maps are only parsed when working with `dotenv.Parser()`, which is intended for `.env` files and not environment variables in general and doesn't work. I don't know. But it won't work without much modification :/

But on the other hand I've just looked into the config file filters feature of Authelia and it works for my use case for now. I just have to use a custom Dockerfile that extends from Authelia's base image and create a little config file with templating enabled.
For future reference, and for other people looking for this, here's how I did it now:

- `authelia/configuration.yml`:
  ```yaml
  session:
    cookies:
      - domain: '{{ mustEnv "MY_DOMAIN" }}'
        authelia_url: '{{ mustEnv "MY_AUTHELIA_URL" }}'
  ```
- `authelia/Dockerfile`:
  ```dockerfile
  FROM authelia/authelia:4.38.6

  COPY ./configuration.yml /app/configuration.yml

  # Here I usually copy an initial users.yml file into the config folder,
  # but I'll leave it out for this demo.
  #COPY ./users.yml /config/users.yml

  ENV X_AUTHELIA_CONFIG_FILTERS="template" \
      X_AUTHELIA_CONFIG="/app/configuration.yml"
  ```
- `docker-compose.yml`:
  ```yaml
  authelia:
    build: ./authelia
    image: authelia/authelia:4.38.6
    container_name: authelia
    #volumes:
    #  - authelia_config:/config
    environment:
      # ... a bunch of other envs ...
      MY_DOMAIN: example.com
      MY_AUTHELIA_URL: https://auth.example.com
      # ... a bunch of other envs ...
  ```
  
Feel free to close this issue or leave it open if you will ever consider adding a more proper support for environment variables configuration.
Or turn it into a discussion for future reference for other users :)

**Comment by james-d-elliott** [comment]
I was planning to mention the env template features but forgot. Glad you found it. I am going to convert it to a discussion it though, if people figure something out we can implement it. We know people want it we at the very least need examples of other apps that do this to find a format that works, and then get koanf to implement it hopefully.

**Comment by james-d-elliott** [comment]
Also for reference I also spent a LOT of time trying to get this working without a custom parser.

**Reply by jonasgeiler** [reply]
Thank you for your hard work 🙏🏼🩶

**Comment by WilliamStam** [comment]
yeah thanks guys for all the effort! 

the issue i have with the config file as is is that you cant pass in env variables like ${DOMAIN}.

wouldnt something like how traefik handles the labels work in a case like this? 

```
AUTHELIA_ACCESS_CONTROL_RULES_this_can_be_anything_DOMAIN
AUTHELIA_ACCESS_CONTROL_RULES_this_can_be_anything_POLICY
```

would need something on the ingesting of the vars tho to split it out which might be a ballache

im thinking here of something like

```
AUTHELIA_ACCESS_CONTROL_RULES_0_DOMAIN=xxx
AUTHELIA_ACCESS_CONTROL_RULES_0_POLICY=xxx
AUTHELIA_ACCESS_CONTROL_RULES_1_DOMAIN=xxx
AUTHELIA_ACCESS_CONTROL_RULES_1_POLICY=xxx
```

(useful wherever theres a list of "objects?" )

**Reply by james-d-elliott** [reply]
One particular issue with access control in general is there are some fairly advanced ways to configure it, as soon as it gets advanced people will want to configure the advanced methods in YAML, but the order matters, and determining order intent when mixing them is almost impossible without adding additional elements users must configure.

In addition, this would be complex to implement in general as it would require a custom built parser which is not something we want to maintain.

**Reply by WilliamStam** [reply]
fair point. 

i know docker container isnt the primary focus of the project as well so that does hinder a bit. 

as to the order requirement - the _0_ and _1_ would probably take care of that. 

my main concern here is that most of the values needed in the config file are already defined in the outer compose .env like domain which would be required for the cookies option. 

i like @jonasgeiler 's approach for adding in template values into the config. just dont like the idea of the dockerfile first to get templating working. if it is it natively supported ie if i add a configuration.yaml with `'{{ mustEnv "MY_DOMAIN" }}` in it then im totaly ok with that and would think that would be by far the best approach to solving it tbh

**Reply by james-d-elliott** [reply]
> i know docker container isnt the primary focus of the project as well so that does hinder a bit.

What?

> as to the order requirement - the 0 and 1 would probably take care of that.

Unfortunately this is not the case. It doesn't account for users who will specify it in both ENV and YAML and it doesn't account for the parser requirement. To illustrate the ENV and YAML issue how do you determine the order if 3 rules are defined in ENV and 3 are defined in YAML. To illustrate the need for a parser try to express this rule in ENV:

```yaml
    - domain: 
        - 'secure.example.com'
        - 'extrasecure.example.com'
      domain_regex:
        - '^secure-\w+.example.com$'
      policy: 'one_factor'
      networks:
        - 'internal'
        - 'VPN'
        - '192.168.1.0/24'
        - '10.0.0.1'
      methods:
        - 'OPTIONS'
      subject: 
      - ['group:admins', 'group:mods']
      - 'user:admin'
      resources:
      - '^/groups/dev/.*$'
      - '^/users/dev/.*$'
```

> adding in template values into the config. just dont like the idea of the dockerfile first to get templating working. if it is it natively supported ie if i add a configuration.yaml with '{{ mustEnv "MY_DOMAIN" }} in it then im totaly ok with that and would think that would be by far the best approach to solving it tbh

You can set environment variables without building a docker image as with any image as per the [docs](https://www.authelia.com/configuration/methods/files/).

**Reply by WilliamStam** [reply]
i am sooooooo sorry! i honestly didnt understand that part :( 

well.. this works great

```
#compose.yml
services:
    authelia:
        image: authelia/authelia:latest
        container_name: authelia
        volumes:
            - ./config:/config
        command:
            - 'authelia'
            - '--config=/config/configuration.yml'
            - '--config.experimental.filters=expand-env'
        environment:
            - TZ
            - LOG_LEVEL=infogggg
```
(notice the log level misspelling. thats just to see that it makes it into the log)

```
#configuration.yml
log:
  ## Level of verbosity for logs: info, debug, trace.
  level: '${LOG_LEVEL}'
```

and the output

```
authelia  | time="2024-07-25T10:52:54+02:00" level=error msg="Configuration: log: option 'level' must be one of 'trace', 'debug', 'info', 'warn', or 'error' but it's configured as 'infogggg'"
```
(notice our log level variable at play)

dudes/dudettes/goldfish you guys rock! thank you
