### DISCUSSION TITLE
Config file not rendered by templating system

### DISCUSSION THREAD

**Discussion by cellulosa** [authelia/authelia#7059] [Troubleshooting]
hi there, I can't get the templating system to render my env variables.

I'm running v4.38.7.

I have setup a docker-compose `test.yml` file with the following:

```yml
services:
  authelia:
    image: docker.io/authelia/authelia:latest
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - MY_DOMAIN=website.com
    volumes:
      - ./authelia/config/configuration.yml:/config/configuration.yml
```

this is `./config/configuration.yml`:

```yml
session:
  cookies:
    - domain: '{{ env "MY_DOMAIN" }}'
      authelia_url: 'https://auth.{{ env "MY_DOMAIN" }}'
      default_redirection_url: 'https://www.{{ env "MY_DOMAIN" }}'
```

When running `docker compose -f test.yml exec authelia authelia config template` I get:

```yml
---
##
## Authelia rendered configuration file (file filters).
##
## Filters: 
##

---
##
## File Source Path: /config/configuration.yml
##

session:
  cookies:
    - domain: '{{ env "MY_DOMAIN" }}'
      authelia_url: 'https://auth.{{ env "MY_DOMAIN" }}'
      default_redirection_url: 'https://www.{{ env "MY_DOMAIN" }}'
```

Any idea what could be happening? Or how to debug this?

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

It seems like the environment variables are not being replaced by their values in your configuration file when using the templating system. This issue might be related to the way you are using the `env` function in your template. According to the information provided in the sources, the correct way to use templating with environment variables in Authelia's configuration files involves a slightly different syntax.

Based on the example provided in the GitHub issue [#6993](https://github.com/authelia/authelia/issues/6993), the correct syntax to use for templating with environment variables should be `{{ mustEnv "MY_DOMAIN" }}` instead of `{{ env "MY_DOMAIN" }}`. The `mustEnv` function is used to ensure that the environment variable is defined, and it will replace the placeholder with the value of the environment variable.

Here's how you should adjust your `./config/configuration.yml`:

```yml
session:
  cookies:
    - domain: '{{ mustEnv "MY_DOMAIN" }}'
      authelia_url: 'https://auth.{{ mustEnv "MY_DOMAIN" }}'
      default_redirection_url: 'https://www.{{ mustEnv "MY_DOMAIN" }}'
```

Additionally, ensure that the `X_AUTHELIA_CONFIG_FILTERS` environment variable is set to `template` in your Docker Compose file, which you have already done. This tells Authelia to use the templating filter when processing the configuration file.

If after making these changes you still encounter issues, you can try the following steps to debug:

1. **Check Environment Variables**: Ensure that the environment variables are correctly passed to the Authelia container. You can do this by executing a command inside the container to print the environment variables, for example, `docker compose -f test.yml exec authelia printenv`.

2. **Review Authelia Logs**: Look into Authelia's logs for any errors or warnings related to configuration loading or templating. You can view the logs by running `docker compose -f test.yml logs authelia`.

3. **Check Authelia Version**: Ensure that you are using an Authelia version that supports the templating feature as expected. Although you mentioned using v4.38.7, double-check that the correct version is being pulled and used.

4. **Consult Documentation**: Review the [Authelia templating documentation](https://www.authelia.com/configuration/methods/files) and [GitHub discussions](https://github.com/authelia/authelia/issues/6993) for any updates or additional tips related to templating and environment variables.

If you've tried these steps and are still facing issues, consider reaching out to the Authelia community or support channels for further assistance.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
