### DISCUSSION TITLE
$$ Support Request - Athelia / LDAP configuration issues - need someone with knowledge to assist

### DISCUSSION THREAD

**Discussion by compumatter** [authelia/authelia#7069] [General]
I've been reconfiguring for hours and I have finally thrown in the towel, though I suspect we are getting close.

We have a Samba AD/DC backend and the goal is to use members of the group "backup" to be able to pass validation with Authelia and then view the website intended.

I end up with a variety of end results based on my configuration.yml but typically it's a white screen with one url loop or a white screen with many url loops.

I've created a video to make the problem, my ldap configs, my nginx configs and the results  / log more clear:

- https://youtu.be/RcTF49k1yfI

If anyone would like to do a zoom session and be paid for the assistance that would be ideal.  Alternatively, I have attached my configuration.yml file and vhosts file in case it is of value in the effort.

[configuration.yml-and-nginx-vhosts.zip](https://github.com/authelia/authelia/files/14846335/configuration.yml-and-nginx-vhosts.zip)

If there is a better place for me to visit to request support I am happy to go there directly of course.

Jay / Servermatter

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Based on the information provided and the context from the sources, it seems like you're encountering issues with integrating Authelia for authentication with a Samba AD/DC backend, resulting in a looping or white screen when attempting to access a protected website. This could be due to several factors, including misconfiguration in your `configuration.yml`, issues with LDAP settings, or problems with your NGINX setup.

Given the complexity of your issue and the fact that you've provided a video detailing your problem, it's clear that a more interactive form of support might be beneficial. While I can offer some general advice and points to check based on the information provided, it might indeed be more efficient to seek direct assistance, as you've suggested.

1. **Check LDAP Configuration**: Ensure that your LDAP configuration in `configuration.yml` correctly points to your Samba AD/DC, with the correct base DN, user DN, group DN, and filters for users and groups. Pay special attention to the `groups_filter` to ensure it's correctly set up to identify members of the "backup" group. The LDAP configuration examples provided in the Authelia documentation can serve as a reference.

2. **Review NGINX Configuration**: Ensure that your NGINX configuration correctly forwards authentication requests to Authelia and that the protected endpoints are correctly set up. Misconfiguration here could lead to redirection loops or access issues.

3. **Debugging and Logs**: Review Authelia and NGINX logs for any errors or warnings that could indicate where the issue lies. Authelia's verbose logging can be particularly helpful in identifying authentication or configuration issues.

4. **Community Support**: Given the complexity of your setup and the specific issues you're facing, engaging directly with the Authelia community might be the most effective way to get targeted help. The Authelia GitHub discussions (https://github.com/authelia/authelia/discussions) or the Authelia Discord server could be good places to seek assistance. You might find experts there who are willing to offer a Zoom session for direct support.

5. **Professional Support**: If your situation requires immediate resolution and you're open to paid support, consider reaching out to IT consultants or companies specializing in Samba AD/DC and Authelia integration. While the Authelia community might offer volunteer help, professional services can provide dedicated support tailored to your needs.

Remember to redact any sensitive information before sharing your configuration files or logs publicly or with support personnel.

Lastly, ensure that your Authelia version is up to date, as newer versions might have fixes or improvements that could resolve your issue.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment]
Hey @compumatter your authelia configuration needs to be updated to serve from a subpath. See the before and after example below:

```yaml
##
## Server Configuration
##
server:
  ## The address for the Main server to listen on in the address common syntax.
  ## Formats:
  ##  - [<scheme>://]<hostname>[:<port>][/<path>]
  ##  - [<scheme>://][hostname]:<port>[/<path>]
  ## Square brackets indicate optional portions of the format. Scheme must be 'tcp', 'tcp4', 'tcp6', or 'unix'.
  ## The default scheme is 'unix' if the address is an absolute path otherwise it's 'tcp'. The default port is '9091'.
  ## If the path is specified this configures the router to handle both the `/` path and the configured path.
  address: 'tcp://0.0.0.0:9091/'
```

```yaml
##
## Server Configuration
##
server:
  ## The address for the Main server to listen on in the address common syntax.
  ## Formats:
  ##  - [<scheme>://]<hostname>[:<port>][/<path>]
  ##  - [<scheme>://][hostname]:<port>[/<path>]
  ## Square brackets indicate optional portions of the format. Scheme must be 'tcp', 'tcp4', 'tcp6', or 'unix'.
  ## The default scheme is 'unix' if the address is an absolute path otherwise it's 'tcp'. The default port is '9091'.
  ## If the path is specified this configures the router to handle both the `/` path and the configured path.
  address: 'tcp://0.0.0.0:9091/authelia'
```
