### DISCUSSION TITLE
Traefik timeouts since v4.38?

### DISCUSSION THREAD

**Discussion by RefineryX** [authelia/authelia#7085] [Q&A] [answered]
Wondered if anyone facing issues with Traefik + Authelia since upgrading to v4.38?

Periodically, especially after a restart, Traefik is unable to reach Authelia. Traefik logs show timeouts. However, if I restart traefik it works again.

``service.domain.com`` >> redirects to > ``auth.domain.com`` - timeouts.

Restarts Traefik - all working again.

**Edit:**
It appears that Authelia is getting the request...? Not sure what is going on here.

**Authelia logs:**
```
time="2024-04-04T19:24:03+01:00" level=info msg="Access to https://proxy.domain.com/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.domain.com/?rd=https%3A%2F%2Fproxy.domain.com%2F&rm=GET" method=GET path=/api/verify remote_ip=10.10.1.130
```

**Traefik logs**
```
time="2024-04-04T19:24:03+01:00" level=debug msg="Accepting IP 10.10.1.130" middlewareName=middleware-ipallowlist@file middlewareType=IPAllowLister
time="2024-04-04T19:24:03+01:00" level=debug msg="Remote error http://authelia:9091/api/verify?rd=https://auth.domain.com. StatusCode: 302" middlewareName=middleware-authelia@file middlewareType=ForwardedAuthType
time="2024-04-04T19:24:03+01:00" level=debug msg="Accepting IP 10.10.1.130" middlewareType=IPAllowLister middlewareName=middleware-ipallowlist@file
time="2024-04-04T19:24:33+01:00" level=debug msg="'504 Gateway Timeoutproxy' caused by: dial tcp 172.17.5.4:9091: i/o timeout"
```

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Based on the context provided, it seems you're encountering an issue that might be related to the startup sequence or network connectivity between Traefik and Authelia containers, especially after upgrading to Authelia v4.38.0. A similar issue was reported in the context where Authelia was unable to complete startup due to schema migration errors, although it was not directly related to network timeouts or connectivity issues with Traefik (source: https://github.com/authelia/authelia/issues/6859).

However, there are a few potential causes and solutions you might consider:

1. **Startup Dependency**: Ensure that Authelia is fully started and operational before Traefik attempts to connect to it. You can manage service dependencies in your `docker-compose.yml` to ensure the correct startup order.

2. **Network Configuration**: Verify that the network configuration allows Traefik to communicate with Authelia. Both services should be on the same Docker network, and there should be no IP conflicts or misconfigurations that could cause intermittent connectivity issues.

3. **Resource Constraints**: Check if there are any resource constraints on your Docker host that might cause Authelia to start slowly or become temporarily unresponsive, especially after a restart. Adjusting resource allocations might help.

4. **Version Compatibility**: Although not directly mentioned in the provided context, ensure that the versions of Traefik and Authelia you are using are compatible. You mentioned an upgrade to Authelia v4.38.0; verify that this version does not introduce any changes that affect its integration with Traefik.

5. **Logs and Debugging**: Review the logs for both Authelia and Traefik around the time the issue occurs. Authelia's debug logs (as seen in the context from https://github.com/authelia/authelia/discussions/5599) might provide more insight into what happens during the startup and when Traefik attempts to connect.

If the issue persists after checking these areas, consider reaching out to the Authelia community or support channels with detailed logs and configuration details for more targeted assistance.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment]
Fairly likely this is a docker network misconfiguration, show your docker compose?

**Reply by RefineryX** [reply]
Thanks - I've removed the other services and included just Authelia and Traefik.

```
networks:

  authelia-net:
    name: authelia-net
    internal: true

  traefik-net:
    name: traefik-net
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/24


services:

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: always
    networks:
      - authelia-net
      - redis-net
    depends_on:
      - redis
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/admin/docker/authelia:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=https
      - traefik.http.routers.authelia.rule=Host(`auth.domain.com`)
      - traefik.http.routers.authelia.middlewares=middleware-chain-defaults@file
      - traefik.http.services.authelia.loadbalancer.server.port=9091
  ## Additional Config
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    healthcheck:
      disable: true

  traefik:
    container_name: traefik
    image: traefik
    restart: always
    networks:
      - traefik-net
      - adguard-net
      - authelia-net
      - cloudflared-net
      - dozzle-net
      - duplicati-net
      - paperless-net
      - portainer-net
      - vpn-net
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - CF_API_EMAIL=[REMOVED]
      - CF_DNS_API_TOKEN=[REMOVED]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/admin/docker/traefik/traefik.yml:/traefik.yml:ro
      - /home/admin/docker/traefik/acme.json:/acme.json:rw
      - /home/admin/docker/traefik/rules.yml:/rules.yml:ro
      - /home/admin/docker/traefik/logs:/logs:rw
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`proxy.domain.com`)
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=domain.com
      - traefik.http.routers.traefik.tls.domains[0].sans=*.domain.com 
      ## Middlewares
      - traefik.http.routers.traefik.middlewares=middleware-chain-defaults@file,middleware-authelia@file
      ## Services - API
      - traefik.http.routers.traefik.service=api@internal
  ## Additional Config
    read_only: true
    user: 1000:995
    security_opt:
      - no-new-privileges:true
    extra_hosts:
      - host.docker.internal:172.20.0.1 # allows communication to containers in host_mode
```

Looking back at the original logs, it says ``'504 Gateway Timeoutproxy' caused by: dial tcp 172.17.5.4:9091:``. Which is part of the the ``redis-net``.

I also just found [this](https://community.traefik.io/t/gateway-504-error-with-services/14434) which states "you created 2 networks and the authelia container is assigned to both of them. Traefik, while forwarding, doesn't know which network to use." Looking back at my compose, looks like I've accidentally deleted ``traefik.docker.network=authelia-net`` during recent maintenance. My Bad.

This should hopefully fix the issues... knew something was going on as Traefik and Authelia have been SOLID for the past two years!! At this point, I am thinking they should just go in the same network.... 'proxy-net' or something?
