### DISCUSSION TITLE
TLS: client didn't provide a certificate

### DISCUSSION THREAD

**Discussion by xulinus** [authelia/authelia#7098] [Troubleshooting] [answered]
I am running Authelia with Treafik as a proxy. Authelia and Traefik is communicating by mTLS (self-issued certificates with Smallstep CA). 

In the Authelia logs I am getting an error that I can't figure out how to debug.

```
authelia | time="2024-04-05T22:32:23+02:00" level=debug msg="error when serving connection "\[::1\]:9091"&lt;-&gt;"\[::1\]:37522": tls: client didn't provide a certificate"
```

Since the address shown in the error message is localhost (::1) I'm assuming that  this is not an issue with the communication between Authelia and Traffic (which works fine btw). My guess is that it has something to do with the health check since the container is also reporting an unhealthy state.

I am running: Authelia untagged-v4.38.7 (v4.38.7, fd4cea4).

```
# part of configuration.yml
server:
  address: tcp://0.0.0.0:9091
  tls:
    key: "/certificates/authelia/key.key"
    certificate: "/certificates/authelia/cert.crt"
    client_certificates: ["/certificates/root_ca.crt"]
```

```
# authelia part of docker-compose.yml
  authelia:
    container_name: authelia
    depends_on:
      - redis
    image: authelia/authelia
    restart: always
    networks:
      - backend
      - proxy
    expose:
      - 9091
    volumes:
      - ./authelia/config:/config
      - ./authelia/secrets:/secrets
      - ./certs:/certificates
    environment:
      TZ: Europe/Stockholm
      #AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /secrets/POSTGRESDB_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/SMTP_PASSWORD
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/LDAP_PASSWORD
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /secrets/OIDC_HMAC
      #AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_CERTIFICATE_CHAIN_FILE: /secrets/OIDC_CERT_CHAIN
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /secrets/OIDC_PRIVATE_KEY
```

Any help on how I can make this error go away is appreciated.
