### DISCUSSION TITLE
Configuration: session: option 'cookies' must be configured with the per cookie option

### DISCUSSION THREAD

**Discussion by hardball2-0** [authelia/authelia#7113] [Q&A] [answered]
**Version** : [authelia/authelia:latest](https://hub.docker.com/layers/authelia/authelia/latest/images/sha256-0d5ac6e586c610f4d5bfebe0632a68cd0245397298555f2b5101c7ad31e143e7?context=explore)

**Deployment Method**
Docker

Reverse Proxy
Nginx proxy manager

**Description**
Getting the following errors in the log:

`level=error msg="Configuration: session: option 'cookies' must be configured with the per cookie option 'default_redirection_url' but the global one is configured which is not supported" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"`

In my config i have this :

```
session:
  secret: 'The secret '
  name: 'authelia_session'
  same_site: 'none'
  inactivity: '1h'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'mydomain.ovh'
      authelia_url: 'https://auth.mydomain.ovh'
```
      
 **Documentation** 
I have done the same but nothing change

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

The error message you're encountering indicates that the `default_redirection_url` option must be configured on a per-cookie basis within the `cookies` section of your configuration, and that a global configuration for this option is not supported. This means that for each cookie defined in the `cookies` array, you must specify a `default_redirection_url`. However, your provided configuration snippet does not include the `default_redirection_url` for the cookie.

To resolve this issue, you should add the `default_redirection_url` option within the `cookies` section of your configuration file, like so:

```yaml
session:
  secret: 'The secret'
  name: 'authelia_session'
  same_site: 'none'
  inactivity: '1h'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'mydomain.ovh'
      authelia_url: 'https://auth.mydomain.ovh'
      default_redirection_url: 'https://your.default.redirection.url'
```

Replace `https://your.default.redirection.url` with the URL where users should be redirected by default when they visit Authelia directly. This URL must be able to read and write cookies for the configured domain and use the HTTPS scheme.

This adjustment should address the error by ensuring that each cookie configuration includes a `default_redirection_url`, as required by Authelia's configuration validation process.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
