### DISCUSSION TITLE
Server Authz Endpoints invalid configuration example

### DISCUSSION THREAD

**Discussion by HannesJo0139** [authelia/authelia#7121] [Documentation Feedback]
On [https://www.authelia.com/configuration/miscellaneous/server-endpoints-authz/](https://www.authelia.com/configuration/miscellaneous/server-endpoints-authz/) the configuration example

```
server:
  endpoints:
    authz:
      ...     
      auth-request:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'HeaderAuthRequestAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
```

is invalid since `HeaderAuthRequestAuthorization` is no valid strategy name.

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

You are correct; the configuration example provided on the [Server Authz Endpoints](https://www.authelia.com/configuration/miscellaneous/server-endpoints-authz/) page of Authelia's documentation contains an error. The strategy name `HeaderAuthRequestAuthorization` is not valid according to the available documentation and resources. Based on the information provided in the context, the valid authentication strategy names include `CookieSession`, `HeaderAuthorization`, `HeaderProxyAuthorization`, and others, but `HeaderAuthRequestAuthorization` is not listed among them.

To correct the configuration, you should use a valid strategy name. If your intention is to use the authorization header for authentication, the correct strategy name would be `HeaderAuthorization`. Here is how the corrected configuration snippet should look:

```yaml
server:
  endpoints:
    authz:
      ...
      auth-request:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
```

This configuration uses `HeaderAuthorization` as the strategy for the `auth-request` endpoint, which is a valid and recognized strategy name according to the Authelia documentation.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
