### DISCUSSION TITLE
Authelia stop without errors

### DISCUSSION THREAD

**Discussion by Marc-Proux** [authelia/authelia#7179] [Q&A] [answered]
Hi, I'm new in authelia. I'm trying to deploy an authelia docker as an SSO on my server. But every time, the container exit without any error. In the logs, I've got some warnings but nothings that should made crash the conatiner.

My `configuration.yml`

```yaml
theme: dark
jwt_secret: "secrets"

server: 
  host: 0.0.0.0 # do not change this! 
  port: 9091 # do not change this, this is Authelia internal port 

log: 
  level: info 
  format: text 
  file_path: /var/log/authelia/authelia.log

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldap://openldap:389
    timeout: 5s
    start_tls: false
    base_dn: DC=arcadia-hub,DC=com
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: CN=admin,DC=arcadia-hub,DC=com
    password: "password"

session: 
  secret: 'insecure_session_secret' 
  name: 'authelia_session' 
  inactivity: '5m' 
  expiration: '1h' 
  remember_me: '1M' 
  cookies: 
    - domain: 'arcadia-hub.com' 
      authelia_url: 'https://auth.arcadia-hub.com' 
      default_redirection_url: 'https://www.arcadia-hub.com' 
      name: 'authelia_session' 
      inactivity: '5m' 
      expiration: '1h' 
      remember_me: '1d'

regulation: 
  max_retries: 5 
  find_time: 10m
  ban_time: 12h

storage: 
  encryption_key: "sql_secrets_key"
  local: 
    path: /config/db.sqlite

notifier: 
  filesystem: 
    filename: /config/notification.txt

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 
        - "auth.arcadia-hub.com"
      policy: bypass
    - domain:
        - "traefik.arcadia-hub.com"
      subject: 
        - "group:admins"
        - "group:dev"
      policy: one_factor
```

My `docker-compose.yml`

```yaml
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /app/authelia/config:/config
      - /app/authelia/config/configuration.yml:/config/configuration.yml
      - /app/authelia/log:/var/log/authelia
    networks:
      - arcadia_network
    ports:
      - "9091:9091"

networks:
  arcadia_network:
    name: arcadia_network
    driver: bridge
```

And the log :
```sh
time="2024-04-15T08:24:53Z" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-04-15T08:24:53Z" level=debug msg="Logging Initialized" fields.level=debug file=/var/log/authelia/authelia.log format=text keep_stdout=false
time="2024-04-15T08:24:53Z" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration key 'authentication_backend.ldap.display_name_attribute' is deprecated in 4.38.0 and has been replaced by 'authentication_backend.ldap.attributes.display_name': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration key 'session.remember_me_duration' is deprecated in 4.38.0 and has been replaced by 'session.remember_me': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration key 'authentication_backend.ldap.url' is deprecated in 4.38.0 and has been replaced by 'authentication_backend.ldap.address': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration key 'authentication_backend.ldap.mail_attribute' is deprecated in 4.38.0 and has been replaced by 'authentication_backend.ldap.attributes.mail': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration key 'authentication_backend.ldap.group_name_attribute' is deprecated in 4.38.0 and has been replaced by 'authentication_backend.ldap.attributes.group_name': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration key 'authentication_backend.ldap.username_attribute' is deprecated in 4.38.0 and has been replaced by 'authentication_backend.ldap.attributes.username': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2024-04-15T08:24:53Z" level=warning msg="Configuration: configuration keys 'server.host', 'server.port', and 'server.path' are deprecated in 4.38.0 and has been replaced by 'server.address' in the format of '[tcp[(4|6)]://]<hostname>[:<port>][/<path>]' or 'tcp[(4|6)://][hostname]:<port>[/<path>]': you are not required to make any changes as this has been automatically mapped for you to the value 'tcp://0.0.0.0:9091/', but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2024-04-15T08:24:53Z" level=info msg="Authelia v4.38.8 is starting"
time="2024-04-15T08:24:53Z" level=info msg="Log severity set to debug"
```

If someone have some idea why the container keep stopping
