### DISCUSSION TITLE
Grafana authelia integration, token_endpoint_auth_method problem

### DISCUSSION THREAD

**Discussion by Marc-Proux** [authelia/authelia#7203] [Q&A] [answered]
Hi,
I'm trying to integrate Authelia in Grafana but I have an issue with the token_endpoint_auth_method configuration.

The error generated in Authelia log:
```
The request was determined to be using 'token_endpoint_auth_method' method 'none', however the OAuth 2.0 client registration does not allow this method. The registered client with id 'grafana' is configured to only support 'token_endpoint_auth_method' method 'client_secret_basic'
```

Same in Grafana log:
```
level=error msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.token.exchange] failed to exchange code to token: oauth2: \"invalid_client\" \"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'none', however the OAuth 2.0 client registration does not allow this method.\""
```

My Authelia clients config:
```
- client_id: 'grafana'
        client_name: 'Grafana'
        client_secret: ....
        public: false
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://grafana.arcadia-hub.com/login/generic_oauth'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
```

I tried to remove the token_endpoint_auth_method line (in the doc they the default value is 'client_secret_basic' or change it to client_secret_post but the error always says that the value is none
