### DISCUSSION TITLE
Issues upgrading to Authelia 4.38 using SWAG in Unraid

### DISCUSSION THREAD

**Discussion by halexh** [authelia/authelia#7250] [Troubleshooting]
Before Authelia 4.38 I had SWAG working with it correctly for my frigate.domain.com webpage. I auto upgraded my authelia container to 4.38, but I had not updated my `configuration.yml` file, resulting in frigate.domain.com being inaccessible due to obvious config issues when authelia would start.

I have attempted to update my `configuration.yml` file in Authelia, as well as updating my `authelia-location.conf` and `authelia-server.conf` files in SWAG to the most recent versions. Starting up both containers, I am not met with any warnings or errors in either of their logs.

I have a few issues that I am not sure how to resolve.

The first has been the most difficult for me, and that is that any time I attempt to access frigate.domain.com the below is reported in the authelia log and I am met with an error 403 on the webpage, never seeing the authelia login screen. I am able to access the frigate container from its local IP just fine, since that isnt going through swag and authelia when I try an access it through frigate.domain.com.

```
time="2024-04-27T13:43:15-04:00" level=debug msg="Check authorization of subject username= groups= ip=[redacted - my WAN IP] and object https://frigate.domain.com/ (method GET)."
time="2024-04-27T13:43:15-04:00" level=info msg="Access to https://frigate.domain.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://domain.com/?rd=https%3A%2F%2Ffrigate.domain.com%2F&rm=GET" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=[redacted - my WAN IP] 
``` 
It seems like Authelia is being passed a anonymous user, but I never get to the Authelia login landing page when I go to frigate.domain.com, in order to attempt to login and try and access the webpage as a non-anonymous user.

Further, if I attempt to access Authelia locally via its Web UI, it produces the following error:
```
time="2024-04-27T15:46:54-04:00" level=error msg="Error occurred retrieving user session" error="unable to retrieve session cookie domain provider: no configured session cookie domain matches the url 'http://192.168.68.80:9091/api/state'" method=GET path=/api/state remote_ip=192.168.68.79 stack="github.com/authelia/authelia/v4/internal/handlers/handler_state.go:16  StateGET\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54      handleRouter.(*BridgeBuilder).Build.func5.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:65     SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:91     SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30     SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.0/router.go:441                        (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 handleRouter.LogRequest.func40\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:23  handleRouter.StripPath.func41.1\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38      RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.52.0/server.go:2374                     (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.52.0/workerpool.go:224                  (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.52.0/workerpool.go:196                  (*workerPool).getCh.func1\nruntime/asm_amd64.s:1695                                               goexit"
```
And the following page:

![image](https://github.com/authelia/authelia/assets/27832066/d73eb053-eb37-41c3-b88c-4ade05144ba1)

Edit: Second issue below is resolved.
~~The second issue is that if I dont set `ntp.disable_startup_check` to `true`, I am always met with the following:~~
```
time="2024-04-27T13:56:46-04:00" level=error msg="Error occurred running a startup check" error="the system clock is not synchronized accurately enough with the configured NTP server" provider=ntp stack="github.com/authelia/authelia/v4/internal/commands/root.go:139 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-04-27T13:56:46-04:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[ntp]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
```

~~And I am not really sure how to resolve this. If I set it  `ntp.disable_startup_check` to `false` in order to get the container to start, I can run `date` within it which clearly matches the host's date, which is the exact local time. I had these exact same settings enabled and working (presumably - there certainly wasnt a startup error like this before) before this 4.38 upgrade.~~

Below is my Authelia `configuration.yml`:
```
theme: 'dark'

server:
  address: 'tcp://:9091/authelia'

log:
  level: 'debug'

telemetry:
  metrics:
    enabled: false

totp:
  disable: false
  
webauthn:
  disable: false

identity_validation:
  reset_password:
    jwt_secret: '[redacted]'

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: true
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false

  file:
    path: '/config/users_database.yml'
    password:
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

  zxcvbn:
    enabled: false
    min_score: 3

privacy_policy:
  enabled: false
  require_user_acceptance: false
  policy_url: ''

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'domain.com'
      policy: 'one_factor'
    - domain: 'frigate.domain.com'
      policy: 'one_factor'

session:
  secret: '[redacted]'

  cookies:
     -
      name: 'authelia_session'
      domain: 'domain.com'
      authelia_url: 'https://domain.com'
      default_redirection_url: 'https://www.domain.com'
      same_site: 'lax'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'

  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'

regulation:
  max_retries: 5
  find_time: '2 minutes'
  ban_time: '12 hours'

storage:
  encryption_key: '[redacted]'

  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: false

  filesystem:
    filename: '/config/notification.txt'
...
```
