### DISCUSSION TITLE
Seems loop in infinite startup check

### DISCUSSION THREAD

**Discussion by maicss** [authelia/authelia#7277] [Q&A] [answered]
I am trying https://github.com/authelia/authelia/blob/master/examples/compose/lite/docker-compose.yml

```
# configuration.yml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  address: 'tcp://127.0.0.1:9091/'

log:
  level: 'debug'

totp:
  issuer: 'authelia.com'

identity_validation:
  reset_password:
    jwt_secret: 'a_very_important_secret'

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    # Rules applied to everyone
    - domain: 'whoami.maicssh.space'
      policy: 'bypass'
    - domain: 'traefik.maicssh.space'
      policy: 'one_factor'
    - domain: 'secure.maicssh.space'
      policy: 'two_factor'

session:
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: 'insecure_session_secret'

  cookies:
    - name: 'authelia_session'
      domain: 'maicssh.space'  # Should match whatever your root protected domain is
      authelia_url: 'https://auth.maicssh.space'
      expiration: '1 hour'
      inactivity: '5 minutes'

  # redis:
  #   host: 'redis'
  #   port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: 'you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this'
  local:
    path: '/config/db.sqlite3'

notifier:
  smtp:
    username: 'test'
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: 'password'
    address: 'smtp://mail.maicssh.space:25'
    sender: 'admin@maicssh.space'
```

```
# users_database.yml

```
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  authelia:
    disabled: false
    displayname: "Authelia User"
    # Password is authelia
    password: "$6$rounds=50000$BpLnfgDsc2WD8F2q$Zis.ixdg9s/UOJYrs56b5QEZFiZECu0qZVNsIYxBaNJ7ucIL.nlxVCT5tqh8KHG8X4tlwCFm5r6NTOZZ5qRFN/"  # yamllint disable-line rule:line-length
    email: authelia@authelia.com
    groups:
      - admins
      - dev
```
time="2024-05-06T17:27:58+08:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-05-06T17:27:58+08:00" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2024-05-06T17:27:58+08:00" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
time="2024-05-06T17:27:58+08:00" level=info msg="Authelia v4.38.8 is starting"
time="2024-05-06T17:27:58+08:00" level=info msg="Log severity set to debug"
time="2024-05-06T17:27:58+08:00" level=info msg="Storage schema is being checked for updates"
time="2024-05-06T17:27:58+08:00" level=info msg="Storage schema is already up to date"
time="2024-05-06T17:27:58+08:00" level=error msg="Error occurred running a startup check" error="failed to dial connection: dial tcp 49.75.104.99:25: connect: connection refused" provider=notification stack="github.com/authelia/authelia/v4/internal/commands/root.go:128 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-05-06T17:27:59+08:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-05-06T17:27:59+08:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-05-06T17:27:59+08:00" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2024-05-06T17:27:59+08:00" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
time="2024-05-06T17:27:59+08:00" level=info msg="Authelia v4.38.8 is starting"
time="2024-05-06T17:27:59+08:00" level=info msg="Log severity set to debug"
time="2024-05-06T17:27:59+08:00" level=info msg="Storage schema is being checked for updates"
time="2024-05-06T17:27:59+08:00" level=info msg="Storage schema is already up to date"
time="2024-05-06T17:27:59+08:00" level=error msg="Error occurred running a startup check" error="failed to dial connection: dial tcp 49.75.104.99:25: connect: connection refused" provider=notification stack="github.com/authelia/authelia/v4/internal/commands/root.go:128 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-05-06T17:27:59+08:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-05-06T17:28:00+08:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-05-06T17:28:00+08:00" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2024-05-06T17:28:00+08:00" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
time="2024-05-06T17:28:00+08:00" level=info msg="Authelia v4.38.8 is starting"
time="2024-05-06T17:28:00+08:00" level=info msg="Log severity set to debug"
time="2024-05-06T17:28:00+08:00" level=info msg="Storage schema is being checked for updates"
time="2024-05-06T17:28:00+08:00" level=info msg="Storage schema is already up to date"
time="2024-05-06T17:28:00+08:00" level=error msg="Error occurred running a startup check" error="failed to dial connection: dial tcp 49.75.104.99:25: connect: connection refused" provider=notification stack="github.com/authelia/authelia/v4/internal/commands/root.go:128 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-05-06T17:28:00+08:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-05-06T17:28:01+08:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
...
```
