### DISCUSSION TITLE
Emails not working

### DISCUSSION THREAD

**Discussion by nothing2obvi** [authelia/authelia#7300] [Q&A] [answered]
Hello, I didn't change anything in my Authelia setup but over the past few days I've noticed I'm not getting emails anymore. I'm using Gmail. Logging into Authelia I'm asked for a one-time password but I don't get an email. I even tried issuing a new app password for Gmail and using it in Authelia, but that didn't work.

This is my SMTP setup, which again, I haven't changed. My password is stored in a file.
```
  smtp:
    address: "smtp.gmail.com:587"
    timeout: "5 seconds"
    username: "email-here"
    sender: "email-here"
    subject: "[Authelia] {title}"
```

Nothing relevant in my logs:
```
05/12/2024
01:39:21 AM
level=
debug
method=
POST
msg=
Mark 1FA authentication attempt made by user 'username-here'
path=
/api/firstfactor
remote_ip=
ip-here
time=
2024-05-12T08:39:21Z
05/12/2024
01:39:21 AM
level=
debug
method=
POST
msg=
Successful 1FA authentication attempt made by user 'username-here'
path=
/api/firstfactor
remote_ip=
ip-here
time=
2024-05-12T08:39:21Z
```

I'd appreciate any help. Thank you!
