### DISCUSSION TITLE
Issue when loading secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources

### DISCUSSION THREAD

**Discussion by sarpuser** [authelia/authelia#7321] [Troubleshooting] [answered]
I cannot seem to load any secrets into the configuration file. I have all my secrets in `authelia/secrets` which is mapped to `/secrets/` in the container. This folder is owned by the authelia user and is mode 600. In my configuration file, I am using `encryption_key = '{{secret AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE}}'` in my conifguration files. I have also tried using `encryption_key = $AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE` and `encryption_key = AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE`. No matter what I try, I am getting an error saying "error loading secret into key 'session.secret': it's already defined in other configuration sources" in the logs. This happens for all the secrets I try to import. 

Here is my docker-compose.yml:
```yaml
---
networks:
  proxy:
    external: true
    name: 'proxy'

services:
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    user: '994:992'
    networks:
      - proxy
    expose:
      - 9091
    environment:
      AUTHELIA_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      AUTHELIA_DUO_API_INTEGRATION_KEY_FILE: '/secrets/DUO_API_INTEGRATION_KEY'
      AUTHELIA_DUO_API_SECRET_KEY_FILE: '/secrets/DUO_API_SECRET_KEY'
      TZ: 'America/New_York'
    volumes:
      - '/var/lib/authelia/config:/config'
      - '/var/lib/authelia/secrets:/secrets:ro'
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 5m
      timeout: 5s
```

Here are the logs:
```
time="2024-05-18T02:26:17-04:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-05-18T02:26:17-04:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format= keep_stdout=true
time="2024-05-18T02:26:17-04:00" level=debug msg="Process user information" gid=994 uid=994
time="2024-05-18T02:26:17-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2024-05-18T02:26:17-04:00" level=error msg="Configuration: secrets: error loading secret into key 'duo_api.integration_key': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:17-04:00" level=error msg="Configuration: secrets: error loading secret into key 'duo_api.secret_key': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:17-04:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:17-04:00" level=error msg="Configuration: secrets: error loading secret into key 'storage.encryption_key': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:17-04:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:23-04:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-05-18T02:26:23-04:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format= keep_stdout=true
time="2024-05-18T02:26:23-04:00" level=debug msg="Process user information" gid=994 uid=994
time="2024-05-18T02:26:23-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2024-05-18T02:26:23-04:00" level=error msg="Configuration: secrets: error loading secret into key 'duo_api.integration_key': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:23-04:00" level=error msg="Configuration: secrets: error loading secret into key 'duo_api.secret_key': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:23-04:00" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:23-04:00" level=error msg="Configuration: secrets: error loading secret into key 'storage.encryption_key': it's already defined in other configuration sources" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
time="2024-05-18T02:26:23-04:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1222                                         goexit"
```

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

The issue you're encountering where secrets are reported as "already defined in other configuration sources" typically indicates that the same configuration keys are being defined in multiple places within your Authelia configuration. This can happen if the secrets are set both in the environment variables and directly in the configuration files, or if there are duplicate entries within the configuration itself.

Here are a few steps to troubleshoot and resolve this issue:

1. **Check for Duplicate Entries in Configuration Files**: Ensure that the keys for secrets like `jwt_secret`, `session.secret`, `duo_api.integration_key`, `duo_api.secret_key`, and `storage.encryption_key` are not defined more than once across all your configuration files. This includes checking for deprecated keys that might be set alongside new ones.

2. **Environment Variables and Configuration Files**: Verify that you are not setting the same secrets both as environment variables and directly in the configuration files. If you are using environment variables to specify the path to the secret files (as you are doing), ensure these are not also hardcoded in any configuration files.

3. **Permissions and Ownership**: Although you mentioned that permissions and ownership are correctly set, it's good to double-check that the Authelia user has read access to the secrets directory and all files within it.

4. **Configuration Syntax**: Ensure that the syntax used in your configuration files is correct. For environment variables pointing to files, you should use the format `AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'` without additional curly braces or dollar signs which you mentioned trying (`{{secret AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE}}` and `$AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE`).

5. **Deprecated Configuration Keys**: As indicated by the logs, some keys like `jwt_secret` are deprecated. Make sure to update these to the new expected keys as per the latest Authelia documentation.

6. **Log Analysis**: Review the logs for any additional messages that might indicate where the configuration is being loaded from or if there are specific files causing the conflict.

If after these checks the issue persists, consider simplifying your configuration to the minimum necessary to run Authelia and incrementally add configurations to identify the problematic setting.

For more detailed guidance, you can refer to the Authelia documentation on secrets management and configuration:
- [Authelia Secrets Management](https://www.authelia.com/configuration/secrets/)
- [Authelia Configuration](https://www.authelia.com/configuration/)

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by sarpuser** [comment]
That AI is actually surprisingly very coherent... I changed all the instances of `{{secret AUTHELIA_..._FILE}}` to just `AUTHELIA_..._FILE` and it looks like I am still getting the defined elsewhere error. I am not sure where else it would be defined. The docker container only has access to these folders and in there there is a single configuration.yml. In that file there is also nowhere that it is defined, except for where it should be....

**Reply by james-d-elliott** [reply]
Show the contents of /var/lib/authelia/config/configuration.yml?

**Reply by james-d-elliott** [reply]
Actually the way you describe it you've configured it both in the secret env vars, and configured it in the configuration.yml, you can't do both.

**Reply by sarpuser** [reply]
I changed teh AUTHELIA_JWT_SECRET_FILE to AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE as suggested. 
```yaml
---
theme: "dark"


default_2fa_method: "mobile_push"


server:
  address: "tcp://:9091/"
  asset_path: "/config/assets/"


log:
  level: "debug"
  file_path: "/config/authelia.log"
  keep_stdout: true


telemetry:
  metrics:
    enabled: false
    address: "tcp://:9959/metrics"

    buffers:
      read: 4096
      write: 4096

    timeouts:
      read: "6 seconds"
      write: "6 seconds"
      idle: "30 seconds"

totp:
  disable: false
  algorithm: "SHA1"
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

  allowed_algorithms:
    - "SHA1"

  allowed_digits:
    - 6

  allowed_periods:
    - 30

  disable_reuse_security_policy: false


duo_api:
  disable: false
  hostname: "api.duosecurity.com"
  integration_key: AUTHELIA_DUO_API_INTEGRATION_KEY_FILE
  secret_key: AUTHELIA_DUO_API_SECRET_KEY_FILE
  enable_self_enrollment: false


identity_validation:
  reset_password:
    jwt_lifespan: "5 minutes"
    jwt_algorithm: "HS256"
    jwt_secret: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE

  elevated_session:
    code_lifespan: "5 minutes"
    elevation_lifespan: "10 minutes"
    characters: 8
    require_second_factor: true
    skip_second_factor: true


authentication_backend:
  password_reset:
    disable: false

  file:
    path: "/config/users_database.yml"
    watch: false
    password:
      algorithm: "argon2"
      argon2:
        variant: "argon2id"
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16


password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

  zxcvbn:
    enabled: false
    min_score: 3


privacy_policy:
  enabled: false
  require_user_acceptance: false
  policy_url: ""


access_control:
  default_policy: "deny"

  rules:
    - domain: "auth.mydomain.com"
      policy: "bypass"
    - domain: ["mydomain.com"]
      policy: "one_factor"
    - domain: ["portainer.mydomain.com", "nginx.mydomain.com"]
      policy: "two_factor"


session:
  secret: AUTHELIA_SESSION_SECRET_FILE

  cookies:
    - name: "authelia_session"
      domain: "mydomain.com"
      authelia_url: "https://auth.mydomain.com"
      default_redirection_url: "https://mydomain.com"
      inactivity: "5 minutes"
      expiration: "1 hour"
      remember_me: "1 month"


regulation:
  max_retries: 3
  find_time: "2 minutes"
  ban_time: "5 minutes"


storage:
  encryption_key: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE

  local:
    path: "/config/db.sqlite3"


notifier:
  disable_startup_check: false

  filesystem:
    filename: "/config/notification.txt"
```
