### DISCUSSION TITLE
How do you add a default policy to your user groups in Authelia?

### DISCUSSION THREAD

**Discussion by brettinternet** [authelia/authelia#7332] [Q&A] [answered]
I'm trying to setup OIDC with Minio, Authelia and I use Glauth as a backend. I have two groups assigned to a user `admins` and `people`. Currently, when I attempt to login through Minio OIDC, I get this error:

```
None of the given policies (`admins,people`) are defined, credentials will not be generated
```

In the [setup documentation](https://www.authelia.com/integration/openid-connect/minio/) it says, "Add a default policy to your user groups in Authelia". What does this mean? Is this something that needs to be done through Glauth groups or Authelia access_control?

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

The error message you're encountering suggests that there is a mismatch or an undefined policy for the groups `admins` and `people` within your Authelia configuration. When the documentation mentions adding a "default policy to your user groups in Authelia," it refers to defining access control rules within Authelia's configuration that specify how different groups (like `admins` and `people`) are handled during the authentication process.

This setup does not need to be done through Glauth groups directly but rather through Authelia's access control configuration. Here’s how you can address this:

1. **Define Access Control Rules in Authelia**: You need to specify what authentication policy applies to each group. This is done in the `access_control` section of the Authelia configuration file. For example:

   ```yaml
   access_control:
     rules:
       - domain: "example.com"
         resources:
           - "^/path/to/resource"
         subject: "group:admins"
         policy: two_factor
       - domain: "example.com"
         resources:
           - "^/path/to/another/resource"
         subject: "group:people"
         policy: one_factor
   ```

   In this example, members of the `admins` group are required to pass two-factor authentication, while members of the `people` group can access with one-factor authentication.

2. **Ensure Group Names Match**: Make sure that the group names defined in your Authelia rules match exactly with those coming from your identity provider (Glauth in your case). Any discrepancy in group names can lead to policies not being applied correctly, which seems to be the issue you are facing.

3. **Check the OIDC Configuration**: Ensure that your OIDC configuration in Minio is correctly set up to communicate with Authelia, and that Authelia is correctly receiving and processing the group claims from Glauth.

4. **Logging and Debugging**: Increase the logging level in Authelia to help identify what exactly is being received in the authentication requests and to confirm that the correct policies are being triggered.

By setting up the access control rules as described, you should be able to resolve the error regarding undefined policies for your user groups.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
