### DISCUSSION TITLE
Open ID Connect  Portainer Unauthorized

### DISCUSSION THREAD

**Discussion by sarpuser** [authelia/authelia#7333] [Troubleshooting] [answered]
Every time I try to log in using OAuth with Portainer, I get an error message saying Unauthorized. I have verified that the Client ID and secret is as is in the config. I have created an user in Portainer with the same name as the Authelia user. I have used `docker run -u "$(id -u):$(id -g)" -v "$(pwd)":/keys authelia/authelia:latest authelia crypto pair rsa generate --bits 4096 --directory /keys` to generate the key/certificate and pasted those values into the config file. What am I doing wrong?

Here is my oidc config:
```yaml
identity_providers:
  oidc:
    hmac_secret:
    jwks:
      - algorithm: 'RS256'
        key: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
        certificate_chain: |
          -----BEGIN CERTIFICATE-----
          -----END CERTIFICATE-----
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_jwt_access_token_stateless_introspection: false
    discovery_signed_response_alg: 'none'
    require_pushed_authorization_requests: false
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins:
        - 'https://"mydomain.com'
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'portainer'
        client_name: 'Portainer'
        client_secret: ''
        authorization_policy: "two_factor"
        redirect_uris:
          - 'https://portainer.mydomain.com'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
```

Here is the Portainer config:
<img width="1512" alt="Screenshot 2024-05-21 at 15 41 51" src="https://github.com/authelia/authelia/assets/23362324/d5fb25d2-21b3-4bad-8b69-1e662d21d57b">

Here is the Portainer error message:
<img width="1512" alt="Screenshot 2024-05-21 at 15 40 07" src="https://github.com/authelia/authelia/assets/23362324/b0a39a40-c895-4fc0-b15f-35d1564d5725">
