### DISCUSSION TITLE
Allow authelia to require 2fa verification for each distinct service.

### DISCUSSION THREAD

**Discussion by Crowley723** [authelia/authelia#7384] [Ideas]
I have app1.example.com and app2.example.com.

I use authelia to require two factors to access each app.

I think it would be a good idea to allow admins to require additional 2fa checks to access each distinct applications. 

Example:
I try to access app1. I get redirected to log in to authelia. I log in, using 1fa and 2fa, then get redirected to app1.

Later, I try to access app2, and it redirects to authelia and asks for my second factor again. 
(I still have access to app1 because the session didn't expire, but app2 has no active authenticated session) 

This would make it much more difficult for someone trying to impersonate someone else to leverage authelias sso to access all applications.
SSO requires one password and one 2fa per session.
A bad actor can phish someone's 2fa credential and use it before it expires.

Once the code they phished expires, they need a new one to access any other apps.

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Authelia currently supports Single Sign-On (SSO) which allows users to authenticate once and gain access to multiple applications without needing to re-authenticate. However, your requirement to enforce additional 2FA checks for each distinct application is not a default behavior in Authelia.

To achieve this, you would need to configure your access control policies to enforce 2FA for each application separately. This can be done by setting up specific rules for each application in the `access_control` section of your configuration file. Here is an example configuration:

```yaml
access_control:
  default_policy: deny
  rules:
    - domain: app1.example.com
      policy: two_factor
    - domain: app2.example.com
      policy: two_factor
```

This configuration ensures that both `app1.example.com` and `app2.example.com` require two-factor authentication. However, to enforce re-authentication for each application, you might need to adjust session management settings or implement custom logic to invalidate sessions for different applications.

For more detailed configuration options, you can refer to the [Access Control documentation](https://www.authelia.com/overview/authorization/access-control).

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment]
We can think about something like this. The issue is there is no clear defining attribute that distinguishes individual applications so people will whine no matter what we implement. If the session doesn't exist however the user will be required to completely authenticate again.

This can somewhat already be done but requires a complete reauthentication using a subdomain which represents a logical unit. You just need to configure authelia to handle requests for multiple domains.

For example:

```
session:
  cookies:
  - domain: app1.example.com
     authelia_url: https://auth.app1.example.com
  - domain: app2.example.com
     authelia_url: https://auth.app2.example.com
```
