### DISCUSSION TITLE
Hosting Authelia via Traefik on Docker, using a PathPrefix /authelia rather than a subdomain

### DISCUSSION THREAD

**Discussion by jamesfreeman959** [authelia/authelia#7385] [Q&A] [answered]
Hi all

I've been hunting for the last couple of days for a solution to this one, and come up blank so hoping someone on here either knows the answer, or can definitively tell me that what I'm trying to do isn't going to work!

I've had great success for the past few years running Authelia on Docker, and using Traefik in front of it to handle the redirection for authentication. That has always worked well, but I've always achieved this using a separate subdomain for authelia (let's say `authelia.example.com`).

I'm working on a different project now where the ideal solution is to have authelia available at `www.example.com/authelia`. I've been playing with numerous configurations in Traefik - I can successfully set up the Authelia container on the `/authelia` path, and the first web request goes absolutely fine. 

However when Authelia tries to load it's various components (CSS, JS, etc.) it is always referencing them from the root path - one specific example is that it tries to load:
```
https://www.example.com/static/js/index.txf8ESTP.js
```
When what I want it to do is to load:
```
https://www.example.com/authelia/static/js/index.txf8ESTP.js
```
I've tried various tricks to rewrite the URL and such, but all end up either breaking the initial request, or creating recursive loops.

Is there a way to tell Authelia that it's being hosted at a different path? Has anyone done this successfully, on Traefik or otherwise (happy to port solutions)? Happy to post code snippets etc., but there's been so many permutations I wanted to just start with the high level question and see if anyone could help.

Thanks in advance!

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

To host Authelia at a subpath like `www.example.com/authelia` using Traefik, you need to configure both Traefik and Authelia to be aware of the subpath. Unfortunately, Authelia does not natively support being hosted on a subpath out of the box, which is why you're encountering issues with static assets being referenced from the root path.

However, you can try the following workaround to achieve this:

1. **Traefik Configuration**:
   - Use Traefik's `PathPrefix` and `StripPrefix` middlewares to handle the subpath routing.

2. **Authelia Configuration**:
   - You will need to ensure that Authelia is aware of the subpath. This might involve modifying the base URL settings in Authelia's configuration if such an option is available.

Here is an example of how you might configure Traefik to handle the subpath:

```yaml
http:
  routers:
    authelia:
      rule: "PathPrefix(`/authelia`)"
      service: authelia
      middlewares:
        - authelia-strip

  middlewares:
    authelia-strip:
      stripPrefix:
        prefixes:
          - "/authelia"

  services:
    authelia:
      loadBalancer:
        servers:
          - url: "http://authelia:9091"
```

In this configuration:
- The `PathPrefix` rule ensures that requests to `/authelia` are routed to the Authelia service.
- The `stripPrefix` middleware removes the `/authelia` prefix before forwarding the request to Authelia.

3. **Authelia Configuration**:
   - If Authelia has a setting for a base URL or similar, set it to `/authelia`. This will ensure that Authelia generates URLs with the correct subpath.

If Authelia does not support setting a base URL, you might need to use a reverse proxy in front of Authelia to rewrite the URLs in the HTML content. This can be complex and may not be fully reliable.

Given the complexity and potential limitations, you might want to consider continuing to use a subdomain for Authelia if possible, as it is the more straightforward and supported configuration.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by jamesfreeman959** [comment, marked as answer]
I ended up answering my own question by reading the documentation more carefully - the answer was, in the configuration file, to set:

```
server:
  address: "tcp://:9091/authelia"
```

I'll leave this here in case it helps someone else!

**Reply by james-d-elliott** [reply]
Nice! Glad you figured it out (and yes this is correct).

**Comment by AndreiOsipov** [comment]
Hello, i tried it with nginx but I couldn't use it. Even i set address: "tcp://:9091/authelia" i have requests to https://www.example.com/static/js/index.txf8ESTP.js not https://www.example.com/authelia/static/js/index.txf8ESTP.js
Does anyone know how this works with nginx? Thanks!

**Reply by Crowley723** [reply]
I don't see any reason this wouldn't work with NGINX. In fact, SWAG (for the moment) uses the paths by default.

Perhaps you could share your nginx and authelia config?

**Reply by james-d-elliott** [reply]
Authelia dynamically detects the path when the subpath is configured. If a request is made to `/` then the path will be absent from resources, if it's made to `/authelia/` it will be present from resources.

**Reply by AndreiOsipov** [reply]
Sure. current nginx configuration is

```
worker_processes auto;
events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11;
    server_tokens off;
    charset utf-8; 
    
    
    server {
        listen 443 ssl;
        server_name datalens.radsciens.ru;
    
        include /config/nginx/snippets/ssl.conf;

        # Настраиваем Datalens с аутентификацией через Authelia
        location /datalens/ {
            auth_request /authelia/api/verify;
            auth_request_set $user $upstream_http_remote_user;
            proxy_pass http://datalens:8080/collections;
        }

        location /authelia/ {
            proxy_pass http://authelia:9091/authelia/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Uri /authelia/;
            proxy_set_header X-Forwarded-Prefix /authelia;
            rewrite ^/authelia(/.*)$ $1 break;
        }

        # Ensure static files are routed correctly
        location /authelia/static/ {
            proxy_pass http://authelia:9091/authelia/static/;
        }

    }
}
```
and my authelia config

```
server:
  address: 'tcp://0.0.0.0:9091/authelia'

log:
  level: debug

authentication_backend:
  file:
    path: /config/users.yml
  password_reset:
    disable: true

access_control:
  default_policy: deny
  rules:
    - domain: datalens.radscience.ru
      policy: one_factor

session:
  secret: '{{ env "AUTHELIA_SESSION_SECRET" }}'
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 5m


  cookies:
    - domain: 'datalens.radscience.ru'
      authelia_url: 'https://datalens.radscience.ru/authelia'
      default_redirection_url: 'https://datalens.radscience.ru/datalens'

      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notification.log
```
