### DISCUSSION TITLE
permission denied errors

### DISCUSSION THREAD

**Discussion by suikerchiller** [authelia/authelia#7393] [Troubleshooting] [answered]
Can't get the container up and running via docker compose while using secrets. Used the [following guide](https://www.smarthomebeginner.com/authelia-docker-compose-guide-2024/) as a starting point, see configs & log below. Secrets are owned by root:root and files chmod 600 located in default docker folder.

It looks like there are a couple of different things at play, how do I fix this? Thx!

**docker compose**
```
##### NETWORKS
networks:
  default:
    driver: bridge
  proxy:
    name: proxy
  socket:
    name: socket

##### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_api_email:
    file: $DOCKERDIR/secrets/cf_api_email
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key

##### SERVICES
include:
  # CORE
  - compose/socket-proxy.yml
  - compose/traefik.yml
  - compose/authelia.yml
  - compose/portainer.yml
```
**authelia.yml**
```
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38.8
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    networks:
      - proxy
      - default
    # ports:
    #   - "9091:9091"
    volumes:
      - $DOCKERDIR/appdata/authelia:/config
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
    secrets:
      - authelia_jwt_secret
      - authelia_storage_encryption_key
      - authelia_session_secret
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=websecure"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
```
**authelia/configuration.yml**
```
server:
  address: tcp://0.0.0.0:9091/
  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: true

totp:
  issuer: "example.com"
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 256 # blocks this much of the RAM

access_control:
  default_policy: deny
  rules:
    - domain:
        - "*.example.com"
        - "example.com"
      policy: two_factor

session:
  name: authelia_session
  same_site: lax
  expiration: 7h
  inactivity: 5m
  remember_me: 1M
  cookies:
   - domain: 'example.com'
      authelia_url: 'https://authelia.example.com'
      default_redirection_url: 'https://example.com'

regulation:
  max_retries: 3
  find_time: 300
  ban_time: 600

storage:
  # For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
  # This is good for the beginning. If you have a busy site then switch to other databases.
  local:
   path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  filesystem:
    filename: /config/notifications.txt
```

And here's an output of the log:
```
sudo docker compose -f docker-compose-c34.yml logs -tf --tail="50" authelia

authelia  | 2024-06-04T19:40:10.374883167Z time="2024-06-04T21:40:10+02:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled"
authelia  | 2024-06-04T19:40:10.374893285Z time="2024-06-04T21:40:10+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
authelia  | 2024-06-04T19:41:10.815021349Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: failed to load configuration from file path(/config/configuration.yml) source: yaml: line 63: did not find expected key"
authelia  | 2024-06-04T19:41:10.815035172Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_jwt_secret into key 'identity_validation.reset_password.jwt_secret': file permission error occurred: open /run/secrets/authelia_jwt_secret: permission denied"
authelia  | 2024-06-04T19:41:10.815037132Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_session_secret into key 'session.secret': file permission error occurred: open /run/secrets/authelia_session_secret: permission denied"
authelia  | 2024-06-04T19:41:10.815038833Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_storage_encryption_key into key 'storage.encryption_key': file permission error occurred: open /run/secrets/authelia_storage_encryption_key: permission denied"
authelia  | 2024-06-04T19:41:10.815040609Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
authelia  | 2024-06-04T19:41:10.815042186Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
authelia  | 2024-06-04T19:41:10.815043966Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: session: option 'cookies' is required"
authelia  | 2024-06-04T19:41:10.815045472Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"
authelia  | 2024-06-04T19:41:10.815053422Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: storage: option 'encryption_key' is required"
authelia  | 2024-06-04T19:41:10.815054965Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
authelia  | 2024-06-04T19:41:10.815056483Z time="2024-06-04T21:41:10+02:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled"
authelia  | 2024-06-04T19:41:10.815082459Z time="2024-06-04T21:41:10+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
authelia  | 2024-06-04T19:42:11.278467024Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: failed to load configuration from file path(/config/configuration.yml) source: yaml: line 63: did not find expected key"
authelia  | 2024-06-04T19:42:11.278485170Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_jwt_secret into key 'identity_validation.reset_password.jwt_secret': file permission error occurred: open /run/secrets/authelia_jwt_secret: permission denied"
authelia  | 2024-06-04T19:42:11.278487183Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_session_secret into key 'session.secret': file permission error occurred: open /run/secrets/authelia_session_secret: permission denied"
authelia  | 2024-06-04T19:42:11.278488867Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_storage_encryption_key into key 'storage.encryption_key': file permission error occurred: open /run/secrets/authelia_storage_encryption_key: permission denied"
authelia  | 2024-06-04T19:42:11.278490665Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
authelia  | 2024-06-04T19:42:11.278492409Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
authelia  | 2024-06-04T19:42:11.278494026Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: session: option 'cookies' is required"
authelia  | 2024-06-04T19:42:11.278495499Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"
authelia  | 2024-06-04T19:42:11.278499625Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: storage: option 'encryption_key' is required"
authelia  | 2024-06-04T19:42:11.278506670Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
authelia  | 2024-06-04T19:42:11.278508675Z time="2024-06-04T21:42:11+02:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled"
authelia  | 2024-06-04T19:42:11.278533842Z time="2024-06-04T21:42:11+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
authelia  | 2024-06-04T19:43:11.746478834Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: failed to load configuration from file path(/config/configuration.yml) source: yaml: line 63: did not find expected key"
authelia  | 2024-06-04T19:43:11.746494326Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_jwt_secret into key 'identity_validation.reset_password.jwt_secret': file permission error occurred: open /run/secrets/authelia_jwt_secret: permission denied"
authelia  | 2024-06-04T19:43:11.746496200Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_session_secret into key 'session.secret': file permission error occurred: open /run/secrets/authelia_session_secret: permission denied"
authelia  | 2024-06-04T19:43:11.746498105Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_storage_encryption_key into key 'storage.encryption_key': file permission error occurred: open /run/secrets/authelia_storage_encryption_key: permission denied"
authelia  | 2024-06-04T19:43:11.746500872Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
authelia  | 2024-06-04T19:43:11.746503150Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
authelia  | 2024-06-04T19:43:11.746505380Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: session: option 'cookies' is required"
authelia  | 2024-06-04T19:43:11.746507514Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"
authelia  | 2024-06-04T19:43:11.746509671Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: storage: option 'encryption_key' is required"
authelia  | 2024-06-04T19:43:11.746511911Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
authelia  | 2024-06-04T19:43:11.746577146Z time="2024-06-04T21:43:11+02:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled"
authelia  | 2024-06-04T19:43:11.746592223Z time="2024-06-04T21:43:11+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
authelia  | 2024-06-04T19:44:12.215484358Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: failed to load configuration from file path(/config/configuration.yml) source: yaml: line 63: did not find expected key"
authelia  | 2024-06-04T19:44:12.215498788Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_jwt_secret into key 'identity_validation.reset_password.jwt_secret': file permission error occurred: open /run/secrets/authelia_jwt_secret: permission denied"
authelia  | 2024-06-04T19:44:12.215501141Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_session_secret into key 'session.secret': file permission error occurred: open /run/secrets/authelia_session_secret: permission denied"
authelia  | 2024-06-04T19:44:12.215503211Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: secrets: error loading secret path /run/secrets/authelia_storage_encryption_key into key 'storage.encryption_key': file permission error occurred: open /run/secrets/authelia_storage_encryption_key: permission denied"
authelia  | 2024-06-04T19:44:12.215505259Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
authelia  | 2024-06-04T19:44:12.215507146Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
authelia  | 2024-06-04T19:44:12.215508982Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: session: option 'cookies' is required"
authelia  | 2024-06-04T19:44:12.215510733Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"
authelia  | 2024-06-04T19:44:12.215512543Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: storage: option 'encryption_key' is required"
authelia  | 2024-06-04T19:44:12.215515238Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
authelia  | 2024-06-04T19:44:12.215517155Z time="2024-06-04T21:44:12+02:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled"
authelia  | 2024-06-04T19:44:12.215561537Z time="2024-06-04T21:44:12+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
```
