### DISCUSSION TITLE
Using Basic Authentication with the new authorization endpoints

### DISCUSSION THREAD

**Discussion by ivanov17** [authelia/authelia#7400] [Q&A] [answered]
Hello community!

I want to switch to the [new configuration that version 4.38 introduced](https://www.authelia.com/blog/4.38-release-notes/#customizable-authorization-endpoints). I'm using Haproxy as a reverse proxy backend and I should switch to [ForwardAuth](https://www.authelia.com/reference/guides/proxy-authorization/#forwardauth) implementation and use `/api/authz/forward-auth` endpoint instead of `/api/verify`.

I'm also currently using Authelia to provide Basic Authentication for WebDAV/CalDAV services. To do this I use `/api/verify` endpoint with the `auth=basic` query parameter.

Unfortunately, I didn't find anything in the Authelia documentation about using Basic Authentication with the new authorization endpoints. Does this work for new endpoints?

It seems I should to use [HeaderAuthorization](https://www.authelia.com/reference/guides/proxy-authorization/#headerauthorization) strategy here, but I'm not sure if Basic Authentication will work. If anyone has a workable solution to use Basic Authentication along with 2FA, please share your configuration.

Thank you.

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Hello!

Yes, you can use Basic Authentication with the new authorization endpoints introduced in version 4.38. For your use case with HAProxy and WebDAV/CalDAV services, you should indeed use the `ForwardAuth` implementation and the `/api/authz/forward-auth` endpoint.

To enable Basic Authentication, you should use the `HeaderAuthorization` strategy. Here is a basic example of how you can configure this:

1. **Authelia Configuration**:
   Update your Authelia configuration to use the `ForwardAuth` implementation with the `HeaderAuthorization` strategy.

   ```yaml
   server:
     address: 0.0.0.0:9091
     endpoints:
       authz:
         forward-auth:
           implementation: 'ForwardAuth'
           authn_strategies:
             - name: 'HeaderAuthorization'
               schemes:
                 - 'Basic'
             - name: 'CookieSession'
   ```

2. **HAProxy Configuration**:
   Configure HAProxy to use the new endpoint and pass the necessary headers.

   ```haproxy
   frontend http-in
       bind *:80
       acl AuthNeeded path_beg /webdav /caldav
       http-request set-header X-Forwarded-Proto https if { ssl_fc }
       http-request set-header X-Forwarded-Host %[req.hdr(host)]
       http-request set-header X-Forwarded-URI %[path] if AuthNeeded
       http-request set-header X-Forwarded-For %[src]
       http-request set-header Authorization %[req.hdr(Authorization)] if AuthNeeded
       http-request set-header Proxy-Authorization %[req.hdr(Proxy-Authorization)] if AuthNeeded
       http-request set-header Remote-User %[req.hdr(Remote-User)] if AuthNeeded
       http-request set-header Remote-Groups %[req.hdr(Remote-Groups)] if AuthNeeded
       http-request set-header Remote-Name %[req.hdr(Remote-Name)] if AuthNeeded
       http-request set-header Remote-Email %[req.hdr(Remote-Email)] if AuthNeeded
       http-request auth realm Authelia if AuthNeeded
       http-request deny if !{ http_auth(AuthNeeded) }
       use_backend webdav-backend if AuthNeeded

   backend webdav-backend
       server webdav1 192.168.1.10:80
   ```

3. **Basic Authentication with 2FA**:
   Ensure that your Authelia policy is configured to require 2FA for the resources you want to protect.

   ```yaml
   access_control:
     default_policy: deny
     rules:
       - domain: "*.example.com"
         resources:
           - "^/webdav.*"
           - "^/caldav.*"
         policy: two_factor
   ```

By following these steps, you should be able to use Basic Authentication along with 2FA for your WebDAV/CalDAV services using the new `ForwardAuth` endpoint.

For more detailed information, you can refer to the [Authelia 4.38 release notes](https://www.authelia.com/blog/4.38-release-notes/#customizable-authorization-endpoints) and the [Proxy Authorization guide](https://www.authelia.com/reference/guides/proxy-authorization/#forwardauth).

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
