### DISCUSSION TITLE
Basic auth example produces 404 on /api/authz/auth-request/basic

### DISCUSSION THREAD

**Discussion by cyberb** [authelia/authelia#7417] [Q&A] [answered]
I am trying to follow this Nginx Basic Auth example: https://www.authelia.com/integration/proxies/nginx

authelia-location-basic.conf mentions this url:
```
set $upstream_authelia http://authelia:9091/api/authz/auth-request/basic;
```

My config:
```
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
      ext-authz:
        implementation: 'ExtAuthz'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
      auth-request:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'HeaderAuthRequestProxyAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'

```

But when I try to use it I get 404 from authelia:

```
Replied (status=404)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/api/authz/auth-request/basic
```

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

It looks like you're encountering a 404 error because the endpoint `/api/authz/auth-request/basic` does not exist in your current Authelia configuration. The `auth-request` endpoint in your configuration does not include a sub-path for `basic`.

To resolve this issue, you should adjust your Nginx configuration to use the correct endpoint that matches your Authelia configuration. Based on your provided configuration, you should use the `/api/authz/auth-request` endpoint without the `/basic` sub-path.

Here is the corrected Nginx configuration snippet:

```nginx
set $upstream_authelia http://authelia:9091/api/authz/auth-request;

location /internal/authelia/authz {
    internal;
    proxy_pass $upstream_authelia;

    ## Headers
    proxy_set_header X-Original-Method $request_method;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Content-Length "";
    proxy_set_header Connection "";

    ## Basic Proxy Configuration
    proxy_pass_request_body off;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    proxy_redirect http:// $scheme://;
    proxy_http_version 1.1;
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;
    client_body_buffer_size 128k;

    ## Advanced Proxy Configuration
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
```

Make sure to update your Nginx configuration to match the correct endpoint as defined in your Authelia configuration.

For more details, you can refer to the official documentation:
- [Authelia Nginx Integration](https://www.authelia.com/integration/proxies/nginx)

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by cyberb** [comment]
doc is wrong for authelia-location-basic.conf then?

**Comment by james-d-elliott** [comment, marked as answer]
You're missing the endpoint you need to configure in the preamble of [authelia-location-basic.conf](https://www.authelia.com/integration/proxies/nginx/#authelia-location-basicconf)

**Comment by cyberb** [comment]
you mean this?
`Note: This example assumes you configured an authz endpoint with the name auth-request/basic and the implementation AuthRequest which contains the HeaderAuthorization and HeaderProxyAuthorization strategies.`

even after adding:
```
  auth-request:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'HeaderProxyAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
```
it said 404 on `/api/authz/auth-request/basic` but when I changed it to `/api/authz/auth-request` it started to work, I still think doc not clear about `.../basic` endpoint

**Reply by james-d-elliott** [reply]
That's operating correctly and per the docs. You only configured `auth-request`, not `auth-request/basic`. If it's not registered the 404 is the correct response code.

**Comment by cyberb** [comment]
Ah these are literally freeform endpoints, i can define like
```
  auth-request:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'CookieSession'
  auth-request/basic:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'HeaderProxyAuthorization'
            schemes:
              - 'Basic'
```
