### DISCUSSION TITLE
authelia and cloudflare, origin rules etc.

### DISCUSSION THREAD

**Discussion by crosscutsaw** [authelia/authelia#7433] [Q&A] [answered]
hello,

i reached dead end. google is not working for my issue. so i'd like to get help from you.

**structure**
fs.zurrak.com >>> filebrowser application. it's running on :666 so i assigned an origin rule for it.
![image](https://github.com/authelia/authelia/assets/73831924/6848f612-25b2-45d3-8577-0f98dc831d6d)

au.zurrak.com >>> authelia. it's running on :777 so i assigned an origin rule for it.
![image](https://github.com/authelia/authelia/assets/73831924/87cff468-cefc-4b8e-a394-88c15aa97ae9)

**what i want to do?**
i want to protect fs.zurrak.com with authelia. only authenticated authelia users can be redirected to fs.zurrak.com.

**configuration.yml**
```
server:
  address: tcp://0.0.0.0:777/
  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info
  format: text
  file_path: /opt/authelia/authelia.log
  keep_stdout: true

totp:
  disable: false
  issuer: 'zurrak.com'
  algorithm: 'sha1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  allowed_algorithms:
    - 'SHA1'
  allowed_digits:
    - 6
  allowed_periods:
    - 30
  disable_reuse_security_policy: false

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m
  file:
    path: /opt/authelia/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 256 # blocks this much of the RAM

access_control:
  default_policy: deny
  rules:
    - domain:
        - "fs.zurrak.com"
      policy: two_factor

session:
  name: authelia_session
  same_site: lax
  expiration: 7h
  inactivity: 5m
  remember_me: 1M
  cookies:
    - domain: 'zurrak.com'
      authelia_url: 'https://au.zurrak.com'
      default_redirection_url: 'https://fs.zurrak.com'

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: 'a_very_important_secret'
  local:
   path: /opt/authelia/db.sqlite3

#smtp
notifier:
  smtp:
    username: 'redacted@zurrak.com'
    # Password can also be set using a secret: https://www.authelia.com/configuration/methods/secrets/
    password: 'redacted'
    sender: 'redacted@zurrak.com'
    host: 'mail.zurrak.com'
    port: 587
```

thank you in advance

**Comment by glime-ai** [comment, marked as answer]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

To protect `fs.zurrak.com` with Authelia, you need to configure your reverse proxy (e.g., NGINX, Traefik, Caddy) to forward authentication requests to Authelia. Below is an example configuration for NGINX, which you can adapt to your setup.

### NGINX Configuration

1. **Create the necessary configuration snippets:**

   - `authelia-authrequest.conf`:
     ```nginx
     auth_request /authelia;
     error_page 401 =302 https://au.zurrak.com/?rd=$request_uri;
     auth_request_set $user $upstream_http_remote_user;
     auth_request_set $email $upstream_http_remote_email;
     auth_request_set $groups $upstream_http_remote_groups;
     proxy_set_header Remote-User $user;
     proxy_set_header Remote-Email $email;
     proxy_set_header Remote-Groups $groups;
     ```

   - `authelia-location.conf`:
     ```nginx
     location /authelia {
         internal;
         proxy_pass http://authelia:777/api/verify;
         proxy_set_header Host $host;
         proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header Content-Length "";
         proxy_pass_request_body off;
     }
     ```

2. **Configure your NGINX server block for `fs.zurrak.com`:**

   ```nginx
   server {
       listen 80;
       server_name fs.zurrak.com;

       include /path/to/authelia-authrequest.conf;

       location / {
           include /path/to/authelia-location.conf;
           proxy_pass http://filebrowser:666;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;
       }
   }
   ```

### Authelia Configuration

Your `configuration.yml` seems mostly correct. Ensure the following settings are properly configured:

- **Access Control Rules:**
  ```yaml
  access_control:
    default_policy: deny
    rules:
      - domain:
          - "fs.zurrak.com"
        policy: two_factor
  ```

- **Session Configuration:**
  ```yaml
  session:
    name: authelia_session
    same_site: lax
    expiration: 7h
    inactivity: 5m
    remember_me: 1M
    domain: 'zurrak.com'
    authelia_url: 'https://au.zurrak.com'
    default_redirection_url: 'https://fs.zurrak.com'
  ```

### Final Steps

1. **Restart NGINX** to apply the new configuration:
   ```sh
   sudo systemctl restart nginx
   ```

2. **Ensure Authelia is running** and accessible at `https://au.zurrak.com`.

3. **Test the setup** by accessing `https://fs.zurrak.com` and verifying that it redirects to Authelia for authentication.

If you encounter any issues, please provide specific error messages or logs for further assistance.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
