### DISCUSSION TITLE
Different domain for auth and for application?

### DISCUSSION THREAD

**Discussion by TheZoker** [authelia/authelia#7439] [Q&A] [answered]
Hi there,

Let's say I have two applications reachable via `app.domain.dev` and `app.domain.com`, which I want to protect via authelia.

Authelia itself is available from `auth.domain.com`.

When now configure my setup, I have this session block:
```yaml
session:
  name: authelia_session
  same_site: lax
  secret: xxx
  cookies:
    - domain: 'domain.com'
      authelia_url: 'https://auth.domain.com'
      default_redirection_url: 'https://domain.com'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'
    - domain: 'domain.dev'
      authelia_url: 'https://auth.domain.com'
      default_redirection_url: 'https://domain.dev'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'
  expiration: 1h
  inactivity: 5m
  remember_me: 1M
  redis:
    host: Redis
    port: 6379

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'auth.domain.com'
      policy: bypass
    - domain: 'app.domain.com'
      policy: one_factor
    - domain: 'app.domain.dev'
      policy: two_factor
```

Now I get this error in the logs:
```
Configuration: session: domain config #2 (domain 'domain.dev'): option 'authelia_url' does not share a cookie scope with domain 'domain.dev' with a value of 'https://auth.domain.com'
```

How can I solve this issue? Thanks!

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

The error you're encountering is due to the fact that the `authelia_url` for `domain.dev` does not share a cookie scope with `domain.dev`. In other words, the `authelia_url` must be within the same domain or a parent domain of the domain it is protecting.

To resolve this issue, you need to ensure that the `authelia_url` for `domain.dev` is within the same domain scope. Here is an updated configuration that should work:

```yaml
session:
  name: authelia_session
  same_site: lax
  secret: xxx
  cookies:
    - domain: 'domain.com'
      authelia_url: 'https://auth.domain.com'
      default_redirection_url: 'https://domain.com'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'
    - domain: 'domain.dev'
      authelia_url: 'https://auth.domain.dev'
      default_redirection_url: 'https://domain.dev'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'
  expiration: 1h
  inactivity: 5m
  remember_me: 1M
  redis:
    host: Redis
    port: 6379

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'auth.domain.com'
      policy: bypass
    - domain: 'app.domain.com'
      policy: one_factor
    - domain: 'app.domain.dev'
      policy: two_factor
```

In this updated configuration, the `authelia_url` for `domain.dev` is set to `https://auth.domain.dev`, which shares the same domain scope as `domain.dev`.

For more detailed information, you can refer to the session configuration documentation:
- [Session Configuration](https://www.authelia.com/configuration/session/introduction)

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
