### DISCUSSION TITLE
Users getting disconnected from Authelia with a valid cookie

### DISCUSSION THREAD

**Discussion by orakless** [authelia/authelia#7454] [Troubleshooting]
Hi,
We are using Authelia for the deployment of one of our apps. It's still in an alpha state and is only gathering a few users at the same time.
We have a session problem when using the app: sometimes, Authelia revokes the user's session even if the cookie is still valid. We still haven't pin-pointed why it does that, we can stay connected for 40 minutes or for 2 minutes before getting kicked out of the service.

We are using the default session backend, with SQLite3 storage and YaML file user database. We are also using Caddy as our web server and reverse proxy.

Our architectures uses three sites:
- auth.example.com, which is Authelia's domain
- app.example.com, which is our app's API
- client.example.com, which is our web client

Both our API and web client are protected and needs 1-factor authentication.

Our Caddyfile
```
# Trusted proxies
(trusted_proxy_list) {
	trusted_proxies <list of ips>
}

# CORS short-hand
(cors) {
	header Access-Control-Allow-Origin "{args.0}"
	header Access-Control-Allow-Methods "GET, POST, OPTIONS"
}

# Authelia
auth.example.com {
	import cors https://client.example.com
	reverse_proxy host.docker.internal:9091 {
		import trusted_proxy_list
	}
}

# App's API 
app.example.com {
	forward_auth host.docker.internal:9091 {
                uri /api/authz/forward-auth
                copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
                import trusted_proxy_list
        }
	reverse_proxy <api_address>:<port> {
		import trusted_proxy_list
	}
}

# Web client
client.example.com {
	forward_auth host.docker.internal:9091 {	
		uri /api/authz/forward-auth
    }
	header /config/* {
		Cache-Control "no-cache, no-store, must-revalidate"
    }
    root * /srv
    try_files {path} /
    file_server browse
}
```

Authelia's configuration.yml
```yml
server:
  asset_path: '/config/assets/'
  address: 'tcp://:9091/'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
  
log:
  level: 'debug'

identity_validation:
  reset_password:
    jwt_secret: 'SECRET'

authentication_backend:
  refresh_interval: '20s'
  password_reset:
    disable: false
  file:
    path: '/etc/authelia/database/users.yml'
    watch: true    

session:
  secret: 'SECRET'
  cookies:
  - domain: 'example.com'
    authelia_url: 'https://auth.example.com/'
    default_redirection_url: 'https://client.example/'

storage:
  encryption_key: 'SECRET'
  local:
    path: '/etc/authelia/database/db.sqlite3'

access_control:
  default_policy: deny
  rules:
  - domain: 'app.example.com'
    policy: 'one_factor'
  - domain: 'client.example.com'
    policy: 'one_factor'
notifier:
  smtp:
    address: 'provider.com'
    username: 'person@example.com'
    password: 'SECRET'
    sender: "Person <person@example.com>"
    subject: "[App] {title}"
```

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

It seems like the issue might be related to the session configuration or the storage backend. Here are a few suggestions to help troubleshoot and potentially resolve the issue:

1. **Session Configuration**:
   - Ensure that the session expiration and inactivity settings are properly configured. For example, you might want to explicitly set the `expiration` and `inactivity` values in the session configuration.
   - Example:
     ```yaml
     session:
       secret: 'SECRET'
       name: 'authelia_session'
       domain: 'example.com'
       same_site: 'lax'
       inactivity: '5m'
       expiration: '1h'
       remember_me: '1M'
       cookies:
       - domain: 'example.com'
         authelia_url: 'https://auth.example.com/'
         default_redirection_url: 'https://client.example/'
     ```

2. **Storage Backend**:
   - SQLite3 is not recommended for high availability or production environments due to its limitations. Consider switching to a more robust storage backend like PostgreSQL or MySQL.
   - Example configuration for PostgreSQL:
     ```yaml
     storage:
       encryption_key: 'SECRET'
       postgres:
         host: 'db.example.com'
         port: 5432
         database: 'authelia'
         username: 'authelia_user'
         password: 'SECRET'
     ```

3. **Session Provider**:
   - Ensure that the session provider is not using memory storage, as it is not suitable for production environments. Redis is recommended for session storage.
   - Example configuration for Redis:
     ```yaml
     session:
       secret: 'SECRET'
       name: 'authelia_session'
       domain: 'example.com'
       same_site: 'lax'
       inactivity: '5m'
       expiration: '1h'
       remember_me: '1M'
       provider:
         redis:
           host: 'redis.example.com'
           port: 6379
           database_index: 0
           password: 'SECRET'
     ```

4. **Caddy Configuration**:
   - Ensure that the Caddy configuration is correctly set up to handle the forward authentication and reverse proxy settings. Double-check the `forward_auth` and `reverse_proxy` directives.

5. **Logs and Debugging**:
   - Check the Authelia logs for any errors or warnings that might indicate why the sessions are being revoked. The log level is already set to `debug`, which should provide detailed information.

If the issue persists after making these changes, please provide more details about the specific errors or logs you are seeing, and we can further investigate the problem.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
