### DISCUSSION TITLE
Login issue

### DISCUSSION THREAD

**Discussion by dabaobbb** [authelia/authelia#7462] [Q&A] [answered]
After I log in , nothing happened,I still in login page.
![image](https://github.com/authelia/authelia/assets/38378099/7b64d14e-d64a-44f2-8685-a5515de31629)

log showed this:
![image](https://github.com/authelia/authelia/assets/38378099/29939645-4d73-4d5d-917e-3b2e8e8a971f)
it showed successful 

this is my config 

##
##
## This configuration tunes the identity validation flows.
#
#
#
#
##
log:
  ## Level of verbosity for logs: info, debug, trace.
  level: 'trace'

identity_validation:
  reset_password:
    jwt_secret: "df797b7cd35f0e4c67d6df2a9ac236a7fa630c121cdc3ac970132dac99da12b7"

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'authelia.local.com'
      policy: 'one_factor'

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 3
  max_desync: '3s'
  disable_startup_check: true
  disable_failure: true

storage:
        ##
  ## PostgreSQL (Storage Provider)
  ##
  postgres:
    ## The address of the PostgreSQL server to connect to in the address common syntax.
    ## Format: [<scheme>://]<hostname>[:<port>].
    ## Square brackets indicate optional portions of the format. Scheme must be 'tcp', 'tcp4', 'tcp6', or 'unix`.
    ## The default scheme is 'unix' if the address is an absolute path otherwise it's 'tcp'. The default port is '5432'.
    address: 'tcp://192.168.1.3:5432'

    ## The database name to use.
    database: 'authelia'

    ## The schema name to use.
    schema: 'public'

    ## The username used for SQL authentication.
    username: 'authelia'

    ## The password used for SQL authentication.
     ## The password used for SQL authentication.
    ## Can also be set using a secret: https://www.authelia.com/c/secrets
    password: 'authelia'

    ## The connection timeout in the duration common syntax.
    # timeout: '5 seconds'

    ## PostgreSQL TLS settings. Configuring this requires TLS.
    # tls:
      ## The server subject name to check the servers certificate against during the validation process.
      ## This option is not required if the certificate has a SAN which matches the address options hostname.
      # server_name: 'postgres.example.com'
      #
      #
      #
      #
authentication_backend:
  file:
    path: /config/users_database.yml

    watch: false
    search:
      email: true #this is what allows users to login using their email
      case_insensitive: false

    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

# cookies:
  #   -
      ## The name of the session cookie.
      # name: 'authelia_session'

      ## The domain to protect.
      ## Note: the Authelia portal must also be in that domain.
      # domain: 'example.com'
session:
                cookies:

      ## The name of the session cookie.
      # name: 'authelia_session'

      ## The domain to protect.
      ## Note: the Authelia portal must also be in that domain.
    - domain: 'authelia.local.com'
      authelia_url: https://authelia.local.com
      # default_redirection_url: https://192.168.1.3:9091
   ## Cookie Session Domain default 'name' value.
  name: 'authelia_session'

  ## Cookie Session Domain default 'same_site' value.
  same_site: 'lax'

  ## Cookie Session Domain default 'inactivity' value.
  inactivity: '5m'

  ## Cookie Session Domain default 'expiration' value.
  expiration: '1h'

  ## Cookie Session Domain default 'remember_me' value.
  remember_me: '1M'
                          
This is my  users_database.yml

# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  authelia:
    disabled: false
    displayname: 'Admin'
    password: '$argon2id$v=19$m=65536,t=3,p=4$/SkhHue6WTHJU//teIYwBQ$0jKcU4np0l3DuDcqAwECeorWiVVM4NJFId17zNQia9c'  # Password is 'authelia'
    email: 'songyang@163.com'
    groups:
      - 'admins'
      - 'dev'
...
# yamllint enable rule:line-length

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

It seems like your configuration might have some issues that could be causing the login problem. Here are a few things to check and adjust:

1. **Session Configuration**:
   - Ensure that the `domain` in the session configuration matches the domain you are using to access Authelia.
   - Make sure the `authelia_url` is correctly set and accessible.

2. **Access Control**:
   - Verify that the domain in the access control rules matches the domain you are using.

3. **Cookies Configuration**:
   - Ensure that the session cookie settings are correctly configured. It looks like you have commented out the `cookies` section. Uncomment and properly configure it.

4. **Log Level**:
   - Since you have set the log level to `trace`, check the logs for any detailed error messages that might give more insight into the issue.

Here is a revised version of your configuration with some adjustments:

```yaml
log:
  level: 'trace'

identity_validation:
  reset_password:
    jwt_secret: "df797b7cd35f0e4c67d6df2a9ac236a7fa630c121cdc3ac970132dac99da12b7"

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'authelia.local.com'
      policy: 'one_factor'

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 3
  max_desync: '3s'
  disable_startup_check: true
  disable_failure: true

storage:
  postgres:
    address: 'tcp://192.168.1.3:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    password: 'authelia'

authentication_backend:
  file:
    path: /config/users_database.yml
    watch: false
    search:
      email: true
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

session:
  name: 'authelia_session'
  domain: 'authelia.local.com'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'authelia.local.com'
      authelia_url: 'https://authelia.local.com'
      default_redirection_url: 'https://192.168.1.3:9091'
```

Make sure to restart Authelia after making these changes. If the issue persists, please provide more details from the logs to help diagnose the problem further.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
