### DISCUSSION TITLE
One and two factor local network

### DISCUSSION THREAD

**Discussion by Bojo67** [authelia/authelia#7470] [Documentation Feedback] [answered]
Hello everyone!
I have configured my access control like this:

```
access_control :
  default_policy : 'deny

  networks :
    - name : 'internal'
      networks :
        # - '10.10.0.0/16'
        - '192.168.31.0/24'
    # - name : 'VPN
    # networks: '10.9.0.0/16

  rules :
    - domain_regex: '^.*\.domaine\.fr$' # - policy: 'one_factor
      policy : 'one_factor
      networks :
        - '192.168.31.0'

    - domain: 'file.domaine.fr
      policy: 'two_factor
```

The problem is that when I'm local, it also asks me for double authentication!
Is this a configuration problem or is it not possible? 

Thanks 🙏

Translated with DeepL.com (free version)

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

It looks like there are a few issues in your configuration that might be causing the problem. Here are some points to consider:

1. **Syntax Errors**: Ensure that all your strings are properly closed with quotes. For example, `default_policy : 'deny` should be `default_policy : 'deny'`, and `domain: 'file.domaine.fr` should be `domain: 'file.domaine.fr'`.

2. **Network Specification**: The network `192.168.31.0` should be specified with a subnet mask, like `192.168.31.0/24`.

3. **Policy Order**: The order of the rules matters. Ensure that the more specific rules come before the more general ones.

Here is a corrected version of your configuration:

```yaml
access_control:
  default_policy: 'deny'

  networks:
    - name: 'internal'
      networks:
        - '192.168.31.0/24'

  rules:
    - domain_regex: '^.*\.domaine\.fr$'
      policy: 'one_factor'
      networks:
        - '192.168.31.0/24'

    - domain: 'file.domaine.fr'
      policy: 'two_factor'
```

Make sure to check the following:
- The `domain_regex` rule should match the domains correctly.
- The `networks` should be specified correctly with subnet masks.
- The policies should be correctly defined and ordered.

If the issue persists, please provide more details about the specific behavior you are experiencing and any relevant logs.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Comment by james-d-elliott** [comment, marked as answer]
The logs will likely reveal you've not setup the proxy correctly (either via architecture or config) to get the correct IP. The telling factor will be the wrong IP logged on requests.

**Comment by Bojo67** [comment]
The problem is that in the logs it's giving me SMTP problems, even though it's configured and working, because I'm receiving mail for double authentication!

The logs : 
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.address"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.disable_html_emails"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.disable_require_tls"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.identifier"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.password"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.sender"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.startup_check_address"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.subject"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.timeout"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: configuration key not expected: storage.smtp.username"
time="2024-06-30T20:03:46+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
time="2024-06-30T20:03:46+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970
(*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117
(*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041
(*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10
main\nruntime/internal/atomic/types.go:194
(*Uint32).Load\nruntime/asm_amd64.s:1695
goexit"

My SMTP configuration :

```
##
## Notification Provider
##
## Notifications are sent to users when they require a password reset, a WebAuthn registration or a TOTP registration.
## The available providers are: filesystem, smtp. You must use only one of these providers.
notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp://test000-eu.n0c.com:587'
    timeout: '5 seconds'
    username: 'test@domaine.fr'
    password: 'password'
    sender: 'Authelia <test@domaine.fr>'
    identifier: 'localhost'
    subject: '[Authelia] {title}'
    startup_check_address: 'test@domaine.fr'
    disable_require_tls: false
    disable_starttls: false
    disable_html_emails: false

```

in the advanced tab of every proxy except authelia's, I have this : 

```
 location /authelia {
internal;
set $upstream_authelia http://192.168.31.1:9091/api/verify; #change the IP and Port to match the IP and Port of your Authelia container
proxy_pass_request_body off;
proxy_pass $upstream_authelia;    
proxy_set_header Content-Length "";

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
client_body_buffer_size 128k;
proxy_set_header Host $host;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr; 
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 4 32k;

send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;
}

location / {
set $upstream_file $forward_scheme://$server:$port; #change uptime-kuma to match your container name: $upstream_some-container-name or $upstream_somecontainername
proxy_pass $upstream_file; #change uptime-kuma to match your container name: $upstream_some-container-name or $upstream_somecontainername

auth_request /authelia;
auth_request_set $target_url https://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $email $upstream_http_remote_email;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Email $email;
proxy_set_header Remote-Groups $groups;

error_page 401 =302 https://auth.domaine.fr/?rd=$target_url; #change this to match your authentication domain/subdomain

client_body_buffer_size 128k;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

set_real_ip_from 192.168.31.0/24; #make sure this matches your network setup
real_ip_header CF-Connecting-IP;
real_ip_recursive on;

}
```
