### DISCUSSION TITLE
Authelia error reading database

### DISCUSSION THREAD

**Discussion by Strux-DK** [authelia/authelia#7506] [Q&A] [answered]
I have digged myself deep into the Authelia rabbit hole and i'm desperately trying to just make it work for once. I'm running a docker LXC in proxmox with authelia, nginx proxy manager, heimdall, redis and a radarr containers as a test. when running "docker logs authelia" i get: 
error reading the authentication database: could not validate the schema: Users.Matias.users: non zero value required" provider=user
and i also get:
time="2024-07-07T13:43:34+02:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[user]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                  (Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                 (Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                 (Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
What is meant by this? I've looked through my users database with only one user and i'm pretty sure it's as it should be

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

The error messages you're encountering suggest that there are issues with the user provider configuration in your Authelia setup. Specifically, the error `error reading the authentication database: could not validate the schema: Users.Matias.users: non zero value required` indicates that there might be a problem with the structure or content of your user database.

Here are some steps to troubleshoot and resolve the issue:

1. **Check User Database Format**:
   Ensure that your user database (likely a YAML file) is correctly formatted. The error suggests that a required field is missing or incorrectly set. Here is an example of a correct user database format:

   ```yaml
   users:
     matias:
       password: "$argon2id$v=19$m=65536,t=2,p=1$Z3Vlc3Q$K1N1bGx5U2VjcmV0UGFzc3dvcmQ="
       displayname: "Matias"
       email: "matias@example.com"
       groups:
         - admins
   ```

   Make sure that all required fields (`password`, `displayname`, `email`, and `groups`) are present and correctly formatted.

2. **Validate YAML Syntax**:
   Use a YAML validator to ensure there are no syntax errors in your user database file. Even a small indentation error can cause issues.

3. **Check for Common Errors**:
   - Ensure that the `password` field contains a valid hash.
   - Ensure that the `groups` field is a list and not a single string.
   - Ensure that all user entries have unique keys.

4. **Review Logs for More Details**:
   The error message suggests checking the error level logs for more details. Run `docker logs authelia` and look for any additional error messages that might provide more context.

5. **Example Configuration**:
   Here is a more detailed example of a user database configuration:

   ```yaml
   users:
     matias:
       password: "$argon2id$v=19$m=65536,t=2,p=1$Z3Vlc3Q$K1N1bGx5U2VjcmV0UGFzc3dvcmQ="
       displayname: "Matias"
       email: "matias@example.com"
       groups:
         - admins
     anotheruser:
       password: "$argon2id$v=19$m=65536,t=2,p=1$Z3Vlc3Q$K1N1bGx5U2VjcmV0UGFzc3dvcmQ="
       displayname: "Another User"
       email: "anotheruser@example.com"
       groups:
         - users
   ```

If you continue to experience issues, please provide more details about your user database configuration, and I can assist further.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).

**Reply by Strux-DK** [reply]
I checked and validated my users database, however i can see that 2 databases has been created in my LXC; one at path/to/config/authelia/users_database.yml and one at path/to/config/authelia/config/users_database.yml - and at this point, i'm not sure which one to maintain.
Users database (they're the same, but the error is still produced):
```
# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  matias:
    displayname: "Strux"
    password: "secret hash"
    email: "matias@example.com"
    groups:
      - admins

...
# yamllint enable rule:line-length
```
I created the hash with:
```htpasswd -nbB matias <password>```
I don't know if that is a valid approach.

Logs:
```
time="2024-07-07T13:43:34+02:00" level=info msg="Authelia v4.38.9 is starting"
time="2024-07-07T13:43:34+02:00" level=info msg="Log severity set to info"
time="2024-07-07T13:43:34+02:00" level=info msg="Storage schema is being checked for updates"
time="2024-07-07T13:43:34+02:00" level=info msg="Storage schema is already up to date"
time="2024-07-07T13:43:34+02:00" level=error msg="Error occurred running a startup check" error="error reading the authentication database: could not validate the schema: Users.Matias.users: non zero value required" provider=user
time="2024-07-07T13:43:34+02:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[user]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-07-07T13:44:17+02:00" level=info msg="Authelia v4.38.9 is starting"
time="2024-07-07T13:44:17+02:00" level=info msg="Log severity set to info"
time="2024-07-07T13:44:17+02:00" level=info msg="Storage schema is being checked for updates"
time="2024-07-07T13:44:17+02:00" level=info msg="Storage schema is already up to date"
time="2024-07-07T13:44:17+02:00" level=info msg="Startup complete"
time="2024-07-07T13:44:17+02:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2024-07-07T13:46:56+02:00" level=info msg="Shutdown initiated"
time="2024-07-07T13:46:56+02:00" level=info msg="Shutdown complete"
time="2024-07-07T13:46:57+02:00" level=info msg="Authelia v4.38.9 is starting"
time="2024-07-07T13:46:57+02:00" level=info msg="Log severity set to info"
time="2024-07-07T13:46:57+02:00" level=info msg="Storage schema is being checked for updates"
time="2024-07-07T13:46:57+02:00" level=info msg="Storage schema is already up to date"
time="2024-07-07T13:46:57+02:00" level=info msg="Startup complete"
time="2024-07-07T13:46:57+02:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2024-07-07T13:49:49+02:00" level=info msg="Shutdown initiated"
time="2024-07-07T13:49:49+02:00" level=info msg="Shutdown complete"
```
If there's anything else i can provide, please do tell
