### DISCUSSION TITLE
Can't get TOTP working...

### DISCUSSION THREAD

**Discussion by nickali** [authelia/authelia#7507] [Q&A]
I've got one factor working fine and now I'm trying to transition to two factor, but I never get asked for a TOPT. 

My set up is pretty simple.

users-database.yml:
```
users:
  my-username:
    disabled: false
    displayname: "I Groot"
    password: "$argon2id$v=..."
    email: my@email.com
    groups:
      - admins
      - dev
```

configuration.yml:
```
...
access_control:
  default_policy: deny
  rules:
    - domain: 'auth.mydomain.org'
      policy: 'two_factor'
session:
  secret: '...'
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'auth.mydomain.org'
      authelia_url: 'https://auth.mydomain.org'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'
...
totp:
  disable: false
  issuer: 'auth.mydomain.org'
```

When I try to authenticate, after I put in my username and password, I'm never asked to register TOTP. Instead I get approved. 

I've also tried generating the TOTP manually with:

```
$ authelia storage user totp generate my-username --sqlite.path db.sqlite3
Successfully generated TOTP configuration for user 'my-username' with URI 'otpauth://totp/auth.mydomain.org:my-username?algorithm=SHA1&digits=6&issuer=auth.mydomain.org&period=30&secret=ARQ...'
```

I then see a corresponding entry in the top_configurations:

```
  2 | 2024-07-07T17:15:14.864739Z |              | my-username     | auth.mydomain.org | SHA1      |      6 |     30 | H\...
```
<br>
Do I need to pass in the encryption key when I call 'authelia...totp generate..'?

Here is what I see in my logs when I try to authenticate:

```
time="2024-07-07T16:56:47Z" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-07-07T16:56:47Z" level=debug msg="Mark 1FA authentication attempt made by user 'my@email.com'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:249 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-07-07T16:56:47Z" level=debug msg="Successful 1FA authentication attempt made by user 'my@email.com'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:271 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-07-07T16:56:47Z" level=trace msg="Profile details for user 'my@email.com' => groups: [admins dev], emails [my@email.com]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:135 handleRouter.FirstFactorPOST.func10" method=POST path=/api/firstfactor remote_ip=127.0.0.1
```
<br>
My Caddyfile:

```
# Authelia Portal.
auth.mydomain.org {
        tls internal
        reverse_proxy authelia:9091 {
                ## This import needs to be included if you're relying on a trusted proxies configuration.
                import trusted_proxy_list
        }
}
```

I'm using a Cloudflare Tunnel which is set up as:

```
Public hostname: auth.mydomain.org
Service Type: https://localhost
Origin Server Name: auth.mydomain.org
No TLS Verify: True
HTTP Host Header: auth.mydomain.org
```

Cloudflare transformation rule:

```
When incoming requests match 'X-Forwarded-For' 'does not equal' '<blank>'
Then 'Remove' 'X-Forwarded-For'
```

These Cloudflare settings have been working for one_factor, so I don't think they are the issue.

Any ideas why TOTP isn't being triggered?
