### DISCUSSION TITLE
What does "Error occurred trying to determine the external Authelia URL for Target URL" mean?

### DISCUSSION THREAD

**Discussion by wsw70** [authelia/authelia#7524] [Q&A] [answered]
I had a Caddy+Authelia installation working, I am now moving towards a Traefik+Authelia one and I have a problem probably related to my lack of understanding of how this combo works.

What works:
- Traefik can serve a container without authentication
- Authelia runs in a container and is correctly proxied through Traefik (i.e. `https://authelia.swtk.eu` is available, with Authelia being at `http://authelia:9091`

My setup is identical to [the one from the docs](https://www.authelia.com/integration/proxies/traefik/#assumptions-and-adaptation).

What does not work:
- adding a container that I would like to protect with Authelia (by adding a `traefik.http.routers.<container>.middlewares=authelia@docker` label) generates the following error in Authelia when I attempt to access it:

```
time="2024-07-13T21:55:12+02:00" level=error msg="Error occurred trying to determine the external Authelia URL for Target URL" error="authelia url lookup failed" method=GET path=/api/authz/forward-auth remote_ip=171.33.110.201 target_url="https://worldclock.swtk.eu/"
```

I seem to be te only one in the world that has this issue so help please!

For reference, this is how Traefik and Authelia are spawned:

```
  traefik:
    image: traefik:latest
    command:
      # general
      - --providers.file.filename=/config/config.yml
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker.exposedByDefault=false
      # Tell Traefik to discover containers using the Docker API
      - --providers.docker=true
      # Enable the Trafik dashboard
      - --api.dashboard=true
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=ovh
      - --certificatesresolvers.letsencrypt.acme.email=XXX
      - --certificatesresolvers.letsencrypt.acme.storage=/config/acme.json
      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # Set up the TLS configuration for our websecure listener and wildcard
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entryPoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=swtk.eu
      - --entrypoints.websecure.http.tls.domains[0].sans=*.swtk.eu
      # force all traffic through authelia
      #- --entryPoints.websecure.http.middlewares=authelia@docker
      # Send anonymous usage data
      - --global.sendAnonymousUsage
      ## Please see the Forwarded Header Trust section of the Authelia Traefik Integration documentation.
      - --entryPoints.http.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7
      - --entryPoints.http.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7
      - --entryPoints.http.forwardedHeaders.insecure=false
      - --entryPoints.http.proxyProtocol.insecure=false
    ports:
      - 80:80
      - 443:443
      - 18080:8080
    environment:
      - OVH_ENDPOINT=https://eu.api.ovh.com/v1
      - OVH_APPLICATION_KEY=XXX
      - OVH_APPLICATION_SECRET=XXX
      - OVH_CONSUMER_KEY=XXX
      - TZ=Europe/Paris
    volumes:
      - traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      
  authelia:
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    volumes:
      - authelia:/config
    environment:
      TZ: "Europe/Paris"
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`authelia.swtk.eu`)
      #- traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name

```

**Comment by glime-ai** [comment]
Please note this response was created using generative AI leveraging previously available information from the repository. This information may be helpful however it is our strong recommendation that you carefully consider the information before blindly applying it.

---

It seems like the issue you're encountering is related to the configuration of the external Authelia URL. The error message indicates that Authelia is having trouble determining the external URL for the target URL.

Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Ensure Correct External URL Configuration**:
   Make sure that the external URL for Authelia is correctly configured. This can be done by setting the `authelia_url` parameter in the forwardAuth address. For example:
   ```yaml
   - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth?authelia_url=https://authelia.swtk.eu
   ```

2. **Check Middleware Configuration**:
   Ensure that the middleware is correctly referenced in your Traefik configuration. The middleware should be defined and referenced properly in your Traefik labels.

3. **Verify Network Configuration**:
   Ensure that both Traefik and Authelia are on the same Docker network and can communicate with each other. This is crucial for the forwardAuth middleware to work correctly.

4. **Review Traefik Logs**:
   Check the Traefik logs for any additional errors or warnings that might provide more context about the issue.

5. **Authelia Configuration**:
   Ensure that the Authelia configuration is correct and that it is set up to handle the forwardAuth requests properly.

Here is an example of how your Traefik and Authelia configuration might look with the `authelia_url` parameter added:

```yaml
traefik:
  image: traefik:latest
  command:
    - --providers.file.filename=/config/config.yml
    - --log.level=DEBUG
    - --api.insecure=true
    - --providers.docker.exposedByDefault=false
    - --providers.docker=true
    - --api.dashboard=true
    - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
    - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=ovh
    - --certificatesresolvers.letsencrypt.acme.email=XXX
    - --certificatesresolvers.letsencrypt.acme.storage=/config/acme.json
    - --entrypoints.web.address=:80
    - --entrypoints.web.http.redirections.entrypoint.to=websecure
    - --entrypoints.web.http.redirections.entrypoint.scheme=https
    - --entryPoints.websecure.address=:443
    - --entrypoints.websecure.http.tls=true
    - --entryPoints.websecure.asDefault=true
    - --entrypoints.websecure.http.tls.certResolver=letsencrypt
    - --entrypoints.websecure.http.tls.domains[0].main=swtk.eu
    - --entrypoints.websecure.http.tls.domains[0].sans=*.swtk.eu
    - --global.sendAnonymousUsage
    - --entryPoints.http.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7
    - --entryPoints.http.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7
    - --entryPoints.http.forwardedHeaders.insecure=false
    - --entryPoints.http.proxyProtocol.insecure=false
  ports:
    - 80:80
    - 443:443
    - 18080:8080
  environment:
    - OVH_ENDPOINT=https://eu.api.ovh.com/v1
    - OVH_APPLICATION_KEY=XXX
    - OVH_APPLICATION_SECRET=XXX
    - OVH_CONSUMER_KEY=XXX
    - TZ=Europe/Paris
  volumes:
    - traefik:/config
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro

authelia:
  image: docker.io/authelia/authelia:latest
  restart: unless-stopped
  volumes:
    - authelia:/config
  environment:
    TZ: "Europe/Paris"
  labels:
    - traefik.enable=true
    - traefik.http.routers.authelia.rule=Host(`authelia.swtk.eu`)
    - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth?authelia_url=https://authelia.swtk.eu
    - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
    - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name
```

If the issue persists, please provide more details about your configuration and any additional error messages you are seeing.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=6fsHkcyufjQLaB&utm_medium=github).
