### DISCUSSION TITLE
Quickly Logging back in after logout issue

### DISCUSSION THREAD

**Discussion by ghost** [authelia/authelia#7535] [Troubleshooting]
Issue: Logging out a user via /api/logout, sometimes if I quickly attempt to log back in to the app, authelia will authenticate the previous session. No cookies are set except authelia_session, which is the session id of the supposedly logged out session. Obviously this is not the desired result given another user may be logging in. Interestingly, if a wait a few minutes, and log back in to the same app, it works properly. Seems to be something with timing. I am using SFA and the system is dockerized.

The result code of the /api/logout is successful(ret code 200). Here is my TypeScript function performing the logout:
```
  logout() {
    const logoutUrl = 'https://auth.domain.com/api/logout';
    const headers = new HttpHeaders({
      'Content-Type': 'application/json'
    });

    return this.http.post(this.logoutUrl, {}, { headers, withCredentials: true }).subscribe(
      response => {
        console.log('Logout successful', response);
        this.bAuthenticated = false;
        this.clearCookies(['username', 'email', 'groups', 'name']); // Add specific cookies to clear
    
        this.router.navigate(['/logout']);
      },
      error => {
        console.error('Logout failed', error);
      }
    );
  }
```
Note that the user metadata is cleared on a successful logout. The router.navigate routes to a page that provides a link to login to the app:
```
<a href="https://test.domain.com">Click here to log back in</a>
```

As mentioned earlier, everything works fine sometimes, but other times the authelia login screen is not displayed, and informs  my reverse proxy that the location is authorized, and not user metadata is present in the cookies. Sometimes when it gets in that loop/state, you can only get out of it by waiting a fiew minutes or clearing the domain date(which nukes the authelia_session cookie).

Here is my authelia session config:
```
session:
   name: authelia_session
   secret: "<secret>"
   expiration: 1h
   inactivity: 5m
   same_site: 'lax'
   remember_me: '1M'
   cookies:
    - domain: 'domain.com'
      authelia_url: 'https://auth.domain.com'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'
   redis:
      host: app_redis
      port: 6379
```
I am using mariadb for storage. Any help would be great. Thanks

Greg
