### DISCUSSION TITLE
Consent screen is shown every time

### DISCUSSION THREAD

**Discussion by nfx** [authelia/authelia#7548] [General]
Is it really necessary to show consent every non-first time when user sign-ins with authelia to an app? Azure AD asks consent for the first time only, for example. config:

```
    clients: # generate UUIDs with `uuidgen`
      - client_name: Grafana
        client_id: GHLKJH....
        client_secret: {{ secret "/run/secrets/grafana-client" }}
        public: false
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - https://grafana.mrkr.dev/login/generic_oauth
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
```
