### DISCUSSION TITLE
Secure Vaultwarden

### DISCUSSION THREAD

**Discussion by ZzenlD** [authelia/authelia#7610] [Q&A] [answered]
Hello everyone,

I would like to secure my Vaultwarden instance with Authelia as follows: 
- All users of the group “vaultwarden_user” should be able to log in via the web interface and via app/browser extension.
- The /admin path, should only be accessible to users in the “vaultwarden_admin” group.
- A user can belong to both groups.

My current configuration looks like this:
```yaml
access_control:
  default_policy: deny
  rules:
    - domain:
      - vaultwarden.mydomain
      resources:
        - '^/admin.*'
      policy: one_factor
      subject:
        - group:vaultwarden_admin
       
    - domain:
        - vaultwarden.mydomain
      policy: one_factor
      subject:
        - group:vaultwarden_user
```

The problem now is that users who only belong to the group “vaultwarden_user” can also access /admin. Does anyone know what my mistake is and how I can implement this correctly?

Thanks for your help.
