### DISCUSSION TITLE
Help integrating Zot Container Registry with Authelia SSO

### DISCUSSION THREAD

**Discussion by giovannipapini** [authelia/authelia#7615] [Q&A]
Hello everyone, I'm lately trying to integrate [Zot SSO authentication](https://zotregistry.dev/v2.1.0/articles/authn-authz/#using-google-github-or-gitlab) with [Authelia OAuth](https://www.authelia.com/integration/openid-connect/oauth-2.0-bearer-token-usage), but I'm quite stuck.

I tried to districate myself in the documentation (in the links), but I'm not sure if it is even possible and in such case what am I doing wrong.

The relevant parts of my current respective configurations are:

```
authelia/conf.yml

identity_providers:
  oidc:
    jwks:
      - key: {{ secret "/run/secrets/authelia.identity.providers.oidc.jwks.key" | mindent 10 "|" | msquote }}
        #algorithm: 'RS256'
    discovery_signed_response_alg: 'none'
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    clients:
      - client_id: {{ secret "/run/secrets/authelia.oidc.zot.client.id" | squote }}
        client_secret: {{ secret "/run/secrets/authelia.oidc.zot.client.secret" | squote }}
        public: false
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'http://{{ mustEnv "CTX_REGISTRY_SUBDOMAIN" }}.{{ mustEnv "CTX_DOMAIN" }}/zot/auth/callback/oidc'
        audience:
          - 'http://{{ mustEnv "CTX_REGISTRY_SUBDOMAIN" }}.{{ mustEnv "CTX_DOMAIN" }}'
        scopes:
          - 'offline_access'
          - 'authelia.bearer.authz'
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        response_types:
          - 'code'
        response_modes:
          - 'form_post'
        consent_mode: 'explicit'
        require_pushed_authorization_requests: true
        token_endpoint_auth_method: 'none'
```

```
zot/config.json

  "http": {
    "address": "0.0.0.0",
    "port": "5000",
    "externalUrl": "https://{{ env "CTX_REGISTRY_SUBDOMAIN" }}.{{ env "CTX_DOMAIN" }}",
    "auth": {
      "apikey": true,
      "openid": {
        "providers": {
          "oidc": {
            "name": "Authelia SSO",
            "issuer": "https://{{ env "CTX_AUTHELIA_SUBDOMAIN" }}.{{ env "CTX_DOMAIN" }}",
            "clientid": "{{ secret "oidc.zot.client.id" }}",
            "clientsecret": "{{ secret "oidc.zot.client.id" }}",
            "scopes": ["openid", "user", "email", "groups"]
          }
        }
      }
    }
  },
```

Any expert in OIDC/OAuth flows that could help me?
