### DISCUSSION TITLE
Help getting Microsoft Entra ID as identity provider

### DISCUSSION THREAD

**Discussion by WilliamStam** [authelia/authelia#7667] [Q&A] [answered]
hi, we have microsoft entra id (old azure AD) that our users are in. want to connect authelia to use it as the main identity provider. 

im a few shades of in need of help on where to get started with it even.

can it be used to return the groups the user is a part of as well?

this look ok?

```yaml
# identity_providers.yaml

identity_providers:
    oidc:
        # https://www.authelia.com/configuration/identity-providers/openid-connect/provider/
        hmac_secret: '{{ env "HMAC_SECRET" }}'
        jwks:
            -   algorithm: 'RS256'
                use: 'sig'
                key: '{{ secret "/secrets/oidc/jwks/rsa.2048.key" | mindent 10 "|" | msquote }}'
                
        enable_client_debug_messages: false
        minimum_parameter_entropy: 8
        enforce_pkce: 'public_clients_only'
        enable_pkce_plain_challenge: false
        enable_jwt_access_token_stateless_introspection: false
        discovery_signed_response_alg: 'none'
        discovery_signed_response_key_id: ''
        require_pushed_authorization_requests: false
        authorization_policies:
            admin:
                default_policy: 'user'
                rules:
                    - policy: 'two_factor'
                      subject: 'group:admin'
            user:
                default_policy: 'one_factor'
                rules:
                    - policy: 'one_factor'
                      subject: 'group:users'
                
        lifespans:
            access_token: '1h'
            authorize_code: '1m'
            id_token: '1h'
            refresh_token: '90m'

        
        
        clients:
            -   client_id: 'gitea'
                client_name: 'Gitea'
                client_secret: '$pbkdf2-sha512$31000jf.9yHxzQGZziziccp6Yng'.
                public: false
                authorization_policy: 'user'
                redirect_uris:
                    - 'https://git.{{ env "DOMAIN" }}/user/oauth2/4gl/callback'
                scopes:
                    - 'openid'
                    - 'email'
                    - 'profile'
                userinfo_signed_response_alg: 'none'
                token_endpoint_auth_method: 'client_secret_basic'
``` 

this is mainly me just playing around with it. another question. Clients part is needed for every app we add to the "stack" right?
