### DISCUSSION TITLE
OIDC: Token Revocation fails if client is public

### DISCUSSION THREAD

**Discussion by tamedfox42** [authelia/authelia#7711] [Troubleshooting]
While working with Authelia and [`oidc-client-ts`](https://github.com/authts/oidc-client-ts), I noticed that the library was unable to revoke access tokens provided by my Authelia instance, which yields the following log messages:

```
level=error msg="Revocation Request with id '...' failed with error: 
Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). 
The request was determined to be using 'revocation_endpoint_auth_method' method 'none', however the OAuth 2.0 client registration does not allow this method. 
The registered client with id 'demo' is configured to only support 'revocation_endpoint_auth_method' method ''. 
Either the Authorization Server client registration will need to have the 'revocation_endpoint_auth_method' updated to 'none' or the Relying Party will need to be configured to use ''."
```

To the best of my knowledge, Authelia's config does not have such a flag (`revocation_endpoint_auth_method`). This error happens while I use a client with `public: true` set.

<details><summary>Authelia Configuration</summary>
<p>

```
identity_validation:
  reset_password:
    jwt_secret: 'a_very_important_secret'

log:
  level: 'debug'

access_control:
  default_policy: one_factor

authentication_backend:
  file:
    path: '/etc/authelia/users_database.yml'

session:
  secret: 'insecure_session_secret'

  cookies:
    - name: 'authelia_session'
      domain: 'example.com'
      authelia_url: 'https://auth.example.com'
      expiration: '1 hour'
      inactivity: '5 minutes'

storage:
  encryption_key: 'you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this'
  local:
    path: '/etc/authelia/db.sqlite3'

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/etc/authelia/notifier.txt'

identity_providers:
  oidc:
    hmac_secret: 'this_is_a_secret_abc123abc123abc'
    jwks:
      - key_id: 'example'
        algorithm: 'RS256'
        use: 'sig'
        key: |
          -----BEGIN PRIVATE KEY-----
          ...
          -----END PRIVATE KEY-----
        certificate_chain: |
          -----BEGIN CERTIFICATE-----
          ...
          -----END CERTIFICATE-----
    clients:
      - client_id: 'demo'
        authorization_policy: 'one_factor'
        public: true
        response_types:
          - code
          - id_token
          - token
        redirect_uris:
          - "https://demo.example.com/processLogin"
```

</p>
</details> 

<details><summary>Authelia Version</summary>
<p>

```
# authelia build-info
Last Tag: v4.38.10
State: tagged clean
Branch: v4.38.10
Commit: b7d5e3ff29917bd0842c8509b4a8338d19f2934e
Build Number: AUR
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 18 Aug 2024 12:09:18 +0000
Extra: 

Go:
    Version: go1.23.0
    Module Path: 
    Executable Path: command-line-arguments

```

</p>
</details> 

<details><summary>Replication</summary>
<p>

- Generate a token using `authorization` endpoint (follow redirection in Browser, extract token)

```
curl -i -k 'https://auth.example.com/api/oidc/authorization?client_id=demo&redirect_uri=https://demo.example.com/processLogin&state=abcd1234&response_type=token&scope=openid'              
```

- Test that the access token works

```
curl -i -k -H "Authorization: Bearer $TOKEN" 'https://auth.example.com/api/oidc/userinfo'                                                                                                   
```

- Try to revoke the token

```
curl -i -k -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "token=$TOKEN&token_type_hint=access_token&client_id=demo" 'https://auth.example.com/api/oidc/revocation'
```

</p>
</details> 

Is this a bug within Authelia (or not yet implemented) or does the library/me use the API incorrectly?
