### DISCUSSION TITLE
I think the `email` claim isn't being advertised

### DISCUSSION THREAD

**Discussion by livingsilver94** [authelia/authelia#7746] [Q&A] [answered]
This post will be highly uncertain because I'm not familiar with OIDC. Please bear with me.

I think the `email` claim isn't being advertised despite the `email` scope is listed. In particular, I'm trying to make Authelia work as the OIDC provider for [Mealie](https://mealie.io).

See my Authelia configuration:

```yaml
- client_id: 'mealie'
  client_name: 'Mealie'
  public: true
  authorization_policy: 'one_factor'
  require_pkce: true
  pkce_challenge_method: 'S256'
  redirect_uris:
    - 'https://mealie.{{env "MY_DOMAIN"}}/login'
    - 'https://mealie.{{env "MY_DOMAIN"}}/login?direct=1'
  scopes:
    - 'openid'
    - 'email'
    - 'profile'
    - 'groups'
  userinfo_signed_response_alg: 'none'
  token_endpoint_auth_method: 'none'
```

Mealie is able to reach Authelia, but the login fails because
> [OIDC] Required claims not present. Expected: {'email', 'name', 'preferred_username'} Actual: dict_keys(['amr', 'at_hash', 'aud', 'auth_time', 'azp', 'client_id', 'exp', 'groups', 'iat', 'iss', 'jti', 'name', 'preferred_username', 'sub'])

I think the `email` scope is being ignored...? For the record, I also host oCIS and the OAuth login is working in that case.
