### DISCUSSION TITLE
Authelia doesn't protect subdomain.

### DISCUSSION THREAD

**Discussion by kaliavarun** [authelia/authelia#7747] [Q&A]
hello,
I am setting up authelia for a homelab . I am runnning a SWAG container with authelia and homepage containers running in same networl. I have configured authelia.mydomain.com and homepage.mydomain.com as CNAME in cloudflare.

Here is the configuration.yml for authelia.

![image](https://github.com/user-attachments/assets/167ad7ed-2d42-49a8-b4e6-be9895a2d848)

Here is my authelia proxy conf

![image](https://github.com/user-attachments/assets/73dd6d5b-a672-40f9-951a-5f676656e38a)

Here is my homepage proxy conf.

![image](https://github.com/user-attachments/assets/63b4a4ae-0dd4-4f95-8b45-66a3757b167c)

Here is the default.conf

![image](https://github.com/user-attachments/assets/4f7ecb15-2a6c-4c0d-8fe9-d0853f593074)

Here is the docker compsose:

```
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=mydomain.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/config
    #networks:
    #  - net
    ports:
      - 9091:9091
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data
    #networks:
    #  - net
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3001:3000
    volumes:
      - ./homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
```

When I access authelia.mydomain.com I can see the login screen. Once authenticated successfully, it redirects to homepage.mydomain.com. This is ok. However, I can also directly access homepage.mydomain.com in a different browser without any authentication. Looks like homepage.mydomain.com is not protected. I am not sure what can I do to protect all subdomains. I want the user accessing to be redirected to authelia.homepage.com first and then redirected to homepage.mydomain.com or any other subdomain only after authentication.
