### DISCUSSION TITLE
[Help] Integrate authelia for both Remote and local access

### DISCUSSION THREAD

**Discussion by alx-xlx** [authelia/authelia#7836] [Q&A]
I have nextcloud running in a docker container in pi5. it runs on 192.168.0.103:8092
I have exposed it to internet using cloudflared tunnel

```
  - hostname: nc.example.org
    service: http://192.168.0.103:8092
```

I have caddy running as reverse proxy 
my Caddyfile looks like
```
nc.example.org {
    redir /.well-known/carddav /remote.php/dav/ 301
    redir /.well-known/caldav /remote.php/dav/ 301

    reverse_proxy http://192.168.0.103:8092
    tls {
        dns cloudflare _QR*******************************u-VP
    }
}


I am not very techie, so please be gentle

**Comment by james-d-elliott** [comment]
There are a number of ways to integrate authelia. The minimum requirements would be to configure authelia similar to any other app, I'd suggest the [get started guide](https://www.authelia.com/integration/prologue/get-started/) for this. Then you need to decide between OIDC and forwarded authentication. Forwarded authentication is simpler but most phone apps or desktop apps don't like it, OIDC is more complex but often is supported by apps (not always unfortunately). 

We have a community guide on the OIDC element but it assumes you've got the minimal setup already: https://www.authelia.com/integration/openid-connect/nextcloud/

**Comment by christaikobo** [comment]
```
nc.example.org {
    redir /.well-known/carddav /remote.php/dav/ 301
    redir /.well-known/caldav /remote.php/dav/ 301

    tls {
        dns cloudflare _QR*******************************u-VP
    }

    handle /auth* {
        reverse_proxy 192.168.0.103:9091
    }

    handle {
        forward_auth 192.168.0.103:9091 {
            uri /api/authz/forward-auth?authelia_url=https://nc.example.org/auth
        }
        reverse_proxy 192.168.0.103:8092
    }
}
```
This is a barebones caddy file example. 

```
users:
  admin:
    disabled: false
    displayname: 'Admin'
    password: ''
    email: ''
    groups:
      - 'admin'
```
Barebones for `users_database.yml`
```
---

authentication_backend:

  file:
    path: '/config/users_database.yml'

totp:
  issuer: 'Authelia'

access_control:

  rules:
  - domain:
    - 'nc.example.org'
    subject:
    - 'group:admin'
    - 'group:user'
    policy: 'two_factor'

regulation:
  max_retries: 5
  find_time: '3 minutes'
  ban_time: '30 minutes'

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

identity_validation:

  reset_password:
    jwt_secret: ''

session:

  cookies:
    - domain: 'nc.example.org'
      authelia_url: 'https://nc.example.org/auth'

storage:
  encryption_key: ''

  local:
    path: '/config/db.sqlite3'

notifier:

  smtp:
    address: 'smtp://'
    # timeout: '5 seconds'
    username: ''
    password: ''
    sender: 'Authelia <admin@example.com>'


server:
  address: 'tcp://:9091/auth'

log:
  level: 'info'
  format: 'text'
  file_path: '/config/authelia.{datetime:2006-01-02}.log'
...
```
Barebones for `configuration.yml`, fill in the empty items. 

```
docker run -d \
  --restart unless-stopped \
  --name authelia \
  -e TZ= \
  -e PUID= \
  -e PGID= \
  -v /path/to/config:/config \
  ghcr.io/authelia/authelia:latest
```
docker run commands.
