### DISCUSSION TITLE
Google OAuth with Authelia - Need Guidance

### DISCUSSION THREAD

**Discussion by StrangeNoob** [authelia/authelia#7848] [Q&A] [answered]
Hi everyone,

I’m trying to integrate Google OAuth with Authelia using the OpenID Connect (OIDC) provider. I have successfully created the `client_id` and `client_secret` through Google Cloud, and configured the redirect URIs. However, I’m encountering configuration challenges, particularly around jwks and ensuring the setup works as expected with Google’s OAuth flow.

Has anyone successfully implemented this? Any help or guidance would be greatly appreciated!

Here’s my current setup:

```
identity_providers:
  oidc:
    clients:
      - client_id: "..."
        client_secret: "..."
        redirect_uris:
          - "..."
    jwks:
      uri: "https://www.googleapis.com/oauth2/v3/certs"
```

Thanks in advance!
