### DISCUSSION TITLE
Seeking help: authelia@docker connection refused

### DISCUSSION THREAD

**Discussion by deefour** [authelia/authelia#7902] [Troubleshooting] [answered]
I am many hours deep trying to get traefik to redirect to authelia, but cannot get past this issue. I am reaching out for help.

    2024-09-22T06:16:08Z DBG github.com/traefik/traefik/v3/pkg/middlewares/auth/forward.go:153 > Error calling http://authelia:12200/api/authz/forward-auth. Cause: Get "http://authelia:12200/api/authz/forward-auth": dial tcp 192.168.90.8:12200: connect: connection refused middlewareName=authelia@docker middlewareType=ForwardAuth

Here are `docker-compose.yml` details for authelia, traefik, and sonarr.

```
  services:
    sonarr:
      container_name: sonarr
      hostname: sonarr.internal
      image: ghcr.io/hotio/sonarr
      ports:
        - "12010:8989"
      volumes:
        - /share/media/docker/sonarr/config:/config
        - /share/media/content:/data
      environment:
        - PUID=1201
        - PGID=1002
        - UMASK=002
        - TZ="Etc/UTC"
      cap_add:
        - NET_ADMIN
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.disable_ipv6=1
      devices:
        - /dev/net/tun:/dev/net/tun
      restart: unless-stopped
      networks:
        - traefik_proxy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sonarr.entrypoints=websecure"
        - "traefik.http.routers.sonarr.tls=true"
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.example.org`)"
        - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
        - "traefik.http.routers.sonarr.middlewares=authelia@docker"

    traefik:
      container_name: traefik
      hostname: traefik.internal
      image: traefik:v3.1
      security_opt:
        - no-new-privileges:true
      restart: unless-stopped
      networks:
        traefik_proxy:
          ipv4_address: 192.168.90.254
      environment:
        - CF_API_EMAIL_FILE=/run/secrets/cf_api_email
        - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
        - CLOUDFLARE_EMAIL=********
        - PUID=1219
        - PGID=1003
        - UMASK=002
        - TZ="Etc/UTC"
      command:
        - --log.level=DEBUG
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --api.dashboard=true
        - --global.sendAnonymousUsage=false

        # LetsEncrypt certificate resolver
        - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
        - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
        - --certificatesResolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
        - --certificatesResolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=60
        - --certificatesResolvers.letsencrypt.acme.dnschallenge.disablePropagationCheck=true
        - --certificatesresolvers.letsencrypt.acme.email=**********
        - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
        
        # 80 -> 443 redirect
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:443
        - --entrypoints.traefik.address=:8443
        - --entrypoints.websecure.http.tls=true
        - --entrypoints.web.http.redirections.entrypoint.to=websecure
        - --entrypoints.web.http.redirections.entrypoint.scheme=https
        - --entrypoints.web.http.redirections.entrypoint.permanent=true
        
        # TLS connection
        - --entrypoints.websecure.http.tls=true
        - --entrypoints.websecure.http.tls.certResolver=letsencrypt
        - --entrypoints.websecure.http.tls.domains[0].main=example.org
        - --entrypoints.websecure.http.tls.domains[0].sans=*.example.org

        - --providers.docker.network=traefik_proxy
        - --entrypoints.websecure.http.tls.options=tls-opts@file
      ports:
        - 80:80
        - 443:443
        - 12190:8443
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /share/selfhosting/docker/traefik/data/certs:/letsencrypt
        - /share/selfhosting/docker/traefik/logs:/logs
      secrets:
        - cf_dns_api_token
        - cf_api_email
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.example.org`)"
        - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=strip"
        - "traefik.http.routers.traefik.middlewares=authelia@docker"
        - "traefik.http.middlewares.strip.stripprefix.prefixes=/traefik"
      depends_on:
        - authelia

    authelia:
      image: docker.io/authelia/authelia:latest
      container_name: authelia
      hostname: authelia.internal
      environment:
        - LOG_LEVEL=debug
        - PUID=1220
        - PGID=1003
        - UMASK=002
        - TZ=Etc/UTC
        - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
        - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
        - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
        - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      secrets:
        - authelia_jwt_secret
        - authelia_session_secret
        - authelia_storage_encryption_key
        - smtp_password
      volumes:
        - /share/selfhosting/docker/authelia/config:/config
      ports:
        - 12200:9091
      restart: unless-stopped
      networks:
        - traefik_proxy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authelia.entrypoints=websecure"
        - "traefik.http.routers.authelia.tls=true"
        - "traefik.http.routers.authelia.rule=Host(`authelia.example.org`)"
        - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:12200/api/authz/forward-auth"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"

  networks:
    traefik_proxy:
      name: traefik_proxy
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.90.0/24
```

and here is my configuration.yml for authelia

```
    ---
    theme: 'light'

    default_2fa_method: 'totp'

    server:
      address: 'tcp://:9091/'

    log:
      level: 'debug'
      format: 'json'
      file_path: '/config/authelia.log'
      keep_stdout: true

    telemetry:
      metrics:
        enabled: false

    totp:
      disable: false
      issuer: 'authelia.example.org'

    regulation:
      max_retries: 3
      find_time: '2 minutes'
      ban_time: '5 minutes'

    storage:
      local:
        path: '/config/db.sqlite3'

    notifier:
      disable_startup_check: true
      smtp:
        username: postmaster@example.org
        host: smtp.mailgun.org
        port: 465
        sender: 'authelia@example.org'

    session:
      cookies:
        - name: 'authelia_session'
          domain: 'example.org'
          authelia_url: 'https://authelia.example.org'
          expiration: '1 hour'
          inactivity: '5 minutes'

    authentication_backend:
      file:
        path: '/config/users_database.yml'
      password_reset:
        disable: true

    access_control:
      default_policy: 'deny'
      rules:
        - domain: '*.example.org'
          policy: 'bypass'
```

Other relevant info:
 - I have confirmed my SMTP config is working/valid
 - I have tried `authelia` and `authelia.internal` in the `traefik.http.middlewares.authelia.forwardauth.address` config.
 - The `12200:9091` port mapping is important to me; I have another container already exposing port 9091, and don't want to change it.
