### DISCUSSION TITLE
Migrate AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_CERTIFICATE_CHAIN_FILE and AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE environment variables to new jwk configuration in 4.38.0

### DISCUSSION THREAD

**Discussion by bw210343** [authelia/authelia#7905] [Q&A] [answered]
I am current using two environment variables:
```
        - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_CERTIFICATE_CHAIN_FILE
          value: "/etc/letsencrypt/live/agjei.xyz/tls.crt/cert.pem"
        - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE
          value: "/etc/letsencrypt/live/agjei.xyz/tls.key/privkey.pem"
```

There do not appear to be JWKS equivalents listed on the environment variable page @ https://www.authelia.com/configuration/methods/environment/

Reading https://www.authelia.com/blog/4.38-release-notes/ and https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#jwks it seems I might be able to use:
```
identity_providers:
  oidc:
    jwks:
      - key: {{ secret "/etc/letsencrypt/live/agjei.xyz/tls.key/privkey.pem" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/etc/letsencrypt/live/agjei.xyz/tls.crt/cert.pem" | mindent 10 "|" | msquote }}
```
However, this fails with and invalid config:
```
level=error msg="Configuration: failed to load configuration from file path(/config/configuration.yml) source: yaml: invalid map key: map[string]interface {}{\"secret \\\"/etc/letsencrypt/live/agjei.xyz/tls.key/privkey.pem\\\" | mindent 10 \\\"|\\\" | msquote\":interface {}(nil)}"
```

What should I be doing instead?
