### DISCUSSION TITLE
Access control with group policy and wildcard

### DISCUSSION THREAD

**Discussion by molitoris** [authelia/authelia#7930] [Documentation Feedback]
My goal was to restrict access for a single page ("abc.example.org") based on a group policy. Other pages should be accessible with two factors. My approach was like this.
```
# Access control
access_control:
  default_policy: deny
  rules: 
  - domain: "abc.example.org"
    subject:
    - ['group:abc']
    policy: one_factor
  
  - domain: "*.example.org"
    policy: two_factor
```
However, this only requires all users not part of the `abc` group to login with a second factor. I solved the issue by adding an additional entry which denies all users for "abc.example.org" not part of the group:
```
# Access control
access_control:
  default_policy: deny
  rules: 
  - domain: "abc.example.org"
    subject:
    - ['group:abc']
    policy: one_factor
  - domain: "abc.example.org"
    policy: 'deny'  
  - domain: "*.example.org"
    policy: two_factor
```
I belive this is a common use case to restrict a single page based on a group policy in combination with a wildcard. It would benefit the communit to have such an example in the documentation.
