### DISCUSSION TITLE
Howto create config-files for each application/service

### DISCUSSION THREAD

**Discussion by ZzenlD** [authelia/authelia#8094] [Q&A] [answered]
Hello everyone,
for better clarity, I would like to create a file in the /config/apps folder for each application configured in Authelia with eg. the name `vaultwarden.my.domain.yml` and the following content:
```yaml
# Defines the oidc client configuration of the application
oidc_client:
  - client_id: vaultwarden.my.domain
    client_name: vaultwarden
    client_secret: <client-secret>
    authorization_policy: vaultwarden_my_domain
    require_pkce: false
    redirect_uris:
      - https://vaultwarden.my.domain/oauth_callback
    scopes:
      - openid
      - profile
      - email
      - groups

# Defines who can successfully log in via oidc
authorization_policy:
  vaultwarden_my_domain:
    default_policy: deny
    rules:
      - policy: one_factor
        subject:
          - group:vaultwarden.my.domain_user

# Defines who can access which resources/paths
access_control:
  - domain:
      - vaultwarden.my.domain
    resources:
      - '^/admin.*$'
    policy: one_factor
    subject:
      - group:vaultwarden.my.domain_admin
  - domain:
      - vaultwarden.my.domain
    policy: one_factor
    subject:
      - group:vaultwarden.my.domain_user
```
This has the advantage that everything that belongs to an application can be viewed and customized in one file, without a lot of scrolling.

Problem: I cannot read the file correctly into the main configuration file. Can anyone help me? My previous attempt looks like this:
```yaml
[...]
access_control:
  default_policy: deny
  rules:
{{- range $file := glob "/config/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "access_control") }}
{{- . | toYaml | expandenv | nindent 6 }}
{{- end }}
{{- end }}

[...]
identity_providers:
  oidc:
    clients:
{{- range $file := glob "/config/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "oidc_client") }}
{{- . | toYaml | expandenv | nindent 6 }}
{{- end }}
{{- end }}

    authorization_policies:
{{- range $file := glob "/config/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "authorization_policy") }}
{{- . | toYaml | expandenv | nindent 6 }}
{{- end }}
{{- end }}
```

Thank you already for your help, you would be doing me a huge favor.

**Comment by james-d-elliott** [comment]
Have you tried using the [authelia config template](https://www.authelia.com/reference/cli/authelia/authelia_config_template/) command? Looks to me like you've used a `$` without escaping them with another `$`.

**Comment by ZzenlD** [comment]
To be honest, I haven't got through the templates yet and I'm not particularly good at Go either.

I just wanted to show with this “example code” what exactly I have in mind. The fromYaml function does not yet exist either.

I don't think it takes much to read in the file and assign it correctly, but I can't figure out how to do it.

I would really appreciate a working code, the software itself is brilliant.

**Comment by ZzenlD** [comment]
I have now customized the templates as follows (inserted the second $):
```
{{- range $$file := glob “/config/apps/*” }}
{{- with (index (fileContent $$file | fromYaml) “access_control”) }}
{{- . | toYaml | expandenv | nindent 6 }}
{{- end }}
{{- end }}
```

And then started the Authelia container in version 4.38.10 with the following command: `authelia config template --config.experimental.filters expand-env,template --config /config/configuration.yml`

However, this now issues the following error message:
```
[authelia] | panic: runtime error: invalid memory address or nil pointer dereference
[authelia] | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x561944ad9c93]
[authelia] | 
[authelia] | goroutine 1 [running]:
[authelia] | text/template.(*Template).init(...)
[authelia] | 	text/template/template.go:71
[authelia] | text/template.(*Template).Parse(0x0, {0xc000412800, 0x1625})
[authelia] | 	text/template/template.go:208 +0x33
[authelia] | github.com/authelia/authelia/v4/internal/configuration.(*TemplateBytesFilter).Filter(0xc000d05b30, {0xc000411000?, 0xc000d06360?, 0x19?})
[authelia] | 	github.com/authelia/authelia/v4/internal/configuration/koanf_provider_filtered_file.go:92 +0x4c
[authelia] | github.com/authelia/authelia/v4/internal/configuration.(*FilteredFile).ReadBytes(0xc000cb9b00)
[authelia] | 	github.com/authelia/authelia/v4/internal/configuration/koanf_provider_filtered_file.go:44 +0x94
[authelia] | github.com/authelia/authelia/v4/internal/configuration.(*FileSource).readFile(0xc000cbd4d0, {0xc000d06360, 0x19})
[authelia] | 	github.com/authelia/authelia/v4/internal/configuration/sources.go:148 +0xc9
[authelia] | github.com/authelia/authelia/v4/internal/configuration.(*FileSource).readFilesFile(...)
[authelia] | 	github.com/authelia/authelia/v4/internal/configuration/sources.go:136
[authelia] | github.com/authelia/authelia/v4/internal/configuration.(*FileSource).ReadFiles(0xc000cbd4d0)
[authelia] | 	github.com/authelia/authelia/v4/internal/configuration/sources.go:130 +0x58
[authelia] | github.com/authelia/authelia/v4/internal/commands.(*CmdCtx).ConfigTemplateRunE(0xdffa10a000000000?, 0xc000cb9bb0?, {0x0?, 0x0?, 0x0?})
[authelia] | 	github.com/authelia/authelia/v4/internal/commands/config.go:140 +0x9d
[authelia] | github.com/spf13/cobra.(*Command).execute(0xc0002bcf08, {0xc000d0e500, 0x4, 0x4})
[authelia] | 	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
[authelia] | github.com/spf13/cobra.(*Command).ExecuteC(0xc0005fa608)
[authelia] | 	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
[authelia] | github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
[authelia] | 	github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
[authelia] | main.main()
[authelia] | 	github.com/authelia/authelia/v4/cmd/authelia/main.go:10 +0x18
```
How do you debug something like this? I just don't know what to do :/

**Reply by james-d-elliott** [reply]
You'd need to provide a way for us to replicate it. Also for reference `expand-env` will be removed in an update, it's formally deprecated.

**Reply by ZzenlD** [reply]
Okay thanks for the answer, I understand that.
So I deploy Authelia via docker-compose and pass a local configuration directory:
```yaml
version: "3.9"
services:
  authelia:
    image: docker.io/authelia/authelia:4.38.10
    hostname: authelia
    read_only: true
    tmpfs:
      - /app
    security_opt:
      - no-new-privileges
    volumes:
      - ./config:/config
      - ./var:/var
    labels:
      - io.containers.autoupdate=registry
    networks:
      - proxy
    environment:
      - TZ=Europe/Berlin
      - X_AUTHELIA_CONFIG_FILTERS=expand-env,template
    restart: always

networks:
  proxy:
    external:
      name: proxy
``` 
In the directory `./config` I then store the following `configuration.yml`:
```yaml
theme: auto

log:
  level: info

totp:
  issuer: authelia.my.domain
  digits: 8
  period: 30

identity_validation:
  reset_password:
    jwt_secret: INSERT_JWT_SECRET

ntp:
  address: udp://time.cloudflare.com:123

authentication_backend:
  file:
    path: /var/users_database.yml
    watch: true

password_policy:
  standard:
    enabled: true
    min_length: 24

session:
  secret: INSERT_SECRET
  cookies:
    - domain: my.domain
      authelia_url: https://authelia.my.domain
      default_redirection_url: https://my.domain
      inactivity: 5m
      expiration: 1h
      remember_me: -1

storage:
  encryption_key: INSERT_ENCRYPTION_KEY
  local:
    path: /var/db.sqlite3

notifier:
  filesystem:
    filename: /var/notification.txt

access_control:
  default_policy: deny
  rules:
{{- range $$file := glob "/config/apps/*" }}
{{- with (index (fileContent $$file | fromYaml) "access_control") }}
{{- . | toYaml | expandenv | nindent 6 }}
{{- end }}
{{- end }}

identity_providers:
  oidc:
    hmac_secret: INSERT_HMAC_SECRET
    lifespans:
      authorize_code: 1m
      id_token: 5m
      access_token: 5m
      refresh_token: 90m
    jwks:
      - key: |
          INSERT_JWKS_KEY

    clients:
{{- range $$file := glob "/config/apps/*" }}
{{- with (index (fileContent $$file | fromYaml) "oidc_client") }}
{{- . | toYaml | expandenv | nindent 6 }}
{{- end }}
{{- end }}

    authorization_policies:
{{- range $$file := glob "/config/apps/*" }}
{{- with (index (fileContent $$file | fromYaml) "authorization_policy") }}
{{- . | toYaml | expandenv | nindent 6 }}
{{- end }}
{{- end }}
```

In the directory `./config/apps` follows a file named `<domain>.yml` for each application as mentioned above.

I hope this helps. I would be happy to give you a cafe afterwards ;)

**Reply by james-d-elliott** [reply]
I can't replicate it with this, please provide a sample of the files in the apps dir that this can be replicated with (it must be reproducible with only those files, if there are additional files not provided it will likely not be useful).

**Reply by ZzenlD** [reply]
The files in the Apps folder look like in the first post.

The entire folder structure of Authelia looks like this:
```
authelia
├── compose.yml
├── config
│   ├── apps
│   │   ├── nextcloud.my.domain.yml
│   │   └── vaultwarden.my.domain.yml
│   └── configuration.yml
└── var
    └── users_database.yml
```

The files in the ./config/apps folder look like the following example:
`vaulwarden.my.domain.yml`:
```yaml
# Defines the oidc client configuration of the application
oidc_client:
  - client_id: vaultwarden.my.domain
    client_name: vaultwarden
    client_secret: <client-secret>
    authorization_policy: vaultwarden_my_domain
    require_pkce: false
    redirect_uris:
      - https://vaultwarden.my.domain/oauth_callback
    scopes:
      - openid
      - profile
      - email
      - groups

# Defines who can successfully log in via oidc
authorization_policy:
  vaultwarden_my_domain:
    default_policy: deny
    rules:
      - policy: one_factor
        subject:
          - group:vaultwarden.my.domain_user

# Defines who can access which resources/paths
access_control:
  - domain:
      - vaultwarden.my.domain
    resources:
      - '^/admin.*$'
    policy: one_factor
    subject:
      - group:vaultwarden.my.domain_admin
  - domain:
      - vaultwarden.my.domain
    policy: one_factor
    subject:
      - group:vaultwarden.my.domain_user
```

`nextcloud.my.domain.yml`:
```yaml
# Defines the oidc client configuration of the application
oidc_client:
  - client_id: nextcloud.my.domain
    client_name: nextcloud
    client_secret: <client-secret>
    authorization_policy: nextcloud_my_domain
    require_pkce: true
    redirect_uris:
      - https://nextcloud.my.domain/apps/oidc_login/oidc
    scopes:
      - openid
      - profile
      - email
      - groups

# Defines who can successfully log in via oidc
authorization_policy:
  nextcloud_my_domain:
    default_policy: deny
    rules:
      - policy: one_factor
        subject:
          - group:nextcloud.my.domain_user

# Defines who can access which resources/paths
access_control:
  - domain:
      - nextcloud.my.domain
    policy: one_factor
    subject:
      - group:nextcloud.my.domain_user
```

The `users_database.yml` looks like this:
```yaml
users:
  User:
    disabled: false
    displayname: "Demo User"
    password: <password>
    email: <email>
    groups:
      - vaultwarden.my.domain_user
      - nextcloud.my.domain_user
```

I hope this helps, if not I will create a public Git repository with exactly these files and their content. More files are actually not involved.

Thanks for the interest in my problem, that is not self-evident :)

**Reply by james-d-elliott** [reply]
I've fixed the issue making it hard to debug, the issue is that `glob` is not a templating function listed in the official go list or our list.

**Reply by ZzenlD** [reply]
Oh wow thank you very much. How do I have to adjust my configuration for this to work?

**Reply by nightah** [reply]
The issue that was resolved was to address the nil pointer error you would have seen.

Currently there isn't a mechanism to iterate over a glob pattern of files for the purposes you intend.

We are open to adding a new template function in the next minor release, time permitting.

We will keep in touch as we progress said implementation if you're happy to test it?

**Reply by ZzenlD** [reply]
That would be great, of course I'd love to test it. Many thanks for the great help.

**Comment by james-d-elliott** [comment]
Would you mind giving [feat-template-glob](https://github.com/authelia/authelia/pull/8494) a try?

Example here (using `glob`):

https://github.com/authelia/authelia/blob/26a00197743338a1fff13b712e5ce52864545ef0/internal/configuration/test_resources/config_glob.yml

The docs for `glob` are here:

https://github.com/authelia/authelia/blob/26a00197743338a1fff13b712e5ce52864545ef0/docs/content/reference/guides/templating.md#glob

Example here (using `walk`):

https://github.com/authelia/authelia/blob/26a00197743338a1fff13b712e5ce52864545ef0/internal/configuration/test_resources/config_walk.yml

The docs for `walk` are here:

https://github.com/authelia/authelia/blob/26a00197743338a1fff13b712e5ce52864545ef0/docs/content/reference/guides/templating.md#walk

**Reply by james-d-elliott** [reply]
@ZzenlD

**Reply by ZzenlD** [reply]
Merry Christmas and thanks a lot, i will try that after the holiday days :)

**Reply by ZzenlD** [reply]
I wanted to start testing today, but the tag does not seem to exist in Docker Hub, so `docker pull authelia/authelia:feat-template-glob` fails.

**Reply by james-d-elliott** [reply, marked as answer]
It was merged into 4.38.18

**Reply by ZzenlD** [reply]
Thanks for the tip. Now it works with the configuration files mentioned above and the following templates:
```yaml
---
[...]
access_control:
  default_policy: deny
  rules:
{{- range (glob "/config/configs/*.yml") }}
{{- with (index (fileContent . | fromYaml) "access_control") }}
{{ . | toYaml | nindent 6 }}
{{- end }}
{{- end }}

[...]
identity_providers:
  oidc:
    clients:
{{- range (glob "/config/configs/*.yml") }}
{{- with (index (fileContent . | fromYaml) "oidc_client") }}
{{ . | toYaml | nindent 6 }}
{{- end }}
{{- end }}

    authorization_policies:
{{- range (glob "/config/configs/*.yml") }}
{{- with (index (fileContent . | fromYaml) "authorization_policy") }}
{{ . | toYaml | nindent 6 }}
{{- end }}
{{- end }}
```

The only “unpleasant” thing is that a blank line is always inserted when the config is generated, for example:
```yaml
identity_providers:
  oidc:
    clients:

      - client_id: nextcloud
        client_name: Nextcloud
        client_secret: <secret>
        require_pkce: true
        redirect_uris:
          - https://<domain>
        scopes:
          - openid
          - profile
          - email
          - groups

      - client_id: forgejo
        client_name: Forgejo
        client_secret: <secret>
        require_pkce: true
        redirect_uris:
          - https://<domain>
        scopes:
          - openid
          - profile
          - email
          - groups

```

Maybe I have overlooked something and someone can help me how to avoid the blank line :)
If someone has a suggestion for how to write the template even easier, let me know.

**Reply by james-d-elliott** [reply]
You can use `{{-` and `-}}` to control new lines before and after. See the go docs on this: https://pkg.go.dev/text/template#hdr-Text_and_spaces

**Comment by vadella** [comment]
Hello,

This solution works for me with 2 caveat. 
*   If you have a `{{ secret <secret_file> }}` in the secondary configuration it does not expand that one
*  If you have the secret code in it, you need to escape any `$`

`/etc/authelia/configuration.yml.j2`
``` yaml
...

identity_providers:
  oidc:
    hmac_secret: '{{ "{{" }} secret "{{ authelia_config.secrets_dir }}/hmac_secret" {{ "}}" }}'
    jwks:
      - use: 'sig'
        key: {{ "{{" }} secret "{{ authelia_config.secrets_dir }}/oidc_private_key" | mindent 10 "|" | msquote {{ "}}" }}
    clients:
{{ "{{-" }} range $file := glob "{{ authelia_config.config_dir }}/apps/*" {{ "}}" }}
{{ "{{-" }} with (index (fileContent $file | fromYaml) "oidc_client") {{ "}}" }}
{{ "{{-" }} . | toYaml | expandenv | nindent 6 {{ "}}" }}
{{ "{{-" }} end {{ "}}" }}
{{ "{{-" }} end {{ "}}" }}

...
```

`/etc/authelia/apps/forgejo_authelia.yml.j2`

``` yaml
oidc_client:
  - client_id: 'forgejo'
    client_name: 'Forgejo'
    client_secret:  '{{ "{{" }} secret "{{ authelia_config.secrets_dir }}/oidc_clientsecret_forgejo  " {{ "}}" }}'
...
```
(I use Ansible, to write these to the authelia server, hence the `{{ "{{" }}`)

`authelia config template --config.experimental.filters=template --config=/etc/authelia/configuration.yml` results in 
``` yaml
...
    clients:
      - access_token_signed_response_alg: none
        authorization_policy: one_factor
        claims_policy: forgejo
        client_id: forgejo
        client_name: Forgejo
        client_secret: '{{ secret "/etc/authelia/secrets/oidc_clientsecret_forgejo }}'
...
```

Instead I need to do `client_secret: '{{ authelia_config.oidc_clientsecret_forgejo  | replace("$", "$$")}}'`. It needs the double `$` to escape it and prevent the authelia templating to mangle it.

**Reply by james-d-elliott** [reply]
We will not be supporting `expand-env` going forward. Would suggest instead of escaping the `$` to not include `expand-env` at all. 

As long as what is provided to authelia itself is `client_secret: '{{ secret "/etc/authelia/secrets/oidc_clientsecret_forgejo" }}` and have `template` filter enabled, if `/etc/authelia/secrets/oidc_clientsecret_forgejo` is readable by the Authelia user and it contains `$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng` then Authelia will be happy with that.

**Reply by vadella** [reply]
Thank you for the swift reply. I removed the `expand-env`, but the issue remains the same. 
`authelia config template --config.experimental.filters=template --config=/etc/authelia/configuration.yml` still shows `client_secret: '{{ secret '/etc/authelia/secrets/oidc_clientsecret_forgejo' }}` while the other secrets are changed to the contents of their secret file.

I get following message in the systemctl status: 
`identity_providers: oidc: clients: client 'forgejo': option 'client_secret' is plaintext but for clients not using any endpoint authentication method 'client_secret_jwt' it should be a hashed value as plaintext values are deprecated with the exception of 'client_secret_jwt' and will be removed in the near future`

which indicates to me that authelia uses the string `"client_secret: '{{ secret "/etc/authelia/secrets/oidc_clientsecret_forgejo"` as `client_secret`, instead of replacing it with the value in the file.


If I remove the `'` (`client_secret:  {{ secret "/etc/authelia/secrets/oidc_clientsecret_forgejo }}`), this changes to the following error message `template: config.template:117:37: executing "config.template" at <fromYaml>: error calling fromYaml: yaml: cannot use 'map[string]interface {}{"secret \"/etc/authelia/secrets/oidc_clientsecret_forgejo":interface {}(nil)}' as a map key; try decoding into yaml.Node`

`sudo -u authelia cat /etc/authelia/secrets/oidc_clientsecret_forgejo` shows `$pbkdf2-sha512$310000$/4aBS.....Ar`


What did change was that I indeed do no longer need to escape te `$` if I want to use the secret in the secondary config file, so that's an improvement at least.

**Reply by james-d-elliott** [reply]
What does the part you're having issues with look like before running `authelia config template`?

**Comment by vadella** [comment]
` /etc/authelia/apps/forgejo.authelia.yml` contains 

``` yaml
oidc_client:
  - client_id: 'forgejo'
    client_name: 'Forgejo'
    client_secret:  '{{ secret "/etc/authelia/secrets/oidc_clientsecret_forgejo }}'
...
```

**Reply by james-d-elliott** [reply]
You're missing a closing `"`.

**Reply by vadella** [reply]
I get the same error with the closing `"`

**Reply by james-d-elliott** [reply]
Show the full template?

**Reply by vadella** [reply]
a cleaned up `/etc/authelia/configuration`

``` yaml
---
default_2fa_method: totp
server:
  address: 'tcp://auth.example.com:9091/'
  disable_healthcheck: false
  tls:
    key: '/etc/letsencrypt/live/auth/privkey.pem'
    certificate: '/etc/letsencrypt/live/auth/fullchain.pem'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
telemetry:
  metrics:
    enabled: true
    address: 'tcp://auth.example.com:9959/metrics'
totp:
  disable: false
  issuer: 'Authelia'
webauthn:
  disable: true
duo_api:
  disable: true
identity_validation:
  reset_password:
    jwt_secret: '{{ secret "/etc/authelia/secrets/jwt_secret" }}'
definitions:
  network:
    internal:
      - '192.168.1.0/24'
authentication_backend:
  password_change:
    disable: true
  password_reset:
    disable: true
  ldap:
    address: 'ldaps://lldap.example.com:6360'
    implementation: 'lldap'
    tls:
      server_name: 'lldap.example.com'
      skip_verify: false
    base_dn: 'dc=example,dc=com'
    additional_users_dn: 'ou=people'
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    additional_groups_dn: 'ou=groups'
    groups_filter: (&(member={username_attribute})(objectClass=groupOfNames))
    user: 'uid=bind_user,ou=people,dc=example,dc=com'
    password: '{{ secret "/etc/authelia/secrets/lldap_bind_pw" }}'
    attributes:
      mail: 'mail'
      member_of: 'memberOf'
      username: 'uid'
      display_name: 'displayName'
      group_name: cn
      extra:
{{- range $file := glob "/etc/authelia/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "ldap_attributes") }}
{{- . | toYaml | nindent 8 }}
{{- end }}
{{- end }}
access_control:
  default_policy: 'one_factor'
  rules:
{{- range $file := glob "/etc/authelia/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "access_control") }}
{{- . | toYaml | nindent 6 }}
{{- end }}
{{- end }}
session:
  secret: '{{ secret "/etc/authelia/secrets/session_secret" }}'
  cookies:
    - name: 'authelia_session'
      domain: example.com
      authelia_url: 'https://auth.example.com'
      same_site: 'lax'
regulation:
  modes:
    - 'user'
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'
storage:
  encryption_key: '{{ secret "/etc/authelia/secrets/encryption_key" }}'
  local:
    path: '/etc/authelia/db.sqlite3'
log:
  level: 'debug'
  format: 'json'
  file_path: '/etc/authelia/authelia.log'
  keep_stdout: false
notifier:
  smtp:
    ...
identity_providers:
  oidc:
    hmac_secret: '{{ secret "/etc/authelia/secrets/hmac_secret" }}'
    jwks:
      - use: 'sig'
        key: {{ secret "/etc/authelia/secrets/oidc_private_key" | mindent 10 "|" | msquote }}
    clients:
{{- range $file := glob "/etc/authelia/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "oidc_client") }}
{{- . | toYaml | nindent 6 }}
{{- end }}
{{- end }}
    authorization_policies:
{{- range $file := glob "/etc/authelia/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "authorization_policy") }}
{{- . | toYaml | nindent 6 }}
{{- end }}
{{- end }}
    scopes:
{{- range $file := glob "/etc/authelia/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "oidc_scopes") }}
{{- . | toYaml | nindent 6 }}
{{- end }}
{{- end }}
    claims_policies:
{{- range $file := glob "/etc/authelia/apps/*" }}
{{- with (index (fileContent $file | fromYaml) "oidc_claims_policies") }}
{{- . | toYaml | nindent 6 }}
{{- end }}
{{- end }}
```

and `/etc/authelia/apps/forgejo.authelia.yml`
``` yaml
oidc_client:
  - client_id: 'forgejo'
    client_name: 'Forgejo'
    client_secret:  '{{ secret "/etc/authelia/secrets/oidc_clientsecret_forgejo" }}'
    public: false
    authorization_policy: 'one_factor'
    require_pkce: true
    pkce_challenge_method: 'S256'
    redirect_uris:
      - 'https://forgejo.example.com/user/oauth2/authelia/callback'
    scopes:
      - 'openid'
      - 'email'
      - 'profile'
      - 'groups'
      - 'forgejo'
    response_types:
      - 'code'
    consent_mode: 'implicit'
    grant_types:
      - 'authorization_code'
    access_token_signed_response_alg: 'none'
    userinfo_signed_response_alg: 'none'
    token_endpoint_auth_method: 'client_secret_basic'
    claims_policy: 'forgejo'
authorization_policy:
  forgejo:
    default_policy: deny
    rules:
      - policy: one_factor
        subject:
          - group:forgejo_user
          - group:forgejo_admin
oidc_scopes:
  forgejo:
    claims:
      - sshpublickey
oidc_claims_policies:
  forgejo:
    custom_claims:
      sshpublickey: {}
access_control:
  - domain:
      - forgejo.example.com
    policy: one_factor
    subject:
      - group:forgejo_user
      - group:forgejo_admin
ldap_attributes:
  sshpublickey:
      name: 'sshpublickey'
      multi_valued: true
      value_type: 'string'
```


There is a secondary issue with this config, that forgejo doesn't seem to get the `group `or `sshpublickey `of the user, but I will log a separate issue/question for that
