### DISCUSSION TITLE
WRONGPASS with redis 7

### DISCUSSION THREAD

**Discussion by stone-w4tch3r** [authelia/authelia#8111] [Q&A] [answered]
I try to configure redis for authelia. But no matter what I do I get WRONGPASS error.

My docker-compose.yml
```yaml
services:

  authelia:
    image: authelia/authelia:latest
    restart: unless-stopped
    container_name: authelia-container
    depends_on:
      - authelia-postgres
      - authelia-redis
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
    volumes:
      - ./configuration.yml:/config/configuration.yml
      - ./users_database.yaml:/config/users_database.yaml
    env_file:
      - .env

  authelia-redis:
    image: redis:7
    restart: unless-stopped
    expose:
      - 6379
    container_name: authelia-redis-container
    command: "redis-server --save 60 1 --loglevel warning --requirepass 1234" #TODO: change password
    volumes:
      - ./redis:/data
```

And related section of configuration.yml
```yaml
session:
  domain: 'mydomain.com'

  redis:
    host: 'authelia-redis-container'
    port: 6379
    # username: 'default' # I tried to add/remove this line
    password: '1234'
```

Every time I do `docker compose up`, I see this error in logs:
```
authelia-container           | time="2024-10-26T20:42:08Z" level=fatal msg="redis connection error: WRONGPASS invalid username-password pair or user is disabled." stack="github.com/authelia/authelia/v4/internal/commands/context.go:150 (*CmdCtx).LoadProviders\ngithub.com/authelia/authelia/v4/internal/commands/root.go:72     (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal
```

I tried to hardcode password to 1234, tried to explicitly set user as "default" in configuration.yml.

For debugging I entered redis container and verified that user-password pair is correct.
```
# redis-cli
127.0.0.1:6379> AUTH default 1234
OK
```

---
So am I doing something wrong, or this is a bug?

**Comment by james-d-elliott** [comment, marked as answer]
I can't replicate this using the example redis container you provided on the same network as a redis install with the below config:


```yaml
session:
  domain: 'mydomain.com'

  redis:
    host: 'authelia-redis-container'
    port: 6379
    username: 'default'
    password: '1234'
```
