### DISCUSSION TITLE
Remote-Name and Remote-Email headers missing when using Forward-Auth on 2 different Traefik hosts

### DISCUSSION THREAD

**Discussion by flosoft** [authelia/authelia#8121] [Q&A] [answered]
For some reason, when running Authelia across 2 hosts through Traefik, I do not get **Remote-Name** and **Remote-Email** headers on the second (remote) host when using Forward Auth.
I do get these 2 headers on the host that is running Authelia on the same docker.

Everything else seems to work just fine in terms of authentication.

### Responses
DebugApp1 on HostA (the host running Authelia)
```
Name: debug1
Hostname: 967319bc5356
IP: 127.0.0.1
IP: ::1
IP: 172.18.0.7
RemoteAddr: 172.18.0.3:60994
GET / HTTP/1.1
Host: debug2.jensen.ovh
[...]
Cookie: authelia_session=[snip/]
[...]
Remote-Email: [valid email address here]
Remote-Groups: admins,dev
Remote-Name: [valid name here]
Remote-User: florian
[...]
X-Forwarded-For: [ip address of client here]
X-Forwarded-Host: debug1.example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: e2aafb1d5652
X-Real-Ip: [ip address of client here]
```

DebugApp2 on HostB (the host remotely connecting to Authelia)
```
Name: debug
Hostname: 0cf4c532ba67
IP: 127.0.0.1
IP: ::1
IP: 172.25.0.10
RemoteAddr: 172.25.0.3:34530
GET / HTTP/1.1
Host: debug2.example.com
[...]
Cookie: authelia_session=[snip/]
[...]
Remote-Groups: admins,dev
Remote-User: florian
[...]
X-Forwarded-For: [ip address of client here]
X-Forwarded-Host: debug2.example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: 0f87d0dd9c72
X-Real-Ip: [ip address of client here]
```

### The configurations
I'm running Authelia in the following environment with 2 docker hosts:

- HostA
 - authelia
 - debugapp1
- HostB
 - debugapp2

The Traefik Configuration on **Host A**:
```
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    [...]
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.example.com`)'
      [...]
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/authz/forward-auth'  # yamllint disable-line rule:line-length
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
```

The DebugApp1 configuration on **Host A**:
```
services:
  whoami:
    image: traefik/whoami
    command:
       # It tells whoami to start listening on 2001 instead of 80
       - --port=80
       - --name=debug
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.debug.rule=Host(`debug1.example.com`)'
      [...]
      - "traefik.http.routers.debug.middlewares=authelia"
```

The DebugApp2 configuration on **Host B**:
```
services:
  whoami:
    image: traefik/whoami
    command:
       # It tells whoami to start listening on 2001 instead of 80
       - --port=80
       - --name=debug
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.debug.rule=Host(`debug2.example.com`)'
       - 'traefik.http.middlewares.authelia.forwardauth.address=https://auth.example.com/api/authz/forward-auth'  # yamllint disable-line rule:line-length
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
      [...]
      - "traefik.http.routers.debug.middlewares=authelia"

```

As I have the full authResponseHeaders on both hosts, I'm a bit stumped as to where the 2 fields are going missing, especially as the fields are showing on Host A.
