### DISCUSSION TITLE
Authelia + Caddy - login redirects back to login

### DISCUSSION THREAD

**Discussion by ctag** [authelia/authelia#8131] [Troubleshooting] [answered]
Hi,

I think I've seen similar discussions while searching my issue:
https://github.com/authelia/authelia/discussions/5792
https://github.com/authelia/authelia/discussions/6032
But I don't see an answer that works for me.

This setup has been working for a couple weeks now, but yesterday I restarted the compose file with authelia in it, and now I'm unable to log in. Entering a wrong password returns "incorrect password" and 401 in the network monitor. Entering the correct password just redirects me back to the login screen, with a `200 firstfactor` in the network log.

![image](https://github.com/user-attachments/assets/8946e0a0-0e38-4075-b416-b732900b0d6a)

I have Authelia paired with Caddy-docker-proxy in a docker compose:
```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9.1-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    networks:
      caddy: null
      nextcloud-aio: null
      authelia: null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - /mnt/data/caddy/caddyfile/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
  authelia:
    image: authelia/authelia:latest
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - authelia
      - caddy
    labels:
      caddy: auth.csb.sh
      caddy.reverse_proxy: "{{upstreams 9091}}"
    expose:
      - 9091
    volumes:
      - /mnt/data/authelia/config:/config
      - /mnt/data/authelia/secrets:/config/secrets
    environment:
      AUTHELIA_JWT_SECRET_FILE: /config/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/SESSION_SECRET
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /config/secrets/SMTP_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /config/secrets/REDIS_PASSWORD
  redis:
    image: redis:7
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass
      blah
    networks:
      - authelia
    volumes:
      - redis_data:/data
networks:
  authelia: null
  caddy:
    external: true
  nextcloud-aio:
    external: true
volumes:
  caddy_data: {}
  redis_data: {}
```

Authelia config:
```
# Miscellaneous https://www.authelia.com/configuration/miscellaneous/introduction/
# Set also AUTHELIA_JWT_SECRET_FILE
theme: auto
default_redirection_url: https://auth.csb.sh/

# First Factor https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  file:
    path: /config/users_database.yml

# Second Factor https://www.authelia.com/configuration/second-factor/introduction/
totp:
  issuer: 'auth.csb.sh'

# Security https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: two_factor

# Session https://www.authelia.com/configuration/session/introduction/
# Set also AUTHELIA_SESSION_SECRET_FILE
session:
  domain: csb.sh
  remember_me: '12M'
  # https://www.authelia.com/configuration/session/redis/
  # Set also AUTHELIA_SESSION_REDIS_PASSWORD_FILE if appropriate
  redis:
    host: redis
    port: 6379

# Storage https://www.authelia.com/configuration/storage/postgres/
# Set also AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
# Set also AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
storage:
  local:
    path: '/config/db.sqlite3'
#  postgres:
#    host: database
#    database: authelia
#    username: authelia

# SMTP Notifier https://www.authelia.com/configuration/notifications/smtp/
# Set also AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
notifier:
  smtp:
    host: smtp.blah.com
    port: 465
    username: blah
    sender: "Authelia <>"
```

In my caddyfile:
```
(fauth) {
        forward_auth {args[0]} authelia:9091 {
                uri /api/verify?rd=https://auth.csb.sh
                copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
        }
}
```

And then in a given app's docker compose:
```
  web-nginx:
    image: cthulhoo/ttrss-web-nginx:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8280:80
      #- ${HTTP_PORT}:80
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app
    networks:
      - caddy
      - default
    labels:
      caddy: rss.csb.sh
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.import: fauth *
```
