### DISCUSSION TITLE
Bypass policy with '#' in url

### DISCUSSION THREAD

**Discussion by Himlol** [authelia/authelia#8169] [Q&A] [answered]
Hello

I'm trying to add a bypass policy for access_control. Here is a piece of the config:
```
access_control:
  default_policy: deny
  rules:
  - domain: 'afine.my-domain'
    resources:
    - '^/share/'
    policy: bypass
  - domain: 'vw.my-domain'
    resources:
    - '^/#/send/'
    policy: bypass
  - domain: '*.my-domain'
    policy: two_factor
   ```
I noticed that this doesn't work if the url contains a "#" character. I tried using the same encoding replacing "#" with "%23", but it still doesn't work.
Am I doing something wrong or is there something wrong with Authelia?
Has anyone encountered a similar case?

authelia version 4.38.10
