### DISCUSSION TITLE
Redis Sentinel configuration

### DISCUSSION THREAD

**Discussion by djjudas21** [authelia/authelia#8220] [Q&A] [answered]
I'm attempting to configure my Authelia deployment to work with a Redis Sentinel deployment which I have done with [OT Redis Operator](https://github.com/OT-CONTAINER-KIT/redis-operator). I'm new to Redis Sentinel but my deployment has created the following pods and services:

```
[jonathan@latitude authelia]$ kubectl get po
NAME                        READY   STATUS             RESTARTS        AGE
authelia-59db975c8f-jlpq9   0/1     CrashLoopBackOff   5 (20s ago)     3m35s
authelia-redis-0            2/2     Running            0               10m
authelia-redis-1            2/2     Running            0               10m
authelia-redis-2            2/2     Running            0               10m
authelia-redis-sentinel-0   1/1     Running            0               9m43s
authelia-redis-sentinel-1   1/1     Running            0               9m40s
authelia-redis-sentinel-2   1/1     Running            0               9m37s
lldap-79684474c9-4jwsv      1/1     Running            1 (25d ago)     39d
lldap-79684474c9-jj24x      1/1     Running            1 (25d ago)     39d
lldap-mariadb-0             1/1     Running            2 (6d20h ago)   55d
```

```
[jonathan@latitude authelia]$ kubectl get svc
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
authelia                             ClusterIP   10.152.183.41    <none>        80/TCP,9959/TCP     4d
authelia-redis                       ClusterIP   10.152.183.171   <none>        6379/TCP,9121/TCP   10m
authelia-redis-additional            ClusterIP   10.152.183.97    <none>        6379/TCP            10m
authelia-redis-headless              ClusterIP   None             <none>        6379/TCP            10m
authelia-redis-sentinel              ClusterIP   10.152.183.122   <none>        26379/TCP           9m49s
authelia-redis-sentinel-additional   ClusterIP   10.152.183.206   <none>        26379/TCP           9m49s
authelia-redis-sentinel-headless     ClusterIP   None             <none>        26379/TCP           9m50s
lldap-http                           ClusterIP   10.152.183.249   <none>        17170/TCP           223d
lldap-ldap                           ClusterIP   10.152.183.133   <none>        3890/TCP,6360/TCP   223d
lldap-mariadb                        ClusterIP   10.152.183.188   <none>        3306/TCP            223d
```

So, I have configured Authelia by setting the following in my `values.yaml`:

```yaml
    ##
    ## Redis Provider
    ##
    ## Important: Kubernetes (or HA) users must read https://www.authelia.com/overview/authorization/statelessness/
    ##
    ## The redis connection details
    redis:
      enabled: true
      deploy: false
      enabledSecret: false
      #host: authelia-redis
      port: 6379

      ## This is the Redis DB Index https://redis.io/commands/select (sometimes referred to as database number, DB, etc).
      database_index: 0

      ## The maximum number of concurrent active connections to Redis.
      maximum_active_connections: 8

      ## The target number of idle connections to have open ready for work. Useful when opening connections is slow.
      minimum_idle_connections: 0

      ## The Redis HA configuration options.
      ## This provides specific options to Redis Sentinel, sentinel_name must be defined (Master Name).
      high_availability:
        enabled: true
        enabledSecret: false
        ## Sentinel Name / Master Name
        sentinel_name: authelia-redis-sentinel.auth.svc.cluster.local

        ## The additional nodes to pre-seed the redis provider with (for sentinel).
        ## If the host in the above section is defined, it will be combined with this list to connect to sentinel.
        ## For high availability to be used you must have either defined; the host above or at least one node below.
        nodes: []
        # nodes:
        #   - host: 'sentinel-0.databases.svc.cluster.local'
        #     port: 26379
        #   - host: 'sentinel-1.databases.svc.cluster.local'
        #     port: 26379

        ## Choose the host with the lowest latency.
        route_by_latency: false

        ## Choose the host randomly.
        route_randomly: false
```

My understanding is that Authelia should query the Sentinel service to discover the actual Redis server(s). This seems to be failing, here's the trace log from Authelia:

```
time="2024-11-10T20:23:43Z" level=debug msg="Loaded Configuration Sources" caller="github.com/authelia/authelia/v4/internal/commands/context.go:266 (*CmdCtx).LogConfigure" files="[/configuration.yaml]" filters="[template]"
time="2024-11-10T20:23:43Z" level=debug msg="Logging Initialized" caller="github.com/authelia/authelia/v4/internal/commands/context.go:267 (*CmdCtx).LogConfigure" fields.level=trace file= format=text keep_stdout=true
time="2024-11-10T20:23:43Z" level=debug msg="Process user information" caller="github.com/authelia/authelia/v4/internal/commands/context.go:307 (*CmdCtx).LogProcessCurrentUserRunE" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
time="2024-11-10T20:23:43Z" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'two_factor' is going to be applied to all requests" caller="github.com/authelia/authelia/v4/internal/commands/context.go:317 (*CmdCtx).ConfigValidateLogRunE"
time="2024-11-10T20:23:43Z" level=info msg="Authelia v4.38.16 is starting" caller="github.com/authelia/authelia/v4/internal/commands/root.go:62 (*CmdCtx).RootRunE"
time="2024-11-10T20:23:43Z" level=info msg="Log severity set to trace" caller="github.com/authelia/authelia/v4/internal/logging/logger.go:93 setLevelStr"
time="2024-11-10T20:23:43Z" level=trace msg="Starting scan of directory  for certificates" caller="github.com/authelia/authelia/v4/internal/utils/crypto.go:350 NewX509CertPool"
time="2024-11-10T20:23:44Z" level=trace msg="sentinel: GetMasterAddrByName master=\"authelia-redis-sentinel.auth.svc.cluster.local\" failed: dial tcp: lookup redis.databases.svc.cluster.local on 10.152.183.10:53: no such host" caller="github.com/redis/go-redis/v9@v9.5.3/sentinel.go:558 (*sentinelFailover).MasterAddr"
time="2024-11-10T20:23:44Z" level=fatal msg="redis connection error: redis: all sentinels specified in configuration are unreachable" caller="github.com/authelia/authelia/v4/internal/commands/context.go:150 (*CmdCtx).LoadProviders" stack="github.com/authelia/authelia/v4/internal/commands/context.go:150 (*CmdCtx).LoadProviders\ngithub.com/authelia/authelia/v4/internal/commands/root.go:72     (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
```

Something looks wrong here. `sentinel: GetMasterAddrByName master=\"authelia-redis-sentinel.auth.svc.cluster.local\" failed: dial tcp: lookup redis.databases.svc.cluster.local on 10.152.183.10:53: no such host` looks like it is picking up the Sentinel name I have set, but then using the wrong name in the DNS lookup. Is this a misconfiguration on my part, or a bug? Thanks

**Comment by james-d-elliott** [comment, marked as answer]
Your DNS server at `10.152.183.10` doesn't seem to be able to resolve the hostname `redis.databases.svc.cluster.local`:

`lookup redis.databases.svc.cluster.local on 10.152.183.10:53: no such host`

Looks like there's some confusion here because that service doesn't exist, I think you're conflating the `sentinel_name` which is required to perform discovery after connecting to a sentinel or redis node. You need to configure `host` to `authelia-redis-sentinel.auth.svc.cluster.local` and port to `26379` I believe, then adjust the `sentinel_name` to the correct name for the sentinel cluster you've configured.

**Comment by djjudas21** [comment]
Thanks for the explanation. I've now set my Authelia config as you describe, referencing the Sentinel as the `host` and providing the cluster name in `sentinel_name`. It now starts up correctly.

```yaml
    ##
    ## Redis Provider
    ##
    ## Important: Kubernetes (or HA) users must read https://www.authelia.com/overview/authorization/statelessness/
    ##
    ## The redis connection details
    redis:
      enabled: true
      deploy: false
      enabledSecret: false
      host: authelia-redis-sentinel.auth.svc.cluster.local
      port: 26379

      ## This is the Redis DB Index https://redis.io/commands/select (sometimes referred to as database number, DB, etc).
      database_index: 0

      ## The maximum number of concurrent active connections to Redis.
      maximum_active_connections: 8

      ## The target number of idle connections to have open ready for work. Useful when opening connections is slow.
      minimum_idle_connections: 0

      ## The Redis HA configuration options.
      ## This provides specific options to Redis Sentinel, sentinel_name must be defined (Master Name).
      high_availability:
        enabled: true
        enabledSecret: false
        ## Sentinel Name / Master Name
        sentinel_name: myMaster

        ## The additional nodes to pre-seed the redis provider with (for sentinel).
        ## If the host in the above section is defined, it will be combined with this list to connect to sentinel.
        ## For high availability to be used you must have either defined; the host above or at least one node below.
        nodes: []
        # nodes:
        #   - host: 'sentinel-0.databases.svc.cluster.local'
        #     port: 26379
        #   - host: 'sentinel-1.databases.svc.cluster.local'
        #     port: 26379

        ## Choose the host with the lowest latency.
        route_by_latency: false

        ## Choose the host randomly.
        route_randomly: false
```

I did note, however, that setting `sentinel_name` to something incorrect still returns `redis connection error: redis: all sentinels specified in configuration are unreachable` even if the Sentinel hostname/port is correct and it's a config error rather than a network problem. Not sure if you can easily improve this error or if it's just returned from the redis lib?

Anyway, my installation is working now - thanks for your help.
