### DISCUSSION TITLE
Can't get authelia to work

### DISCUSSION THREAD

**Discussion by leonio94** [authelia/authelia#8331] [Q&A] [answered]
Hello,

I'm new to traefik and authelia. I managed to configure reverse proxy via traefik for some services, guacamole for external access, any many other services routed internally using local dns added in pihole.

I wanted to configure two factor authentication to guacamole using authelia. Yes I know that I can configure MFA in guacamole itself, it is done and it works fine - I just want to test authelia for future purposes, If I will need another auth layer for app that doesn't support MFA natevily.

So I followed few YT tutorials and github repos and managed to create these configs (all secrets are replaced, all IPs and FQDNs are not real ofc):

authelia config:
```
---
###############################################################
#                   Authelia configuration                    #
###############################################################
jwt_secret: #SECRET
default_redirection_url: https://auth.mydomain.ovh    ### add your domain of autehlia here
log:
  level: debug

totp:
  issuer: mydomain.ovh ### your plain domain

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: "*.mydomain.ovh"
      policy: bypass # JUST FOR TESTS

session:
  name: authelia_session
  domain: mydomain.ovh
  secret: #SECRET
  expiration: 1h
  inactivity: 5m
  remember_me_duration:  1M

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
# generate with 'docker run authelia/authelia:latest authelia crypto rand --length 128 --charset alphanumeric'
  encryption_key: #SECRET
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: #SECRET
    sender: Authelia <test.mail@gmail.com>
    subject: "[Authelia] {title}"
  # For testing purpose, notifications can be sent in a file. 
  # filesystem:
  #   filename: /config/notification.txt
```

traefik and authelia compose:
```
---
services:
  traefik:
    image: docker.io/library/traefik:v3.2.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - /home/docker/traefik/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /home/docker/traefik/data/certs/:/var/traefik/certs/:rw
      - /home/docker/traefik/config/conf.d/:/etc/traefik/conf.d/:ro
    environment:
      - CF_DNS_API_TOKEN=#SECRET
    restart: unless-stopped
    networks:
      - proxy-network

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /home/docker/traefik/config:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.mydomain.ovh`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.certresolver=cloudflare'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.mydomain.ovh'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw
    networks:
      - proxy-network
networks:
  proxy-network:
    external: true 
```

user_database config:
```
users:
  user1: #username
    disabled: false
    displayname: "Test User"
    password: "$argon2id$v=19$m=65536,t=1,p=8$HASHEDPASS"
#   to generate the password use 'docker run authelia/authelia:latest authelia crypto hash generate argon2 --password 'password''
    email: test.email@gmail.com
    groups:
      - admin
      - user
```
Before move to guacaomle I wanted to just ensure authelia is running, so I am trying to access auth.mydomain.ovh and get this:
![image](https://github.com/user-attachments/assets/04e7559f-3bc3-4c80-ac0a-57fd40e0a13c)

In container logs each time I see the same error:
`time="2024-11-25T21:44:25+01:00" level=error msg="Error occurred retrieving user session" error="unable to retrieve session cookie domain provider: no configured session cookie domain matches the url 'https://auth.mydomain.ovh/api/state'" method=GET path=/api/state remote_ip=192.168.1.100 stack="github.com/authelia/authelia/v4/internal/handlers/handler_state.go:16 StateGET\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54 handleRouter.(*BridgeBuilder).Build.func5.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:65 SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105 SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30 SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.2/router.go:441 (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 handleRouter.LogRequest.func40\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38 RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.57.0/server.go:2385 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.57.0/workerpool.go:225 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.57.0/workerpool.go:197 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700`

in traefik:
`192.168.1.100 - - [26/Nov/2024:08:22:05 +0000] "GET / HTTP/1.1" 200 1067 "-" "-" 492 "authelia@docker" "http://172.100.1.4:9091" 0ms 192.168.1.100 - - [26/Nov/2024:08:22:05 +0000] "GET /manifest.json HTTP/1.1" 200 313 "-" "-" 493 "authelia@docker" "http://172.100.1.4:9091" 0ms 192.168.1.100 - - [26/Nov/2024:08:22:05 +0000] "GET /locales/en-US/settings.json HTTP/1.1" 200 2 "-" "-" 494 "authelia@docker" "http://172.100.1.4:9091" 0ms 192.168.1.100 - - [26/Nov/2024:08:22:05 +0000] "GET /locales/en-US/portal.json HTTP/1.1" 200 2 "-" "-" 495 "authelia@docker" "http://172.100.1.4:9091" 0ms 192.168.1.100 - - [26/Nov/2024:08:22:05 +0000] "GET /locales/en/settings.json HTTP/1.1" 200 8971 "-" "-" 496 "authelia@docker" "http://172.100.1.4:9091" 0ms 192.168.1.100 - - [26/Nov/2024:08:22:05 +0000] "GET /locales/en/portal.json HTTP/1.1" 200 7266 "-" "-" 497 "authelia@docker" "http://172.100.1.4:9091" 0ms 192.168.1.100 - - [26/Nov/2024:08:22:05 +0000] "GET /api/state HTTP/1.1" 403 13 "-" "-" 498 "authelia@docker" "http://172.100.1.4:9091" 0ms`

Nothing I do seems to have any impact on this error. It's either 404 or this, it's driving me mad. I am for sure missing something, could anyone possibly help here?

**Comment by james-d-elliott** [comment]
Show the contents of the `/home/docker/traefik/config` dir? Also what version?

**Reply by leonio94** [reply]
Traefik is in version 3.2.1, authelia latest.
This is my `/home/docker/traefik` dir tree:

.
├── compose.yml
├── config
│   ├── conf.d
│   │   ├── adguard.yaml
│   │   └── pihole.yaml
│   ├── configuration.yml
│   ├── db.sqlite3
│   ├── traefik.yaml
│   └── users_database.yml
├── data
│   └── certs
│       ├── acme.json
│       └── cloudflare-acme.json
└── logs
    └── traefik.log

In conf.d I have dynamic configuration for adguard and pihole which is probably not relevant. 
Configuration.yml is authelia config pasted above, user_database.yml and compose are also posted.

Here is my traefik static conf:
```
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# --> (Optional) Change log level and format here ...
#     - level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
log:
 level: DEBUG

# --> (Optional) Enable accesslog here ...
accesslog: {}
# <--

# --> (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  insecure: true
# <--

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # --> (Optional) Redirect all HTTP to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    # <--
  websecure:
    address: :443
    http:
      tls: {}

# -- Configure your CertificateResolver here...
certificatesResolvers:
  cloudflare:
    acme:
      email: test.mail@gmail.com  # <-- Change this to your email
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare # <-- (Optional) Change this to your DNS provider
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# --> (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true
# <--

providers:
  docker:
    exposedByDefault: false  # <-- (Optional) Change this to true if you want to expose all services
  file:
    directory: /etc/traefik
    watch: true
```
