### DISCUSSION TITLE
Cookie Flow Question

### DISCUSSION THREAD

**Discussion by mazzz1y** [authelia/authelia#8332] [Q&A] [answered]
Let's assume I have the domain: `example.com`. Here is my cookie setup, as in the documentation:

```yaml
session:
  cookies:
    - name: 'authelia_session'
      domain: 'example.com'
      authelia_url: 'https://auth.example.com'
```

I want to secure some services on the subdomains:

* `app1.example.com`: Some app using the OAuth2 flow, like Nextcloud
* `app2.example.com`: Using Traefik ForwardAuth middleware
* `app3.example.com`: Not a secured app
 
In this setup, if app3 has malicious code, it can steal the `authelia_session` cookie since Authelia sets the cookie for the whole `.example.com` domain(with a dot).

I tried to avoid this behavior by setting the cookie domain as `auth.example.com`, which makes the cookie visible only for Authelia. OAuth2 apps can still use Authelia since they're not checking the cookies themselves. But this makes ForwardAuth not work since `app2` can't access the cookie.

It seems to me that it could be possible to solve this problem like this:

```yaml
session:
  cookies:
    - name: 'authelia_session'
      domain: 'example.com' # only the root domain, without dot
      authelia_url: 'https://example.com/auth'
    - name: 'authelia_app2_session'
      domain: 'app2.example.com'
      authelia_url: 'https://example.com/auth'
```

Here, we've moved Authelia to the root domain, allowing it to set cookies on the root domain and subdomains. We set the cookie only for the root domain, making it invisible to subdomains. Additionally, we set another cookie on the ForwardAuth subdomains. This way, both OAuth2 and ForwardAuth applications can work with Authelia while preventing the malicious `app3` from stealing the cookie.

The issue I experienced is that Authelia can't set a cookie on the main domain without a dot, or I haven't figured out how to do it.

Could you help me understand if I correctly understand the authorization flow, what my issue is, and how I can resolve it?
