### DISCUSSION TITLE
Missing refresh_token even with offline_access scope

### DISCUSSION THREAD

**Discussion by sy6sy2** [authelia/authelia#8354] [Troubleshooting] [answered]
My Harbor client (and also my others clients like Grafana and Outline) does not seems to receive a refresh token from Authelia.

With trace log enable, Authelia gives me something like that:

```
authelia-1  | time="2024-11-29T12:16:17Z" level=debug msg="Access Request with id 'd4e8b12a-9a35-4a34-b973-46f461c3b245' on client with id 'harbor' has successfully been processed" caller="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:64 OpenIDConnectTokenPOST" method=POST path=/api/oidc/token remote_ip=XX.XX.XX.XX.XX
authelia-1  | time="2024-11-29T12:16:17Z" level=trace msg="Access Request with id 'd4e8b12a-9a35-4a34-b973-46f461c3b245' on client with id 'harbor' produced the following claims: map[access_token:authelia_at_************** expires_in:2591999 id_token:*********.***********.************* scope:openid profile email groups offline_access token_type:bearer]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:66 OpenIDConnectTokenPOST" method=POST path=/api/oidc/token remote_ip=XX.XX.XX.XX.XX
```

By inspecting the source code of Authelia, I expect to find something like `refresh_token:authelia_rt_**************` in the log lines but it's not.

Also, on Harbor side, this is what I get in the log when I do a `docker login` and my access token is expired:

```
harbor-core        | 2024-11-29T11:06:38Z [ERROR] [/server/middleware/security/oidc_cli.go:68][requestID="75085f71-89b3-415d-84b7-71885ce0f833"]: failed to verify secret, username: sylvain-ce, error: failed to refresh token, username: sylvain-ce, error: oauth2: token expired and refresh token is not set
```

So, based on the logs of the client and Authelia my assumption is that Authelia does not send the `refresh_token` along side the. `access_token`.
However I guess that everything is well configured...

Authelia client configuration:

```
      - client_id: 'harbor'
        client_name: 'Harbor'
        client_secret: MY_SECRET'
        public: false
        authorization_policy: 'harbor_policy'
        redirect_uris:
          - 'https://DOMAIN/c/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
          - 'offline_access'
```

Harbor configuration:

![Capture d’écran 2024-11-29 à 13 23 22](https://github.com/user-attachments/assets/70ef8588-b0fe-4782-bf03-679d0b8ebc5f)

Thank you for the help!

**Comment by james-d-elliott** [comment, marked as answer]
There's no value in issuing a token that can't be used, so you'll have to also allow the grant type to be used:

```yaml
        grant_types:
          - 'refresh_token'
          - 'authorization_code'
```

**Comment by sy6sy2** [comment]
I fell stupid now 😄 
Thank you for your fast answer and also for this great software!

Also, the Harbor integration documentation (https://www.authelia.com/integration/openid-connect/harbor/) does not talk about the refresh token stuff, but it's needed for users to have the `docker login` command to works correctly when the access token is expired (see the bottom of this page https://goharbor.io/docs/2.6.0/administration/configure-authentication/oidc-auth/).
Maybe the documentation may be updated to integrated this? I can open a PR if needed?

**Reply by james-d-elliott** [reply]
Yes please make a PR we'd greatly appreciate it. These docs are maintained by the community.

I originally made that guide but at the time it had issues with refresh tokens (it wouldn't use the new refresh token as per the spec and continually used the old one). So just ensure it works for a few refreshes before you submit.

**Reply by sy6sy2** [reply]
I just tested with really short lifespans just to test.
```
    lifespans:
      access_token: '1 minute'
      authorize_code: '1 minute'
      id_token: '1 minute'
      refresh_token: '5 minutes'
```
I executed `docker login` 3 times every 3 minutes to see if Harbor is able to refresh the token and it seems to work, so I guess that Harbor is able to store the "new" refresh token it receives during the refresh_token flow.
I also see this lines in log if I do a `docker login` once the access token is expired so it's seem to be ok!

```
harbor-core        | 2024-11-29T22:31:10Z [DEBUG] [/pkg/oidc/secret.go:87]: Verifying the secret for user: sylvain-ce
harbor-core        | 2024-11-29T22:31:10Z [DEBUG] [/pkg/oidc/secret.go:116]: Refreshing token
harbor-core        | 2024-11-29T22:31:10Z [DEBUG] [/pkg/oidc/secret.go:132]: Token refreshed and persisted
```
