### DISCUSSION TITLE
Blank emails when using Send Grid

### DISCUSSION THREAD

**Discussion by simonliu99** [authelia/authelia#8357] [Q&A] [answered]
I have Authelia set up to send emails through SendGrid but the emails I receive have no content, only a subject line. Not sure what the issue is or how to fix.

`configuration.yml:`
```
notifier:
  smtp:
    username: 'apikey'
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: 'somepassword'
    address: 'submission://smtp.sendgrid.net:587'
    sender: 'Authelia <auth@email.com>'
```
logs:
```
time="2024-11-29T17:16:26-05:00" level=error msg="Error occurred retrieving TOTP configuration for user 'simonliu': error occurred retrieving the configuration from the storage backend" error="no TOTP configuration for user" method=GET path=/api/secondfactor/totp remote_ip=192.168.0.53 stack="github.com/authelia/authelia/v4/internal/handlers/handler_sign_totp.go:44 TimeBasedOneTimePasswordGET\ngithub.com/authelia/authelia/v4/internal/middlewares/require_auth.go:19   Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54         handleRouter.(*BridgeBuilder).Build.func6.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:65        SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105       SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30        SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.2/router.go:441                           (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14    handleRouter.LogRequest.func40\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38         RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.57.0/server.go:2385                        (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.57.0/workerpool.go:225                     (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.57.0/workerpool.go:197                     (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                  goexit"
time="2024-11-29T17:16:27-05:00" level=debug msg="Sending an email to user to confirm identity for session elevation"
```

EDIT: disabling HTML content seems to have fixed the content issue
