### DISCUSSION TITLE
Feedback from a new user

### DISCUSSION THREAD

**Discussion by stone-w4tch3r** [authelia/authelia#8425] [Documentation Feedback]
Recently I learned and tried to use authelia in my selfhosting setup, and I want to share my experience. It was not great, unfortunately.

I would be glad to provide a direct contribution into documentation, but from my point of view the problem is too general/big and it can't be addressed by one person, so the only thing I can do is to write this "review".

### TL;DR
For me it took several weeks to achieve final result. Documentation is too exhaustive, I would call this approach "we think that you should learn EVERYTHING before starting". While there are attempts to create some sort of quick start guide, it still fails to be simple and step-by-step. IMHO it would be better to take "safe defaults" approach and much simplify learning curve.

Issues:

### Block 1, redundancy
You know, redundancy is good in infrastructure, but not in text ;-)

- documentation is written in such a way that on every page there are a lot of deep-level technical terms, excessive details, redundant banners that instruct user to consult multiple other articles before reading this one
- banners obsession, which leads to hard to read text. Look at [this](https://www.authelia.com/integration/prologue/get-started/#important-notes). Seriously?
- crucial information is mixed with optional. For example [this](https://www.authelia.com/integration/deployment/docker/#environment-variables) had no real value for me and I wonder why it is the first paragraph and all important stuff goes only after it
- redundant "example warnings" like [this](https://www.authelia.com/configuration/first-factor/introduction/#configuration). On every page. I got it from the beginning, and I doubt if it ever was needed to mention
- when exploring configuration options, required/important ones are not obvious, you need to read every option to understand what you can omit and what you really need. Short example at the top would make life easier, and those who need all the guts could read further. [Example](https://www.authelia.com/configuration/session/introduction/)
- too many "IMPORTANT READ THIS FIRST" blocks. Often you can encounter situation when a page contain multiple such refererences to other pages, that have similar references itself, and sometimes those references really do not contain useful information because they just lead to first article of the same article block

### Block 2. Slow quick start
- "get started" page starts to throw multiple terms into you right from the beginning, instead of ignoring techincal details and giving simple instructions
- the real quick start guide is hidden into "integration/deployment/XXX/", you need to find it manually
- good quick start guides in internet became outdated after latest changes 4.XXX
- instead of explaining what different configuration options do, which are important and which can be ignored, docker bundles just give you config files and leave you on your own

And many other smaller issues that I can't remember now.

### Block 3. Runtime issues
Now I can remember only one, but very important and severe issue
- authelia overwrites incorrect/missing config with default one. Seriously? This is very, very bad. Not only it violates [fail fast](https://martinfowler.com/ieeeSoftware/failFast.pdf), but also this behaviour is not expected and it took me a lot of time to discover this, while I tried to understand whre do all those strange values in logs came from

### Block 4. What to do?
I understand that all this may see opinionated and anyway is hard to fix, so I can suggest a couple of simple but important ideas.

1. Create real quick start guide. Ask chatgpt, it will give you better results than current ones (I checked). Or take good article from the internet and rewrite it for modern authelia. Unfortunately, I can't remember which guides I started with, but [this](https://www.smarthomebeginner.com/authelia-docker-compose-guide-2024/) one looks not bad, for example
2. Create a couple of youtube videos for different popular use cases. Seriously, youtube is a great source, but due to latest changes old guides are outdated and are hard to reimplement. At least authelia starts with a lot of warnings, which makes live harder, and sometimes it does not start at all. If you can't create a video yourself, cooperate with youtube blogers, I am sure they will be glad to help
3. Do not require your user to be authelia expert and even security expert. Use secure defaults. User has a job to do, really :D

 ### Summary
So, it was realy hard to learn and start using authelia. Being honest, I regret that I spent so much time and selected authelia for my setup. The least I can do to justify this work is to try to make authelia better for new users by writing this. I hope that it will affect current documentation approach and authelia will be more accessible in future

P.S. unfortunately, finally I decided to give up authelia in favor on more complex solution. Authelia lacks user management backend, and existing open source LDAP solutions are too exotic, unpopular and old-school. Because LDAP itself is outdated, I think

**Comment by james-d-elliott** [comment]
Thanks for taking the time to post this. I will give your review an additional response. But I have a few questions first, and some brief comments.

> authelia overwrites incorrect/missing config with default one. Seriously? This is very, very bad. Not only it violates [fail fast](https://martinfowler.com/ieeeSoftware/failFast.pdf), but also this behaviour is not expected and it took me a lot of time to discover this, while I tried to understand whre do all those strange values in logs came from

Can you please elaborate on this with a specific example? The default values are set for security reasons and do not override anything as far as I'm aware.

> Do not require your user to be authelia expert and even security expert. Use secure defaults. User has a job to do, really :D

We already set secure defaults. Though I'm somewhat confused about this feedback given the above feedback.

However there are options that have to be configured regardless. Every option that requires configuration is clearly articulated as such in the configuration docs. I can understand that there are different ways to communicate this, but there are often questions other than "is this option required?", people want to understand the effects of an option before they change it. Naturally there are always going to be clearer ways to articulate that depending on the reader and we're always aiming to improve. It's only when users decide to adjust the defaults that they would be required to read the docs more in depth about various security topics.

> Create a couple of youtube videos for different popular use cases. Seriously, youtube is a great source, but due to latest changes old guides are outdated and are hard to reimplement. At least authelia starts with a lot of warnings, which makes live harder, and sometimes it does not start at all. If you can't create a video yourself, cooperate with youtube blogers, I am sure they will be glad to help

I don't believe this would be a wise time investment, but potentially depending on the specific persons reach.

> P.S. unfortunately, finally I decided to give up authelia in favor on more complex solution. Authelia lacks user management backend, and existing open source LDAP solutions are too exotic, unpopular and old-school. Because LDAP itself is outdated, I think

I don't believe this is quite accurate regarding it being outdated. There are not really any replacement open technologies for identity storage. Many of the modern identity solutions are backed by it.

It's been around a long time but that's not necessarily a indicator of outdated technology. Many widely used technologies today are widely used specifically because the implementation details were almost perfect or have been iterated on to improve them, LDAP is one of those technologies, in my opinion.

User management is coming and there are several amazing LDAP solutions like [lldap](https://github.com/lldap/lldap) which offer the necessary function to handle this already.

**Comment by stone-w4tch3r** [comment]
I checked again, looks like overwriting config is no more an issue, at least with this setup:

<details>

<summary>more</summary>

docker-compose.yml
```yml
cat docker-compose.yml
services:

  authelia:
    image: authelia/authelia:latest
    restart: unless-stopped
    container_name: authelia-container
    depends_on:
      - authelia-postgres
      - authelia-redis
    volumes:
      - ./configuration.yml:/config/configuration.yml
      - ./users_database.yml:/config/users_database.yml
    expose:
      - 9091
    env_file:
      - .env
    networks:
      caddy_net:
      internal_net:

  authelia-postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: authelia-postgres-container
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "authelia"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      internal_net:

  authelia-redis:
    image: redis:7
    restart: unless-stopped
    expose:
      - 6379
    container_name: authelia-redis-container
    command: "redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./redis:/data
    networks:
      internal_net:

volumes:
  configuration.yml:
  users_database.yml:
  db:
  redis:

networks:
  caddy_net:
  internal_net:
```

configuration.yml
```yml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

# Miscellaneous https://www.authelia.com/configuration/miscellaneous/introduction/
theme: auto

server:
  address: 'tcp://:9091'

log:
  level: 'debug'

identity_validation:
  reset_password:
    jwt_secret: 'XXX'

# First Factor https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  file:
    path: /config/users_database.yml

# Second Factor https://www.authelia.com/configuration/second-factor/introduction/
totp:
  issuer: 'auth.example.com'
webauthn:
    disable: false
    display_name: 'Authelia'
    user_verification: 'required'
    timeout: '60s'

# Security https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: 'deny'
  rules:
    - domain: 'test1'
      policy: 'two_factor'
    - domain: 'test2'
      policy: 'two_factor'

# Session https://www.authelia.com/configuration/session/introduction/
session:
  secret: 'XXX'
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://auth.example.com'
      default_redirection_url: 'https://example.com'
  
  redis:
    host: 'authelia-redis-container'
    port: 6379
    password: 'XXX'

# Storage https://www.authelia.com/configuration/storage/postgres/
storage:
  encryption_key: 'XXX'
  postgres:
    address: 'tcp://authelia-postgres-container:5432'
    database: 'authelia'
    username: 'authelia'
    password: 'XXX'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

# SMTP Notifier https://www.authelia.com/configuration/notifications/smtp/
notifier:
  smtp:
    address: 'submission://smtp.example.com:587'
    username: 'username@example.com'
    password: 'XXX'
    sender: 'authelia@example.com'

identity_providers:
  oidc:
    hmac_secret: 'XXX'
    jwks:
      - key: |
          -----BEGIN PRIVATE KEY-----
          XXX
          -----END PRIVATE KEY-----
    clients:
      - client_id: lobe-chat
        client_name: LobeChat
        client_secret: 'XXX'
        public: False
        authorization_policy: two_factor
        redirect_uris:
          - 'https://lobechat.example.com/api/auth/callback/authelia'
        scopes:
          - openid
          - profile
          - email
        userinfo_signed_response_alg: none%                                                                             
```

logs:
```
authelia-container           | time="2024-12-13T10:50:51Z" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
authelia-container           | time="2024-12-13T10:50:51Z" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
authelia-container           | time="2024-12-13T10:50:51Z" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
authelia-container           | time="2024-12-13T10:50:51Z" level=error msg="Configuration: error occurred during unmarshalling configuration: decoding failed due to the following error(s):\n\nerror decoding 'identity_providers.oidc.jwks[0].key': could not decode to a schema.CryptographicKey: error occurred attempting to parse PEM block: either no PEM block was supplied or it was malformed" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
authelia-container           | time="2024-12-13T10:50:51Z" level=error msg="Configuration: storage: option 'encryption_key' must be 20 characters or longer" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
authelia-container           | time="2024-12-13T10:50:51Z" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
authelia-container exited with code 1
```

</details>

My particular issue was that if I misconfigured something, authelia on launched notified about error while loading, and than used some sort of default config

>However there are options that have to be configured regardless. Every option that requires configuration is clearly articulated as such in the configuration docs. I can understand that there are different ways to communicate this, but there are often questions other than "is this option required?", people want to understand the effects of an option before they change it. Naturally there are always going to be clearer ways to articulate that depending on the reader and we're always aiming to improve. It's only when users decide to adjust the defaults that they would be required to read the docs more in depth about various security topics.

Of course you need to configure something. But what I wanted to say that for me it was not apparent what I should configure, what I could just copy from examples etc

Unfortunately I am not able to help you to detect particular and concrete problems in docks, because for me it felt like one big problem. But if you want to go deeper, you may try some sort of User/Usability Testing. I asked chatgpt to describe the process as I see it:

>This process involves selecting a group of new users who will learn and set up your project using only the documentation provided. During this testing, you will observe their interactions, take notes on any challenges they face, and gather feedback on how effectively the documentation helps them achieve their objectives. You can conduct these sessions remotely or in person, allowing users to express their thoughts as they navigate through the material while you document their experiences. The insights gained from this testing will reveal areas of confusion, enabling you to enhance the clarity and effectiveness of the documentation.
