### DISCUSSION TITLE
Traefik says Authelia middleware does not exist

### DISCUSSION THREAD

**Discussion by A2va** [authelia/authelia#8452] [Q&A] [answered]
I'm trying to configure authelia but traefik displays the error `middleware "authelia@docker" does not exist`

I followed both the upcoming blog post [Authelia + Traefik Setup Guide](https://deploy-preview-8316--authelia-staging.netlify.app/blog/authelia--traefik-setup-guide/) and the lite/local examples in the repo.

Searching for the bug on the internet, I end up on authelia config and apply these tips from the [Traefik FAQ](https://www.authelia.com/integration/proxies/traefik/#middleware-autheliadocker-not-found)
but the bug still remains.

My docker compose is:
```yaml
services:
  traefik:
    image: traefik:v3
    container_name: traefik
    depends_on:
      - authelia
    command:
      - --api.dashboard=true
      - --log.level=INFO
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entryPoint.permanent=true
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.domains[0].main=a2va.dev
      - --entrypoints.https.http.tls.domains[0].sans=*.a2va.dev
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --certificatesresolvers.cloudflare.acme.storage=acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      proxy: {}
      authelia:
        aliases:
          - 'auth.a2va.dev'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
    environment:
      - CF_API_EMAIL=${EMAIL}
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - PUID=${UID}
      - PGID=${GID}
      - TZ='Europe/Paris'

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token=${CLOUDFLARED_TOKEN}
    environment:
      - PUID=${UID}
      - PGID=${GID}
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - proxy

  authelia:
    image: authelia/authelia:4.38.17
    container_name: authelia
    volumes:
      - ./authelia/secrets:/secrets:ro
      - ./authelia/config:/config
      - ./authelia/logs:/var/log/authelia/
    networks:
      authelia: {}
    labels:
      ## Expose Authelia through Traefik
      traefik.enable: 'true'
      - "traefik.http.routers.authelia.rule='Host(`auth.a2va.dev`)'"
      - "traefik.http.routers.authelia.entrypoints='https'"
      ## Setup Authelia Middlewares
      - "traefik.http.middlewares.authelia.forwardAuth.address='http://authelia:9091/api/authz/forward-auth'"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders='Remote-User,Remote-Groups,Remote-Name,Remote-Email'"
    environment:
      TZ: 'Europe/Paris'
      X_AUTHELIA_CONFIG_FILTERS: template

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.a2va.dev`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.middlewares=authelia@docker"
      - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    environment:
      - PUID=${UID}
      - PGID=${GID}
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
  authelia: {}
```
The strange thing is that it works, auth.a2va.dev shows the authelia interface and whoami.a2va.dev redirects to authentication.
And if the commands for the traefik configuration are put in a yaml file, the error doesn't appear (but if possible I would like to keep this config in the compose file, as I want to have as few files as possible).
