### DISCUSSION TITLE
Clarification on Restriction of Local IP Usage with HTTP Redirect URIs

### DISCUSSION THREAD

**Discussion by nthduy** [authelia/authelia#8508] [Q&A] [answered]
I am using Authelia as the identity provider for an Immich instance, and it works perfectly for my external domain. However, I want to use the local IP address of the instance when I am at home to improve upload speeds. My current configuration includes the following redirect URIs:

```yaml
redirect_uris: 
  - https://my.external.com/api/oauth/mobile-redirect 
  - http://192.168.1.100:2283/auth/login 
  - http://192.168.1.100:2283/user-settings 
  - https://my.external.com/auth/login
  - https://my.external.com/user-settings
 ```
When attempting to use OAuth with the local IP address, I encounter the following error:

```
Authorization Response for Request with id 'xxxx-yyyy' on client with id 'immich' could not be created: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Redirect URL is using an insecure protocol, http is only allowed for hosts with suffix 'localhost', for example: http://myapp.localhost/.
method=GET path=/api/oidc/authorization
```

The current documentation mentions some restrictions on redirect URIs, but it does not specify the limitation of http to localhost-suffixed domains.

Some restrictions that have been placed on clients and their redirect URIs are as follows:
https://www.authelia.com/configuration/identity-providers/openid-connect/clients/#redirect_uris
> 1. If a client attempts to authorize with Authelia and its redirect URI is not listed in the client configuration the attempt to authorize will fail and an error will be generated.
 > 2. The redirect URIs are case-sensitive.
 >3. The URI must include a scheme and that scheme must be one of http or https.

If this is an intentional restriction, could the documentation be updated to reflect this limitation explicitly?
If not, is there a workaround or configuration change I can use to allow local IP addresses with http?
Thank you for your help ! 😁

**Comment by james-d-elliott** [comment]
This probably depends on which flow is being used as some flows have a restriction imposed by the OpenID Connect 1.0 standards. The configuration is more lenient than the library is. What does the rest of your client configuration look like?

**Reply by nthduy** [reply]
The rest of my client configuration look like this
```
oidc: 
    clients:
    - client_id: immich
      client_name: Immich
      client_secret: my-super-secret-key
      public: false 
      authorization_policy: two_factor
      redirect_uris: 
       - https://my.external.com/api/oauth/mobile-redirect 
       - http://192.168.1.100:2283/auth/login 
       - http://192.168.1.100:2283/user-settings 
       - https://my.external.com/auth/login
       - https://my.external.com/user-settings
      grant_types:
        - authorization_code
      scopes:
        - openid
        - profile
        - email 
      userinfo_signed_response_alg: none
```
