### DISCUSSION TITLE
smtp error

### DISCUSSION THREAD

**Discussion by jddavies89** [authelia/authelia#8539] [Troubleshooting] [answered]
Hello, could you help please?

<img width="839" alt="errorSMTP" src="https://github.com/user-attachments/assets/d9da3e1f-3701-4650-9bb9-b6600af202a8" />

configuration.yaml for authelia

##############################################################################
#                   Authelia configuration  thehomelab.wiki                  #
##############################################################################

server:
  ## The address for the Main server to listen on in the address common syntax.
  ## Formats:
  ##  - [<scheme>://]<hostname>[:<port>][/<path>]
  ##  - [<scheme>://][hostname]:<port>[/<path>]
  ## Square brackets indicate optional portions of the format. Scheme must be 'tcp', 'tcp4', 'tcp6', or 'unix'.
  ## The default scheme is 'unix' if the address is an absolute path otherwise it's 'tcp'. The default port is '9091'.
  ## If the path is specified this configures the router to handle both the `/` path and the configured path.
  address: 'tcp://cloudingsauth.duckdns.org:9091' #'tcp://:9091/'

#server:
#  host: https://cloudingsauth.duckdns.org/ #0.0.0.0
#  port: 9091 # if you need this changed make sure it reflects also in the docker-compose.yml

log:
  level: debug
identity_validation.reset_password.jwt_secret:  secret

default_redirection_url: "https://h.duckdns.org/"
totp:
  issuer: https://h.duckdns.org/
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  file:
    path: ./users.yml # Make sure this file exists
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "sub.mydomain.com"
      policy: bypass
    - domain: # Proxies only requiring username and password
        - "sub.mydomain.com"
      policy: one_factor
    - domain: # Proxies needing 2 factor below
        - sub.mydomain.com
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret:  secret
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain:  https://h.duckdns.org/ #"mydomain.com" # Needs to be your root domain

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: grey   # options: dark, light

storage:
  encryption_key: encryption key
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: jxxxes@outlook.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: jxxxes@outlook.com password
    host: smtp-mail.outlook.com
    port: 587
    sender: jxxxes@outlook.com

#ntp:
 # address: 'udp://127.0.0.1:123'

**Comment by james-d-elliott** [comment]
The `default_redirection_url` must either be the same as the session domain, or it must be a subdomain of it.

Edit: actually on closer inspection your domain is not well formed. Remove the comments after it.

**Reply by jddavies89** [reply]
What is the session domain? 
this 
server:
  ## The address for the Main server to listen on in the address common syntax.
  ## Formats:
  ##  - [<scheme>://]<hostname>[:<port>][/<path>]
  ##  - [<scheme>://][hostname]:<port>[/<path>]
  ## Square brackets indicate optional portions of the format. Scheme must be 'tcp', 'tcp4', 'tcp6', or 'unix'.
  ## The default scheme is 'unix' if the address is an absolute path otherwise it's 'tcp'. The default port is '9091'.
  ## If the path is specified this configures the router to handle both the `/` path and the configured path.
  address: 'tcp://h.duckdns.org:9091' #'tcp://:9091/'

so does tha mean server.address needs to be the same as default_redirect_url?

are you refering to removing the " sign on here? 

from 
default_redirection_url: "https://h.duckdns.org/"

to
default_redirection_url: https://h.duckdns.org/

and i did this too
from
 domain:  https://h.duckdns.org/ #"mydomain.com" # Needs to be your root domain

to 
 domain:  https://h.duckdns.org/ 


and removed 

    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
at the bottom in smtp.

i am still getting this error
<img width="844" alt="errorSMTP 2" src="https://github.com/user-attachments/assets/4d2deffb-90b2-477d-ac07-5f7267303870" />

**Reply by james-d-elliott** [reply]
The server address is not relevant here, it's just the port and IP it listens on. Can you show your full config again?

**Comment by jddavies89** [comment]
```
##############################################################################
#                   Authelia configuration  thehomelab.wiki                  #
##############################################################################

server:
  ## The address for the Main server to listen on in the address common syntax.
  ## Formats:
  ##  - [<scheme>://]<hostname>[:<port>][/<path>]
  ##  - [<scheme>://][hostname]:<port>[/<path>]
  ## Square brackets indicate optional portions of the format. Scheme must be 'tcp', 'tcp4', 'tcp6', or 'unix'.
  ## The default scheme is 'unix' if the address is an absolute path otherwise it's 'tcp'. The default port is '9091'.
  ## If the path is specified this configures the router to handle both the `/` path and the configured path.
  address: 'tcp://cloudingsauth.duckdns.org:9091' #'tcp://:9091/'

#server:
#  host: https://cloudingsauth.duckdns.org/ #0.0.0.0
#  port: 9091 # if you need this changed make sure it reflects also in the docker-compose.yml

log:
  level: debug
identity_validation.reset_password.jwt_secret:  secret

default_redirection_url: https://cloudingsauth.duckdns.org/
totp:
  issuer: https://cloudingsauth.duckdns.org/
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  file:
    path: ./users.yml # Make sure this file exists
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "sub.mydomain.com"
      policy: bypass
    - domain: # Proxies only requiring username and password
        - "sub.mydomain.com"
      policy: one_factor
    - domain: # Proxies needing 2 factor below
        - sub.mydomain.com
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret:  secret
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: grey   # options: dark, light

storage:
  encryption_key: encryption key
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: jxxx@outlook.com
    password: jxxx@outlook.com password here
    host: smtp-mail.outlook.com
    port: 587
    sender: jxxxx@outlook.com

#ntp:
 # address: 'udp://127.0.0.1:123'
```

**Reply by james-d-elliott** [reply]
```yaml
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret:  secret
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
```

The domain is missing entirely now, you still need it there, just at the end previously you had a comment.

**Reply by jddavies89** [reply]
got you, added this in

```
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret:  Lg1uxEMn46H1P7x5rcDIpkraD67NGm0UQUePqG7dvfb635brmHzvhezIPVTbpxJWCvwrghtDFHYdfnyGvfqlHp2CcCoz
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: https://cloudingsauth.duckdns.org/
```


im getting this
<img width="848" alt="errorSMTP 3" src="https://github.com/user-attachments/assets/3e616ce0-7851-4204-87a2-2d902760b963" />

**Reply by james-d-elliott** [reply]
The domain should be a domain, not a URL (i.e. cloudingsauth.duckdns.org)

**Reply by jddavies89** [reply]
thank you, i fell i am so close!

is it just the smtp bit? but i look at it and it looks fine.


<img width="852" alt="errorSMTP 4" src="https://github.com/user-attachments/assets/0f74765d-c732-4d49-8f8b-fa5dee81e19c" />



code



```
##############################################################################
#                   Authelia configuration  thehomelab.wiki                  #
##############################################################################

server:
  ## The address for the Main server to listen on in the address common syntax.
  ## Formats:
  ##  - [<scheme>://]<hostname>[:<port>][/<path>]
  ##  - [<scheme>://][hostname]:<port>[/<path>]
  ## Square brackets indicate optional portions of the format. Scheme must be 'tcp', 'tcp4', 'tcp6', or 'unix'.
  ## The default scheme is 'unix' if the address is an absolute path otherwise it's 'tcp'. The default port is '9091'.
  ## If the path is specified this configures the router to handle both the `/` path and the configured path.
  address: 'tcp://cloudingsauth.duckdns.org:9091' #'tcp://:9091/'

#server:
#  host: https://cloudingsauth.duckdns.org/ #0.0.0.0
#  port: 9091 # if you need this changed make sure it reflects also in the docker-compose.yml

log:
  level: debug
identity_validation.reset_password.jwt_secret:  secret

default_redirection_url: https://cloudingsauth.duckdns.org/
totp:
  issuer: https://cloudingsauth.duckdns.org/
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  file:
    path: ./users.yml # Make sure this file exists
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "sub.mydomain.com"
      policy: bypass
    - domain: # Proxies only requiring username and password
        - "sub.mydomain.com"
      policy: one_factor
    - domain: # Proxies needing 2 factor below
        - sub.mydomain.com
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret:  secret
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: cloudingsauth.duckdns.org

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: grey   # options: dark, light

storage:
  encryption_key: encryption key
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: jxxxxxx@outlook.com
    password: jxxxxxx@outlook.com password
    host: smtp-mail.outlook.com
    port: 587
    sender: jxxxx@outlook.com

#ntp:
 # address: 'udp://127.0.0.1:123'
```

**Reply by james-d-elliott** [reply]
Looks like it's good to go, you'll just need to either use credentials that the SMTP server will accept or use the file based one documented here instead of SMTP: https://www.authelia.com/configuration/notifications/introduction/

**Reply by jddavies89** [reply]
Okay thank you, understood.

so i have two options either inline within the configuration.yaml file or its own file.


If i do inline within the configuration.yaml file can you confirm my code is correct please and i should be following this link if i have a outlook account?


https://support.microsoft.com/en-gb/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040


pop or imap settings

notifier:
  smtp:
    username: email@outlook.com
    password: email password
    host: smtp-mail.outlook.com
    port: 587
    sender: email@outlook.com
```

Once there is no errors and it is up, i access it via default_redirection_url: address?

**Reply by james-d-elliott** [reply]
Their docs indicate they don't permit username/password auth.

**Reply by jddavies89** [reply]
aaa i did try that too, and i feel i moved on thank you.

code: 

```
notifier:
  disable_startup_check: false #true #true/false
  smtp:
    #username: jxxxs@outlook.com
    #password: 
    host: outlook.office365.com
    port: 587
    sender: jxxxs@outlook.com
    startup_check_address: jxxxs@outlook.com
```

error message - Possibly with the domain? but i can ping the domain fine.

<img width="839" alt="errorSMTP 5" src="https://github.com/user-attachments/assets/4c2bf49d-268d-4e2e-8b40-822a19589537" />
