### DISCUSSION TITLE
Unable to achieve desired remember_me behavior

### DISCUSSION THREAD

**Discussion by Cnote43** [authelia/authelia#8544] [Q&A]
I've been unable to achieve my desired remember_me behavior. I'm currently the only user and I'm just accessing my own self-hosted services. I want to have my session remain valid for 1 month after successfully authenticating. I've tried different session settings, but no matter what I'm always required to re-authenticate every 3 days.  Here are my current session settings:

```
session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'mydomain.com'
      authelia_url: 'https://authelia.mydomain.com'
      default_redirection_url: 'https://www.mydomainl.com'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1M'
  redis:
    host: '192.168.1.2'
    port: 6379
```

I access my services over a Cloudflare tunnel, reverse proxied through swag.
