### DISCUSSION TITLE
error msg="Configuration: session: option 'domain' and option 'cookies' can't be specified at the same time"

### DISCUSSION THREAD

**Discussion by Moacc95** [authelia/authelia#8556] [Q&A] [answered]
Hello, 
I have been trying to migrate to 4.38 for several days but I have this error message: error msg="Configuration: session: option 'domain' and option 'cookies' can't be specified at the same time". 

I have tried several configurations but without success... Does anyone have an idea? Here is my configuration: 

```
server:
  address: 'tcp://0.0.0.0:9091/authelia'
  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: 'debug'
  format: 'json'
  file_path: '/config/authelia.log'
  keep_stdout: true

totp:
  issuer: 'authelia.com'
  period: 30
  skew: 1

duo_api:
  disable: false
  hostname: 'api-xxx.duosecurity.com'
  integration_key: 'KEY'
  secret_key:
  enable_self_enrollment: false

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: '5 minutes'
  file:
    path: '/config/users_database.yml'
    password:
      algorithm: 'argon2'
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 256 # blocks this much of the RAM

access_control:
  default_policy: deny
  rules:
    # - domain:
    #     - "*.example.com"
    #     - "example.com"
    #   policy: bypass
    #   networks: # bypass authentication for local networks
    #     - 10.0.0.0/8
    #     - 192.168.0.0/16
    #     - 172.16.0.0/12
     - domain: '*.domaine.duckdns.org'
       policy: 'two_factor'

# https://www.authelia.com/configuration/session/introduction/
session:
  secret:
  name: 'authelia_session'
  cookies:
    - name: 'authelia_session'
      domain: 'domaine.duckdns.org'
      authelia_url: 'https://authelia.domaine.duckdns.org'
      inactivity: '5 minutes'
      default_redirection_url: 'https://domaine.duckdns.org'

  redis:
    host: 'redis'
    port: 6379
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: '10 minutes'
  ban_time: '12 hours'

storage:
  mysql:
    address: 'tcp://autheliadb:3306'
    database: 'authelia'
    username: 'authelia'
    password:
    timeout: '5 seconds'

notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp://smtp.gmail.com:587'
    username: 'mail@gmail.com'
    password:
    sender: 'mail@gmail.com'
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: 'test@authelia.com'
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: 'TLS1.2'
```

**Comment by james-d-elliott** [comment]
What are your env vars and what do the full logs show?

**Comment by Moacc95** [comment]
my log :

```
time="2025-01-04T08:58:35+01:00" level=debug msg="Process user information" gid=100 uid=1000

time="2025-01-04T08:58:35+01:00" level=error msg="Configuration: session: option 'domain' and option 'cookies' can't be specified at the same time" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"

time="2025-01-04T08:58:35+01:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"

      
```

my env : 
```
########################################################################################################################

services:
   authelia:
      image: authelia/authelia:latest
      container_name: authelia
      #labels:
        #- com.centurylinklabs.watchtower.enable=true
        #- diun.enable=true
      networks:
        - reverse-proxy-network
        - authelia-local
      #expose:
        #- 9091
      environment:
        - PUID=1000
        - PGID=100
        - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/JWT_SECRET
        #- AUTHELIA_JWT_SECRET_FILE=/secrets/JWT_SECRET
        - AUTHELIA_SESSION_DOMAIN=domaine.duckdns.org
        - AUTHELIA_SESSION_SECRET_FILE=/secrets/SESSION_SECRET
        - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/secrets/STORAGE_PASSWORD
        - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/STORAGE_ENCRYPTION_KEY
        - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/secrets/SMTP_PASSWORD
        - AUTHELIA_DUO_API_SECRET_KEY_FILE=/secrets/DUO_KEY
        - TZ=Europe/Paris
      ports:
        - 9091:9091/tcp
      volumes:
        - /srv/dev-disk-by-uuid-c8472a0a-61b5-4f1d-8189-1623ef476463/appdata/authelia:/config
        - /srv/dev-disk-by-uuid-04f96bfa-66bb-49c2-b1a6-a1b87ea0de44/DATA_DOCKER/secrets:/secrets

      secrets:
        - JWT_SECRET
        - SESSION_SECRET
        - STORAGE_PASSWORD
        - STORAGE_ENCRYPTION_KEY
        - SMTP_PASSWORD
        - DUO_KEY
        - ISSUER_PRIVATE_KEY
      depends_on:
        - mariadb
        - redis
      #restart: unless-stopped
      restart: no
```
