### DISCUSSION TITLE
Some requests are rejected as 401 even when authorized

### DISCUSSION THREAD

**Discussion by Aetf** [authelia/authelia#8562] [Troubleshooting]
### Version

v4.38.17

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Description

When handling lots of requests in a short amount of time, Authelia seems to return 401 unauthorized responses for some requests, even though the whole session is already authorized and most of the requests are ok. For example, when requesting a web app where lots of requests for js/css/xhr are generated, Authelia randomly rejects some requests, making the app not work properly.

In addition, the requests that did go through seems to have longer latency than without Authelia.

Looking in Authelia logs, there are some errors about "Unable to save updated user session" and redis connection pool timeout. From redis side, there is no error logs.

This happens to my Syncthing web interface and Kubernetes dashboards. Here is an example: 
![image](https://github.com/user-attachments/assets/9d7f050e-6036-4a1b-90b2-117864f7b8a9)

### Reproduction

Setup:
- I run Traefik as my ingress controller in my Kubernetes cluster
- Web apps (e.g. Syncthing web interface, kubernetes dashboard) is added as Ingress using domain matching
- ForwardAuth middleware using Authelia (`/api/authz/forward-auth` endpoint) is configured on those routes
- Authelia itself is using redis for session storage and file for user database
- Redis is running in single instance mode, on the same host as Authelia. It is dedicated to Authelia.

Run:
- Request the home page of the webapp, which generates lots of requests

(I'm not sure if any web app specifics matter here. Maybe just hitting Authelia  `/api/authz/forward-auth` endpoint with some canned authorized requests is enough to repro)

### Expectations

Once authorized and authenticated, Authelia should always return 200 authorized response for the configured acl protected requests.

### Configuration (Authelia)

```yaml
---
##
## Authelia rendered configuration file (file filters).
##
## Filters: template
##

---
##
## File Source Path: /config/00-main.yaml
##

server:
  # the default value is too small, and will cause 431 error
  buffers:
    read: 8192
  # disable internal healthcheck, we rely on k8s probes
  disable_healthcheck: true
  tls:
    key: /tls/tls.key
    certificate: /tls/tls.crt

certificates_directory: /tls

theme: "light"

log:
  level: "debug"

totp:
  issuer: 'unlimited-code.works'

authentication_backend:
  password_reset:
    disable: false
  file:
    path: '/storage/users.yaml'
    watch: true
    search:
      email: true
    password:
        algorithm: argon2id
        iterations: 1
        key_length: 32
        salt_length: 16
        memory: 128
        parallelism: 8

session:
  name: "authelia_session"
  expiration: "1d"
  inactivity: "1d"
  remember_me: "1y"
  redis:
    host: 'authelia-redis-master.serving-system'
    port: 6379
  cookies:
    - domain: 'unlimited-code.works'
      authelia_url: 'https://auth.unlimited-code.works'
      default_redirection_url: 'https://auth.unlimited-code.works/settings'

storage:
  local:
    path: |-
      /storage/db.sqlite3

notifier:
  smtp:
    address: 'smtp://smtp.mail-system:8025'
    ## HELO/EHLO Identifier. Identifies the mail client
    identifier: |-
      auth.unlimited-code.works
    sender: 'auth@unlimited-code.works'
    subject: "[Authelia] {title}"

identity_providers:
  oidc:
    jwks:
      - key: "removed"
    cors:
      endpoints:
      - authorization
      - token
      - revocation
      - introspection
      - userinfo
    authorization_policies:
      jellyfin:
        default_policy: 'deny'
        rules:
          - policy: 'two_factor'
            subject: 'group:users'
          - policy: 'two_factor'
            subject: 'group:jellyfin-users'
      immich:
        default_policy: 'deny'
        rules:
          - policy: 'two_factor'
            subject: 'group:users'
          - policy: 'two_factor'
            subject: 'group:immich-users'



---
##
## File Source Path: /config/01-oidc.yaml
##

identity_providers:
  oidc:
    clients: [removed]
---
##
## File Source Path: /config/02-acl.yaml
##

##
## Access Control Configuration
##
## Access control is a list of rules defining the authorizations applied for one resource to users or group of users.
##
## If 'access_control' is not defined, ACL rules are disabled and the 'bypass' rule is applied, i.e., access is allowed
## to anyone. Otherwise restrictions follow the rules defined.
##
## Note: One can use the wildcard * to match any subdomain.
## It must stand at the beginning of the pattern. (example: *.mydomain.com)
##
## Note: You must put patterns containing wildcards between simple quotes for the YAML to be syntactically correct.
##
## Definition: A 'rule' is an object with the following keys: 'domain', 'subject', 'policy' and 'resources'.
##
## - 'domain' defines which domain or set of domains the rule applies to.
##
## - 'subject' defines the subject to apply authorizations to. This parameter is optional and matching any user if not
##    provided. If provided, the parameter represents either a user or a group. It should be of the form
##    'user:<username>' or 'group:<groupname>'.
##
## - 'policy' is the policy to apply to resources. It must be either 'bypass', 'one_factor', 'two_factor' or 'deny'.
##
## - 'resources' is a list of regular expressions that matches a set of resources to apply the policy to. This parameter
##   is optional and matches any resource if not provided.
##
## Note: the order of the rules is important. The first policy matching (domain, resource, subject) applies.
access_control:
  ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  ## resource if there is no policy to be applied to the user.
  default_policy: deny

  # networks:
  # - name: private
  #   networks:
  #   - 10.0.0.0/8
  #   - 172.16.0.0/12
  #   - 192.168.0.0/16
  # - name: vpn
  #   networks:
  #   - 10.9.0.0/16
  networks: []
  removed

## OpenID Connect 1.0 policies
## The authorization policies section allows creating custom authorization policies which can be applied to clients.
## This is useful if you wish to only allow specific users to access specific clients i.e. RBAC.
## It’s generally recommended however that users rely on the OpenID Connect 1.0 relying party to provide RBAC controls based on the available claims.
##
## Each policy applies one of the effective policies which can be either one_factor or two_factor as per the standard policies,
## or also the deny policy which is exclusively available via these configuration options.
##
## Each rule within a policy is matched in order where the first fully matching rule is the applied policy.
## If the deny rule is matched the user is not asked for consent and it is considered a rejected consent and returns an OpenID Connect 1.0 access_denied error.
##
## The key for the policy itself is the name of the policy, which is used when configuring the client authorization_policy option.
## In the example we name the policy policy_name.
##
## See https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#authorization_policies
identity_providers:
  oidc:
    authorization_policies:
      removed
```

### Build Information

```shell
Last Tag: v4.38.17
State: tagged clean
Branch: v4.38.17
Commit: 592ab519b4167dfe4462ee0a613d38d3e4b8efa0
Build Number: 35061
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Thu, 31 Oct 2024 09:37:31 +1100
Extra:

Go:
    Version: go1.23.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
https://gist.github.com/Aetf/71d8ee4f2ee79f2e735d7b2bf26e0c7e

(as gist otherwise the comment is too long than github limitation)
```

### Logs (Proxy / Application)

```shell
Redis: https://gist.github.com/Aetf/c8a433075764e4b57e1c1366f36d335a
```

### Generative AI

No

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
