### DISCUSSION TITLE
actualbudget / actual - OIDC configuration

### DISCUSSION THREAD

**Discussion by cromelex** [authelia/authelia#8590] [Documentation Feedback] [answered]
Tested with

[Authelia](https://www.authelia.com/)
        [v4.38.18](https://github.com/authelia/authelia/releases/tag/v4.38.18)
    [Actual Budget](https://actualbudget.org/)
        [v25.1.0](https://github.com/actualbudget/actual/releases/tag/v25.1.0)

Okay I managed to get this working with **Actual Budget**, as documented in https://github.com/actualbudget/actual/issues/4029#issuecomment-2577666661

For Authelia, I added the following to configuration.yml and then restarted it.

```yml
identity_providers:
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    clients:
    # Actual
      - client_id: 'actualbudget'
        client_name: 'Actual'
        client_secret: ''$pbkdf2-digestedsecret'
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://actualbudget.example.com/openid/callback'
        public: false
        require_pkce: true
        pkce_challenge_method: 'S256'
        grant_types:
          - 'authorization_code'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
```

For Actual, I had to create a `config.json` in `/data`.
The authMethod required for Authelia cannot currently be set from the Actual Budget GUI.

```json
{
"openId": {
        "issuer": "https://auth.example.com",
        "client_id": "actual",
        "client_secret": "insecure_secret",
        "server_hostname": "https://actualbudget.example.com",
        "authMethod": "oauth2"
    }
}
```
Then, go into the actualbudget docker container and run 

`npm run disable-openid`  #to ensure it was disabled
Then run
`npm run enable-openid`

I went back into my Actual-Budget instance, logged out and logged back in, selecting the OpenID option. This triggered the request to Authelia and assigned my user as owner for the budget.

Then I added a second user based on this
https://deploy-preview-447.www.actualbudget.org/docs/experimental/multi-user

ie, go to `https://actualbudget.example.com/user-directory` and manually added the 2nd user,.

To share a budget between users, the owner needs to give them access to the specific budget via `https://actualbudget.example.com//user-access`.

Logged in via Authelia with said user successfully.

Seems to be working as intended! Not sure if anyone else wants to test this and confirm it works, and then the example could be added to the documentation.
