### DISCUSSION TITLE
bypass static files

### DISCUSSION THREAD

**Discussion by ivan-sirosh** [authelia/authelia#8591] [Troubleshooting]
Hello,
I want to bypass static files, because checking authorization for each significantly slows the loading process of page, but for some reason it does not work.

my ACL:
```yaml
access_control:
    default_policy: 'deny'
    rules:
      - domain:
          - '*.in.example.com'
        resources:
          - '\.(js|css|png|jpe?g|svg|gif|webp|woff2?|ttf|otf|eot|ico|bmp|mp4|mp3|wav|avi|mkv|webm|ogg|m4a|flac|aac)(\?.*)?$'
        policy: 'bypass'
      - domain_regex:
          - '^.+stg\.in\.example\.com$'
        domain:
          - 'dev.in.example.com'
        policy: one_factor
        subject:
          - [ 'group:dev' ]
```

I still see in logs that authelia checks each and every connection. what am I doing wrong?

```
time="2025-01-09T06:55:52Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/Content/Fonts/fonts.css?h=ZYP7+3tB+/eme7MGOlDOLg (method GET)."                                                             
time="2025-01-09T06:55:52Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/Content/styles.css?h=VAwjWra8YBWH8JiyE7JFDA (method GET)."                                                                  
time="2025-01-09T06:55:52Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/index-c63a3d9123308207f20c.js (method GET)."                                                                                
time="2025-01-09T06:55:52Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/initialize.json?t=1736405752803 (method GET)."                                                                              
time="2025-01-09T06:55:53Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/Content/Images/Icons/favicon-32x32.png?h=lmqCw7GaBq+Sl0mzceEopQ (method GET)."                                              
time="2025-01-09T06:55:53Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/Content/Images/Icons/apple-touch-icon.png?h=6OFTjFECz9UsB7H/TlShUg (method GET)."                                           
time="2025-01-09T06:55:54Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/api/v1/customFilter (method GET)."                                                                                          
time="2025-01-09T06:55:54Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/api/v1/system/status (method GET)."                                                                                         
time="2025-01-09T06:55:54Z" level=debug msg="Check authorization of subject username=mark groups=dev ip=192.168.88.178 and object https://aaastg.in.example.com/api/v1/config/host (method GET).
```
