### DISCUSSION TITLE
RSA key PEM parsing fails

### DISCUSSION THREAD

**Discussion by zcchen** [authelia/authelia#8595] [Troubleshooting] [answered]
Hi there,

I have configured Authelia to act as an OIDC 1.0 provider. Consequently, I have generated an RSA key pair and entered it into the config according to the docs:
```
identity_providers:
  oidc:
    jwks:
      - key: '{{ secret "/config/secrets/oidc/jwks/rsa.2048.key" | mindent 10 "|" | msquote }}'
```
And I have also set `X_AUTHELIA_CONFIG_FILTERS=template` env in my docker-compose config, since it is mentioned at [https://github.com/authelia/authelia/discussions/7375](https://github.com/authelia/authelia/discussions/7375).

But it failed as:
```
"Configuration: failed to load configuration from file path(/config/configuration.yml) source: yaml: line 80: did not find expected key"
``` 

It works well if I replaced the related config as:
```
identity_providers:
  oidc:
    jwks:
      - key: |-
          -----BEGIN PRIVATE KEY-----
          .....
          -----END PRIVATE KEY-----
```

docker image version: `authelia/authelia:4.38.18`
