### DISCUSSION TITLE
Custom attribute mapping for user defined attribute from ldap.

### DISCUSSION THREAD

**Discussion by SharimNaveed** [authelia/authelia#8621] [Q&A] [answered]
I have integrated [lldap ](https://github.com/lldap/lldap) with authelia. In my LLDAP server, I have some custom user-defined attributes (e.g., tenantid) that I want to return in the response headers after successful authentication.

**Is it possible in authelia to do so?**

**what i tried so far,**

 ```
authentication_backend:
  ldap:
    implementation: custom
    address: ldap://lldap:3890
    attributes:
      display_name: displayName
      username: uid
      group_name: cn
      mail: mail
      tenant: tenantid  <---- user defined attribute of ldap
```

but authelia gives error saying configuration key not expected.

```
time="2025-01-24T19:02:53Z" level=error msg="Configuration: configuration key not expected: authentication_backend.ldap.attributes.tenant" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-01-24T
```

Looking at error logs I came to conclusion that currently it's not possible in authelia.

**Questions:**

- Is it possible to achieve my goal using Authelia? If so, could you guide me on how to configure it correctly?
- If this is not currently supported, what do you think about adding support for custom attributes as a new feature in Authelia?
