### DISCUSSION TITLE
Filter all non-GET requests through one_factor but just return 401 (version v4.38.16)

### DISCUSSION THREAD

**Discussion by wfy-belief** [authelia/authelia#8643] [Q&A] [answered]
**Expect to redirect to the login page.**

## my access_control rules
```yaml
    rules:
      - domain: 'http.example.com'
        policy: 'bypass'
        methods:
          - 'GET'
      - domain: 'http.example.com'
        subject:
          - 'group:public_read_write'
        policy: 'one_factor'
```
test service is follow

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      name: httpbin
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http.example.com
  namespace: default
  labels:
    app.kubernetes.io/name: httpbin
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # https://doc.traefik.io/traefik/middlewares/overview/
    - kind: Rule
      match: Host(`http.example.com`)
      services:
        - kind: Service
          name: httpbin
          port: 80
      middlewares:
        - name: http-to-https
        - name: 'forwardauth-authelia' # name of your middleware, as defined in your middleware.yml
          namespace: 'default'
```

When a web page is accessed normally it is normal, but when a post or put request is sent, it returns 401 without redirection
<img width="1661" alt="image" src="https://github.com/user-attachments/assets/5f553b4c-f56c-4d09-a104-a2780faf6959" />

the logger is follow
time="2025-01-25T09:22:19Z" level=info msg="Access to https://http.example.com/put (method PUT) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://auth.example.com/?rd=https%3A%2F%2Fhttp.example.com%2Fput&rm=PUT" method=GET path=/api/authz/forward-auth remote_ip=10.42.1.1

my session config is

```
  session:
    redis:
      enabled: true
      enabledSecret: true
      host: 'redis-master.default'
      port: 6379

    encryption_key:
      ## The value of a generated secret when using the ~ secret_name.
      value: ''

    cookies:
      - domain: 'example.com'
        subdomain: 'auth'
        authelia_url: 'https://auth.example.com'
        name: 'authelia_session'
        # same_site: 'lax'
        # inactivity: '5m'
        # expiration: '1h'
        # remember_me: '1d'
```

**The expectation is to redirect to login, or is this phenomenon normal now?**

```
curl 'https://http.example.com/put' \
  -X 'PUT' \
  -H 'accept: application/json' \
  -H 'accept-language: en,zh;q=0.9,zh-CN;q=0.8' \
  -H 'content-length: 0' \
  -H 'origin: https://http.example.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://http.example.com/' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' -vl
* Host http.example.com:443 was resolved.
* IPv6: (none)
* IPv4: 100.88.88.12
*   Trying 100.88.88.12:443...
* Connected to http.example.com (100.88.88.12) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=example.com
*  start date: Jan  6 07:42:29 2025 GMT
*  expire date: Apr  6 07:42:28 2025 GMT
*  subjectAltName: host "http.example.com" matched cert's "*.example.com"
*  issuer: C=US; O=Let's Encrypt; CN=R10
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://http.example.com/put
* [HTTP/2] [1] [:method: PUT]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: http.example.com]
* [HTTP/2] [1] [:path: /put]
* [HTTP/2] [1] [accept: application/json]
* [HTTP/2] [1] [accept-language: en,zh;q=0.9,zh-CN;q=0.8]
* [HTTP/2] [1] [content-length: 0]
* [HTTP/2] [1] [origin: https://http.example.com]
* [HTTP/2] [1] [priority: u=1, i]
* [HTTP/2] [1] [referer: https://http.example.com/]
* [HTTP/2] [1] [sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"]
* [HTTP/2] [1] [sec-ch-ua-mobile: ?0]
* [HTTP/2] [1] [sec-ch-ua-platform: "macOS"]
* [HTTP/2] [1] [sec-fetch-dest: empty]
* [HTTP/2] [1] [sec-fetch-mode: cors]
* [HTTP/2] [1] [sec-fetch-site: same-origin]
* [HTTP/2] [1] [user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36]
> PUT /put HTTP/2
> Host: http.example.com
> accept: application/json
> accept-language: en,zh;q=0.9,zh-CN;q=0.8
> content-length: 0
> origin: https://http.example.com
> priority: u=1, i
> referer: https://http.example.com/
> sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"
> sec-ch-ua-mobile: ?0
> sec-ch-ua-platform: "macOS"
> sec-fetch-dest: empty
> sec-fetch-mode: cors
> sec-fetch-site: same-origin
> user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
> 
* Request completely sent off
< HTTP/2 401 
< alt-svc: h3=":443"; ma=2592000
< content-type: text/html; charset=utf-8
< date: Sat, 25 Jan 2025 09:27:05 GMT
< location: https://auth.example.com/?rd=https%3A%2F%2Fhttp.example.com%2Fput&rm=PUT
< permissions-policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), screen-wake-lock=(), sync-xhr=(), xr-spatial-tracking=(), interest-cohort=()
< referrer-policy: strict-origin-when-cross-origin
< set-cookie: authelia_session=8y-dZLWhziFtIKbXXD-QFzZ!b^01$n_l; expires=Sat, 25 Jan 2025 10:27:05 GMT; domain=example.com; path=/; HttpOnly; secure; SameSite=Lax
< x-content-type-options: nosniff
< x-dns-prefetch-control: off
< x-frame-options: DENY
< content-length: 105
< 
* Connection #0 to host http.example.com left intact
<a href="https://auth.example.com/?rd=https%3A%2F%2Fhttp.example.com%2Fput&amp;rm=PUT">401 Unauthorized</a>%                                                               
```
