### DISCUSSION TITLE
Protecting php-fpm status page with authelia (via caddy)

### DISCUSSION THREAD

**Discussion by spomata** [authelia/authelia#8666] [General]
Hi,
I have been able to configure authelia and caddy to provide security to multiple apps in my setup, however I am facing an issue with the php-fpm status page which I would like to secure behind the authelia wall.

From the likes of the error I would say it depends on FPM exposing the page without any session or login requirement (kinda like the  phpinfo() output).

What would be a feasible way to achieve this?

**LOGS**

Authelia error is:

```
Target URL does not appear to have a relevant session cookies configuration
```

I am using the caddy snippet seen in the documentation as:

```
    @fpmstatus {
            path /fpmstatus
    }

    forward_auth @fpmstatus auth.mydomain.tld:9091 {
            uri /api/authz/forward-auth
            copy_headers Remote-User Remote-Groups Remote-Email Remote-Name
    }
```

**Comment by Crowley723** [comment]
You're going to have to share the full, un-truncated log error to get any meaningful help. Feel free to redact the domain to `example.com`. (We need to know what the "Target URL" is, and if its the same as what is configured in your session config).

**Reply by spomata** [reply]
Hi, thanks for your reply and for giving me a hint. From what you say clearly there is something wrong in my config (no session entry for the domain pointed by target URL).

Main source of confusion was that I added an entry per domain where I intended to deploy authelia gating, under access_control/rules (including the domain I am trying to protect), while I only have a single TLD in session/cookies thinking (dumbly) that it was enough.

I assume that subdomains are covered by the main domain defined in the cookies single domain entry, which is the reason why domain1 and domain2 in the snippet below work. Anyway just to clarify here's a snippet of my config:

```
  cookies:
    - domain: '$AUTHDOMAIN.it'
      authelia_url: 'https://auth.$AUTHDOMAIN.it'
      ## The name of the session cookie.
      name: 'authelia_session'
```

```
access_control:
  ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  ## resource if there is no policy to be applied to the user.
  default_policy: 'deny'

  rules:
    - domain: 'domain1.$AUTHDOMAIN.it'
      policy: 'two_factor'

    - domain: 'domain2.$AUTHDOMAIN.it'
      policy: 'two_factor'

    - domain: '$TARGETURLTLD.com'
      policy: 'two_factor'
```

And the redacted log:

```

time="2025-01-26T15:04:07Z" level=error msg="Target URL does not appear to have a relevant session cookies configuration" error="unable to retrieve session cookie domain provider: no configured session cookie domain matches the url 'https://$TARGETURLTLD.com/fpmstatus?full'" method=GET path=/api/authz/forward-auth remote_ip=xyz target_url="https://$TARGETURLTLD.com/fpmstatus?full"
```
