### DISCUSSION TITLE
id_token_signing_alg_values_supported Include none Is there any way to not return it?

### DISCUSSION THREAD

**Discussion by wfy-belief** [authelia/authelia#8684] [Q&A]
my config is follow
but .well-known/openid-configuration id_token_signing_alg_values_supported return ["RS256","none"]
```yaml
identity_providers:
  oidc:
    lifespans:
      access_token: '1 hour'
      authorize_code: '1 minute'
      id_token: '1 hour'
      refresh_token: '1 hour and 30 minutes'
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_client_debug_messages: false
    enable_jwt_access_token_stateless_introspection: false
    minimum_parameter_entropy: 8
    discovery_signed_response_alg: 'RS256'
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key_id: 'public'
        key: | 
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
    cors:
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'xxxxxxx'
        client_name: 'KAFKA UI'
        client_secret: '$pbkdf2-sha512$310000$Tf2HocbXV4zIcqTb0SKsmg$0N7GXKDMWYq2Rd4ns3GPAlEk2jrd532GzjNy0gzM9NHBUG43WVEhz.FseMjwZdodqco93hYYWIxkQA4KxasSCA'
        public: false
        redirect_uris:
          - 'https://xxxxxx'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'one_factor'
        consent_mode: 'auto'
        require_pushed_authorization_requests: false
        require_pkce: false
        pkce_challenge_method: ''
        authorization_signed_response_alg: 'none'
        authorization_signed_response_key_id: ''
        id_token_signed_response_alg: 'RS256'
        id_token_signed_response_key_id: 'public'
        access_token_signed_response_alg: 'none'
        access_token_signed_response_key_id: ''
        userinfo_signed_response_alg: 'none'
        userinfo_signed_response_key_id: ''
        introspection_signed_response_alg: 'none'
        introspection_signed_response_key_id: ''
        request_object_signing_alg: ''
        token_endpoint_auth_signing_alg: ''
        token_endpoint_auth_method: 'client_secret_basic'
...
```
