### DISCUSSION TITLE
Should the https/wss check be enforced even when using authn_strategies other than CookieSession?

### DISCUSSION THREAD

**Discussion by christaikobo** [authelia/authelia#8731] [Q&A] [answered]
I have an basic auth endpoint like this:

```
  endpoints:
    authz:
      basic-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
```

And when using it with http scheme, I got "Target URL 'http://127.0.0.1:8080/' has an insecure scheme 'http', only the 'https' and 'wss' schemes are supported so session cookies can be transmitted securely" error.

This is understandable if I am using a cookiesession strategy, but for basic auth, I don't see any cookie being used anyway, so is it possible to bypass this scheme check for a basic auth endpoint?

(Or did I miss something obvious that can do this?)
