### DISCUSSION TITLE
Stirling PDF OpenID Connect 1.0 Integration

### DISCUSSION THREAD

**Discussion by cansi22** [authelia/authelia#8781] [Documentation Feedback] [answered]
### Description

To add to Integration list APP

**Stirling PDF**

[](https://docs.stirlingpdf.com/Advanced%20Configuration/Single%20Sign-On%20Configuration#oauth-2-set-up)

Tested Versions

Stirling PDF: 0.41.0
Authelia: 4.38.19

**Application Root URL:** {service_web}
**Authelia Root URL:** {Authelia_URL}
**Client ID:** stirlingpdf
**Client Secret:** {secure_secret}

Authelia:
```
identity_providers:
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    clients:
          - id: stirlingpdf
            description: Stirling PDF
            public: false
            secret: '{secure_secret}'
            authorization_policy: two_factor
            redirect_uris: {service_web}/login/oauth2/code/oidc
            scopes:
              - 'openid'
              - 'email'
              - 'profile'
```

**Application** 
```
  oauth2:
    enabled: true # set to 'true' to enable login (Note: enableLogin must also be 'true' for this to work)
    issuer: '{Authelia_URL}' # set to any provider that supports OpenID Connect Discovery (/.well-known/openid-configuration) endpoint
    clientId: 'stirlingpdf' # client ID from your provider
    clientSecret: '{secure_secret}' # client secret from your provider
    autoCreateUser: true # set to 'true' to allow auto-creation of non-existing users
    blockRegistration: false # set to 'true' to deny login with SSO without prior registration by an admin
    useAsUsername: email # default is 'email'; custom fields can be used as the username
    scopes: openid, profile, email # specify the scopes for which the application will request permissions
    provider: Authelia # set this to your OAuth provider's name, e.g., 'google' or 'keycloak'
```

### Use Case

Stirling PDF OpenID Connect 1.0 Integration parameters to add to documentation.

Tested in my server.

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] I have checked for related issues and checked the documentation
