### DISCUSSION TITLE
Using Nginx to Rewrite Static IPs to Domain Names for Authelia

### DISCUSSION THREAD

**Discussion by hidrol** [authelia/authelia#8833] [General]
Hi everyone,

I'm setting up Authelia for authentication, but I have a challenge due to its lack of support for IP-based rules. I have multiple Autonomous Guided Vehicles (AGVs) operating in a manufacturing hall. Each AGV has its own isolated local network and is currently accessed externally via static IP addresses.

Since Authelia works with domain names, I'm looking for a way to configure Nginx to rewrite or redirect requests from static IP addresses to corresponding domain names. Ideally, I want to map something like:

https://192.168.10.10/config→ https://config.agv1.com
https://192.168.10.11/visu → https://visu.agv2.com

This should work transparently for clients accessing the AGVs. Has anyone successfully set up such a configuration in Nginx, or is there another approach I should consider?

Thanks in advance!

**Comment by james-d-elliott** [comment]
Could you elaborate on what you mean by lack of support?

```yaml
session:
  cookies:
  - domain: '192.168.10.10'
    authelia_url: 'https://192.168.10.10/auth'
  - domain: '192.168.10.11'
    authelia_url: 'https://192.168.10.11/auth'
access_control:
  default_policy: 'deny'
  rules:
    - domain: '192.168.10.10'
      policy: 'bypass'
    - domain: '192.168.10.11'
      policy: 'bypass'
```

**Reply by hidrol** [reply]
Thanks for your response! I was referring to [https://github.com/authelia/authelia/discussions/6905#discussioncomment-8808422](url). I guess I drew the wrong conclusions then?

**Reply by james-d-elliott** [reply]
The user was trying to access authelia directly when they'd not configured the isolated domain to support that, it's generally expected that users would not use an IP to connect to authelia. However if you want to setup authelia like that it would theoretically work just fine.

**Reply by hidrol** [reply]
That's good to hear, thanks for the clarification!

**Comment by hidrol** [comment]
I'm still struggling with setting up the config without subdomains. Not sure how the config files should look like. https://192.168.10.95/whoami seems not to be reachable.

```
access_control:
  default_policy: deny
  rules:
    - domain:
        - "192.168.10.95"
      policy: bypass
     - domain:
         - "192.168.10.95/whoami"
       policy: one_factor
 
session:
  cookies:
    - domain: '192.168.10.95'
      authelia_url: 'https://192.168.10.95/auth'
      default_redirection_url: 'https://192.168.10.95/auth'
```
and whoami.conf
```
server {
    listen 80;
    server_name 192.168.10.95;

    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name 192.168.10.95;

    include /config/nginx/snippets/ssl.conf;
    include /config/nginx/snippets/authelia-location.conf;

    location /whoami/ {
        include /config/nginx/snippets/proxy.conf;
        include /config/nginx/snippets/authelia-authrequest.conf;
        proxy_pass http://whoami/;
    }
}
```

**Reply by james-d-elliott** [reply]
Sorry didn't see this earlier:

```yaml
access_control:
  default_policy: deny
  rules:
     - domain:
         - '192.168.10.95'
       policy: one_factor
       resources: '^/whoami([/?].*)?$'
    - domain:
        - '192.168.10.95'
      policy: bypass
```

That'll get authelia working, as far as nginx, that's a bit out of my area without logs from both authelia and nginx.
