### DISCUSSION TITLE
Making Authelia Session Cookies Domain-Specific – Best Practices?

### DISCUSSION THREAD

**Discussion by Entepotenz** [authelia/authelia#9023] [Q&A] [answered]
Hello everyone,

I'm a happy user of Authelia. :-)

Recently, I started wondering if I’m configuring sessions in the recommended way.  
Here’s my current session configuration (`configuration.yaml`):
```yaml
session:
  name: authelia_session
  same_site: lax
  cookies:
    - domain: 'domainX.com'
      authelia_url: 'https://authelia.domainX.com'
      default_redirection_url: 'https://domainX.com'
```

I noticed that when I open link-dashboard.domainX.com, the Authelia session cookie is shared with this subdomain, even though no authentication is required for it.
<img width="1452" alt="Screenshot 2025-03-18 at 20 19 07" src="https://github.com/user-attachments/assets/2ed998ba-9d69-4cdd-905b-e70ef8bfb5e4" />

Is there a way to configure the session so that the cookie is only valid for selected subdomains?

Any advice would be greatly appreciated!

Best regards,
Entepotenz
