### DISCUSSION TITLE
Audiobookshelf - Sharing configuration for simple setups

### DISCUSSION THREAD

**Discussion by Entepotenz** [authelia/authelia#9024] [Show and tell]
Hello everyone,

I am big fan of Authelia and I want share my configuration with the internet.
In this case I want to share my working example of integrating the OpenID of Authelia with Audiobookshelf.

```yaml
identity_providers:
  oidc:
    hmac_secret: INSERT_RANDOM_SECRET
    jwks:
      - algorithm: "RS256"
        use: "sig"
        key: |
          -----BEGIN PRIVATE KEY-----
          XXXXXX
          -----END PRIVATE KEY-----
    enable_client_debug_messages: false
    # enforce_pkce: 'always'
    authorization_policies:
      policy_name:
        default_policy: "two_factor"
        rules:
          - policy: "deny"
            subject: "group:admins"
    clients:
      - client_id: INSERT_RANDOM_CLIENT_ID
        client_name: "Audiobookshelf"
        client_secret: INSERT_RANDOM_CLIENT_SECRET
        public: false
        authorization_policy: "two_factor"
        require_pkce: true
        pkce_challenge_method: "S256"
        redirect_uris:
          - "https://INSERT_AUDIOBOOKSHELF_DOMAIN/auth/openid/callback"
          - "https://INSERT_AUDIOBOOKSHELF_DOMAIN/auth/openid/mobile-redirect"
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
```

Here is the `users_database.yml`:
(Keep in mind that you can configure the roles in audiobookshelf by assigning specific group names)
```yml
---
users:
  administrator:
    displayname: "administrator"
    password: "INSERT_PASSWORD_HASH"
    email: "INSERT_EMAIL"
    groups:
      # for audiobookshelf group claim
      - admin
  non_administrator:
    displayname: "non_administrator"
    password: "INSERT_PASSWORD_HASH"
    email: "INSERT_EMAIL"
    groups:
      # for audiobookshelf group claim
      - user
```

Here is the Aduiobookshelf configuration in the webui.
Keep in mind that if the users in authelia do not exist yet in Audiobookshelf you need to enable "auto register" at least until the necessary users logged in for the first time.
<img width="802" alt="Screenshot 2025-03-18 at 21 08 48" src="https://github.com/user-attachments/assets/89970a93-1c71-4bc4-b9ed-191a4f2a28da" />
<img width="803" alt="Screenshot 2025-03-18 at 21 09 01" src="https://github.com/user-attachments/assets/9d09aee8-f25f-415a-a746-6253bb86dd2e" />

**Comment by james-d-elliott** [comment]
Thanks for this! If you feel like you can make a contribution here: https://github.com/authelia/authelia/tree/master/docs/content/integration/openid-connect

Otherwise if you're not interested or feel like it's too much I'll ask for a couple screenshots and make it myself.

**Reply by Entepotenz** [reply]
Yes, I can make the contribution. It will come soon :-)

**Reply by james-d-elliott** [reply]
Forgot to mention use `<appname>.example.com` and `auth.example.com` and `example.com` for all examples, including screenshots if possible. You'll also notice some templates in the existing examples which automatically include variables from the site.

**Reply by Entepotenz** [reply]
FYI: I created the PR
https://github.com/authelia/authelia/pull/9064

**Comment by Al4ndil** [comment]
Hi @Entepotenz 
I'm sorry to ask a stupid question...
I have set up OIDC integration for Audiobookshelf. Everything works on a browser, but I can't get the ABS app to work on Android.
I keep getting a redirect alert.
Are you able to use it? How?
NB: I am using SWAG as a proxy.

**Reply by Entepotenz** [reply]
Hi @Al4ndil ,

No Problem.

Can you please share the specific error message?

**Reply by Al4ndil** [reply]
Thx @Entepotenz !
This one : "Server redirected somewhere else (to authelia.XXX.duckdns.org.)"
I use the standard configuration of SWAG for Audiobookshelf and your configuration for Auithelia integration.

**Reply by Entepotenz** [reply]
What is your configuration of the authelia redirect URIs?

**Reply by Al4ndil** [reply]
> What is your configuration of the authelia redirect URIs?

```
redirect_uris:
- 'https://audiobookshelf.XXX.duckdns.org/auth/openid/callback'
- 'https://audiobookshelf.XXX.duckdns.org/auth/openid/mobile-redirect'
- 'audiobookshelf://oauth'
```

Authelia logs when i attempt to connect with android app : 
```
{"level":"debug","msg":"Check authorization of subject username= groups= ip=213.41.227.124 and object https://audiobookshelf.XXX.duckdns.org/audiobookshelf/sw.js (method GET).","time":"2025-07-01T10:51:54+02:00"}
{"level":"info","method":"GET","msg":"Access to https://audiobookshelf.XXX.duckdns.org/audiobookshelf/sw.js (method GET) is not authorized to user \u003canonymous\u003e, responding with status code 401 with location redirect to https://authelia.XXX.duckdns.org/?rd=https%3A%2F%2Faudiobookshelf.XXX.duckdns.org%2Faudiobookshelf%2Fsw.js\u0026rm=GET","path":"/api/authz/auth-request","remote_ip":"213.41.227.124","time":"2025-07-01T10:51:54+02:00"}
```

**Reply by Entepotenz** [reply]
I might be wrong but it looks like you are running audiobookshelf on this subpath "audiobookshelf":
https://audiobookshelf.XXX.duckdns.org/audiobookshelf/sw.js

But your redirects are missing this subpath. Is this correct?

**Reply by Al4ndil** [reply]
> I might be wrong but it looks like you are running audiobookshelf on this subpath "audiobookshelf": https://audiobookshelf.XXX.duckdns.org/audiobookshelf/sw.js
> 
> But your redirects are missing this subpath. Is this correct?

I agree with what you said.
On the other hand, it's strange that there's a subpath, my authentication configuration on Audiobookshelf, indicating that I don't want one. Could this be a bug?

![image_2025-07-02_112521103](https://github.com/user-attachments/assets/8a27305c-a9a7-46e1-864e-384ed80b374b)

**Reply by Al4ndil** [reply]
@Entepotenz 
I tested this by activating the subpath in the Audiobookshelf settings.
This did not change my error message.

**Comment by Al4ndil** [comment]
@Entepotenz 
since audiobookshelf 2.18, the /audiobookshelf subpath must be added when accessing via a reverse proxy

**Comment by Entepotenz** [comment]
@Al4ndil 
Are you configuring some special HTTP headers in your reverse proxy?

Here is my full identity_provider authelia configuration for audiobookshelf:
```yaml
identity_providers:
  oidc:
    # hmac_secret: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
    jwks:
      - algorithm: "RS256"
        use: "sig"
        key: {{ secret "/run/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_JWKS_KEY" | mindent 10 "|" | msquote }}
    enable_client_debug_messages: false
    # enforce_pkce: 'always'
    authorization_policies:
      policy_name:
        default_policy: "two_factor"
        rules:
          - policy: "deny"
            subject: "group:admins"
    clients:
      - client_id: {{ secret "/run/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_CLIENTS_AUDIOBOOKSHELF_CLIENT_ID" | mindent 2 "|" | msquote }}
        client_name: "Audiobookshelf"
        client_secret: {{ secret "/run/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_CLIENTS_AUDIOBOOKSHELF_CLIENT_SECRET_DIGEST" | mindent 2 "|" | msquote }}
        public: false
        authorization_policy: "two_factor"
        require_pkce: true
        pkce_challenge_method: "S256"
        redirect_uris:
          - "https://audiobookshelf.example.org:PORT/auth/openid/callback"
          - "https://audiobookshelf.example.org:PORT/auth/openid/mobile-redirect"
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
```
