### DISCUSSION TITLE
Authelia and Swag in a non-standard port

### DISCUSSION THREAD

**Discussion by bdovaz** [authelia/authelia#9074] [Q&A] [answered]
I have mapped the ports in the swag container so that it is not listening on the standard port but on another one, example: `5443:443`. Everything else is with the default values so authelia is set to 443.

The problem is that then in the `.well-known/openid-configuration` endpoint I don't see the port `5443`, it omits it as if it was configured in the standard port.

How can I make authelia “aware” of this change? Because otherwise when I try to authenticate through a client configured with OIDC I get errors of discovery policies that does not match the issuer name with the authority, etc... And it is because it compares the url with the standard port (field `issuer` of the endpoint .well-known/openid-configuration with the standard port `443` vs authority field of the client that I configure that includes the non-standard port `5443`).

**Comment by Crowley723** [comment]
I believe that you can modify the session domain to include the port. `example.com:5443`

**Reply by bdovaz** [reply]
@Crowley723 it won't let me set a port:

`option 'domain' does not appear to be a valid cookie domain or an ip address"`

**Reply by Crowley723** [reply]
```yaml
session:
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://auth.example.com:5433''
      name: 'authelia_session'
```
Sounds like you're using the old syntax for the session config. The above should work properly.

**Reply by bdovaz** [reply]
This is how I had it already configured and I get what I said in my first message,

`https://authelia.****.duckdns.org:5443/.well-known/openid-configuration`

![image](https://github.com/user-attachments/assets/92b58575-9e7c-47ce-9a24-f400cdebe52a)

As you can see, in spite of accessing with a non-standard port, in the endpoint, it appears with the standard port...

I'm using this configuration untouched: https://github.com/linuxserver/reverse-proxy-confs/blob/master/authelia.subdomain.conf.sample

And as I say in my first message, the only thing I have changed is the port mapping of the swag container to `5443:443`.

**Reply by Crowley723** [reply]
Can you share your current session config?

**Reply by bdovaz** [reply]
```yaml
session:
  name: authelia_session
  secret: '****'
  expiration: 1h
  inactivity: 5m
  remember_me: 1M
  cookies:
    - domain: ****.duckdns.org
      authelia_url: https://authelia.****.duckdns.org:5443
```
