### DISCUSSION TITLE
Jellyfin Pushed Authorization Request failed

### DISCUSSION THREAD

**Discussion by bdovaz** [authelia/authelia#9078] [Q&A] [answered]
> Pushed Authorization Request failed with error: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'client_secret_basic', however the OAuth 2.0 client registration does not allow this method. The registered client with id 'jellyfin' is configured to only support 'token_endpoint_auth_method' method 'client_secret_post'. Either the Authorization Server client registration will need to have the 'token_endpoint_auth_method' updated to 'client_secret_basic'x or the Relying Party will need to be configured to use 'client_secret_post'." method=POST path=/api/oidc/pushed-authorization-request remote_ip=****

And I have configured it as it says:

https://www.authelia.com/integration/openid-connect/jellyfin/#authelia

I use this plugin:

https://github.com/9p4/jellyfin-plugin-sso

**Comment by james-d-elliott** [comment]
The config is tested by multiple people with the latest released version. Are you using a dev version? If not please show your actual configs.

**Reply by bdovaz** [reply]
Authelia:

```yaml
clients:
      - client_id: jellyfin
        client_name: Jellyfin
        client_secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng' # The digest of 'insecure_secret'.
        public: false
        authorization_policy: one_factor
        require_pkce: true
        pkce_challenge_method: S256
        redirect_uris:
          - 'https://jellyfin.*****.duckdns.org:5443/sso/OID/redirect/authelia'
          - 'https://jellyfin.*****.duckdns.org:5443/sso/OID/r/authelia'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
```

Jellyfin:

```xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://authelia.****.duckdns.org:5443</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>insecure_secret</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>false</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
            <string>jellyfin-admins</string>
          </AdminRoles>
          <Roles>
            <string>jellyfin-users</string>
          </Roles>
          <EnableFolderRoles>true</EnableFolderRoles>
          <EnableLiveTvRoles>false</EnableLiveTvRoles>
          <EnableLiveTv>false</EnableLiveTv>
          <EnableLiveTvManagement>false</EnableLiveTvManagement>
          <LiveTvRoles />
          <LiveTvManagementRoles />
          <FolderRoleMappings>
            <FolderRoleMappings>
            <FolderRoleMappings>
              <Role>jellyfin-users</Role>
              <Folders>
                <string>f137a2dd21bbc1b99aa5c0f6bf02a805</string>
                <string>a656b907eb3a73532e40e44b968d0225</string>
              </Folders>
            </FolderRoleMappings>
          </FolderRoleMappings>
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>groups</string>
          </OidScopes>
          <SchemeOverride>https</SchemeOverride>
          <NewPath>true</NewPath>
          <CanonicalLinks />
          <DefaultUsernameClaim>preferred_username</DefaultUsernameClaim>
          <DisableHttps>false</DisableHttps>
          <DoNotValidateEndpoints>false</DoNotValidateEndpoints>
          <DoNotValidateIssuerName>false</DoNotValidateIssuerName>
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```

**Reply by james-d-elliott** [reply]
Very odd, that looks fine. You can try changing `client_secret_post` to `client_secret_basic` but I doubt that will fix it.

**Reply by bdovaz** [reply]
I have already tried it and I get the error in reverse, it's very strange...

If I try to disable in the plugin in C# `OidcClientOptions -> DisablePushedAuthorization = true` (I have a fork and I'm replacing the assembly), the login works perfectly... It is something of the `Pushed Authorization Requests` but I do not understand why it fails me...

**Reply by james-d-elliott** [reply]
Maybe they don't build with static dependencies and that was added to the plugin deps?

**Reply by Crowley723** [reply]
I can confirm that v3.5.2.4 of the sso-auth plugin works as expected with v4.39.1 of authelia as of now.
My configs look very similar to yours.

**Reply by hendrik1120** [reply]
Are you using the manifest provided by the repo or are you trying to troubleshoot your PR here? https://github.com/9p4/jellyfin-plugin-sso/pull/244

**Reply by bdovaz** [reply]
@hendrik1120 At first I tried to follow the steps of:

https://www.authelia.com/integration/openid-connect/jellyfin/#authelia

https://github.com/9p4/jellyfin-plugin-sso

https://github.com/linuxserver/reverse-proxy-confs/blob/master/authelia.subdomain.conf.sample

https://github.com/linuxserver/reverse-proxy-confs/blob/master/jellyfin.subdomain.conf.sample

But when I started to have problems, I made a fork of that project and compiled an assembly, putting more logs in case they helped me...

**Reply by james-d-elliott** [reply]
Did you set authelia to require pushed authorization requests?

**Reply by taiwan-king** [reply]
> @hendrik1120 一開始我試著按照以下步驟進行：
> 
> https://www.authelia.com/integration/openid-connect/jellyfin/#authelia
> 
> https://github.com/9p4/jellyfin-plugin-sso
> 
> https://github.com/linuxserver/reverse-proxy-confs/blob/master/authelia.subdomain.conf.sample
> 
> https://github.com/linuxserver/reverse-proxy-confs/blob/master/jellyfin.subdomain.conf.sample
> 
> 但是當我開始遇到問題時，我對那個項目進行了分支，並編譯了一個組件，增加了更多的日誌以防它們能幫助我……

Since you are already using a reverse proxy,  
you can try accessing the URL without the port number.
This setting, `<SchemeOverride>https</SchemeOverride>`, is actually related to the reverse proxy.  
You can try removing it to see if everything works correctly.  
If it still doesn't work, add it back.  
Additionally, make sure that your external connection has a valid certificate.
I see that your configuration is using one_factor.
It should be simpler.
`<OidEndpoint>https://authelia.****.duckdns.org:5443</OidEndpoint>`
You may need to check whether you have **auth** or **authelia**,  
You ultimately need to reverse proxy to port **9091** for it to be correct.
and make sure it matches the documentation.

You can refer to my configuration.  
It works correctly this way:  
[https://github.com/authelia/authelia/discussions/8935](https://github.com/authelia/authelia/discussions/8935).
You added the two URIs correctly, and the plugin author also recommended it. There's no need to refer to my settings for this part.

**Reply by bdovaz** [reply]
I spent some time reconfiguring everything from scratch without reusing anything from my current instances (nswag + authelia + jellyfin) and I still have exactly the same problems:
* I have to use the `Scheme Override` configuration to `https` from the Jellyfin plugin. It seems that it is not able to configure the proxy even if I set the domain to `Advanced -> Networking`. I have created an issue to make it easier to debug this problem: https://github.com/jellyfin/jellyfin/issues/13762
* I have created a PR to have a similar configuration to the previous one but for the port (as I have said, I don't use the standard port) https://github.com/9p4/jellyfin-plugin-sso/pull/246
* I have created a PR to be able to disable the `pushed authorization` which seems to be optional in the OIDC specification and it is possible to ignore it. https://github.com/9p4/jellyfin-plugin-sso/pull/244

For the time being and until the PRs are merge and another release of the plugin is released, which I don't know when it will be or if it will be merge (I hope it will), I will continue with my fork.

**Comment by james-d-elliott** [comment, marked as answer]
I think we can close this out as it can't be replicated. If more information such as what was requested is provided we can look into it more.

**Comment by ThatWileyGuy** [comment]
I seem to be hitting this. When I first set up Jellyfin according to the documentation, logon failed with an error that Jellyfin was using `client_secret_basic` but was configured to use `client_secret_post`. I changed `token_endpoint_auth_method` to `client_secret_basic` and my first logon worked, but testing again in a private browser I'm now getting the opposite error (client is using `client_secret_post` but is configured to use `client_secret_basic`) in the Authelia logs and Jellyfin is putting up an error page with `Error preparing login: Unauthorized - Failed to push authorization parameters`

Authelia config looks like this:
```
     - client_id: 'OMITTED'
        client_name: 'Jellyfin'
        client_secret: 'OMITTED'
        public: false
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://jellyfin.OMITTED/sso/OID/redirect/Authelia'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
```
