### DISCUSSION TITLE
Re-auth on old device everytime a new device signs in

### DISCUSSION THREAD

**Discussion by iamdangry** [authelia/authelia#9095] [Troubleshooting]
I have updated to 4.39.1 from 4.38 and have noticed if I am logged in on my desktop and then login on my phone or iPad, my desktop session prompts to re-auth everytime without fail. But after I have signed back in on my desktop all clients are happy and I don't get a re-auth prompt until the session expires.

Am I missing something? Behaviour has only started with the upgrade to 4.39.1. Authelia was quite happy for 18months prior.

**Comment by james-d-elliott** [comment]
This issue occurred due to a change in go 1.24, we disabled the change go made and released the confirmed fix in 4.39.1. Double check you're using 4.39.1.

**Reply by iamdangry** [reply]
Confirmed on 4.39.1 (pulled a fresh copy as a precaution) and can confirm, the behaviour still occurs

**Reply by james-d-elliott** [reply]
Might want to show your config and logs, we have not had anyone else have this issue on 4.39.1.

**Reply by iamdangry** [reply]
Sorry, got delayed with something else, but can confirm it is still happening as of today although inconsistently. Just now I was able to re-produce it twice in a row, but then the third time so I could capture logs it functioned as expected. I did have a new experience where Authelia failed to accept my Yubikey on first try and threw an error about failed assertion. After a refresh it came good but all the clients logged out.

Config:
```
theme: 'auto'

server:
  address: 'tcp://:9091/authelia'

log:
  level: 'debug'

totp:
  disable: true
  issuer: 'authelia.com'

webauthn:
  disable: false
  timeout: '60 seconds'
  display_name: 'Authelia'
  selection_criteria:
    user_verification: 'preferred'

identity_validation:
  reset_password:
    jwt_secret: 'secret'

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain: '*.tld'
      resources:
        - '/.client/manifest.json$'
        - '/.client/[a-zA-Z0-9_-]+.png$'
        - '/service_worker.js$'
      policy: 'bypass'
    - domain: 'unifi.tld'
      policy: 'bypass'
    - domain: 'silver.tld'
      policy: 'two_factor'
    - domain: 'silverwork.tld'
      policy: 'two_factor'
    - domain: 'silveredge.tld'
      policy: 'two_factor'
    - domain: 'freshrss.tldt'
      policy: 'two_factor'

session:
  secret: 'secret'

  cookies:
    - name: 'authelia_session'
      domain: 'tld'
      authelia_url: 'https://authelia.tld'
      expiration: '1 hour'
      inactivity: '5 minutes'
      remember_me: '1M'
      same_site: strict

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: 'key'
  local:
    path: '/config/db.sqlite3'

notifier:
  filesystem:
    filename: /config/notification.log

identity_providers:
  oidc:
    claims_policies:
      default:
        id_token: ['groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
    jwks:
      - key_id: 'my-key'
        algorithm: 'RS256'
        use: 'sig'
        key: |
          -----BEGIN PRIVATE KEY-----
          
          -----END PRIVATE KEY-----
    clients:
      - client_id: 'freshrss'
        client_name: 'FreshRSS'
        client_secret: 'secret'
        public: false
        authorization_policy: 'two_factor'
        consent_mode: 'implicit'
        claims_policy: 'default'
        redirect_uris:
          - 'https://freshrss.tld:443/i/oidc/'
        scopes:
          - 'openid'
          - 'groups'
          - 'email'
          - 'profile'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
        jwks:
          - key_id: 'my-key'
            algorithm: 'RS256'
            use: 'sig'
            key: |
              -----BEGIN PUBLIC KEY-----
              
              -----END PUBLIC KEY-----
```

Log entry from a session that was logged out
```
authelia  | time="2025-03-27T13:29:12+10:00" level=info msg="Access to https://silver.tld/.config (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.tld/?rd=https%3A%2F%2Fsilver.tld%2F.config&rm=GET" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=redacted`
```
