### DISCUSSION TITLE
Using OIDC Authelia fails to redirect back to the app

### DISCUSSION THREAD

**Discussion by o-techie** [authelia/authelia#9099] [Troubleshooting] [answered]
When I submit my credentials through Authelia, I get a blank screen at /consent/openid/decision?..., and I'm not redirected back to the application. So far, I’ve determined that the issue may be related to loading resources from ./static/js and ./static/css. It seems that this path is incorrect when loading the page at /consent, as shown below:

![Untitled](https://github.com/user-attachments/assets/1d0d07c7-725b-4a91-816b-87a75eca320e)

Is that a bug or misconfiguration?

My current test setup is:

Docker image with authelia version v4.39.1

**_docker-compose.yml_**

```version: "2.2"
services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: '/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: '/secrets/AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD'
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: '/secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD'
    ports:
      - 9091:9091
    volumes:
      - ./data/authelia/config:/config
      - ./data/authelia/secrets:/secrets
```

**_configuration.yml_**

```
theme: 'auto'

log:
  level: 'debug'

server:
  address: 'tcp://:9091/'
  disable_healthcheck: false
  tls:
    key: ''
    certificate: ''
    client_certificates: []
  headers:
    csp_template: ''
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6s'
    write: '6s'
    idle: '30s'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz: {}
    rate_limits: {}

totp:
  disable: false
  issuer: '[redacted]'
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '90 seconds' #only for testing

authentication_backend:
  ldap:
    address: '[redacted]'
    implementation: 'activedirectory'
    timeout: '5s'
    start_tls: false
    tls:
      server_name: '[redacted]'
      skip_verify: true
      minimum_version: 'TLS1.2'
    base_dn: '[redacted]'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(pwdLastSet=0))(|(!(accountExpires=*))(accountExpires=0)(accountExpires>={date-time:microsoft-nt})))'
    groups_filter: '(&(member={dn})(|(sAMAccountType=268435456)(sAMAccountType=536870912)))'
    user: '[redacted]'
    attributes:
      distinguished_name: 'distinguishedName'
      username: 'sAMAccountName'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'

regulation:
  modes:
    - 'user'
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

access_control:
  default_policy: 'one_factor'

session:
  name: 'authelia_session'
  same_site: 'lax'
  cookies:
    - domain: '[redacted]'
      authelia_url: 'https://login.[redacted]'

storage:
  local:
    path: '/config/db.sqlite3'

notifier:
  smtp:
    address: '[redacted]'
    username: '[redacted]'
    sender: '[redacted]
    subject: '[redacted] {title}'

identity_providers:
  oidc:
    jwks:
      - key_id: 'authelia'
        algorithm: 'RS256'
        use: 'sig'
        key: |
            -----BEGIN PRIVATE KEY-----
            [redacted]
            -----END PRIVATE KEY-----
    clients:
      - client_id: "[redacted]"
        client_name: "Grist"
        client_secret: "[redacted]"
        public: false
        authorization_policy: "one_factor"
        grant_types:
          - refresh_token
          - authorization_code
        redirect_uris:
          - "[redacted]"
        scopes:
          - "openid"
          - "email"
          - "profile"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_basic"
```
