### DISCUSSION TITLE
Authelia Indefinite Redirect with SWAG

### DISCUSSION THREAD

**Discussion by HeyItsJono** [authelia/authelia#9131] [Troubleshooting] [answered]
### Version

v4.39.1

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

3.3.0

### Description

I had Authelia up and running fine with SWAG deployed via Docker, but have just moved house so have had all my services down for the last week or two. Today I got round to setting them back up; nothing has changed network-wise since I've moved the router across and everything is set up the same (and my nameservers are already pointing to my new IP); however now Authelia fails to redirect anonymous users to a signin page. Instead any attempt to reach my site just loads indefinitely and then times out.

Looking at the Authelia logs, it's detecting an attempt to reach the requested page, which suggests SWAG/DNS issues aren't the problem, and it's passing an auth url back to the browser, but this url isn't resolving:
```
2025-03-29T12:34:09.873551226Z {"level":"info","method":"GET","msg":"Access to https://home.PLACEHOLDER.COM/ (method GET) is not authorized to user \u003canonymous\u003e, responding with status code 401 with location redirect to https://auth.PLACEHOLDER.COM/?rd=https%3A%2F%2Fhome.PLACEHOLDER.COM%2F\u0026rm=GET","path":"/api/authz/auth-request","remote_ip":"192.168.0.7","time":"2025-03-29T23:34:09+11:00"}
```
The browser redirects to this URL but it just times out.
Similarly attempting to visit `auth.PLACEHOLDER.COM` times out, where it would have otherwise just shown the login page.
Subdomains that aren't guarded by Authelia resolve correctly.

### Reproduction

Deploy SWAG & Authelia via docker, then attempt to visit any subdomain -> timeout will occur.

### Expectations

User should get redirected to the Authelia login page.

### Configuration (Authelia)

```yaml
# yamllint disable rule:comments-indentation
---
###############################################################################
##                           Authelia Configuration                          ##
###############################################################################

## 
## Notes:
##
##    - SEE: configuration.yml.sample for extensive documentation of all options & descriptions
##    - the default location of this file is assumed to be configuration.yml unless otherwise noted
##    - when using docker the container expects this by default to be at /config/configuration.yml
##    - the default location where this file is loaded from can be overridden with the X_AUTHELIA_CONFIG environment var
##    - the comments in this configuration file are helpful but users should consult the official documentation on the
##      website at https://www.authelia.com/ or https://www.authelia.com/configuration/prologue/introduction/
##    - this configuration file template is not automatically updated
##    - For info on secrets, see https://www.authelia.com/configuration/methods/secrets/
##
theme: 'auto'
default_2fa_method: 'totp'

server:
  address: 'tcp://:9091/authelia'
  disable_healthcheck: false
  buffers:
    read: 4096
    write: 4096

log:
  level: 'debug' # info, debug, or trace
  format: 'json'
  file_path: '/config/logs/authelia.log'
  keep_stdout: true

totp:
  issuer: 'Authelia'
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  allowed_algorithms:
  - 'SHA1'
  allowed_digits:
  - 6
  allowed_periods:
  - 30
  disable_reuse_security_policy: false

webauthn:
  disable: false
  timeout: '60 seconds'
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  user_verification: 'preferred'

# duo_api:
  # disable: false
  # hostname: 'api-123456789.example.com'
  # integration_key: 'ABCDEF'
  ## Secret can also be set using a secret: https://www.authelia.com/c/secrets
  # secret_key: '1234567890abcdefghifjkl'
  # enable_self_enrollment: false

identity_validation:
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'

ntp:
  address: 'udp://time.cloudflare.com:123'

authentication_backend:
  password_reset:
    disable: false

  refresh_interval: '5 minutes'

  # file:
  #   path: '/config/users_database.yml'
  #   watch: false
  #   search:
  #     email: false
  #     case_insensitive: false
  #   password:
  #     algorithm: 'argon2'
  #     argon2:
  #       variant: 'argon2id'
  #       iterations: 3
  #       memory: 65536
  #       parallelism: 4
  #       key_length: 32
  #       salt_length: 16
  #     scrypt:
  #       iterations: 16
  #       block_size: 8
  #       parallelism: 1
  #       key_length: 32
  #       salt_length: 16
  #     pbkdf2:
  #       variant: 'sha512'
  #       iterations: 310000
  #       salt_length: 16
  #     sha2crypt:
  #       variant: 'sha512'
  #       iterations: 50000
  #       salt_length: 16
  #     bcrypt:
  #       variant: 'standard'
  #       cost: 12

  ldap:
    address: 'ldap://lldap:3890'
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: 'dc=PLACEHOLDER,dc=COM'
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
    user: 'cn=authelia,ou=people,DC=PLACEHOLDER,DC=COM'
    additional_users_dn: ou=people
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(&(member={dn})(objectclass=groupOfUniqueNames))"

access_control:
  default_policy: 'deny'
  rules:
    - domain:
      - auth.PLACEHOLDER.COM
      policy: bypass
    - domain:
      - plex.PLACEHOLDER.COM
      - wizarr.PLACEHOLDER.COM
      - overseerr.PLACEHOLDER.COM
      policy: 'two_factor'
      subject:
      - 'group:lldap_admin'
      - 'group:lldap_user'
    - domain:
      - PLACEHOLDER.COM
      - "*.PLACEHOLDER.COM"
      policy: 'two_factor'
      subject:
      - 'group:lldap_admin'

session:
  cookies:
    - name: 'PLACEHOLDER_authelia_session'
      domain: 'PLACEHOLDER.COM'
      authelia_url: 'https://auth.PLACEHOLDER.COM'
      default_redirection_url: 'https://PLACEHOLDER.COM'
      same_site: 'lax'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'

  # Defaults
  name: 'authelia_session'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'

regulation: # Bruteforce protection
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  local:
    path: '/config/db.sqlite3'

notifier: # Either SMTP or Filesystem, not both.
  disable_startup_check: false
  # filesystem: # If using this, every time you would be 'sent an email', just open notifications.txt to find the security code.
    # filename: '/config/notifications.txt'
  
  smtp:
    address: 'smtp://smtp.gmail.com:587'
    username: 'PLACEHOLDERCOM@gmail.com'
    sender: 'Authelia <PLACEHOLDERCOM@gmail.com>'
    subject: '[Authelia] {title}'
    startup_check_address: 'PLACEHOLDERCOM@gmail.com'
    tls:
      minimum_version: 'TLS1.2'
```

### Build Information

```shell
λ docker exec authelia authelia build-info
Last Tag: v4.39.1
State: tagged clean
Branch: v4.39.1
Commit: 9a22f5c30b216b6d1aa1f80b6a36fac62e9f7727
Build Number: 41283
Build OS: linux
Build Arch: arm64
Build Compiler: gc
Build Date: Tue, 18 Mar 2025 14:49:44 +1100
Extra:

Go:
    Version: go1.24.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
2025-03-29T13:05:22.285568293Z time="2025-03-30T00:05:22+11:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
2025-03-29T13:05:22.285667533Z time="2025-03-30T00:05:22+11:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/logs/authelia.log format=json keep_stdout=true
2025-03-29T13:05:22.285932864Z time="2025-03-30T00:05:22+11:00" level=debug msg="Process user information" gid=1000 uid=1000
2025-03-29T13:05:22.294633011Z time="2025-03-30T00:05:22+11:00" level=warning msg="Configuration: configuration key 'webauthn.user_verification' is deprecated in 4.39.0 and has been replaced by 'webauthn.selection_criteria.user_verification': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
2025-03-29T13:05:22.294747417Z time="2025-03-30T00:05:22+11:00" level=warning msg="Configuration: configuration key 'webauthn.user_verification' is deprecated in 4.39.0 and has been replaced by 'webauthn.selection_criteria.user_verification': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
2025-03-29T13:05:22.294858120Z time="2025-03-30T00:05:22+11:00" level=info msg="Authelia v4.39.1 is starting"
2025-03-29T13:05:22.294878027Z time="2025-03-30T00:05:22+11:00" level=info msg="Log severity set to debug"
2025-03-29T13:05:22.320162346Z {"level":"info","msg":"Storage schema is being checked for updates","time":"2025-03-30T00:05:22+11:00"}
2025-03-29T13:05:22.325737390Z {"level":"info","msg":"Storage schema is already up to date","time":"2025-03-30T00:05:22+11:00"}
2025-03-29T13:05:22.599831761Z {"level":"debug","msg":"LDAP Supported OIDs. Control Types: none. Extensions: 1.3.6.1.4.1.4203.1.11.1","time":"2025-03-30T00:05:22+11:00"}
2025-03-29T13:05:27.020551822Z {"level":"debug","msg":"webauthn-metadata provider: startup check skipped as it is disabled","time":"2025-03-30T00:05:27+11:00"}
2025-03-29T13:05:27.161131220Z {"level":"info","msg":"Startup complete","time":"2025-03-30T00:05:27+11:00"}
2025-03-29T13:05:27.162137841Z {"level":"info","msg":"Listening for non-TLS connections on '[::]:9091' path '/' and '/authelia'","server":"main","service":"server","time":"2025-03-30T00:05:27+11:00"}
2025-03-29T13:05:45.856283231Z {"level":"debug","msg":"Check authorization of subject username= groups= ip=192.168.0.7 and object https://drive.PLACEHOLDER.COM/ (method GET).","time":"2025-03-30T00:05:45+11:00"}
2025-03-29T13:05:45.856436804Z {"level":"info","method":"GET","msg":"Access to https://drive.PLACEHOLDER.COM/ (method GET) is not authorized to user \u003canonymous\u003e, responding with status code 401 with location redirect to https://auth.PLACEHOLDER.COM/?rd=https%3A%2F%2Fdrive.PLACEHOLDER.COM%2F\u0026rm=GET","path":"/api/authz/auth-request","remote_ip":"192.168.0.7","time":"2025-03-30T00:05:45+11:00"}
```

### Logs (Proxy / Application)

```shell
No changes to the logs appear in SWAG during this process.
```

### Documentation

authelia-server.conf
```
## Version 2024/03/16 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx/authelia-server.conf.sample
# Make sure that your authelia container is in the same user defined bridge network and is named authelia
# Rename /config/nginx/proxy-confs/authelia.subdomain.conf.sample to /config/nginx/proxy-confs/authelia.subdomain.conf
# For authelia 4.37 and below, make sure that the authelia configuration.yml has 'path: "authelia"' defined
# For authelia 4.38 and above, make sure that the authelia configuration.yml has 'address: "tcp://:9091/authelia"' defined

# location for authelia subfolder requests
location ^~ /authelia {
    auth_request off; # requests to this subfolder must be accessible without authentication

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_authelia authelia;
    proxy_pass http://$upstream_authelia:9091;
}

# location for authelia 4.37 and below auth requests
location = /authelia/api/verify {
    internal;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_authelia authelia;
    proxy_pass http://$upstream_authelia:9091/api/verify;

    ## Include the Set-Cookie header if present
    auth_request_set $set_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $set_cookie;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
}

# location for authelia 4.38 and above auth requests
location = /authelia/api/authz/auth-request {
    internal;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_authelia authelia;
    proxy_pass http://$upstream_authelia:9091/api/authz/auth-request;

    ## Include the Set-Cookie header if present
    auth_request_set $set_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $set_cookie;

    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
}

# virtual location for authelia 401 redirects
location @authelia_proxy_signin {
    internal;

    ## Include the Set-Cookie header if present
    auth_request_set $set_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $set_cookie;

    ## Set the $target_url variable based on the original request
    set_escape_uri $target_url $scheme://$http_host$request_uri;

    ## Translate the Location response header from the auth subrequest into a variable
    auth_request_set $signin_url $upstream_http_location;

    if ($signin_url = '') {
        ## Set the $signin_url variable
        set $signin_url https://$http_host/authelia/?rd=$target_url;
    }

    ## Redirect to login
    return 302 $signin_url;
}
```

compose.yaml
```
  authelia:
    container_name: authelia
    image: 'authelia/authelia'
    user: '1000:1000'
    expose:
      - 9091
    volumes:
      - '/home/PLACEHOLDER/containers/authelia/config:/config'
    environment:
      TZ: 'Australia/Sydney'
    env_file: "./env/auth.env"
    restart: 'unless-stopped'
    security_opt: [no-new-privileges:true]


  lldap:
    container_name: lldap
    image: lldap/lldap:stable
    ports:
    - "17170:17170" # Web UI
    - "3890:3890" # LDAP
    # - "6360:6360" # LDAPS (LDAP over SSL)
    environment:
      - UID=1000
      - GID=1000
      - TZ=Australia/Sydney
    env_file: "./env/lldap.env"
    volumes:
      - /home/PLACEHOLDER/containers/lldap/data:/data
      - /home/PLACEHOLDER/containers/lldap/secrets:/secrets
    restart: unless-stopped
    security_opt: [no-new-privileges:true]

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - URL=PLACEHOLDER.COM
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - PROPAGATION=180
      - CERTPROVIDER=zerossl
      - EMAIL=PLACEHOLDER
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-crowdsec|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-maxmind
    env_file: "./env/swag.env"
    volumes:
      - /home/PLACEHOLDER/containers/swag:/config
      # - /home/PLACEHOLDER/containers/homeassistant/home-assistant.log:/hass/home-assistant.log:ro # For fail2ban (currently disabled in favour of CrowdSec)
      # - /home/PLACEHOLDER/containers/authelia/config/logs/authelia.log:/authelia/authelia.log:ro # For fail2ban (currently disabled in favour of CrowdSec)
    ports:
      - 443:443 # SSL for NGinx to handle HTTPS
      - 80:80 # Landing Page
      - 81:81 # Dashboard Mod: https://github.com/linuxserver/docker-mods/tree/swag-dashboard
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

_No response_

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
