### DISCUSSION TITLE
Cloudflare Zero Trust - Failed to get your identity (email was not returned)

### DISCUSSION THREAD

**Discussion by Hernansandi** [authelia/authelia#9181] [Troubleshooting] [answered]
Hi! I'm trying to set up Authelia with Cloudflare Access following this https://www.authelia.com/integration/openid-connect/cloudflare-zerotrust/ . Everything seems to work fine until this part:
<img width="391" alt="image" src="https://github.com/user-attachments/assets/46306b11-90f9-4a41-a27f-2b06472724f9" />
and then return this:
<img width="556" alt="image" src="https://github.com/user-attachments/assets/2656f9e4-1ed0-4cf0-8b63-c6a228743e1f" />

this is my configuration.yml:
```
identity_providers:
  oidc:
    hmac_secret: 'this_is_a_secret_abc123abc123abc'
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: |
          -----BEGIN PRIVATE KEY-----
          [private key]
          -----END PRIVATE KEY-----
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    enable_client_debug_messages: false
    enforce_pkce: 'public_clients_only' 
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins:
        - 'https://<my-domain>'
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'cloudflare'
        client_name: 'Cloudflare ZeroTrust'
        client_secret: '$diggest'
        public: false
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://<my-team>.cloudflareaccess.com/cdn-cgi/access/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
```
        
And this in cloudflare:
```
Name (Required): Authelia
App ID (Required): cloudflare
Client secret (Required): <unsafe-client_secret>
Auth URL (Required): https://auth.<my-domain>/api/oidc/authorization
Token URL (Required): https://auth.<my-domain>/api/oidc/token
Certificate URL (Required): https://auth.<my-domain>/jwks.json
Proof Key for Code Exchange (PKCE): On
Enable SCIM: Off

Optional configurations
Email claim:
-
OIDC Claims:
- preferred_username
- mail

OIDC Scopes:
- openid
- email
- profile
```

**Comment by Hernansandi** [comment, marked as answer]
solved. i added claims_policies like this:
```
claims_policies:
      ## Creates the 'default' claims policy.
      default:
        id_token: ['rat', 'groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
    clients:
      - client_id: 'client_example_id'
        ## Assigns the 'default' claims policy to this client.
        claims_policy: 'default'
```
i see in https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter
