### DISCUSSION TITLE
OIDC from Harbor results on a "go-jose/go-jose: unknown/unsupported algorithm" error

### DISCUSSION THREAD

**Discussion by flixman** [authelia/authelia#9196] [Q&A]
I am installing harbor and trying to use Authelia as SSO. To this end, the configuration of the client in Authelia is:

```
        - client_id: 'harbor'
          client_name: 'Harbor'
          client_secret:
             path: '/secrets/oidc-clients/harbor.password'
          public: false
          authorization_policy: 'one_factor_local'
          redirect_uris:
            - 'https://harbor.{{ domain }}/c/oidc/callback'
          grant_types:
            - 'refresh_token'
            - 'authorization_code'
          scopes:
            - 'openid'
            - 'profile'
            - 'email'
            - 'offline_access'
            - 'roles'
          userinfo_signed_response_alg: 'none'
          token_endpoint_auth_method: 'client_secret_post'
```
the configuration for the OIDC connector in harbor is:
```
{"auth_mode":"oidc_auth","oidc_auto_onboard":true,"oidc_client_id":"harbor","oidc_endpoint":"https://auth.test.local","oidc_name":"authelia","oidc_scope":"openid,email,offline_access,profile,roles","oidc_user_claim":"email","primary_auth_mode":true,"oidc_client_secret":"xxxxxxxx"}
```
The reason for using client_secret_post is that using client_secret_basic resulted in an error. With this setup, I get to the page in which I am ask to give the app access to the identities and, when clicking in authorize, I get the error:
```
{"errors":[{"code":"BAD_REQUEST","message":"oauth2: \"error\" \"The error is unrecognizable\""}]}
```
and in authelia log, with trace level, I get this:
```
time="2025-04-05T14:36:21Z" level=error msg="Access Response for Request with id 'eecf2048-c2d8-43d6-b6d0-2c2f125288e4' failed to be created with error: go-jose/go-jose: unknown/unsupported algorithm" caller="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:57 OpenIDConnectTokenPOST" method=POST path=/api/oidc/token remote_ip=10.42.0.1 stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:57                   OpenIDConnectTokenPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:114 RegisterOpenIDConnectRoutes.NewHTTPToAutheliaHandlerAdaptor.func16\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                            RegisterOpenIDConnectRoutes.(*BridgeBuilder).Build.func2.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                          SecurityHeadersNoStore.func1\ngithub.com/valyala/fasthttp@v1.59.0/userdata.go:57                                           (*userData).Get\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                           SecurityHeadersBase.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             RegisterOpenIDConnectRoutes.(*CORSPolicy).Middleware.func17\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                            RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2380                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                                     goexit"
```

I do not know if this should be reported as an error (and, if so, to which project?) because I cannot see what "unsupported algorithm" is being requested. Can anybody provide some advice?

**Comment by james-d-elliott** [comment]
What version and what does the rest of the OIDC config look like?

**Reply by flixman** [reply]
Authelia is 4.39.1, and the helm chart is 0.10.4. This is the whole configuration:

```
---
# yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39/json-schema/configuration.json
theme: 'light'
default_2fa_method: ''
server:
  address: 'tcp://0.0.0.0:9091/'
  asset_path: ''
  headers:
    csp_template: ''
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6 seconds'
    write: '6 seconds'
    idle: '30 seconds'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz:
      auth-request:
        implementation: 'AuthRequest'
      ext-authz:
        implementation: 'ExtAuthz'
      forward-auth:
        implementation: 'ForwardAuth'
log:
  level: 'trace'
  format: 'text'
  file_path: ''
  keep_stdout: true
telemetry:
  metrics:
    enabled: false
identity_validation:
  elevated_session:
    code_lifespan: '5 minutes'
    elevation_lifespan: '10 minutes'
    characters: 8
    require_second_factor: false
    skip_second_factor: false
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
totp:
  disable: false
  issuer: 'Authelia'
  skew: 1
  secret_size: 32
  algorithm: 'SHA1'
  digits: 6
  period: 30
  allowed_algorithms:
    - 'SHA1'
  allowed_digits:
    - 6
  allowed_periods:
    - 30
webauthn:
  disable: false
  enable_passkey_login: false
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  timeout: '60 seconds'
  filtering:
    permitted_aaguids: []
    prohibited_aaguids: []
    prohibit_backup_eligibility: false
  selection_criteria:
    attachment: ''
    discoverability: 'preferred'
    user_verification: 'preferred'
  metadata:
    enabled: false
    validate_trust_anchor: true
    validate_entry: true
    validate_entry_permit_zero_aaguid: false
    validate_status: true
    validate_status_permitted: []
    validate_status_prohibited: []
ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  password_change:
    disable: false
  ldap:
    implementation: 'custom'
    address: 'ldap://openldap.openldap.svc.cluster.local:389'
    timeout: '5 seconds'
    start_tls: false
    tls:
      server_name: ''
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
    pooling:
      enable: false
      count: 5
      retries: 2
      timeout: '10 seconds'
    base_dn: 'dc=test,dc=local'
    additional_users_dn: 'ou=users'
    users_filter: '(|(&({username_attribute}={input})(|(objectClass=inetOrgPerson)(objectClass=simpleSecurityObject)))(&({mail_attribute}={input})(objectClass=inetOrgPerson)))'
    additional_groups_dn: 'ou=groups'
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    group_search_mode: 'filter'
    permit_referrals: false
    permit_unauthenticated_bind: false
    permit_feature_detection_failure: false
    user: 'cn=authelia,ou=functional,dc=test,dc=local'
    attributes:
      distinguished_name: ''
      username: 'cn'
      display_name: ''
      family_name: ''
      given_name: ''
      middle_name: ''
      nickname: ''
      gender: ''
      birthdate: ''
      website: ''
      profile: ''
      picture: ''
      zoneinfo: ''
      locale: ''
      phone_number: ''
      phone_extension: ''
      street_address: ''
      locality: ''
      region: ''
      postal_code: ''
      country: ''
      mail:  'mail'
      member_of:  ''
      group_name:  ''
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: false
    require_lowercase: false
    require_number: false
    require_special: false
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'test.local'
      authelia_url: 'https://auth.test.local'
regulation:
  modes:
  - 'user'
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'
storage:
  postgres:
    address: 'tcp://host.k3s.internal:5432'
    servers: []
    timeout: '5 seconds'
    database: 'authelia'
    schema: 'public'
    username: 'authelia_pg'
notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'
identity_providers:
  oidc:
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_client_debug_messages: false
    enable_jwt_access_token_stateless_introspection: false
    minimum_parameter_entropy: 8
    discovery_signed_response_alg: ''
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    authorization_policies:
      one_factor_local:
        default_policy: 'one_factor'
        rules:
        - policy: 'one_factor'
          networks:
          - '10.0.0.0/8'
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/secrets/oidc-jwks/jwks.pem" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/secrets/oidc-jwks/jwks.crt" | mindent 10 "|" | msquote }}
    cors:
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'argocd'
        client_name: 'Argo CD'
        client_secret: '{{ secret "/secrets/oidc-clients/argocd.password" }}'
        public: false
        redirect_uris:
          - 'https://argocd.test.local/auth/callback'
        scopes:
          - 'openid'
          - 'groups'
          - 'email'
          - 'profile'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'one_factor'
        consent_mode: 'auto'
        require_pushed_authorization_requests: false
        require_pkce: false
        pkce_challenge_method: ''
        authorization_signed_response_alg: 'none'
        authorization_signed_response_key_id: ''
        authorization_encrypted_response_key_id: ''
        authorization_encrypted_response_alg: ''
        authorization_encrypted_response_enc: ''
        id_token_signed_response_alg: 'RS256'
        id_token_signed_response_key_id: ''
        id_token_encrypted_response_key_id: ''
        id_token_encrypted_response_alg: ''
        id_token_encrypted_response_enc: ''
        access_token_signed_response_alg: 'none'
        access_token_signed_response_key_id: ''
        access_token_encrypted_response_key_id: ''
        access_token_encrypted_response_alg: ''
        access_token_encrypted_response_enc: ''
        userinfo_signed_response_alg: 'none'
        userinfo_signed_response_key_id: ''
        userinfo_encrypted_response_key_id: ''
        userinfo_encrypted_response_alg: ''
        userinfo_encrypted_response_enc: ''
        introspection_signed_response_alg: 'none'
        introspection_signed_response_key_id: ''
        introspection_encrypted_response_key_id: ''
        introspection_encrypted_response_alg: ''
        introspection_encrypted_response_enc: ''
        introspection_endpoint_auth_method: 'client_secret_basic'
        introspection_endpoint_auth_signing_alg: 'RS256'
        request_object_signing_alg: ''
        request_object_encryption_alg: 'none'
        request_object_encryption_enc: ''
        token_endpoint_auth_method: 'client_secret_basic'
        token_endpoint_auth_signing_alg: ''
        revocation_endpoint_auth_method: 'client_secret_basic'
        revocation_endpoint_auth_signing_alg: 'RS256'
        pushed_authorization_request_endpoint_auth_method: 'client_secret_basic'
        pushed_authorization_request_endpoint_auth_signing_alg: 'RS256'
      - client_id: 'gitea'
        client_name: 'Gitea'
        client_secret: '{{ secret "/secrets/oidc-clients/gitea.password" }}'
        public: false
        redirect_uris:
          - 'https://gitea.test.local/user/oauth2/authelia/callback'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'one_factor_local'
        consent_mode: 'auto'
        require_pushed_authorization_requests: false
        require_pkce: false
        pkce_challenge_method: ''
        authorization_signed_response_alg: 'none'
        authorization_signed_response_key_id: ''
        authorization_encrypted_response_key_id: ''
        authorization_encrypted_response_alg: ''
        authorization_encrypted_response_enc: ''
        id_token_signed_response_alg: 'RS256'
        id_token_signed_response_key_id: ''
        id_token_encrypted_response_key_id: ''
        id_token_encrypted_response_alg: ''
        id_token_encrypted_response_enc: ''
        access_token_signed_response_alg: 'none'
        access_token_signed_response_key_id: ''
        access_token_encrypted_response_key_id: ''
        access_token_encrypted_response_alg: ''
        access_token_encrypted_response_enc: ''
        userinfo_signed_response_alg: 'none'
        userinfo_signed_response_key_id: ''
        userinfo_encrypted_response_key_id: ''
        userinfo_encrypted_response_alg: ''
        userinfo_encrypted_response_enc: ''
        introspection_signed_response_alg: 'none'
        introspection_signed_response_key_id: ''
        introspection_encrypted_response_key_id: ''
        introspection_encrypted_response_alg: ''
        introspection_encrypted_response_enc: ''
        introspection_endpoint_auth_method: 'client_secret_basic'
        introspection_endpoint_auth_signing_alg: 'RS256'
        request_object_signing_alg: ''
        request_object_encryption_alg: 'none'
        request_object_encryption_enc: ''
        token_endpoint_auth_method: 'client_secret_basic'
        token_endpoint_auth_signing_alg: ''
        revocation_endpoint_auth_method: 'client_secret_basic'
        revocation_endpoint_auth_signing_alg: 'RS256'
        pushed_authorization_request_endpoint_auth_method: 'client_secret_basic'
        pushed_authorization_request_endpoint_auth_signing_alg: 'RS256'
      - client_id: 'harbor'
        client_name: 'Harbor'
        client_secret: '{{ secret "/secrets/oidc-clients/harbor.password" }}'
        public: false
        redirect_uris:
          - 'https://harbor.test.local/c/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'offline_access'
          - 'roles'
        grant_types:
          - 'refresh_token'
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'one_factor_local'
        consent_mode: 'auto'
        require_pushed_authorization_requests: false
        require_pkce: false
        pkce_challenge_method: ''
        authorization_signed_response_alg: 'none'
        authorization_signed_response_key_id: ''
        authorization_encrypted_response_key_id: ''
        authorization_encrypted_response_alg: ''
        authorization_encrypted_response_enc: ''
        id_token_signed_response_alg: 'RS256'
        id_token_signed_response_key_id: ''
        id_token_encrypted_response_key_id: ''
        id_token_encrypted_response_alg: ''
        id_token_encrypted_response_enc: ''
        access_token_signed_response_alg: 'none'
        access_token_signed_response_key_id: ''
        access_token_encrypted_response_key_id: ''
        access_token_encrypted_response_alg: ''
        access_token_encrypted_response_enc: ''
        userinfo_signed_response_alg: 'none'
        userinfo_signed_response_key_id: ''
        userinfo_encrypted_response_key_id: ''
        userinfo_encrypted_response_alg: ''
        userinfo_encrypted_response_enc: ''
        introspection_signed_response_alg: 'none'
        introspection_signed_response_key_id: ''
        introspection_encrypted_response_key_id: ''
        introspection_encrypted_response_alg: ''
        introspection_encrypted_response_enc: ''
        introspection_endpoint_auth_method: 'client_secret_basic'
        introspection_endpoint_auth_signing_alg: 'RS256'
        request_object_signing_alg: ''
        request_object_encryption_alg: 'none'
        request_object_encryption_enc: ''
        token_endpoint_auth_method: 'client_secret_post'
        token_endpoint_auth_signing_alg: ''
        revocation_endpoint_auth_method: 'client_secret_basic'
        revocation_endpoint_auth_signing_alg: 'RS256'
        pushed_authorization_request_endpoint_auth_method: 'client_secret_basic'
        pushed_authorization_request_endpoint_auth_signing_alg: 'RS256'
access_control:
  default_policy: 'deny'
  rules:
    - policy: one_factor
      domain:
        - 'guestbook.test.local'
    - policy: one_factor
      domain:
        - 'argocd.test.local'
      subject:
        - ['group:argocd']
    - policy: one_factor
      domain:
        - 'gitea.test.local'
      subject:
        - ['group:gitea']
    - policy: one_factor
      domain:
        - 'harbor.test.local'
      subject:
        - ['group:harbor']

```
