### DISCUSSION TITLE
Regulation trouble ? "Unsuccessful 1FA authentication attempt by user" logged over and over

### DISCUSSION THREAD

**Discussion by Bidonh** [authelia/authelia#9202] [Troubleshooting] [answered]
Hello, I have been using Authelia with SWAG on docker without trouble.
Recently I updated from v4.38.19 to v4.39.1.

I tidied up my configuration.yml because of a warning "Configuration: configuration key 'webauthn.user_verification' is deprecated in 4.39.0 and has been replaced by 'webauthn.selection_criteria.user_verification', no trouble either.

After a while I noticed this message being logged over and over. The weird thing is the IP is the ISP modem IP...
And I am connecting to my LAN with my router not the ISP modem.
Besides LAN IP have a BYPASS rule.

```
time="2025-04-06T12:41:37+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'USER_REDACTED'" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
time="2025-04-06T12:41:40+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'USER_REDACTED'" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
time="2025-04-06T12:41:42+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'USER_REDACTED'" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
time="2025-04-06T12:41:45+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user '192.168.0.254' and they are banned until 12:46:41PM on April 6 2025 (+02:00)" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
```
I disabled the 1FA rules one after the other (I have only 3 services) but no success.
Only disabling regulation worked and got rid of the error msg.

I don't see what could trigger so many login attempts from the ISP modem, I checked those services are not launched from my smartphone.

There was also a succession of consecutive bans logged ....
```
time="2025-04-07T15:24:12+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user '192.168.0.254' and they are banned until 3:29:10PM on April 7 2025 (+02:00)" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
time="2025-04-07T15:24:13+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user '192.168.0.254' and they are banned until 3:29:10PM on April 7 2025 (+02:00)" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
time="2025-04-07T15:24:18+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user '192.168.0.254' and they are banned until 3:29:10PM on April 7 2025 (+02:00)" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
time="2025-04-07T15:24:19+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user '192.168.0.254' and they are banned until 3:29:10PM on April 7 2025 (+02:00)" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
```

My configuration looks like that.

```
access_control:
  default_policy: 'deny'

  networks:
    - name: local
      networks:
      # LAN network
        - 192.168.0.0/16

  rules:
     # Bypass FA when connected to the LAN
    - domain:
      - "domain1.me"
      - "*.domain1.me"
      - "domain2.org"
      - "*.domain2.org"
      policy: bypass
      networks:
        - local

    # Open public access
    #- domain:

    # Single authentication for applications lacking authentication system
    - domain:
      - "service1.domain2.org"
      - "service2.domain2.org"
      - "service3.domain2.org"
      policy: one_factor

    # 2FA for sensitive services
    - domain:
      - "service4.domain2.org"
      policy: two_factor  
```

**Comment by james-d-elliott** [comment]
Those are authorizations using the `Authorization` header and the basic scheme, which are always evaluated for valid credentials if present and configured as a way to authenticate with authelia. You can configure the authz endpoints to not consider that header if desired.

**Comment by Bidonh** [comment]
I set info on debug to see what was triggering the error message.
It's my smartphone connecting on dav.

```time="2025-04-07T18:23:19+02:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.0.254 and object https://service1.domain2.org/dav/USER_REDACTED/ (method PROPFIND)."
time="2025-04-07T18:23:20+02:00" level=debug msg="Mark 1FA authentication attempt made by user 'USER_REDACTED'" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254
time="2025-04-07T18:23:20+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'USER_REDACTED'" method=GET path=/api/authz/auth-request path_raw=/authelia/api/authz/auth-request remote_ip=192.168.0.254 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:276            doMarkAuthenticationAttemptWithRequest\ngithub.com/authelia/authelia/v4/internal/handlers/handler_authz_authn.go:341 (*HeaderAuthnStrategy).handleGetBasic\ngithub.com/authelia/authelia/v4/internal/handlers/handler_authz_authn.go:261 (*HeaderAuthnStrategy).Get\ngithub.com/authelia/authelia/v4/internal/handlers/handler_authz.go:163       (*Authz).authn\ngithub.com/authelia/authelia/v4/internal/handlers/handler_authz.go:60        (*Authz).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66            handlerMain.(*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30           SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.4/router.go:441                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14       handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:23        handlerMain.StripPath.func32.1\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38            RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2380                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                     goexit"
```

In the configuration, I set Authelia to bypass that service.

```
    # Open public access
    - domain:
      - "service1.domain2.org"
      policy: bypass

```

I'll check the authz endpoints configuration.

**Reply by james-d-elliott** [reply, marked as answer]
Something like this:

```yaml
server:
  endpoints:
    authz:
      auth-request:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'CookieSession'
```
