### DISCUSSION TITLE
Auth Response Headers not found

### DISCUSSION THREAD

**Discussion by vrbgtrhr** [authelia/authelia#9208] [Q&A] [answered]
Using this middlewares and IngressRoute in the test app or in the browser i get the `Remote-User` Headers that i need. In the [documentation ](https://www.authelia.com/integration/trusted-header-sso/introduction/) i see that `/api/verify` expose that Headers but i noticed that is legacy in the `openapi.yml`

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      middlewares:
        - name: "forwardauth-authelia"
          namespace: kube-system
      services:
        - name: test
          namespace: test
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: authelia_traefik_lb
              secure: true
              sameSite: None
---
apiVersion: "traefik.containo.us/v1alpha1"
kind: "Middleware"
metadata:
  name: "forwardauth-authelia"
  labels:
    app.kubernetes.io/instance: "authelia"
    app.kubernetes.io/name: "authelia"
spec:
  forwardAuth:
    address: "http://authelia.authelia.svc.cluster.local/api/authz/forward-auth"
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
      - "Remote-Email"
      - "Remote-Name"
 ---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/authelia`)
      middlewares:
        - name: headers-authelia
      services:
        - name: authelia
          port: 80
          namespace: authelia
          passHostHeader: true
          strategy: RoundRobin
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: authelia_traefik_lb
              secure: true
              sameSite: None
---
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers-authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      Cache-Control: "no-store"
      Pragma: "no-cache"
```
