### DISCUSSION TITLE
youtrack integration

### DISCUSSION THREAD

**Discussion by hudecof** [authelia/authelia#9244] [Q&A] [answered]
Hello,

I would like to ask, if there is a way to integrate the YouTrack, https://www.jetbrains.com/youtrack/, from jetBrains.

They do not support the Open ID Connect, just OpenId 2.0, OAuth 2.0. and SAML ad authentification protocol.
<img width="800" alt="Screenshot 2025-04-14 at 08 21 04" src="https://github.com/user-attachments/assets/5eab7a75-bdb5-424c-bedb-7d11b164a870" />

Sorry for this question, but I'm stil do not understant the SSO so good to setup the authelia for this. The authelia shoulb be capable of the OAuth 2.0.

The seting of the YoouTrack is just the URL.

<img width="600" alt="Screenshot 2025-04-14 at 08 26 30" src="https://github.com/user-attachments/assets/21bc00be-e56c-4ce6-a6d0-bf0e4de8953f" />

regards
   Peter

**Comment by hendrik1120** [comment]
Hi, yes there is a way to integrate YouTrack with Authelia, but it's not pretty.
Authelia only the supports the newer OpenID Connect 1.0 standard, which is built on top of OAuth2.0.
OpenID 2.0 has been deprecated for quite some time now.

With that said, using OAuth2.0 you can configure Authelia with YouTrack using the following steps:

## YouTrack

1. Create a new OAuth2.0 authorization module with the name of `authelia` and the authorization url of `https://auth.example.com/api/oidc/authorization`
2. Only change the following settings:

Client ID: `youtrack`
Client secret: `insecure_secret`
#### Authorization Service Endpoints
Authorization: `https://auth.example.com/api/oidc/authorization`
Token: `https://auth.example.com/api/oidc/token`
User Data: `https://auth.example.com/api/oidc/userinfo`
#### Field Mapping
User ID: `sub`
Username: `preferred_username`
Full name: `name`
Email: `email`
Email verification state: `email_verified`
#### Additional Settings
Scope: `openid email profile`

## Authelia
`configuration.yml`

```yaml
identity_providers:
  oidc:
    clients:
      - client_id: 'youtrack'
        client_name: 'youtrack'
        client_secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'copy from youtrack configuration page'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        token_endpoint_auth_method: 'client_secret_basic'
        userinfo_signed_response_alg: 'none'
```

Just because this is working, there is no guarantee or support for this integration.
You should familiarize yourself with the OpenID Connect 1.0 and 0Auth2.0 standards regardless.
