### DISCUSSION TITLE
authelia works , but well-known/openid-configuration always 404

### DISCUSSION THREAD

**Discussion by changchichung** [authelia/authelia#9322] [Q&A] [answered]
I started an Authelia container using docker-compose, with Nginx Proxy Manager in front of it.
Here's my docker-compose.yml:
```yaml
networks:
  net:
    driver: 'bridge'

services:
  authelia:
    image: 'authelia/authelia'
    container_name: 'authelia'
    ports:
      - 9091:9091
    volumes:
      - './authelia:/config'
    networks:
      net: {}
    restart: 'unless-stopped'
    environment:
      TZ: 'Asia/Taipei'
```

I added the following section in Nginx Proxy Manager:
```nginx
    location / {
        set $upstream_authelia http://192.168.100.2:9091; 
        proxy_pass $upstream_authelia;
        client_body_buffer_size 128k;
 
        #Timeout if the real server is dead
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
 
        # Advanced Proxy Config
        send_timeout 5m;
        proxy_read_timeout 360;
        proxy_send_timeout 360;
        proxy_connect_timeout 360;
 
        # Basic Proxy Config
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_redirect  http://  $scheme://;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_cache_bypass $cookie_session;
        proxy_no_cache $cookie_session;
        proxy_buffers 64 256k;
 
        # If behind reverse proxy, forwards the correct IP
        set_real_ip_from 10.0.0.0/8;
        set_real_ip_from 172.0.0.0/8;
        set_real_ip_from 192.168.0.0/16;
        set_real_ip_from fc00::/7;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
    }
```

and my configuration.yml 
```
#used this site to generate the secret: https://www.grc.com/passwords.htm

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
  file_path: authelia.log
  keep_stdout: true

jwt_secret: '7X23dRXASjdhf8Q2qsiqc4QrvUNDra4OhnVuEuwU='
theme: auto
default_redirection_url: https://auth.abc.com/

#Ref: https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  file:
    watch: true
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

#Ref: https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: deny
  rules:
    - domain: "*.abc.com"
      #policy: two_factor
      policy: one_factor

#Ref: https://www.authelia.com/configuration/session/introduction/
session:
  name: authelia_session
  secret: 'jj4idpHtFASD$kdkr94zfid097ijEbV8J3DwaLf+DR2k='
  domain: abc.com

#Ref: https://www.authelia.com/configuration/security/regulation/
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

#Ref: https://www.authelia.com/configuration/storage/sqlite/
storage:
  encryption_key: 'NqpoEASsda89fBnVYhnt57E93SHeCg='
  local:
    path: /config/db.sqlite3

#Ref: https://www.authelia.com/configuration/notifications/introduction/
notifier:
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
  filesystem:
    filename: /config/notification.txt
# smtp:
#   username: <your-user@your-email-domain.org>
#   password: <your-user-email-password-for-smtp>
#   host: <your-email-host-url-or-ip>
#   port: <your-email-port-for-smtp>  # 25 non-ssl, 443 ssl, 587 tls
#   sender: <sender@your-email-domain.org>
#   subject: "[Authelia] {title}"
#   disable_require_tls: false # set to true if your domain uses no tls or ssl only
#   disable_html_emails: false # set to true if you don't want html in your emails
#   tls:
#     server_name: <your-email-host-url-or-ip>
#     skip_verify: false
#     minimum_version: TLS1.2
```

I can now access the Authelia login page at https://auth.abc.com and successfully log in using the username and password from my user_database.yml. 

here is the docker logs
```
authelia  | time="2025-04-23T13:40:35+08:00" level=info msg="Startup complete"
authelia  | time="2025-04-23T13:40:35+08:00" level=info msg="Watching file for changes" file=/config/users_database.yml service=watcher watcher=users
authelia  | time="2025-04-23T13:40:35+08:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
authelia  | time="2025-04-23T13:46:04+08:00" level=debug msg="Mark 1FA authentication attempt made by user 'alpha'" method=POST path=/api/firstfactor remote_ip=123.123.123.123
authelia  | time="2025-04-23T13:46:04+08:00" level=debug msg="Successful 1FA authentication attempt made by user 'alpha'" method=POST path=/api/firstfactor remote_ip=123.123.123.123
```

However, I am unable to access https://auth.abc.com/.well-known/openid-configuration , it always return 404 not found
and there are nothing wrong in docker logs

Is there anything wrong with my configuration? any suggestion ?
