### DISCUSSION TITLE
Problems encountered with traefik

### DISCUSSION THREAD

**Discussion by ForcemCS** [authelia/authelia#9333] [Q&A] [answered]
I have successfully deployed authelia in a K3S environment, I have an ops platform that is in beta, but has no authentication, so I want to use authelia. for the following configuration
I use curl https://link.h.example.com returns: 404 page not found I don't know what's wrong (I can be sure that the ops platform is fine)
```
root@debian:~/authelia# curl https://op.h.example.com
<!DOCTYPE html>
<html lang="en">
<head>
  <base href="https://op.h.example.com/" />
  <meta property="csp-nonce" content="FmQVlbKh2HPMg1IXY5yL7avPe1f5CfKV" />
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#000000" />
  <meta name="description" content="Authelia login portal for your apps" />
  <link rel="manifest" href="./manifest.json" />
  <link rel="icon" href="./favicon.ico" />
  <title>Login - Authelia</title>
  <script type="module" crossorigin src="./static/js/index.IU4ABaPR.js"></script>
  <link rel="stylesheet" crossorigin href="./static/css/index.BRNgFhlp.css">
</head>

<body
    data-basepath=""
    data-duoselfenrollment="false"
    data-logooverride="false"
    data-privacypolicyurl=""
    data-privacypolicyaccept="false"
    data-passkeylogin="false"
    data-rememberme="true"
    data-resetpassword="true"
    data-resetpasswordcustomurl=""
    data-theme="light"
>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
</body>
</html>
```
```
root@debian:~/authelia# cat link.yaml 
apiVersion: traefik.containo.us/v1alpha1 
kind: Middleware
metadata:
  name: authelia-auth
  namespace: authelia 
spec:
  forwardAuth:

    address: http://authelia.authelia.svc.cluster.local:9091/api/authz/forward-auth?rd=https://op.h.example.com/
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
---
# corrected-link-websecure.yaml
apiVersion: traefik.containo.us/v1alpha1 
kind: IngressRoute
metadata:
  name: tool-service
  namespace: hdh5
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`link.h.example.com`)
      kind: Rule
      middlewares:

        - name: authelia-auth 
          namespace: authelia
        # --- ---
      services:
        - name: tool-service
          port: 80
          scheme: http 
  tls:
    secretName: link-tls
```

**Comment by james-d-elliott** [comment]
Traefik will return a 404 when it can't find a middleware you've configured for a service.

**Reply by ForcemCS** [reply]
However, I feel that the configuration is correct, and I am unsure how to troubleshoot (I am a beginner with Traefik).

**Reply by james-d-elliott** [reply]
Have you looked at the traefik logs after setting them to debug?

**Reply by ForcemCS** [reply]
```yaml
root@debian:/var/lib/rancher/k3s/server/manifests# cat traefik-log.yaml 
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-       
    logs:
      general:
        level: "DEBUG"            
        format: "common"          
        filePath: "/tmp/general.log" 
      access:
        enabled: true
        filePath: "/tmp/access.log" 
        format: "common"          
        #bufferingSize: 0         
        #filters:
        #  # statusCodes: ["200"]  
        #  retryAttempts: true     
        #  minDuration: 20         
      fields:           
        general:
          defaultMode: keep       
          names:                  
            ClientUsername: keep
            StartUTC: drop        
        headers:                
          defaultMode: keep     
          names:                
            # User-Agent: redact
            Authorization: drop
            Content-Type: keep
```

I enabled debugging, but there are no debug logs, only
```
10.10.0.220 - - [25/Apr/2025:03:47:10 +0000] "GET / HTTP/1.1" 404 19 "-" "-" 2900867 "-" "-" 0ms
```

My authelia configuration is as follows. Is there a problem with my configuration?
```
.....
configMap:
  server: { host: 0.0.0.0, port: 9091 }
  log: { level: 'info' }

  session:
    name: 'authelia_session'
    expiration: '1 hour'
    inactivity: '30 minutes'
    cookies:
    - domain: op.h.example.com 
    redis:
      enabled: true
      deploy: true
      host: 'authelia-redis-master.authelia.svc.cluster.local'
  storage:
    postgres:
      enabled: true
      deploy: true
      address: 'authelia-postgresql.authelia.svc.cluster.local:5432'
      username: authelia
      database: authelia
      password:
        disabled: false
        value: authelia
  authentication_backend:
    file:
      enabled: true 
      path: '/config/users_database.yml'
      password:
        algorithm: 'argon2id'
        argon2: { variant: 'argon2id', iterations: 3, memory: 65536, parallelism: 4, key_length: 32, salt_length: 16 }


  access_control:
    default_policy: 'deny' 
    rules: 
      - { domain: "op.h.example.com", policy: bypass }
      - { domain: "link.h.example.com", policy: two_factor }


  notifier:
    smtp: { enabled: false }
    filesystem:
      enabled: true #
      filename: '/config/notifications.log' 
....

```

**Reply by james-d-elliott** [reply]
What happens whern you remove the middleware? There is absolutely no way the authelia config can return a 404 here. It only occurs if traefik does not know the host, can't find the backend app, or a middleware can't be found If there is a config issue with authelia the only status codes that could potentially occur are 401, 403, and 500 I believe. Maybe 501..

**Reply by ForcemCS** [reply, marked as answer]
Once the middleware was removed and I was able to access my operations platform (https://link.h.example.com) normally, I read the official documentation again.

I authelia modified the authelia configuration as follows
```

  session:
    name: 'authelia_session'
    expiration: '1 hour'
    inactivity: '30 minutes'
    cookies:
    - domain: h.example.com 
	  sub
      authelia_url: 'https://op.h.example.com'
    ...........

  access_control:
    default_policy: 'deny' 
    rules: 
      - { domain: "*.h.example.com", policy: two_factor }
	............
```
Regarding Traefik configuration, I referred to https://www.authelia.com/integration/kubernetes/traefik-ingress/. My configuration is as follows, and it is now working as expected.
```
apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'Middleware'
metadata:
  name: 'forwardauth-authelia' 
  namespace: 'hdh5' 
  labels:
    app.kubernetes.io/instance: 'authelia'
    app.kubernetes.io/name: 'authelia'
spec:
  forwardAuth:
    address: 'http://authelia.authelia.svc.cluster.local:9091/api/authz/forward-auth'
    authResponseHeaders:
      - 'Remote-User'
      - 'Remote-Groups'
      - 'Remote-Email'
      - 'Remote-Name'
---
apiVersion: 'networking.k8s.io/v1'
kind: 'Ingress'
metadata:
  name: 'app'
  namespace: 'hdh5'
  annotations:
    traefik.ingress.kubernetes.io/router.entryPoints: 'websecure' # name of your https entry point (default is 'websecure')
    traefik.ingress.kubernetes.io/router.middlewares: 'hdh5-forwardauth-authelia@kubernetescrd' # name of your middleware, as defined in your middleware.yml
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  rules:
    - host: 'link.h.example.com'
      http:
        paths:
          - path: '/'
            pathType: 'Prefix'
            backend:
              service:
                name:  tool-service
                port:
                  number: 80
  tls:
  - hosts:
    - link.h.example.com
    secretName: link-tls

```
