### DISCUSSION TITLE
Email for Reset Password is False

### DISCUSSION THREAD

**Discussion by Hernansandi** [authelia/authelia#9410] [Q&A] [answered]
### Description

I'm trying to use the "Reset Password" feature in Authelia. When I click "Reset Password" and enter a valid username (which exists in LDAP), I only receive a message saying:

> "An email has been sent to your address to complete the process."

However, I never receive any email. Interestingly, when I input a random/invalid username, I also get the _same message_.

I checked the logs, I realized that the email sent was not an email attribute on LDAP but a combined value of username + @gmail.com.
How to deal with it?

### Configuration

I'm using `authentication_backend` with `ldap`:

```
authentication_backend:
  ldap:
    address: 'ldap://openldap:389'
    implementation: 'custom'
    timeout: '5s'
    start_tls: false
    tls:
      server_name: 'ldap.example.com'
      skip_verify: false
      minimum_version: 'TLS1.2'
    base_dn: 'DC=example,DC=com'
    additional_users_dn: 'OU=users'
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    additional_groups_dn: 'OU=groups'
    groups_filter: '(&(objectClass=posixGroup)(memberUid={username}))'
    user: 'CN=admin,DC=exampe,DC=co'
    password: "password"
    attributes:
      distinguished_name: 'distinguishedName'
      username: 'uid'
      display_name: 'displayName'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'

```
