### DISCUSSION TITLE
Unable to use Google as oidc (Configuration: configuration key not expected: authentication_backend.oidc.google.client_id)

### DISCUSSION THREAD

**Discussion by maeffjus** [authelia/authelia#9508] [Q&A] [answered]
Hey, I am trying for two or three days to use Google as my identity provider with the latest image and also with 4.38, none is working.
As soon as I add the oidc provider, the container fails to start. (Before it worked, with just local user authentification)

Here is the part of the config, which I tried in every way I can imagine - also even asked Gemini to look over it with no success:

```
authentication_backend:
  file:
    path: /config/users_database.yml
    watch: true
    password:
      algorithm: argon2id

      iterations: 1    # Standard des CLI-Tools
      memory: 131072   # Standard des CLI-Tools (128MiB)
      parallelism: 4   # Standard des CLI-Tools
      key_length: 32
      salt_length: 16


  oidc:                             
    google:                         
      client_id: "WHATEVER.apps.googleusercontent.com"        
      client_secret: "WHATEVER"  
      issuer: https://accounts.google.com                               
      redirect_uri: https://auth.mydomain.de/api/oidc/callback          
      scopes:                                                             
        - "openid"                                                      
        - "profile"
        - "email"
      username_claim: "email"                                             

```

Any idea - is it a bug or am I just too stupid?

Regards,
Maeffjus
