### DISCUSSION TITLE
Failed to validate authenticator metadata for Authenticator Attestation GUID '00000000-0000-0000-0000-000000000000'

### DISCUSSION THREAD

**Discussion by aureq** [authelia/authelia#9514] [Troubleshooting] [answered]
So, I have an older Yubikey that supports Fido-U2F and in previous versions of Authelia, I was able to register it and use it.

In a more recent version (4.39.3), I'm unable to register that key. 

The debug logs.

```
"Error occurred validating a WebAuthn registration challenge for user 'aureq': error comparing the response to the WebAuthn session data" error="Failed to validate authenticator metadata for Authenticator Attestation GUID '00000000-0000-0000-0000-000000000000'. The authenticator has no registered metadata. (invalid_attestation): Error occurred validating metadata during attestation validation: " method=POST path=/api/secondfactor/webauthn/credential/register remote_ip=192.168.42.127 stack="github.com/authelia/authelia/v4/internal/handlers/handler_register_webauthn.go:214 WebAuthnRegistrationPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/require_auth.go:55            RequireElevated.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                  handlerMain.(*BridgeBuilder).Build.func9.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:65                 SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                 SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                    (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14             handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/metrics.go:23                 handlerMain.NewMetricsRequest.func33.1\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                  RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.62.0/server.go:2455                                 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:225                              (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:197                              (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                           goexit"
```

Wondering if this is related to https://github.com/authelia/authelia/issues/9133 ?

Build-info

```
Last Tag: v4.39.3
State: tagged clean
Branch: v4.39.3
Commit: 48b809ffddb551d0d6a94545e8109311dc709573
Build Number: 43993
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 11 May 2025 21:04:23 +1000
Extra: 

Go:
    Version: go1.24.3 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

Here is the configuration

```yaml
---
# yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39/json-schema/configuration.json
theme: 'dark'
default_2fa_method: 'webauthn'
server:
  address: 'tcp://0.0.0.0:9091/'
  asset_path: ''
  headers:
    csp_template: ""
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6 seconds'
    write: '6 seconds'
    idle: '30 seconds'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz:
      auth-request:
        implementation: 'AuthRequest'
      ext-authz:
        implementation: 'ExtAuthz'
      forward-auth:
        implementation: 'ForwardAuth'
log:
  level: 'debug'
  format: 'text'
  file_path: '/config/authelia.log'
  keep_stdout: true
telemetry:
  metrics:
    enabled: true
    address: 'tcp://0.0.0.0:9959'
    buffers:
      read: 4096
      write: 4096
    timeouts:
      read: '6 seconds'
      write: '6 seconds'
      idle: '30 seconds'
definitions:
  network:
    home:
    - '192.168.0.0/16'
    k8s:
    - '10.0.0.0/8'
identity_validation:
  elevated_session:
    code_lifespan: '5 minutes'
    elevation_lifespan: '10 minutes'
    characters: 8
    require_second_factor: false
    skip_second_factor: false
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
totp:
  disable: true
  issuer: 'Authelia'
  skew: 1
  secret_size: 32
  algorithm: 'SHA1'
  digits: 6
  period: 30
  allowed_algorithms:
    - 'SHA1'
  allowed_digits:
    - 6
  allowed_periods:
    - 30
webauthn:
  disable: false
  enable_passkey_login: false
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  timeout: '60 seconds'
  filtering:
    permitted_aaguids: []
    prohibited_aaguids: []
    prohibit_backup_eligibility: false
  selection_criteria:
    attachment: ''
    discoverability: 'preferred'
    user_verification: 'preferred'
  metadata:
    enabled: true
    validate_trust_anchor: true
    validate_entry: true
    validate_entry_permit_zero_aaguid: false
    validate_status: true
    validate_status_permitted: []
    validate_status_prohibited: []
ntp:
  address: 'udp://ntp.local.example.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: true
    custom_url: ''
  password_change:
    disable: false
  ldap:
    implementation: 'rfc2307bis'
    address: 'ldap://ldap.identity-services.svc'
    timeout: '5 seconds'
    start_tls: false
    tls:
      server_name: ''
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
    pooling:
      enable: false
      count: 5
      retries: 2
      timeout: '10 seconds'
    base_dn: 'DC=example,DC=net'
    additional_users_dn: 'OU=Users'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=inetOrgPerson))'
    additional_groups_dn: 'OU=Authelia,OU=Groups'
    groups_filter: '(&(uniquemember={dn})(objectclass=groupOfUniqueNames))'
    group_search_mode: 'filter'
    permit_referrals: false
    permit_unauthenticated_bind: false
    permit_feature_detection_failure: false
    user: 'CN=authelia,OU=Services,DC=example,DC=net'
    attributes:
      distinguished_name: ''
      username: ''
      display_name: ''
      family_name: ''
      given_name: ''
      middle_name: ''
      nickname: ''
      gender: ''
      birthdate: ''
      website: ''
      profile: ''
      picture: ''
      zoneinfo: ''
      locale: ''
      phone_number: ''
      phone_extension: ''
      street_address: ''
      locality: ''
      region: ''
      postal_code: ''
      country: ''
      mail:  ''
      member_of:  ''
      group_name:  ''
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: false
    require_lowercase: false
    require_number: false
    require_special: false
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '12 hours'
  expiration: '14 hours'
  remember_me: '1 month'
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://login.example.com'
      default_redirection_url: 'https://www.example.com'
regulation:
  modes:
  - 'user'
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'
storage:
  local:
    path: '/config/db.sqlite3'
notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp://smtp.mail-services.svc.cluster.local'
    timeout: '5 seconds'
    username: ''
    sender: 'Authelia <admin@example.com>'
    identifier: 'localhost'
    subject: '[Authelia] {title}'
    startup_check_address: 'test@authelia.com'
    disable_html_emails: false
    disable_require_tls: false
    disable_starttls: false
    tls:
      server_name: 'www.example.com'
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
identity_providers:
  oidc:
    lifespans:
      access_token: '1 hour'
      refresh_token: '1 hour and 30 minutes'
      id_token: '1 hour'
      authorize_code: '1 minute'
      device_code: '10 minutes'
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_client_debug_messages: false
    enable_jwt_access_token_stateless_introspection: false
    minimum_parameter_entropy: 8
    discovery_signed_response_alg: ''
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/secrets/authelia-secrets/oidc.private.key" | mindent 10 "|" | msquote }}
    cors:
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'harbor-registry-system'
        client_name: 'Harbor'
        client_secret: '{{ secret "/secrets/authelia-secrets/oidc.client.harbor-registry-system.txt" }}'
        public: false
        redirect_uris:
          - 'https://registry.k8s.local.example.com/c/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'two_factor'
        consent_mode: 'auto'
        require_pushed_authorization_requests: false
        require_pkce: false
        pkce_challenge_method: ''
        authorization_signed_response_alg: 'none'
        authorization_signed_response_key_id: ''
        authorization_encrypted_response_key_id: ''
        authorization_encrypted_response_alg: ''
        authorization_encrypted_response_enc: ''
        id_token_signed_response_alg: 'RS256'
        id_token_signed_response_key_id: ''
        id_token_encrypted_response_key_id: ''
        id_token_encrypted_response_alg: ''
        id_token_encrypted_response_enc: ''
        access_token_signed_response_alg: 'none'
        access_token_signed_response_key_id: ''
        access_token_encrypted_response_key_id: ''
        access_token_encrypted_response_alg: ''
        access_token_encrypted_response_enc: ''
        userinfo_signed_response_alg: 'none'
        userinfo_signed_response_key_id: ''
        userinfo_encrypted_response_key_id: ''
        userinfo_encrypted_response_alg: ''
        userinfo_encrypted_response_enc: ''
        introspection_signed_response_alg: 'none'
        introspection_signed_response_key_id: ''
        introspection_encrypted_response_key_id: ''
        introspection_encrypted_response_alg: ''
        introspection_encrypted_response_enc: ''
        introspection_endpoint_auth_method: 'client_secret_basic'
        introspection_endpoint_auth_signing_alg: 'RS256'
        request_object_signing_alg: ''
        request_object_encryption_alg: 'none'
        request_object_encryption_enc: ''
        token_endpoint_auth_method: 'client_secret_basic'
        token_endpoint_auth_signing_alg: ''
        revocation_endpoint_auth_method: 'client_secret_basic'
        revocation_endpoint_auth_signing_alg: 'RS256'
        pushed_authorization_request_endpoint_auth_method: 'client_secret_basic'
        pushed_authorization_request_endpoint_auth_signing_alg: 'RS256'
access_control:
  default_policy: 'deny'
  rules:
    - policy: two_factor
      domain:
        - 'docs.example.com'
      subject:
        - ['group:Administrators']
      resources:
        - '^/restricted/.*'
```

and running `authelia validate-config` returns `Configuration parsed and loaded successfully without errors.

**Comment by Crowley723** [comment]
You should share your configuration, build info, and some more logs.

It may be possible that you have a misconfiguration that is excluding the key with an unknown AAGUID.

**Reply by aureq** [reply]
Hi @Crowley723 I updated the original comment. As for the AAGUID configuration, I have left the default values that are present in the Helm Chart.

**Comment by james-d-elliott** [comment, marked as answer]
The authenticator is not performing attestation or returning an attestation statement with an empty AAGUID. You have the following settings configured which requires the authenticator prove it's lineage (i.e. that it's not fake):

```yaml
webauthn:
  metadata:
    enabled: true
    validate_entry_permit_zero_aaguid: false
```

You can change either of these and it may allow this non-compliant authenticator.
