### DISCUSSION TITLE
immich: How to setup immich_quota claim?

### DISCUSSION THREAD

**Discussion by Splinter7914** [authelia/authelia#9521] [Q&A] [answered]
[Immich oauth](https://immich.app/docs/administration/oauth/) metions `immich_quota` claim that can be used to control the quota of the user created.

I have not been able to get it to work. Here is what i tried. I followed [oidc cliams](https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/) and [immich oidc connect](https://www.authelia.com/integration/openid-connect/immich/) documentation.

Running: `authelia version v4.39.3` in docker.

I am using lldap for authentication backend and created a user attribute called `immich_quota` in lldap. For the user I am testing i set the value of it to 25.

```
authentication_backend:
  # Password reset through authelia works normally.
  password_reset:
    disable: false
  # How often authelia should check if there is a user update in LDAP
  refresh_interval: 1m
  ldap:
    implementation: lldap
    address: ldap://lldap:3890
    # issue using env for these values
    base_dn: {{ secret "/secrets/lldap_base_dn" }}
    # The username and password of the bind user.
    # "bind_user" should be the username you created for authentication with the "lldap_strict_readonly" permission. It is not recommended to use an actual admin account here.
    # If you are configuring Authelia to change user passwords, then the account used here needs the "lldap_password_manager" permission instead.
    # issue using env for these values
    user: {{ secret "/secrets/lldap_user" }}
    password: '{{ secret "/secrets/lldap_password" }}'
    attributes:
      extra:
        immich_quota:
          multi_valued: false
          value_type: 'string'
```

Then under `oidc` i added custom claims and scopes

```
    claims_policies:
      immich:
        custom_claims:
          immich_quota:
            attribute: 'immich_quota'
    scopes:
      immich:
        claims:
          - 'immich_quota'
```

then I added the claims and scopes to the immich client. I am not sure if I was suppose to add both scopes and claims policy or just one. I also tried with only adding either to scopes or claims policy.

```
scopes:
  - 'openid'
  - 'profile'
  - 'email'
  - 'immich'
claims_policy: 'immich'
```

Even though the user had immich_quota set to a specific value in lldap it kept getting the quota set to 10GB in immich. Authelia, lldap and oidc etc are all new to me so may be I am missing something simple :).
