### DISCUSSION TITLE
Authelia container is not starting - configuration wrong?

### DISCUSSION THREAD

**Discussion by tauchvogel** [authelia/authelia#9538] [Troubleshooting] [answered]
Hi there,

I try to start authelia docker via Portainer. My stack is that:
```
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    volumes:
      - ./config:/config  # ✅ nur ein Mountpunkt, sauber
    ports:
      - "9091:9091"
    environment:
      - TZ=Europe/Berlin
```

M yconfiguration.yml is like that:
```
log:
  level: info

host: 0.0.0.0
port: 9091

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: "*.mydomain.com"
      policy: one_factor

session:
  name: authelia_session
  secret: "secret_token_here"
  expiration: 3600
  inactivity: 300
  cookies:
    - name: authelia_session
      domain: mydomain.com
      authelia_url: https://mydomain.com

storage:
  encryption_key: "secret_token_here"
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```

My logs are now:
```
time="2025-05-18T16:31:52+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"

time="2025-05-18T16:32:44+02:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"

time="2025-05-18T16:32:44+02:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"

time="2025-05-18T16:32:44+02:00" level=error msg="Configuration: session: option 'cookies' is required"

time="2025-05-18T16:32:44+02:00" level=error msg="Configuration: storage: option 'encryption_key' is required"

time="2025-05-18T16:32:44+02:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"

time="2025-05-18T16:32:44+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"

time="2025-05-18T16:32:44+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
```

What can I do? Please help me.
