### DISCUSSION TITLE
I'm not able to sign in authelia

### DISCUSSION THREAD

**Discussion by sandraimmaculate** [authelia/authelia#9551] [Q&A] [answered]
Hello Team,
I have installed of version authelia version v4.39.3 not in docker using the below commands 
Step 1: Installing Authelia
Add the Authelia's signing keys so the packages can be installed on your system

$ curl https://apt.authelia.com/organization/signing.asc | sudo apt-key add -
Then register the repository address and fetch it:

$ sudo apt-get install apt-transport-https --yes
$ echo "deb https://apt.authelia.com/stable/debian/debian/ all main" | sudo tee /etc/apt/sources.list.d/authelia-stable-debian.list
$ sudo apt-get update
Finally, install it

$ sudo apt install authelia

as after completion i authelia was not running may be beacuse of the yaml formate so i changed below is my configuration file 
```
identity_validation:
  reset_password:
    jwt_secret: Emu4m6sTfTQb9hZJQUEpKTkumCaDmJumBTgsbkCXziM=

authentication_backend:
  file:
    path: /etc/authelia/users_database.yml

access_control:
  default_policy: one_factor
  rules:
    - domain: "*.cocolab.duckdns.org"
      policy: two_factor

session:
  name: authelia_session
  secret: uLw1X8T3i4mXIJCpEQpfdmp0Xbwoxcfb2NVZ6fF+hsoy2dh+NvUSCAgDQ1Yv7lc8hRS2Uk0ugK8Dk9Ke5CfMCA==
  expiration: 3600  # 1 hour
  inactivity: 300   # 5 minutes
  domain: cocolab.duckdns.org

storage:
  encryption_key: 3RzxvqwVkue9SpBdCb6IcVn8/ikJVT/aEFndAx3Px8Y=
  local:
    path: /etc/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /etc/authelia/notification.txt
log:
  level: debug
  format: json
  file_path: /etc/authelia/authelia.log
```
and my nginx configurations are 
```
cat /etc/nginx/conf.d/cocolab.duckdns.org.conf 
server {
    listen 8888;
    server_name cocolab.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/letsencryptbase;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 7443 ssl;
    server_name cocolab.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/cocolab.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cocolab.duckdns.org/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/cocolab.duckdns.org/chain.pem;
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
    add_header X-Frame-Options SAMEORIGIN;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Content-Type-Options nosniff;
    add_header Permissions-Policy "geolocation=(self), camera=(), speaker=()";
    add_header X-XSS-Protection "1; mode=block";
    proxy_set_header X-Forwarded-Proto $scheme;


   location /.well-known/acme-challenge/ {
        root /usr/share/nginx/letsencryptbase;
    }

    location / {
        proxy_pass http://127.0.0.1:9091;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
cat /etc/nginx/sites-available/cocolab.duckdns.org 
# Redirect HTTP to HTTPS
server {
    server_name auth.cocolab.duckdns.org;
    listen 8888;
    return 301 https://$server_name$request_uri;
}

# HTTPS server for your application
server {
    server_name .cocolab.duckdns.org;
    listen 7443 ssl http2;

    ssl_certificate /etc/letsencrypt/live/cocolab.duckdns.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cocolab.duckdns.org/privkey.pem; # managed by Certbot
    ssl_session_cache shared:SSL:2m;

    # Include Authelia internal endpoint (used for auth_request)
    include snippets/authelia.conf;

    location / {
        # Protect this route with Authelia
        include snippets/auth.conf;

        proxy_pass http://127.0.0.1:9091;  # 👈 Your actual app backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

```
location /authelia {
    internal;
    set $upstream_authelia http://127.0.0.1:9091/api/verify;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;    
    proxy_set_header Content-Length "";

    proxy_pass_header Content-Security-Policy;

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # [REQUIRED] Needed by Authelia to check authorizations of the resource.
    # Provide either X-Original-URL and X-Forwarded-Proto or
    # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
    # Those headers will be used by Authelia to deduce the target url of the     user.
    # Basic Proxy Config
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr; 
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
```
```
auth_request /authelia;
auth_request_set $target_url $scheme://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;

proxy_set_header Remote-User $user;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name $name;
proxy_set_header Remote-Email $email;

error_page 401 =302 https://cocolab.duckdns.org/?rd=$target_url;
```


i want to configure authelia for carbonio to enable 2fa im totally getting confused please help me! 
thanks in advance
