### DISCUSSION TITLE
Authelia x Zoraxy

### DISCUSSION THREAD

**Discussion by james-d-elliott** [authelia/authelia#9583] [Troubleshooting]
@7brend7 regarding https://github.com/tobychui/zoraxy/issues/33#issuecomment-2912083743 what authelia logs are you getting when this occurs?

**Comment by 7brend7** [comment]
@james-d-elliott thanks for looking into it...
so, e.g. I'm trying to open `home.mypublicdomain.com` in incognito without any  auth:

```
authelia  | time="2025-05-27T19:24:48Z" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handlerMain.LogRequest.func31" method=GET path=/ remote_ip=172.19.0.1
authelia  | time="2025-05-27T19:24:48Z" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handlerMain.LogRequest.func31" method=GET path=/ remote_ip=172.19.0.1
authelia  | time="2025-05-27T19:24:58Z" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handlerMain.LogRequest.func31" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:58Z" level=debug msg="Check authorization of subject username= groups= ip=11.11.11.11 and object https://authelia.mypublicdomain.com/ (method GET)." caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:52 (*Authorizer).GetRequiredLevel"
authelia  | time="2025-05-27T19:24:58Z" level=trace msg="ACL HIT Position 1 for subject username= groups= ip=11.11.11.11 and object https://authelia.mypublicdomain.com/ (method GET, policy one_factor)" caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:57 (*Authorizer).GetRequiredLevel"
authelia  | time="2025-05-27T19:24:58Z" level=info msg="Access to https://authelia.mypublicdomain.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mypublicdomain.com/?rd=https%3A%2F%2Fauthelia.mypublicdomain.com%2F&rm=GET" caller="github.com/authelia/authelia/v4/internal/handlers/handler_authz_impl_forwardauth.go:53 handleAuthzUnauthorizedForwardAuth" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:58Z" level=trace msg="Replied (status=401)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handlerMain.LogRequest.func31" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:58Z" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handlerMain.LogRequest.func31" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:58Z" level=debug msg="Check authorization of subject username= groups= ip=11.11.11.11 and object https://authelia.mypublicdomain.com/ (method GET)." caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:52 (*Authorizer).GetRequiredLevel"
authelia  | time="2025-05-27T19:24:58Z" level=trace msg="ACL HIT Position 1 for subject username= groups= ip=11.11.11.11 and object https://authelia.mypublicdomain.com/ (method GET, policy one_factor)" caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:57 (*Authorizer).GetRequiredLevel"
authelia  | time="2025-05-27T19:24:58Z" level=info msg="Access to https://authelia.mypublicdomain.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mypublicdomain.com/?rd=https%3A%2F%2Fauthelia.mypublicdomain.com%2F&rm=GET" caller="github.com/authelia/authelia/v4/internal/handlers/handler_authz_impl_forwardauth.go:53 handleAuthzUnauthorizedForwardAuth" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:58Z" level=trace msg="Replied (status=401)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handlerMain.LogRequest.func31" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:59Z" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handlerMain.LogRequest.func31" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:59Z" level=debug msg="Check authorization of subject username= groups= ip=11.11.11.11 and object https://authelia.mypublicdomain.com/ (method GET)." caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:52 (*Authorizer).GetRequiredLevel"
authelia  | time="2025-05-27T19:24:59Z" level=trace msg="ACL HIT Position 1 for subject username= groups= ip=11.11.11.11 and object https://authelia.mypublicdomain.com/ (method GET, policy one_factor)" caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:57 (*Authorizer).GetRequiredLevel"
authelia  | time="2025-05-27T19:24:59Z" level=info msg="Access to https://authelia.mypublicdomain.com/ (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mypublicdomain.com/?rd=https%3A%2F%2Fauthelia.mypublicdomain.com%2F&rm=GET" caller="github.com/authelia/authelia/v4/internal/handlers/handler_authz_impl_forwardauth.go:53 handleAuthzUnauthorizedForwardAuth" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
authelia  | time="2025-05-27T19:24:59Z" level=trace msg="Replied (status=401)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handlerMain.LogRequest.func31" method=GET path=/api/authz/forward-auth remote_ip=11.11.11.11
```

I dont see any attempt to query `home.mypublicdomain.com`, so it seams like wrong configuration:
```
access_control:
  default_policy: 'deny'
  rules:
    - domain:
        - "*.mypublicdomain.com"
      policy: one_factor

storage:
  local:
    path: '/config/db.sqlite3'

authentication_backend:
  file:
    path: '/config/users_database.yml'

log:
  level: 'trace'

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'

session:
  cookies:
    -
      name: 'authelia_session'
      domain: 'mypublicdomain.com'
      authelia_url: 'https://authelia.mypublicdomain.com'
      same_site: 'lax'
      inactivity: '5 minutes'
      expiration: '2 hours'
      remember_me: '1 month'

  redis:
    host: redis_authelia
    port: 6379

regulation:
  max_retries: 3
  find_time: 5m
  ban_time: 15m

server:
  address: 'tcp://:9091/'
```

but if I whitelisted authelia - all subdomains can be opened without auth
```
- domain:
        - "authelia.mypublicdomain.com"
      policy: bypass
```
