### DISCUSSION TITLE
Issue when loading secrets: Configuration: secrets: error loading secret path  '/secrets/JWT_SECRET

### DISCUSSION THREAD

**Discussion by jericho63** [authelia/authelia#9598] [Troubleshooting] [answered]
Hello,

I cannot seem to load any secrets into the configuration file. I have all my secrets in authelia/secrets which is mapped to /secrets/ in the container. 
No matter what I try, I am getting an error saying ```
" level=error msg="Configuration: secrets: error loading secret path  '/secrets/JWT_SECRET' into key 'identity_validation.reset_password.jwt_secret
': file does not exist error occurred: open  '/secrets/JWT_SECRET': no such file or directory"" 
```

I need an exterior eye, , i have Read the documentation and i' dont see what i miss.

here my docker compose file

`services: 
authelia:
image: ghcr.io/authelia/authelia:4.39.3
container_name: authelia
user: "1000:1000"

environment:
 - TZ=Europe/Paris
 - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE= '/secrets/JWT_SECRET'
 - AUTHELIA_SESSION_SECRET_FILE= '/secrets/SESSION_SECRET'
 - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/secrets/STORAGE_PASSWORD'
 - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE= '/secrets/STORAGE_ENCRYPTION_KEY'
networks:
default:
volumes:
 - '/data/authelia/config/:/config'
 - '/data/authelia/secrets/:/secrets:ro'
restart: unless-stopped`

**Comment by james-d-elliott** [comment]
`ls -al /data/authelia/secrets`

**Reply by jericho63** [reply]
hello

`-rw-rw---- 1 francois francois  129 27 mai   21:25 JWT_SECRET
-rw-rw---- 1 francois francois  129 27 mai   21:35 SESSION_SECRET
-rw-rw---- 1 francois francois  129 27 mai   21:35 STORAGE_ENCRYPTION_KEY
`

**Reply by james-d-elliott** [reply]
Have you done a `docker compose up -d` recently?

**Reply by jericho63** [reply]
yes , i did it there is some minutes and always the same error

**Reply by james-d-elliott** [reply]
Please show both the full input and output of the `ls` command above, fairly sure this is a path issue.

**Reply by jericho63** [reply]
`francois@srv-home-docker:~$ ls -al /data/authelia/secrets
total 20
drwxr-xr-x 2 francois francois 4096 28 mai   16:46 .
drwxr-xr-x 4 francois francois 4096 28 mai   17:07 ..
-rw-rw---- 1 francois francois  129 27 mai   21:25 JWT_SECRET
-rw-rw---- 1 francois francois  129 27 mai   21:35 SESSION_SECRET
-rw-rw---- 1 francois francois  129 27 mai   21:35 STORAGE_ENCRYPTION_KEY
`

**Reply by james-d-elliott** [reply]
Very odd. Add the following modifications to your compose and do `docker compose up -d` again, then execute `docker execute authelia ls /secrets`:

```yaml
services:
  authelia:
    healthcheck:
      disable: true
    environment:
      - AUTHELIA_LOG_LEVEL=trace
    command: 'sleep 3300'
```

**Reply by james-d-elliott** [reply, marked as answer]
Also this has a mix of `=` and `:` for envs; you need to use one, I'd recommend `:` as it is vastly superior at putting the compose in compose (see the second example):

```yaml
environment:
 - TZ=Europe/Paris
 - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE= '/secrets/JWT_SECRET'
 - AUTHELIA_SESSION_SECRET_FILE= '/secrets/SESSION_SECRET'
 - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/secrets/STORAGE_PASSWORD'
 - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE= '/secrets/STORAGE_ENCRYPTION_KEY'
```

```yaml
    environment:
      TZ: 'Europe/Paris'
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/secrets/STORAGE_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      AUTHELIA_LOG_LEVEL: 'trace'
```
