### DISCUSSION TITLE
authelia, traefik, cloudflared integration

### DISCUSSION THREAD

**Discussion by anatoidgit** [authelia/authelia#9641] [Troubleshooting]
Hello,
I've been trying to setup rediracting to auth.domain.com for 2 days now, but I just cannot pull it off. As of right now I have traefik listening at :80 and redirecting every subdomain to the proper localhost:port. As for the authelia, I'm redirecting auth.domain.com using cloudflared (hence no auth.domain.com router in my dynamic.yml). Whenever I try to add a middleware to redirect my subdomains to auth. I get 401 unauthorized (as if they we're denied access by auth., which they didn't reach at all (no login panel appeares)).

I'm posting my files (excluding the actual domains/subdomains and uuids), hoping someone more advanced could help me!

Cheers

sidenotes:
- I'm tunneling each subdomain through cloudflare
- Every sub.domain.com works unless I add the authelia-auth middleware section to the router block

/docker/traefik/docker-compose.yml
```
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/dev-disk-by-uuid-XXXX/docker/traefik/traefik.yml:/traefik>
      - /srv/dev-disk-by-uuid-XXXX/docker/traefik/dynamic.yml:/dynamic>
    networks:
      - traefik
  homepage:
    image: nginx:alpine
    container_name: homepage
    volumes:
     - /srv/dev-disk-by-uuid-XXXX/docker/traefik/homepage:/usr/share/n>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`home.domain.com`) || Host(`domain.com`) || Host(`www.domain.com`)"
      - "traefik.http.routers.home.entrypoints=web"
      - "traefik.http.services.home.loadbalancer.server.port=80"
    networks:
      - traefik
networks:
  traefik:
    external: true
```
    
/docker/traefik/dynamic.yml

```
http:
  routers:
    example:
      rule: "Host(`example.domain.com`)"
      entryPoints:
        - "web"
      service: example-service
      middlewares:
        - forwarded-headers@file
        - authelia-auth@file

  middlewares:
    authelia-auth:
      forwardAuth:
        address: http://authelia:9091/api/verify
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
          - Remote-Preferred-Username
  services:
    example-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.100:8080"
```          

          
/docker/authelia/docker-compose.yml

```
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    ports:
      - "0.0.0.0:9091:9091"
    volumes:
      - ./config:/config
#      - ./users_database.yml:/config/users_database.yml
    environment:
      - TZ=Europe/Warsaw
    networks:
      - traefik

networks:
  traefik:
    external: true 
```    
    
/docker/authelia/config/configuration.yml

```
server:
  address: tcp://0.0.0.0:9091

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: example
authentication_backend:
  file:
    path: /config/users_database.yml


access_control:
  default_policy: deny
  rules:
    - domain: "*.domain.com"
      policy: one_factor
    - domain: auth.domain.com
      policy: bypass


session:
  name: authelia_session
  secret: example
  expiration: 3600
  inactivity: 300
  cookies:
    - domain: domain.com
      authelia_url: https://auth.domain.com
      default_redirection_url: https://home.domain.com


storage:
  encryption_key: example
  local:
    path: /config/db.sqlite3


notifier:
  filesystem:
    filename: /config/notification.txt
```
