### DISCUSSION TITLE
Configuring oidc jwks key via file

### DISCUSSION THREAD

**Discussion by keunes** [authelia/authelia#9650] [Q&A] [answered]
Hello,
I'm trying to set up Authelia with Docker compose. In my configuration file, I (want to) specify the following:
```yaml
identity_providers:
  oidc:
    jwks:
      - key : [something]
```

https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#key notes:
> It is recommended that you use a file to specify this particular option.

As a beginning homelab geek I want to follow this recommendation. However, using the provided example on the same page (`{{ secret "/config/secrets/oidc/jwks/rsa.2048.key" | mindent 10 "|" | msquote }}`) doesn't work. I've read the 'File filters' documentation page that is linked, but I don't quite understand it. ChatGPT seems to suggest it's related to Kubernetes (which I'm not using).

https://www.authelia.com/configuration/prologue/security-sensitive-values/ and https://www.authelia.com/integration/deployment/docker/ don't really give examples or tell what to do.

https://github.com/authelia/authelia/discussions/8132#discussioncomment-11098916 notes:
> We don't support inserting multiline strings from env vars. You'll need to use a file as the source like shown in the example you linked.

So my question is: is that possible in Docker? And if so, how?

**Comment by Crowley723** [comment]
Gpt is partially correct, the go templating is heavily used in kubernetes, specifically for helm. That said, authelia uses go and thus we can make use of the same templating.

You need to make sure you enable the `template` file filter, then you can use something like this:

```yaml
identity_providers:
  oidc:
    jwks:
      - key_id: example
        algorithm: RS256
        use: sig
        key: {{ secret "/secrets/jwks_rsa_2048_private.txt" | mindent 10 "|" | msquote }}
```
(This is directly from my config)

Which will properly insert the private key into the config when authelia starts.

**Reply by keunes** [reply]
Thanks @Crowley723 for the quick reply!
I've changed from the embedded key to the file reference:
```
identity_providers:
  oidc:
    hmac_secret: 'sanitised' # Generate: openssl rand -hex 32
    jwks:
      - key: {{ secret "/config/secrets/oidc/jwks/private.pem" | mindent 10 "|" | msquote }}
```
Logging into the interactive shell confirms that the file is on the expected path:
```
docker exec -it authelia sh
/app # ls /config/secrets/oidc/jwks/p
private.pem  public.pem
```
I have added also the following to my Docker compose, which I understand is the way to 'enable the `template` file filter':
```
    environment:
      - AUTHELIA_CONFIGURATION_FILTERS=template
```
I'm getting an error though:
```
Configuration: failed to load configuration from file path(/config/configuration.yml) source: yaml: invalid map key: map[string]interface {}{\"secret \\\"/config/secrets/oidc/jwks/private.pem\\\" | mindent 10 \\\"|\\\" | msquote\":interface {}(nil)}" caller="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1
```
I suppose I'm missing something here - but what? :-)
