### DISCUSSION TITLE
Default session inactivity setting not applied? / Authelia session not expiring

### DISCUSSION THREAD

**Discussion by keunes** [authelia/authelia#9660] [Troubleshooting]
I've set up Authelia and it's working quite well :-)

One point I don't quite understand, however, is that my sessions don't seem to expire. Once I log in to Authelia, if I want to authenticate with an app 15 minutes later, I can do that without having to enter my Authelia credentials again.

I wouldn't expect this to work, because I have not set any session specifics set up:
```
session:
  cookies:
    - domain: 'mydomain.nl'
      authelia_url: 'https://auth.mydomain.nl'
```

Given the default session inactivity setting being 5 minutes ([docs](https://www.authelia.com/configuration/session/introduction/#inactivity)), I would expect to be prompted to provide my credentials again.

I'm using 'Memory' as the session storage provider.
