### DISCUSSION TITLE
Error occurred saving consent pre-configuration to the database

### DISCUSSION THREAD

**Discussion by robalecal** [authelia/authelia#9675] [Q&A] [answered]
Hi,

I'm trying to make use of the pre_configured_consent_duration for OIDC clients however when I authenticate and then check the _Remember Consent_ box and accept consent, nothing happens.

Looking in the logs, I see the following error:

```
{
  "time": "2025-06-14T12:57:46+01:00",
  "level": "error",
  "msg": "Error occurred saving consent pre-configuration to the database",
  "client_id": "<client_id>",
  "error": "error inserting oauth2 consent pre-configuration for subject 'f92489f2-521c-439b-b76a-d6070941dc06' with client id <client_id> and scopes 'openid email': ERROR: null value in column \\\"id\\\" of relation \\\"oauth2_consent_preconfiguration\\\" violates not-null constraint (SQLSTATE 23502)",
  "flow_id": "a17ca9d4-a8ad-428e-a86a-ed5fb775fae0",
  "method": "POST",
  "path": "/api/oidc/consent",
  "remote_ip": "10.0.0.4",
  "session_id": "258",
  "stack": "github.com/authelia/authelia/v4/internal/handlers/handler_oauth2_consent.go:337 handleOAuth2ConsentFlowIDPOST\\ngithub.com/authelia/authelia/v4/internal/handlers/handler_oauth2_consent.go:169 OAuth2ConsentPOST\\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66               RegisterOpenIDConnectRoutes.(*BridgeBuilder).Build.func2.1\\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105             SecurityHeadersNoStore.func1\\ngithub.com/valyala/fasthttp@v1.62.0/server.go:773                               (*RequestCtx).UserValue\\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30              SecurityHeadersBase.func1\\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                 (*Router).Handler\\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14          handlerMain.LogRequest.func31\\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:23           handlerMain.StripPath.func32.1\\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38               RecoverPanic.func1\\ngithub.com/valyala/fasthttp@v1.62.0/server.go:2455                              (*Server).serveConn\\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:225                           (*workerPool).workerFunc\\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:197                           (*workerPool).getCh.func1\\nruntime/asm_amd64.s:1700                                                        goexit",
  "username": "<username>"
}
```

I checked the database and I can see in the oauth2_consent_session for the client_id, that there are rows corresponding to each session:

```
...
id                 | 249
challenge_id       | 56d00f62-f2d0-4f88-b775-5ed39e3169a7
client_id          | <client_id>
subject            | f92489f2-521c-439b-b76a-d6070941dc06
authorized         | t
granted            | t
requested_at       | 2025-06-14 10:46:25.238941+01
responded_at       | 2025-06-14 10:56:08.120395+01
form_data          | client_id=<client_id>&redirect_uri=https%3A%2F%2Flubelogger.example.com%2FLogin%2FRemoteAuth&response_type=code&scope=openid+email&state=70196821
requested_scopes   | openid|email
granted_scopes     | openid|email
requested_audience | 
granted_audience   | 
preconfiguration   | 
granted_claims     | 
expires_at         | 2000-01-01 00:00:00+00
...
```

However the oauth2_consent_preconfiguration table remains empty (which is presumably the issue, I'm just not sure why):
```

 id | client_id | subject | created_at | expires_at | revoked | scopes | audience | requested_claims | signature_claims | granted_claims 
----+-----------+---------+------------+------------+---------+--------+----------+------------------+------------------+----------------
(0 rows)

```
Here is the configuration for the client_id in question (I have the same issue regardless of the client I try):
```
  oidc:
    ## The hmac_secret is used to sign OAuth2 tokens (authorization code, access tokens and refresh tokens).
    ## HMAC Secret can also be set using a secret: https://www.authelia.com/c/secrets
    hmac_secret: '<hmac_secret>'

    ## The JWK's issuer option configures multiple JSON Web Keys. It's required that at least one of the JWK's
    ## configured has the RS256 algorithm. For RSA keys (RS or PS) the minimum is a 2048 bit key.
    jwks:
      -
      ## Key ID embedded into the JWT header for key matching. Must be an alphanumeric string with 7 or less characters.
      ## This value is automatically generated if not provided. It's recommended to not configure this.
      # key_id: 'example'

      ## The key algorithm used with this key.
      # algorithm: 'RS256'

      ## The key use expected with this key. Currently only 'sig' is supported.
      # use: 'sig'

      ## Required Private Key in PEM DER form.
       key: |
         -----BEGIN PRIVATE KEY-----
         <key>
         -----END PRIVATE KEY-----

    ## Authorization Policies which can be utilized by clients. The 'policy_name' is an arbitrary value that you pick
    ## which is utilized as the value for the 'authorization_policy' on the client.
    authorization_policies:
      default:
        default_policy: 'two_factor'
        rules:
          - policy: 'deny'
            subject:
              - 'user:guest'

    claims_policies:
      ## Creates the 'default' claims policy.
      default:
        id_token: ['groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
      legacy_claims:
        id_token: ['email', 'email_verified', 'preferred_username', 'name']
    
    clients:
     - client_id: '<client_id>'
        client_name: 'LubeLogger'
        client_secret: '<client_secret>'
        public: false
        authorization_policy: 'default'
        redirect_uris:
          - 'https://lubelogger.example.com/Login/RemoteAuth'
          #- 'https://lubelogger.example.com/Login/RemoteAuthDebug'
        ## Assigns the 'legacy_claims' claims policy to this client.
        claims_policy: 'legacy_claims'
        pre_configured_consent_duration: 4w
        scopes:
          - 'openid'
          - 'email'
        grant_types:
          - 'authorization_code'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
```

I'm not sure where I'm going wrong so any guidance would be much appreciated! Let me know if any more information would be helpful.

EDIT: formatting
