### DISCUSSION TITLE
Issue with redirect URL for opkssh

### DISCUSSION THREAD

**Discussion by vigneshmanick** [authelia/authelia#9691] [Troubleshooting]
Hello all,

I am testing authelia and have managed to setup it up to use for a couple of integrations which is working as expected. I have run into an issue with configuring it for `opkssh` according to the documentation here https://www.authelia.com/integration/openid-connect/opkssh/

-  If the configuration is set to `token_endpoint_auth_method: client_secret_basic` as explained in the documentaion, Authelia errors out saying that the option should be set to none
- After removing the above option , authelia starts successfully but then during login i run into another issue. 
  - The redirect uri set in the configuration is as follows

```yml
identity_providers:
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    clients:
      - client_id: 'opkssh'
        client_name: 'opkssh'
        public: true
        require_pkce: true
        pkce_challenge_method: 'S256'
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'http://localhost:3000/login-callback'
          - 'http://localhost:10001/login-callback'
          - 'http://localhost:11110/login-callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
```
  - after executing `.\opkssh-windows-amd64.exe login --provider=https://auth.my-domain.com,opkssh`, i get to the authelia login portal and am able to identify with the credentials successfully but after login and clicking on accept the browser errors out with the following message (the `http` url is redirecting to `https`)

![image](https://github.com/user-attachments/assets/d16e6da8-c10a-4d2e-ad79-7d5efa586e4a)

![image](https://github.com/user-attachments/assets/f39c9a04-fd9d-4c2f-85a5-e4f5d2c44878)

  - based on a tip i recieved from opkssh developer, i commented out the line in `proxy.conf` `proxy_redirect http:// $scheme://` but this setting is suggested in documentation for `nginx` integration. 
  
```
## Basic Proxy Configuration
client_body_buffer_size 128k;
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503; ## Timeout if the real server is dead.
#proxy_redirect  http://  $scheme://;
```

Question is:

- Is it ok to comment out this line?, from what i understand this causes nginx to stop redirecting http requests to https, this is required for `opkssh` but does this have impact on the `authelia` instance itself? or are there other options that can be specified instead of this?
  - The log that i have from nginx for this is
  
`231befdb72b5 44.23.28.21- - [19/Jun/2025:06:17:13] "GET /api/oidc/authorization?access_type=offline&client_id=somelongid&code_challenge_method=S256&consent_id=longid&prompt=consent&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin-callback&response_type=code&scope=openid+profile+email+groups&state=stateid HTTP/2.0" 303 0 "https://auth.my-domain.com/consent/openid/decision?flow=openid_connect&flow_id=somelongid" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0" "-"`

- Is the error about `token_endpoint_auth_method` ok? or have i made other configuration errors?

Authelia version:  `v4.39.4`
Opkssh version: `0.7.0`
Running in : `Podman`
Proxy: `Nginx`

Nginx configuration

```conf
server {
    listen 80;
    server_name auth.my-domain.com;

    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name auth.my-domain.com 

    ssl_certificate /etc/nginx/conf.d/certs/auth.my-domain.pem;
    ssl_certificate_key /etc/nginx/conf.d/certs/auth.my-domain.key;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    set $upstream http://authelia:9091;

    location / {
        proxy_pass http://127.0.0.1:9091; # default port for authelia

        include /etc/nginx/conf.d/snippets/proxy.conf; 
        client_max_body_size 512M;
    }

    location = /api/verify {
        proxy_pass $upstream;
    }

    location /api/authz/ {
        proxy_pass $upstream;
    }
}
```

If you need further details, please let me know.

Thanks!
