### DISCUSSION TITLE
tracking: issue with smtp timeout / hanging on startup instead of erroring

### DISCUSSION THREAD

**Discussion by james-d-elliott** [authelia/authelia#9695] [Troubleshooting]
This is a meta tracking issue for a likely upstream issue in the SMTP lib where the timeout doesn't occur on startup. If you have helpful input i.e. reproduction instructions that have not similarly been provided, or code that may solve this issue, please feel free to get involved.

Responses that are effectively just noise and do not add value like "me too" etc may be deleted. If you'd like to contribute (we'd encourage it) please include a configuration and trace logs especially if you have a public SMTP server that we can try. I'm fairly certain the issue occurs before auth.

**Comment by james-d-elliott** [comment]
We're looking for settings that can be used to replicate this as we've been unable to so far.

**Comment by oscarcarlsson** [comment]
I had some issues getting this to work with my email provider migadu.com, the pod would just be restarted without an error message which was confusing until I found an issue sending me here.

My SMTP server is smtp.migadu.com, which requires TLS and uses port 465.

I had to explicitly disable STARTTLS to make it work, below is a working configuration for the helm chart:

    smtp:
      enabled: true
      address: "submissions://smtp.migadu.com:465"
      disable_starttls: true
      username: "foo@example.com"

Not sure if helpful but at least a data point!

helm chart version `0.10.45`

**Reply by james-d-elliott** [reply]
Thanks for posting this. I'll see if I can replicate it. 

It's something in the smtp library I'm almost certain but I'm not sure what it is, where to start looking, and how to actually report it. There are also no similar issues last time I looked.

**Reply by james-d-elliott** [reply]
Actually would you mind breaking it again and showing the trace logs related to the notifier?

**Reply by oscarcarlsson** [reply]
I tried but failed :-) :-( 

I must have been in a blocklist while using the default readiness & liveness probes. I tuned them up to several minutes (then theory was issues replicating/migrating DB or such) and kept on iterating configuration parameters, and eventually it worked.

It wasn't even setting `disable_starttls` to true that did the trick, nor setting `identifier` to another value.

So in case someone else reads this while troubleshooting:

Increase readiness and liveness probes to avoid restarting and hitting the SMTP server too fast:

```yaml
pod:
  # ...
  probes:
    readiness:
      initialDelaySeconds: 120
      periodSeconds: 60
      timeoutSeconds: 5
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
```

Once you get this up and running, you can safely remove the probe settings above and use the defaults again!

For migadu.com these settings Works For Me(tm):

```yaml
configMap:
  notifier:
    smtp:
      enabled: true
      address: "submissions://smtp.migadu.com:465"
      sender: "Authelia <authelia@example.com>"
      username: "authelia@example.com"
      password:
        secret_name: smtp-credentials
```
