### ISSUE TITLE
Allow customize HTTP Headers in Config (Traefik only)

### ISSUE THREAD

**Issue by knrdl** [authelia/authelia#1003]
Hi, 
the headers `Proxy-Authorization, Remote-User, Remote-Groups` are currently set as constants in `/internal/handlers/const.go`

It would be nice if these headers were changable via config because:
- some backends expect `Remote-User` and `Remote-Groups` to have different names (especially when migrating from other solutions) 
- Traefik2 filters out the `Proxy-Authorization` header in the request, so it's not usable for authelia

There could be an additional config section, which might be look like this per default:
```
http_header_names:
  request_auth: Proxy-Authorization
  response_user: Remote-User
  response_groups: Remote-Groups
```

What do you think?
