### ISSUE TITLE
Support for subject combinations in ACLs

### ISSUE THREAD

**Issue by lippl** [authelia/authelia#1083]
Currently you can only have a "match any" of the subjects, but no way to combine them, to check for example if a user is member of two specified groups at once.
Extending #869 it would be nice to also allow a combination ob multiple subjects.
In addition to the logical OR for each subject rule and within that rule they'll just be checked with logical ANDs then.
It could be an approach to use one of the following configurations:
```
subject:
        - "group:admins" && "group:devs"
        - "group:moderators"
```
OR
```
subject:
        - "group:testers"
        - 
                - "group:admins"
                - "group:devs"
        - "group:moderators"
```
What do you think and prefer?

**Comment by nightah** [comment]
As mentioned in Matrix I'm probably in favour of the top option, the second just seems a little too "busy" for me.

Similar to the current ACL's design I suspect this would be first matching rule within a subject?

**Comment by james-d-elliott** [comment]
What about:

```yaml
access_control:
  default_policy: deny
  rules:
    - domain: example.com
       policy: one_factor
       subject:
          - "group:admins"
          - "group:devs"
      subject_modifier: and
    - domain: example.com
       policy: two_factor
       subject:
         - "group:moderators"
```
