### ISSUE TITLE
Unable to initialize SQLite database

### ISSUE THREAD

**Issue by blake1029384756** [authelia/authelia#1101]
I am trying to setup authelia using the default storage backend with SQLite. However i get the following error when doing so.

https://gist.github.com/blake1029384756/cb974326d3e4672fae97dd2d9676eb18

**Comment by nightah** [comment]
@blake1029384756 are you deploying this via Docker or bare metal?

If Docker could you please provide either your Docker run statement or `docker-compose.yml` that defines your container? Can you also provide your `configuration.yml` for Authelia?

**Comment by nightah** [comment]
@blake1029384756 did you manage to get this sorted?

If not could you please provide the requested information so we can assist you?

**Comment by xplreitr** [comment]
I had the same problem after upgrading to 4.20.0 until I updated the line in configuration.yml from 

```YAML
storage:
  local:
    path: /var/lib/authelia/db.sqlite3
```

to 

```YAML
storage:
  local:
    path: /config/db.sqlite3
```
