### ISSUE TITLE
HTTP 405 with header "proxy-authorization: Basic XXX" 

### ISSUE THREAD

**Issue by plague-doctor** [authelia/authelia#1109]
The authentication from browser works like a charm, but when I try to curl single password protected application I get HTTP 405 (and Authelia auth page) instead of being redirected to the app page.

curl -IL -H "Proxy-Authorization: Basic XXXXXX==" https://app.example.com

```
HTTP/2 302 
content-type: text/plain; charset=utf-8
date: Wed, 10 Jun 2020 23:52:56 GMT
location: https://auth.example.com/?rd=https%3A%2F%2Fapp.example.com%2F
content-length: 78

HTTP/2 405 
allow: GET, OPTIONS
content-type: text/plain; charset=utf-8
date: Wed, 10 Jun 2020 23:52:56 GMT
content-length: 18
```

Logs:
```
time="2020-06-11T09:52:57+10:00" level=info msg="Access to https://app.example.com/ is not authorized to user , redirecting to https://auth.example.com?rd=https%3A%2F%2Fapp.example.com%2F" method=GET path=/api/verify remote_ip=192.168.1.1
```

Authelia configuration:
```
host: 0.0.0.0
port: 9091
log_level: debug
jwt_secret: SECRET

authentication_backend:
  file:
    path: /etc/authelia/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024

totp:
  issuer: example.com
  period: 30
  skew: 1

session:
  name: authelia_session
  secret: SECRET
  domain: example.com
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  disable_startup_check: true
  smtp:
    username: email
    password: password
    host: mail.host.com
    port: 587
    sender: email
    subject: "[Authelia] {title}"

access_control:
  default_policy: bypass
  rules:
    - domain: "app.example.com"
      policy: one_factor
```
