### ISSUE TITLE
"Error caught when verifying user authorization: An anonymous user cannot be authenticated."

### ISSUE THREAD

**Issue by shayant85** [authelia/authelia#1156]
Hello,

We have recently started using authelia along with Traefik. We have managed to get everything to work using the authelia file authentication backend. However we want to migrate to LDAP (Active Directory) authentication and this is where we have ran into issues, specifically during the redirection.

Here is my LDAP configuration (values are arbitrary for privacy reasons):
  
```
  ldap:
    url: ldaps://ldaps.mydomain.corp.com
    skip_verify: true
    base_dn: DC=mydomain,DC=corp,DC=com
    username_attribute: mail
    users_filter: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
    groups_filter: (&(member={dn})(objectclass=group))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: mail
    user: ldapadmin@mydomain.corp.com
    password: password
```

As you can see in the container logs below, we can log into LDAP and authenticate the user successfully, however once logged in, the browser shows "unauthorized" during redirection with the error in the logs: _"Error caught when verifying user authorization: An anonymous user cannot be authenticated. That might be the sign of a compromise"_:

```
authelia.1.ftvazso81jx6a15oawpposkgi@node-01    | time="2020-06-24T23:19:58-04:00" level=debug msg="Credentials validation of user user@corp.com is ok" method=POST path=/api/firstfactor remote_ip=10.0.0.2

authelia.1.ftvazso81jx6a15oawpposkgi@node-01    | time="2020-06-24T23:19:58-04:00" level=debug msg="Mark authentication attempt made by user user@corp.com" method=POST path=/api/firstfactor remote_ip=10.0.0.2

authelia.1.ftvazso81jx6a15oawpposkgi@node-01    | time="2020-06-24T23:20:13-04:00" level=debug msg="Required level for the URL https://example.corp.ca/test-user/ is 1" method=POST path=/api/firstfactor remote_ip=10.0.0.2

authelia.1.ftvazso81jx6a15oawpposkgi@node-01    | time="2020-06-24T23:20:13-04:00" level=debug msg="Redirection URL https://example.corp.ca/test-user/ is safe" method=POST path=/api/firstfactor remote_ip=10.0.0.2

authelia.1.ftvazso81jx6a15oawpposkgi@node-01    | time="2020-06-24T23:20:13-04:00" level=debug msg="Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL" method=GET path=/api/verify remote_ip=10.0.0.2

authelia.1.ftvazso81jx6a15oawpposkgi@node-01    | time="2020-06-24T23:20:13-04:00" level=error msg="Error caught when verifying user authorization: An anonymous user cannot be authenticated. That might be the sign of a compromise" method=GET path=/api/verify remote_ip=10.0.0.2

 stack="github.com/authelia/authelia/internal/handlers/handler_verify.go:242     VerifyGet\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:47 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v0.7.0/router.go:443                          (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.9.0/server.go:2041                        (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.9.0/workerpool.go:223                     (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.9.0/workerpool.go:195                     (*workerPool).getCh.func1\nruntime/asm_amd64.s:1373                                                 goexit"
```
 

Note that except for the authentication-backend configuration, the rest of the configs for Traefik and authelia are identical for both File or LDAP backend.

One thing I have noticed is, when I login using the file backend, in the authelia greeting page I see the "Hi username" greeting. However when using the LDAP backend, it only says "Hi" without showing any username. This tells me that authelia is unable to fetch the value for "display_name_attribute" from LDAP and I wonder if that would cause a problem and make this an "anonymous user"?

We have also noticed some slowness and intermittent connectivity issues between our server and the LDAP server. I was thinking maybe that would be related, but then again the authentication seems to be going through based on the above logs, it's the redirect part that is "unauthorized" due to the "anonymous user". So the question is, why does the user remain "anonymous" after a successful LDAP login?

Any tips to further troubleshoot this would be appreciated.

**Comment by nightah** [comment]
Based on your configuration and your example logs it looks to me like you only want to allow users to login with their email.

This is fine, though what I would suggest is that you tweak your configuration so the user storage is still based on their `username`, my assumption here is that your usernames are actually indeed unique, if so can you tweak your configuration like this please:

```
  ldap:
    url: ldaps://ldaps.mydomain.corp.com
    skip_verify: true
    base_dn: dc=mydomain,dc=corp,dc=com
    username_attribute: sAMAccountName
    users_filter: (&({mail_attribute}={input})(objectCategory=person)(objectClass=user))
    groups_filter: (&(member={dn})(objectclass=group))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: mail
    user: ldapadmin@mydomain.corp.com
    password: password
```

I would also recommend during your testing to set `refresh_interval: 0` or `refresh_interval: always`. This is just to ensure that during your testing you don't have to wait for 5 minutes for changes/information to be propogated.

Now having said that the error also may not be entirely related to just your LDAP configuration; to be sure can you provide the output of a LDAP search with the respective query to see what results are being reuturned, if any?

So something like: `ldapsearch -x -LLL -D "cn=<ADMINUSERHERE>" -b dc=mydomain,dc=corp,dc=com -H ldaps://ldaps.mydomain.corp.com -w <PASSWORDHERE> "(&(mail=test@mydomain.corp.com)(objectCategory=person)(objectClass=user))"`

If that's not returning anything then it's likely to be your LDAP configuration.
