### ISSUE TITLE
Impossible to use Active Directory as first factor authentication

### ISSUE THREAD

**Issue by daurpam** [authelia/authelia#1162]
Thanks in advance, I look for similar issues but trying to fix with that instructions doesn't work. I'm trying to config authelia against Active Directory config on a Windows Server 2016. I'm using a traefik docker container to put all together.

## configuration.yml ##
```
host: 0.0.0.0
port: 9091
server:
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: ""
log_level: debug
jwt_secret: my_secrete
authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    url: ldap://172.17.24.5
    skip_verify: false
    base_dn: dc=mydomain,dc=local
    username_attribute: sAMAccountName
    additional_users_dn: ou=Company
    users_filter:  (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
    additional_groups_dn: ou=groups
    group_name_attribute: cn
    mail_attribute: mail
    user: cn=administrator,dc=mydomain,dc=LOCAL
    password: mypassword
access_control:
  default_policy: deny
  rules:
    - domain: hello.mydomain.local
      policy: one_factor
    - domain: login.mydomain.local
      policy: one_factor
    session:
  name: authelia_session
  secret: remove_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: mydomain.local
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  local:
    path: /config/db.sqlite3
```
The error shown in logs 
```
authelia    | time="2020-06-30T12:42:50+02:00" level=debug msg="Mark authentication attempt made by user myuser@mydomain.local" method=POST path=/api/firstfactor remote_ip=172.17.24.137
authelia    | time="2020-06-30T12:42:50+02:00" level=error msg="Error while checking password for user myuser@mydomain.local: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C090442, comment: AcceptSecurityContext error, data 52e, v3839\x00" method=POST path=/api/firstfactor remote_ip=172.17.24.137 stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64  (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:94             handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:100 FirstFactorPost.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.2.2/router.go:348                           (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14       LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.14.0/server.go:2162                        (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.14.0/workerpool.go:223                     (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.14.0/workerpool.go:195                     (*workerPool).getCh.func1\nruntime/asm_amd64.s:1373                                                  goexit"
```

I've tried to change user_filter and username_attribute, but doesn't work. Perhaps there is some mistake on my config file or anything else. 
## docker-compose.yml ##
```
version: '3'

services:

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /home/docker/authelia:/config
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.mydomain.local`)'
      - 'traefik.http.routers.authelia.entrypoints=web-secure'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.certresolver=le'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.mydomain.local/'
    expose:
      - 9091
    restart: unless-stopped

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web-secure"
      - "traefik.http.routers.whoami.tls=true"
      - "traeifk.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.routers.whoami.middlewares=authelia@docker"
      - "traefik.http.routers.whoami.rule=Host(`hello.mydomain.local`)"

networks:
  proxy:
    external: true
```

Hope someone can help me.. Thank you!

**Comment by james-d-elliott** [comment]
This is my configuration. This only allows enabled users, and matches either email or sAMAccountName. Let me know if this doesn't help.

Users are located in OU=People,OU=Accounts,DC=example,DC=com
Groups are located in OU=Groups,OU=Accounts,DC=example,DC=com

```yaml
    authentication_backend:
      disable_reset_password: true
      ldap:
        url: ldap://dc:3268
        skip_verify: false
        base_dn: DC=example,DC=com
        additional_users_dn: OU=People,OU=Accounts
        additional_groups_dn: OU=Groups,OU=Accounts
        users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))
        username_attribute: sAMAccountName
        groups_filter: (&(member={dn})(objectClass=group))
        group_name_attribute: cn
        refresh_interval: 5m
        mail_attribute: mail
        user: CN=Authelia,OU=Services,OU=Accounts,DC=example,DC=com
        password: servicepw
```
