### ISSUE TITLE
Active Directory login slow

### ISSUE THREAD

**Issue by shayant85** [authelia/authelia#1179]
Hi,

Not sure if this is an issue with Authlia specifically... we have managed to get Active Directory login to work, however, it is quite slow and sometimes could take up to two minutes for the user to login.

When we do a manual query from a container (on the same host as authelia) against the ldap server, it works instantly using the following command:

`ldapsearch -v -H ${LDAP_SERVER} -D "${USERNAME}" -w "${PASSWORD}" -b 'DC=corp,DC=com' "(&(mail=${USER})(objectCategory=person)(objectClass=user))"
`

So there don't seem to be any connectivity issues... But when we go through Authelia it takes **exactly** 45 seconds to do the initial query and credential verification, and another 45 seconds to query the user groups. You can see this in the sample log below and the delay points are separated by line breaks:

```
time="2020-07-06T11:09:13-04:00" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:09:13-04:00" level=trace msg="LDAP client starts a TLS session"

time="2020-07-06T11:09:58-04:00" level=trace msg="Computed user filter is (&(mail=user@corp.com)(objectCategory=person)(objectClass=user))"
time="2020-07-06T11:09:58-04:00" level=trace msg="LDAP client starts a TLS session"
time="2020-07-06T11:09:58-04:00" level=debug msg="Credentials validation of user user@corp.com is ok" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:09:58-04:00" level=debug msg="Mark authentication attempt made by user user@corp.com" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:09:58-04:00" level=trace msg="LDAP client starts a TLS session"

time="2020-07-06T11:10:43-04:00" level=trace msg="Computed user filter is (&(mail=user@corp.com)(objectCategory=person)(objectClass=user))"
time="2020-07-06T11:10:43-04:00" level=trace msg="Computed groups filter is (&(member=CN=123456,OU=Business Units,DC=corp,DC=com)(objectclass=group))"
time="2020-07-06T11:10:43-04:00" level=trace msg="Details for user user@corp.com => groups: [group1], emails [user@corp.com]" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:10:43-04:00" level=trace msg="Check authorization of subject username=user@corp.com groups=group1 ip=10.0.0.2 and url https://test.com/route"
time="2020-07-06T11:10:43-04:00" level=debug msg="Required level for the URL https://test.com/route is 1" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:10:43-04:00" level=debug msg="Redirection URL https://test.com/route is safe" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:10:43-04:00" level=trace msg="attempt successful: true, exec duration: 90313, avg execution duration: 9931, random delay ms: 28, total delay ms: 9959, actual delay ms: 1" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:10:43-04:00" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2020-07-06T11:10:43-04:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=10.0.0.2
```

Looks like it seems to be related to TLS, but not sure why there is no delay when we run the ldapsearch command manually instead of going through Authelia. I also thought the 45 seconds delay was interesting given that it's the exact same delay every time. 

Here is our LDAP config for reference:

```
  ldap:
    url: ldaps://ldaps.mydomain.corp.com
    skip_verify: true
    base_dn: dc=mydomain,dc=corp,dc=com
    username_attribute: sAMAccountName
    users_filter: (&({mail_attribute}={input})(objectCategory=person)(objectClass=user))
    groups_filter: (&(member={dn})(objectclass=group))
    group_name_attribute: cn
    mail_attribute: mail
    user: ldapadmin@mydomain.corp.com
    password: password
```

Thanks in advance.
