### ISSUE TITLE
authentication on subfolder

### ISSUE THREAD

**Issue by netpages** [authelia/authelia#1186]
Hi,
i'm testing Authelia 4.20.0 with ldap backend in combination with Traefik 2
I would like to protect only the subfolder /admin on a subdomain test.tld.de

Authelia Config looks like:
```access_control:
  default_policy: deny
  rules:
    - domain: test.tld.de
      resources:
        - "^/admin.*$"
        - "^/admin/.*$"
      policy: one_factor
    - domain: test.tld.de
      policy: bypass
```

this is working fine!
I can access test.tld.de without login and test.tld.de/admin with login

as i add restriction to a (LDAP) user/group to test.tld.de/admin, no login is required on test.tld.de and test.tld.de/admin

Config looks like:
```
access_control:
  default_policy: deny
  rules:
    - domain: test.tld.de
      resources:
        - "^/admin.*$"
        - "^/admin/.*$"
      subject: "user:demo"
      policy: one_factor
    - domain: test.tld.de
      policy: bypass
```

Authelia Logs:
```

time="2020-07-08T10:23:59+02:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=xx.xx.xx.xx
time="2020-07-08T10:23:59+02:00" level=trace msg="Headers=GET /api/verify?rd=https://authelia.test.tld.de HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0\r\nHost: test-proxy_authelia:9091\r\nContent-Length: 0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: de,en-US;q=0.7,en;q=0.3\r\nCache-Control: max-age=0\r\nUpgrade-Insecure-Requests: 1\r\nX-Forwarded-For: remote_ip=xx.xx.xx.xx\r\nX-Forwarded-Host: test.tld.de\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: 8e1d6afc70b3\r\nX-Forwarded-Uri: /admin/\r\nX-Real-Ip: remote_ip=xx.xx.xx.xx\r\n\r\n" method=GET path=/api/verify remote_ip=xx.xx.xx.xx
time="2020-07-08T10:23:59+02:00" level=trace msg="Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL" method=GET path=/api/verify remote_ip=xx.xx.xx.xx
time="2020-07-08T10:23:59+02:00" level=trace msg="Inactivity report: Inactivity=3, MaxInactivity=900" method=GET path=/api/verify remote_ip=xx.xx.xx.xx
time="2020-07-08T10:23:59+02:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=xx.xx.xx.xx
time="2020-07-08T10:23:59+02:00" level=trace msg="Check authorization of subject username= groups= ip=remote_ip=xx.xx.xx.xx and url https://test.tld.de/admin/."
time="2020-07-08T10:23:59+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/verify remote_ip=xx.xx.xx.xx
```

what I'm doing wrong here?

**Comment by mpfaff** [comment]
Thanks for pointing this out! I can't believe I didn't notice this earlier!

**Comment by james-d-elliott** [comment]
So what's happening here is Authelia steps through the access list until it finds a rule that matches or falls back to the default policy.

1. Rule #1 DOES NOT match since the user is not "demo", it's anonymous.
2. Rule #2 DOES match since the domain is test.tld.de, thus policy is bypass.
3. Default Rule (deny) is never hit because it's already found a matching rule.

Thus your rules need to look like this:

```yaml
access_control:
  default_policy: deny
  rules:
    - domain: test.tld.de
      resources:
        - "^/admin.*$"
        - "^/admin/.*$"
      subject: "user:demo"
      policy: one_factor
    - domain: test.tld.de
      resources:
        - "^/admin.*$"
        - "^/admin/.*$"
      policy: deny
    - domain: test.tld.de
      policy: bypass
```
