### ISSUE TITLE
302 error with Traefik2 and Authelia

### ISSUE THREAD

**Issue by paulmorabito** [authelia/authelia#1195]
Hi,

I seem to be having a problem similar to #704. 

I first set up Traefik 2 + Authelia about 2 months and I am sure it was working then but seems to be recently causing problems. When trying to access an Authelia protected URL, Traefik returns a 404 error with the log message:

`time="2020-07-13T00:13:30Z" level=debug msg="Remote error http://authelia:9091/api/verify?rd=https://login.mydomain.net/. StatusCode: 302" middlewareName=books@docker middlewareType=ForwardedAuthType
`

Authelia reports:

`time="2020-07-13T09:14:18+09:00" level=info msg="Access to https://books.mydomain.net/ is not authorized to user , redirecting to https://login.mydomain.net/?rd=https%3A%2F%2Fbooks.mydomain.net%2F" method=GET path=/api/verify remote_ip=192.168.1.1`

My Traefik compose config is as follows:

```
  traefik2:
    container_name: traefik2
    image: traefik:chevrotin
    restart: unless-stopped
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
        # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true
#      - --api.insecure=true
#      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      #- --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.mydomain.net`)
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
#      - --providers.file.filename=/path/to/file # Load dynamic configuration from a file.
      - --providers.file.watch=true # Only works on top level files in the rules folder
      - --certificatesResolvers.dns-cloudflare.acme.email=my@email.com
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    depends_on:
      - authelia
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /home/user/docker/traefik2/rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/user/docker/traefik2/acme/acme.json:/acme.json
      - /home/user/docker/traefik2/traefik.log:/traefik.log
    environment:
      - CF_API_EMAIL=my@email.com
      - CF_API_KEY=ghfhfh55654fghfh
    labels:
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.mydomain.net`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
#      - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=mydomain.net"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.mydomain.net"
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file"

```

Authelia compose is:

```
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - /home/user/docker/authelia/:/config
    networks:
      - t2_proxy
    ports:
      - 9091:9091
    restart: unless-stopped
    environment:
      - TZ=
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.mydomain.net`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
```

A sample container with the issue is:

```
  books:
    image: 
    container_name: books
    environment:
      - PUID=1000
      - PGID=999
    volumes:
      - /home/user/docker/books:/config
      - /media/Library:/books
    ports:
      - 8083:8083
    restart: always
    networks:
      - default
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.books-rtr.entrypoints=https"
      - "traefik.http.routers.books-rtr.rule=Host(`books.mydomain.net`,`www.books.mydomain.net`)"
      - "traefik.http.routers.books-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.books-rtr.middlewares=books, chain-no-auth@file"
      - 'traefik.http.middlewares.books.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.mydomain.net/'
      - 'traefik.http.middlewares.books.forwardauth.trustforwardheader=true'
      - 'traefik.http.middlewares.books.forwardauth.authresponseheaders=X-Forwarded-User'
      #- 'traefik.http.routers.books-rtr.middlewares=authelia@docker'
      ## HTTP Services
      - "traefik.http.routers.books-rtr.service=books-svc"
      - "traefik.http.services.books-svc.loadbalancer.server.port=8083"

```

Authelia config is:
```

###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: 
totp:
  issuer: authelia.com

#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "*.mydomain.net"
      policy: two_factor
    - domain: "*.mydomain.net"
      policy: bypass
      networks:
      - 192.168.1.0/24


session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: 
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: mydomain.net # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  #filesystem:
  #  filename: /etc/authelia/data/notification.txt
  smtp:
    username: 
    password: 
    sender: 
    host: smtp.gmail.com
    port: 587


```

I had to clean the configs of personal info so if anything doesn't make sense then let me know. Also, The configs are a little messy as I've been debugging quite a bit (with no success to date).

There are no errors or issues in the authelia logs or in Traefik that I can see other than what I pasted. It seems to not matter whether I access the URL's from internal to my home network (when Authelia should not auth) or external (where it should, at least according to the config). 

The middleware chain-no-auth@file can be ignored as the same behavior is exhibited with or without it's presence. However, I can provide if required.

There was a recommendation in #704  to add "/#/" to the forwarded address. I did this but had no successful result.

Any help would be really appreciated.

**Comment by nightah** [comment]
So if you want to remove the authentication requirement on your local network you need to re-order your rules to the following:

```yaml
access_control:
  default_policy: deny
  rules:
    - domain: "*.mydomain.net"
      policy: bypass
      networks:
      - 192.168.1.0/24
    - domain: "*.mydomain.net"
      policy: two_factor
```

The rules are iterated through sequentially until a matching rule is found, because `*.mydomain.net` matches the first rule you have defined within your provided configuration you'll never actually get to the second.
The rule of thumb is to put your most explicit ACL's towards the top and more generic ones further down the list.

**Comment by paulmorabito** [comment]
@nightah thanks, that part seemed to have worked. 

Still got the 404 error when access externally.

**Comment by nightah** [comment]
So just to be clear `https://login.mydomain.net` doesn't work external from your network?
I don't see a forward auth setup on your Authelia container but could you try the following for your ACL's:

```yaml
access_control:
  default_policy: deny
  rules:
    - domain: "login.mydomain.net"
      policy: bypass
    - domain: "*.mydomain.net"
      policy: bypass
      networks:
      - 192.168.1.0/24
    - domain: "*.mydomain.net"
      policy: two_factor

**Comment by paulmorabito** [comment]
@nightah I updated the configuration.yml as above and added the following three lines to authelia compose:
```

      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.mydomain.net/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups'
```
I actually had this before and commented it out as many examples elsewhere don't include it.

Internal network: Works fine when I access books.mydomain.net and all other domains as per previous container.

External network: Same 302 error as per original post. Also, If i try to access the http://login.mydomain.net/?rd= URL on internal network then it also gives the same error.

**Comment by paulmorabito** [comment]
I should also add that I can access http://login.mydomain.net from both internal and external network when I open it directly in a browser. The issue occurs when Traefik needs to redirect to it.

**Comment by nightah** [comment]
Your compose file is quite busy but if you can paste the current version I'll see if I can clean it up for you with a working example.

**Comment by paulmorabito** [comment]
@nightah LOL yes, I based it off various how to's and there is also some possibly unnecessary legacy stuff in there too.

Latest is as below, it's really uncahnged from above segments previously pasted:

```
  traefik2:
    container_name: traefik2
    image: traefik:chevrotin
    restart: unless-stopped
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
        # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true
#      - --api.insecure=true
#      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      #- --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.mydomain.net`)
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
#      - --providers.file.filename=/path/to/file # Load dynamic configuration from a file.
      - --providers.file.watch=true # Only works on top level files in the rules folder
      - --certificatesResolvers.dns-cloudflare.acme.email=my@email.com
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    depends_on:
      - authelia
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /home/user/docker/traefik2/rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/user/docker/traefik2/acme/acme.json:/acme.json
      - /home/user/docker/traefik2/traefik.log:/traefik.log
    environment:
      - CF_API_EMAIL=my@email.com
      - CF_API_KEY=ghfhfh55654fghfh
    labels:
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.mydomain.net`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
#      - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=mydomain.net"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.mydomain.net"
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file"

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - /home/user/docker/authelia/:/config
    networks:
      - t2_proxy
    ports:
      - 9091:9091
    restart: unless-stopped
    environment:
      - TZ=
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.mydomain.net`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.mydomain.net/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups'

 books:
    image: 
    container_name: books
    environment:
      - PUID=1000
      - PGID=999
    volumes:
      - /home/user/docker/books:/config
      - /media/Library:/books
    ports:
      - 8083:8083
    restart: always
    networks:
      - default
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.books-rtr.entrypoints=https"
      - "traefik.http.routers.books-rtr.rule=Host(`books.mydomain.net`,`www.books.mydomain.net`)"
      - "traefik.http.routers.books-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.books-rtr.middlewares=books, chain-no-auth@file"
      - 'traefik.http.middlewares.books.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.mydomain.net/'
      - 'traefik.http.middlewares.books.forwardauth.trustforwardheader=true'
      - 'traefik.http.middlewares.books.forwardauth.authresponseheaders=X-Forwarded-User'
      #- 'traefik.http.routers.books-rtr.middlewares=authelia@docker'
      ## HTTP Services
      - "traefik.http.routers.books-rtr.service=books-svc"
      - "traefik.http.services.books-svc.loadbalancer.server.port=8083"

```
