### ISSUE TITLE
Possibility for Multiple Target URLs under protected domain

### ISSUE THREAD

**Issue by lued** [authelia/authelia#1198]
I'm looking to redirect another domain through Authelia that is not a subdomain of the protected domain.

I guess I'm more or less looking for the correct field for session/domain configuration. Comments say "If empty, the cookie is restricted to the subdomain of the issuer", although this is a required field. I couldn't find anything in the documentation regarding this type of configuration. 

authelia/configuration.yml
```access_control:
  default_policy: deny

  rules:
    - domain: '*.{domain 1}'
      policy: two_factor

    - domain: '*.{domain 2}'
      policy: two_factor

...
...

session:
  ...

  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer.
  domain: {domain 1 as a required field}```

Kind regards
- lued

**Comment by nightah** [comment]
This isn't possible today, the cookie and all the respective configuration is tied to a single root domain.
You would need to run multiple instances of Authelia to achieve your intended outcome.

Though this is something that the team should discuss and design to support in future. I think a single instance of Authelia with the ability to support multiple domains is something that we should consider, as the topic is gaining a lot of traction and interest.

cc @clems4ever @james-d-elliott

**Comment by james-d-elliott** [comment]
I'm wondering if we could use OIDC plus a container that just does the OIDC handshake with Authelia.

**Comment by dginhoux** [comment]
I use multiple domains, with on instance per domain.

Everything work fine. But if I use ldap as user backend, the same for all domains but for authelia, can I use the same storage backend (myssl, same database) for all domains instanced...?

**Comment by CubicrootXYZ** [comment]
Anything new here? Would be interested in that feature too.

**Comment by nearcatch** [comment]
> The most logical way is:
> 
>     1. We implement our own session provider that can write to multiple domains. The upstream library we currently use is very limiting, we're probably going to have to do this anyway regardless.
>     2. A user has to configure the main domain (we will call this auth.example1.com). When an unauthenticated user is directed to authelia on a domain other than the main domain (other domain in this example is auth.example2.com) they are redirected to the main domain.
>     3. They authenticate (if already sufficiently authenticated this step is skipped).
>     4. We redirect them back to auth.example2.com with a JWT signed by authelia.
>     5. We write the session linking cookie.
>     6. We redirect them to the destination.

Step 2 in this scenario wouldn't really be desirable in my usage case. I run Authelia twice, once for a WAN domain and once for my local LAN. It would be nice to consolidate them into one instance if Authelia could intelligently process requests based on the incoming domain, but I wouldn't want it to redirect requests on my WAN domain to my LAN, or vice versa. If Authelia ends up doing that, I'll probably continue using separate instances, even if it's less efficient.

Ideally Authelia would just do what Traefik rules do and choose paths based on the domain, without any single domain being primary over the other.

**Comment by james-d-elliott** [comment]
> Step 2 in this scenario wouldn't really be desirable in my usage case. I run Authelia twice, once for a WAN domain and once for my local LAN. It would be nice to consolidate them into one instance if Authelia could intelligently process requests based on the incoming domain, but I wouldn't want it to redirect requests on my WAN domain to my LAN, or vice versa. If Authelia ends up doing that, I'll probably continue using separate instances, even if it's less efficient.

So if you had a user visit protected.example1.com and they authenticated, and then some time later they visit protected.example2.com, you'd want them to have to sign in again?

**Comment by nearcatch** [comment]
> So if you had a user visit protected.example1.com and they authenticated, and then some time later they visit protected.example2.com, you'd want them to have to sign in again?

Yes, absolutely. Two separate domains should not be assumed to share authentication. Some people might like that, so maybe it could be an optional switch for a chosen domain, but I would definitely not want cross-domain cookies to be a default.

**Comment by superadmin84** [comment]
+1 For wanting multiple domains. I also agree with @nearcatch that sharing sessions between domains should be a feature that can be toggled. I know y'all are busy with OIDC at the moment, but is this even on the road map yet?

**Comment by james-d-elliott** [comment]
> I also agree with @nearcatch that sharing sessions between domains should be a feature that can be toggled.

The multiple domains thing will be significantly more difficult as you cannot share a u2f/webauthn device with multiple domains. Additionally this presents the least value overall as an option. I can't see a whole lot of advantage to this over running two separate instances of Authelia with near identical configurations.

> I know y'all are busy with OIDC at the moment, but is this even on the road map yet?

As this is a fairly significant undertaking, and it's likely to involve us replacing several libraries (specifically the session/cookie library), it's not something we've put on the roadmap yet until we get some of the other significantly large features checked off.

> I have also noticed that even if you set all the configurations to a specific root domain, if the authelia instance is hosted on a different root domain, authentication breaks.

Could you elaborate? It sounds like you mean your applications are sitting at *.example.com and Authelia is sitting at auth.site.com.

**Comment by nearcatch** [comment]
> I can't see a whole lot of advantage to this over running two separate instances of Authelia with near identical configurations.

So I currently run 3 Authelia instances, for two WAN domains and my LAN domain. Some annoyances this causes:
- For every Authelia update, I have to modify 3 different config files for any breaking changes.
- Any changes I make to my Authelia environment again mean changing 3 config files.
- A lot of repetition in my docker-compose file.
- 3 instances using memory, although Authelia doesn't use much at idle, and I have the memory to spare. But it would still be a concern for someone running Authelia on a Pi or something similar, I would think.

However, I realize it'll be a lot of work to make Authelia domain-aware, and doing it properly would require a lot of changes. Frex, to be properly secure, the users database would have to modified so each user could be associated with some domains and not others. Or there would have to be separate users database for each domain. So I understand that for now, and probably a long while into the future, the best option is to continue running separate Authelia instances. And maybe the effort involved in isolating domains for security means that the safest way is always going to be separate instances versus a "smart" config file.

**Comment by bozerkins** [comment]
@james-d-elliott , I have a question regarding solution of this in kubernetes. 

We have a case where we would like to have Authelia for multiple domains as well. I was thinking of creating single installation via the helm chart https://github.com/authelia/chartrepo, but disabling ingress. After that creating 2 ingresses manually, that would work for each of the domains. Can there be problems with such an approach / workaround? 

The installation would be one, but multiple ingress-es (for different domains) would exist connected to the installation.

**Comment by DblK** [comment]
> The issue is that as auth.example1.com you _**cannot**_ read OR write a cookie for example2.com or auth.example2.com. It's literally a baked in standard of the web.

Actually, you can using `iframe` and `postMessage` and to secure it with CORS (Access-Control-Allow-Origin).

**Comment by james-d-elliott** [comment]
> 

The issue is the library supplying the session cookie requires a domain configured, I plan on redoing it for our needs but it's not a trivial job unfortunately.

> Actually, you can using `iframe` and `postMessage` and to secure it with CORS (Access-Control-Allow-Origin).
> 
> Here is [some spec/article](https://meta.stackexchange.com/questions/64260/how-does-sos-new-auto-login-feature-work) how to do it.

This is more of a guide on how to hack around the restrictions browsers put in place which has security implications that even the author recognizes.

I wouldn't even consider SE's method of dealing with this as they describe it in that article as the best method. OIDC or SAML are easily the best methods, followed by the method I described in a closed system. I highly doubt this method will ever be used as we intentionally block using Authelia in an iframe due to the numerous attack vectors that exist when using iframes. 

The article also doesn't really counter my point, auth.example1.com still can't set normal cookies for any domain other than itself. It's the iframe at example2.com setting it.

**Comment by james-d-elliott** [comment]
Side note, this is a very popular issue so I'm making sure the team discusses it to see if we can come to an appropriate solution. It likely will be something we do after webauthn and a few enhancements to OIDC if we agree to prioritize it however.

**Comment by ITJamie** [comment]
in the mean time... is it ok to point multiple authelia installs at the same database? a few people have asked but i havnt seen clarity on that.
in my case access rules are going to be the same, it's just that some tools exist under a legacy domains.

**Comment by nearcatch** [comment]
> in the mean time... is it ok to point multiple authelia installs at the same database? a few people have asked but i havnt seen clarity on that. in my case access rules are going to be the same, it's just that some tools exist under a legacy domains.

If you're asking whether it will work, I currently have 3 authelia containers pointed to the same database container and they've been running smoothly.

**Comment by james-d-elliott** [comment]
> in the mean time... is it ok to point multiple authelia installs at the same database? a few people have asked but i havnt seen clarity on that. in my case access rules are going to be the same, it's just that some tools exist under a legacy domains.

This will work fine for everything other than U2F/Webauthn.

**Comment by Beanow** [comment]
> I'm wondering if we could use OIDC plus a container that just does the OIDC handshake with Authelia.

Older comment, but thought I would add this is how I've used Keycloak for some time.

One can use a container like [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/) or [traefik-forward-auth](https://github.com/thomseddon/traefik-forward-auth) as an OAuth client, authenticating with your Authelia instance, as well as being a forward auth server authenticating requests for each secondary domain. Defacto that makes the root domain that Authelia protects the main/authoritative one.

1. `protected.second.local` request is checked with forward auth, using `*.second.local` session cookie/
2. `auth.second.local` when not authenticated for this domain, initiates OIDC flow.
3. `authelia.first.local` might already be logged in with `*.first.local` cookie, otherwise do so now.
4. Redirected back to `auth.second.local`, setting session cookies.
5. Redirected back to `protected.second.local`

A **major** downside to this approach is you're now depending on this client to implement access control (if it supports any) and session management, independently from Authelia's configuration.

Independent session management also means, logging out may not propagate to all secondary domains. As a workaround you could use very short sessions. But that will cause browser redirects (and currently always triggers a consent page https://github.com/authelia/authelia/issues/2598).

On the positive side, this setup is more flexible than coercing HA features into a multi-instance setup, because you only need client credentials and an HTTPS connection. Making it easy to connect, even across different networks and hosts. Which could be a selling point, when your primary domain is on a public cloud, and your secondary domain is an on-premise intranet.

So I would consider an "Authelia agent". Which pulls all data from the primary Authelia instance, but without the drawbacks I just mentioned for existing OAuth clients. For an example of this, you might look at [Portainer agent](https://github.com/portainer/agent)'s "Edge mode".

**Comment by Beanow** [comment]
I've gone ahead and made an example environment of such a setup:
https://github.com/Beanow/authelia-oidc-multi

**Comment by Leopere** [comment]
Definitely need this somehow please.  I can potentially capture and direct a number of incoming URLS in the browser to Authelia via Træfik however once there the fact there's only support for a single domain is kinda a bummer.

```yaml
version: '3.7'

networks:
  default:
    driver: overlay
  traefik:
    external: true

services:
  authelia:
    image: authelia/authelia
    volumes:
      - /mnt/tank/persist/authelia/production/config:/config
    networks:
      - traefik
      - default
    deploy:
      labels:
        ## https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html
        - 'traefik.enable=true'
        - 'traefik.http.routers.authelia.tls=true'
        - "traefik.http.services.authelia.loadbalancer.server.port=9091"
        - 'traefik.http.routers.authelia.rule=Host(`login.example.com`)'
        - 'traefik.http.routers.authelia.entrypoints=websecure'
        - "traefik.http.routers.authelia.tls.certresolver=letsencryptresolver"
        - "traefik.docker.network=traefik"
## Authelia recommendations
        - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.example.com/'
        - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
        - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
        - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic'
        - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
        - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
```
