### ISSUE TITLE
Central definitions for networks

### ISSUE THREAD

**Issue by mbunkus** [authelia/authelia#1220]
This is a feature request.

We have quite a lot of networks for which we want to bypass restrictions (think internal networks we consider safe, for multiple sites, both IPv4 and IPv6) while enforcing 2FA for accesses from everything else. This is possible right now, of course, but it requires copy-pasting the whole section of networks to each and every access control rule.

It would be nice to be able to define sets of networks elsewhere, to assign them a symbolic and and to use that symbolic name in network access rules. Here's a hypothetical example:

```yaml
networks:
  - name: internal
    networks:
      - 10.123.45.0/24
      - 2001:db8:0:45::/64
  - name: VPN
    networks:
      - 10.123.67.0/24
      - 10.123.68.0/24
      - 2001:db8:0:67::/64
      - 2001:db8:0:68::/64

access_control:
  rules:
    - domain: www.mysite.de
      resources:
        - .
      policy: bypass
      networks:
        - internal
        - VPN

    - domain: www.mysite.de
      resources:
        - "^/executive/.*"
      policy: two_factor

    - domain: internal.mysite.de
      resources:
        - .
      policy: bypass
      networks:
        - internal
        - VPN

    - domain: internal.mysite.de
      resources:
        - .
      policy: two_factor
```

This would have tons of advantages over the current scheme:

1. It makes implementing new blocks much easier.
2. It makes changing the list of networks much easier as you only have to do it in one place instead of many places.
3. It makes auditing the configuration MUCH easier.

Thanks for considering!
