### ISSUE TITLE
Two Authelia services clashing with two root domains

### ISSUE THREAD

**Issue by KeithSSmith** [authelia/authelia#1232]
I have seen the discussion on #1198 and that might ultimately solve the issue I am having here. But in lieu of this not being handled natively as part of the project I have tried running two separate Authelia containers behind one Traefik instance and it seems like Traefik isn't routing authentication requests to the correct Authelia service and looking for help. Here is the setup:

2 root domains:

- foo.com
- bar.com

1 Traefik service and 2 Authelia services so that each handles the root domain above. So far it appears random which Authelia service Traefik is routing to and I am getting locked out (Unathorized) of the domain Authelia is not in charge of with the following output in the logs. I can authenticate into both domains when routing is going through the specific Authelia service, but hoping I'm missing something about why Traefik isn't doing this consistently.

```
time="2020-07-23T23:26:46-05:00" level=error msg="The target URL https://whoami.foo.com/ is not under the protected domain bar.com" method=GET path=/api/verify stack="github.com/authelia/authelia/internal/handlers/handler_verify.go:405     VerifyGet.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.2.2/router.go:348                          (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.14.0/server.go:2162                       (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.14.0/workerpool.go:223                    (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.14.0/workerpool.go:195                    (*workerPool).getCh.func1\nruntime/asm_amd64.s:1373                                                 goexit"
```

Here is the configuration of each:

```
  traefik:
    image: traefik:v2.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=false"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--api"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=cloudflareresolver"
      - "--certificatesresolvers.cloudflareresolver.acme.email=$CLOUDFLARE_EMAIL"
      - "--certificatesresolvers.cloudflareresolver.acme.storage=/acme.json"
      - "--certificatesresolvers.cloudflareresolver.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflareresolver.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--accessLog=true"
      - "--accessLog.bufferingSize=100"
      - "--accessLog.filters.statusCodes=400-499"
    ports:
      - 80:80
      - 443:443
    volumes:
      # To persist certificates
      - $USERDIR/traefik2/acme/acme.json:/acme.json
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/traefik2/traefik.log:/traefik.log
    networks:
      - traefik
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.foo.com`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: authelia@docker

  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami.foo.com`)
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.middlewares: authelia@docker
    depends_on:
      - authelia

  authelia:
    image: authelia/authelia
    restart: unless-stopped
    secrets:
      - jwt
      - duo
      - session
      - redis
      - mysql
      - smtp
      - ldap
    networks:
      - traefik
    volumes:
      - $USERDIR/authelia-foo:/config
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/duo
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/redis
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/mysql
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap
      - TZ=$TZ
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.authelia-rtr-foo.entrypoints: websecure
      traefik.http.routers.authelia-rtr-foo.rule: Host(`authelia.foo.com`)
      traefik.http.routers.authelia-rtr-foo.tls: true
      ## Middlewares
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/verify?rd=https://authelia.foo.com
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: Remote-User, Remote-Groups
```

And the 2nd Authelia service along with a website behind it:

```
  authelia:
    image: authelia/authelia
    restart: unless-stopped
    secrets:
      - jwt
      - duo
      - session
      - redis
      - mysql
      - smtp
      - ldap
    networks:
      - traefik
    volumes:
      - $USERDIR/authelia-bar:/config
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/duo
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/redis
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/mysql
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap
      - TZ=$TZ
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.authelia-rtr-bar.entrypoints: websecure
      traefik.http.routers.authelia-rtr-bar.rule: Host(`authelia.bar.com`)
      ## Middlewares
      traefik.http.middlewares.authelia-bar.forwardauth.address: http://authelia:9091/api/verify?rd=https://authelia.bar.com
      traefik.http.middlewares.authelia-bar.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia-bar.forwardauth.authResponseHeaders: Remote-User, Remote-Groups

  website:
    image: bar-website
    restart: unless-stopped
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.bar-website.entrypoints: websecure
      traefik.http.routers.bar-website.rule: Host(`bar.com`)
      traefik.http.routers.bar-website.tls: true
      traefik.http.routers.bar-website.middlewares: authelia-bar@docker
```

**Comment by james-d-elliott** [comment]
You will need to name the second Authelia instance differently. I would suggest authelia-foo and authlia-bar.. example to follow:

```yaml
  traefik:
    image: traefik:v2.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=false"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--api"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=cloudflareresolver"
      - "--certificatesresolvers.cloudflareresolver.acme.email=$CLOUDFLARE_EMAIL"
      - "--certificatesresolvers.cloudflareresolver.acme.storage=/acme.json"
      - "--certificatesresolvers.cloudflareresolver.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflareresolver.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--accessLog=true"
      - "--accessLog.bufferingSize=100"
      - "--accessLog.filters.statusCodes=400-499"
    ports:
      - 80:80
      - 443:443
    volumes:
      # To persist certificates
      - $USERDIR/traefik2/acme/acme.json:/acme.json
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/traefik2/traefik.log:/traefik.log
    networks:
      - traefik
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.foo.com`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: authelia-foo@docker
  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami.foo.com`)
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.middlewares: authelia-foo@docker
    depends_on:
      - authelia-foo
  authelia-foo:
    image: authelia/authelia
    restart: unless-stopped
    secrets:
      - jwt
      - duo
      - session
      - redis
      - mysql
      - smtp
      - ldap
    networks:
      - traefik
    volumes:
      - $USERDIR/authelia-foo:/config
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/duo
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/redis
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/mysql
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap
      - TZ=$TZ
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.authelia-rtr-foo.entrypoints: websecure
      traefik.http.routers.authelia-rtr-foo.rule: Host(`authelia.foo.com`)
      traefik.http.routers.authelia-rtr-foo.tls: true
      ## Middlewares
      traefik.http.middlewares.authelia-foo.forwardauth.address: http://authelia-foo:9091/api/verify?rd=https://authelia.foo.com
      traefik.http.middlewares.authelia-foo.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia-foo.forwardauth.authResponseHeaders: Remote-User, Remote-Groups
  authelia-bar:
    image: authelia/authelia
    restart: unless-stopped
    secrets:
      - jwt
      - duo
      - session
      - redis
      - mysql
      - smtp
      - ldap
    networks:
      - traefik
    volumes:
      - $USERDIR/authelia-bar:/config
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/duo
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/redis
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/mysql
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap
      - TZ=$TZ
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.authelia-rtr-bar.entrypoints: websecure
      traefik.http.routers.authelia-rtr-bar.rule: Host(`authelia.bar.com`)
      ## Middlewares
      traefik.http.middlewares.authelia-bar.forwardauth.address: http://authelia-bar:9091/api/verify?rd=https://authelia.bar.com
      traefik.http.middlewares.authelia-bar.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia-bar.forwardauth.authResponseHeaders: Remote-User, Remote-Groups
  website:
    image: bar-website
    restart: unless-stopped
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.bar-website.entrypoints: websecure
      traefik.http.routers.bar-website.rule: Host(`bar.com`)
      traefik.http.routers.bar-website.tls: true
      traefik.http.routers.bar-website.middlewares: authelia-bar@docker
```
