### ISSUE TITLE
No redirection after authentication - K3s - Traefik 1.7 - Rancher

### ISSUE THREAD

**Issue by thehedgefrog** [authelia/authelia#1288]
**Summary**

I have setup Authelia on my cluster, and I get the expected behaviour before, and after, authenticating with Authelia - however, I never get redirected.

**How to reproduce**
- Setup Authelia following the docs
- Include the necessary arguments in the *traefik.toml* file 
```toml
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.auth.forward]
    address = "https://authelia.mydomain.com/api/verify?rd=https://authelia.mydomain.com"
    trustForwardHeader = true
    authResponseHeaders = ["Remote-User", "Remote-Groups"]
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
```
- Add a new service
- Setup an ingress with the following annotations
```
kubernetes.io/ingress.class = traefik
ingress.kubernetes.io/auth-type = forward
ingress.kubernetes.io/auth-url = http://authelia.mydomain.com/api/verify?rd=https://authelia.mydomain.com/%23%/
traefik.ingress.kubernetes.io/redirect-entry-point = https
traefik.ingress.kubernetes.io/redirect-permanent = true
```
- Access the ingress hostname
- Log in as usual
- After logging in, result is that the "Authenticated" page stays on screen and no redirection to the ingress hostname occurs
- However, when manually going to the ingress hostname URL again, access is granted, which indicates a successful authentication.

**Expected behaviour**

After authentication, the user is redirected to the original hostname they accessed.

**Versions**
k3s v1.18.6+k3s1
Authelia v4.21.0 (latest)
Traefik v1.7
