### ISSUE TITLE
Endpoint Monitoring

### ISSUE THREAD

**Issue by ProfessorManhattan** [authelia/authelia#1324]
Hey, I have StatPing set up and I would like to monitor the web services behind Authelia to make sure they're all healthy. Is there any way to accomplish this?

**Comment by james-d-elliott** [comment]
So there are a few methods I can see working. 

1. You can setup a network access control policy to bypass Authelia. This works well if the service has a static IP, and nothing else shares that IP. 
2. You can setup the service to access the services directly, i.e. instead of using https://service.example.com if that service is on the same docker network as StatPing you can likely do http://svc (where service.example.com is your external URL, and svc is your docker container name).
3. You setup a user for this purpose and use the auth headers to authenticate, and you give that user only a one_factor requirement.
4. You setup a specific endpoint that is available without authentication to everyone. This is way more involved than the others.

**Examples:**

These rules belong at the top of your access_control section, below any other bypass rules. The first is an example of the first method, the second is an example of the third, and the third is an example of the fourth. You only need one of these.

```
yaml
access_control:
  default_policy: deny
  rules:
    - domain: service.example.com
      policy: bypass
      networks:
      - 192.168.1.23/32
    - domain: '*.example.com'
      policy: one_factor
      subject: 'user:statping'
   - domain: '*.example.com'
      policy: bypass
      resources:
        - '^/api.*$'
```
