### ISSUE TITLE
high memory consumption even though sha512 is configured

### ISSUE THREAD

**Issue by tribor** [authelia/authelia#1355]
I experience memory issues similar to issues#845. So I tried to use sha512 password hashing but still the argon2id algorithm is being used for hash generation. After the first successful login the memory cosumption rises up to 1GB.

used version:
`Authelia version v4.22.0, build 1684ffb98997cd4243e887340e5a4ab29a5eaf86`

steps to reproduce:
1. change config in `authelia/compose/local/authelia/configuration.yml`:
```
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: sha512
```
2. run setup.sh from authelia/compose/local
3. memory usage is about 20 MiB
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
f07face7ef1b        authelia            0.00%               20.68MiB / 3.848GiB   0.52%               876B / 0B           0B / 0B             8
```
4. check generated file `/config/users_database.yml` in authelia container to see wrong algorithm beeing used:
```
# List of users
users:
  user:
    displayname: "Mr User"
    password: "$argon2id$v=19$m=1048576,t=1,p=8$S1FLblU5V2pTVFhud0VqVA$m8kpAb6wnHaIOFzftDpkRquChEg9DjI7j4A0Dat28Zg"
    email: user@example.com
    groups:
      - admins
      - dev
```
5. manually generate sha512  hash
```
/app # authelia hash-password foo -z
Password hash: $6$rounds=50000$c1ErMGtKMnRHK3VN$pb3MXVlVNUzuZ6.ac580xBitxhfkO1JodGI.HhZoHN/EUjyQXlWbOt2s4MGE0DOpch99my3uort3qYsu0566R.
```
6. change hash in file  `/config/users_database.yml`  to:
```
users:
  user:
    displayname: "Mr User"
    password: "$6$rounds=50000$c1ErMGtKMnRHK3VN$pb3MXVlVNUzuZ6.ac580xBitxhfkO1JodGI.HhZoHN/EUjyQXlWbOt2s4MGE0DOpch99my3uort3qYsu0566R."
    email: user@example.com
    groups:
      - admins
      - dev
```
7. after login to traefik.example.com the memory usage is
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
1dcb7ce27f48        authelia            0.05%               1.055GiB / 3.848GiB   27.41%              28kB / 12.8kB       0B / 0B             7
```

**Comment by tribor** [comment]
Note: I also tried to use `argon2id` with low parameters for parallelism and memory (8/64 or even 1/8) but this changes nothing on the memory beeing used (I did restart the containers)

**Comment by james-d-elliott** [comment]
So with the following configs I cannot replicate your issue. The important part is the $6$ prefix which tells Authelia the algo is sha512 (it supports both even though the algo is set to sha512, just if anyone changes their password the new one will be sha512). Can you make absolutely sure you're editing the correct file by changing the username and ensuring you're using the hash you generated using the authelia binary?

```yaml
users:
  user:
    displayname: "Mr User"
    password: "$6$rounds=50000$c1ErMGtKMnRHK3VN$pb3MXVlVNUzuZ6.ac580xBitxhfkO1JodGI.HhZoHN/EUjyQXlWbOt2s4MGE0DOpch99my3uort3qYsu0566R."
    email: user@mr.com
    groups:
      - owner
      - administrator
```

```yaml
authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: sha512
      iterations: 50000
      key_length: 32
      salt_length: 32
```
