### ISSUE TITLE
Access user/group from request headers using traefik

### ISSUE THREAD

**Issue by blaskowitz100** [authelia/authelia#1367]
Hello everyone,

I have some problem accessing the information about the current user from the headers. At the moment I am using authelia in combination with traefik to secure my services in a docker compose setup.

So far everything is working as expected. I can logging to all the services. But I am not able to receive the information which user is currently logged in. As far as I understood the documentation I have to forward the auth headers from authelia in traefik:

```
...
authelia:
    build:
      context: .
      dockerfile: apps/traefik-proxy/authelia/Dockerfile
    image: argos_ibm_authelia:1.1.0
    container_name: authelia
    depends_on:
      - redis
    networks:
      - auth_network
    volumes:
      # Overwrite prod config
      - ./apps/traefik-proxy/authelia/dev:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.example.com`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.certresolver=letsencrypt'

      # Default authentication service with redirection to the user interface of authelia
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=http://auth.example.com'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups'
    expose:
      - 9091
    restart: unless-stopped
whoami:
  image: containous/whoami
      container_name: public
      networks:
        - argos_ibm_network
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.public.rule=Host(`whoami.example.com`)'
        - 'traefik.http.routers.public.entrypoints=https'
        - 'traefik.http.routers.public.tls=true'
        - 'traefik.http.routers.public.tls.options=default'
        - 'traefik.http.routers.public.middlewares=authelia@docker'
      expose:
        - 80
      restart: unless-stopped
...
```

If I call the subdomain `whoami.example.com` I see that those auth headers are available, after I have logged in using the authelia user interface:

```
Hostname: 149d82e86e34
IP: 127.0.0.1
IP: 172.28.0.4
RemoteAddr: 172.28.0.8:47788
GET / HTTP/1.1
Host: auth.example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de;q=0.8
Cache-Control: no-cache
Cookie: _ga=GA1.2.1225504843.1601629415; authelia_session=ICQOkGprpSbmyuihBONHIgxpXzvQjbsu
Pragma: no-cache
Referer: https://auth.example.com/
Remote-Groups: admins,dev
Remote-User: sme
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-site
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 192.168.60.1
X-Forwarded-Host: auth.example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: 2b9285a215a5
X-Real-Ip: 192.168.60.1
``` 

But if I check the headers of an GET request against an additional API service that is secured with the same traefik middleware, I dont see those headers (Remote-User, Remote-Group)...

Can somebody explain me how I can get access to this headers?
