### ISSUE TITLE
Restart required to apply newly added users when using file backend

### ISSUE THREAD

**Issue by mawilmsen** [authelia/authelia#1378]
I need to reinstantiate (i.e. docker stack remove, docker stack deploy) my authelia instance after I add new users, otherwise the users are not found. Is that the expected behaviour? I am using the file authentication backend and running in docker swarm mode. 

I did expect authelia to automatically watch for changes in the users file and automatically reload the contents. However, that doesn't happen.

My authentication backend config:

```
authentication_backend:
  disable_reset_password: true
  file:
    path: /config/users.yml
    password:
      algorithm: sha512
```

and my docker compose config to mount the users file:

```
  authelia:
    image: authelia/authelia
    volumes:
      - ./authelia:/config
```

Thanks for helping!
