### ISSUE TITLE
Redis Error 'Set secret of the session object'

### ISSUE THREAD

**Issue by undaunt** [authelia/authelia#1380]
Hello all,

When trying to configure redis within authelia I'm hitting the title error: Set secret of the session object. The authelia container and redis are both accessible to each other on the same overlay bridge network (my traefik proxy network) and I can ping redis from within Authelia's shell prompt. The secret is showing up properly within /run/secrets/authelia_session_redis_password.

I'm currently using an environmental variable to set the redis password, and am able to connect to redis with redis-commander via the same variable passing the password. The same value of the variable is stored as the docker secret. I also tested this with no password, and with the password embedded directly in the configuration file - all the same result.

As soon as I remove redis from the authelia configuration, everything works. I'm not sure what is happening. Thanks for any insight.

```
  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    networks:
      - $TRAEFIK_NETWORK
    entrypoint: redis-server --appendonly yes --requirepass $REDIS_PASSWORD --maxmemory 1024mb --maxmemory-policy allkeys-lru
    ports:
      - "$REDIS_PORT:6379"
    security_opt:
      - no-new-privileges:true
    sysctls:
      net.core.somaxconn: '65535'
    volumes:
      - ${DOCKERDIR}/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  authelia:
    image: authelia/authelia:4.20
    container_name: authelia
    restart: always
    networks:
      - $TRAEFIK_NETWORK
    depends_on:
      - mariadb
    security_opt:
      - no-new-privileges
    volumes:
      - $DOCKERDIR/authelia:/config
    environment:
      - TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE/run/secrets/authelia_session_secret
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/authelia_session_redis_password
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
      - authelia_storage_mysql_password
      - authelia_session_redis_password
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
```
