### ISSUE TITLE
Storage schema upgrade failed at v1 on update to V4.23

### ISSUE THREAD

**Issue by Elmardus** [authelia/authelia#1441]
On updating to the new release (using docker-compose) from V4.22 to 4.23, Authelia fails to initialize the SQL database with the following error:

```
time="2020-11-10T11:37:31+02:00" level=info msg="Logging severity set to debug"
time="2020-11-10T11:37:31+02:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2020-11-10T11:37:31+02:00" level=debug msg="Storage schema is v0, latest is v1"
time="2020-11-10T11:37:31+02:00" level=fatal msg="Unable to initialize SQL database: storage schema upgrade failed at v1: Unable to /mysql_provider.go:77 NewMySQLProvidergithub.com/authelia/authelia/cmd/authelia/main.go:76               startServer\ngithub.com/aommand.go:943                       (*Command).ExecuteC\ngithub.com/spf13/cobra@v0.0.7/command.go:883                       (*Comman                                        goexit"
```

Reverting to `image: authelia/authelia:4.22` resolves this issue. I am using the latest mariadb docker-image, set up in configuration.yml as shown below:

```
storage:
  mysql:
    host: authelia-db
    port: 3306
    database: authelia
    username: authelia
    password: redacted
```

Did I configure my database incorrectly? Or is this caused by a recent change?

**Comment by james-d-elliott** [comment]
We added one table. What MariaDB version did you use? I'm sure we tested that upgrade, wondering if it's something specific to the version or your setup.

Does the Authelia user have create table perms on that DB?

**Comment by Elmardus** [comment]
I am on the lastest mariadb docker image, which is _1:10.5.7+maria~focal_. 
To be honest I am not sure about the permissions on that DB, I haven't configured anything in the mariadb except the following in the docker-compose file:

```
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /home/Authelia:/config
    expose:
      - 9091
    restart: unless-stopped
    depends_on:
      - authelia-db
      - authelia-redis

  authelia-db:
    image: mariadb
    container_name: authelia-db
    restart: unless-stopped
    expose:
      - 3306      
    volumes:
      - /home/Authelia/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redacted
      - MYSQL_PASSWORD=redacted
      - MYSQL_DATABASE=authelia
      - MYSQL_USER=authelia
```

The following tables exist now (I reverted to 4.22)
```
root@b2d6ebee6668:/# mysqlshow authelia -p               
Database: authelia
+------------------------------+
|            Tables            |
+------------------------------+
| authentication_logs          |
| config                       |
| identity_verification_tokens |
| totp_secrets                 |
| u2f_devices                  |
| user_preferences             |
+------------------------------+
```
