### ISSUE TITLE
List of subjects not working as explained in docs

### ISSUE THREAD

**Issue by LukasK13** [authelia/authelia#1447]
Thanks for this awesome project, I love it.

I tried using a list of subjects as explained in the docs under [Access Control](https://www.authelia.com/docs/configuration/access-control.html) using

```
    - domain: dev.example.com
      subject: 
      - ["group:dev", "user:john"]
      policy: two_factor
```
which didn't work for me. However
```
    - domain: dev.example.com
      subject: ["group:dev", "user:john"]
      policy: two_factor
```
worked for me (notice the missing `- ` for the list of subjects).
The docs mention that this dash is required "Make sure to preceed it by a list key -".

I'm not sure if this is a mistake in the docs or a bug.
