### ISSUE TITLE
Docker Container Unhealthy in 4.23.1

### ISSUE THREAD

**Issue by JeffResc** [authelia/authelia#1461]
Hello all and thank you for the great project. I recently updated my container from 4.23.0 to 4.23.1 and when running `docker ps`, I can see that the authelia container is `unhealthy`. As a temporary fixed, I've rolled back to 4.23.0 where this isn't an issue. Is this an issue with my configuration and breaking changes or an error within the project?

Logs when running 4.23.1:
```
time="2020-11-14T00:20:01-05:00" level=info msg="Logging severity set to debug"
time="2020-11-14T00:20:02-05:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2020-11-14T00:20:02-05:00" level=debug msg="Storage schema is up to date"
time="2020-11-14T00:20:02-05:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
time="2020-11-14T00:20:02-05:00" level=debug msg="Notifier SMTP client attempting connection to xxx.xxx.xxx:587"
time="2020-11-14T00:20:04-05:00" level=debug msg="Notifier SMTP client connected successfully"
time="2020-11-14T00:20:04-05:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: xxx.xxx.xxx), attempting"
time="2020-11-14T00:20:04-05:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2020-11-14T00:20:04-05:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: PLAIN LOGIN"
time="2020-11-14T00:20:04-05:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2020-11-14T00:20:04-05:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2020-11-14T00:20:04-05:00" level=warning msg="Error reading hosts memory limit: open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory"
time="2020-11-14T00:20:04-05:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
```

I'm running authelia/authelia:4.23.1 on arch64/aarch64.

Image information:
```
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
authelia/authelia                          latest              8fa2d96139ea        3 days ago          30.1MB
```

Thank you :smile:

**Comment by nightah** [comment]
Thanks for the report @JeffResc can you please provide the outputs of the following commands from within your container (`docker exec -it authelia ash`):

1. `ls -lah /usr/bin/local/`
2. `ps | grep authelia | awk '{print $6}' | head -1`
3. `cat /config/configuration.yml | grep ^tls`
4. `cat /config/configuration.yml | grep ^port | sed -e 's/port: //'`

**Comment by JeffResc** [comment]
@nightah Thanks for the reply, here are the outputs:
```
/app # ls -lah /usr/bin/local/
ls: /usr/bin/local/: No such file or directory
```
```
/app # ps | grep authelia | awk '{print $6}' | head -1
/config/configuration.yml
```
```
/app # cat /config/configuration.yml | grep ^tls
```
```
/app # cat /config/configuration.yml | grep ^port | sed -e 's/port: //'
9091
```

**Comment by nightah** [comment]
Sorry first one should have been: `ls -lah /usr/local/bin/`. So far everything looks right, which is odd.

Can you try the following in the container and provide me the output to the last command please:
`cd /usr/local/bin`
`echo -e '\necho ${AUTHELIA_SCHEME}://localhost:${AUTHELIA_PORT}/api/state' >> healthcheck.sh`
`./healthcheck.sh; echo $?`

**Comment by JeffResc** [comment]
@nightah Thanks again. Here's the output of the two commands:
```
/app # ls -lah /usr/local/bin/
total 16K    
drwxr-xr-x    1 root     root        4.0K Nov 11 00:21 .
drwxr-xr-x    1 root     root        4.0K Oct 21 05:25 ..
-rwxr-xr-x    1 root     root         238 Nov 10 22:53 entrypoint.sh
-rwxr-xr-x    1 root     root         464 Nov 10 22:53 healthcheck.sh
```

```
/usr/local/bin # ./healthcheck.sh; echo $?
'get: bad port spec 'localhost:9091
1
```

**Comment by nightah** [comment]
Alright so looks like it thinks there's an issue with the `healthcheck.sh`.
`cat /usr/local/bin/healthcheck.sh` please.

**Comment by JeffResc** [comment]
```
/app # cat /usr/local/bin/healthcheck.sh
#!/bin/sh

AUTHELIA_CONFIG=$(ps | grep authelia | awk '{print $6}' | head -1)
AUTHELIA_SCHEME=$(cat "${AUTHELIA_CONFIG}" | grep ^tls)
AUTHELIA_PORT=$(cat "${AUTHELIA_CONFIG}" | grep ^port | sed -e 's/port: //')

if [[ -z ${AUTHELIA_PORT} ]]; then
  AUTHELIA_PORT=9091
fi

if [[ -z ${AUTHELIA_SCHEME} ]]; then
  AUTHELIA_SCHEME=http
else
  AUTHELIA_SCHEME=https
fi

wget --quiet --tries=1 --spider ${AUTHELIA_SCHEME}://localhost:${AUTHELIA_PORT}/api/state || exit 1/app
```

**Comment by nightah** [comment]
I mean this is really odd based on what you have provided the `healthcheck.sh` should be running the following command for you:

`wget --quiet --tries=1 --spider http://localhost:9091/api/state`

Does the below command return a `0` for you?

`wget --quiet --tries=1 --spider http://localhost:9091/api/state; echo $?`

**Comment by JeffResc** [comment]
Yes, it seems to.
```
/app # wget --quiet --tries=1 --spider http://localhost:9091/api/state; echo $?
0
```

**Comment by nightah** [comment]
The script looks fine and I can't seem to replicate the issue on any of my machines.

Can you try removing the contents of the script and pasting it back in with vi inside the container?

Then try run it again with `./healthcheck.sh; echo $?`

**Comment by JeffResc** [comment]
I copied the above output from `cat /usr/local/bin/healthcheck.sh` and used that. I did `chmod +x /usr/local/bin/healthcheck.sh` to make it executable and then ran it.
```
/app # /usr/local/bin/healthcheck.sh
cat: can't open '': No such file or directory
cat: can't open '': No such file or directory
/app # echo $AUTHELIA_CONFIG

```

**Comment by JeffResc** [comment]
Wait, sorry. I'm not accustomed to vi and messed up when pasting it back in. I added nano to the container and re-did everthing. Here's the new output:
```
/app # /usr/local/bin/healthcheck.sh
'get: bad port spec 'localhost:9091
/app #
```

**Comment by nightah** [comment]
It could be line endings could you try dos2unix and convert them to LF?

**Comment by nightah** [comment]
Could you post the output of:
`cat -e /usr/local/bin/healthcheck.sh`

This should show us the line endings of the file to see if that's causing any issues.

**Comment by JeffResc** [comment]
Hm, not sure if that helped anything
```
/app # cat -e /usr/local/bin/healthcheck.sh
#!/bin/sh$
$
AUTHELIA_CONFIG=$(ps | grep authelia | awk '{print $6}' | head -1)$
AUTHELIA_SCHEME=$(cat "${AUTHELIA_CONFIG}" | grep ^tls)$
AUTHELIA_PORT=$(cat "${AUTHELIA_CONFIG}" | grep ^port | sed -e 's/port: //')$
$
if [[ -z ${AUTHELIA_PORT} ]]; then$
  AUTHELIA_PORT=9091$
fi$
$
if [[ -z ${AUTHELIA_SCHEME} ]]; then$
  AUTHELIA_SCHEME=http$
else$
  AUTHELIA_SCHEME=https$
fi$
$
wget --quiet --tries=1 --spider ${AUTHELIA_SCHEME}://localhost:${AUTHELIA_PORT}/api/state || exit 1/app # 
```

```
/app # dos2unix /usr/local/bin/healthcheck.sh 
/app # /usr/local/bin/healthcheck.sh 
'get: bad port spec 'localhost:9091
```

**Comment by JeffResc** [comment]
Also here are my configuration files with some redacted information. I figured the move I could provide, the better

configuration.yml
```yml
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: xxx
default_redirection_url: https://xxx.xxx.xxx
totp:
  issuer: xxx.xxx

#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 128

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: xxx.xxx.xxx
      policy: one_factor
    - domain: xxx.xxx.xxx
      policy: one_factor
    - domain: xxx.xxx.xxx
      policy: one_factor
    - domain: xxx.xxx.xxx
      policy: bypass
    - domain: xxx
      policy: bypass
    - domain: xxx.xxx
      policy: bypass
    - domain: xxx.xxx.xxx
      policy: one_factor
    - domain: xxx.xxx.xxx
      policy: bypass
    - domain: xxx.xxx.xxx
      policy: one_factor
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: xxx
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: xxx.xxx # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: xxx@xxx.xxx
   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: xxxx
    host: xxx.xxx.xxx
    port: xxx
    sender: xxx@xxx.xxx
```

users_database.yml
```yml
users:
  xxx:
    password: xxx
    displayname: xxx
    email: xxx@xxx.xxx
    groups:
    - admins
  xxx:
    password: xxx
    displayname: xxx
    email: xxx@xxx.xxx
    groups:
    - admins
```

**Comment by xhitman** [comment]
Hello, I can confirm that there's an issue with the latest version, a container doesn't start. When rolling back to the previous version (as an author of this topic) everything works fine again. When I check the logs, there're no errors. I use docker swarm mode on a dev virtual machine.

**Comment by nightah** [comment]
Just to be clear this issue does not result in the container not starting.

This issue specifically is relating to an unhealthy container, which may have implications if you're running with Traefik.
@james-d-elliott attempted to replicate this without success on a RPi3 with Ubuntu focal and Docker from the official Docker repo.

@JeffResc what OS/Docker version are you running?
Can you provide the outputs of `docker info` and `docker version` too please?

**Comment by JeffResc** [comment]
Running Ubuntu 20.04.1 LTS on the Raspberry Pi 4
 ```
ubuntu@lambda-pi:~$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1022-raspi
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.805GiB
 Name: lambda-pi
 ID: JMKJ:RLIF:Y5IR:JEG6:NB7K:IG6Q:CF5Y:NIV3:I42K:HDKV:SL5E:HZ7U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
```
```
ubuntu@lambda-pi:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 17:03:40 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Wed Sep 16 17:02:11 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
```
ubuntu@lambda-pi:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by nightah** [comment]
Is that utilising Docker with [these instructions](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)?

**Comment by JeffResc** [comment]
@nightah I installed using the script at [https://get.docker.com/](https://get.docker.com/)

**Comment by mikurth** [comment]
Hi, have a issue with the healthcheck.sh as the executed wget was not allowed as i had defined the host that auhtelia should listen to in configuration.yml:

# The host and port to listen on
#host: 172.20.0.2
port: 9091

uncommenting it as above makes it work and trafik works just fine again. Would be great if the host from config file could be used

**Comment by nightah** [comment]
We definitely can update the script to determine the host from the config, but I'm curious as to why you've set the host to what appears to me as the container IP in the Docker network?

By setting it to 0.0.0.0 or blank as long as you don't expose the port to the host you would achieve the same outcome.

**Comment by 9SMTM6** [comment]
Simular situation here. authelia/authelia:4.23.2, Unraid OS 6.8.3 (Linux 4.19.107-Unraid x86_64). Thats not an ARM Platform.

Container starts, but is unhealthy, which leads to traefik never establishing a route. Logs at debug don't show anything interesting:

```
time="2020-11-20T21:41:09Z" level=info msg="Logging severity set to debug"
time="2020-11-20T21:41:09Z" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2020-11-20T21:41:09Z" level=debug msg="Storage schema is up to date"
time="2020-11-20T21:41:09Z" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
```

Config:
```
###############################################################
#                   Authelia configuration                    #
###############################################################

# host: 0.0.0.0
port: 9091
log_level: debug

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE
# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.XX.YY

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

access_control:
  default_policy: deny
  rules:
    - domain: authelia.XX.YY
      policy: bypass
    - domain:
        - "*.XX.YY"
        - "XX.YY"
      policy: one_factor # two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: XX.YY # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120 #secounds
  ban_time: 300 #secounds

storage:
  local:
    path: /config/db.sqlite3

notifier:
  # For testing purposes, notifications can be sent in a file. Be sure to map the volume in docker-compose.
  filesystem:
    filename: /config/notification.txt
```

A relevant snippet from docker inspect:
```
"Health": {
                "Status": "unhealthy",
                "FailingStreak": 8,
                "Log": [
                    {
                        "Start": "2020-11-20T22:43:41.072674506+01:00",
                        "End": "2020-11-20T22:43:41.14007241+01:00",
                        "ExitCode": 1,
                        "Output": "wget: bad port spec 'localhost:9091\r'\n"
                    },
```

repeats like that.

Whether i comment in or not the line `host: 0.0.0.0` doesn't appear to make a difference.

Version 4.23.0 seems to work.

Docker is as installed by Unraid:
```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.7.3
  Library Version: 101
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.107-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.67GiB
 Name: 3LockedChest
 ID: 2XOQ:AVOS:HZMX:SCWK:M4HO:L7ZH:QHEZ:HV67:FLKC:QUQG:HFKV:SN5V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```
