### ISSUE TITLE
Unauthorized all the time: bug from /sys/fs/cgroup/memory/memory.limit_in_bytes ?

### ISSUE THREAD

**Issue by schklom** [authelia/authelia#1502]
Hi everyone !

I am having the same problem as [here](https://github.com/authelia/authelia/issues/1461), but their solutions don't work for me. After starting the container, every site with `authelia` middleware gives back an "Unauthorized" response.

Would anyone please help me ?

I want to use `authelia` along with `traefik` on my Raspberry Pi 4. Without `authelia` my services work fine.
Here are my redacted logs for `authelia`.
```
time="2020-12-02T23:33:22+01:00" level=info msg="Logging severity set to debug"
time="2020-12-02T23:33:22+01:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2020-12-02T23:33:22+01:00" level=debug msg="Storage schema is up to date"
time="2020-12-02T23:33:22+01:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
time="2020-12-02T23:33:22+01:00" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:587"
time="2020-12-02T23:33:22+01:00" level=debug msg="Notifier SMTP client connected successfully"
time="2020-12-02T23:33:23+01:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: smtp.gmail.com), attempting"
time="2020-12-02T23:33:23+01:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2020-12-02T23:33:23+01:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"
time="2020-12-02T23:33:23+01:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2020-12-02T23:33:23+01:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2020-12-02T23:33:23+01:00" level=warning msg="Error reading hosts memory limit: open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory"
time="2020-12-02T23:33:23+01:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
time="2020-12-02T23:38:51+01:00" level=error msg="The target URL https://hell.MYDOMAIN:EXTPORT/ is not under the protected domain authelia.MYDOMAIN" method=GET path=/api/verify remote_ip=10.2.0.5 stack="github.com/authelia/authelia/internal/handlers/handler_verify.go:412     VerifyGet.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.2.4/router.go:348                          (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.15.1/server.go:2162                       (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.15.1/workerpool.go:223                    (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.15.1/workerpool.go:195                    (*workerPool).getCh.func1\nruntime/asm_arm.s:857
```

I don't know which file is relevant, so here are most of them.

<details><summary>configuration.yml (my domain is written MYDOMAIN:EXTPORT)</summary>

```
host: 0.0.0.0
port: 9091
log_level: debug
default_redirection_url: "https://auia.MYDOMAIN:EXTPORT/"
#jwt_secret: set as a secret

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 128 # tried 1024, problem didn't change
      parallelism: 8

access_control:
# I'm trying to bypass everything to reduce source of errors, until I can get this working
  default_policy: bypass

session:
  name: authelia_session
  #secret: insecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1d
  domain: "authelia.MYDOMAIN"

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
  mysql:
    host: authelia-db
    port: 3306
    database: authelia
    username: authelia
    #password: set as a secret
  disable_startup_check: false

  smtp:
    username: MYEMAIL@gmail.com
    #password: set as a secret
    host: smtp.gmail.com
    port: 587
    sender: MYEMAIL@gmail.com
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    trusted_cert: ""
    disable_require_tls: false
    disable_verify_cert: false
    disable_html_emails: false
```
</details>

<details><summary>users_database.yml</summary>

```
users:
  username:
    displayname: "schklom"
    password: "$argon2id$v=19$blablabla"
    email: MYEMAIL@gmail.com
    groups:
      - admins
      - dev
```

</details>
<details><summary>docker-compose.yml</summary>

```
version: "3.8"

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKERCONFIG}/authelia:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_mysql_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_mysql_password
      - authelia_notifier_smtp_password
      - authelia_redis_pass
    depends_on:
      - authelia-db
    restart: unless-stopped
    networks:
      - 1authelia-net
      - auth-db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`${AUTHELIA_DOMAIN_NAME}`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTHELIA_DOMAIN_NAME}:${HTTPS_WAN_PORT}'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'

  authelia-db:
    image: linuxserver/mariadb
    container_name: authelia-db
    restart: on-failure:2
    security_opt:
      - no-new-privileges:true
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/authelia_mysql_root_password
      - FILE__MYSQL_DATABASE=/run/secrets/authelia_mysql_database
      - FILE__MYSQL_USER=/run/secrets/authelia_mysql_user
      - FILE__MYSQL_PASSWORD=/run/secrets/authelia_mysql_password
      - TZ=${TZ}
    secrets:
      - authelia_mysql_root_password
      - authelia_mysql_database
      - authelia_mysql_user
      - authelia_mysql_password
    volumes:
      - ${DOCKERDATA}/authelia-db:/config
    networks:
      - auth-db

  traefik:
    image: "traefik:v2.3"
    container_name: traefik
    restart: on-failure:2
    security_opt:
      - no-new-privileges:true
    ports:
      - ${TRAEFIK_PORT_443}:443
      - ${TRAEFIK_PORT_80}:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFIG}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${DOCKERCONFIG}/traefik/dynamic_conf.yml:/etc/traefik/dynamic_config.yml:ro
      - ${DOCKERCONFIG}/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERCONFIG}/traefik/traefik.log:/var/log/traefik.log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - 1authelia-net

networks:
  1authelia-net:
  auth-db:

secrets:
  authelia_session_secret:
    file: ${DOCKERCONFIG}/secrets/authelia_session_secret
  authelia_mysql_root_password:
    file: ${DOCKERCONFIG}/secrets/authelia_mysql_root_password
  authelia_mysql_database:
    file: ${DOCKERCONFIG}/secrets/authelia_mysql_database
  authelia_mysql_user:
    file: ${DOCKERCONFIG}/secrets/authelia_mysql_user
  authelia_mysql_password:
    file: ${DOCKERCONFIG}/secrets/authelia_mysql_password
  authelia_notifier_smtp_password:
    file: ${DOCKERCONFIG}/secrets/authelia_notifier_smtp_password
  authelia_redis_pass:
    file: ${DOCKERCONFIG}/secrets/authelia_redis_pass
```

</details>

In case you're wondering, I handle port 80 and HTTPS in `traefik` config files. They're useless here so I don't show them.

And lastly, `PUID` and `PGID` are the main user with sudo capabilities (like the default "pi" user in a Raspberry Pi).

Many thanks to anyone who will take time to help me through this :)

**Comment by nightah** [comment]
Your `domain` setting is set to your Authelia sub-domain, this means it can only protect sites under that domain or subdomains of `authelia.MYDOMAIN` such as `*.authelia.MYDOMAIN`.

```
session:
  name: authelia_session
  #secret: insecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1d
  domain: "authelia.MYDOMAIN"
```

You should be setting your domain to your root domain, so `domain: "MYDOMAIN"` for example: `domain: example.com`
