### ISSUE TITLE
Authelia Mariadb 10.5; level=fatal msg="Unable to initialize SQL database

### ISSUE THREAD

**Issue by Daniel-WW** [authelia/authelia#1510]
Hello, 

I'm a very newbie in using services with docker. In the last weeks I learned hard and long lessons in setting up docker-compose, traefik v2, mariadb, authelia...

Now I did my setup for authelia, trying to use for storage a mysql database with mariadb 10.5, but anyhow authelia is not able to connect to the database. I receive the following response from logs:

`time="2020-12-03T20:11:57+01:00" level=fatal msg="Unable to initialize SQL database: dial tcp 192.168.90.250:3306: connect: no route to host" stack="github.com/authelia/authelia/internal/storage/mysql_provider.go:77 NewMySQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:75               startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:120              main.func1\ngithub.com/spf13/cobra@v0.0.7/command.go:842                       (*Command).execute\ngithub.com/spf13/cobra@v0.0.7/command.go:943                       (*Command).ExecuteC\ngithub.com/spf13/cobra@v0.0.7/command.go:883                       (*Command).Execute\ngithub.com/authelia/authelia/cmd/authelia/main.go:137              main\nruntime/proc.go:204                                                main\nruntime/asm_amd64.s:1374                                           goexit"
`

Here is my storage code in configuration.yml
>storage:
>  mysql:
>host: 192.168.90.250
>port: 3306
>database: authelia
>username: xxx

If I use local storage with 
`  local:
    path: /config/db.sqlite3`
the it works and I can open authelia. 

So I would be very grateful for every kind of help. I could post more of my code, but I'm not sure what ist necessary or wich step is important first to check. 

Thank you for your help in advance. Best regards - Daniel

**Comment by nightah** [comment]
Is your MariaDB also running in a container or is that on your host?

Can you provide your `docker-compose.yml` including Authelia and MariaDB please?

**Comment by Daniel-WW** [comment]
Hello, 

yes MariaDB is also running in a container. Here is my (reduced) `docker-compose.yml`:

```yaml
version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy
  default:
    driver: bridge
  socket_proxy:
    external:
      name: socket_proxy
    
########################### SECRETS
secrets:
  cloudflare_email:
    file: $SECRETSDIR/cloudflare_email
  cloudflare_api_key:
    file: $SECRETSDIR/cloudflare_api_key
  mysql_root_password:
    file: $SECRETSDIR/mysql_root_password
  redis_password:
    file: $SECRETSDIR/redis_password
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  authelia_storage_mysql_password:
    file: $SECRETSDIR/authelia_storage_mysql_password
  authelia_notifier_smtp_password:
    file: $SECRETSDIR/authelia_notifier_smtp_password
  authelia_duo_api_secret_key:
    file: $SECRETSDIR/authelia_duo_api_secret_key

########################### SERVICES
services:
# All services / apps go below this line

  ############################# FRONTENDS

  # Traefik 2 - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:picodon # the chevrotin tag refers to v2.2.x
    restart: unless-stopped
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true
      # - --api.insecure=true
      - --api.dashboard=true
      # - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      # - --providers.docker.endpoint=unix:///var/run/docker.sock # Use Docker Socket Proxy instead for improved security
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      # - --providers.docker.defaultrule=HostHeader(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)
      - --providers.docker.exposedByDefault=false
      # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services.
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=$DOMAINNAME
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME
      # - --entrypoints.https.http.tls.domains[1].main=$DOMAIN # Pulls main cert for second domain
      # - --entrypoints.https.http.tls.domains[1].sans=*.$DOMAIN # Pulls wildcard cert for second domain
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
      # - --providers.file.filename=/path/to/file # Load dynamic configuration from a file.
      - --providers.file.watch=true # Only works on top level files in the rules folder
      # - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90 # To delay DNS check and reduce LE hitrate
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.254 # You can specify a static IP
    # networks:
    #   - t2_proxy
      socket_proxy:
    depends_on:
      - socket-proxy

    security_opt:
      - no-new-privileges:true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - $DOCKERDIR/traefik2/rules:/rules # file provider directory
    #  - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
      - $DOCKERDIR/traefik2/acme/acme.json:/acme.json # cert location - you must touch this file and change permissions to 600
      - $DOCKERDIR/traefik2/traefik.log:/traefik.log # for fail2ban - make sure to touch file before starting the container
      - $DOCKERDIR/shared:/shared
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/cloudflare_email
      - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key
      - DOCKER_HOST=tcp://socket-proxy:2375
      # - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      # - CF_API_KEY=$CLOUDFLARE_API_KEY
    secrets:
      - cloudflare_email
      - cloudflare_api_key
    labels:
      - "traefik.enable=true"
      ## HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      ## HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      # - "traefik.http.routers.traefik-rtr.rule=HostHeader(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
      # - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs
    
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file"

  ##...

  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    # image: authelia/authelia:4.21.0
    restart: unless-stopped
    networks:
      - t2_proxy
    #  t2_proxy:
    #    ipv4_address: 192.168.90.240
    expose: 
      - 9091
    depends_on:
      - mariadb
      - redis
    volumes:
      - $DOCKERDIR/authelia:/config #:ro
      - $DOCKERDIR/authelia:/var/lib/authelia
      - $DOCKERDIR/authelia/users_database.yml:/etc/authelia/users_database.yml

    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=HostHeader(`authelia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-basic-auth@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"

  ###...

  ############################# DATABASE

  # MariaDB - MySQL Database
  # After starting container for first time dexec and mysqladmin -u root password <password>
  mariadb:
    container_name: mariadb
    image: mariadb/server:latest
    restart: always
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.250

    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/mariadb/data:/config
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password # Not taking this pw during initialization
    secrets:
      - mysql_root_password

  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:6.0.6
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes --requirepass "$$(cat $$REDIS_PASSWORD_FILE)" --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.252
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/redis/data:/data
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - redis_password 

  ##...

  # phpMyAdmin - Database management
  # Create a new user with admin privileges. Cannot login as MySQL root for some reason.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.251

    depends_on:
      - mariadb
    security_opt:
      - no-new-privileges:true
    # volumes:
    #  - $DOCKERDIR/phpmyadmin:/etc/phpmyadmin
    environment:
      - PMA_HOST=192.168.90.250
      - PMA_PORT=3306
    #  - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.phpmyadmin-rtr.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-rtr.rule=HostHeader(`pma.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-basic-auth@file"
    #  - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"


```

Docker is running on a Synology NAS 918+ and I tried to learn setup my docker-compose with the help an instructions on [Smarthomebeginner Blog](https://www.smarthomebeginner.com/docker-authelia-tutorial/#1_Authelia_Required_Configuration). 

Thanks for your help - Daniel

**Comment by james-d-elliott** [comment]
Can you take a look at the database in phpmyadmin? Tell us which tables exist and what the rows inside the config table look like if it exists?

**Comment by Daniel-WW** [comment]
Hello, thanks for your help and advices. If I tried to take a look at the database with myphpadmin, but I was not able to connect to the database. (I worked find before.) So I did a restart of the containers, tried again, but no success...
If I want to open the database by terminal I get the following output: 
```
$ sudo docker exec -ti mariadb /bin/bash
root@0e7f99d39ccb:/# mysql -u root -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@0e7f99d39ccb:/# 
```
For me it seams that root ist not able to connect to server at "localhost". 
I tried the proposed changes, running without static IP, but I got always the same output.  

I'm quite confused, because I was able to login an I could created the database before.

**Comment by james-d-elliott** [comment]
I would nuke the data volume for the container and start again if it were me, unless there is data you need. 

Also I generally recommend the bitnami images as they have been super reliable and easy to manage for me. Example below if you're interested, MARIADB_DATABASE, MARIADB_USER, and MARIADB_PASSWORD are only used on first run to create a new DB with a user who has full privileges to that DB.

```yaml
  mariadb:
    container_name: mariadb
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MARIADB_DATABASE=authelia
      - MARIADB_USER=authelia
      - MARIADB_PASSWORD=authelia_pass
    restart: always
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/mariadb/data:/config
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - mysql_root_password
```
