### ISSUE TITLE
LDAP groups for user always empty

### ISSUE THREAD

**Issue by zmiguel** [authelia/authelia#1517]
Hi, I'm unable to setup authelia using groups permission because the ldap groups for a user are always empty

**My Setup** *(docker)*

*osixia/openldap:latest* - as OpenLDAP server
*wheelybird/ldap-user-manager:v1.4* - as OpenLDAP Manager

**Authelia config**

```
ldap:
    implementation: custom
    url: ldap://openldap
    skip_verify: true
    start_tls: false
    minimum_tls_version: TLS1.2

    base_dn: dc=zmiguel,dc=me

    # An additional dn to define the scope to all users.
    additional_users_dn: ou=people

    users_filter: (&({username_attribute}={input})(objectClass=person))

    # An additional dn to define the scope of groups.
    additional_groups_dn: ou=groups
    
    groups_filter: (&(member={dn})(objectclass=groupOfNames))

    # The attribute holding the name of the group
    group_name_attribute: cn

    user: cn=admin,dc=zmiguel,dc=me
    password: <admin_password>
```
If using 
```
rules:
    - domain: "mydomain.example"
      subject: "group:users"
      policy: one_factor
```
I always get access denied because Authelia can't find the groups for my user.

If I remove `subject: "group:users"` it works because authelia ignores the groups

**Authelia Logs**

```
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="LDAP client starts a session over raw TCP"
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="Computed user filter is (&(uid=zmiguel)(objectClass=person))"
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="LDAP client starts a session over raw TCP"
authelia             | time="2020-12-08T21:30:51Z" level=debug msg="Credentials validation of user zmiguel is ok" method=POST path=/api/firstfactor remote_ip=redacted
authelia             | time="2020-12-08T21:30:51Z" level=debug msg="Mark authentication attempt made by user zmiguel" method=POST path=/api/firstfactor remote_ip=redacted
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="LDAP client starts a session over raw TCP"
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="Computed user filter is (&(uid=zmiguel)(objectClass=person))"
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="Computed groups filter is (&(member=uid=zmiguel,ou=people,dc=zmiguel,dc=me)(objectclass=groupOfNames))"
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="Details for user zmiguel => groups: [], emails [redacted]" method=POST path=/api/firstfactor remote_ip=redacted
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="Check authorization of subject username=zmiguel groups= ip=redacted and url https://redacted/."
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="No matching rule for subject username=zmiguel groups= ip=redacted and url https://redacted/... Applying default policy."
authelia             | time="2020-12-08T21:30:51Z" level=debug msg="Required level for the URL https://redacted/ is 3" method=POST path=/api/firstfactor remote_ip=redacted
authelia             | time="2020-12-08T21:30:51Z" level=debug msg="Redirection URL https://redacted/ is safe" method=POST path=/api/firstfactor remote_ip=redacted
authelia             | time="2020-12-08T21:30:51Z" level=trace msg="attempt successful: true, exec duration: 18, avg execution duration: 901, random delay ms: 30, total delay ms: 931, actual delay ms: 913" method=POST path=/api/firstfactor remote_ip=redacted
```

**What have I tried**

- replacing `groups_filter: (&(member={dn})(objectclass=groupOfNames))` with other objectclass, this one seems the correct one
- commenting or not `group_name_attribute: cn` but having it seems like the correct thing, as the group names are under cn
- Using NIS vs BIS LDAP database, no change

Please note this is my first time using LDAP on any project, so I might have miss-configured something.
If you need any other information please let me know.

Thank you.
