### ISSUE TITLE
Escape character error in regular expressions of resources (Access Control Policies)

### ISSUE THREAD

**Issue by homlett** [authelia/authelia#1523]
Hi there,

It seems Authelia doesn't support escape character in regex :
`time="2020-12-10T16:39:31Z" level=error msg="Error malformed yaml: line 34: found unknown escape character"`

The related `configuration.yml` part with the rule trying to match a string including `?`:
```
...
access_control:
  rules:
  - domain: secure.example.com
      resources:
        - "^/auth\?.*$"
      policy: one_factor
...
```
