### ISSUE TITLE
refresh_interval not working as expected 

### ISSUE THREAD

**Issue by aman207** [authelia/authelia#1638]
Hi,

I have refresh_interval set to always, however when I disable the user in AD after authenticating and refresh the page, I am still allowed access to the web page. Why is this? Based on the documentation for refresh_interval, I would expect authelia to revoke the session and bring me back to the login page. Is there something wrong with my configuration?

I believe users_filter is configured correctly, as I cannot login to a fresh session if the user is already disabled.

authelia config
```
host: 0.0.0.0
port: 9091

server:
  read_buffer_size: 4096

log_level: debug

jwt_secret: ...

authentication_backend:
  disable_reset_password: true
  refresh_interval: always

  ldap:
    implementation: activedirectory
    url: ldap://192.168.1.201
    base_dn: dc=home,dc=local,dc=lan
    username_attribute: sAMAccountName

    users_filter: (&({username_attribute}={input})(objectClass=person)(!userAccountControl:1.2.840.113556.1.4.803:=2)(!pwdLastSet=0))

    groups_filter: (&(member={dn})(objectclass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail

    user: cn=onionad,cn=Users,dc=home,dc=local,dc=lan
    password: ...
	
access_control:

  default_policy: one_factor

  networks:
    - name: internal
      networks:
        - 192.168.1.0/24
        - 192.168.0.0/24

session:
  name: authelia_session
  secret: "..."

  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: aman207.net

  redis:
    host: 127.0.0.1
    port: 6379
    database_index: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /home/onionadmin/db.sqlite3
```

nginx config
```

server {
	listen 443 ssl;
	server_name tauth.aman207.net;
		
	location / {
		proxy_pass http://192.168.1.111:9091/;
	}
}

server {
	listen 443 ssl;
	server_name tsonarr.aman207.net;
	
	proxy_buffering off;
	fastcgi_buffering off;
	
	location /authelia {
		internal;
		proxy_pass_request_body off;
		proxy_pass http://192.168.1.111:9091/api/verify;    
		proxy_set_header Content-Length "";

		proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

		client_body_buffer_size 128k;
		proxy_set_header Host $host;
		proxy_set_header X-Original-URL https://$http_host$request_uri;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $remote_addr; 
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Host $http_host;
		proxy_set_header X-Forwarded-Uri $request_uri;
		proxy_set_header X-Forwarded-Ssl on;
		proxy_redirect  http://  $scheme://;
		proxy_http_version 1.1;
		proxy_set_header Connection "";
		proxy_cache_bypass $cookie_session;
		proxy_no_cache $cookie_session;
		proxy_buffers 4 32k;

		send_timeout 5m;
		proxy_read_timeout 240;
		proxy_send_timeout 240;
		proxy_connect_timeout 240;
	}

	location / {
		auth_request /authelia;
		auth_request_set $target_url https://$http_host$request_uri;
		error_page 401 =302 https://tauth.aman207.net/?rd=$target_url;

		proxy_pass http://192.168.1.101:8989/;
	}
}
```

**Comment by james-d-elliott** [comment]
Thanks for notifying us of the issue. I'm going to try and replicate it. Would you be able to set the log level to trace and give us the logs? You can anonymize the domains/usernames/etc.

**Comment by james-d-elliott** [comment]
For reference, we've traced the entire flow of that and it looks fine, so something strange is happening. Also interested in which version you're using?

**Comment by aman207** [comment]
For sure, trace log here: [authelia-trace.txt](https://github.com/authelia/authelia/files/5884671/authelia-trace.txt) 
I logged in, refreshed the page once, disabled the user in AD and refreshed again. Stopped authelia shortly after.
Thanks for looking into this, let me know if there's anything else I can do/provide

Version is: `Authelia version v4.25.2, build bab776b850cd6b96b1a8be9c30566e2a935d237f`

**Comment by james-d-elliott** [comment]
I'm pretty sure I've found the location of the bug in the code. Currently it likely only refreshes user details if the rule has a group subject attached to it. I'm going to remove this check and just do it for all rules. You are welcome to test the validity of my theory by adding a group requirement to a domain - theoretically if I'm right it should work for those domains.

**Comment by aman207** [comment]
Yup, that is 100% it. 

Added these lines to the config. Authelia will now kick me back to the login screen if I disable the user.
Thanks again!
```
authentication_backend:
  ldap:
    groups_filter: (&(member={dn})(objectClass=group)(objectCategory=group))
    group_name_attribute: cn
	
access_control:  
  rules:
    - domain: "*.aman207.net"
      subject: "group:Test group"
      policy: one_factor
```
