### ISSUE TITLE
Login taking over 3-4 minutes

### ISSUE THREAD

**Issue by javatarz** [authelia/authelia#1707]
I'm running authelia using docker ([authelia/authelia:latest](https://hub.docker.com/r/authelia/authelia/tags?page=1&ordering=last_updated&name=latest)) and using [LSIO's swag](https://github.com/linuxserver/docker-swag) as my reverse proxy (which internally runs nginx).

When I enter my credentials, it takes authelia 4 minutes to log me in. At this point, top doesn't show any resources being blocked, specifically. At this time, it doesn't auto-redirect me to my target either. Hitting the root domain at this point helps me go to the logged in resource. No specific delays shown in nginx's logs. The request is quickly forwarded to authelia but authelia doesn't mark the user logged in for 3-4 minutes :(

Here's what the logs show (at trace)
```
time="2021-02-08T13:31:32+05:30" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=[redacted]
time="2021-02-08T13:34:47+05:30" level=debug msg="Mark authentication attempt made by user [redacted]" method=POST path=/api/firstfactor remote_ip=[redacted]
```

Note the 3-4 minute delay in noting that the login was successful. How do I debug this and figure out why it's so slow?

Related config (snipped out a lot, ask me if you want something specific)
```
server:
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: "authelia"

log_level: trace
log_format: text
log_file_path: /config/authelia.log

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m

  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 4

access_control:
  default_policy: deny

  rules:
    - domain: [redacted]
      policy: one_factor # Will be moved to two_factor when the system is stable

session:
  name: authelia_session
  expiration: 1d
  inactivity: 15m # Bumped this up from 5 recently to test
  remember_me_duration: 1M
  domain: [redacted]
  redis: # Added this to check if caching helps
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /config/db.sqlite3 # Can be changed if needed but I can't point towards this being the bottleneck

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt # Will be changed when stable
```

**Comment by javatarz** [comment]
Rebooted the machine once and the performance is better but still, quite slow at 37 seconds :(

```
time="2021-02-08T16:39:15+05:30" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=[redacted]
time="2021-02-08T16:39:52+05:30" level=debug msg="Mark authentication attempt made by user karun" method=POST path=/api/firstfactor remote_ip=[redacted]
```

The machine is quite under-powered but they CPU spiked to only about 25% during these 37 seconds. Is there a way to debug if the throttling is due to CPU, disk or some other reason?

**Comment by nightah** [comment]
Tune your memory for password hashing down to like 32MB:

`memory: 32`

The most common issue thing that affects login speed is the memory allocated when utilising a file based backend.

**Comment by nightah** [comment]
Our of curiosity what are the specs on the machine that you are running Authelia on?

**Comment by javatarz** [comment]
Just tested against the new configuration (`memory: 32`) and disabled redis.

```
time="2021-02-09T09:02:10+05:30" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=[redacted]
time="2021-02-09T09:02:17+05:30" level=debug msg="Mark authentication attempt made by user karun" method=POST path=/api/firstfactor remote_ip=[redacted]
time="2021-02-09T09:02:18+05:30" level=debug msg="Credentials validation of user karun is ok" method=POST path=/api/firstfactor remote_ip=[redacted]
```
7 seconds ain't bad. Is there some other check I can make to make this faster?

> Our of curiosity what are the specs on the machine that you are running Authelia on?
It's a [WD PR4100](https://shop.westerndigital.com/products/network-attached-storage/wd-my-cloud-pro-series-pr4100#WDBNFA0000NBK-NESN) running an Intel Pentium N3710 quad-core 1.6GHz processor and 4GB of RAM.

Is there a better configuration I can run this on?

**Comment by nightah** [comment]
I wouldn't recommend disabling Redis, since your sessions won't survive a restart of Authelia.

I'd recommend reading https://www.authelia.com/docs/configuration/authentication/file.html#password-hash-algorithm-tuning and tuning your memory accordingly.

When tuning and testing with some embedded devices (RPi's) we documented the settings [here](https://www.authelia.com/docs/configuration/authentication/file.html#examples-for-specific-systems) with those settings hashing was taking less than 0.5s.

If you find you're still having issues with slow login I'd recommend looking at LDAP, realistically if you're going to be running this at any scale I'd recommend that as the primary option to explore.

**Comment by javatarz** [comment]
I've gotten it down to 10-11 seconds. The issue could still be anything and not just the algorithm. Here's an interesting piece of log that raises a few questions

```
time="2021-02-10T13:18:42+05:30" level=trace msg="attempt successful: true, exec duration: 33623, avg execution duration: 4262, random delay ms: 38, total delay ms: 4300, actual delay ms: 1"
```

In this case, the total time taken was about 33 seconds. "avg execution duration" is 4.2 seconds. Is this the time to calculate the hash? If so, it's longer than the 0.5 we would expect but most of the time is spent outside hashing.

Can someone familiar with the code comment if my suspicion is correct? I'll also try hunting this piece of logger down and look at the stats it's printing.

Will try testing with LDAP as well later today and report back. Either way, I think a PR with more logs to debug this might be coming (though I have little to no go experience, I think I should be able to manage as long as the project has a good "how to get started guide")

**Comment by javatarz** [comment]
Based on the [code around the logger](https://github.com/authelia/authelia/blob/b989c1b169d0ccfe105c8c3efa1c2fb63cd18023/internal/handlers/handler_firstfactor.go#L37), my interpretation is that the duration to execute the request was 33.6 seconds and the average execution time (based on a sliding window of execution times) is 4 seconds.

This means some requests are REALLY slow and most requests are really fast. A debugger here would be awesome but I'll have to setup this code locally to run it. Might be worth it considering the high login time for me right now 😃

**Comment by nightah** [comment]
I'd say this is likely just due to memory pressures on the system with whatever else you may have running.

You should be able to confirm this by changing away from the default argon2id algo for password hashing and using sha512 instead:

`authelia hash-password yourpasswordhere -z`

Then copy that hash into your `users_database.yml` for whichever user you're utilising to test this.

**Comment by ViRb3** [comment]
I had the same issue on a Raspberry Pi 4. Here's my current settings that work instantly:
```yml
    password:
      algorithm: sha512
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8
```
