### ISSUE TITLE
Docker secrets not adding to config - errors Set domain of session object and Notifier should be either 'smtp'. . .

### ISSUE THREAD

**Issue by alxsch** [authelia/authelia#1724]
* authelia    | time="*" level=error msg="Set domain of the session object"
* authelia    | time="*" level=error msg="Notifier should be either `smtp` or `filesystem`"

Attempting to follow the documentation [here](https://www.authelia.com/docs/configuration/secrets.html).

# docker-compose.yml

```
---
version: "2.2"

networks:
  default:
    external:
      name: ${MAIN_NETWORK}

secrets:
  jwt:
    file: ./secrets/jwt_secret
  duo:
    file: ./secrets/duo
  smtp:
    file: ./secrets/smtp
  session:
    file: ./secrets/session

services:

  authelia:
    image: authelia/authelia:4.26.0
    container_name: authelia
    secrets:
      - jwt
      - duo
      - smtp
      - session

    environment:
      - TZ=${MAIN_TZ}
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/duo
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp

    volumes:
      - ./config/authelia:/config
    restart: unless-stopped
```

# configuration.yml

```
host: 0.0.0.0
port: 9091
server:
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: "authelia"
log_level: debug
theme: dark
default_redirection_url: "https://example.com"
authentication_backend:
  disable_reset_password: false
  file:
   path: /config/users_database.yml
   password:
     algorithm: -----
     iterations: ---
     key_length: ---
     salt_length: ---
     memory: ---
     parallelism: ---
access_control:
  default_policy: deny
  rules:
    - domain:
      - "example.com"
      - "*.example.com"
      policy: two_factor
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
```

# ../config/secrets/smtp

```
smtp:
  username: noreply@example.com
  password: ********
  host: example.com
  port: 465
  sender: noreply@example.com
  subject: "[Authelia] {title}"
  startup_check_address: test@authelia.com
  trusted_cert: ""
  disable_require_tls: false
  disable_verify_cert: false
```

**Comment by nightah** [comment]
I believe you've misunderstood the usage of the secrets. Only specific fields are read through via secrets (typically passwords, secrets and/or JWT's). They're summarised [here](https://www.authelia.com/docs/configuration/secrets.html).

Given how you have configured the `smtp:` key into the secret file the errors are pretty clear in stating what the problems are.
I assume the omitted the `session:` key probably is in your session secret file too, your configuration should look something like [this](https://www.authelia.com/docs/configuration/session.html#configuration):
```yaml
session:
  # The name of the session cookie. (default: authelia_session).
  name: authelia_session

  # The secret to encrypt the session data. This is only used with Redis.
  # Secret can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
  secret: unsecure_session_secret

  # The time in seconds before the cookie expires and session is reset.
  expiration: 1h

  # The inactivity time in seconds before the session is reset.
  inactivity: 5m

  # The remember me duration.
  # Value of 0 disables remember me.
  # Value is in seconds, or duration notation. See: https://docs.authelia.com/configuration/index.html#duration-notation-format
  # Longer periods are considered less secure because a stolen cookie will last longer giving attackers more time to spy
  # or attack. Currently the default is 1M or 1 month.
  remember_me_duration:  1M

  # The domain to protect.
  # Note: the login portal must also be a subdomain of that domain.
  domain: example.com

  # The redis connection details (optional)
  # If not provided, sessions will be stored in memory
  redis:
    host: 127.0.0.1
    port: 6379
    # Use a unix socket instead
    # host: /var/run/redis/redis.sock

    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    password: authelia
```

In the above example the `secret:` option within the `session:` key is what you would pass in within the secret file.
The file should just be the value of the actual option.
