### ISSUE TITLE
[Feature Request] honor pwdReset: TRUE on openldap

### ISSUE THREAD

**Issue by davama** [authelia/authelia#1766]
Basically if attribute is present, then force user to reset their password.

with sssd when attribute is present, the user is given a msg that they must change their password and force to type old pass then new pass.

Of course willing to test.

thanks!

**Comment by james-d-elliott** [comment]
This would probably take a fair bit of thought. There are many LDAP implementations and they each have differing methods to signify this. We also have to ensure it's reset after. It would probably require 3 additional configuration options:

```yaml
authentication_backend:
  ldap:
    password_reset_attribute: pwdReset
    password_reset_required_value: "TRUE"
    password_reset_value: "FALSE"
```

Ideally a feature like this should also exist as an alternative to the current email based password reset.

**Comment by james-d-elliott** [comment]
This can be half done via a filter:

`(!(pwdReset=TRUE))`

We will have to think about the added functionality of forcing a reset, specifically.

**Comment by davama** [comment]
Thank you!

Ill give it a try and post the results

**Comment by nightah** [comment]
@davama how'd you go with testing this, with the updated filter did it prevent you from being able to login with that user?

Just want to understand current behaviour so we know how to plan the second portion of this request.

**Comment by davama** [comment]
@nightah 

It works but will have an issue when it comes to email.
The user with the `pwdReset=True` is ignored, therefore he cannot authenticate to authelia. Once I reset try to reset my password, the user is not found therefore, no email is sent.

Im trying to figure out how to better write the filter:

```
users_filter: (&({username_attribute}={input})(objectClass=person)(!(pwdReset=TRUE)))
```

**Comment by james-d-elliott** [comment]
We may have to have a set of filters for this purpose where the `users_filter` is remapped as a default. I think it's the most flexible overall.

**Comment by davama** [comment]
That’ll be interesting to see
Let me know so i can test
Thank you for the support!

**Comment by james-d-elliott** [comment]
@davama see the linked PR, it's based on some other rather large changes to LDAP. Docs: https://645cd13fb6279b000851c935--authelia-staging.netlify.app/configuration/first-factor/ldap/

Specifically: https://645cd13fb6279b000851c935--authelia-staging.netlify.app/configuration/first-factor/ldap/#users_reset_filter

**Comment by davama** [comment]
Thank you very much @james-d-elliott !

I see there are a few changes to the ldap configuration settings.

i would like to give this a test.
how could I go about in downloading a PR based docker image?

Thanks!

**Comment by james-d-elliott** [comment]
Tag is the branch name, so `authelia/authelia:feat-ldap-reset-filter`.

**Comment by davama** [comment]
Hello @james-d-elliott 

hope you are doing well.

I have no issue authenticating with my credentials and getting an email to reset my password. It is only after i clicked the reset password link and input my new password that i get the error below. I have yet to try an account with the `pwdReset` attribute. Simply wanted to make sure all previous functionality is good before i move on testing this feature.

perhaps it's a config issue?

```
{
  "level": "error",
  "method": "POST",
  "msg": "unable to update password. Cause: cannot find user DN of user 'myusername'. Cause: LDAP Result Code 4 \"Size Limit Exceeded\": ",
  "path": "/api/reset-password",
  "remote_ip": "10.x.x.x",
  "stack": [
    {
      "File": "github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go",
      "Line": 67,
      "Name": "(*AutheliaCtx).Error"
    },
    {
      "File": "github.com/authelia/authelia/v4/internal/handlers/handler_reset_password_step2.go",
      "Line": 52,
      "Name": "ResetPasswordPOST"
    },
    {
      "File": "github.com/authelia/authelia/v4/internal/middlewares/bridge.go",
      "Line": 54,
      "Name": "(*BridgeBuilder).Build.func1.1"
    },
    {
      "File": "github.com/authelia/authelia/v4/internal/middlewares/headers.go",
      "Line": 25,
      "Name": "SecurityHeadersCSPNone.func1"
    },
    {
      "File": "github.com/authelia/authelia/v4/internal/middlewares/headers.go",
      "Line": 51,
      "Name": "SecurityHeadersNoStore.func1"
    },
    {
      "File": "github.com/authelia/authelia/v4/internal/middlewares/headers.go",
      "Line": 16,
      "Name": "SecurityHeaders.func1"
    },
    {
      "File": "github.com/fasthttp/router@v1.4.19/router.go",
      "Line": 420,
      "Name": "(*Router).Handler"
    },
    {
      "File": "github.com/valyala/fasthttp@v1.47.0/http.go",
      "Line": 158,
      "Name": "(*Response).StatusCode"
    },
    {
      "File": "github.com/authelia/authelia/v4/internal/middlewares/metrics.go",
      "Line": 22,
      "Name": "NewMetricsRequest.func1.1"
    },
    {
      "File": "github.com/valyala/fasthttp@v1.47.0/server.go",
      "Line": 2365,
      "Name": "(*Server).serveConn"
    },
    {
      "File": "github.com/valyala/fasthttp@v1.47.0/workerpool.go",
      "Line": 224,
      "Name": "(*workerPool).workerFunc"
    },
    {
      "File": "github.com/valyala/fasthttp@v1.47.0/workerpool.go",
      "Line": 196,
      "Name": "(*workerPool).getCh.func1"
    },
    {
      "File": "runtime/asm_amd64.s",
      "Line": 1598,
      "Name": "goexit"
    }
  ],
  "time": "2023-05-17T19:34:13Z"
}
```

below is my update ldap config:

```
authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  ldap:
    implementation: custom
    address: 'ldap://dcom-dave-vm.domain.com'
    timeout: '5s'
    start_tls: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: 'dc=domain,dc=com'
    additional_users_dn: 'ou=people'
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    users_reset_filter: '(!(pwdReset=TRUE))'
    additional_groups_dn: 'ou=group'
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    group_search_mode: 'filter'
    mail_attribute: mail
    display_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: cn=pwmanager,dc=domain,dc=com
    #password: is via ENV var
    attributes:
      distinguished_name: 'dn'
      username: 'uid'
      display_name: 'cn'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'
```

I can post my openldap logs too, but want to make sure that my config is sane before i do so.

Best,
Dave

**Comment by james-d-elliott** [comment]
Try this:

```yaml
authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  ldap:
    implementation: custom
    address: 'ldap://dcom-dave-vm.domain.com'
    timeout: '5s'
    start_tls: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: 'dc=domain,dc=com'
    additional_users_dn: 'ou=people'
    users_filter: '(&({username_attribute}={input})(objectClass=person)(!(pwdReset=TRUE)))'
    users_reset_filter: '(&({username_attribute}={input})(objectClass=person))'
    additional_groups_dn: 'ou=group'
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    group_search_mode: 'filter'
    mail_attribute: mail
    display_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: cn=pwmanager,dc=domain,dc=com
    #password: is via ENV var
    attributes:
      distinguished_name: 'dn'
      username: 'uid'
      display_name: 'cn'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'
```
