### ISSUE TITLE
Allow host and port variables in configuration file to be strings

### ISSUE THREAD

**Issue by rus64** [authelia/authelia#1812]
When using Ansible to deploy Authelia, one might have a template file using Jinja2 to pass in variables. Jinja2 always returns string types:

```yaml
# configuration.yml.j2
host: "{{ authelia_host }}"
port: "{{ authelia_port }}"
```
becomes

```yaml
# configuration.yml
host: "0.0.0.0"
port: "9091"
```

This appears to break the Authelia configuration, however in other places strings are accepted, e.g. for the redis port:

```yaml
session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 5m
  domain: public.example.com

  redis:
      host: redis
      port: "6379"
```

Is it possible to accept string types for all values in the configuration file to be conducive for templating?
