### ISSUE TITLE
Error during notifier startup check

### ISSUE THREAD

**Issue by MacGyver27** [authelia/authelia#1828]
Hi,

Out of the sudden authelia won't start:
```
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=info msg="Logging severity set to debug"
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=debug msg="Storage schema is being checked to verify it is up to date"
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=debug msg="Storage schema is up to date"
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=debug msg="Notifier SMTP client attempting connection to mail.example.com:587"
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=debug msg="Notifier SMTP client connected successfully"
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: mail.example.com), attempting"
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=warning msg="Notifier SMTP client encountered error during cleanup: x509: certificate has expired or is not yet valid: current time 2021-03-14T19:05:07+01:00 is after 2021-03-08T21:19:04Z"
traefik2.authelia | time="2021-03-14T19:05:07+01:00" level=fatal msg="Error during notifier startup check: x509: certificate has expired or is not yet valid: current time 2021-03-14T19:05:07+01:00 is after 2021-03-08T21:19:04Z" stack="github.com/authelia/authelia/cmd/authelia/main.go:112 startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137 main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856          (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960          (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897          main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154 main\nruntime/proc.go:225 
```

docker-compose:
```yml
  authelia:
    container_name: traefik2.authelia
    image: authelia/authelia:latest
    restart: always
    network_mode: host
    depends_on:
      - mariadb
      - redis
    volumes:
      - $PWD/authelia:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      # TRAEFIK 2
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.rule=Host(`authelia.example.com`)
      - traefik.http.routers.authelia.service=authelia
      - traefik.http.routers.authelia.middlewares=authelia.auth@file
      - traefik.http.services.authelia.loadbalancer.server.port=9091
```
configuration:
```yml
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# I used this site to generate the secret: https://www.grc.com/passwords.htm
# use docker secret file instead AUTHELIA_JWT_SECRET_FILE
jwt_secret: ****************************

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.example.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
duo_api:
  hostname: ****************************.duosecurity.com
  integration_key: ****************************
  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
  # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE
  secret_key: ****************************

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.example.com
      policy: bypass
    - domain: admin.example.com
      policy: two_factor
      subject: 
      - ["****************************"]
    - domain: "*.example.com"
      policy: one_factor
      subject: 
      - ["****************************"]
    - domain: docker.edoras.example.com
      subject: 
      - ["****************************"]
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Used a different secret, but the same site as jwt_secret above.
  # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  secret: ****************************
  expiration: 1M # 1 hour
  inactivity: 3d # 5 minutes
  remember_me_duration: 3M
  domain: example.com # Should match whatever your root protected domain is

# Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
  redis:
    host: redis
    port: 63791
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
# For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
#  local:
#    path: /config/db.sqlite3
  mysql:
  # MySQL allows running multiple authelia instances. Create database and enter details below.
    host: mariadb
    port: 33061
    database: authelia
    username: authelia
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    # use docker secret file instead AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE
    password: ****************************

notifier:
  smtp:
    username: authelia@example.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: ****************************
    host: mail.example.com
    port: 587
    sender: authelia@example.com
    disable_require_tls: true
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
#  filesystem:
#    filename: /tmp/authelia/notification.txt
```

I have no issues connection to my email. This is from the email tester:
![image](https://user-images.githubusercontent.com/6546231/111080059-f3181980-84fc-11eb-9654-04a3a550cda9.png)

However thunderbird isn't completely happy:
![image](https://user-images.githubusercontent.com/6546231/111080145-6883ea00-84fd-11eb-852f-3e1e947d03fa.png)

Any ideas please? Appreciate.
