### ISSUE TITLE
Unable to set up postgres storage backend

### ISSUE THREAD

**Issue by Hitman247m** [authelia/authelia#1857]
### Description

I've been trying for the last few days to set up the postgres storage backend for authelia with no success. Everything is set up with docker compose, and I'm using the same postgres setup for other services with no issues. Here's the database:

```yaml
  authelia-test-db:
    container_name: authelia-test-db
    image: postgres:13.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authelia"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_DB=authelia
      - POSTGRES_USER=authelia
      - POSTGRES_PASSWORD=PASSWORD
    volumes:
      - '/services/authelia-test/db:/var/lib/postgresql/data'
```

The database itself initializes correctly, and I'm able to run commands from a test container I created, with the same credentials. However, when I try to start authelia (with the following settings):

```yaml
storage:
  postgres:
    host: authelia-test-db
    port: 5432
    database: authelia
    username: authelia
    password: PASSWORD
    sslmode: disable
```
 
I see the following log lines in the database:

```
2021-03-26 12:29:09.056 UTC [1] LOG:  starting PostgreSQL 13.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
2021-03-26 12:29:09.056 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-03-26 12:29:09.056 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-03-26 12:29:09.058 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-03-26 12:29:09.060 UTC [49] LOG:  database system was shut down at 2021-03-26 12:29:08 UTC
2021-03-26 12:29:09.063 UTC [1] LOG:  database system is ready to accept connections
2021-03-26 12:29:18.468 UTC [62] FATAL:  could not open file "global/pg_filenode.map": Permission denied
2021-03-26 12:29:19.765 UTC [63] FATAL:  could not open file "global/pg_filenode.map": Permission denied
2021-03-26 12:29:21.052 UTC [64] FATAL:  could not open file "global/pg_filenode.map": Permission denied
2021-03-26 12:29:22.523 UTC [65] FATAL:  could not open file "global/pg_filenode.map": Permission denied
2021-03-26 12:29:24.088 UTC [52] PANIC:  could not open file "pg_wal/000000010000000000000001": Permission denied
2021-03-26 12:29:24.404 UTC [66] FATAL:  could not open file "global/pg_filenode.map": Permission denied
2021-03-26 12:29:24.861 UTC [1] LOG:  WAL writer process (PID 52) was terminated by signal 6: Aborted
2021-03-26 12:29:24.861 UTC [1] LOG:  terminating any other active server processes
2021-03-26 12:29:24.861 UTC [53] WARNING:  terminating connection because of crash of another server process
2021-03-26 12:29:24.861 UTC [53] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-03-26 12:29:24.861 UTC [53] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-03-26 12:29:24.861 UTC [54] LOG:  could not open temporary statistics file "pg_stat/global.tmp": Permission denied
2021-03-26 12:29:24.862 UTC [1] LOG:  all server processes terminated; reinitializing
2021-03-26 12:29:24.886 UTC [1] PANIC:  could not open file "global/pg_control": Permission denied
```

Here's the corresponding lines from the authelia container:

```
chown: /config/configuration.yml: Read-only file system
time="2021-03-26T08:38:18-04:00" level=info msg="Logging severity set to info"
time="2021-03-26T08:38:18-04:00" level=fatal msg="Unable to initialize SQL database: failed to connect to `host=authelia-test-db user=authelia database=authelia`: server error (FATAL: could not open file \"global/pg_filenode.map\": Permission denied (SQLSTATE 42501))" stack="github.com/authelia/authelia/internal/storage/postgres_provider.go:84 NewPostgreSQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:78                  startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137                 main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856                          (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960                          (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897                          main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154                 main\nruntime/proc.go:225                                                   main\nruntime/asm_amd64.s:1371                                              goexit"
chown: /config/configuration.yml: Read-only file system
time="2021-03-26T08:38:19-04:00" level=info msg="Logging severity set to info"
time="2021-03-26T08:38:19-04:00" level=fatal msg="Unable to initialize SQL database: failed to connect to `host=authelia-test-db user=authelia database=authelia`: server error (FATAL: could not open file \"global/pg_filenode.map\": Permission denied (SQLSTATE 42501))" stack="github.com/authelia/authelia/internal/storage/postgres_provider.go:84 NewPostgreSQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:78                  startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137                 main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856                          (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960                          (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897                          main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154                 main\nruntime/proc.go:225                                                   main\nruntime/asm_amd64.s:1371                                              goexit"
chown: /config/configuration.yml: Read-only file system
time="2021-03-26T08:38:20-04:00" level=info msg="Logging severity set to info"
time="2021-03-26T08:38:20-04:00" level=fatal msg="Unable to initialize SQL database: failed to connect to `host=authelia-test-db user=authelia database=authelia`: server error (FATAL: could not open file \"global/pg_filenode.map\": Permission denied (SQLSTATE 42501))" stack="github.com/authelia/authelia/internal/storage/postgres_provider.go:84 NewPostgreSQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:78                  startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137                 main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856                          (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960                          (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897                          main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154                 main\nruntime/proc.go:225                                                   main\nruntime/asm_amd64.s:1371                                              goexit"
```

As a test, I brought up the database by itself, and did a `chmod -R 0777` for the postgres data, then brought up the authelia container, but the results were the same.

### Expected Behaviour

I expect the authelia container to start and connect to the database successfully.

### Reproduction Steps

_N/A_

### Additional Information

Image Versions:
- postgres:13.2-alpine and postgres:11.8-alpine
- authelia/authelia:4.27.2

Environment:
- OS: CentOS 8
- Docker: 20.10.5
- Docker Compose: 1.25.4

**Comment by james-d-elliott** [comment]
This seems to be a issue related to the pg container. Can you try downing the compose and deleting `/services/authelia-test/db` and trying again?

**Comment by Hitman247m** [comment]
@james-d-elliott I tried that a few times, with different variations. The pg container starts correctly, the problem only starts when I bring up the authelia container. I've also tried creating the `/services/authelia-test/db` folder manually, then bringing the container up. The issue persists. I'm using the same postgres config for a bunch of other services, and it works perfectly.

**Comment by james-d-elliott** [comment]
Seems very strange, We actually do integration testing against that container. I will attempt to replicate it.

**Comment by james-d-elliott** [comment]
Seems completely functional to me with those containers. Is the volume mounted to /services special in any way? I tried both of the postgres containers you specified and they both work. They result in the database chowning files correctly and authelia crashing once because postgres wasn't ready. Then Authelia initializes the database successfully. 

```yaml
version: "3"
services:
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authelia"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
    - POSTGRES_DB=authelia
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=authelia
    volumes:
    - ./data/db:/var/lib/postgresql/data
  authelia:
    image: authelia/authelia:4.27.2
    container_name: authelia
    restart: unless-stopped
    volumes:
    - ./data/authelia:/config
```

**Comment by Hitman247m** [comment]
That's really odd.. To answer your question, nope, `/services` is just linked to /raid1, but nothing terribly fancy:

```bash
$ ls -la / | grep services
lrwxrwxrwx.   1 root    6 Mar 22  2020 services -> /raid1/
```

The only different I noticed from your compose file, I'm using version 2.4, but I don't think that would make any difference.
```yaml
version: '2.4'

services:

  authelia-test:
...
```
