### ISSUE TITLE
Authentication without domain

### ISSUE THREAD

**Issue by deeztek** [authelia/authelia#1865]
Is it possible to authenticate through Authelia without the use of a domain? In other words, let's say I have a resource on /account and I want Authelia to authenticate them. Is that possible or am I missing something in the documentation. I see paths but they are always seem to be used with domains. 

This is for a standalone Linux install. 

Thanks

**Comment by james-d-elliott** [comment]
The resources rule in ACL's allows you to select the exact path/query.

**Comment by james-d-elliott** [comment]
@deeztek  one note, you have to have authelia share a root domain with the protected domain. So if you use resources, you still need domain, but you could have a rule like below where the path on *.example.com/account is bypassed, and *.example.com/secure requires one_factor auth.

```yaml
session:
  domain: example.com
access_control:
  default_policy: deny
  rules:
  - domain: "*.example.com"
    resources:
    - "^/account$"
    policy: bypass
  - domain: "*.example.com"
    resources:
    - "^/secure$"
    policy: one_factor
```
