### ISSUE TITLE
[Bug] ActiveDirectory LDAP - LDAP Result Code 32 "No Such Object"

### ISSUE THREAD

**Issue by datdamnzotz** [authelia/authelia#1900]
## Bug Report

Docker image: authelia/authelia:latest - 4.27.4
Docker version 20.10.5, build 55c4c88
Ubuntu 18.04 LTS
LDAP is Windows Server 2019 - Active Directory Schema Version is 88

```  
  ldap:
    implementation: activedirectory
    # The url to the ldap server. Scheme can be ldap or ldaps in the format (port optional) <scheme>://<address>[:<port>].
    url: ldap://<domain>.com

    # Use StartTLS with the LDAP connection.
    start_tls: true

    tls:
      skip_verify: true
      minimum_version: TLS1.2

    # The base dn for every entries.
    base_dn: DC=<domain>,DC=com
    username_attribute: sAMAccountName
    additional_users_dn: OU=Users OU
    additional_groups_dn: ou=groups
    groups_filter: (&(objectCategory=group)(member={dn}))
    group_name_attribute: cn
    mail_attribute: mail
    users_filter: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
    # display_name_attribute: displayname

    # The username and password of the admin user.
    user: CN=<user>,DC=<domain>,DC=com
    password: pass

```

### Description

```	
=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2021-04-09T19:30:59-06:00" level=trace msg="Computed user filter is (&(sAMAccountName=<user>)(objectCategory=person)(objectClass=user))"
time="2021-04-09T19:30:59-06:00" level=debug msg="Mark authentication attempt made by user <user>" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2021-04-09T19:30:59-06:00" level=debug msg="Credentials validation of user <user> is ok" method=POST path=/api/firstfactor remote_ip=10.0.0.2
time="2021-04-09T19:30:59-06:00" level=trace msg="Computed user filter is (&(sAMAccountName=<user>)(objectCategory=person)(objectClass=user))"
time="2021-04-09T19:30:59-06:00" level=trace msg="Computed groups filter is (&(member=CN=<user>,OU=Users OU,DC=<domain>)(objectclass=group))"
time="2021-04-09T19:30:59-06:00" level=error msg="Error while retrieving details from user <user>: Unable to retrieve groups of user <user>. 
Cause: LDAP Result Code 32 \"No Such Object\": 0000208D: NameErr: DSID-03100288, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=<domain>'\n\x00" 
method=POST path=/api/firstfactor remote_ip=10.0.0.2 
stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64
  (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:112
  handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:161
  FirstFactorPost.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49
  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.10/router.go:414
  (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14
  LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.23.0/server.go:2207
  (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:223
  (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:195
  (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371
  goexit"
```  

Running a ldap query against the Computed groups filter  returns names via powershell:
```powershell
Get-ADGroup -LDAPFilter "(&(objectCategory=group)(member=CN=<user>,DC=<domain>))"
```
![image](https://user-images.githubusercontent.com/3913859/114254363-2454ff80-996c-11eb-85ce-f736bc090bd9.png)
