### ISSUE TITLE
Unraid - docked won’t start after update

### ISSUE THREAD

**Issue by lsultana98** [authelia/authelia#1927]
After updating the container this morning. Authelia will not start up, please see screenshot for errors. Thanks in advanced. ![image](https://user-images.githubusercontent.com/45834283/115109041-edf43180-9fb6-11eb-8932-2ab9d20c7950.jpeg)

**Comment by james-d-elliott** [comment]
You will just need to update your configuration for the new version.

```yaml
notifier:
  smtp:
    trusted_cert: /path/to/certificates/smtp.pem
    disable_verify_cert: false
```

becomes:

```yaml
certificates_directory: /path/to/certificates
notifier:
  smtp:
    tls:
      skip_verify: false
```

**Comment by lsultana98** [comment]
I am still a little confused. This is what I currently have, what exactly am I changing?
`notifier:
  # You can disable the notifier startup check by setting this to true.
  disable_startup_check: true

  # For testing purpose, notifications can be sent in a file
  ## filesystem:
  ##   filename: /config/notification.txt

  # Use a SMTP server for sending notifications. Authelia uses PLAIN or LOGIN method to authenticate.
  # [Security] By default Authelia will:
  #   - force all SMTP connections over TLS including unauthenticated connections
  #      - use the disable_require_tls boolean value to disable this requirement (only works for unauthenticated connections)
  #   - validate the SMTP server x509 certificate during the TLS handshake against the hosts trusted certificates
  #     - trusted_cert option:
  #       - this is a string value, that may specify the path of a PEM format cert, it is completely optional
  #       - if it is not set, a blank string, or an invalid path; will still trust the host machine/containers cert store
  #     - defaults to the host machine (or docker container's) trusted certificate chain for validation
  #     - use the trusted_cert string value to specify the path of a PEM format public cert to trust in addition to the hosts trusted certificates
  #     - use the disable_verify_cert boolean value to disable the validation (prefer the trusted_cert option as it's more secure)
  smtp:
    username: example@gmail.com
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    password: YOURPASSWORD
    host: smtp.gmail.com
    port: 465
    sender: support@YOURDOMAIN.COM
    # Subject configuration of the emails sent.
    # {title} is replaced by the text from the notifier
    subject: "[Authelia] {title}"
    # This address is used during the startup check to verify the email configuration is correct. It's not important what it is except if your email server only allows local delivery.
    startup_check_address: test@authelia.com
    trusted_cert: ""
    disable_require_tls: false
    disable_verify_cert: false`

Sorry if this is a little confusing.

**Comment by lsultana98** [comment]
Sorry mate I am still a little confused. This is what I currently have (I'm not even really using the smtp function.


[help.txt](https://github.com/authelia/authelia/files/6329165/help.txt)

**Comment by james-d-elliott** [comment]
Easy fix, remove the following lines:

```yaml
    trusted_cert: ""
    disable_verify_cert: false
```

**Comment by lsultana98** [comment]
I am now getting:
![Screenshot_1](https://user-images.githubusercontent.com/45834283/115113126-fd31aa00-9fcb-11eb-97f0-ccd0394e6c3c.png)

I was able to get Authelia working without providing these previously?

**Comment by james-d-elliott** [comment]
The configuration you sent me has those configured from what I can see. Should look like this after the suggested edits:

```yaml
notifier:
  # You can disable the notifier startup check by setting this to true.
  disable_startup_check: true

  # For testing purpose, notifications can be sent in a file
  ## filesystem:
  ##   filename: /config/notification.txt

  # Use a SMTP server for sending notifications. Authelia uses PLAIN or LOGIN method to authenticate.
  # [Security] By default Authelia will:
  #   - force all SMTP connections over TLS including unauthenticated connections
  #      - use the disable_require_tls boolean value to disable this requirement (only works for unauthenticated connections)
  #   - validate the SMTP server x509 certificate during the TLS handshake against the hosts trusted certificates
  #     - trusted_cert option:
  #       - this is a string value, that may specify the path of a PEM format cert, it is completely optional
  #       - if it is not set, a blank string, or an invalid path; will still trust the host machine/containers cert store
  #     - defaults to the host machine (or docker container's) trusted certificate chain for validation
  #     - use the trusted_cert string value to specify the path of a PEM format public cert to trust in addition to the hosts trusted certificates
  #     - use the disable_verify_cert boolean value to disable the validation (prefer the trusted_cert option as it's more secure)
  smtp:
    username: example@gmail.com
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    password: YOURPASSWORD
    host: smtp.gmail.com
    port: 465
    sender: support@YOURDOMAIN.COM
    # Subject configuration of the emails sent.
    # {title} is replaced by the text from the notifier
    subject: "[Authelia] {title}"
    # This address is used during the startup check to verify the email configuration is correct. It's not important what it is except if your email server only allows local delivery.
    startup_check_address: test@authelia.com
    disable_require_tls: false
```
