### ISSUE TITLE
Document HTTP forward auth headers

### ISSUE THREAD

**Issue by tomlawesome** [authelia/authelia#1936]
### Description

It would be great if some documentation on Authelia & forward auth HTTP headers could be written. As a relative beginner it is extremely confusing to understand how to correctly implement it. 

### Use Case

I am using traefik + authelia. I would like to be able to login/auth via Authelia with 2FA and then forward that to a service with a REMOTE_USER header. 

I understand this might well already be possible, but a lack of documentation/examples means I don't understand how authelia handles it and how I would make it so that Authelia/traefik sends the header to my application after login. 

Example:

Browser to https://service.example.com ---> traefik chain-authelia middlewares ---> login to authelia with 2FA ---> succesful login, authelia/traefik sends REMOTE_USER header to service ---> Service logs in automatically.

**Comment by clems4ever** [comment]
Hello @tomlawesome , have you seen this one already? https://www.authelia.com/docs/deployment/supported-proxies/#how-can-the-backend-be-aware-of-the-authenticated-users.

I think we already have examples for each of the supported proxies but if that's not sufficient can you point out exactly what is missing and where we should insert it within the current documentation? You can even do a proposal through a PR if you'd like, I'd be glad to review it.

**Comment by tomlawesome** [comment]
Hello @clems4ever. I have seen it but I am not really sure if I implemented it correctly? I have actually used files:

middlewares.yml
```
    middlewares-authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.example.com"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
```
chains.yml
```
http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - cfp@file
          - middlewares-authelia@file
```
I then specify the following label on my service in docker-compose.yml if I want to protect it with authelia:
```
- 'traefik.http.routers.router-name.middlewares=chain-authelia@file'
```
This works well to force authelia login before forwarding to the service.

But I have configured two of my service now to accept login via REMOTE_USER header. As I understand... Authelia should be sending the header already? I specified it in my middleware? But neither service seems to be able to login via this way. I have tried to check if the header is there and I can't see it. 

Is there a way I can check authelia is sending the header properly? I don't think it's sending it. Or maybe my config is wrong?
I'm not sure! thanks for your help.
