### ISSUE TITLE
add git hosted repositories and wordpress admin as example for resources access control 

### ISSUE THREAD

**Issue by dginhoux** [authelia/authelia#1940]
I use authelia since a long time and i love it.

I use it to secure few projects and here, i allow git related command without any auth (by authelia, gitea does by token) while human access for the web git ui are still authenticad by authelia.
The other example is more easier to secure a wordpress admin panel and allow the entire blog opened and freely published.

Here my resources example that work since few months now : 
```
access_control:
  default_policy: deny
  rules:
    # git bypass for git command 
    - domain: "git.XXX.net"
      resources: 
      - "^.*\\.git/(HEAD|info/refs|objects/info/.*|git-(upload|receive)-pack).*$"
      policy: bypass

    # blog security for admin panel
    - domain: "blog.XXX.net"
      resources: 
      - "^/wp-admin.*$"
      - "^/wp-config.php.*$"
      policy: two_factor

    # blog open to everyone
    - domain: "blog.XXX.net"
      policy: bypass

    # default two auth
    - domain: "*.XXX.net"
      policy: two_factor

```

I think this can be usefull for everybody ; so use it if you want.
