### ISSUE TITLE
Authelia can't connect to db. Getting error "Unable to initialize SQL database: Error 1045: Access denied for user 'authelia'..." 

### ISSUE THREAD

**Issue by smokemyshoes** [authelia/authelia#1956]
## Bug Report

Hi

I could reeally need your help. I can't get Authelia to connect to my MariaDB container and I feel like I have tried everything.

### Description

I'm getting the error `Unable to initialize SQL database: Error 1045: Access denied for user 'authelia'...` when my authelia container tries to connect to my linuxserver/mariadb container.

### Expected Behaviour

I was expecting that the authelia would connect to the mariadb container and that the authelia container would start.

### Reproduction Steps

I have reviewed my docker-compose file like 10 times and nuked containers, images and volumes more times than I can count.

I have checked the following:
 - With adminer I have checked that I can log into the db both as root and as the authelia-user
 - That the containers are infact both connected to the "auth_backend_net" and that the db can be ping'ed
 - That all secrets are passed along to the db container. Obviously I can't check this for the authelia container as it won't start
 - Host-mounted volumes and their content are owned by the users assigned to the containers
 - The authelia database is created but is obviously empty as in it has no tables

### Additional Information

Here is an excerpt of my compose-file:
```
version: "3.9"

##################################### NETWORKS
networks:
  proxy_net:
    external:
      name: proxy_net
  proxy_backend_net:
    external:
      name: proxy_backend_net
  auth_backend_net:
    external:
      name: auth_backend_net
....

....

##################################### SECRETS
secrets:
  authelia_db_user:
    file: /docker-apps/docker/appdata/authelia-db/secrets/authelia_db_user
  authelia_db_password--app:
    file: /docker-apps/docker/appdata/authelia/secrets/authelia_db_password
  authelia_db_password--db:
    file: /docker-apps/docker/appdata/authelia-db/secrets/authelia_db_password
  authelia_db_root_password:
    file: /docker-apps/docker/appdata/authelia-db/secrets/authelia_db_root_password
  authelia_jwt_secret:
    file: /docker-apps/docker/appdata/authelia/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: /docker-apps/docker/appdata/authelia/secrets/authelia_session_secret
  authelia_smtp_password:
    file: /docker-apps/docker/appdata/authelia/secrets/authelia_smtp_password
  authelia_redis_password--app:
    file: /docker-apps/docker/appdata/authelia/secrets/authelia_redis_password
  authelia_redis_password--redis:
    file: /docker-apps/docker/appdata/authelia-redis/secrets/authelia_redis_password
....

....

##################################### SERVICES
services:
....

....

  # Authelia - Application
  authelia-app:
    image: authelia/authelia:latest
    restart: always
    container_name: authelia-app
    depends_on:
      - authelia-db
      - authelia-redis
    environment:
      - TZ=Europe/ZZZZ
      - PUID=XXXX
      - PGID=XXXX
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_smtp_password
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_db_password--app
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/authelia_redis_password--app
    volumes:
      - /docker-apps/docker/appdata/authelia:/config
      - /docker-apps/docker/appdata/authelia/configuration.yml:/config/configuration.yml
    networks:
      - proxy_net
      - auth_backend_net
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_smtp_password
      - authelia_db_password--app
      - authelia_redis_password--app
  
  # Authelia - Database (MariaDB)
  authelia-db:
    image: linuxserver/mariadb:latest
    restart: always
    container_name: authelia-db
    environment:
      - PGID=YYYY
      - PUID=YYYY
      - TZ=Europe/ZZZZ  
      - MYSQL_DATABASE=authelia
      - FILE__MYSQL_USER=/run/secrets/authelia_db_user
      - FILE__MYSQL_PASSWORD=/run/secrets/authelia_db_password--db
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/authelia_db_root_password
    volumes:
      - /docker-apps/docker/appdata/authelia-db:/config
    networks:
      - auth_backend_net
    secrets:
      - authelia_db_user
      - authelia_db_password--db
      - authelia_db_root_password

....
```
Here is my authelia config-file:
```
# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################
host: 0.0.0.0
port: 9091

theme: dark

server:
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: ""

log_level: debug

default_redirection_url: https://mydomain.net

totp:
  issuer: mydomain.net
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 64
      salt_length: 16
      memory: 4096
      parallelism: 32

access_control:
  default_policy: deny
  rules:
    - domain:
      - "*.mydomain.net"
      - mydomain.net
      policy: two_factor

session:
  name: authelia_session
  expiration: 2h
  inactivity: 10m
  remember_me_duration: 1M
  domain: mydomain.net

  redis:
    host: authelia-redis
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 2

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 30m

storage:
  mysql:
    host: authelia-db
    port: 3306
    database: authelia
    username: authelia

notifier:
  disable_startup_check: false
  smtp:
    username: mydomain@gmail.com
    sender: support@mydomain.net
    host: smtp.gmail.com
    port: 587
...
```
Here is the Authelia container log:
```
time="2021-04-28T13:04:29+02:00" level=fatal msg="Unable to initialize SQL database: Error 1045: Access denied for user 'authelia'@'authelia-app.auth_backend_net' (using password: YES)" stack="github.com/authelia/authelia/internal/storage/mysql_provider.go:77 NewMySQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:80               startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137              main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856                       (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960                       (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897                       main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154              main\nruntime/proc.go:225                                                main\nruntime/asm_amd64.s:1371                                           goexit"


time="2021-04-28T13:05:30+02:00" level=info msg="Logging severity set to debug"


time="2021-04-28T13:05:30+02:00" level=debug msg="Storage schema is being checked to verify it is up to date"


time="2021-04-28T13:05:30+02:00" level=fatal msg="Unable to initialize SQL database: Error 1045: Access denied for user 'authelia'@'authelia-app.auth_backend_net' (using password: YES)" stack="github.com/authelia/authelia/internal/storage/mysql_provider.go:77 NewMySQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:80               startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137              main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856                       (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960                       (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897                       main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154              main\nruntime/proc.go:225                                                main\nruntime/asm_amd64.s:1371                                           goexit"
```
And here is the MariaDB log (I had hoped for a statement like "ready for connections..." but this is the only linuxser/mariadb container I have running so I don't know if this is how the log is supposed to look when the container is fully deployed):
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.


[s6-init] ensuring user provided files have correct perms...exited 0.


[fix-attrs.d] applying ownership & permissions fixes...


[fix-attrs.d] done.


[cont-init.d] executing container initialization scripts...


[cont-init.d] 01-envfile: executing... 


[env-init] MYSQL_PASSWORD set from FILE__MYSQL_PASSWORD


[env-init] MYSQL_ROOT_PASSWORD set from FILE__MYSQL_ROOT_PASSWORD


[env-init] MYSQL_USER set from FILE__MYSQL_USER


[cont-init.d] 01-envfile: exited 0.


[cont-init.d] 10-adduser: executing... 



-------------------------------------


          _         ()


         | |  ___   _    __


         | | / __| | |  /  \ 


         | | \__ \ | | | () |


         |_| |___/ |_|  \__/




Brought to you by linuxserver.io


-------------------------------------



To support LSIO projects visit:


https://www.linuxserver.io/donate/


-------------------------------------


GID/UID


-------------------------------------



User uid:    YYYY


User gid:    YYYY


-------------------------------------



[cont-init.d] 10-adduser: exited 0.


[cont-init.d] 30-config: executing... 


[cont-init.d] 30-config: exited 0.


[cont-init.d] 40-initialise-db: executing... 


[cont-init.d] 40-initialise-db: exited 0.


[cont-init.d] 90-warning: executing... 



******************************************************


******************************************************


*                                                    *


*                                                    *


*          This image will soon be rebased           *


*               from ubuntu to alpine.               *


*       Please be aware, this may cause issues       *


*     It is strongly recommended to make backups     *


*         of your config and databases before        *


*       updating your image to the alpine base.      *


*                                                    *


*                                                    *


******************************************************


******************************************************


[cont-init.d] 90-warning: exited 0.


[cont-init.d] 99-custom-scripts: executing... 


[custom-init] no custom files found exiting...


[cont-init.d] 99-custom-scripts: exited 0.


[cont-init.d] done.


[services.d] starting services


[services.d] done.


210428 12:24:03 mysqld_safe Logging to syslog.


210428 12:24:03 mysqld_safe Starting mysqld daemon with databases from /config/databases
```
