### ISSUE TITLE
Traefik middleware doesn't work

### ISSUE THREAD

**Issue by davidphayanouvong** [authelia/authelia#1963]
Hello,

I use authelia with traefik both are in latest version.

I used Authelia on docker without any problem, now i try to migrate my infrastructure to kubernetes and i have some trouble.

i can access to authelia GUI, use my credential, everything fine.

Now i try to deploy the forwardauth Middleware and it doesn't work, i have an error HTTP ERROR 500

Traefik is on another namespace (traefik) and authelia in "dev" namespace

this is my configuration:
```
# service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authelia
    argocd.argoproj.io/instance: dev
  name: authelia
  namespace: dev
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
  selector:
    app: authelia
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: dev
  name: authelia
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
        - env:
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /app/secrets-authelia/jwt
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /app/secrets-authelia/session
            - name: AUTHELIA_DUO_API_SECRET_KEY_FILE
              value: /app/secrets-authelia/duo
          image: 'authelia/authelia:4.28.2'
          imagePullPolicy: IfNotPresent
          name: authelia
          ports:
            - containerPort: 9091
          securityContext:
            runAsGroup: 100
            runAsUser: 1024
          volumeMounts:
            - mountPath: /config
              name: authelia-config
            - mountPath: /app/secrets-authelia
              name: secrets-authelia
              readOnly: true
            - mountPath: /app/secrets-redis
              name: secrets-redis
              readOnly: true
      volumes:
        - name: secrets-authelia
          secret:
            items:
              - key: jwt_secret
                path: jwt
              - key: session_secret
                path: session
              - key: duo_secret
                path: duo
            secretName: authelia
        - name: secrets-redis
          secret:
            items:
              - key: redis
                path: redis
            secretName: dev2-redis
        - name: authelia-config
          nfs:
            path: /xxxxx
            server: x.x.x.x
```

```
#ingressroute.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    argocd.argoproj.io/instance: dev
  name: authelia
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`authelia-dev.xxx.xx`)
      middlewares:
        - name: authelia
          namespace: dev
      services:
        - name: authelia
          port: 9091
  tls:
    secretName: wildcard-xxx-tls
```
```
#middleware.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    argocd.argoproj.io/instance: dev
  name: authelia
  namespace: dev
spec:
  forwardAuth:
    address: 'http://authelia:9091/api/verify?rd=https://authelia-dev.xxx.xx/'
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
    trustForwardHeader: true
```

and the traefik log when i try to access to the GUI:
```
 k logs traefik-84b498ff95-8qttb --since 1m | grep authelia
time="2021-04-30T17:40:53Z" level=debug msg="Error calling http://authelia:9091/api/verify?rd=https://authelia-dev.xxx.fr/. Cause: Get \"http://authelia:9091/api/verify?rd=https://authelia-dev.xx.fr/\": dial tcp: lookup authelia on 10.96.0.10:53: no such host" middlewareName=dev-authelia@kubernetescrd middlewareType=ForwardedAuthType
{"ClientAddr":"10.244.1.1:21815","ClientHost":"10.244.1.1","ClientPort":"21815","ClientUsername":"-","DownstreamContentSize":0,"DownstreamStatus":500,"Duration":5680575,"OriginContentSize":0,"OriginDuration":5606891,"OriginStatus":500,"Overhead":73684,"RequestAddr":"authelia-dev.xxx.fr","RequestContentSize":0,"RequestCount":2279,"RequestHost":"authelia-dev.xxx.fr","RequestMethod":"GET","RequestPath":"/","RequestPort":"-","RequestProtocol":"HTTP/2.0","RequestScheme":"https","RetryAttempts":0,"RouterName":"dev-authelia-2a93348d78ee5e120121@kubernetescrd","StartLocal":"2021-04-30T17:40:53.869300811Z","StartUTC":"2021-04-30T17:40:53.869300811Z","entryPointName":"websecure","level":"info","msg":"","time":"2021-04-30T17:40:53Z"}
```

Thanks for you help!
