### ISSUE TITLE
Authelia silently failing to start

### ISSUE THREAD

**Issue by SerialVelocity** [authelia/authelia#2006]
## Bug Report

I just tried updating from 4.15.1 to 4.29.2. The container is now failing to start up with exit code 1. 

Logs only contain:
```
time="2021-05-15T13:19:59Z" level=error msg="Unable to find config file: /config/configuration.yml"
time="2021-05-15T13:19:59Z" level=error msg="Generating config file: /config/configuration.yml"
time="2021-05-15T13:19:59Z" level=error msg="Generated configuration at: /config/configuration.yml"
```

Environment variables set:
```
        - name: AUTHELIA_JWT_SECRET_FILE
          value: /run/secrets/authelia/jwt_secret
        - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
          value: /run/secrets/authelia/ldap_password
        - name: AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE
          value: /run/secrets/authelia-mysql/db_password
```

Configuration:
```
    host: 0.0.0.0
    port: 9091
    log_level: debug

    authentication_backend:
      ldap:
        ...

    session:
      expiration: 86400
      inactivity: 43200
      remember_me_duration: 1y
      domain: <my domain>
      # TODO: redis session store

    regulation:
      max_retries: 1000
      find_time: 120
      ban_time: 300

    storage:
      mysql:
        ...

    access_control:
      default_policy: one_factor

    notifier:
      filesystem:
        filename: /tmp/authelia-notification.txt
```

Expected behaviour:
An error message about why it is failing
