### ISSUE TITLE
Help configuring Authelia and Docker apps

### ISSUE THREAD

**Issue by zkvvoob** [authelia/authelia#2014]
Hello all,

I've just finished setting up Authelia following [this guide](https://www.blackvoid.club/authelia-sso-and-2fa-portal/). I've got Nginx Proxy Manager working properly for all my subdomains/apps; Authelia is on a subdomain of its own (auth.mydomain.com), LDAP seems to be functioning correctly (as in, I can log in, use TOTP code and am redirected to the selected page).

What I can't figure out is how exactly does the authentication to any given apps work. I've tried with Gogs (a git app) - put the Nginx config in NPM and when I try to open gogs.mydomain.com, I'm redirected to Authelia (so far, so good), I enter my credentials and then the browser goes to gogs.mydomain.com where I can see 403 Forbidden error message.

I'm new to Nginx and I don't understand if there's additional configuration that needs to be done at each individual app so as to recognize the credentials passed by Authelia.

Ideally, I'd like successful authentication to load my Heimdall dashboard with tiles/apps for each individual user and then the user could click on the tile and be automatically logged in the respective app.

Thank you in advance for helping me.

**Comment by james-d-elliott** [comment]
Hey @zkvvoob this is likely missing configuration in your access control section. Lets say the destination is gogs.example.com, you'd need the following section in your configuration (keeping in mind this section is highly tunable, and that the first rule in the list that matches the conditions of the request applies the configured policy):

```yaml
access_control:
  default_policy: deny
  rules:
  - domain: gogs.example.com
    policy: one_factor
```

Alternatively:


```yaml
access_control:
  default_policy: deny
  rules:
  - domain: "*.example.com"
    policy: one_factor
```
