### ISSUE TITLE
Vault Integration

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#2026]
### Description

Add native HashiCorp Vault support to Authelia.

`go get github.com/hashicorp/vault/api`

### Use Case

Allow provisioning the secrets via vault without the use of the injector. This will mean the secret data is only available in memory, and not via any fs means. Additionally it provides support for people using plain docker or docker swarm instead of limiting it to kubernetes users.

**Comment by Gsyltc** [comment]
Hi,

you can use OIDC configuration to connect Vault 

in Authelia configuration file

Section
```
identity_providers:
  oidc:
      #    hmac_secret: DOCKER SECRET
      #    issuer_private_key:  DOCKER SECRET
    clients:
    - id: your_generated_id
      description: Vault
      secret: your_generated_secret
      authorization_policy: two_factor (as you want)
      redirect_uris:
      - https://vault.jeedom-gaston.ovh/oidc/callback
      - https://vault.jeedom-gaston.ovh/ui/vault/auth/oidc/oidc/callback
      scopes:
      - openid
      - groups
      - email
      - profile
```

In Vault, Create an Auth Method based on OIDC
If you use the WebUI you can configure OIDC like this : 

```
OIDC discovery URL : https://<your-authelia-domain>/
Default Role : You user default role (exemple : user, admin, myrole)

Under the drop down button "Show OIDC Option"
OIDC client ID :  your_generated_id
OIDC client secret : your_generated_secret
```

That's all :)

Have à nice day
