### ISSUE TITLE
Make Authelia "Kubernetes aware" with custom resource types

### ISSUE THREAD

**Issue by AlexGustafsson** [authelia/authelia#2041]
### Description

Applications such as Traefik may use the fact that they're running in a Docker Swarm or in Kubernetes to leverage the features they have. In the case of Docker Swarm, Traefik make use of labels on the containers to automatically configure Traefik at run-time. When deployed in a Kubernetes cluster, Traefik may support custom resource types to control ingress.

A similar feature deployed to Authelia would allow administrator to more easily configure protection for a new application when deployed on Kubernetes. An administrator would deploy a custom resource such as the one listed below in order to configure the ACL.

```yaml
apiVersion: authelia.com/v1
kind: AccessControlRule
metadata:
  name: allow-admins
  namespace: my-application-namespace
spec:
  domain: my-application.example.org
  policy: two_factor
  subject: "group:admin"
```

Authelia would use the Kubernetes API at runtime with RBAC configured to securely monitor the change of these resources. When a resource, such as the one above, is added, Authelia would then configure itself at run-time to allow admins to access the application.

### Use Case

Authelia may be a central part of a deployed network architecture. In Kubernetes, it therefore often makes sense to handle its configuration centrally and have it in its own namespace. What does not make sense, however, is continuously updating the configuration file to add applications defined elsewhere.

Although the same features could be offered by forthcoming admin UI and API, they do not handle the code-based nature of this proposed feature. In the case of Kubernetes, where everything is defined in configuration files, it may make sense to fill that gap.

Some (vaguely) related discussion:
* https://github.com/authelia/authelia/issues/646
* https://github.com/authelia/authelia/issues/1275

**Comment by AlexGustafsson** [comment]
I'm going to take a look on this issue to try the methodology out. Though my use case mostly covers Kubernetes, supporting Docker Swarm deployments based on labels is similar enough to perhaps warrant some research on that as part of this issue as well.

**Comment by AlexGustafsson** [comment]
The implementation is planned as follows:

* A custom resource is created and deployed on the Kubernetes cluster (this will look very similar if not identical to the rule item already available in the config file for Authelia). I have a PoC for this.
* A library for using the custom resource's API is put in place which allows watching the custom resources for changes, additions and deletions. The API uses the official Kubernetes client library. I have a PoC for this.
* Add a config option to _explicitly toggle on_ the behavior
* In `startServer`, initialize a Kubernetes "watcher" using the aforementioned library, if the functionality is activated.
* The watcher will produce a list of  `AccessControlRule` when Authelia is first started, based on the currently deployed configuration on Kubernetes
* The configuration is merged with the existing rule set
* Authelia may continue to start as usual
* The watcher continues to listen for changes in the background and produce an up-to-date set of `AccessControlRule` whenever a change is made and merges with the existing rule set

I have two concerns:
1. How do we properly handle the merging? What happens if rules collide?
2. What happens if the deployed configuration on Kubernetes becomes invalid?

As for the first concern, I haven't given it too much thought as I'd really like some input there. It feels like one of those cases where it's easy to implement, but difficult to design. Also, since a background thread will be updating the access control rules of the authorizer, we should lock the access to the set when it's in use. I haven't studied the code base enough to see if that may be a potential issue or not, so I'd appreciate some heads up if that's the case.

As for the second result, a somewhat sensible way is simply to ignore bad updates. The issue with this, however, is that admins may believe they've deployed access control for a domain, when in reality it hasn't been activated. One can of course swing the other way in terms of security and block all access to a domain with bad configuration. But that leads to an unusable website, which is sub-optimal to say the least. To some extent, this may be solved statically by implementing a schema which all custom rules need to follow. These are verified before the rules may be deployed onto Kubernetes, meaning they won't reach Authelia at all. One may however chose to ignore these errors and apply a badly formatted rule anyway, meaning Authelia has to take care of it anyway.

To some extent I think both of the concerns are relevant when introducing other run-time abilities such as the coming API I've seen being planned. So you may already have some good solutions lined up.

**Comment by AlexGustafsson** [comment]
Regarding the side note and static check via a schema in the Kubernetes custom resource definition. It turns out Kubernetes does not support a schema where strings and arrays etc. are interchangeable, such as the configuration files are. It's therefore not possible to allow the same schema to be used. Currently, I've added a schema which reflects how the configuration is stored in Go (arrays etc.). Another option is to allow the syntax, but to not offer the schema validation at all.

Example that's okay in the config, but not Kubernetes with the current schema:
```yaml
domain: example.org
subject: "group:admins"
```

Example that's okay (if we ignore the key change) in the config, as well as Kubernetes:
```yaml
domains:
  - example.org
 subjects:
  - ["group:admins"]
```

**Comment by james-d-elliott** [comment]
The biggest complication you're going to experience with this is the method for resolving rule order. Rules are parsed in a top down method similar to how a firewall works. This is not going to be ideal for a k8s CRD, and the method to fix it would be unlikely to be compatible with the file based config.

**Comment by AlexGustafsson** [comment]
__Solution 1: Adding a rule index value__

The CRDs are meant to be deployed alongside the app it controls, within the same namespace. If one deploys a CRD for multiple, entirely different applications, it sort of depletes the purpose of them. If one assumes that this is true, the issue of resolving rule order is bound to the rules for a single app. We may add a field to the CRD that explicitly states the rule order - within the namespace they're deployed. That way, we may sort the rules by that value, for each namespace. This of course assumes that there's no overlap of rules between namespaces, which may be a valid assumption - but it may still be prone to misconfiguration.

One may get the exact same behavior of rules as the config files if the rule order of the CRDs are global. But that will likely become an unmaintainable mess. Narrowing it down to a namespace alleviates some of that pain. Of course, there may be namespaces with plenty of apps in them, which may still make a lot of CRDs a bit hard to maintain in the sense that the rule order has to be kept. But disregarding the rule order is not an option.

__Solution 2: Making the CRD a list of rules__

A different alternative to resolving this is making a CRD for a list of rules. The lists should not rely on the order they're applied. The rules within the list are applied in the order they're written. This makes it more like the configuration file and removes some potential pain points for the cost of being ever so slightly more verbose.

```yaml
apiVersion: authelia.com/v1
kind: AccessControlRules
metadata:
  name: allow-admins
  namespace: my-application-namespace
spec:
  rules:
    - domains:
        - my-application.example.org
      policy: two_factor
      subjects:
        - ["group:admin"]
```

__Interoperability with the config file__
As for interoperability with the configuration file, I believe it makes sense to always append the rules from the CRD to the existing rules. Whether that is just those defined in the configuration file, or in the future, rules that are created via an API, the CRDs should be applied last.

**Comment by james-d-elliott** [comment]
You bring up some interesting solutions to this, and helped me think of a third option.

We could theoretically utilize the position field that already exists. If we allow users to *optionally* configure this both in the config file and in the CRD. In this scenario the rules would be processed in order similar to how you mentioned.

Specifically if we parse and add config file rules first, where the default position value of each rule is a sequential number starting at 0, then we parse and add the CRD, and insert the rules based on their priority, or in alphanumeric order (name+namespace), we would have a relatively customizable option.

I believe there is nothing stopping us adding rules in their configured position, the only check we have to do is if a rule already exists in that position, and choose a method to deal with this situation. The two methods that come to mind are: if rule 5 already exists, increment 5 by 1 until it finds a position where the rule does not exist, *or* if rule 5 already exists, insert it into position 6 moving any subsequent rules down one.

> As for interoperability with the configuration file, I believe it makes sense to always append the rules from the CRD to the existing rules. Whether that is just those defined in the configuration file, or in the future, rules that are created via an API, the CRDs should be applied last.

I somewhat disagree about having the CRD rules last, as it would make more sense to me to have *specific* rules in the CRD and *catch all* rules in the config file. However maybe there is something I've not considered and overall I like your response.

**Comment by AlexGustafsson** [comment]
I don't quite see a case for having the rules from CRDs in between rules of the config file, so whether or not the rules from the config file are added first or last, the position should be scoped for the CRDs and perhaps even scoped for the namespace. The reasoning is that a multi-tenant operator using the CRDs will not necessarily be exposed to the config at all - they will only know what they can see in their namespace(s).

I think your reasoning on adding the rules from the configuration file last to act as default rules has merit. One potential issue could be cases where the admin wants to restrict some endpoints to never allow them. If the CRDs are applied first, the rules set by the admin may become obsolete - because Authelia uses the first rule it matches, right? I suppose the idea is that the admin controlling Authelia is in complete control, whilst admins deploying CRDs are not - meaning they should not be able to overwrite the behavior of the config file, only restrict further. Hopefully that makes sense.

As for the sorting, perhaps a hybrid would work. We let the CRDs be a list of rules. The list may have an optional `position` or `priority` set. The first rule in the list will be given the defined priority, the second the defined priority + 1 and so on. That way, it's simple to allow for a similar behavior as in the config files for smaller deployments where there's perhaps a CRD per namespace without any overlap. Using the priority, a more complex setup may also be supported across namespace. If no priority is specified, the rules are sorted by creation time and assigned an incremental priority based on index. That way, the order is not necessarily controlled but at the very least deterministic.

When merging with the rules from the config, the priorities may not overlap. If we apply the config first, the position of the last rule + 1 will be added to any position defined in the CRDs. Conversely, if we apply the config last, the position of the last CRD rule + 1 will be added to any position for the rules from the config.

**Comment by feitnomore** [comment]
If you allow me, I would like to share my 2 cents on this.

First create a configmap with your configuration file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  configuration.yml: |
    ---
    ###############################################################
    #                   Authelia configuration                    #
    ###############################################################
    jwt_secret: my-secret
    default_redirection_url: https://login.my-domain.com
    server:
      host: 0.0.0.0
      port: 9091
    log:
      level: info
    totp:
      issuer: my-domain.com
      .
      .
      .
    access_control:
      default_policy: deny
      rules:
        # Rules applied to everyone
        - domain: web1.my-domain.com
          policy: two_factor
          subject:
          - ["group:admins"]
```

Then you can use https://github.com/stakater/Reloader with your deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
  annotations:
    configmap.reloader.stakater.com/reload: "authelia-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      runtimeClassName: gvisor
      securityContext:
        runAsUser: 10000
        runAsGroup: 30000
      containers:
      - image: authelia/authelia
        name: authelia
        ports:
          - name: http
            containerPort: 9091
        - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE
          value: "/etc/authelia/keys/key.pem"
        args:
          - --config
          - /etc/authelia/configuration.yml
        readinessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 9091
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /etc/authelia
        - name: key-volume
          mountPath: /etc/authelia/keys
        - name: authelia-volume
          mountPath: /opt/authelia
      volumes:
        - name: config-volume
          configMap:
            name: authelia-config
        - name: key-volume
          secret:
            secretName: authelia-keys
        - name: authelia-volume
          persistentVolumeClaim:
            claimName: authelia-claim
```

That way, if you `kubectl edit authelia-config -n authelia` and save, the tool will reload your pods automatically.
