### ISSUE TITLE
Authelia does not accept my TOTP, before it worked

### ISSUE THREAD

**Issue by Sakujakira** [authelia/authelia#2066]
## Bug Report
Hi there, since today Authelia seems to not accept my TOTP anymore. Maybe someone could help me. 

### Description

Since (at least) yesterday Authelia won't accept my 2FA generated Code. 
I am running Authelia in combination with SWAG from linuxserver.io (Nginx). Authelia mentions my TOTP is wrong, but this is in fact the code generated by Authy. 

### Expected Behaviour

Authelia accepts my code and grants access to protected ressources. 

### Reproduction Steps

Login, enter first Factor. Enter Second Factor -> Failure. 

#### Log from Docker Container

```
time="2021-06-06T14:57:42+02:00" level=info msg="Logging severity set to debug"
time="2021-06-06T14:57:42+02:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2021-06-06T14:57:42+02:00" level=debug msg="Storage schema is up to date"
time="2021-06-06T14:57:42+02:00" level=debug msg="Notifier SMTP client attempting connection to XXXXXXXX.kasserver.com:587"
time="2021-06-06T14:57:42+02:00" level=debug msg="Notifier SMTP client connected successfully"
time="2021-06-06T14:57:42+02:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: XXXXXXXX.kasserver.com), attempting"
time="2021-06-06T14:57:42+02:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2021-06-06T14:57:42+02:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: PLAIN LOGIN"
time="2021-06-06T14:57:42+02:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2021-06-06T14:57:42+02:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2021-06-06T14:57:42+02:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091/authelia"
time="2021-06-06T14:57:57+02:00" level=debug msg="Mark authentication attempt made by user manuel" method=POST path=/api/firstfactor remote_ip=192.168.xx.yy
time="2021-06-06T14:57:57+02:00" level=debug msg="Credentials validation of user manuel is ok" method=POST path=/api/firstfactor remote_ip=192.168.xx.yy
time="2021-06-06T14:58:04+02:00" level=error msg="Wrong passcode during TOTP validation for user manuel" method=POST path=/api/secondfactor/totp remote_ip=192.168.xx.yy stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:65     (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:148               handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_sign_totp.go:36       SecondFactorTOTPPost.func1\ngithub.com/authelia/authelia/internal/middlewares/require_first_factor.go:15 RequireFirstFactor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:50     AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.12/router.go:414                             (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14          LogRequestMiddleware.func1\ngithub.com/authelia/authelia/internal/middlewares/strip_path.go:20           StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.24.0/server.go:2219                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:223                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:195                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371                                                     goexit"
time="2021-06-06T15:00:10+02:00" level=debug msg="Check authorization of subject username=manuel groups= ip=192.168.xx.yy and object https://my.domain.tld/bazarr/ (method GET)."
time="2021-06-06T15:00:10+02:00" level=info msg="Access to https://my.domain.tld/bazarr/ (method GET) is not authorized to user manuel, sending 401 response" method=GET path=/api/verify remote_ip=192.168.11.78
time="2021-06-06T15:00:25+02:00" level=error msg="Wrong passcode during TOTP validation for user manuel" method=POST path=/api/secondfactor/totp remote_ip=192.168.xx.yy stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:65     (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:148               handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_sign_totp.go:36       SecondFactorTOTPPost.func1\ngithub.com/authelia/authelia/internal/middlewares/require_first_factor.go:15 RequireFirstFactor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:50     AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.12/router.go:414                             (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14          LogRequestMiddleware.func1\ngithub.com/authelia/authelia/internal/middlewares/strip_path.go:20           StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.24.0/server.go:2219                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:223                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:195                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371                                                     goexit"

```

#### Docker Compose
```
authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - TZ=Europe/Berlin
      - PUID=118
      - PGID=124
    volumes:
      - ${USERDIR}/docker/authelia:/config
    restart: unless-stopped
    networks:
      - web
    security_opt:
      - no-new-privileges:true
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=https://discord.com/api/webhooks/YYYYYYYYYYYYYYY/XXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXX"
      - "org.hotio.pullio.author.avatar=https://hotio.dev/img/pullio-sunglasses.svg"
```

I do appreciate any help and hints.
