### ISSUE TITLE
Auth portal in /login

### ISSUE THREAD

**Issue by GeorgeRT** [authelia/authelia#2095]
Using nginx, how do I configure the portal to be a location in the protected server, eg. test1factor.example.org/login  and of course the authenticated redirect would be test1factor.example.org.  I can't make the login page show using the below.  Using a separate server name (eg, auth.example.org) works just fine.  Thanks.
```
server {
   server_name    auth.example.org;
   location / {
      set $upstream_authelia http://127.0.0.1:9091;
      proxy_pass $upstream_authelia;
      include /var/www/library/authelia/proxy.conf;
   }
}

server {
   server_name    test1factor.example.org;
   location /login {
      set $upstream_authelia http://127.0.0.1:9091;
      proxy_pass $upstream_authelia;
      include /var/www/library/authelia/proxy.conf;
   }

   location / {
      try_files $uri $uri/ @slug;
      include /var/www/library/authelia/auth.conf;
      include /var/www/library/authelia/proxy.conf;
   }
}
```
configuration.yml looks like:

   ```
- domain: test1factor.example.org
      resources:
      - "^/login/.*"
      - "^/favicon.*"
      - "^/static/.*"
      policy: bypass

    - domain: test1factor.example.org
      policy: one_factor
```
and auth.conf redirect is:
```
#error_page 401 =302 https://auth.example.org/?rd=$target_url;
error_page 401 =302 https://test1factor.example.org/login;
```
