### ISSUE TITLE
feature : get user group using the attribute memberOf on user

### ISSUE THREAD

**Issue by Alexsaphir** [authelia/authelia#2161]
### Description

The goal is to get the groups of an user using the attribute memberOf. No query is done with a group filter. A Base Group DN and a group attribute could still be supplied to keep a short group name in  the Authelia configuration and not the full DN.

### Use Case

The main use case is to provide a solution to the nested group issue with openldap and freeipa.
Freeipa provide the attribute memberOf per default and openldap need an overlay attribute to be added. It's not necessary with active directory due to the support of the nested extension.

Authelia  already make a distinction between active directory and the others ldap provider.
A parameter to distinguish between the current behavior and the one would need to be added but the other settings could be reused

**Comment by james-d-elliott** [comment]
Hey @Alexsaphir thanks for the idea. Would you be willing to share if you're using FreeIPA or not? Basically I'd like to expand the number of implementations we have direct support for, FreeIPA being one.

Additionally this is potentially something we can do and I think it would be relatively easy. Basically have a `groups_attribute` and `groups_modes` configuration option. Default would be `search`, but `attribute,search` or `attribute` would be additional options. Example configurations below and the expected results:

### Example 1

```yaml
authentication_backend:
  ldap:
    groups_attribute: memberOf
    groups_mode: search
```
**Result:** Current behaviour

### Example 2

```yaml
authentication_backend:
  ldap:
    groups_attribute: memberOf
    groups_mode: attribute
```
**Result:** Proposed behaviour, we just provide the value from the groups_attribute

### Example 2

```yaml
authentication_backend:
  ldap:
    groups_attribute: memberOf
    groups_mode: search,attribute
```
**Result:** Example 1 and Example 2 behaviour, we concatenate and de-duplicate the results.

Thoughts @nightah @clems4ever

**Comment by Alexsaphir** [comment]
Hi @james-d-elliott , you should thanks the Grafana team, I discover this settings up LDAP in it yesterday and was impressed, and yes I use FreeIPA. OpenLDAP users could still enjoy this improvement by enabling  the memberOf [overlay](https://www.openldap.org/doc/admin24/overlays.html) _(Note that the memberOf attribute is an operational attribute, so it must be requested explicitly.)_.

For reference the following query `ldapsearch -x -b "cn=users,cn=accounts,dc=alexsaphir,dc=com" -H ldap://192.168.0.2 -D "uid=admin,cn=users,cn=accounts,dc=alexsaphir,dc=com" -w $IPA_ADMIN_PASSWORD uid=alexsaphir memberOf`

against my FreeIPA instance give the results (shorten for brevity):
``` 
# alexsaphir, users, accounts, alexsaphir.com
dn: uid=alexsaphir,cn=users,cn=accounts,dc=alexsaphir,dc=com

memberOf: cn=authelia,cn=groups,cn=accounts,dc=alexsaphir,dc=com
memberOf: cn=authelia-admin,cn=groups,cn=accounts,dc=alexsaphir,dc=com
```
If the group name inside the authelia configuration is `authelia` and `groups_attribute=memberOf`, you need to match the following query: 

<pre>
f"{groups_attribute}: {group_name_attribute}=<b>authelia</b>,{additional_groups_dn},{base_dn}"
</pre>

**Comment by clems4ever** [comment]
> Hey @Alexsaphir thanks for the idea. Would you be willing to share if you're using FreeIPA or not? Basically I'd like to expand the number of implementations we have direct support for, FreeIPA being one.
> 
> Additionally this is potentially something we can do and I think it would be relatively easy. Basically have a `groups_attribute` and `groups_modes` configuration option. Default would be `search`, but `attribute,search` or `attribute` would be additional options. Example configurations below and the expected results:
> 
> ### Example 1
> ```yaml
> authentication_backend:
>   ldap:
>     groups_attribute: memberOf
>     groups_modes: search
> ```
> 
> **Result:** Current behaviour
> 
> ### Example 2
> ```yaml
> authentication_backend:
>   ldap:
>     groups_attribute: memberOf
>     groups_modes: attribute
> ```
> 
> **Result:** Proposed behaviour, we just provide the value from the groups_attribute
> 
> ### Example 2
> ```yaml
> authentication_backend:
>   ldap:
>     groups_attribute: memberOf
>     groups_modes: search,attribute
> ```
> 
> **Result:** Example 1 and Example 2 behaviour, we concatenate and de-duplicate the results.
> 
> Thoughts @nightah @clems4ever

Sounds like a plan, I like the idea of supporting nested groups. Thanks for the suggestion @Alexsaphir .
I'd rather limit the implementation to example 2 though because it covers the majority of use cases, we don't really "need" example 3 yet.
We would need to make it work with openldap though so that we can properly test the feature in a suite.

**Comment by Alexsaphir** [comment]
If you want I can test it with FreeIPA on my side and report any issue.
For the automation with OpenLDAP, you can follow https://github.com/rroemhild/docker-test-openldap/pull/6/commits/0872312174f93d72304b8b89ec48127208209584 .

**Comment by james-d-elliott** [comment]
> I'd rather limit the implementation to example 2 though because it covers the majority of use cases, we don't really "need" example 3 yet.

Makes sense to me. Amir had the same idea.

> 
> 
> If you want I can test it with FreeIPA on my side and report any issue.
> For the automation with OpenLDAP, you can follow [rroemhild/docker-test-openldap@0872312](https://github.com/rroemhild/docker-test-openldap/commit/0872312174f93d72304b8b89ec48127208209584) .

@Alexsaphir I would indeed like this if we implemented it. What I was hoping for is for you to create a set of sane defaults values for FreeIPA in general.

I have just identified another potential issue. Using the memberOf attribute we only obtain the distinguishedName's of groups most likely (can you confirm if this is accurate?). This means we'd have to lookup each group that ends with the baseDN. I can relatively easily programmatically generate a filter which finds all objects with a specific distinguishedName however this is going to be inefficient if there is a built in way to do this.

**Comment by james-d-elliott** [comment]
@Alexsaphir feel free to try the image tagged `feat-ldap-group-attr`. It contains a few new things. The freeipa implementation has been added, you can view the defaults and critique them [here](https://github.com/authelia/authelia/pull/2178/files#diff-c1278aed7954b018e82841f8e1831f454e44a03977785d380f85725d5a5995cfR99-R108). Additionally I added the groups_attribute and distinguished_name_attribute options. distinguished_name_attribute is used to build the filter to find groups with specific DN's. 

```yaml
authentication_backend:
  ldap:
    implementation: freeipa
    # groups_attribute: memberOf
    # distinguished_name_attribute: dn
```

**Comment by james-d-elliott** [comment]
This is effectively closed by 4482 linked just above this comment. No need to use `memberOf`.

**Comment by alKraa** [comment]
@james-d-elliott I don't see how #4482 solves the nested group issue mentioned by @Alexsaphir.
Using memberOf this would have been possible, without it groups have to be resolved recursively, but that's not happening I think!?
Am I missing something?

**Comment by james-d-elliott** [comment]
Hi @alKraa I think you're not, think I did when I closed it, while this doesn't work for nested groups provided the user has the privileges to query the `member` attribute this works for everything else. As far as nested groups there is only three ways to do this:

1. The LDAP provider provides a specific OID for a search like this. As far as I can see FreeIPA doesn't.
2. The LDAP provider is queried once for the user, and:
    1. Once for every single group they have a `memberOf` for *or*
    2. Once in bulk for every group they have a `memberOf` for (provided the server supports this)
3. The LDAP provider is queried recursively for each group level.

I'll run up my FreeIPA VM (since they have  one of the most god awful containers in existence) and take a quick look at the feasibility of option 1 and 2.

**Comment by james-d-elliott** [comment]
@alKraa try with the following:

- [PR5418](https://github.com/authelia/authelia/pull/5418)
- [Documentation](https://645a2653a9f9150008bbf1d5--authelia-staging.netlify.app/configuration/first-factor/ldap/)
- Docker Image: `feat-ldap-memberof`

 Configuration example (only important values are listed, and note all the attribute values have changed):

```yaml
authentication_backend:
  ldap:
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person)(!(nsAccountLock=TRUE))(krbPasswordExpiration>={date-time:generalized})(|(!(krbPrincipalExpiration=*))(krbPrincipalExpiration>={date-time:generalized})))'
    groups_filter: '(&(|({memberOf}))(objectClass=groupOfNames))'
    group_search_mode: 'memberof'
    attributes:
      distinguished_name: ''
      username: 'uid'
      display_name: 'displayName'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'
```
