### ISSUE TITLE
LDAP: Add FreeIPA Implementation

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#2177]
### Description

Add an implementation for FreeIPA with sane defaults. Criteria is as follows:

Users filter should exclude:
- [x] Users which are disabled if this feature exists in FreeIPA.
- [x] Users which have expired passwords if this feature exists in FreeIPA.

Values Needed:
- [x] ~~distinguished_name_attribute (new attribute)~~
- [x] users_filter (see above, needs particular attention)
- [x] username_attribute
- [x] mail_attribute
- [x] display_name_attribute
- [x] ~~groups_attribute~~
- [x] group_name_attribute

### Use Case

Easier LDAP Implementation.

**Comment by deathbybandaid** [comment]
I normally am opposed to comments that don't contribute to a discussion, but my purpose right now is to be a voice of a humble home-labber that is very interested in the development of this feature.

I'd like to be able to create a group in freeipa called sonarr_users for users of sonarr versus specifying individuals.

Doing so makes authelia more fluid, as it doesn't require a config-change+restart to implement, as ldap queries are done live.

**Comment by james-d-elliott** [comment]
I'm happy to put some time into this. I've just not had someone who actively uses it and is actually constructive with their feedback.

Could you explain what you mean by restarting? Authelia already periodically queries LDAP for up-to-date information.

**Comment by deathbybandaid** [comment]
As of now, authelia isn't pulling group memberships from FreeIPA properly.

Example, I am using authelia to protect sonarr.

````
    - domain:
      - 'sonarr.my.domain'
      subject:
      - 'user:user_a'
      - 'user:user_b'
      policy: one_factor
````

If I want to modify what users can access sonarr, I have to modify the yaml and restart authelia.

The prefered method would be to 

````
    - domain:
      - 'sonarr.my.domain'
      subject:
      - 'group:sonarr_users'
      policy: one_factor
````

This way, I can modify a group membership in freeipa, without having to restart authelia for the user permissions to take effect.

**Comment by james-d-elliott** [comment]
Yeah gotcha. So it's not exactly restart related it's just that it doesn't work because FreeIPA doesn't use a RFC compliant group membership method.

That's the main issue I was aiming to tackle with a FreeIPA implementation.

**Comment by deathbybandaid** [comment]
It's mostly a convenience thing, really

**Comment by james-d-elliott** [comment]
Can you share your LDAP section minus password (feel free to anonymize the DN's), as well as your compose for FreeIPA itself?

**Comment by deathbybandaid** [comment]
Here's my ldap section in my authelia configuration.yml

````
authentication_backend:
  password_reset:
    disable: true
    custom_url: ""
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldaps://freeipa1.mylocal.domain
    base_dn: dc=mylocal,dc=domain
    username_attribute: uid
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=inetOrgPerson))
    additional_groups_dn: cn=groups,cn=accounts
    groups_filter: (&(member=uid={input},cn=accounts,dc=mylocal,dc=domain)(objectClass=groupofnames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: uid=svc_authelia,cn=users,cn=accounts,dc=mylocal,dc=domain
    password: totally_the_most_secure_password
````

Not sure what you mean by my freeipa compose

**Comment by james-d-elliott** [comment]
This config should actually work now I've managed to dig through their implementation more (didn't manage to test it as FreeIPA's official docker container is absolute garbage):

```yaml
authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldaps://freeipa.example.com
    base_dn: DC=example,DC=com
    additional_users_dn: CN=users,CN=accounts
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: displayName
    additional_groups_dn: ''
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    group_name_attribute: cn
    user: UID=admin,CN=users,CN=accounts,DC=example,DC=com
```

**Comment by james-d-elliott** [comment]
Okay I settled on this setting suite for now, works perfectly with groups, and prevents disabled accounts from logging in (tested on  FreeIPA 4.10 on AlmaLinux 9):

```yaml
authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldaps://freeipa.example.com
    tls:
      server_name: freeipa.example.com
      skip_verify: true
    base_dn: DC=ipa,DC=example,DC=com
    additional_users_dn: CN=users,CN=accounts
    users_filter: '(&({username_attribute}={input})(objectClass=person)(!(nsAccountLock=TRUE)))'
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: displayName
    additional_groups_dn: ''
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    group_name_attribute: cn
    user: UID=authelia,CN=users,CN=accounts,DC=ipa,DC=example,DC=com
    password: authelia
```
