### ISSUE TITLE
Get first and last name

### ISSUE THREAD

**Issue by elwinh** [authelia/authelia#2211]
Hello,

I would like to pass the firstname and lastname of the user.
I see the options are available for Remote-User,Remote-Groups,Remote-Name,Remote-Email.
Is there also a option for Firstname and Lastname? 

            "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true",
            "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"

**Comment by nightah** [comment]
Remote-Name is based off of the following configuration for an LDAP based backend:
https://github.com/authelia/authelia/blob/c98b2a7d59d18e97bd8f567fbb6294e57e8499a8/config.template.yml#L210

For the file based backend it's based off of the `displayname` field:
https://github.com/authelia/authelia/blob/c98b2a7d59d18e97bd8f567fbb6294e57e8499a8/internal/authentication/users_database.template.yml#L11

In the case of LDAP displayname usually is a combination of First name + Last name.

**Comment by elwinh** [comment]
Oke, but how to split them in traefik so that there are 2 new headers. One containing the firstname and one containing the last name?

**Comment by nightah** [comment]
This is probably a little more difficult with Traefik because they don't provide the ability to manipulate/transform headers natively.

You'll need a plugin like this one: https://pilot.traefik.io/plugins/605afbe6a5f67ab9a1b0e540/rewrite-header and you'll need to write the two new headers based on the `Remote-Name` header.

**Comment by nightah** [comment]
So in case anybody else comes across this issue and wants a working solution, I've utilised https://github.com/domainesia/traefik-plugin-reformatheader as a local/private plugin with Traefik successfully.

Just one thing to keep in mind is that the plugin in its current state is slightly broken, so either wait until the following is merged: https://github.com/domainesia/traefik-plugin-reformatheader/pull/1.

Alternatively, you could just utilise the branch from my fork directly: https://github.com/nightah/traefik-plugin-reformatheader/tree/fix-plugin.

Onto the required configuration:

**Traefik**
You need to mount `/plugins-local` inside your Traefik container:
```yml
    volumes:
      - /path/to/traefik/plugins-local:/plugins-local
```

The tree needs to look like the following with the aforementioned plugin/repo cloned in the last directory `traefik-plugin-reformatheader`:
```
plugins-local
└── src
    └── github.com
        └── domainesia
            └── traefik-plugin-reformatheader
                ├── go.mod
                ├── go.sum
                ├── README.md
                └── reformatheader.go
```

You also need the following configuration on your Traefik container to enable the plugin locally:
```yml
    command:
      - --experimental.localPlugins.reformatheader.moduleName=github.com/domainesia/traefik-plugin-reformatheader
```

And here's the middleware with an example on the `whoami` container:
```yml
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.example.com`)
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.middlewares=authelia,firstname,lastname
      - traefik.http.middlewares.firstname.plugin.reformatheader.fromhead=Remote-Name
      - traefik.http.middlewares.firstname.plugin.reformatheader.regex=(.*) .*
      - traefik.http.middlewares.firstname.plugin.reformatheader.create=Remote-FirstName
      - traefik.http.middlewares.firstname.plugin.reformatheader.format=$${1}
      - traefik.http.middlewares.lastname.plugin.reformatheader.fromhead=Remote-Name
      - traefik.http.middlewares.lastname.plugin.reformatheader.regex=.* (.*)
      - traefik.http.middlewares.lastname.plugin.reformatheader.create=Remote-LastName
      - traefik.http.middlewares.lastname.plugin.reformatheader.format=$${1}
```

It's important to note that the middlewares are applied **AFTER** the `authelia` middleware which sets the `Remote-Name` header. The above also assumes that your `Remote-Name` header contains the first name and last name separated by a space: `<FIRSTNAME> <LASTNAME>`, if this isn't the case you may need to adjust the regexes.

You could also use the regex `(.*) (.*)` and `$${1}` represents the first name and `$${2}` represents the last name.
