### ISSUE TITLE
Traefik unable to redirect external traffic after succesful login and Missing X-Forwarded-Host on reset password

### ISSUE THREAD

**Issue by alborotogarcia** [authelia/authelia#2227]
### 

Unable to forward through traefik when exposing services on an external dns provider (cloudflare).

Been testing lately, and I got authelia working on openldap and smtp relay notification settings on k3d. 
But when it comes to deploy on bare metal servers in my private VPS it doesn't make any redirection at all. Just keeps on /authenticated endpoint.

I am deploying this on a 3 node k3s cluster with cloudflare proxying my .live subdomains (including authelia endpoint) to my dyndns.

FWIW, I have routed 80 and 443 to traefik, and I keep all my internal dns records in a pihole host (external to my k3s cluster). 
I also set my pihole as the only dns server (which later points to cloudflare). 
Authelia does login to my internal ldap instance deployed in my k3s cluster. 

I have set the challenge solver to dns-01 so tls works for all my subdomains on cloudflare. And got the certificates stored as a secret correctly.

I have also tried to set X-Forwarded-Host to my local IP and it seems to send me the email registration for password recovery. So I suspect cloudflare proxy is hidding the headers that allows authelia to TOTP. 

Should I expect it may work for redirection on external traffic if I disable two factor auth? If so, will it still prevent ddos with fail2ban?

There is plenty of doc for traefik but on docker, I'd appreciate to have some on kubernetes too as most of the labels name exceeds 63 character on kubernetes.

### Expected Behaviour
302 to Original CNAME
_N/A_

### Reproduction Steps

```apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: auth
spec:
  forwardAuth:
    address: http://authelia-service.auth.svc:80/api/verify/?rd=https://auth.$MYDOMAIN # also tried only with https://auth.$MYDOMAIN/api/verify 
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-User
      - X-Secret
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
```
```
apiVersion: v1
kind: Service
metadata:
  name: authelia-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9091
  selector:
    app: authelia
  type: LoadBalancer # ClusterIP # LoadBalancer
  # externalTrafficPolicy: Local
  loadBalancerIP: 192.168.x.x
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/hostname: auth.$MYDOMAIN
    cert-manager.io/cluster-issuer: letsencrypt-stg
spec:
  tls:
    - secretName: authelia-ingress-tls
      hosts:
        - auth.$MYDOMAIN 
  rules:
    - host: auth.$MYDOMAIN 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia-service
                port:
                  number: 80
```
The ingress that fails to redirect to after successful one factor authentication. FWIW, I have defined the external hostname annotation at Service level. I can reach it, it redirects to authelia endpoint but then no redirection back to the original url.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
    # ingress.kubernetes.io/auth-type: "forward"
    # traefik.http.middlewares.authelia.forwardauth.tls.insecureskipverify: "true"
    # traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: "Remote-User, Remote-Groups, Remote-Name, Remote-Email"
    # traefik.ingress.kubernetes.io/redirect-entry-point: "https"
    # traefik.ingress.kubernetes.io/redirect-permanent: "true"
    # ingress.kubernetes.io/auth-url: "https://auth.$MYDOMAIN /api/verify?rd=https://helloworld.$MYDOMAIN /" # #/?rd=https://helloworld.$MYDOMAIN /
    # ingress.kubernetes.io/auth-url: "http://authelia-service.auth.svc:80/api/verify" # #/?rd=https://helloworld.$MYDOMAIN
    traefik.ingress.kubernetes.io/router.middlewares: auth-authelia@kubernetescrd
spec:
  rules:
    - host: helloworld.$MYDOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80
  tls:
    - secretName: authelia-ingress-tls
      hosts:
        - helloworld.$MYDOMAIN
```

_N/A_

### Additional Information

_N/A_
