### ISSUE TITLE
Configuration load error from default Kubernetes environment variables

### ISSUE THREAD

**Issue by ieaves** [authelia/authelia#2253]
### Description

Authelia deployments to Kubernetes using a mounted config file cause deployment failures with

```
error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* cannot parse 'port' as int: strconv.ParseInt: parsing \"tcp://ip-address:9091\": invalid syntax"
```

This occurs regardless of the provided config files port value and instead appears related to a default environment variable populated by Kubernetes (K0s in this instance). Updating the deployment with an explicit `AUTHELIA_PORT` env variable i.e.

```
  env:
  - name: AUTHELIA_PORT
    value: "9091"
```
allows the deployment to proceed successfully.

### Expected Behaviour

Authelia deployments in Kubernetes should successfully deploy regardless of which method is used to provide a configuration file.

### Reproduction Steps

Create an Authelia deployment with an explicitly mounted file configuration but no secret or configmap and check the logs of the deployed container.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
        - name: authelia
          image: authelia/authelia:latest
          ports:
            - name: http
              containerPort: 9091
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              subPath: authelia
              name: configs
      volumes:
        - name: configs
          persistentVolumeClaim:
            claimName: your-pvc-with-authelia-configs
 ```
