### ISSUE TITLE
Docker healthcheck fails

### ISSUE THREAD

**Issue by modem7** [authelia/authelia#2261]
End 2021-08-06T08:36:54.704558826+01:00
ExitCode 127
Output /bin/sh: /usr/local/bin/healthcheck.sh: not found
Start 2021-08-06T08:36:54.606117282+01:00

Latest tag.

**Comment by nightah** [comment]
Have you manually set your healthcheck in your `docker run`/`docker create` commands or `docker-compose.yml`?

The healthcheck is no longer found at that location and the default Dockerfile doesn't reference that location either.

**Comment by modem7** [comment]
Heya, 

I have not - did think that might have been the case initially.

```
# Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: Authelia
    # Check this before upgrading: https://github.com/authelia/authelia/blob/master/BREAKING.md
    # image: authelia/authelia:latest
    image: authelia/authelia:4.29.0
    restart: always
    networks:
      pihole:
        ipv4_address: '172.22.0.116'
    volumes:
      - $USERDIR/Authelia:/config
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    depends_on: 
      - dnscrypt-proxy
    # depends_on:
    #   dnscrypt-proxy:
    #     condition: service_healthy
    labels:
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME`)"
      - "traefik.http.routers.authelia-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
```

This is my config - I rolled back to 4.29 just after raising this issue as that version works.
