### ISSUE TITLE
Configuration - Secrets File: Secrets saved in the .env file errors

### ISSUE THREAD

**Issue by viper2g1** [authelia/authelia#2315]
System- Unraid Docker
container: authelia/authelia

I created a file named ".env" and in it I stored several suggested secrets.  When I try to start the container I get errors in the log about the SQL, SMTP, and Redis passwords, thought they are set correctly in the .env.  If I set them manually in the configuration.yml everything works fine.  The only ones I seem to be able to set with the .env variables are the TLS_KEY and the Session_Secret.  

Here is what is listed in the .env for example:

```
AUTHELIA_TLS_KEY_FILE=password1
AUTHELIA_SESSION_SECRET_FILE=password2
AUTHELIA_SESSION_REDIS_PASSWORD_FILE=password3
AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=password4
AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=password5
```

Here is how they appear in the configuration.yml for example:

`jwt_secret: AUTHELIA_JWT_SECRET_FILE`

Here is the extra parameter used in Unraid's docker editor to point towards the .env file:

`-env-file=/mnt/user/appdata/authelia/.env`

MySql error logs:

`time="2021-08-24T14:36:21-07:00" level=fatal msg="Unable to initialize SQL database: Error 1045: Access denied for user 'authelia'@'172.18.0.1' (using password: YES)" stack="github.com/authelia/authelia/v4/internal/storage/mysql_provider.go:81 NewMySQLProvider\ngithub.com/authelia/authelia/v4/internal/commands/root.go:95 getProviders\ngithub.com/authelia/authelia/v4/internal/commands/root.go:65 cmdRootRun\ngithub.com/spf13/cobra@v1.2.1/command.go:860 (*Command).execute\ngithub.com/spf13/cobra@v1.2.1/command.go:974 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.2.1/command.go:902 main\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:11 main\nruntime/proc.go:225 main\nruntime/asm_amd64.s:1371 goexit"`

Redis Error logs:

`time="2021-08-24T14:38:30-07:00" level=fatal msg="Redis connection error: WRONGPASS invalid username-password pair or user is disabled." stack="github.com/authelia/authelia/v4/internal/commands/root.go:138 getProviders\ngithub.com/authelia/authelia/v4/internal/commands/root.go:65 cmdRootRun\ngithub.com/spf13/cobra@v1.2.1/command.go:860 (*Command).execute\ngithub.com/spf13/cobra@v1.2.1/command.go:974 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.2.1/command.go:902 main\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:11 main\nruntime/proc.go:225 main\nruntime/asm_amd64.s:1371 goexit"`

My configuration.yml:

```
---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: AUTHELIA_JWT_SECRET_FILE
default_redirection_url: https://mydomain.net

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE

totp:
  issuer: mydomain.net

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: "*.mydomain.net"
      policy: one_factor
      subject: "group:admins"
      
    - domain:
        - domain1.mydomain.net
        - domain2.mydomain.net
        - domain3.mydomain.net
      policy: one_factor
      subject: "group:mygroup"

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: mydomain.net  # Should match whatever your root protected domain is

  redis:
    host: my.ip.add.ress
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    password: AUTHELIA_SESSION_REDIS_PASSWORD_FILE

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  mysql:
    host: my.ip.add.ress
    port: 3306
    database: authelia
    username: authelia
    ## Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    password: AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE
    timeout: 5s

notifier:
  smtp:
    username: my@email.com
    # Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    password: AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    sender: my@email.com
    host: smtp.gmail.com
    port: 587
...
```

**Comment by james-d-elliott** [comment]
So there are two issues.

1. _FILE env's must point to a file, not have the content. Example instead of `password1` you need to create a file named anything, say `storagepassword` and then mount that in the container, setting the env `AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/path/to/storagepassword`.
2. When you use secrets you should completely omit the configuration for the password/secret/etc from your configuration. i.e:

```yaml
storage:
  mysql:
    host: my.ip.add.ress
    port: 3306
    database: authelia
    username: authelia
    ## Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    password: AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE
    timeout: 5s
```

Becomes:

```
storage:
  mysql:
    host: my.ip.add.ress
    port: 3306
    database: authelia
    username: authelia
    ## Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    timeout: 5s
```
