### ISSUE TITLE
Authelia seems not to work with open-source version of Redis Sentinel 

### ISSUE THREAD

**Issue by danielskowronski** [authelia/authelia#2323]
## Bug Report

Using authelia v4.30.4 with Redis version 6.2.5 in Sentinel mode is not possible. It seems that lack of hashing policies in open-source version causes issues because Authelia uses non-standard key format.

### Description

Log-in attempt causes the following error:
```
level=error msg="Unable to regenerate session for user daniel: CROSSSLOT Keys in request don't hash to the same slot" method=POST path=/api/firstfactor remote_ip=83.22.35.182 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:66  (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/response.go:148            handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:144 FirstFactorPost.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.1/router.go:414                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14       LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.28.0/server.go:2239                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.28.0/workerpool.go:223                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.28.0/workerpool.go:195                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371                                                     goexit"
```

Redis docs: https://redis.com/blog/redis-clustering-best-practices-with-keys/

Key format used, which is incompatible with default hashing policy
```
127.0.0.1:6379> seckeys *
1) "authelia-session:##REDACTED##"
127.0.0.1:6379> 
```

If you changed format to `authelia-session{##SESSION_KEY##}` it should work.

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

configuration section:
```
session:
  name: authelia_session
  secret: ##REDACTED##
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: ##REDACTED##
  redis:
    username: authelia
    password: ##REDACTED##
    tls:
      server_name: redis-master.rlyeh.ds
      skip_verify: false
      minimum_version: TLS1.2
    high_availability:
      sentinel_name: redis01
      sentinel_password: ##REDACTED##
      nodes:
        - host: redis01
          port: 26379
        - host: redis02
          port: 26379
        - host: redis03
          port: 26379
```
