### ISSUE TITLE
Possible to deploy as auth layer inside docker-compose network?

### ISSUE THREAD

**Issue by mike-lloyd03** [authelia/authelia#2353]
Okay maybe this is just a crazy idea. But I have a service running on my network that has no authentication built into it. I do not want this service exposed to the internet. I also don't want people who are on my wifi able to access this service by just navigating to the IP address of the machine it's running on (e.g. http://192.168.0.100:5000). I'd like to have Authelia serve as an authentication layer over this service.  
  
My thought is to create a docker network with both Authelia and this service running inside of it as well as nginx to manage routing.  
  
- The service (Frigate) is listening on port 5000. I do not have this port exposed in my docker-compose file.
- nginx is listening on port 5005 (exposed in docker-compose) and is configured similar to what's shown [in the Authelia docs](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html)
- Authelia is running in same docker network with port 9091 exposed.
- I have created a self-signed cert to use TLS with nginx

When I try this, I get a 500 error when accessing the site (192.168.0.xxx:5005) and docker logs say:
```
 authelia_1  | 2021/09/08 00:45:27 error when serving connection "172.30.0.4:9091"<->"<mycomputer>:35906": error when reading request headers: cannot find http request method in "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x9e\xc8i\xb20\x
18Q\x1d\xa8\xfb}\x86\x05\tM$\x98\xfc\xa6\tc\xf9\xc0\x0f36X\b\x8fm\v\n \xc0\x9b;\x10\r\xf4\f\xd9\x03\xfd\x18\xa8h\xbfE<\xed\xf6[5\xd8\"\xb0#\xc5\x15\xf9\xd9ƕ\x89\xd0\x00 zz\x13\x01\x13\x02\x13\x03\xc0+\xc0/\xc0,\xc00̨̩\xc0\x13\xc0\x14\x00\x9c
\x00\x9d\x00/\x005\x01\x00\x01\x93\x8a\x8a\x00\x00\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00\n\x00\n\x00\bzz\x00\x1d\x00\x17\x00\x18\x00\v\x00\x02\x01\x00\x00#\x00\x00\x00\x10\x00\x0e\x00\f\x02h2\bhttp/1.1\x00\x05\x00\x05\x01\x00\x00\x00\x00
\x00\r\x00\x12\x00\x10\x04\x03\b\x04\x04\x01\x05\x03\b\x05\x05\x01\b\x06\x06\x01\x00\x12\x00\x00\x003\x00+\x00)zz\x00\x01\x00\x00\x1d\x00 !@I\xb1\xde\xee\x87\x1a\x9a\x05\xbbcXF\xed\a\x8a\xe6g\xe0\xa7/\xa2\n\xe8,b\xfbVS\x8d|\x00-\x00\x02\x0
1\x01\x00+\x00\v\nzz\x03\x04\x03\x03\x03\x02\x03\x01\x00\x1b\x00\x03\x02\x00\x02Di\x00\x05\x00\x03\x02h2**\x00\x01\x00\x00\x15\x00\xdc\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00". Buffer size=517, contents: "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x9e\xc8i\xb20\x18Q\x1d\xa8\xfb}\x86\x05\tM$\x98\xfc\xa6\tc\xf9\xc0\x0f36X\b\x8fm\v\n \xc0\x9b;\x10\r\xf4\
f\xd9\x03\xfd\x18\xa8h\xbfE<\xed\xf6[5\xd8\"\xb0#\xc5\x15\xf9\xd9ƕ\x89\xd0\x00 zz\x13\x01\x13\x02\x13\x03\xc0+\xc0/\xc0,\xc00̨̩\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\x8a\x8a\x00\x00\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00
\n\x00\n\x00\bzz\x00\x1d\x00\x17\x00\x18\x00\v\x00\x02\x01\x00\x00#\x00\x00\x00\x10\x00\x0e\x00\f\x02h2\bhttp/1.1\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\r\x00\x12\x00\x10\x04\x03\b\x04\x04\x01\x05\x03\b\x05\x05\x01\b\x06\x06\x01"..."\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"                                                                                                                                                                
authelia_1  | 2021/09/08 00:45:57 error when serving connection "172.30.0.4:9091"<->"<mycomputer>:35908": error when reading request headers: EOF. Buffer size=517, contents: "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\r\xf2\xb8\xcc \x18
\xe8T\xb8\xc6@\b.FW\x18\xde\a\x00Sx\xde\xecr\x84\xfb\x8c\x01\xb2\x8e\rD \xc0\xdfr\xb5\t\x1a\x16\x1fȞ\x8a\x01|\xd0\xc3\x0eL\x1d\x19\xae\x88\xb2\xf8\xd5u\x11JK\x94r\xd48\x00 ZZ\x13\x01\x13\x02\x13\x03\xc0+\xc0/\xc0,\xc00̨̩\xc0\x13\xc0\x14\x00\
x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\xaa\xaa\x00\x00\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00\n\x00\n\x00\bjj\x00\x1d\x00\x17\x00\x18\x00\v\x00\x02\x01\x00\x00#\x00\x00\x00\x10\x00\x0e\x00\f\x02h2\bhttp/1.1\x00\x05\x00\x05\x01\x00\x00\x00\
x00\x00\r\x00\x14\x00\x12\x04\x03\b\x04\x04\x01\x05\x03\b\x05\x05\x01\b\x06\x06\x01"..."\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
```

docker-compose.yml
```
version: '3.3'
services:
  frigate:
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml:ro
      - /mnt/nvr/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      # - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "1883:1883"
      - "554:554"
     
  nginx:
    restart: unless-stopped
    depends_on: 
      - frigate
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/authelia:/etc/nginx/authelia
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 5005:443

  authelia:
    image: authelia/authelia
    volumes:
      - ./authelia:/config
    ports:
      - 9091:9091  
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
```

Authelia config:
```
---
server.host: 0.0.0.0
server.port: 9091
log.level: debug

jwt_secret: <redacted>

default_redirection_url: "http://192.168.0.xxx:9091"

totp:
  issuer: "authelia.com"
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "https://192.168.0.xxx:5005"
      policy: one_factor

session:
  name: authelia_session
  secret: TVPMIcDFbBwhnW3kLJzKhdjeHhtqisr7m28FgRY8oLh2A4lwuV2jV2ZGdGbh4aa
  expiration: 3600
  inactivity: 300
  domain: "http://192.168.0.xxx:5005"
...
```

Frigate nginx conf
```
server {
    listen 443 ssl http2;
    include /etc/nginx/authelia/authelia.conf;

    ssl_certificate ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key ssl/private/nginx-selfsigned.key;

    location / {
        set $upstream_frigate http://frigate:5000;
        proxy_pass $upstream_frigate;
        # proxy_set_header Host $server_name;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_headers_hash_max_size 1024;
        proxy_headers_hash_bucket_size 128;

        include /etc/nginx/authelia/auth.conf;
        include /etc/nginx/authelia/proxy.conf;
    }
}
```

**Comment by nightah** [comment]
Looks like issues with TLS termination, it might be worthwhile sharing the Nginx configuration both for Authelia and also Frigate.

**Comment by mike-lloyd03** [comment]
I included the Frigate nginx config in the original post but I screwed it up trying to use the `details` html flags. I actually originally wasn't using an nginx config for Authelia, I was just setting the port of the Authelia container as the  target.

But that's probably not right so I wrote this up today. It's listening on 9092 and proxy-passes to 9091 which is the exposed port of the Authelia container. Still having trouble getting it to work though. (I updated the Authelia config files to point to port 9092 as well.)

```
server {
    listen 9092 ssl http2;

    ssl_certificate ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key ssl/private/nginx-selfsigned.key;

    location / {
        set $upstream_authelia http://authelia:9091;
        proxy_pass $upstream_authelia;
        include /etc/nginx/authelia/proxy.conf;
    }
}
```

**Comment by nightah** [comment]
```
domain: "http://192.168.0.xxx:5005"
```

Firstly your domain should be the root domain `192.168.0.xxx`, so no ports or `http//` etc. There's no reason to hide your last octet too since that's a private range.

Just keep in mind if that's your domain it means all of the Authelia protected endpoints need to sit under the same IP, ie they need to be reverse proxied through nginx.

Once you've fixed that up can you provide the contents of `/etc/nginx/authelia/authelia.conf`?

**Comment by mike-lloyd03** [comment]
Yeah maybe masking private IPs is a bit excessive.

I'll update the `domain` line and give it a shot later tonight but basically I'm only using this Authelia instance to protect endpoints inside the docker network, (only the Frigate service.) So maybe the domain should be the CIDR range of the docker network (172.x.x.x).

/etc/nginx/authelia/authelia.conf
```
set $upstream_authelia https://192.168.0.101:9092/api/verify;

# Virtual endpoint created by nginx to forward auth requests.
location /authelia {
    internal;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # [REQUIRED] Needed by Authelia to check authorizations of the resource.
    # Provide either X-Original-URL and X-Forwarded-Proto or
    # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
    # Those headers will be used by Authelia to deduce the target url of the user.
    # Basic Proxy Config
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
```

**Comment by nightah** [comment]
> I'll update the `domain` line and give it a shot later tonight but basically I'm only using this Authelia instance to protect endpoints inside the docker network, (only the Frigate service.) So maybe the domain should be the CIDR range of the docker network (172.x.x.x).

That's fine, but your domain in Authelia needs to match whatever location the end-user is going to be visiting to get to said endpoints. So if it's going to be accessing Frigate through `https://192.168.0.101` it should be set to `192.168.0.101`. Remember the `https` is important because Authelia can only protect and transmit cookies over a secure connection.

You can change the above to reference `http://192.168.0.101:9091/api/verify` it's an interval endpoint so it doesn't need the TLS termination behind Nginx.

Can you provide `/etc/nginx/authelia/auth.conf` too please?

**Comment by mike-lloyd03** [comment]
Okay awesome. This is making a bit more sense now.

/etc/nginx/authelia/auth.conf
```
# Basic Authelia Config
# Send a subsequent request to Authelia to verify if the user is authenticated
# and has the right permissions to access the resource.
auth_request /authelia;
# Set the `target_url` variable based on the request. It will be used to build the portal
# URL with the correct redirection parameter.
auth_request_set $target_url $scheme://$http_host$request_uri;
# Set the X-Forwarded-User and X-Forwarded-Groups with the headers
# returned by Authelia for the backends which can consume them.
# This is not safe, as the backend must make sure that they come from the
# proxy. In the future, it's gonna be safe to just use OAuth.
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name $name;
proxy_set_header Remote-Email $email;
# If Authelia returns 401, then nginx redirects the user to the login portal.
# If it returns 200, then the request pass through to the backend.
# For other type of errors, nginx will handle them as usual.
error_page 401 =302 https://192.168.0.101:9092/?rd=$target_url;
```

**Comment by nightah** [comment]
That looks fine, is there a reason why everything is published on a different port?
Do you not have access to port 443 on that host?

**Comment by mike-lloyd03** [comment]
Yeah I changed some ports around to add nginx over Authelia. Here's the breakdown right now

Frigate container:
- Listening on port 5000 inside docker network only

Authelia container:
- Listening on port 9091 inside docker network only

Nginx container:
- Listening on 5005 over TLS and proxy-pass to `frigate:5000`
- Listening on 9092 over TLS and proxy-pass to `authelia:9091`

**Comment by nightah** [comment]
It would just make it much simpler if you exposed Nginx on 443 and used hostnames to determine the backend service.

You can achieve this on your client machines by setting the IP address of the Nginx host in your hosts file which incidentally also gives you security by obscurity at another level because anybody that doesn't have those hosts configured won't be able to get to your backend services.

**Comment by mike-lloyd03** [comment]
This machine also has other public facing services so 443 is already in use. But yeah I think I'm mixing up where I should be using the host machine's IP (192.168.0.101) and the individual docker containers' hostnames.

**Comment by mike-lloyd03** [comment]
Okay making the changes you've suggested, when I access `https://192.168.0.101:5005`, I get redirected to `https://192.168.0.101:9092/?rd=https://192.168.0.101:5005/` but then I get 502 error. Nginx log says:

```
nginx_1     | 2021/09/09 05:52:36 [error] 22#22: *7 no resolver defined to resolve authelia, client: 192.168.0.158, server: , request: "GET /?rd=https://192.168.0.101:5005/ HTTP/2.0", host: "192.168.0.101:9092"
nginx_1     | 192.168.0.158 - - [09/Sep/2021:05:52:36 +0000] "GET /?rd=https://192.168.0.101:5005/ HTTP/2.0" 502 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.58 Safari/537.36" "-"
nginx_1     | 2021/09/09 05:52:36 [error] 22#22: *7 no resolver defined to resolve authelia, client: 192.168.0.158, server: , request: "GET /favicon.ico HTTP/2.0", host: "192.168.0.101:9092", referrer: "https://192.168.0.101:9092/?rd=https://192.168.0.101:5005/"
```

**Comment by nightah** [comment]
Is both Authelia and Nginx in the same Docker network?

Also put the following line in your `nginx.conf`:
```nginx
resolver 127.0.0.11 ipv6=off  valid=30s;

**Comment by mike-lloyd03** [comment]
Yes the Docker network has Frigate, Nginx, Authelia and Redis in the same
network.

**Comment by mike-lloyd03** [comment]
Okay I think we're getting somewhere. I'm now properly getting the Authelia login page when going to 192.168.0.101:5005, but after authenticating, I'm getting a 403 error.

**Comment by nightah** [comment]
Probably worth providing the outputs of the Authelia and nginx logs when that occurs (make sure you have debug logging turned on for Authelia).

**Comment by mike-lloyd03** [comment]
Log entries:

```
authelia_1  | time="2021-09-11T13:48:16-07:00" level=info msg="Access to https://192.168.0.101:5005/ is forbidden to user mike" method=GET path=/api/verify remote_ip=192.168.0.158
nginx_1     | 192.168.0.158 - - [11/Sep/2021:13:48:16 -0700] "GET / HTTP/2.0" 403 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.58 Safari/537.36" "-"
authelia_1  | time="2021-09-11T13:48:16-07:00" level=info msg="Access to https://192.168.0.101:5005/favicon.ico is forbidden to user mike" method=GET path=/api/verify remote_ip=192.168.0.158
nginx_1     | 192.168.0.158 - - [11/Sep/2021:13:48:16 -0700] "GET /favicon.ico HTTP/2.0" 403 555 "https://192.168.0.101:5005/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.58 Safari/537.36" "-"
```

I've also update my `configuration.yml` file for this host:
```
access_control:                                                                                                                                                                                                                                        
  default_policy: deny                                                                                                                                                                                                                                 
  rules:                                                                                                                                                                                                                                               
    - domain: "https://192.168.0.101:5005"                                                                                                                                                                                                             
      policy: one_factor                                                                                                                                                                                                                               
      subject: "user:mike"
```
