### ISSUE TITLE
Using file notifications seems broken in the latest release

### ISSUE THREAD

**Issue by marinmo** [authelia/authelia#2436]
### Description

Using file notifications does not work; the container exits (restarts) perpetually with
```
authelia     | time="2021-10-02T15:32:32+02:00" level=error msg="Configuration: notifier: you can't configure more than one notifier, please ensure only 'smtp' or 'filesystem' is configured"
authelia     | time="2021-10-02T15:32:32+02:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

### Expected Behaviour

Authelia starts as expected.

### Reproduction Steps

Use the following configuration:
```
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
```

Start the latest authelia docker-container. Note: the configuration below used to work but broke at a time unknown to me (unknown due to unrelated reasons).

### Additional Information
configuration.yml
```
server.host: 0.0.0.0
server.port: 9091
server:
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: "authelia"
log.level: debug
default_redirection_url: https://DOMAIN.EXT
duo_api:
  hostname: redacted
  integration_key: redacted
authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 128
      parallelism: 8
access_control:
  default_policy: deny
  rules:
    - domain:
      - DOMAIN.EXT
      - "*.DOMAIN.EXT"
      policy: two_factor
session:
  name: authelia_session
  expiration: 1h
  inactivity: 15m
  remember_me_duration: 1M
  domain: DOMAIN.EXT
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
```
```
docker-compose:
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Stockholm
      - AUTHELIA_JWT_SECRET_FILE=/config/secrets/jwt
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/config/secrets/duo
      - AUTHELIA_SESSION_SECRET_FILE=/config/secrets/session
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/config/secrets/smtp
    volumes:
      - /home/docker/docker/data/authelia:/config
    restart: unless-stopped
```
