### ISSUE TITLE
LDAP auth ERROR

### ISSUE THREAD

**Issue by HsunGong** [authelia/authelia#2439]
Log Error on LDAP
```
authelia
| time="2021-10-03T11:59:08+08:00" level=fatal msg="The following providers had fatal failures during startup: user"
stack="
github.com/authelia/authelia/v4/internal/commands/root.go:186
doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:83
cmdRootRun\ngithub.com/spf13/cobra@v1.2.1/command.go:860
(*Command).execute\ngithub.com/spf13/cobra@v1.2.1/command.go:974
(*Command).ExecuteC\ngithub.com/spf13/cobra@v1.2.1/command.go:902
main\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:11
main\nruntime/proc.go:255
main\nruntime/asm_amd64.s:1581
goexit"
```

authelia config/configuration.yml
```
ldap:
    base_dn: dc=example,dc=com
    username_attribute: uid
    group_name_attribute: cn # short for cn=admins,ou=groups,dc=example,dc=com
    additional_users_dn: cn=admins
    additional_groups_dn: ou=groups
    users_filter: (&({username_attribute}={input})(objectClass=person))
    groups_filter: (&(uniquemember={dn})(objectclass=groupOfUniqueNames))
    mail_attribute: mail
    display_name_attribute: displayName
    user: admin # also tried cn=admin,dc=example,dc=com
    password: pwd
    implementation: custom
    url: ldap://192.168.1.107
    timeout: 1s
```

It works using command
```
ldapsearch -x -H ldap://192.168.1.107 -D "cn=admin,dc=xun-gong,dc=com" -w 'password' -b "dc=example,dc=com"
```
