### ISSUE TITLE
Unable to create table user_preferences

### ISSUE THREAD

**Issue by bigverm23** [authelia/authelia#2453]
### Description
Running Authelia in provided docker container, received an error message:
`time="2021-10-05T13:18:03-04:00" level=fatal msg="Unable to initialize SQL database: Unable to create table user_preferences: dial tcp 127.0.0.1:3306: connect: connection refused" stack="github.com/authelia/authelia/internal/storage/mysql_provider.go:72 NewMySQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:76               startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:121              main.func1\ngithub.com/spf13/cobra@v0.0.7/command.go:842                       (*Command).execute\ngithub.com/spf13/cobra@v0.0.7/command.go:943                       (*Command).ExecuteC\ngithub.com/spf13/cobra@v0.0.7/command.go:883                       (*Command).Execute\ngithub.com/authelia/authelia/cmd/authelia/main.go:138              main\nruntime/proc.go:203                                                main\nruntime/asm_amd64.s:1373                                           goexit"`

### Additional Information
```
server:
  host: 0.0.0.0
  port: 9091
log:
  level: warn
jwt_secret: xxxxx
default_redirection_url: xxxx
totp:
  issuer: authelia.com
  period: 30
  skew: 1
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.
access_control:
  default_policy: deny
  rules:
    - domain: xxxxxx
      policy: bypass
    - domain:
        - "*.vermillion-us.net"
        - "vermillion-us.net"
      policy: two_factor
session:
  name: authelia_session
  secret: xxxxxxx
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: xxxxx # Should match whatever your root protected domain is
  redis:
    host: redis
    port: 6379
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300
storage:
  local:
    path: /config/db.sqlite3
notifier:
  filesystem:
    filename: /config/notification.txt
duo_api:
  hostname: xxxxxxx
  integration_key: xxxxxxx

```
Compose: 
 ```
 authelia:
    container_name: authelia
    # image: authelia/authelia:latest
    image: authelia/authelia:4.21.0
    restart: always
    networks:
      - traefik_web
    volumes:
      - $DOCKERDIR/docker/authelia:/config
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=HostHeader(`authelia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - $USERDIR/docker/redis:/data
    networks:
      - traefik_web
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - TZ=$TZ
```
