### ISSUE TITLE
Traffic Denied on Wifi/VPN, but allowed on Host Machine

### ISSUE THREAD

**Issue by bigverm23** [authelia/authelia#2456]
### Description

Authelia running in Docker Compose, when navigating to a site like portainer.mydomain.net from the host machine (10.0.0.12), Authelia works as expected (requires login, then Duo push notification for approval, then redirect to portainer.mydomain.net.

When navigating to same site from VPN(10.13.13.1), Authelia denies the request.

Logs: please notice the first line is logged when accessing from LAN 2nd line is logged when accessing from VPN...why is the username and groups blank when coming from wifi devices?
```
today at 9:04:42 PM time="2021-10-05T21:04:42-04:00" level=debug msg="Check authorization of subject username=USER groups=admins,dev ip=publicIP and object https://portainer.mydomain.net/api/endpoint_groups (method GET)."
today at 11:30:26 AM time="2021-10-06T11:30:26-04:00" level=debug msg="Check authorization of subject username= groups= ip=2600:387:c:5112::100 and object https:/portainer.mydomain.net/ (method GET)."
today at 11:30:26 AM time="2021-10-06T11:30:26-04:00" level=info msg="Access to https://lidarr.mydomain.net/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://authelia.mydomain.net?rd=https%3A%2F%2Fportainer.mydomain.net%2F&rm=GET" method=GET path=/api/verify remote_ip="2600:387:c:5112::100"
```
Configuration.yml > Access Control
```
access_control:
  default_policy: deny
  rules:
  - domain: authelia.mydomain.net
    policy: bypass
  - domain:
    - "*.mydomain.net"
    - "mydomain.net"
    policy: bypass
    networks:
      - 10.0.0.0/24
      - publicIP
  - domain:
    - "*.mydomain.net"
    - "mydomain.net"
    policy: two_factor
```
