### ISSUE TITLE
RegEx not working with Bitwarden Sends

### ISSUE THREAD

**Issue by Bleala** [authelia/authelia#2520]
Hello there!

I've got the following problem, that i have got my Bitwarden behind Authelia and everything is working fine.

But when i use sends i want that people can open them without authenticating against authelia, so i tried to slve this issue with a regex rule, which looks like this:

```
    - domain: "vault.example.com"
      resources:
      - "^.*send([/?].*)?$"
      policy: bypass
```

When i check this regex with [Rego](https://regoio.herokuapp.com/) it is working, so i dont get it this is not working when i try to open a send, everytime i have to login to authelia

Default policy is deny, default domain policy (example.com and *.example.com) is two_factor.

Rest of my bitwarden config looks like this (This way i can access my bitwarden with the different apps, but web login is behind two_factor and admin page is not accessible at all:
```
      # Vaultwarden
    - domain: "vault.example.com"
      resources:
      - "^.*send([/?].*)?$"
      policy: bypass
    - domain: "vault.example.com"
      resources:
      - "^/admin([/?].*)?$"
      policy: deny
    - domain: "vault.example.com"
      resources:
      - "^/api/verify([/?].*)?$"
      policy: bypass
    - domain: "vault.example.com"
      resources:
      - "^/([/?].*)?$"
      policy: two_factor
    - domain: vault.example.com
      policy: bypass
```

i also tried to delete everything related to bitwarden and just set the `send` bypass, so `vault.example.com` would be two_factor (because of the default) and sends should be bypassed, but this is working neither.

Does someone has an answer for me?

Greetings
