### ISSUE TITLE
Using apps outside the authelia stack

### ISSUE THREAD

**Issue by dynamicat** [authelia/authelia#2530]
I have traefik, portainer and authelia bundled together in the same docker-compose file which works great.  I have some other apps that share the same network space and are also going through traefik but I want to ensure I have 2FA prior to accessing these apps too.  For example I am using bazarr and here is the config:

```yaml
---
version: "3.3"

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - bazarr_config:/config
      - /mnt/plex/complete/movies:/movies
      - /mnt/plex/complete/tv:/tv
    restart: always
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bazarr-rtr.entrypoints=https"
      - "traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.mydomain.com`)"
      - "traefik.http.routers.bazarr-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr-svc"
      - "traefik.http.services.bazarr-svc.loadbalancer.server.port=6767"
      - "traefik.port=6767"
      - 'traefik.http.routers.bazarr.middlewares=authelia@docker'

networks:
  t2_proxy:
    external: true

volumes:
  bazarr_config:
```

Portainer uses authelia no problem but I cannot see to get bazarr to work at all.  When I navigate to the url https://bazarr.mydomain.com I am taken to the website without any challenge from 2FA.

Can you see anything wrong with my config?
