### ISSUE TITLE
Failed to create middleware keys: middleware authelia/chain-authelia-auth is not in the IngressRoute namespace

### ISSUE THREAD

**Issue by johnynfulleffect** [authelia/authelia#2551]
### Description

Installed via Helm.  Using [this](https://gist.github.com/johnynfulleffect/6ac4601848baaec1091f957dae10d52e) values.yaml

### Expected Behaviour

When adding a middleware to protect an IngressRoute, it should work, not show this error in Traefik:

```
level=error msg="Failed to create middleware keys: middleware authelia/authelia-chain-authelia-auth is not in the IngressRoute namespace homebridge" providerName=kubernetescrd ingress=homebridge namespace=homebridge
```

Ingress Route:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homebridge
  namespace: homebridge
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homebridge.local.example.tech`)
      kind: Rule
      services:
        - kind: Service
          name: homebridge
          namespace: homebridge
          port: 8581
          scheme: http
      middlewares:
      - name: chain-authelia-auth
        namespace: authelia
```

### Reproduction Steps

-Install via helm with values.yaml above
-Configure DNS to work with authelia ingress route and validate login
-Configure an ingress route to use the provided middleware:

```
Release "authelia" has been upgraded. Happy Helming!
NAME: authelia
LAST DEPLOYED: Fri Oct 29 15:54:15 2021
NAMESPACE: authelia
STATUS: deployed
REVISION: 7
TEST SUITE: None
NOTES:
Thank you for installing the authelia-0.6.3 Chart.

Please report any chart issues at https://github.com/authelia/chartrepo/issues and any application issues at https://github.com/authelia/authelia/issues.

The helm release name is authelia.
You have selected the Traefik CRD to deploy the ingress.

If you wish to protect an IngressRoute apply the following middleware:

    middlewares:
    - name: chain-authelia-auth
      namespace: authelia

If you wish to protect a regular Ingress apply the following annotation:

    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: authelia-chain-authelia@kubernetescrd

You should be able to access Authelia soon via https://auth.local.example.tech if everything is configured correctly in your values and the DNS record points to the correct location.You can also direct your ingress to use the following path for forward auth: http://authelia.authelia.authelia.svc.cluster.local/api/verify?rd=https://auth.local.example.tech/.
```

### Additional Information

Rancher k3s, 4 node cluster on Ubuntu 21.04 Server (5.11.0-38-generic)
kubernetes v1.21.5+k3s1
Container runtime: containerd://1.4.9-k3s1
