### ISSUE TITLE
Bypass Nextcloud App

### ISSUE THREAD

**Issue by MRobi1** [authelia/authelia#2557]
I've got Authelia up and running and trying to use it along with Nextcloud. The Android/iOS apps don't support the redirect so I'm trying to setup a bypass rule for it, and have it bypassing the use of the api path but I can't seem to login via the app unless I fully bypass nextcloud.

Here's my config:
```
  rules:
    - domain: nextcloud.mydomain.xyz
      policy: bypass
      resources:
      - '^/api\?.*$'
    - domain: nextcloud.mydomain.xyz
      policy: two_factor
```

And when I try to access via the app I get this in the logs.
`time="2021-11-01T21:56:35-03:00" level=info msg="Access to https://nextcloud.mydomain.xyz/status.php (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=123.456.789.00"`

Anybody tackle this one yet?
