### ISSUE TITLE
Question: Basic auth and 2FA for different urls

### ISSUE THREAD

**Issue by 0xERR0R** [authelia/authelia#2560]
I have some application with web ui and a REST api ("/api/" url) for mobile clients. I want to use authelia to protect **all** urls of the app. I configured authelia basic-auth middleware (traefik) for the docker-container. Now I'm able to use "single_factor" for the web-ui (basic auth without nice login page) and REST.

Can I configure authelia to use 2FA for the web ui and single_factor only for the REST api? Somehow: "/api" -> single_factor basic auth, "/*" -> 2 factor with login page?

**Comment by james-d-elliott** [comment]
Yeah, you just need two rules, one with the api in the resources (above) the other rule for everything else (without a resources rule).

**Comment by 0xERR0R** [comment]
I tried it, but it doesn't work. If I open the web ui, I get the basic auth prompt, after entering the user/pw, it appears again. My config:

```yaml
access_control:
  default_policy: deny
    rules:
    - domain: app.example.com
      policy: one_factor
      resources:
        - "^/api/.*"
      
    - domain: app.example.com
       policy: two_factor
```

On docker container, I configured "authelia-basic@docker" middleware (label for traefik).

REST api on the mobile app works.

I think, the issue is the 2fa, authelia-basic middleware wants only basic auth, there is no prompt for the OTP.

My expectation is: authelia shows the basic auth prompt, I enter the user/pw and authelia redirects to the page where I should enter the OTP token
