### ISSUE TITLE
New Update Broke Container

### ISSUE THREAD

**Issue by lsultana98** [authelia/authelia#2680]
I am having an issue since the update. The container will not start. Logs are showing the following.

![image](https://user-images.githubusercontent.com/45834283/144701359-ad525cfa-ddcb-439f-abbd-70c53452b9ed.png)

Thank you in advance.

**Comment by james-d-elliott** [comment]
See this section of the template: https://github.com/authelia/authelia/blob/master/config.template.yml#L33-L88

```yaml
host: 0.0.0.0
port: 9091
log_level: info
```

Was replaced by:

```yaml
server:
  host: 0.0.0.0
  port: 9091
log:
  level: info
```

Additionally you will need to generate a random string, we are recommending the string is at least 64 characters, but the absolute minimum is 20. That string goes here:

https://github.com/authelia/authelia/blob/master/config.template.yml#L527

So it looks like:

```yaml
storage:
  encryption_key: <random string>
```
