### ISSUE TITLE
Errors on bare metal installation

### ISSUE THREAD

**Issue by MrOzean** [authelia/authelia#2684]
### Description
I have a simple baremetal installation of two Debian LXC containers in the home LAN:
+ Container with local DNS name `sso.authority.local` which host only Authelia as `systemd` service 
+ Container with several local DNS names (`*.home.local`) with a few useful services that I want to protect. Services are managed by Traefik v2 using hostname.  

HTTPS provided by self-signed certs and self-hosted ACME
For example I try to protect  `syncthing.home.local`  

Traefik config
```yml
http: 
  routers: 
    to-syncthing: 
      rule: "Host(`syncthing.home.local`)"
      service: syncthing
      tls:  
        certResolver: acmeresolver 
      middlewares:
        - "compressor"
        - "syncthing-auth"
        
     
    to-dlna:
      rule: "Host(`dlna.home.local`)"
      ...

   
  services: 
    syncthing: 
      loadBalancer: 
        servers: 
          - url: "http://localhost:8384" 
    
    dlna: 
      ...

  middlewares:
    compressor:
      compress: {}

    syncthing-auth:
      forwardAuth:
        address: "https://sso.authority.local/api/verify?rd=https://syncthing.home.local"
        trustForwardHeader: true
        tls:
          insecureSkipVerify: true # for test 
        authResponseHeaders:       
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email     
 ```

Authelia config
```yml
theme: auto
jwt_secret: secret 


server:
 
  host: 0.0.0.0
  port: 443
  path: ""

  read_buffer_size: 32768
  write_buffer_size: 32768

  enable_pprof: false

  enable_expvars: false

  disable_healthcheck: false

  tls: 
    key: "/media/sso/sso.authority.local.key"

    certificate: "/media/sso/sso.authority.local.pem"

log:
  
  level: trace

totp:
  issuer: "sso.authority.local"
  period: 30
  skew: 1
 
authentication_backend: 
  disable_reset_password: true
  refresh_interval: 5m
  file:
    path: /media/sso/authelia/users_database.yml
    password:
      algorithm: argon2id
      iterations: 2
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

session:
  name: oauth_session
  domain: "sso.authority.local"
  same_site: lax
  secret:  secret 
  expiration: 1h
  activity: 5m
  remember_me_duration: 2M

regulation:
  max_retries: 3
  find_time: 3m
  ban_time: 8m

storage:
  local:
    path: /media/sso/authelia/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /media/sso/authelia/notification.txt

access_control:
  default_policy: two_factor
  rules:
    - domain: "syncthing.home.local"
      subject:
        - "group:home-syncthing"
      policy: one_factor
```
### Operation
Tryes to open `syncthing.home.local` in browser gives white page with `Unauthorized` word, and this Authelia log 

```log
INFO[0000] Authelia v4.32.2 is starting
INFO[0000] Log severity set to trace
TRAC[0000] Starting scan of directory  for certificates
TRAC[0000] Finished scan of directory  for certificates
DEBU[0000] Storage schema is being checked to verify it is up to date
DEBU[0000] Storage schema is up to date
INFO[0000] Listening for TLS connections on '0.0.0.0:443' path '/'
TRAC[0004] Request hit                                   method=GET path=/api/verify remote_ip=192.168.1.120
TRAC[0004] Headers=GET /api/verify?rd=https://syncthing.home.local HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Host: sso.authority.local
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: ru,en-US;q=0.9,en;q=0.8
Cache-Control: no-cache
Pragma: no-cache
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-Gpc: 1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 192.168.1.120
X-Forwarded-Host: syncthing.home.local
X-Forwarded-Method: GET
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: home-server
X-Forwarded-Uri: /
X-Real-Ip: 192.168.1.120
  method=GET path=/api/verify remote_ip=192.168.1.120
TRAC[0004] Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL  method=GET path=/api/verify remote_ip=192.168.1.120
ERRO[0004] Target URL https://syncthing.home.local/ is not under the protected domain sso.authority.local  method=GET path=/api/verify remote_ip=192.168.1.120 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:467     VerifyGet.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.3/router.go:414
                (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.30.0/server.go:2266                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.30.0/workerpool.go:223                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.30.0/workerpool.go:195                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581                                                    goexit"
TRAC[0004] Replied (status=401)                          method=GET path=/api/verify remote_ip=192.168.1.120
TRAC[0004] Request hit                                   method=GET path=/api/verify remote_ip=192.168.1.120
TRAC[0004] Headers=GET /api/verify?rd=https://syncthing.home.local HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Host: sso.authority.local
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: ru,en-US;q=0.9,en;q=0.8
Cache-Control: no-cache
Pragma: no-cache
Referer: https://syncthing.home.local/
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Sec-Gpc: 1
X-Forwarded-For: 192.168.1.120
X-Forwarded-Host: syncthing.home.local
X-Forwarded-Method: GET
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: home-server
X-Forwarded-Uri: /favicon.ico
X-Real-Ip: 192.168.1.120
  method=GET path=/api/verify remote_ip=192.168.1.120
TRAC[0004] Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL  method=GET path=/api/verify remote_ip=192.168.1.120
ERRO[0004] Target URL https://syncthing.home.local/favicon.ico is not under the protected domain sso.authority.local  method=GET path=/api/verify remote_ip=192.168.1.120 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:467     VerifyGet.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.3/router.go:414
                           (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.30.0/server.go:2266                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.30.0/workerpool.go:223                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.30.0/workerpool.go:195
  (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581                                                    goexit"
TRAC[0004] Replied (status=401)                          method=GET path=/api/verify remote_ip=192.168.1.120
```

OK, error speak `Target URL https://syncthing.home.local is not under the protected domain`. Try change `session.domain` to 
+ local
+ authority.local
+ home.local
And change hostname `syncthing.home.local` to `syncthing.authority.local` on DNS and Traefik config,in any combination.

Open in browser gives `ERR_TOO_MANY_REDIRECTS` and giant [Authelia log](https://gist.github.com/MrOzean/d9441c304713aa7a600f0c2be22dde5e) with recursive redirects until 
`server.write_buffer_size` is exceeded

**Comment by james-d-elliott** [comment]
```yaml
    syncthing-auth:
      forwardAuth:
        address: "https://sso.authority.local/api/verify?rd=https://syncthing.home.local"
````

The address looks wrong. Is authelia and traefik installed on the same host? If so it should be `http://localhost:9091/api/verify?rd=https://sso.home.local`

Also what is the diff between home.local and authority.local?

**Comment by MrOzean** [comment]
Different hosts  
I have 2 LXC containers, i.e. lightweight Debian VM's on hypervisor, bridged into home LAN
+ First VM with static IP and a bunch of hostnames `home.local`, `syncthing.home.local`, `dlna.home.local` etc. Traefik & services running here
+ And second VM , with static IP and hostname `sso.authority.local` which running only Authelia on 443 port

Host `authority.local`  host doesn't exist

**Comment by nightah** [comment]
@MrOzean the issue here is that the domains you are attempting to protect with Authelia don't share the same base domain as what is set in Authelia.

The `session.domain` configuration option in Authelia needs to be a base domain that the protected sites and Authelia itself share because that's where the session cookie is set.

If you publish Authelia at `authority.home.local` or `sso.authority.home.local` and have your `session.domain` set to `home.local` this should resolve the domain/cookie issue. There could be other misconfiguration that isn't immediately noticeable at the moment but I'd suggest the above at the first pass.

**Comment by MrOzean** [comment]
Hmm, OK, another try this variant.
+ Change hostname `sso.authority.local` to `sso.home.local`. Browser & `home.local` resolves it correct  

![Screenshot_1](https://user-images.githubusercontent.com/21057595/145050166-9b412ebe-eb18-4175-b69e-d171a6884d07.png)
![Screenshot_2](https://user-images.githubusercontent.com/21057595/145050169-be686b59-35a3-437a-982c-180b5867c8e1.png)

+ Set in Authelia config `session.domain: "home.local"`, `totp.issuer: "sso.home.local"`, and disable HTTPS just in case, new config
```yml
theme: auto
jwt_secret: secret

server:
  host: 0.0.0.0
  port: 9000
  path: ""
 
  read_buffer_size: 327680
  write_buffer_size: 327680
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

log:
  level: trace
  format: text

totp:
  issuer: "sso.home.local"
  period: 30
  skew: 1
  
authentication_backend:
  disable_reset_password: true
  refresh_interval: 5m

  file:
    path: /media/sso/authelia/users_database.yml
    password:
      algorithm: argon2id
      iterations: 2
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

session:
  name: oauth_session
  domain: "home.local"
  same_site: lax
  secret: secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M

regulation:
  max_retries: 3
  find_time: 3m
  ban_time: 8m

storage:
  local:
    path: /media/sso/authelia/db.sqlite3
notifier:
  disable_startup_check: false
  filesystem:
    filename: /media/sso/authelia/notification.txt
```
+ Update Traefik config
```yml
 syncthing-auth:
      forwardAuth:
        address: "http://sso.home.local:9000/api/verify?rd=https://syncthing.home.local"
        trustForwardHeader: true
        tls:
          insecureSkipVerify: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
```
Open in browser gives `ERR_TOO_MANY_REDIRECTS` , [Authelia log](https://gist.github.com/MrOzean/e3337072a6e01cf0edf80edb5db46e09/raw/9076045b37aae7748d64c28a1346b0b6f96e1ca2/auhelia_error.log) with recursive redirects until
`server.write_buffer_size` is exceeded  

![Screenshot_3](https://user-images.githubusercontent.com/21057595/145058560-f07c6d56-3caf-4610-9dde-fa29a47b9e49.png)

**Comment by james-d-elliott** [comment]
Open the dev tools and check the value of the location header of each of those redirects for me? Is authelia redirecting to itself?

**Comment by nightah** [comment]
You've got a configuration issue with your forwardAuth address.

The rd param should forward to your auth portal, not the end resource.

```yaml
 syncthing-auth:
      forwardAuth:
        address: "http://sso.home.local:9000/api/verify?rd=https://syncthing.home.local"
        trustForwardHeader: true
        tls:
          insecureSkipVerify: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
```

Should be:

```yaml
 syncthing-auth:
      forwardAuth:
        address: "http://sso.home.local:9000/api/verify?rd=https://sso.home.local"
        trustForwardHeader: true
        tls:
          insecureSkipVerify: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
```
