### ISSUE TITLE
Add matcher for query arguments in ACL rules

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#2708]
### Description

I am attempting to restrict access to resource which due to the nature of application requires me to match an GET argument. Now the first ACL ruleset I sketched was following: 

```
    - domain: app.example.com
      subject: "group:Admins"
      resources:
      - "^/path/to/\\?key=sensitive-page"

    - domain: app.example.com
      policy: deny
      resources:
      - "^/path/to/\\?key=sensitive-page"

    - domain: app.example.com
      policy: bypass
```

Now the problem is that user can manipulate the order of GET arguments so first two rules are not matched, and `key=sensitive-page` resource would be matched by the last ACL rule.

### Expected Behaviour

I think the only realistic option here is to allow Authelia to parse and sanitize the GET arguments and have separate section for matching GET arguments a'a like this:

```
    - domain: app.example.com
      subject: "group:Admins"
      arguments:
         key: "^sensitive-page"
```

Expecting Authelia admin to come up with all the various ways URL can be constructed is not realistic.

**Comment by james-d-elliott** [comment]
We're probably able to add this in the future but I will discuss it with the team, guess I need to start tagging issues we need to talk about, Within all likelihood it will be in a major version bump because it's logical to extract this match functionality out if anything, and make it stand on its own. 

You can match query parameters in any order with syntax similar to this:

```yaml
    - domain: app.example.com
      policy: deny
      resources:
      - "^/path/to/?(\\?|.*&)key=sensitive-page"
```

If I were to do anything in the near future it'd probably be figuring out the ACL checking functionality since this would help alleviate the stress of figuring out if it works. #2112

**Comment by laurivosandi** [comment]
Feel free to lower priority of this, realistically if you use third party app you can't really know all the corner cases to properly protect the application and if it's homebrew application you should just use path prefix based or some other more straightforward approach

**Comment by james-d-elliott** [comment]
```yaml
access_control:
  rules:
  - query:
    - 
      - name: admin
        value: ["true"]
      - name: dashboard  ## logical OR
        value_regex: "^(admin|manager)$"
    -  ## logical AND
      - name: token
        value_regex: "^$"
```

This is what I am playing with as the most logical syntax to get complete coverage over this, not entirely sure I like it due to the double indentation. I also think we need to potentially consider an absent option.
