### ISSUE TITLE
password policy: password history

### ISSUE THREAD

**Issue by mind-ar** [authelia/authelia#2731]
## Feature Request
Implement password history via configuration

### Description
this functionality will allow administrators to limit the reuse of passwords by users
this feature depends on https://github.com/authelia/authelia/pull/2723
questions:
* where to store password history (file, database, etc)?
* should store full hashed password, or store part of hash (ie first 10 digits)

**Comment by james-d-elliott** [comment]
First of all would be interested in what both @nightah  and @clems4ever have to say about this one. However my opinion follows.

The location would be in the users file: https://www.authelia.com/docs/configuration/authentication/file.html#format

Regarding the hashed password, to be clear though I think it's already understood, we actually use random salts in all of our passwords, so just storing the hash is not sufficient, has to be the entire parameterized string including the hash. Also we'd want to store the whole string, as hashing it multiple times is likely to be very costly. It is also not possible to store the users first password except for storing the whole password. 

For LDAP we should rely on the back end to properly implement this and properly utilize it. Otherwise we're implementing a solution that can just be bypassed.

**Comment by mind-ar** [comment]
> The location would be in the users file: https://www.authelia.com/docs/configuration/authentication/file.html#format

something like this?
```yaml
  john:
    displayname: "John Doe"
    password: "$argon2id$v=19$m=65536,t=3,p=2$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t4MFFSs+iM"
    email: john.doe@authelia.com
    groups:
      - admins
      - dev
    password_history: 
      - "$argon2id$v=19$m=65536,t=3,p=2$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t4MFFSs+iM"
      - ...
      - ...
```

> For LDAP we should rely on the back end to properly implement this and properly utilize it. Otherwise we're implementing a solution that can just be bypassed or could allow bypass of an already existing password history policy.

although I think you can add an extra layer of security, there is no place to store history when using ldap.
if you agree, I can implement password history only for file storage

the idea would be something like this:
* add a new parameter in the `password_policy` section: `password_history_length`
* this params tells how many passwords are remembered by authelia
* if a user's entered password is in the list, the action is rejected.

Docs may advise that this param apply only to file storage
