### ISSUE TITLE
OIDC: redirect_uris for owncloud iOS app

### ISSUE THREAD

**Issue by vx3r** [authelia/authelia#2742]
### Description
ownCloud iOS app expects client `redirect_uris` to be `oc://ios.owncloud.com` according to the [doc](https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#redirect-uris).
Authelia accepts only http and https in `redirect_uris`, according to the [doc](https://www.authelia.com/docs/configuration/identity-providers/oidc.html#redirect_uris) .

### Expected Behaviour
OIDC login from iOS app

### Reproduction Steps
Configure owncloud to use authelia as IDP, add default iOS client as described [here](https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#owncloud-desktop-and-mobile-clients) and start login flow from iOS app

### Additional Information

Adding the `oc` uri sheme must resolve the issue, here is the full request coming from iOS app:
`GET/api/oidc/authorize?prompt=consent&response_type=code&code_challenge_method=S256&code_challenge=z7d2cS0bP6Sz03hDpeaiiJXMjQ3RgiAVfFEhVgQ4KFg&scope=openid offline_access email profile&redirect_uri=oc://ios.owncloud.com&client_id=mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1HTTP/2.0 "Mozilla/5.0(iPhone;CPUiPhoneOS15_1likeMacOSX)AppleWebKit/605.1.15(KHTML,likeGecko)Version/15.1Mobile/15E148Safari/604.1"`

thank you

**Comment by james-d-elliott** [comment]
Marking this as a feature request as per the OIDC specification there is only mentions of http schemes, https schemes, and the urn callback. In fact several flows are *required* to use a https redirect_uri scheme. Example:

https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest

**Comment by clems4ever** [comment]
@james-d-elliott , this [RFC](https://datatracker.ietf.org/doc/html/rfc8252#section-7.1), which is the current best practice, describes private-use URI schemes so I think it's fine to consider supporting custom schemes in Authelia.

**Comment by vx3r** [comment]
Thank you all for your support on adding the feature.
It has been merged into main branch but i am still unable to start authelia with this redirect url:
```
    clients:
       -
        id: mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1
        description: ownCloud iOS
        secret: KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx
        public: false
        authorization_policy: two_factor
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
          - offline_access
        redirect_uris:
          - oc://ios.owncloud.com
        grant_types:
          - refresh_token
          - authorization_code
        userinfo_signing_algorithm: none
```
getting following error when restarting authelia:
```
authelia                      | time="2022-07-13T11:02:06+02:00" level=error msg="Configuration: identity_providers: oidc: client 'mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1': option 'redirect_uris' has an invalid value: redirect uri 'oc://ios.owncloud.com' must have a scheme of 'http' or 'https' but 'oc' is configured"
```
with latest version:
```
❯ docker-compose images authelia
Container      Repository        Tag       Image Id       Size
----------------------------------------------------------------
authelia    authelia/authelia   latest   e189cf1abb7a   49.55 MB
```
Am i missing something here ?

thank you

**Comment by Gatherix** [comment]
@vx3r Did you ever find success with this?

**Comment by vx3r** [comment]
@Gatherix nop never worked for me

**Comment by james-d-elliott** [comment]
Feel free to open this as a discussion as it was tested by a user

**Comment by helgeklein** [comment]
I can confirm that the redirect URI `oc://android.owncloud.com` used by ownCloud's Android app works correctly with Authelia 4.37.5.

**Comment by alceasan** [comment]
> I can confirm that the redirect URI `oc://android.owncloud.com` used by ownCloud's Android app works correctly with Authelia 4.37.5.

@helgeklein, could you please post your configuration? I'm trying to get OCIS working with Authelia. So far I have been able to do it with the web client following [this guide](https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/#sso-via-authelia-owncloud-openid-connect-authentication) but I'm having issues with the owncloud android app login. The app redirects with the web browser to my authelia site, but after a successful login there is no redirection to the app, it just stays on the "Authenticated" authelia website and never goes back to the owncloud app.

This is my authelia config for the android app:

```
      - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
        description: ownCloud Android app
        secret: 'dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD'
        scopes:
          - openid
          - groups
          - profile
          - email
          - offline_access
        redirect_uris:
          - oc://android.owncloud.com
        grant_types:
          - refresh_token
          - authorization_code
        userinfo_signing_algorithm: none
```

**Comment by helgeklein** [comment]
@alceasan I've described my entire home server configuration in a very detailed series of articles. The following two articles cover Authelia:

- [Authelia & lldap: Authentication, SSO, User Management & Password Reset for Home Networks](https://helgeklein.com/blog/authentication-sso-user-management-password-reset-for-home-networks/)
- [ownCloud Infinite Scale With OpenID Connect Authentication for Home Networks](https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/)

**Comment by C8opmBM** [comment]
Is there a working alternative for caddy?  I'm currently using SWAG (linuxserver) and I've managed with trial and error to make it work for both web and android, but I'm having issues with the desktop. 

I'm using @helgeklein method, the problematic one is the desktop. It redirects me with error to `httpS://127xxxx`, even though I have it set correctly to `http`
The error, after I delet the S in the prototcol reads (in browser)

`Error returned from the server: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.`

@alceasan - take a look at cors, for me this was problematic. Also I used the implicit consent, to skip the consent window.
Also make sure to use the given secrets, don't change them. Also make sure you have your authelia user created first in owncloud (first without oidc, normal login, then add your oidc).
So follow the guide @helgeklein posted. It's very detailed and works, problem is, in my case with the desktop version.

```
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins: "*"
      allowed_origins_from_client_redirect_uris: false
```

These work:


      - id: ownCloud-web
        description: ownCloud web client
        public: true
        authorization_policy: two_factor
        consent_mode: implicit
        redirect_uris:
          - https://cloud.xxx.net/
          - https://cloud.xxx.net/oidc-callback.html
          - https://cloud.xxx.net/oidc-silent-redirect.html
        
      - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
        description: ownCloud Android app
        secret: 'dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD'
        scopes:
          - openid
          - groups
          - profile
          - email
          - offline_access
        redirect_uris:
          - oc://android.owncloud.com

This doesn't 


```
      - id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
        description: ownCloud desktop client
        consent_mode: implicit
        secret: 'UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh'
        scopes:
          - openid
          - groups
          - profile
          - email
          - offline_access
        redirect_uris:
          - http://127.0.0.1   # I also tried http://127.0.0.1:* - this errors out. I also tried with secure/insecure settings in ocis, no fix.
          - http://localhost
```
