### ISSUE TITLE
Checking for Ldap Activeuser Doesn't work 

### ISSUE THREAD

**Issue by farshadnick** [authelia/authelia#2743]
I have installed freeipa and authelia using Traefik.
With refresh_interval set to always, when I delete an account, the authenticated user gets redirected to login page
but when I disable an account, the user stays authenticated.

### Expected Behaviour
Cookie should get invalidated after a user is disabled in LDAP.

### Description
I have installed freeipa and authelia(Traefik) 
Authentication and all stuff works fine but when I disable an Account in my freeipa, authelia doesn't understand if the user is already signed-in (but when i delete that user authelia understand it and redirects the user to login page)

also I configured `refresh_interval` to the Always    

### Expected Behaviour
When i disable a user in my Freeipa Authelia redirects the authenticated user to login page

**Comment by james-d-elliott** [comment]
You will need to adjust your users filter to exclude disabled users from the results. Disabling users in LDAP has no special adjustment to user other than changing an attribute. We don't currently have a FreeIPA implementation to automatically do this for users however the following addition to the search filter should suffice:

`(!(nsaccountlock=TRUE))`

For example if your filter is currently like this: 

```yaml
authentication_backend:
  ldap:
    users_filter: (&({username_attribute}={input})(objectClass=person))
```

Adjust it to:


```yaml
authentication_backend:
  ldap:
    users_filter: (&({username_attribute}={input})(objectClass=person)(!(nsaccountlock=TRUE)))
```
