### ISSUE TITLE
Proposal: Email notification - Custom templates

### ISSUE THREAD

**Issue by mind-ar** [authelia/authelia#2756]
### Description
This functionality would allow administrators to modify the contents of the password reset mail
End users may not know it's authelia, and offering a more personalized message could avoid pishing spurs.

the alternatives I can think of are:
1. allow the admin to define a full mail template
2. allow the admin to define some texts (i.e. title, description, etc) 

Let me know what you think about this

### Use Case

_N/A_

**Comment by clems4ever** [comment]
Hello @mind-ar , that's a good idea and it would require a design before implementation. It's not a priority for us to implemenet at the moment though.

**Comment by mind-ar** [comment]
Hi @clems4ever , 
i have two main goals with this feature:
1. avoid too generic password reset mail 
2. add i18n for non english speakers (like me!)

![imagen](https://user-images.githubusercontent.com/10672208/148128823-cea23e85-756f-4499-9ac3-ef65dab58073.png)

Here is some idea of configuration options
```yml
notifier:
  message:
    icon: "/app/icons/acme.png"
    title: "Hello {Firstname}, reset your password"
    body: -|
      This email has been sent to you in order to validate your identity. 
      If you did not initiate the process your credentials might have been compromised. 
      You should reset your password and contact an administrator. 
    footer: "Please contact an administrator if you did not initiate the process. "
   
```
If you agree, i can take this issue 
Let me know what you think.
