### ISSUE TITLE
Stuck on redirection with basic auth in k8s ingress-nginx

### ISSUE THREAD

**Issue by Amir-Ahmad** [authelia/authelia#2769]
## Description

Hi, I've been having issues getting Authelia working with basic-auth in my single node k8s cluster, and was hoping I could get help. I'm currently using ingress-nginx as the ingress controller, and authelia is installed via the helm chart. 

There are my annotations for normal signing in, which works:
```
nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
nginx.ingress.kubernetes.io/auth-signin: https://auth.mydomain.net/
nginx.ingress.kubernetes.io/auth-url: https://auth.mydomain.net/api/verify
nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
nginx.ingress.kubernetes.io/auth-snippet: |
proxy_set_header X-Forwarded-Method $request_method;
nginx.ingress.kubernetes.io/configuration-snippet: |
proxy_set_header X-Forwarded-Method $request_method;
```

As soon as i add "?auth=basic" to the auth-url, it redirects me to the same html login, and then continually keeps redirecting: https://auth.mydomain.net/?rd=https://s0.mydomain.net%2Fhello, the redirect url here is fine, but it just never takes me there.

I've tried setting a bunch of various headers like X-Original-URL and X-Forwarded-Proto headers per the instructions here https://www.authelia.com/docs/deployment/supported-proxies/nginx.html, but I'm having no luck. 

Do you have any ideas on how i can fix this?

**Comment by Amir-Ahmad** [comment]
Silly mistake, figured this out. This was because I was setting the auth-signin url (facepalm). It's working after I removed it.

Here is a full working ingress example in case anyone else stumbles upon this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: https://auth.sub.domain.com/api/verify?auth=basic
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
  name: test
spec:
  ingressClassName: nginx
  rules:
  - host: sub.domain.com
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 8080
        path: /test
        pathType: Exact
  tls:
  - hosts:
    - sub.domain.com
```
