### ISSUE TITLE
Unable to access resources with a local installation of Authelia (Forbidden error return)

### ISSUE THREAD

**Issue by l0u1sg** [authelia/authelia#2773]
### Description

Hello, 
I have just configured Authelia on my local network in order to secure the access to my services and use only one password for everything. The installation is ok, I arrive well on the Authelia connection page, I manage to log in, but as soon as I try to access a service other than the basic services installed with Authelia (Traefik, secure & public), the site returns me a forbidden. The site unblocks well in itself, but it is the loading of the resources which is not authorized. Here are the services configurations 

### Config: 
- Authelia config : Not changed from the one created by default with the local Authelia installation script
- docker compose : Not changed
- Secure web container with Authelia (example) :
![image](https://user-images.githubusercontent.com/46707587/148453319-e0ce2a52-f186-4ea6-ba59-5ee5893e654f.png)
(The domain internal.com is declared in my local DNS)

### Error log
- Authelia :
```
time="2022-01-07T08:18:13+11:00" level=info msg="Access to https://homer.internal.com/favicon.ico is forbidden to user lgallet" method=GET path=/api/verify remote_ip=192.168.25.154,
time="2022-01-07T08:18:13+11:00" level=debug msg="Check authorization of subject username=lgallet groups=admins,dev ip=192.168.25.154 and object https://homer.internal.com/favicon.ico (method GET).",
time="2022-01-07T08:18:13+11:00" level=debug msg="No matching rule for subject username=lgallet groups=admins,dev ip=192.168.25.154 and url https://homer.internal.com/favicon.ico... Applying default policy.",
time="2022-01-07T08:18:13+11:00" level=info msg="Access to https://homer.internal.com/ is forbidden to user lgallet" method=GET path=/api/verify remote_ip=192.168.25.154,
time="2022-01-07T08:18:13+11:00" level=debug msg="No matching rule for subject username=lgallet groups=admins,dev ip=192.168.25.154 and url https://homer.internal.com/... Applying default policy.",
time="2022-01-07T08:18:13+11:00" level=debug msg="Check authorization of subject username=lgallet groups=admins,dev ip=192.168.25.154 and object https://homer.internal.com/ (method GET)."
``` 
- Traefik:
```
time="2022-01-06T21:18:13Z" level=debug msg="Remote error http://authelia:9091/api/verify?rd=https://authelia.internal.com. StatusCode: 403" middlewareName=authelia@docker middlewareType=ForwardedAuthType
```

Does anyone have an idea? Thanks :)

**Comment by nightah** [comment]
Can you please provide your Authelia configuration, including your ACLs specifically please.

**Comment by l0u1sg** [comment]
Yes of course : 
```
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: ***
default_redirection_url: https://public.internal.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: public.internal.com
      policy: bypass
    - domain: traefik.internal.com
      policy: one_factor
    - domain: secure.internal.com
      policy: two_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: internal.com  # Should match whatever your root protected domain is
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: ***
notifier:
  filesystem:
    filename: /config/notification.txt
...
```

**Comment by james-d-elliott** [comment]
There is no ACL for homer.internal.com and the default policy is deny, this is intended behavior.

**Comment by l0u1sg** [comment]
Ok, I just updated my configuration file by adding this:
```
access_control:
  default_policy: deny
  rules:
    - domain: public.internal.com
      policy: bypass
    - domain: traefik.internal.com
      policy: one_factor
    - domain: secure.internal.com
      policy: two_factor
    - domain: homer.internal.com
      policy: one_factor
```
Except that now I have a Gateway Timeout error, with these logs in Authelia:
```
time="2022-01-07T20:57:30+11:00" level=debug msg="Check authorization of subject username=lgallet groups=admins,dev ip=192.168.25.154 and object https://homer.internal.com/ (method GET).",
time="2022-01-07T20:58:00+11:00" level=debug msg="Check authorization of subject username=lgallet groups=admins,dev ip=192.168.25.154 and object https://homer.internal.com/favicon.ico (method GET)."
```
And these ones in Traefik :
```

time="2022-01-07T10:00:49Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"authelia_session=e9K8xQpD%$cd*jcw3SIZQGfCc2TQI36P\"],\"Dnt\":[\"1\"],\"Remote-Email\":[\"lgallet@example.com\"],\"Remote-Groups\":[\"admins,dev\"],\"Remote-Name\":[\"Louis Gallet\"],\"Remote-User\":[\"lgallet\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Te\":[\"trailers\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0\"],\"X-Forwarded-Host\":[\"homer.internal.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0ac157d2f3a2\"],\"X-Real-Ip\":[\"192.168.25.154\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"homer.internal.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.25.154:53366\",\"RequestURI\":\"/\",\"TLS\":null}" ForwardURL="http://172.21.0.2:8080",
time="2022-01-07T10:01:19Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"authelia_session=e9K8xQpD%$cd*jcw3SIZQGfCc2TQI36P\"],\"Dnt\":[\"1\"],\"Remote-Email\":[\"lgallet@example.com\"],\"Remote-Groups\":[\"admins,dev\"],\"Remote-Name\":[\"Louis Gallet\"],\"Remote-User\":[\"lgallet\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Te\":[\"trailers\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0\"],\"X-Forwarded-Host\":[\"homer.internal.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"0ac157d2f3a2\"],\"X-Real-Ip\":[\"192.168.25.154\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"homer.internal.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"192.168.25.154:53366\",\"RequestURI\":\"/\",\"TLS\":null}",
time="2022-01-07T10:01:19Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp 172.21.0.2:8080: i/o timeout"
```

And on my browser, I have these logs, apparently, the domain takes 30 seconds to load (hence the timeout) and the resources still returns a 403:
![image](https://user-images.githubusercontent.com/46707587/148527817-107860f0-6b90-4419-a103-ff3acc89f4b2.png)
