### ISSUE TITLE
Unsuccessful TOTP authentication attempt

### ISSUE THREAD

**Issue by fabifont** [authelia/authelia#2811]
### Description

OTP is always rejected. Authelia and the authenticator are synced.

### Expected Behaviour

OTP is accepted.

### Reproduction Steps

1. Go to authelia page
2. Login with credentials
3. The credentials are accepted so authelia asks for the OTP)
4. Register your device for the first time
5. Open the link received via email and scan the QR with your authenticator app (I use authy)
6. Submit the OTP read from the authenticator

### Additional Information

```authelia   | time="2022-01-20T14:20:43+01:00" level=error msg="Unsuccessful TOTP authentication attempt by user 'fabio'" method=POST path=/api/secondfactor/totp remote_ip=<MY_IP> stack="github.com/authelia/authelia/v4/internal/handlers/response.go:181               markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_sign_totp.go:41       SecondFactorTOTPPost\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15 RequireFirstFactor.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51     AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.4/router.go:414                                 (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14          LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.31.0/server.go:2278                              (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.31.0/workerpool.go:223                           (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.31.0/workerpool.go:195                           (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581                                                        goexit"```

**Comment by james-d-elliott** [comment]
Please provide your TOTP settings. This is and a majority of other features are tested, so either the authenticator app is not compatible with your settings, or the time is not in sync like you think (can be tested by increasing the skew to 20).

**Comment by fabifont** [comment]
This is my `configuration.yml`:
```
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark

jwt_secret: secret

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

ntp:
  address: "time.cloudflare.com:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  disable_reset_password: true
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "*.<mydomain>"
      policy: two_factor

session:
  name: authelia_session
  domain: myrootdomain
  secret: secret
  expiration: 1h
  inactivity: 5m

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: secret
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: secret
    password: secret
    sender: secret
    host: smtp.mailbox.org
    port: 587
...
```
