### ISSUE TITLE
Simple access control rules doesn't work as expected

### ISSUE THREAD

**Issue by benjamin-feron** [authelia/authelia#2814]
## Bug Report

Hi, I just want to apply simple access control rules on a domain but it mysteriously does not work.

### Test 1

First, here is default policy :

```yaml
access_control:
  default_policy: deny
```

Here is the rules :

```yaml
  rules:
    - domain: wiki.domain.tld
      ressources:
        - "^/xxx"
      policy: one_factor

    - domain: wiki.domain.tld
      policy: bypass
```

If I visit `wiki.domain.ltd`, I'm redirected to login page, it is not the expected behaviour.

### Expected Behaviour

Home page should display !

### Test 2

If I change policy of the first rule like this :

```yaml
  rules:
    - domain: wiki.domain.tld
      ressources:
        - "^/xxx"
      policy: bypass

    - domain: wiki.domain.tld
      policy: bypass
```
Now, `wiki.domain.ltd` page is displayed ! What happens ?? I'm very confused about this.

### Expected Behaviour

Home page should not display !

### Test 3

Even more surprising... if I now change policy of the second rule like this :

```yaml
  rules:
    - domain: wiki.domain.tld
      ressources:
        - "^/xxx"
      policy: bypass

    - domain: wiki.domain.tld
      policy: one_factor
```
Whaaat ?? `wiki.domain.ltd` page is still displayed !  It is not the expected behaviour at all !

### Expected Behaviour

Home page should not display !!!

### Additional Information

Authelia docker image : authelia/authelia:4.33.1
Traefik docker image : traefik:2.5.6

Any ideas ?

**Comment by james-d-elliott** [comment]
Please change the logs to trace and show us the output.

**Comment by benjamin-feron** [comment]
Thank you for your response @james-d-elliott 

Here is the logs :

```
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Headers=GET /api/verify?rd=https://auth.domain.ltd HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36\r\nHost: authelia:9091\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: fr-FR,fr;q=0.9\r\nCookie: DokuWiki=9vq1f1cb15qj7sm5cv30r9551p\r\nDnt: 1\r\nSec-Ch-Ua: \" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Linux\"\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: none\r\nSec-Fetch-User: ?1\r\nUpgrade-Insecure-Requests: 1\r\nX-Forwarded-For: 192.168.0.254\r\nX-Forwarded-Host: wiki.domain.ltd\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: 2d615fa4ed13\r\nX-Forwarded-Uri: /\r\nX-Real-Ip: 192.168.0.254\r\n\r\n" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (method GET)."
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="ACL MISS Position 1 for subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (Method GET)"
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="ACL MISS Position 2 for subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (Method GET)"
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="ACL MISS Position 3 for subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (Method GET)"
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="ACL MISS Position 4 for subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (Method GET)"
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="ACL MISS Position 5 for subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (Method GET)"
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="ACL MISS Position 6 for subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (Method GET)"
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="ACL HIT Position 7 for subject username= groups= ip=192.168.0.254 and object https://wiki.domain.ltd/ (Method GET)"
authelia    | time="2022-01-20T22:11:32+01:00" level=info msg="Access to https://wiki.domain.ltd/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.domain.ltd?rd=https%3A%2F%2Fwiki.domain.ltd%2F&rm=GET" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Replied (status=302)" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Request hit" method=GET path=/ remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Request hit" method=GET path=/static/js/index.67e37718.js remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.67e37718.js remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Request hit" method=GET path=/static/css/index.6d03b4c9.css remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.6d03b4c9.css remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Request hit" method=GET path=/static/js/vendor.4a71d8d2.js remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:32+01:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/vendor.4a71d8d2.js remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:33+01:00" level=trace msg="Request hit" method=GET path=/favicon.ico remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:33+01:00" level=trace msg="Replied (status=200)" method=GET path=/favicon.ico remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:33+01:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=192.168.0.254
authelia    | time="2022-01-20T22:11:33+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=192.168.0.254
```

**Comment by benjamin-feron** [comment]
It seems there's no subrequest isn't it ?

**Comment by james-d-elliott** [comment]
It's matching rule 7 which doesn't exist in the example you provided. Seems like you're modifying the wrong config file.

**Comment by benjamin-feron** [comment]
Sorry, in the configuration snippets I gave, I only showed rules for domain wiki.domain.tld.
Here, the complete access rules file (7th rules is right one that hits) :

```yaml
access_control:
  default_policy: deny

  networks:
    - name: lan
      networks:
        - 192.168.0.0/24

  rules:

    ##################
    # www.domain.tld #
    ##################

    - domain: www.domain.tld
      policy: bypass

    ###################
    # code.domain.tld #
    ###################

    - domain: code.domain.tld
      subject: "user:befe"
      policy: one_factor

    ###################
    # home.domain.tld #
    ###################

    - domain: home.domain.tld
      subject: "group:users"
      policy: one_factor

    - domain: home.domain.tld
      ressources:
        - "^/admin/"
      subject: "group:admin"
      policy: one_factor

    - domain: home.domain.tld
      ressources:
        - "^/test$"
      subject: "user:befe"
      policy: one_factor

    #####################
    # static.domain.tld #
    #####################

    - domain: static.domain.tld
      policy: bypass


    ###################
    # wiki.domain.tld #
    ###################

    - domain: wiki.domain.tld
      ressources:
        - "^/xxx"
      policy: one_factor

    - domain: wiki.domain.tld
      policy: bypass
```

**Comment by james-d-elliott** [comment]
Can you just try with the last two and report back? The HIT rule is a bypass rule so it shouldn't require auth. This is tested functionality. It should result in  the hit being rule 2.

**Comment by benjamin-feron** [comment]
OK, so,

Access rules files :

```yaml
access_control:
  default_policy: deny

  rules:

    - domain: wiki.b3f3.net
      ressources:
        - "^/xxx"
      policy: one_factor

    - domain: wiki.b3f3.net
      policy: bypass
```

Logs :

```
authelia    | time="2022-01-21T10:54:52+01:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
authelia    | time="2022-01-21T10:54:52+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Headers=GET /api/verify?rd=https://auth.b3f3.net HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36\r\nHost: authelia:9091\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,la;q=0.6,es;q=0.5\r\nDnt: 1\r\nSec-Ch-Ua: \" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Linux\"\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: none\r\nSec-Fetch-User: ?1\r\nUpgrade-Insecure-Requests: 1\r\nX-Forwarded-For: 192.168.0.254\r\nX-Forwarded-Host: wiki.b3f3.net\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Port: 443\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Server: 2d615fa4ed13\r\nX-Forwarded-Uri: /\r\nX-Real-Ip: 192.168.0.254\r\n\r\n" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.0.254 and object https://wiki.b3f3.net/ (method GET)."
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="ACL HIT Position 1 for subject username= groups= ip=192.168.0.254 and object https://wiki.b3f3.net/ (Method GET)"
authelia    | time="2022-01-21T10:54:57+01:00" level=info msg="Access to https://wiki.b3f3.net/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.b3f3.net?rd=https%3A%2F%2Fwiki.b3f3.net%2F&rm=GET" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Replied (status=302)" method=GET path=/api/verify remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Request hit" method=GET path=/ remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Request hit" method=GET path=/static/js/index.67e37718.js remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.67e37718.js remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Request hit" method=GET path=/static/js/vendor.4a71d8d2.js remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Request hit" method=GET path=/static/css/index.6d03b4c9.css remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.6d03b4c9.css remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/vendor.4a71d8d2.js remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Request hit" method=GET path=/manifest.json remote_ip=192.168.0.254
authelia    | time="2022-01-21T10:54:57+01:00" level=trace msg="Replied (status=200)" method=GET path=/manifest.json remote_ip=192.168.0.254
```

Same result...

**Comment by benjamin-feron** [comment]
And here is the only other configuration file, as you can see, no other access rules in that file :

```yaml
default_redirection_url: https://www.domain.ltd

server:
  host: 0.0.0.0
  port: 9091

log:
  level: trace

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldap://openldap
    timeout: 5s
    start_tls: false
    base_dn: DC=domain,DC=ltd
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(memberUid={username})(objectClass=posixGroup))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: CN=admin,DC=domain,DC=ltd

session:
  name: authelia_session
  expiration: 3600
  inactivity: 300
  domain: domain.ltd

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  mysql:
    host: mariadb
    port: 3306
    database: authelia
    username: authelia

notifier:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: benjamin.feron@gmail.com
    sender: "Authelia domain <authelia@domain.ltd>"
    startup_check_address: admin@domain.ltd

theme: dark
```

**Comment by benjamin-feron** [comment]
Authelia docker image : authelia/authelia:4.33.1
Traefik docker image : traefik:2.5.6

**Comment by benjamin-feron** [comment]
> Also which version are you running?

Authelia docker image : authelia/authelia:4.33.1
Traefik docker image : traefik:2.5.6

**Comment by james-d-elliott** [comment]
I'm attempting to replicate it, but as previously mentioned this is heavily tested functionality and seems unlikely it'd occur this way. Though it's always possible I suppose.

**Comment by benjamin-feron** [comment]
Yes I guess.
Thanks for taking the time to help me.
I will continue to investigate on my end as well.

**Comment by james-d-elliott** [comment]
```yaml
access_control:
  default_policy: deny
  rules:
    - domain: "whoami.jameselliott.dev"
      policy: one_factor
      resources:
      - "^/xxx"
    
    - domain: "whoami.jameselliott.dev"
      policy: bypass
```
