### ISSUE TITLE
Access rule : check for "?" char in resource

### ISSUE THREAD

**Issue by benjamin-feron** [authelia/authelia#2819]
## Bug Report

Hi, I just want to write a rule that test if "?" char exists in url.
I know that "?" is a quantification operator for "zero or one occurence" so I guess that "\\?" should do the job but I first want to test with "?" :

```yaml
access_control:
  default_policy: deny
```

```yaml
- domain: test.domain.ltd
      resources:
        - "?"
      policy: one_factor
```

As expected, logs show me an error :

```
authelia    | time="2022-01-21T12:26:39+01:00" level=error msg="Configuration: Resource [?] for rule #7 domain: [test.domain.ltd] is invalid, error parsing regexp: missing argument to repetition operator: `?`"
authelia    | time="2022-01-21T12:26:39+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

This is a normal behaviour since "?" is preceded by nothing so now I try with "\\?"

```yaml
- domain: test.domain.ltd
      resources:
        - "\?"
      policy: one_factor
```

And this time, logs show me a different error :

```
authelia    | time="2022-01-21T12:29:14+01:00" level=error msg="Configuration: Default Policy [deny] is invalid, access control rules must be provided or a policy must either be 'one_factor' or 'two_factor'"
authelia    | time="2022-01-21T12:29:14+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

Is this a bug or did I miss something ?

**Comment by benjamin-feron** [comment]
i think i found, "\\" must be doubled :

```yaml
    - domain: wiki.b3f3.net
      resources:
        - "\\?"
      policy: one_factor
```
Can someone confirm ?
