### ISSUE TITLE
Failure running the user provider startup check: LDAP Result Code 49 \"Invalid Credentials\"

### ISSUE THREAD

**Issue by loeken** [authelia/authelia#2837]
Hello,

I am trying to install authelia through the helm chart version 0.8.1 from charts.authelia.com with the adminpassword topsecure

I created the following structure and can query ldap successfully with admin/topsecure
```
ldapsearch -x -H ldap://localhost -b "dc=ldap,dc=example,dc=com" -D "cn=admin,dc=ldap,dc=example,dc=com" -w topsecure
# extended LDIF
#
# LDAPv3
# base <dc=ldap,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# ldap.example.com
dn: dc=ldap,dc=example,dc=com
objectClass: top
objectClass: dcObject
objectClass: organization
o: loeken
dc: ldap

# users, ldap.example.com
dn: ou=users,dc=ldap,dc=example,dc=com
ou: users
objectClass: organizationalUnit
objectClass: top

# groups, ldap.example.com
dn: ou=groups,dc=ldap,dc=example,dc=com
ou: groups
objectClass: top
objectClass: organizationalUnit

# loeken, users, ldap.example.com
dn: uid=loeken,ou=users,dc=ldap,dc=example,dc=com
givenName: Luke
sn: Filewalker
uid: loeken
uidNumber: 1000
gidNumber: 500
homeDirectory: /home/loeken
loginShell: /bin/bash
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: top
cn: loeken
mail: loeken@example.com
displayName: loeken
userPassword: REDACTED

# admin, groups, ldap.example.com
dn: cn=admin,ou=groups,dc=ldap,dc=example,dc=com
cn: admin
objectClass: groupOfNames
objectClass: top
member: uid=loeken,ou=users,dc=ldap,dc=example,dc=com

# search result
search: 2
result: 0 Success

# numResponses: 6
# numEntries: 5
```

I have this block in my helm chart to define the authentication_backend:

```
configMap:
    log:
        level: trace
    authentication_backend:
        ldap:
            enabled: true
            implementation: custom
            url: ldap://openldap-openldap-stack-ha.openldap.svc.cluster.local
            timeout: 10s
            start_tls: false
            tls:
                server_name: openldap-openldap-stack-ha.openldap.svc.cluster.local
                skip_verify: true
                minimum_version: TLS1.2
            base_dn: dc=ldap,dc=example,dc=com
            username_attribute: uid
            additional_users_dn: ou=users
            users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
            additional_groups_dn: ou=groups
            group_name_attribute: cn
            groups_filter: (&(member={dn})(objectclass=groupOfNames))
            mail_attribute: Email
            display_name_attribute: displayName
            user: "cn=admin,dc=ldap,dc=example,dc=com"
            plain_password: topsecure
```

however in my authelia container the only information i can see is: 

```
time="2022-01-26T16:49:50Z" level=info msg="Authelia v4.33.1 is starting"
time="2022-01-26T16:49:50Z" level=info msg="Log severity set to trace"
time="2022-01-26T16:49:50Z" level=trace msg="Starting scan of directory  for certificates"
time="2022-01-26T16:49:50Z" level=trace msg="Finished scan of directory  for certificates"
time="2022-01-26T16:49:50Z" level=trace msg="Dynamically generated users filter is (&(uid={input})(objectClass=inetOrgPerson))"
time="2022-01-26T16:49:50Z" level=trace msg="Dynamically generated users BaseDN is ou=users,dc=ldap,dc=example,dc=com"
time="2022-01-26T16:49:50Z" level=trace msg="Detected user filter replacements that need to be resolved per lookup are: {input}=true"
time="2022-01-26T16:49:50Z" level=trace msg="Dynamically generated groups BaseDN is ou=groups,dc=ldap,dc=example,dc=com"
time="2022-01-26T16:49:50Z" level=trace msg="Detected group filter replacements that need to be resolved per lookup are: input=true, username=false, dn=false"
time="2022-01-26T16:49:50Z" level=info msg="Storage schema is being checked for updates"
time="2022-01-26T16:49:50Z" level=info msg="Storage schema is already up to date"
time="2022-01-26T16:49:50Z" level=error msg="Failure running the user provider startup check: LDAP Result Code 49 \"Invalid Credentials\": " stack="github.com/authelia/authelia/v4/internal/commands/root.go:97 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:77 cmdRootRun\ngithub.com/spf13/cobra@v1.2.1/command.go:860                 (*Command).execute\ngithub.com/spf13/cobra@v1.2.1/command.go:974                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.2.1/command.go:902                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10      main\nruntime/proc.go:255                                          main\nruntime/asm_amd64.s:1581                                     goexit"
time="2022-01-26T16:49:50Z" level=debug msg="Notifier SMTP client attempting connection to mail.example.me:25"
time="2022-01-26T16:49:50Z" level=debug msg="Notifier SMTP client connected successfully"
time="2022-01-26T16:49:50Z" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: mail.example.me), attempting"
time="2022-01-26T16:49:50Z" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2022-01-26T16:49:50Z" level=debug msg="Notifier SMTP config has no password specified so authentication is being skipped"
time="2022-01-26T16:49:51Z" level=fatal msg="The following providers had fatal failures during startup: user" stack="github.com/authelia/authelia/v4/internal/commands/root.go:117 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:77  cmdRootRun\ngithub.com/spf13/cobra@v1.2.1/command.go:860                  (*Command).execute\ngithub.com/spf13/cobra@v1.2.1/command.go:974                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.2.1/command.go:902                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:255                                           main\nruntime/asm_amd64.s:1581                                      goexit"

```

I am not sure as to why the connection fails as to my understanding i am connecting here to cn=admin,dc=ldap,dc=eampl,dc=com using topsecure, which works via cli/ldapsearch. any suggestions on how i can get more output (i set log to trace) any ideas are welcome
