### ISSUE TITLE
LDAP Result Code 32 "No Such Object"-- Helm chart only

### ISSUE THREAD

**Issue by page1337com** [authelia/authelia#2850]
### Description
Same config between docker and helm chart-

Ubuntu Microk8s Traefik Authelia => AWS Microsoft AD

```
LDAP does not work giving error LDAP Result Code 32 "No Such Object"
```
### Expected Behaviour
Works on docker authelia but does not work on helm chart authelia behind traefik

```
time="2022-02-06T04:14:09Z" level=warning msg="Configuration: No access control rules have been defined so the default policy one_factor will be applied to all requests"
time="2022-02-06T04:14:09Z" level=info msg="Authelia v4.33.1 is starting"
time="2022-02-06T04:14:09Z" level=info msg="Log severity set to info"
time="2022-02-06T04:14:09Z" level=info msg="Storage schema is being checked for updates"
time="2022-02-06T04:14:09Z" level=info msg="Storage schema migration from 0 to 1 is being attempted"
time="2022-02-06T04:14:09Z" level=info msg="Storage schema migration from 0 to 1 is complete"
time="2022-02-06T04:14:09Z" level=info msg="Listening for non-TLS connections on '0.0.0.0:9091' path '/'"
time="2022-02-06T04:14:40Z" level=error msg="Unsuccessful 1FA authentication attempt by user 'admin': cannot find user DN of user 'admin'. Cause: LDAP Result Code 32 \"No Such Object\": 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=ldap,DC=page1337,DC=com'\n\x00" method=POST path=/api/firstfactor remote_ip=119.237.209.202 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:177            markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:100 FirstFactorPost.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.4/router.go:414                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14       LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.31.0/server.go:2278                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.31.0/workerpool.go:223                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.31.0/workerpool.go:195                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581          
```
### Reproduction Steps
```
authentication_backend:
  ldap:
    implementation: activedirectory
    url: ldap://<YOUR_SERVER_NAME>
    timeout: 5s
    start_tls: false
    tls:
      server_name: <YOUR_SERVER_NAME>
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: <YOUR_BASE_DN>
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    user: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
```

### Additional Information
Tested and work on docker traefik authelia but fails on helm traefik authelia. Any ideas?
