### ISSUE TITLE
Minimal Working Example on Localhost gives Connection Refused

### ISSUE THREAD

**Issue by timbmg** [authelia/authelia#2852]
I am (mostly) following the [documentation](https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html) for setting up authelia with traefik. 
However, once i try to reach `https://whoami.app.localhost` which should be protected by authelia, the traefik logs show:
```
msg="Error calling http://authelia:9091/api/verify?rd=https://login.app.localhost/. Cause: Get \"http://authelia:9091/api/verify?rd=https://login.app.localhost/\": dial tcp 172.22.0.5:9091: connect: connection refused" middlewareName=authelia@docker middlewareType=ForwardedAuthType
```

I added `app.localhost` to my `etc/hosts` to forward to `127.0.0.1`

**docker-compse.yml**
```yml
version: "3.3"

networks:
  net:
    driver: bridge

services:
  
  reverse_proxy:
    image: traefik:2.6.0
    container_name: traefik
    networks:
      - net
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --log=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    labels:
      - traefik.enable=true
      - traefik.http.routers.reverse_proxy.rule=Host(`app.localhost`)
      - traefik.http.routers.reverse_proxy.entrypoints=web

  authelia:
    image: authelia/authelia
    container_name: authelia
    networks:
      - net
    ports:
      - 9091:9091
    volumes:
      - ./authelia/:/config
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`login.app.localhost`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls=true
      - traefik.http.middlewares.authelia=authelia
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.app.localhost/
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - net
    expose:
      - 6379
    volumes:
      - ./redis:/data
    environment:
      - TZ=Europe/Berlin

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - net
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.app.localhost`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.middlewares=authelia@docker
    environment:
      - TZ=Europe/Berlin
```

**authelia/configuration.yml**
```yml
server:
  host: 0.0.0.0
  port: 9091

log:
  log_level: debug
  keep_stdout: true

jwt_secret: someRandomString

default_redirection_url: app.localhost

totp:
  issuer: app.localhost
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  file:
    path: /users_database.yml 
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: app.localhost
      policy: bypass
    
    - domain: whoami.app.localhost
      policy: one_factor

session:
  name: authelia_session
  secret: someRandomString
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: app.localhost

redis:
  host: redis
  port: 6379

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: dark 

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```
