### ISSUE TITLE
Implement Audit Logs

### ISSUE THREAD

**Issue by mind-ar** [authelia/authelia#2864]
### Description
Audit Logs allows the administrators to have a detailed log related to authentication (login, logouts, resource access, etc)
Many companies, such as banks, require products to provide audit trails/logs. 
Also, an audit log will be useful when the management portal is developed, as pointed at https://github.com/authelia/authelia/issues/595#issuecomment-612335339

First version can be easily developed, using the current logger, but on different file:
```yml
audit:
  level: info
  keep_stdout: false
  local:
    format: text
    file_path: ""
```
A second version could support db backend
```yml
audit:
  level: info
  keep_stdout: false
  mysql: {}
  postgres: {}
  ...: {}
```
Future version (too future) could allow to push audit logs to common logging systems, e.g. Common Log File System (CLFS) or Common Event Format (CEF)

Things to define:
- [ ] Fields to be logged
- [ ] What must be logged for each level

What do you think?

**Comment by seandlg** [comment]
Currently, we set the log level to `debug` to achieve this. However, this logs access against all endpoints, also non-sensitive ones. Being able to audit logs against `/api`-endpoints would be awesome indeed!

**Comment by james-d-elliott** [comment]
Can you explain what you mean by /api endpoints?

Also if we added audit logging it would only be to a log facility like file or gelf etc, not SQL. It'd likely take this form:

```yaml
log:
  audit:
    enabled: false
    directory: "/audit"
    ## Categories to log. When using the directory logger each of these has its own file.
    ## Most of these can probably be relatively easily implemented, with openid_connect being the least likely to be implemented initially.
    categories:
    - authentication  # logs all user authentication attempts 
    - authorization  # logs all authorization requests to /api/verify
    - openid_connect  # logs all openid connect related things
    - request  # logs 
```

**Comment by seandlg** [comment]
Oh, sure! I meant that only certain endpoints would have to be audited, e.g. if the `rules` section were to be (simplified example):

```yaml
  rules:
    - domain: "web.app.com"
      subject:
        - "group:admins"
      policy: one_factor
      audit: false # SPA, cannot do anything by itself

    # This is required for a preflight OPTIONS request, that sets the CORS policy
    - domain: "api.app.com"
      policy: bypass
      methods:
        - OPTIONS
      audit: false # not of interest

    - domain: "api.app.com"
      subject:
        - "group:admins"
      policy: one_factor
      audit: true # audit any requests that match here
```
I guess my thinking here is that I could extend the security-sensitive, existing access control logic to my `auditing` needs. Does that make sense?

**Comment by mind-ar** [comment]
or, taking something from each idea:
```yml
log:
  audit:
    enabled: false
    directory: "/audit"
... 
  rules:
    - domain: "web.app.com"
      subject:
        - "group:admins"
      policy: one_factor
      audit: [] # SPA, cannot do anything by itself

    - domain: "api.app.com"
      policy: bypass
      methods:
        - OPTIONS
      audit: [] # not of interest

    - domain: "api.app.com"
      subject:
        - "group:admins"
      policy: one_factor
      audit: [authentication, authentication, request ] # audit any requests that match here
```

**Comment by james-d-elliott** [comment]
I'm not convinced making it per policy is a good idea. Getting too granular is going to make it easier to configure it in a way which misses important logs. I feel like this is probably a good realm for logging engines which are purpose built for this kind of filtering. But I can get the feedback of the other team members.

Audit logs are traditionally meant to be used in postmortem when a security breach has occurred or to detect security breaches in advance of the postmortem. While it's on the user, if they use the below information they will be in for a nasty surprise at a point where it's too late to fix it if the API is ever breached by a non-admin account:

```yaml
   - domain: "api.app.com"
      subject:
        - "group:admins"
      policy: one_factor
      networks: 192.168.1.0/24
      audit: true # audit any requests that match here
   - domain: "api.app.com"
      subject:
        - "group:admins"
      policy: two_factor
      audit: true # audit any requests that match here
   - domain: "api.app.com"
      policy: one_factor
      audit: false
```
