### ISSUE TITLE
Worker node ip address showed in logs "ip=" not IP of browser

### ISSUE THREAD

**Issue by ybizeul** [authelia/authelia#2881]
### Description

I'm trying to make so that requests coming from LAN bypass authentication. When I connect I get the authentication page with the following in the logs :
```
time="2022-02-18T20:12:22+01:00" level=debug msg="Check authorization of subject username= groups= ip=10.1.0.41 and object https://test.blah.org/ (method GET)."
time="2022-02-18T20:12:22+01:00" level=info msg="Access to https://test.blah.org/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://authelia.blah.org?rd=https%3A%2F%2Ftest.blah.org%2F&rm=GET" method=GET path=/api/verify remote_ip=10.1.0.41
```

I would expect this rule to match :

```
  networks:
    - name: lan
      networks:
        - 10.0.1.0/24
  rules:
    - domain: test.blah.org
      policy: bypass
      networks:
        - lan
```

### Expected Behaviour

I expect to see the clien't IP instead of k8s worker node IP

### Reproduction Steps

_N/A_

### Additional Information

Middleware configuration

```
---
# Forward authentication to example.com
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia-auth
spec:
  forwardAuth:
    address: http://authelia.authelia:9091/api/verify?rd=https://authelia.blah.org
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
```

Service configuration

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blah
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`test.blah.org`)
    kind: Rule
    middlewares:
    - name: authelia-auth
      namespace: authelia
    services:
    - name: blah
      kind: Service
      port: 80
  tls:
    certResolver: cloudflare
    domains:
    - main: test.blah.org
      sans:
      - test.blah.org
```
