### ISSUE TITLE
Expose options to enable PKCE for OAuth 2 Authorization Code flow

### ISSUE THREAD

**Issue by FineWolf** [authelia/authelia#2921]
## Feature Request
Add options in the configuration schema to enable PKCE for authorization code flow.

### Description
When authenticating a client application (SPA-type frontend application), the recommended approach to properly authenticate is to use the Authorization Flow with PKCE. [Proof Key for Code Exchange is an extension of the authentication code flow](https://oauth.net/2/pkce/) which aims to prevent CSRF and authorization code injection attacks by requiring the client application to prove that it is the owner of a token request.

The work to enable this in Authelia would be minimal since Fosite (the underlying OIDC/OAuth2 library) already has support for PKCE.

The required changes would be as follows:

- Add 3 parameters in `OpenIDConnectConfiguration` (`internal\configuration\schema\identity_providers.go`) to expose PKCE options, specifically:
  - `EnforcePKCE` / `enforce_pkce` (bool - if set to true, requires clients to perform authorization code flows with PKCE - default false)
  - `EnforcePKCEForPublicClients` / `enforce_pkce_for_public_clients` (bool - if set to true, requires only public clients to perform authorization code flows with PKCE - default false - see note below)
  - `EnablePKCEPlainChallengeMethod`  / `enable_pkce_plain_challenge_method` (bool - if set to true, allows `challenge_method = plain` for PKCE challenges - default false [should use `S256` instead])
- Populate relevant default values (see note below)
- In `internal\oidc\provider.go`, enable `OAuth2PKCEFactory` and populate the relevant config from the configuration object.
- Edit the documentation to reflect the changes and recommended values.

---

If you would prefer that default values are set to the most secure and sensible option, I would recommend setting `EnforcePKCEForPublicClients` to true. However, this would be a breaking changes for public clients using the authorization code flow.

---

I can work on the PR required for this feature.

**Comment by james-d-elliott** [comment]
SGTM. You're welcome to do it, otherwise I'm probably able to take a look in a few days.

**Comment by james-d-elliott** [comment]
Also while I see the logic behind this being a breaking change, as OIDC is very clearly marked as beta and subject to breaking changes, I'm inclined to say we just go ahead with the default of enabled. I'd be interested in what @clems4ever and @nightah have to say.

Configuration would look similar to this if we disabled by default:

```yaml
identity_providers:
  oidc:
    pkce:
      enforce: false
      enforce_public_clients: false
      enable_plain_challenge: false
```

Configuration would look similar to this if we enabled by default:

```yaml
identity_providers:
  oidc:
    pkce:
      disable_enforcement: false
      disable_public_client_enforcement: false
      enable_plain_challenge: false
```
