### ISSUE TITLE
[Feature Request] Allow custom HTTP methods

### ISSUE THREAD

**Issue by quasis** [authelia/authelia#2923]
Right now Authelia blocks any HTTP method that is not in the standard list, i.e.:
```
{"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "TRACE", "CONNECT", "OPTIONS"}
```
This is hardcoded, as far as I understand, and even if I explicitly specify some other method in configuration, Authelia will refuse to start. This poses a major problem for WebDAV, CalDAV and alikes, which use an additional set of HTTP methods to communicate with backend (COPY, LOCK, PROPFIND, etc...).

I propose to make the list of allowed methods strict only if the user didn't specify otherwise.

**Comment by james-d-elliott** [comment]
Can you provide logs? There's no reason it would block a request method unless you configure methods in the ACL section. Seems strange to me that it'd operate in any other way than this.

**Comment by quasis** [comment]
Here is an example.

WebDAV sends 2 requests prior to sending the Basic Authorization header. The first request is OPTIONS, the second is PROPFIND, hence the configuration:

```
        access_control:
            rules:
                - domain: "nas.local.test"
                  policy: bypass
                  methods:
                    - OPTIONS
                    - PROPFIND
                - domain: "*.local.test"
                  policy: one_factor

```

Authelia fails with:

```
time="2022-02-28T13:32:25Z" level=error msg="Configuration: Method PROPFIND for rule #1 domain: [nas.local.test] is invalid, must be one of the following methods: GET, HEAD, POST, PUT, PATCH, DELETE, TRACE, CONNECT, OPTIONS"
time="2022-02-28T13:32:25Z" level=fatal msg="Can't continue due to the errors loading the configuration"
```

**Comment by james-d-elliott** [comment]
So my point was if you don't include the methods it should not block, it will bypass in that instance.

**Comment by james-d-elliott** [comment]
Based on the implementation, if you include a methods criteria the rule should not match those methods, and you can't specifically match those methods, but if a rule matches everything other than methods, and methods is not included, it should match and that means it'll apply. That being said I don't think that excludes us from implementing something like this, just think it may potentially solve your issue depending on your needs.

**Comment by quasis** [comment]
>  just think it may potentially solve your issue depending on your needs

Thank you, that indeed worked!

> That being said I don't think that excludes us from implementing something like this

Perhaps the best and the fastest route will be to remove the start-up check for valid method names. Previously I thought that Authelia actually blocks methods that are not on the list, but if it doesn't, then there is no backward compatibility issues here.

**Comment by james-d-elliott** [comment]
> Perhaps the best and the fastest route will be to remove the start-up check for valid method names. Previously I thought that Authelia actually blocks methods that are not on the list, but if it doesn't, then there are no backward compatibility issues here.

I'm not entirely a fan of the idea mainly because there are standards that exist and we should be specific in what we allow when it comes to that. It's important because it would also be very confusing if someone makes a typo that is incredibly hard to spot, it may result in a configuration which could result in a security issue.

For example if we allowed it this configuration would ultimately allow posts when it shouldn't:

```yaml
access_control:
  default_policy: deny
  rules:
  - domain: secure.example.com
    policy: deny
    methods:
    - P0ST
  - domain: secure.example.com
    policy: bypass
```
