### ISSUE TITLE
Webauthn: Login fails specifically over NFC with previously registgered u2f/fido keys (works with webauthn/fido2 keys)

### ISSUE THREAD

**Issue by tarioch** [authelia/authelia#2962]
### Description

After upgrading to 4.34.2 I can no longer login on my mobile using NFC (I use an Yubikey NEO), login through USB on a PC still works.

### Expected Behaviour

Authenticating with NFC works

### Reproduction Steps

1.  Login
2.  Screen to hold the token appears
3.  hold the token => error "Failed to initie security key sign in process" appears

**Comment by tarioch** [comment]
Fyi, I tested on https://demo.yubico.com/webauthn-technical/login and that works fine.

**Comment by james-d-elliott** [comment]
Are you sure it's a Yubikey NEO? They shouldn't work on that test site at all I don't think.

**Comment by james-d-elliott** [comment]
For reference I just tried with my YubiKey 5 NFC. It was registered with Webauthn, I'll attempt to register one with U2F and try again. I suspect there may be an issue with the appid extension when used with NFC and my implementation of appid.

**Comment by tarioch** [comment]
I'm sure it's a yubikey neo. After reregistering with webauthn, it works :). For me that's good enough, but might be good to know that you need to reregister them after the update.

**Comment by james-d-elliott** [comment]
According to the spec and several tests it wasn't. But it's possible some edge case with U2F compat and NFC either with the YubiKey NEO, the browser in question, or the webauthn spec itself.

**Comment by werty1st** [comment]
I can confirm that NFC webauthn is not working.
I'm using a https://solokeys.com/ stick with NFC on an iPhone which successfully logs in on https://WebAuthn.io

**Comment by james-d-elliott** [comment]
> 

Can you provide any more additional information? Were the keys registered before the upgrade? Is there an error in the browser? Is there an error in the Authelia logs? I literally confirmed above NFC keys do work. So there has to be edge cases where they do not work.

**Comment by werty1st** [comment]
I'm using authelia/authelia:4@sha256:b627ca3e951390352c25fd89ad38a060f25c13cbf2a754541bd99ae0f6308ed6

```
webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s
```

I will try this now:

```
webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: none
  user_verification: discouraged
  timeout: 60s
```
