### ISSUE TITLE
User not found at login using file-based user database

### ISSUE THREAD

**Issue by crazyelectron-io** [authelia/authelia#3002]
I am somehow unable to login using the file-based user database.

My user database (for testing) looks like this:
```yaml
users:
  someuser:
    displayname: "Some User"
    password: "$argon2id$v=19$m=65536,t=1,p=8$ZFExOE5iNnVpTk1GOUM3Tw$Yy/dJEKby/uHrSqoHmhJrBCjKlwxlzZr7Gav2Vce+iI"
    email: someuser@somedomain.ext
    groups:
      - admins
      - dev
  ron:
    displayname: "Ron"
    password: "$argon2id$v=19$m=65536,t=1,p=8$TjZrZmZDVThlUldwdkJlTQ$bS9C8eOWZ22ETfXUEmoMK/9o7qBp8L/ORl9xzPrkNSE"
    email: ron@somedomain.ext
    groups:
      - admin
 ```
The password strings are generated with:
```shell
docker run authelia/authelia:latest authelia hash-password test
```
I cleared the Chrome and Edge browser cache and cookies, but I keep getting a user not found error in the logfile.
```
level=debug msg="Check authorization of subject username= groups= ip=10.0.0.2 and object https://traefik.somedomain.ext/ (method GET)."
level=info msg="Access to https://traefik.somedomain.ext/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.somedomain.ext?rd=https%3A%2F%2Ftraefik.somedomain.ext%2F&rm=GET" method=GET path=/api/verify remote_ip=10.0.0.2
level=debug msg="Mark 1FA authentication attempt made by user 'ron'" method=POST path=/api/firstfactor remote_ip=10.0.0.2
level=error msg="Unsuccessful 1FA authentication attempt by user 'ron': user not found" method=POST path=/api/firstfactor remote_ip=10.0.0.2 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:177           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:52 FirstFactorPost.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.6/router.go:414                             (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.34.0/server.go:2341                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.34.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.34.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581
```
The relevant pieces of the configuration file:
```yaml
authentication_backend:
  disable_reset_password: true
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      key_length: 32
      iterations: 2
      salt_length: 16
      parallelism: 8
      memory: 512  # blocks this much of the RAM. Tune this.
```

I keep getting an incorrect username or password error. What am I missing?
