### ISSUE TITLE
Healthcheck failure when listening on IPv6 host

### ISSUE THREAD

**Issue by skayo** [authelia/authelia#3050]
### Description

I'm trying to use `::` as the server host for Authelia, but when setting `server.host` to `[::]`, with brackets (as described in the docs), I get the following error:
```
Error initializing listener: listen tcp: address [[::]]:9091: missing port in address

Stack:
  github.com/authelia/authelia/v4/internal/server/server.go:186 Start
  github.com/authelia/authelia/v4/internal/commands/root.go:80  cmdRootRun
  github.com/spf13/cobra@v1.4.0/command.go:860                  (*Command).execute
  github.com/spf13/cobra@v1.4.0/command.go:974                  (*Command).ExecuteC
  github.com/spf13/cobra@v1.4.0/command.go:902                  (*Command).Execute
  github.com/authelia/authelia/v4/cmd/authelia/main.go:10       main
  runtime/proc.go:255                                           main
  runtime/asm_amd64.s:1581                                      goexit
```

On the other hand, when setting `server.host` to `::`, without brackets (unlike the docs tell you), the server successfully starts but the `healthcheck.sh` throws the following error:
```
wget: bad address ':::9091'
```

I checked the Go docs, and [`net.JoinHostPort`](https://pkg.go.dev/net#JoinHostPort), used [here](https://github.com/authelia/authelia/blob/f8a64171b6283581d3377a39871a45c1a668b0b8/internal/server/server.go#L182), automatically adds square brackets if the host contains a colon, so to fix this you'll probably just need to change [`writeHealthCheckEnv`](https://github.com/authelia/authelia/blob/bed7a8ae3202f917c4ac408ba812c5e87aed1908/internal/server/template.go#L94) and the docs or the line where `net.JoinHostPort` is being used.

The bug probably originated from this PR: #1196  
As you can see the server previously used `fmt.Sprintf` to join host and port, so the docs were correct at the time.  
Maybe switch back to `fmt.Sprintf`?

Otherwise, something like this might work in `writeHealthCheckEnv`:
```go
if host == "0.0.0.0" {
	host = "localhost"
} else if strings.Contains(host, ":") {
	host = "[" + host + "]"
}
```
Another solution would be to use `net.JoinHostPort` in `writeHealthCheckEnv` too.

### Expected Behaviour

The server successfully starts and healthcheck is working.

### Reproduction Steps

I'm using Docker with docker-compose, just like in the [lite example](https://github.com/authelia/authelia/tree/master/examples/compose/lite).  
To reproduce all you have to do is set `server.host` in the `configuration.yml` file to either `::` or `[::]`.  
Then you'll notice the healthcheck fails or the server won't start, depending on what you set `server.host` to.

### Temporary Fix

Here's a temporary docker-compose fix for those facing the same problem:
```yaml
healthcheck:
  test: ["CMD", "wget", "--quiet", "--no-check-certificate", "--tries=1", "--spider", "http://[::]:9091/api/health"]
  interval: 30s
  timeout: 3s
  start_period: 1m
```

### Additional Information

- Authelia Version: `4.34.5`
- Docker Version: `20.10.13`
- Docker Compose Version: `2.2.3`
- Kernel Version: `5.4.0-104-generic`
- Operating System: `Ubuntu 20.04.4 LTS`

**Comment by skayo** [comment]
I checked the Go docs, and [`net.JoinHostPort`](https://pkg.go.dev/net#JoinHostPort) does automatically add square brackets if the host contains a colon!

**Comment by skayo** [comment]
Here's a temporary docker-compose fix for those facing the same problem:
```yaml
healthcheck:
  test: ["CMD", "wget", "--quiet", "--no-check-certificate", "--tries=1", "--spider", "http://[::]:9091/api/health"]
  interval: 30s
  timeout: 3s
  start_period: 1m
```
