### ISSUE TITLE
EOF using OIDC in Gitea 

### ISSUE THREAD

**Issue by MrOzean** [authelia/authelia#3057]
### Description
I got 500 error on Gitea when tries using Authelia OIDC provider. Maybe this error is Gitea error

My configuration is:
- Authelia
Version: v4.34.5
Installation type: virtual machine, using `.deb` file, running via `systemd`
Hostname: `sso.hs.lan` (ip: )
Https: enabled

Gitea OIDC settings 
```yml
      - id: git
        description: 'Self hosted git'
        secret: secret
        authorization_policy: one_factor
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://git.hs.lan/user/oauth2/authelia/callback
        userinfo_signing_algorithm: RS256
```

- Gitea
Version: v1.16.5
Installation type: another virtual machine, official docker image, traefik reverse proxy
Hostname: `git.hs.lan`
Https: enabled

Authentication source settings
```txt
Authentication Type:   OAuth2
Authentication Name:   authelia
OAuth2 Provider :      OpenID Connect
Client ID (Key):       git
Client Secret:         secret
Auto Discovery URL:    https://sso.hs.lan/.well-known/openid-configuration
Additional Scopes:     openid groups email profile
```

All settings works correctly. Button `Login via OpenId` shows on Gitea login pages. Click on login button transfer to Authelia login page. Authelia login succes. Next click `Accept` on `Permissions Request` transfer back to Gitea, but instead success login I got 500 error page.

Gitea log
```log
2022/03/24 16:17:47 Started GET /user/login?redirect_to=%2fuser%2foauth2%2fauthelia%2fcallback%3fcode%3dCvYMAaTSGPAX8tugTaAgF9KQbZ40D9sro7_yGrrfIzI.ueUqUuG1n1xDa7TJLwH8yAZhZc2_gezE8VgfNMA-akk%26scope%3dopenid%2bgroups%2bemail%2bprofile%26state%3dbb463e15-b299-47db-bc4c-6f690dfbf428 for 192.168.1.120:0
2022/03/24 16:17:47 Completed GET /user/login?redirect_to=%2fuser%2foauth2%2fauthelia%2fcallback%3fcode%3dCvYMAaTSGPAX8tugTaAgF9KQbZ40D9sro7_yGrrfIzI.ueUqUuG1n1xDa7TJLwH8yAZhZc2_gezE8VgfNMA-akk%26scope%3dopenid%2bgroups%2bemail%2bprofile%26state%3dbb463e15-b299-47db-bc4c-6f690dfbf428 200 OK in 12.241224ms
2022/03/24 16:17:47 Started GET /assets/js/index.js?v=1b37ebcaa3151193e91d19ed55808a12 for 192.168.1.120:0
2022/03/24 16:17:47 Completed GET /assets/js/index.js?v=1b37ebcaa3151193e91d19ed55808a12 304 Not Modified in 1.349074ms
2022/03/24 16:17:47 Started GET /assets/img/logo.svg for 192.168.1.120:0
2022/03/24 16:17:47 Completed GET /assets/img/logo.svg 304 Not Modified in 99.98µs
2022/03/24 16:17:47 Started GET /assets/img/auth/openid_connect.svg for 192.168.1.120:0
2022/03/24 16:17:47 Completed GET /assets/img/auth/openid_connect.svg 304 Not Modified in 103.895µs
2022/03/24 16:17:50 Started GET /user/oauth2/authelia for 192.168.1.120:0
2022/03/24 16:17:50 Completed GET /user/oauth2/authelia 307 Temporary Redirect in 2.502786ms
2022/03/24 16:17:52 Started GET /user/oauth2/authelia/callback?code=_6C27VKab0WQGcXovCpNMeKGPHnghVqWpnQsZd_NZTs.isdYQTpaM9Yad1ea4JIpY5bpQ4M1MLSxC1lIlmJjZPw&scope=openid+groups+email+profile&state=b0fc6a56-38e8-4ec6-a512-ca3fe7aa234f for 192.168.1.120:0
2022/03/24 16:17:52 ...rs/web/auth/oauth.go:848:SignInOAuthCallback() [E] UserSignIn: invalid character 'e' looking for beginning of value
2022/03/24 16:17:52 Completed GET /user/oauth2/authelia/callback?code=_6C27VKab0WQGcXovCpNMeKGPHnghVqWpnQsZd_NZTs.isdYQTpaM9Yad1ea4JIpY5bpQ4M1MLSxC1lIlmJjZPw&scope=openid+groups+email+profile&state=b0fc6a56-38e8-4ec6-a512-ca3fe7aa234f 500 Internal Server Error in 17.583982ms
```

Authelia systemd service status
```log
Mar 24 16:17:52 sso-authority-server authelia[209080]: 2022/03/24 15:57:29 error when serving connection  "192.168.1.134:9000"<->"192.168.1.135:57156": EOF
```
Authelia (oidc enable_client_debug_messages)
```log
time="2022-03-24T16:12:08Z" level=debug msg="Access Request with id '038d1beb-f6b3-41d4-8c5e-33d01d037c55' on client with id 'git' is being processed" method=POST path=/api/oidc/token remote_ip=192.168.1.104
time="2022-03-24T16:12:08Z" level=debug msg="Access Request with id '038d1beb-f6b3-41d4-8c5e-33d01d037c55' on client with id 'git' has successfully been processed" method=POST path=/api/oidc/token remote_ip=192.168.1.104
time="2022-03-24T16:12:08Z" level=trace msg="Access Request with id '038d1beb-f6b3-41d4-8c5e-33d01d037c55' on client with id 'git' produced the following claims: map[access_token:NiYjiD2kevDeQms7hbkio0kgZnN5aM1zg7nUxZt6C7o.YKfER1vZ2PQFfxpjzzvsfy5uYTsqWqmIEAPfGCKcAUI expires_in:3600 id_token:eyJhbGciOiJSUzI1NiIsImtpZCI6IjhjNzE1OCIsInR5cCI6IkpXVCJ9.eyJhdF9oYXNoIjoiYldKU1lPal9kVnJaZ2ZFem11X0ZNUSIsImF1ZCI6WyJnaXQiXSwiYXV0aF90aW1lIjoxNjQ4MTM3MDA2LCJlbWFpbCI6ImFuZHJleUBsb2NhbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJleHAiOjE2NDgxNDE5MjgsImdyb3VwcyI6WyJob21lLXN5bmN0aGluZyIsImhvbWUtdG9ycmVudCIsInByb21ldGhldXMtdXNlciIsInNoYXJlZC1zMy1jb25zb2xlQWRtaW4iLCJhbmRyZXktc3luY3RoaW5nIiwiYW5kcmV5LXMzLWNvbnNvbGVBZG1pbiJdLCJpYXQiOjE2NDgxMzgzMjgsImlzcyI6Imh0dHBzOi8vc3NvLmhzLmxhbiIsImp0aSI6IjlkOTNhNGJiLTcwNjgtNDhiNS05OTRhLTRkZjk3ZDQ1NTU3YiIsIm5hbWUiOiLQkNC90LTRgNC10LkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbmRyZXkiLCJyYXQiOjE2NDgxMzgzMjYsInN1YiI6ImFuZHJleSJ9.DyQfSUb39kSZSgV_t4MyNZ5fU6CmG5kchO0J1EfMvfQeX0DUokf11DggWJefbAPl0BWMCp4pd-E4zCkBExHpcRVWuE5OWZGVDOuIvvCu16PLBqrd61U1-J40zAuqrsk7c-RbA0Dx_iHjCMlOL9Cag35ZjpIsXmzxbXFsLWw459osDFNqOqwNJUWVfvUsBuIdiE7uR2Hi0qZD9uKOTDiksEHreIDwH9y2vSvcmVrQFsOYdxt7iCpgAFvCq6BDk37LUgfjnfAQoBsM-JMLM0sF8WE4rMdH0hv5i935rqK0H2dmn9mRRcLlCmkLKy2aoPxFzD065WmJcToh520sDhWx2A scope:openid groups email profile token_type:bearer]" method=POST path=/api/oidc/token remote_ip=192.168.1.104
```

**Comment by james-d-elliott** [comment]
EOF there seems to indicate the port was closed abruptly by whatever is connecting to it from 192.168.1.135:57156 (i.e. the client abruptly closed it). The message in gitea shows it failed to decode "something" but doesn't say what but it may be trying to decode the JWT id_token, as it starts with `e`. As soon as you copy  and paste the ID Token into something that reads JWT's like https://jwt.io I can guarantee it decodes it so this appears to be an issue most likely on gitea's end but I can't be sure without more information.

I'd suggest increasing log verbosity on gitea. This functionality has been well tested on sites like https://openidconnect.net/ and https://oidcdebugger.com/, as well as several applications. In addition a majority of the implementation comes from a library designed by the authors of a OIDC Certified OP, which is used in that OP.

**Comment by james-d-elliott** [comment]
Any more information? Also what is `192.168.1.134:9000`? Where are the settings in gitea that configure the discovery or endpoints for Authelia?

**Comment by MrOzean** [comment]
+ ` JWT id_token` signature, extracted from authelia log is correct
![Screenshot_1](https://user-images.githubusercontent.com/21057595/160244507-c5f4df93-2269-44be-b0e2-4608b300b8ad.png)

+ I use Traefik, here conf  
Main conf
```yml
entryPoints: 
  websecure: 
    address: :443 # слушаем 443 порт
  traefik: 
    address: ":8081"
  metrics:
    address: ":8082"

certificatesResolvers: 
  acmeresolver: 
    acme:
      caServer: "https://acme.hs.lan/acme/acme/directory" 
      email: "sso.hs@lan" 
      storage: "/media/sso/traefik/acme.json"
      tlsChallenge: {} 

providers: 
  file: 
    directory: /media/sso/traefik/conf 
    watch: true 

```
Dynamic config
```yml
http:
  routers: 
    default:
      rule: "Host(`sso.hs.lan`)"
      service: oauth 
      tls:  
        certResolver: acmeresolver 
      middlewares:
        - "compressor"

  services:
    oauth:
      loadBalancer:
        serversTransport: ignoreCert
        servers:
          - url: "https://localhost:9000" 

  serversTransports:
    ignoreCert:
      insecureSkipVerify: true 


  middlewares:
    compressor:
      compress: {}
```
Authelia listen `0.0.0.0:9000` over `https`, certificate signed by same authority. Maybe this misconfigured. But this is the only way that worked `Proxy-Authorization` to another sites, i.e. `https://sso.hs.lan:9000/api/verify?rd=https://example.hs.lan/`

+ Authelia, log level to trace + enable_client_debug_messages, clean run, [auth.log](https://github.com/authelia/authelia/files/8355672/auth.log)
+ Gitea, log level to trace, clean run, [gitea.log](https://github.com/authelia/authelia/files/8355681/gitea.log)
+ IP configuration
192.168.1.120 - me
192.168.1.134 - authelia
192.168.1.104 - gitea
192.168.1.135 - another vm
+ Something strange...  
192.168.1.135 not use authelia, no way
Some authelia restart, gives me this systemd service status
```sh
Mar 26 14:07:06 sso-authority-server authelia[233134]: 2022/03/26 14:07:06 error when serving connection "[::1]:9000"<->"[::1]:49388": EOF
Mar 26 14:09:33 sso-authority-server authelia[233134]: 2022/03/26 14:09:33 error when serving connection "[::1]:9000"<->"[::1]:49394": EOF
```
Latest restarts, which were used to collect logs gives no errors...

**Comment by james-d-elliott** [comment]
So everything looks fine to me, bit difficult to figure out what specific thing is causing this issue. What is at the address 192.168.1.135?

**Comment by james-d-elliott** [comment]
Looking at those errors more closely, they seem to be from ipv6 localhost addresses. ::1 is the localhost.. so what's probing port 9000 from the localhost? Also our connection error logs all come in the folllowing formats:

```go
		logger.Tracef("Request was too large to handle from client %s. Response Code %d.", ctx.RemoteIP().String(), fasthttp.StatusRequestHeaderFieldsTooLarge)
		logger.Tracef("Request timeout occurred while handling from client %s: %s. Response Code %d.", 
		logger.Tracef("An unknown error occurred while handling a request from client %s: %s. Response Code %d.", ctx.RemoteIP().String(), ctx.RequestURI(), fasthttp.StatusBadRequest)
```

**Comment by MrOzean** [comment]
Oh, my mistake 192.168.1.135 is file server: Samba + SFTP + Syncthing. Syncthing behind traefik and use Forward-Auth via Authelia. Means the errors that got into `systemd service status` is syncthing -> traefik -> authelia error (but all works correct). That's why it wasn't there the last time I ran it, I turned off everything else except the machines with Gitea and Authelia

**Comment by MrOzean** [comment]
Any ideas? Or I should go to create issue in Gitea  repo?

**Comment by james-d-elliott** [comment]
The only potential things I see as potential causes are a routing or other network level issue in your infrastructure, potentially the read/write buffer settings in the Authelia server config (can try bumping them, though if this was an issue it should log it), or an issue on giteas end, Authelia answers on that endpoint and seems to send a valid id_token. If Authelia triggers an EOF it should log a reason why. 

You could even decode it with a JWT.io.

**Comment by kernelkaribou** [comment]
I was able to get this to work. Originally was getting the same error as you @MrOzean. After changing the 

`userinfo_signing_algorithm: RS256`

to 

`userinfo_signing_algorithm: none`

in my authelia config, it began working. I will not claim to know why however. So if there is anything I can provide, happy to.

**Comment by james-d-elliott** [comment]
I'd love to get a full config example for the docs if you had time, both from the Authelia and Gitea side. If the Gitea side is a GUI I'd appreciate if you used the following values for a screenshot too:

```
issuer: https://auth.example.com
client_id: gitea
client_secret: gitea_client_secret
```

**Comment by kernelkaribou** [comment]
Happy to do so

Below is the basic GUI for gitea

![image](https://user-images.githubusercontent.com/25406580/176571896-1465f5cb-74ec-407f-a8a0-4b1378766dcd.png)

Below is the authelia configuration used.

```
      - id: gitea
        description: 
        secret: gitea_client_secret
        public: false
        authorization_policy: one_factor
        audience: []
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://gitea.example.com/user/oauth2/authelia/callback
        userinfo_signing_algorithm: none
```

If more is needed please let me know.

In addition, I have filed a bug [ OIDC 500 error when using RS256 for userinfo_signing_algorithm on various apps #3641 ](https://github.com/authelia/authelia/issues/3641) as the issue looks to be the same in portainer and not necessarily specific to Gitea when using the specific RS256 value.
