### ISSUE TITLE
Unable to use OIDC

### ISSUE THREAD

**Issue by shadowychaos** [authelia/authelia#3063]
### Description

I am unable to use OIDC as a provider. When navigating to https://<root>/.well-known/openid-configuration, it is a blank white page. When my test applications (Bookstack and Portainer) uses the https://<root>/api/oidc/authorization, it gets a 404.
I am using LDAP (specifically FreeIPA) as the authentication backend and MySQL as the storage backend.
I am using Nginx in front of Authelia (config below)

### Expected Behaviour

OIDC should be functioning.

### Reproduction Steps

Use configuration from https://www.authelia.com/docs/configuration/identity-providers/oidc.html with modifications. Use Authelia in a docker container using docker-compose. Use LDAP as authentication backend and MySQL as storage backend. Session backend is local

### Additional Information

Authelia logs:
```
time="2022-03-26T18:55:16-05:00" level=trace msg="Request hit" method=GET path=/api/oidc/authorization remote_ip=172.20.0.4
time="2022-03-26T18:55:16-05:00" level=trace msg="Replied (status=404)" method=GET path=/api/oidc/authorization remote_ip=172.20.0.4
```

Authelia OIDC Configuration:
```
identity_providers:
  oidc:
    hmac_secret:<hmacsecret_here>
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
     <Privatekey_here>
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    clients:
      - id: bookstack
        description: Wiki
        secret: <secretid_here>
        public: false
        authorization_policy: one_factor
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - <bookstack_url>
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```

Nginx Configuration:
```
worker_processes  1;

events {
    worker_connections  1024; 
}

http {
    log_format compression '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" "$gzip_ratio" "$sent_http_gregorytech_auth_cookie"';
    server {
        listen 80;
        server_name $host;
        return 301 https://$host$request_uri;
    }

map $http_destination_host $destination_host {
    default $http_x_forwarded_host;
    "~.*" $http_destination_host;
}
map $http_destination_path $http_request_path {
    default $http_x_forwarded_uri;
    "~.*" $http_destination_path;
}

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_certificate /ssl/server.cer;
        ssl_certificate_key /ssl/server.key;
    
        location / {
            proxy_pass http://authelia:9091;
	    proxy_redirect off;

            # Timeout if the real server is dead
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
	    client_body_in_file_only on;
	    proxy_set_header Host $host;
	    proxy_set_header X-Original-URL $scheme://$destination_host$http_request_path;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $destination_host;
            proxy_set_header X-Forwarded-Uri $request_uri;
            proxy_cache_bypass $cookie_session;
            proxy_no_cache $cookie_session;
        }
    }
}
```
