### ISSUE TITLE
Not able to escape + sign in resources of rules using regex

### ISSUE THREAD

**Issue by PerryCodekies** [authelia/authelia#3083]
### Description

I am using the v4.34.6 which is latest as of writing, I am not able to start up Authelia because of this rule:
```
  rules:
    - domain: s.domain.example
      resources:
        - "^/admin.*"
        - "^/[a-zA-Z0-9-_]+\+$"
      policy: two_factor
      subject:
        - "group:admin"
```

The 2nd resource is the one causing problem. Here is the related log:
```
time="2022-03-31T20:34:15+08:00" level=error msg="Configuration: failed to load configuration from yaml file(/config/configuration.yml) source: yaml: line 350: found unknown escape character"
```

I also tried the following but obviously it fails:
`"^/[a-zA-Z0-9-_]++$"`

```
level=error msg="Configuration: access control: rule #3 (domain 's.domain.example'): 'resources' option '^/[a-zA-Z0-9-_]++$' is invalid: error parsing regexp: invalid nested repetition operator: `++`"
```

### Expected Behaviour

Expect to start up without issue, and catch all ends with + sign.

### Reproduction Steps

Using the above config.

### Additional Information

I would like to catch all resources that ends with a plus sign, but I am not able to escape the plus sign, any thought? Thanks.

This is not the only rule in my config, but commenting it out allows me to start my Authelia without issue.
