### ISSUE TITLE
Problem using gmail smtp notifications

### ISSUE THREAD

**Issue by YouveGotMeowxy** [authelia/authelia#3164]
Hey all, this is my first time trying to setup an authelia docker container and after about 5 hours, lol, I think I have everything ironed out so far with the exception of the notifications.

For now, I'm simply trying to enter in my Gmail email address and after doing so, I'm greeted with this upon container start:

```
today at 12:31:25 AMtime="2022-04-11T00:31:25-05:00" level=info msg="Authelia v4.34.6 is starting"
today at 12:31:25 AMtime="2022-04-11T00:31:25-05:00" level=info msg="Log severity set to debug"
today at 12:31:25 AMtime="2022-04-11T00:31:25-05:00" level=info msg="Storage schema is being checked for updates"
today at 12:31:25 AMtime="2022-04-11T00:31:25-05:00" level=info msg="Storage schema is already up to date"
today at 12:31:25 AMtime="2022-04-11T00:31:25-05:00" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:465"
today at 12:31:25 AMtime="2022-04-11T00:31:25-05:00" level=info msg="Notifier SMTP client using submissions port 465. Make sure the mail server you are connecting to is configured for submissions and not SMTPS."
today at 12:31:35 AMtime="2022-04-11T00:31:35-05:00" level=error msg="Failure running the notification provider startup check: dial tcp 74.125.129.108:465: i/o timeout" stack="github.com/authelia/authelia/v4/internal/commands/root.go:104 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:78  cmdRootRun\ngithub.com/spf13/cobra@v1.4.0/command.go:860                  (*Command).execute\ngithub.com/spf13/cobra@v1.4.0/command.go:974                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.4.0/command.go:902                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1571                                      goexit"
today at 12:31:35 AMtime="2022-04-11T00:31:35-05:00" level=fatal msg="The following providers had fatal failures during startup: notification" stack="github.com/authelia/authelia/v4/internal/commands/root.go:120 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:78  cmdRootRun\ngithub.com/spf13/cobra@v1.4.0/command.go:860                  (*Command).execute\ngithub.com/spf13/cobra@v1.4.0/command.go:974                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.4.0/command.go:902                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1571                                      goexit"
today at 12:31:35 AMContainer stopped
```

My config looks like this (let me know if I need to post anything else from config and I'll be happy to do so):

```
notifier:
  disable_startup_check: false

  smtp:
    host: smtp.gmail.com
    port: 465
    timeout: 10s
    username: "redacted@gmail.com"

    ## The password used for SMTP authentication.
    ## Can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    #password: (I added this to a docker environment variable secret)

    sender: "My Name <redacted+autheliaOC@gmail.com>"
    identifier: "mydomain.com"
    subject: "[Authelia] {title}"
    startup_check_address: "redacted@gmail.com"
    disable_require_tls: false
    disable_html_emails: false

    tls:
      skip_verify: false
      minimum_version: TLS1.2
```

I'm using the same gmail smtp settings that I use in my nextcloud container (which is tested and working). I have a feeling I'm missing something stupid, but not sure what?

thanks for help! :)
