### ISSUE TITLE
nginx.ingress.kubernetes.io/auth-cache-duration don´t work

### ISSUE THREAD

**Issue by tgruenert** [authelia/authelia#3177]
I am not sure what kind of ticket this is. It might a question at first.

Given: 
WebApp in Kubernetes behind nginx-ingress

Problem:
Currently with every request on a web application authelia will be requested about the currently working user.
This can produce a lot of requests.

ngnix-ingress is configured like
``` 
  annotations: 
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://id.company.com/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://id.company.com" # The url the user will be redirected if she is not authenticated
    nginx.ingress.kubernetes.io/auth-cache-key: "$remote_user$http_authorization"
    nginx.ingress.kubernetes.io/auth-cache-duration: "200 202 10m, 401 1m"
```

What i expect is that ingress should only ask for authentication after 10 min after a successful authentication.
As far as i understand Authelia sets a cookie lifetime. This might influence nginx so it is not calculate a timeout by them self.
Session parameter "expiration" or "inactivity" in Authela have a default value so that can be forced not to be set.

Has anyone more information about this behavior or some solutions? 

Thank you 
... also for Authelia which is doing a great job since more than a year for us.
