### ISSUE TITLE
Individual Session Config per Subdomain

### ISSUE THREAD

**Issue by icegunner** [authelia/authelia#3201]
### Description

Have the ability to set session config per subdomain. So, making the session section in the configuration an array. This way, each subdomain specified would have its own timeouts and possibly secrets and other settings. Perhaps something similar to the access-control -> rules. I'm thinking something like:

``` yml
session:
  - name: subdomain_authelia_session
    secret: XXXXXXXXXXXXXXXX
    expiration: 1h
    inactivity: 20m
    remember_me_duration: 1M
    domain: subdomain.example.com
  - name: default_authelia_session
    secret: XXXXXXXXXXXXXXXX
    expiration: 1h
    inactivity: 5m
    domain: example.com
```

### Use Case

The use case here would be for multiple subdomains within a root domain to have different inactivity or expiration settings. So, in general, all subdomains in site would default to a 5 minute inactivity timeout. But, for one or more subdomains, they might take a while to go through and require a longer timeout.
In my particular case, I have multiple subdomains in my HomeLab. Having a 5 minute inactivity timeout is generally a good thing. However, a couple of the subdomains are places where I write lengthy text (e.g. writing a wiki) that takes me more than 5 minutes to do. If the inactivity is set to 5 minutes, then my session has expired before I can finish writing a wiki and it can't be saved until I re-authenticate.
