### ISSUE TITLE
Error disabling OIDC

### ISSUE THREAD

**Issue by JaneJeon** [authelia/authelia#3212]
### Description

This is so incredibly scuffed. When I tried to disable my oidc configuration, it said "Configuration: identity_providers: oidc: option 'clients' must have one or more clients configured" and would continuously crash.

### Expected Behaviour

For me to be able to disable my oidc configuration completely

### Reproduction Steps

I had something like this set up:

```yaml
identity_providers:
  oidc:
    clients:
      - id: portainer
        description: Portainer
        public: true
        authorization_policy: two_factor
        redirect_uris:
          - $URL
```

Which - before anyone else says it - WAS working. However, I no longer needed it so I commented out the entire section, which led to the crash above.

```yaml
# identity_providers:
#   oidc:
#     clients:
#       - id: portainer
#         description: Portainer
#         public: true
#         authorization_policy: two_factor
#         redirect_uris:
#           - $URL
```

So, given that Authelia was still trying to read the `identity_providers.oidc` section (even though I commented it out) I tried various levels of uncommenting (first, the `identity_providers` top-level section, then the `oidc`, then the `clients` with an empty array). None of them worked.

The only thing that worked is reverting my config to how it was.

So this seems like a regression somewhere between v4.34.6 and v4.35.0, where the bug is y'all are still trying to read `identity_providers.oidc.clients` even though I specifically deleted that whole section. I expect to be able to turn off that `identity_providers` section entirely

### Additional Information

_N/A_

**Comment by james-d-elliott** [comment]
I can't reproduce this with the information provided. I copied the exact  comment section into 4.35.0 and no errors.

**Comment by JaneJeon** [comment]
Well, the “after” would obviously be no client configuration at all, but I believe the error rises from first having a client registered, and _then_ commenting out that entire section.

**Comment by james-d-elliott** [comment]
I can't reproduce this either. Provide more information. Considering the below is not enough to configure OIDC I expect you've not provided your full OIDC configuration and the issue is unrelated to Authelia entirely.
```yaml
identity_providers:
  oidc:
    clients:
```

**Comment by JaneJeon** [comment]
> Considering the below is not enough to configure OIDC even with clients

Wait, but I already posted this on the first comment:

```yml

identity_providers:
  oidc:
    clients:
      - id: portainer
        description: Portainer
        public: true
        authorization_policy: two_factor
        redirect_uris:
          - $URL
```

Are you saying this configuration is incomplete? Because I’ve been using it in prod for several months…?
