### ISSUE TITLE
Ability to specify identity_providers.oidc.clients.[n].secret with environment variables.

### ISSUE THREAD

**Issue by alphabet5** [authelia/authelia#3249]
### Description

The ability to either substitute environment variables into the configuration, or overwrite with environment variables/files for client secrets.

```
Please Note: It is not possible to configure the access control rules section or OpenID Connect identity provider section using environment variables at this time.
```

### Use Case

I would like to be able to specify the client secret with a Kubernetes secret, to be shared between the client and authelia.

I'm not sure if something like `__0__` could be used for the index of the client list? 

It might be easier to allow {{ AUTHELIA_CUSTOM_ENV_NAME }} to be substituted into the config file?

**Comment by james-d-elliott** [comment]
I've spent quite a lot of time trying to figure out a reasonable solution for this. Unfortunately most solutions have large pitfalls.

I would point out you can actually define the entire OIDC section as a secret in k8s, the method of doing so can be achieved using the following snippets:

```yaml
      volumes:
        - name: config-oidc
          secret:
            secretName: authelia-acl
            items:
              - key: configuration.oidc.yaml
                path: configuration.oidc.yaml
            defaultMode: 420
```

```yaml
      containers:
        - name: authelia
          image: docker.io/authelia/authelia:fix-oidc-pre-configured-consent
          command:
            - authelia
          args:
            - '--config=/configuration.yaml'
            - '--config=/configuration.oidc.yaml'
```

```yaml
          volumeMounts:
            - name: config-oidc
              readOnly: true
              mountPath: /configuration.oidc.yaml
              subPath: configuration.oidc.yaml
```
