### ISSUE TITLE
Explore Implicit Consent

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#3277]
### Description

From my reading of https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest (see prompt) seems to indicate that users can remember consent (see pre-configured consent and #2598) but should be prompted for consent if the prompt type is consent, and https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess explicitly states the prompt type MUST be consent if the offline_access scope is requested, however https://openid.net/specs/openid-connect-core-1_0.html#Consent indicates the consent form may be in a variety of forms.

In addition several implementations of OpenID Connect seems to allow administrators to configure this consent process to be implicit rather than explicit; which while I don't think is a good measure for what you should implement, if you combine that factor with the last link it is an indication there is room for providers to decide how to handle this.

The intent of this FR is tracking, and opening the discussion and/or providing updates to the community.

### Use Case

See #2598.

**Comment by theAlevan** [comment]
I second this.

**Comment by james-d-elliott** [comment]
I actually made the first local commit for this today. I'm going to explore a new configuration format as follows:

```yaml
identity_providers:
   oidc:
     clients:
     - id: example
       consent:
         mode: implicit  # explicit, implicit, auto/default, preconfigured
         duration: 1M  # requires auto/default or preconfigured
```
