### ISSUE TITLE
Authelia and Gitlab OpenID

### ISSUE THREAD

**Issue by WladyX** [authelia/authelia#3303]
I'm trying to integrate Authelia with Gitlab.
I've created my configs based on:
https://docs.gitlab.com/ee/integration/openid_connect_provider.html
and 
https://www.authelia.com/docs/configuration/identity-providers/oidc.html

my gitlab.rb:
```
gitlab_rails['omniauth_providers'] = [
  {
    name: "openid_connect",
    label: "Authelia", # optional label for login button, defaults to "Openid Connect"
    icon: "https://avatars.githubusercontent.com/u/59122411?s=200&v=4",
    args: {
      name: "openid_connect",
      scope: ["openid","profile","email"],
      response_type: "code",
      issuer: "https://auth.example.com",
      discovery: true,
      client_auth_method: "query",
      uid_field: "preferred_username",
      send_scope_to_token_endpoint: "false",
      client_options: {
        identifier: "gitlab",
        secret: "mypass",
        redirect_uri: "https://gitlab.example.com/users/auth/openid_connect/callback"
      }
    }
  }
]
```

my authelia conf:
```
      - id: gitlab
        description: gitlab
        secret: mypass
        sector_identifier: ''
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: ''
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://gitlab.example.com/users/auth/openid_connect/callback
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code          
        response_modes:
          - query
          - form_post
        userinfo_signing_algorithm: none 
```
I've replaced my domain with example.com

The integration works ok, but gitlab does not seem to be able to match the user.
it says:
`Signing in using your Authelia account without a pre-existing GitLab account is not allowed.`
For my gitlab user i have added a new identity with Authelia and Identifier "email"
The user in gitlab has the same email as the one in authelia.
Any ideeas what could be wrong?
