### ISSUE TITLE
Authentication issue in in v4.35.4

### ISSUE THREAD

**Issue by ashwin-git-s** [authelia/authelia#3359]
## Bug Report

Authelia v4.35.4 seems to have issues authenticating. I've had to revert to an older docker build as a fix.
### Description
When trying to log into Authelia, the login fails and it generates the following error:

level=error msg="Unsuccessful 1FA authentication attempt by user 'XXXX': user 'XXXX' must have value for attribute 'uid'" method=POST path=/api/firstfactor remote_ip=10.1.1.113 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:233           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:53 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:53 AutheliaMiddleware.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.9/router.go:414                             (*Router).Handler\ngithub.com/valyala/fasthttp@v1.36.0/http.go:153                             (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.36.0/server.go:2338                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.36.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.36.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571                                                    goexit"

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

_N/A_

**Comment by james-d-elliott** [comment]
Could you please provide at least some information that we can utilize to replicate this? 4.35.4 100% works with openldap, Samba ActiveDirectory, Microsoft ActiveDirectory, etc. without this issue. This leads me to believe it's a configuration issue, so you'd probably want to provide that. The error indicates the user doesn't have a `uid` configured so the state of this is important. In addition you didn't even specify which "older docker build" you switched to which is critical in tracking down bugs.

**Comment by ashwin-git-s** [comment]
Thanks for your response.

Sorry, I should have provided more detail in my original report. Here it is now..

How to reproduce this error:
- I get this error that I originally reported when I try to login through the authelia web interface
- I get this error when using the latest official docker image

The work around for me was to go back to using v4.35.0 

Here's the authentication_backend section of my configuration (with redactions)

```
authentication_backend:
  disable_reset_password: true
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldaps://ldap.xxxx.com
    timeout: 5s
    start_tls: false
    tls:
      server_name: ldap.xxxx.com
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: DC=xxx,DC=xxx,DC=com
    username_attribute: uid
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(memberUid={input})(objectclass=posixGroup))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: uid
#    display_name_attribute: displayName
    user: CN=xxx,DC=xxx,DC=xxxx,DC=com
    password: xxxxxx
```

the username_attribute value is set to uid 

The config file that I'm using across the two version of Authelia is the same. The latest triggers the error reported above, and v4.35.0 works with no issues.

Appreciate any guidance you can provide on this.

**Comment by james-d-elliott** [comment]
Is the `uid` attribute actually set? It should only do this if it's empty.

**Comment by ashwin-git-s** [comment]
The uid attribute is set in LDAP

and everything works with the older versions of authelia.

Is there anything else that I can provide to troubleshoot?

**Comment by james-d-elliott** [comment]
I might produce a debug build, only thing that changed that could affect this is if the username attribute has a blank value which we were not checking before.

**Comment by james-d-elliott** [comment]
Can you try `authelia/authelia:debug-ldap` with the log level set to 'debug'? Also instead of replacing usernames with XXXX pick a unique but generic  username unique to each user. i.e. if you have a use named `ashwin` you can replace it with `john`, but only replace that username with `john` to avoid confusion. Some generic usernames that I can think of:

john
mary
gary
sarah
harry
mel

**Comment by ashwin-git-s** [comment]
Thanks. 

I've updated the service to user image: authelia/authelia:debug-ldap

I've change configuration.yml to

```
##############################################################################
#                   Authelia configuration  thehomelab.wiki                  #
##############################################################################

server:
  host: 0.0.0.0
  port: 9091 # if you need this changed make sure it reflects also in the docker-compose.yml
log:
  level: debug
#  level: debug
```

What I see in logs...

```
time="2022-05-15T10:30:50+10:00" level=debug msg="Mark 1FA authentication attempt made by user 'ashwin'" method=POST path=/api/firstfactor remote_ip=10.1.1.113
time="2022-05-15T10:30:50+10:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'ashwin': user 'ashwin' must have value for attribute 'uid'" method=POST path=/api/firstfactor remote_ip=10.1.1.113 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:233           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:53 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:53 AutheliaMiddleware.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.9/router.go:414                             (*Router).Handler\ngithub.com/valyala/fasthttp@v1.36.0/http.go:153                             (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.36.0/server.go:2338                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.36.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.36.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571                                                    goexit"
```

Is there some place else I should be looking for debug logs other than just output of _docker logs -f authelia_ ?

The above is all that I see when I try to login.
