### ISSUE TITLE
how to make  OpenID Connect serve two Clients 

### ISSUE THREAD

**Issue by abe520** [authelia/authelia#3391]
```
identity_providers:
  oidc:
    clients:
      - id: some id you want to use on the client
        description: Some description you want to shown on the Authelia consent page
        secret: some secret string which should also be entered in the proxmox config
        public: false
        authorization_policy: two_factor
        audience: []
        scopes:
          - openid
        redirect_uris:
          - https://proxmox.example.com
        userinfo_signing_algorithm: none
      - id: portainer_client_id
        description: Some description you want to shown on the Authelia consent page
        secret: some secret string which should also be entered in the portainer config
        public: false
        authorization_policy: two_factor
        audience: []
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://portainer.example.com
        userinfo_signing_algorithm: none

```
