### ISSUE TITLE
Authelia & Portainer?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [authelia/authelia#3396]
I followed this guide to get Authelia working with Portainer: [link](https://www.authelia.com/docs/community/oidc-integrations/portainer.html)

But I still get "**Unauthorized**" after the consent screen.

Can someone who's gotten this working verify my config please?

_Note: asterisks are for redaction, but they all match the respective fields in Portainer._

Portainer:

![image](https://user-images.githubusercontent.com/39491297/168890820-553ea2ca-682f-41d3-a85b-a26e85dcad42.png)

Authelia `configuration.yml`

```
    clients:

      ## The ID is the OpenID Connect ClientID which is used to link an application to a configuration.
      - id: "[**]-portainer"

        ## The description to show to users when they end up on the consent screen. Defaults to the ID above.
        description: "[**] Portainer"

        ## The client secret is a shared secret between Authelia and the consumer of this client.
        secret: "<random string of alphanumeric that I also placed on the client secret line in Portainer>"

        ## Sets the client to public. This should typically not be set, please see the documentation for usage.
        public: false

        ## The policy to require for this client; one_factor or two_factor.
        authorization_policy: two_factor

        ## Audience this client is allowed to request.
        audience: []

        ## Scopes this client is allowed to request.
        scopes:
          - openid
          - profile
          - groups
          - email

        ## Redirect URI's specifies a list of valid case-sensitive callbacks for this client.
        redirect_uris:
          - "https://portainer.*******.****"

        ## Grant Types configures which grants this client can obtain.
        ## It's not recommended to define this unless you know what you're doing.
        # grant_types:
          # - refresh_token
          # - authorization_code

        ## Response Types configures which responses this client can be sent.
        ## It's not recommended to define this unless you know what you're doing.
        # response_types:
          # - code

        ## Response Modes configures which response modes this client supports.
        # response_modes:
          # - form_post
          # - query
          # - fragment

        ## The algorithm used to sign userinfo endpoint responses for this client, either none or RS256.
        userinfo_signing_algorithm: none
```

It _seems_ like it's pooping out on the user to login as, but I could be wrong(?). Is `preferred_username` supposed to be _literally_ that? I don't see any `preferred_username` anywhere else in either Authelia or portainer? I also tried replacing `preferred_username` with the username of my portainer user, but get the same result.

**Comment by james-d-elliott** [comment]
`preferred_username` is a claim which maps to the users actual username. What do the logs say?

**Comment by F0x06** [comment]
Hi, i managed to successfully configure portainer with Authelia using following settings

<img width="648" alt="image" src="https://user-images.githubusercontent.com/7167311/169249555-b0e103f3-6158-4030-a697-a742d4abaf8c.png">

```yml
identity_providers:
  oidc:
    hmac_secret: my secret
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      RSAKEY
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - https://example.com
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: portainer
        description: Portainer
        secret: my secret
        sector_identifier: ''
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1m
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://portainer.example.com
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```

**Comment by YouveGotMeowxy** [comment]
@F0x06 TY, I gave your configs a compare with mine, and added the stuff in yours that wasn't in mine, but still not luck unfortunately.

**Comment by YouveGotMeowxy** [comment]
> What do the logs say?

Just so I'm clear how it works; I have an Authelia user named "kacey" that I login with. And the user name in my Portainer is also simply "kacey" .... is that how it's supposed to work so that they match up?

Here is the log:

```
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"debug","method":"GET","msg":"Authorization Request with id '64c1af9c-e4a6-4fce-a435-401983052520' on client with id '[**]-portainer' is being processed","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"debug","method":"GET","msg":"Consent Session is being checked for pre-configuration with signature of client id '[**]-portainer' and subject '9679cc00-c27d-4a70-8998-a9564d97b1fb'","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"debug","method":"GET","msg":"Consent Session checked for pre-configuration with signature of client id '[**]-portainer' and subject '9679cc00-c27d-4a70-8998-a9564d97b1fb' did not find any results","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"debug","method":"GET","msg":"Authorization Request with id '64c1af9c-e4a6-4fce-a435-401983052520' on client with id '[**]-portainer' proceeding to generate a new consent due to unsuccessful lookup of pre-configured consent","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Replied (status=302)","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/consent","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Replied (status=200)","path":"/consent","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/manifest.json","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Replied (status=200)","path":"/manifest.json","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/locales/en/portal.json","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Replied (status=200)","path":"/locales/en/portal.json","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/locales/en-US/portal.json","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Replied (status=200)","path":"/locales/en-US/portal.json","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/api/user/info","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:55 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/api/oidc/consent","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:55-05:00"}
today at 1:43:56 PM{"level":"trace","method":"GET","msg":"Replied (status=200)","path":"/api/user/info","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:56-05:00"}
today at 1:43:56 PM{"level":"trace","method":"GET","msg":"Replied (status=200)","path":"/api/oidc/consent","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:56-05:00"}
today at 1:43:57 PM{"level":"trace","method":"POST","msg":"Request hit","path":"/api/oidc/consent","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"trace","method":"POST","msg":"Replied (status=200)","path":"/api/oidc/consent","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"trace","method":"GET","msg":"Request hit","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"debug","method":"GET","msg":"Authorization Request with id '202158a8-41f7-42a7-9ef0-b0853161109b' on client with id '[**]-portainer' is being processed","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"debug","method":"GET","msg":"Authorization Request with id '202158a8-41f7-42a7-9ef0-b0853161109b' on client with id '[**]-portainer' proceeding to lookup consent by challenge id '8c847aa9-2e35-415f-8404-dfee56f46209'","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"debug","method":"GET","msg":"Authorization Request with id '202158a8-41f7-42a7-9ef0-b0853161109b' loaded consent session with id '8' and challenge id '8c847aa9-2e35-415f-8404-dfee56f46209' for client id '[**]-portainer' and subject '9679cc00-c27d-4a70-8998-a9564d97b1fb' and scopes 'openid profile groups email'","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"debug","method":"GET","msg":"Authorization Request with id '202158a8-41f7-42a7-9ef0-b0853161109b' on client with id '[**]-portainer' was successfully processed, proceeding to build Authorization Response","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"trace","method":"GET","msg":"Authorization Request with id '202158a8-41f7-42a7-9ef0-b0853161109b' on client with id '[**]-portainer' creating session for Authorization Response for subject '9679cc00-c27d-4a70-8998-a9564d97b1fb' with username 'kacey' with claims: \u0026{JTI: Issuer:https://authelia.mydomain.com Subject:9679cc00-c27d-4a70-8998-a9564d97b1fb Audience:[[**]-portainer] Nonce: ExpiresAt:0001-01-01 00:00:00 +0000 UTC IssuedAt:2022-05-20 13:43:57.878751399 -0500 CDT m=+217.713130326 RequestedAt:2022-05-20 18:43:55 +0000 UTC AuthTime:2022-05-20 13:42:37 -0500 CDT AccessTokenHash: AuthenticationContextClassReference: AuthenticationMethodsReferences:[pwd otp mfa] CodeHash: Extra:map[azp:[**]-portainer client_id:[**]-portainer email:redacted@gmail.com email_verified:true groups:[admin co-admin family user guest] name:kacey preferred_username:kacey]}","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"error","method":"GET","msg":"Authorization Response for Request with id '202158a8-41f7-42a7-9ef0-b0853161109b' on client with id '[**]-portainer' could not be created: The Authorization Server requires End-User authentication. Failed to validate OpenID Connect request because prompt was set to 'login' but auth_time ('2022-05-20 13:42:37 -0500 CDT') happened before the authorization request ('2022-05-20 18:43:55 +0000 UTC') was registered, indicating that the user was not re-authenticated which is forbidden.","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","stack":[{"File":"github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go","Line":108,"Name":"OpenIDConnectAuthorizationGET"},{"File":"github.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go","Line":113,"Name":"NewHTTPToAutheliaHandlerAdaptor.func1"},{"File":"github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go","Line":53,"Name":"AutheliaMiddleware.func1.1"},{"File":"github.com/authelia/authelia/v4/internal/middlewares/headers.go","Line":25,"Name":"SecurityHeadersCSPNone.func1"},{"File":"github.com/authelia/authelia/v4/internal/middlewares/headers.go","Line":35,"Name":"SecurityHeadersNoStore.func1"},{"File":"github.com/authelia/authelia/v4/internal/middlewares/headers.go","Line":16,"Name":"SecurityHeaders.func1"},{"File":"github.com/fasthttp/router@v1.4.9/router.go","Line":414,"Name":"(*Router).Handler"},{"File":"github.com/valyala/fasthttp@v1.36.0/http.go","Line":153,"Name":"(*Response).StatusCode"},{"File":"github.com/authelia/authelia/v4/internal/middlewares/strip_path.go","Line":22,"Name":"StripPath.func1.1"},{"File":"github.com/valyala/fasthttp@v1.36.0/server.go","Line":2338,"Name":"(*Server).serveConn"},{"File":"github.com/valyala/fasthttp@v1.36.0/workerpool.go","Line":224,"Name":"(*workerPool).workerFunc"},{"File":"github.com/valyala/fasthttp@v1.36.0/workerpool.go","Line":196,"Name":"(*workerPool).getCh.func1"},{"File":"runtime/asm_amd64.s","Line":1571,"Name":"goexit"}],"time":"2022-05-20T13:43:57-05:00"}
today at 1:43:57 PM{"level":"trace","method":"GET","msg":"Replied (status=303)","path":"/api/oidc/authorization","remote_ip":"1.2.3.4","time":"2022-05-20T13:43:57-05:00"}
```

**Comment by YouveGotMeowxy** [comment]
@james-d-elliott 

Also, do I need to create an access token for my user under User Settings in portainer? I've never created one:

![image](https://user-images.githubusercontent.com/39491297/169594832-6bcaae63-c786-4f24-bc1b-f8d521e8c0f0.png)

**Comment by F0x06** [comment]
> 

Hmmm, in my case i have the following user defined in `users_database.yml`
```yml
users:
  admin:
    displayname: "Admin"
    password: "$argon2id...."
    email: email@domain.com
    groups:
      - admins
      - dev
```

I have no idea what's the problem :/

**Comment by F0x06** [comment]
> @james-d-elliott
> 
> Also, do I need to create an access token for my user under User Settings in portainer? I've never created one:
> 
> ![image](https://user-images.githubusercontent.com/39491297/169594832-6bcaae63-c786-4f24-bc1b-f8d521e8c0f0.png)

I've not used it

**Comment by bodycount28** [comment]
For your reverse proxy, have you configured it to trust header exchange?  I use Traefik and had to add the following as a middleware:

![image](https://user-images.githubusercontent.com/85305683/169603033-57d00050-728a-4445-ae7f-e2e203163706.png)

**Comment by F0x06** [comment]
My authelia docker config
```yml
  traefik-authelia:
    image: authelia/authelia
    container_name: traefik-authelia
    network_mode: host
    volumes:
      - $PWD/storage/authelia:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.example.com`)'
      - 'traefik.http.routers.authelia.tls.certresolver=le'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.services.authelia.loadbalancer.server.port=9091'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://localhost:9091/api/verify?rd=https://login.example.com/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://localhost:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
```
