### ISSUE TITLE
authelia won't redirect after successful 1FA authentication

### ISSUE THREAD

**Issue by basicallynewbie** [authelia/authelia#3523]
### Description

 I deployed traefik with authelia in docker.When app using authelia-secure-forwardAuth,it will do a failed redirection and return to authelia page after successful 1FA authentication.But when app using authelia-basic-forwardAuth,it works normal.
 Without 2FA configed,and just go to authelia page login,it does redirect to default_redirection_url after successful 1FA authentication,and other apps still won't redirect.But after 2FA was configed,authelia page won't redirect to anywhere,and other apps still the same.

### Expected Behaviour 

App will redirect to the right page after successful 1FA authentication with authelia-secure-forwardAuth.Authelia page will redirect to default_redirection_url with or without 2FA configed.

### Reproduction Steps

Frist I deployed traefik,and reverse-proxyed apps,they works fine.Then deployed  authelia without 2FA configed,I can go to the authelia page and redirect to default_redirection_url.Then I point apps' middlewares to authelia-basic-forwardAuth,everything work normal.Then change to authelia-secure-forwardAuth,nothing working right.Setting up 2FA,authelia page won't redirect.

### Additional Information

traefik docker compose
```
version: '3'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/me/docker/traefik:/etc/traefik:ro
      - /home/me/docker/traefik/config.yml:/config.yml:ro
      - /home/me/docker/traefik/certs:/etc/traefik/certs
      - /home/me/docker/traefik/logs:/etc/traefik/logs
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.entrypoints=web'
      - 'traefik.http.routers.traefik.rule=Host(`subdomain1.example.com`)'
      - 'traefik.http.routers.traefik-secure.entrypoints=websecure'
      - 'traefik.http.routers.traefik-secure.rule=Host(`subdomain1.example.com`)'
      - 'traefik.http.routers.traefik-secure.service=api@internal'
      - 'traefik.http.routers.traefik-secure.tls=true'
      - 'traefik.http.routers.raefik-secure.tls.certresolver=production'
      - 'traefik.http.routers.traefik.middlewares=https-redirect'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
```
traefik.yml
```
global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: DEBUG
  filePath: /etc/traefik/logs/traefik.log
accessLog:
  filePath: /etc/traefik/logs/traefik-access.log
api:
  dashboard: true
  debug: true
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
certificatesResolvers:
   staging:
     acme:
       email: myemail
       storage: /etc/traefik/certs/acme.json
       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
       dnsChallenge:
          provider: duckdns
   production:
     acme:
       email: myemail
       storage: /etc/traefik/certs/acme.json
       caServer: "https://acme-v02.api.letsencrypt.org/directory"
       dnsChallenge:
          provider: duckdns
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /config.yml
    directory: /etc/traefik
    watch: true
```
config.yml
```
http:
  routers:
    app:
      entryPoints:
        - web
      rule: "Host(`subdomain2.example.com`)"
      middlewares:
        - https-redirectscheme
      service: app
    app-secure:
      entryPoints:
        - websecure
      rule: "Host(`subdomain2.example.com`)"
      middlewares:
        - default-headers
        - authelia-basic@docker
        #- authelia-secure@docker
      tls: 
        certResolver: production
      service: app
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://192.168.0.130:180"
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
```
authelia docker compose
```
version: '3'

services:

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /home/me/docker/authelia/config:/config
    network_mode: "bridge"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.entrypoints=web'
      - 'traefik.http.routers.authelia.rule=Host(`subdomain3.example.com`)'
      - 'traefik.http.routers.authelia-secure.entrypoints=websecure'
      - 'traefik.http.routers.authelia-secure.rule=Host(`subdomain3.example.com`)'
      - 'traefik.http.routers.authelia-secure.tls=true'
      - 'traefik.http.routers.authelia-secure.tls.certresolver=production'
      - 'traefik.http.routers.authelia.middlewares=https-redirect'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.authelia-secure.forwardauth.address=http://192.168.0.130:9091/api/verify?rd=https%3A%2F%2Fsubdomain3.example.com%2F'
      - 'traefik.http.middlewares.authelia-secure.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-secure.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://192.168.0.130:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
    ports:
      - "9091:9091"
    expose:
      - 9091
    restart: unless-stopped
```
configuration.yml
```
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: ""
default_redirection_url: https://subdomain3.example.com/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: true

log:
  level: trace
  format: json
  file_path: /config/authelia.log
  keep_stdout: true

theme: dark

totp:
  issuer: subdomain3.example.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: true
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  networks:
  - name: internal
    networks:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/18
  rules:
    ## bypass rule
    - domain: 
        - "subdomain3.example.com" 
      policy: bypass
    ## catch-all
    - domain:
        - "subdomain2.example.com"
      policy: one_factor
    #- domain: "subdomain1.example.com1"
    #  policy: two_factor

session:
  name: authelia_session
  domain: example.com
  same_site: lax
  secret: ""
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 15m

storage:
  encryption_key: ""
    path: /config/db.sqlite3
  
notifier:
  filesystem:
    filename: /config/notification.txt
```
[traefik.log.txt](https://github.com/authelia/authelia/files/8908680/traefik.log.txt)
[traefik-access.log.txt](https://github.com/authelia/authelia/files/8908725/traefik-access.log.txt)
[authelia.log.txt](https://github.com/authelia/authelia/files/8908742/authelia.log.txt)
