### ISSUE TITLE
config question

### ISSUE THREAD

**Issue by YouveGotMeowxy** [authelia/authelia#3545]
I basically just want all users to use two factor for my  subdomains. With my current config, it seems that for s**ome of the subdomains it works correctly**, while **some give me a "forbidden to user" error,** even when I've logged into Authelia and selected to Remember the user, so that I stay logged in, and this is what's got me faclempt. :P

The error (happens on a couple of sub domains I've noticed so far):

```
today at 12:58:41 AM{"level":"info","method":"GET","msg":"Access to https://gotify.redacted.rocks/ is forbidden to user kacey","path":"/api/verify","remote_ip":"re.dac.ted","time":"2022-06-19T00:58:41-05:00"}
today at 12:58:41 AM{"level":"info","method":"GET","msg":"Access to https://phpmyadmin.redacted.rocks/favicon.ico is forbidden to user kacey","path":"/api/verify","remote_ip":"re.dac.ted","time":"2022-06-19T00:58:41-05:00"}
```

My config:

```
access_control:
  default_policy: deny

  networks:
    - name: internal
      networks: '10.0.0.0/16'

  rules:
    - domain: '*.redacted.rocks'
      policy: two_factor
      networks: 'internal'
      subject:
        - ['user:kacey', 'user:bob']
        - ['group:admin', 'group:family']
```

I've also tried without the "subject" key/values entirely (actually, originally it didnt have those, and I added them to try and work past this issue).

What am I doing wrong?
