### ISSUE TITLE
OIDC 500 error when using RS256 for userinfo_signing_algorithm on various apps

### ISSUE THREAD

**Issue by kernelkaribou** [authelia/authelia#3641]
### Description

When setting the userinfo_signing_algorithm parameter for and OIDC client to RS256, various services will get an error 500.

### Expected Behaviour

Ability to enable RS256 for userinfo_signing_algorithm in OpenID Connect client settings.

### Reproduction Steps

Demonstrated in both Gitea and Portainer using oauth2. Example configuration for gitea

![image](https://user-images.githubusercontent.com/25406580/176573764-253bf1c7-7b3b-44e1-821a-30bbe81f3d3c.png)

Config for Gitea OpenID client in authelia configuration.yml

```
      - id: gitea
        description: 
        secret: gitea_client_secret
        public: false
        authorization_policy: one_factor
        audience: []
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://gitea.example.com/user/oauth2/authelia/callback
        userinfo_signing_algorithm: RS256
```

This will fail with the error in Gitea

```
2022/06/29 20:21:40 ...rs/web/auth/oauth.go:845:SignInOAuthCallback() [E] [62bcfaa4] UserSignIn: invalid character 'e' looking for beginning of value
2022/06/29 20:21:40 [62bcfaa4] router: completed GET /user/oauth2/authelia/callback?code=SoMeLoNgCoDeStRiNgHeRe&scope=openid&state=ba50284a-6e95-4746-acf4-41e9286f7be3 for 10.0.10.90:0, 500 Internal Server Error in 45.9ms @ auth/oauth.go:808(auth.SignInOAuthCallback)
```

Same configuration as above for Portainer with appropriate changes like redirect URI produces similar error

```
time="2022-06-30T01:23:32Z" level=info msg="2022/06/30 01:23:32 [DEBUG] - OAuth authentication error: invalid character 'e' looking for beginning of value"
time="2022-06-30T01:23:32Z" level=info msg="2022/06/30 01:23:32 http error: Unable to authenticate through OAuth (err=Unauthorized) (code=500)"
```

Changing the userinfo_signing_algorithm below and restarting Authelia will immediately address the issue on both Gitea and Portainer.

`userinfo_signing_algorithm : none`

### Additional Information

While seemingly Authelia is the common denominator, Bookstack which has the same configuration above can use either none or RS256 as the value for userinfo_signing_algorithm without issue. May be worth updating documentation at minimum to indicate this value may not work for all applications, if issue cannot be determined or controlled.

This is related to discussion specific to gitea that the "workaround" was discovered.
[ EOF using OIDC in Gitea #3057 ](https://github.com/authelia/authelia/issues/3057)
