### ISSUE TITLE
User specific subfolder access is no longer working with 4.36

### ISSUE THREAD

**Issue by HannesJo0139** [authelia/authelia#3692]
Updating from 4.35.6 to 4.36.2 users have no access to user specific subfolders anymore. The following access control gives userN access to example.com/photoprism/userN and denies anything else under example.com/photoprism/... 
```
    # Allow photoprism for corresponding users:
    - domain: example.org
      resources:
      - '^/photoprism/user1/.*$'
      subject: 'user:user1'
      policy: two_factor
    - domain: example.org     
      resources:
      - '^/photoprism/user2/.*$'
      subject: 'user:user2'
      policy: two_factor
    # Deny photoprism for other users:
    - domain: example.org
      resources:
      - '^/photoprism/(.+)$'
      policy: deny
```

After updating to 4.36.2, no user is able to access anymore. Error 403. Log says `Access to https://example.org/photoprism/user1/ is forbidden to user user1`

----

As with 4.36, PR https://github.com/authelia/authelia/pull/3597 should have been applied, I also tested 
```
    - domain: example.org
      resources:
      - '^/photoprism/(?P<User>\w+)[/?].*$'
      policy: two_factor
```

It is also not working anymore.

**Comment by james-d-elliott** [comment]
For now make the suffix optional:

```yaml
    # Allow photoprism for corresponding users:
    - domain: example.org
      resources:
      - '^/photoprism/user1(/.*)?$'
      subject: 'user:user1'
      policy: two_factor
    - domain: example.org     
      resources:
      - '^/photoprism/user2(/.*)?$'
      subject: 'user:user2'
      policy: two_factor
    # Deny photoprism for other users:
    - domain: example.org
      resources:
      - '^/photoprism(/(.+))?$'
      policy: deny
```

```yaml
access_control:
  rules:
  - domain: example.org
    resources:
    - '^/photoprism/(?P<User>\w+)([/?].*)?$'
    policy: one_factor
```
