### ISSUE TITLE
Notifier SMTP client encountered error during cleanup: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by Saidou83** [authelia/authelia#3700]
Hi all,

I'm using Authelia in combination with Traefik through docker.
I recently tried to configure the SMTP notifier with my own domain, but I can't get it to work.
I'm getting this error: _"Notifier SMTP client encountered error during cleanup: x509: certificate has expired or is not yet valid"_
My certificates are still valid until March 2023 and I can send/receive mail with other clients.
Tried a fresh setup, but can't figure it out...
Probably it is something stupid :) But if anyone can help me?
You can find the log-file, configuration.yml and docker-compose.yml underneath.

Thanks a lot!

#### Log-file:

```log
time="2022-07-13T14:09:04+02:00" level=info msg="Authelia v4.36.2 is starting"
time="2022-07-13T14:09:04+02:00" level=info msg="Log severity set to debug"
time="2022-07-13T14:09:04+02:00" level=info msg="Storage schema is being checked for updates"
time="2022-07-13T14:09:04+02:00" level=info msg="Storage schema is already up to date"
time="2022-07-13T14:09:04+02:00" level=debug msg="Notifier SMTP client attempting connection to mail.example.com:587"
time="2022-07-13T14:09:04+02:00" level=debug msg="Notifier SMTP client connected successfully"
time="2022-07-13T14:09:04+02:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: mail.example.com), attempting"
time="2022-07-13T14:09:04+02:00" level=warning msg="Notifier SMTP client encountered error during cleanup: x509: certificate has expired or is not yet valid: current time 2022-07-13T14:09:04+02:00 is after 2022-03-11T18:30:30Z"
time="2022-07-13T14:09:04+02:00" level=error msg="Failure running the notification provider startup check: x509: certificate has expired or is not yet valid: current time 2022-07-13T14:09:04+02:00 is after 2022-03-11T18:30:30Z" stack="github.com/authelia/authelia/v4/internal/commands/root.go:161 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:77  cmdRootRun\ngithub.com/spf13/cobra@v1.5.0/command.go:876                  (*Command).execute\ngithub.com/spf13/cobra@v1.5.0/command.go:990                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.5.0/command.go:918                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1571                                      goexit"
time="2022-07-13T14:09:04+02:00" level=fatal msg="The following providers had fatal failures during startup: notification" stack="github.com/authelia/authelia/v4/internal/commands/root.go:177 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:77  cmdRootRun\ngithub.com/spf13/cobra@v1.5.0/command.go:876                  (*Command).execute\ngithub.com/spf13/cobra@v1.5.0/command.go:990                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.5.0/command.go:918                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1571                                      goexit"
```
#### configuration.yml
```yaml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
theme: dark
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: #set with docker labels
default_redirection_url: https://auth.example.com
totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # External subdomains
    - domain: "*.example.com"
      policy: two_factor
    # Individual sites
    - domain: traefik-dashboard.local.example.com
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: #unsecure_session_secret
  expiration: 3600 # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: # Now required  #set with docker labels
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: auth.example.com
    ## This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    #password: # Now required  #set with docker labels
    host: mail.example.com
    port: 587
    sender: auth@example.com
  #filesystem:
    #filename: /config/notification.txt

...
```
#### docker-compose.yml
```yaml
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /home/user/appdata/authelia:/config
    networks:
      - proxy
    secrets:
      - jwt
      - session
      - encryption_key
      - smtp
#      - duo
#      - redis
#      - mysql
#      - ldap
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.local.example.com`,`auth.example.com`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.example.com'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: always
    environment:
      - TZ=Europe/Brussels
      ##SECRETS##
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/encryption_key
#      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/duo
#      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/redis
#      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/mysql
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp
#      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap
    healthcheck:
      disable: true

secrets:
  jwt:
    file: /home/user/appdata/authelia/secrets/jwt
  session:
    file: /home/user/appdata/authelia/secrets/session
  encryption_key:
    file: /home/user/appdata/authelia/secrets/encryption_key
#  duo:
#    file: /home/user/appdata/authelia/secrets/duo
#  redis:
#    file: /home/user/appdata/authelia/secrets/redis
#  mysql:
#    file: /home/user/appdata/authelia/secrets/mysql
  smtp:
    file: /home/user/appdata/authelia/secrets/smtp
#  ldap:
#    file: /home/user/appdata/authelia/secrets/ldap
```
