### ISSUE TITLE
[Traefik] Extent RequestUrlGetter to respect `x-forwarded-prefix`

### ISSUE THREAD

**Issue by niosHD** [authelia/authelia#372]
I started playing around with the comparably new Traefik support and overall things work quite nicely. Thank you for working on it! I just found one small "issue" that is hopefully easy to fix.

In particular, when using Authelia with Traefik 1.7 and a [matcher like `PathPrefixStrip`](https://docs.traefik.io/v1.7/basics/#matchers) the redirect URL after authentication is incorrect. Authelia redirects to the URL with the stripped prefix instead of the original URL. As workaround, I currently set the `x-original-url` header but having also such matchers work out-of-the-box would be even better.

Traefik exposes the missing URL component via the `x-forwarded-prefix` header. Subsequently, including this information when determining the original URL based on the `x-forwarded-*` headers should fix the problem.

**Comment by clems4ever** [comment]
Hello @niosHD , I'm not an expert in Traefik configuration so I might not fully understand the issue. Do you an example of non working configuration?

**Comment by niosHD** [comment]
Hello @clems4ever, sure.

The following docker-compose file starts two containers based on the `mendhak/http-https-echo:latest` image which simply shows the received http headers. The first container is called *echo* and gets served under `https://demo.tld/echo`. The second container is called *headers* and is reached under `https://demo.tld/headers`. Both use the same authelia service (hosted on `https://auth.demo.tld`) that is configured for single factor authentication on `demo.tld`.

The only difference between the two services is the `traefik.frontend.rule` where *echo* uses the **PathPrefix** matcher while *headers* uses the **PathPrefixStrip** matcher. This is useful for exposing web applications in a sub folder instead on a subdomain. The stripped part is exposed via the `x-forwarded-prefix` header.

~~~yaml
version: '3'

services:
  echo:
    image: mendhak/http-https-echo:latest
    labels:
      - "traefik.enable=true"
      - "traefik.backend=echo"
      - "traefik.port=80"
      - "traefik.frontend.priority=100"
      - "traefik.frontend.rule=Host:demo.tld;PathPrefix:/echo"
      - "traefik.frontend.auth.forward.address=https://auth.demo.tld/api/verify?rd=https://auth.demo.tld/%23/"
      - "traefik.frontend.auth.forward.authResponseHeaders=Remote-User,Remote-Groups"
    networks:
      - web-proxy

  headers:
    image: mendhak/http-https-echo:latest
    labels:
      - "traefik.enable=true"
      - "traefik.backend=headers"
      - "traefik.port=80"
      - "traefik.frontend.priority=100"
      - "traefik.frontend.rule=Host:demo.tld;PathPrefixStrip:/headers"
      - "traefik.frontend.auth.forward.address=https://auth.demo.tld/api/verify?rd=https://auth.demo.tld/%23/"
      - "traefik.frontend.auth.forward.authResponseHeaders=Remote-User,Remote-Groups"
      # - "traefik.frontend.headers.customRequestHeaders=X-ORIGINAL-URL:https://demo.tld/headers/"

    networks:
      - web-proxy
networks:
  web-proxy:
    external: true
~~~

Accessing the *echo* service (without prior authentication) correctly forwards to authelia on `https://auth.demo.tld/#/?rd=https://demo.tld/echo` for authentication. However, for the *headers* service the redirect URL is wrong and forwards to `https://auth.demo.tld/#/?rd=https://demo.tld/`.

I currently have to provide the correct URL via the `x-original-url` header to work around the problem. (see commented line in `docker-compose.yml`).

**Comment by clems4ever** [comment]
Sorry @niosHD , did not have time to deep into that issue but now I can. This use case makes sense and was not foreseen. I'll read the doc of X-Forwarded-Prefix and see what I can do.

**Comment by clems4ever** [comment]
Hello @niosHD , are you using v3 of Authelia? If yes, I advise you to test v4 because Traefik v1 and v2 are fully supported now. You can check the doc at https://docs.authelia.com.

Please keep us posted.

**Comment by niosHD** [comment]
Hi @clems4ever, I am on Authelia v4 now but was on v3 when I opened the issue. However, the issue is still not resolved yet.

I don't really know go but I would expect that the `x-forwarded-prefix` handling has to be added to https://github.com/authelia/authelia/blob/master/internal/handlers/handler_verify.go#L43.

Thank you for looking into it!

**Comment by nightah** [comment]
@niosHD I've just attempted to reproduce this with Authelia v4 and Traefik v2 and have been unsuccessful in doing so.

I utilised our compose bundles in `compose/local/` and made some small modifications for both the PathPrefix and StripPrefix, in `public.example.com` and `secure.example.com` respectively.

Attached is a snippet including all Authelia, Traefik and whoami container configurations:

```yaml
version: '3.3'

networks:
  net:
    driver: bridge

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./authelia:/var/lib/authelia
      - ./configuration.yml:/etc/authelia/configuration.yml:ro
      - ./users_database.yml:/etc/authelia/users_database.yml
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.example.com`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.options=default'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.example.com'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne

  traefik:
    image: traefik:v2.2
    container_name: traefik
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.example.com`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.options=default'
      - 'traefik.http.routers.api.middlewares=authelia@docker'
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.file.filename=/etc/traefik/certificates.yml'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--log=true'
      - '--log.level=DEBUG'
      - '--log.filepath=/var/log/traefik.log'

  secure:
    image: containous/whoami
    container_name: secure
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.secure.rule=Host(`secure.example.com`)'
      - 'traefik.http.routers.secure.entrypoints=https'
      - 'traefik.http.routers.secure.tls=true'
      - 'traefik.http.routers.secure.tls.options=default'
      - 'traefik.http.routers.secure.middlewares=authelia@docker, secure@docker'
      - 'traefik.http.middlewares.secure.stripprefix.prefixes=/health'
    expose:
      - 80
    restart: unless-stopped

  public:
      image: containous/whoami
      container_name: public
      networks:
        - net
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.public.rule=Host(`public.example.com`) && PathPrefix(`/public`)'
        - 'traefik.http.routers.public.entrypoints=https'
        - 'traefik.http.routers.public.tls=true'
        - 'traefik.http.routers.public.tls.options=default'
        - 'traefik.http.routers.public.middlewares=authelia@docker'
      expose:
        - 80
      restart: unless-stopped
```

Upon visiting `secure.example.com/health` I am sent to the Authelia portal to authenticate and the refer is set to `https://secure/example.com/health`.

Here's the extract from the whoami container showing that the PrefixStrip also was successful:
```
Hostname: 93881f2f92c4
IP: 127.0.0.1
IP: 172.18.0.2
RemoteAddr: 172.18.0.5:41154
GET / HTTP/1.1
Host: secure.example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cookie: authelia_session=VYYwOlPnySYwReBYoLXrYKOKqHYlPTsb
Referer: https://authelia.example.com/2fa/one-time-password?rd=https%3A%2F%2Fsecure.example.com%2Fhealth
Te: trailers
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 172.18.0.1
X-Forwarded-Host: secure.example.com
X-Forwarded-Port: 443
X-Forwarded-Prefix: /health
X-Forwarded-Proto: https
X-Forwarded-Server: 754c251c1df7
X-Real-Ip: 172.18.0.1
```
