### ISSUE TITLE
Authelia gives 401 on PROPFIND request

### ISSUE THREAD

**Issue by stenterstal** [authelia/authelia#3740]
## Bug Report

[Possibly related to #2923](https://github.com/authelia/authelia/issues/2923)

**[!] I have replaced my domains url in the logs with domain.tld**

### Description

I'm using Authelia with Traefik v2 reverse proxy and Cloudflare.

I have Authelia setup to protect my Cal|CardDAV web portal, but to bypass all traffic that syncs the calendars and agenda. All normal requests (GET|POST etc.) work fine but Authelia gives a 401 on the PROPFIND requests (see logs and configuration below).

In Issue #2923 it is said that when you don't pass any methods it should not block any (I haven't specified any specific methods)

Also the [access control documentation](https://www.authelia.com/configuration/security/access-control/#methods) reads that RFC4918 (eg. PROPFIND) are valid methods to specify under access control, but when PROPFIND is used the following line shows up in the log;
```
time="2022-07-25T15:43:19+02:00" level=error msg="Configuration: Method PROPFIND for rule #8 domain: [dav.domain.tld] is invalid, must be one of the following methods: GET, HEAD, POST, PUT, PATCH, DELETE, TRACE, CONNECT, OPTIONS"
```

### Expected Behaviour

I would expect Authelia to bypass PROPFIND requests when no specific methods are specified in the log as described in #2923
OR
I would expect Authelia to bypass PROPFIND requests when specified under the methods as [described in the documentation](https://www.authelia.com/configuration/security/access-control/#methods)

### Reproduction Steps

1. Use the specified authelia access control config
2. Use [baikal docker container](https://github.com/ckulka/baikal-docker) for the Cal|CardDAV server
3. Intialize baikal
4. Add CalDAV account to a DAV Client or manually make a PROPFIND request to `https://dav.domain.tld/dav.php/calendars/<user>/default/`
5. PROPFIND will return with a `401 Unauthorized`
6. Authelia docker log;
```
time="2022-07-25T15:54:03+02:00" level=debug msg="Check authorization of subject username= groups= ip=172.71.102.13 and object https://dav.domain.tld/dav.php/calendars/sten/default/ (method PROPFIND)."
```
7. Traefik access log;
```
{"ClientAddr":"172.71.102.155:16750","DownstreamStatus":401,"RequestAddr":"dav.domain.tld","RequestMethod":"PROPFIND","RequestPath":"/dav.php/calendars/sten/default/","RequestScheme":"https","level":"info","msg":"","time":"2022-07-25T13:30:57Z"}
```

#### Authelia access control config
```
access_control:
  default_policy: deny:
  rules:
    # Bypass all routes starting with /dav.php
    - domain: 'dav.domain.tld'
      policy: bypass
      resources:
      - '.*/dav.php.*'
      # You can't do this!!
      # methods:
      # - PROPFIND
      # ...
    # Block the web portal
    - domain: 'dav.domain.tld'
      policy: two_factor
```

**Comment by james-d-elliott** [comment]
Update.

**Comment by james-d-elliott** [comment]
Code:

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/access_control.go#L104

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/access_control.go#L145-L151

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/const.go#L301-L304

Message that should be displayed but isn't: 

https://github.com/authelia/authelia/blob/v4.36.2/internal/configuration/validator/const.go#L207-L208

**Comment by stenterstal** [comment]
I updated to docker master tag (updated 8hrs ago, log says; Authelia untagged-v4.36.2 (master, c128945)) and I still have the same errors/problem.

Strange thing I found is that when adding PROPFIND under methods I still get the before mentioned error line, but when changing it to "testmethod" I get the mentioned error message that wasn't displayed before.

```
time="2022-07-25T23:39:10+02:00" level=error msg="Configuration: access control: rule #8 (domain 'dav.domain.tld'): 'methods' option 'testmethod' is invalid: must be one of 'GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'TRACE', 'CONNECT', 'OPTIONS', 'COPY', 'LOCK', 'MKCOL', 'MOVE', 'PROPFIND', 'PROPPATCH', 'UNLOCK'"
```

PROPFIND is still getting 401 even when adding no methods section in config

**Comment by james-d-elliott** [comment]
'testmethod' is not a valid method.

**Comment by stenterstal** [comment]
I understand that 'testmethod' is not valid, only tried it because that way correct error message shows.

I'm not getting config errors any longer with PROPFIND defined in the methods but still getting 401.

To rule out any misconfiguration on my end I tried removing and adding my DAV account to my phone again to no avail.

### Authelia console
```
time="2022-07-26T13:04:07+02:00" level=debug msg="Check authorization of subject username= groups= ip=172.71.94.113 and object https://dav.domain.tld/ (method PROPFIND)."
time="2022-07-26T13:04:07+02:00" level=info msg="Access to https://dav.domain.tld/ (method PROPFIND) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://auth.domain.tld/?rd=https%3A%2F%2Fdav.domain.tld%2F&rm=PROPFIND" method=GET path=/api/verify remote_ip=172.71.94.113
```

### Traefik access log
```
{"ClientAddr":"172.71.94.113:57176","DownstreamStatus":401,"RequestAddr":"dav.domain.tld","RequestMethod":"PROPFIND","RequestPath":"/","RequestScheme":"https","level":"info","msg":"","time":"2022-07-26T11:04:07Z"}
```

### Authelia access control config
```
access_control:
  default_policy: deny
  rules:
    - domain: 'dav.sten.place'
      policy: bypass
      resources:
      - '.*/dav.php.*'
      methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PROPFIND
    - domain: 'dav.sten.place'
      policy: two_factor
```
