### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by walkerleigh** [authelia/authelia#3773]
Authelia rejects login, dsiplaying the toast type message saying that the username or password is incorrect. The log shows: -

```
today at 4:12:33 PMtime="2022-07-31T16:12:33+10:00" level=debug msg="Mark 1FA authentication attempt made by user 'Leigh'" method=POST path=/api/firstfactor remote_ip=10.1.1.126
today at 4:12:33 PMtime="2022-07-31T16:12:33+10:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'Leigh': user not found" method=POST path=/api/firstfactor remote_ip=10.1.1.126 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:197           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:53 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54           (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.10/router.go:414                            (*Router).Handler\ngithub.com/valyala/fasthttp@v1.38.0/http.go:153                             (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.38.0/server.go:2308                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571                                                    goexit"

```

The password hash is generated with: -

`docker run authelia/authelia:latest authelia hash-password -- password`

My users_database.yml

```
users:
  leigh:
    displayname: "Leigh"
    password: "$argon2id$v=19$m=524288,t=1,p=wt&$QhPmU8UTEPs&JGAXWbku2nCux"
    email: my.email@gmail.com
    groups: []
```
Authentication backend section of configration.yml: -
```
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024
```
The output of `docker exec authelia cat /config/users_database.yml` gives the same result as the contents of my users_database.yml

Not sure if this is a password issue or if the user is not being found in the users_database.yml file. If I try with a random username that doesn't exist in the file, the same error is recorded in the log.

Any help would be greatly appreciated.
 
Thanks in anticipation.
