### ISSUE TITLE
Error dialling the SMTP Server

### ISSUE THREAD

**Issue by nsmathew** [authelia/authelia#3806]
### Issue
I have authelia setup as docker container on a linode instance. I have 2 services which are enabled in the configuration for authentication via authelia. 
When i set them as one-factor everything works fine. When i try two_factor i get an exception as below in the logs. Once I enter the username and password the authentication goes onto the 2FA screen. Here I click 'Register Device' and I get the message 'There was a problem initiating the registration process' and the below exception in the logs. 
Any idea why this happens? I have included my configuration as well. 

### Authelia Container Logs
```
time="2022-08-07T22:20:47+08:00" level=warning msg="Configuration: configuration key 'authentication_backend.disable_reset_password' is deprecated in 4.36.0 and has been replaced by 'authentication_backend.password_reset.disable': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-08-07T22:20:47+08:00" level=info msg="Authelia v4.36.3 is starting"
time="2022-08-07T22:20:47+08:00" level=info msg="Log severity set to debug"
time="2022-08-07T22:20:47+08:00" level=info msg="Storage schema is being checked for updates"
time="2022-08-07T22:20:47+08:00" level=info msg="Storage schema is already up to date"
time="2022-08-07T22:20:47+08:00" level=debug msg="notification provider: startup check skipped as it is disabled"
time="2022-08-07T22:20:47+08:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2022-08-07T22:20:59+08:00" level=debug msg="Check authorization of subject username= groups= ip=<redacted> and object https://<redacted>.duckdns.org/ (method )."
time="2022-08-07T22:20:59+08:00" level=info msg="Access to https://<redacted>.duckdns.org/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=<redacted>
time="2022-08-07T22:21:07+08:00" level=debug msg="Mark 1FA authentication attempt made by user '<redacted>'" method=POST path=/api/firstfactor remote_ip=<redacted>
time="2022-08-07T22:21:07+08:00" level=debug msg="Successful 1FA authentication attempt made by user '<redacted>'" method=POST path=/api/firstfactor remote_ip=<redacted>
time="2022-08-07T22:21:07+08:00" level=debug msg="Check authorization of subject username=<redacted> groups=admins,usr ip=<redacted> and object https://<redacted>.duckdns.org/ (method )."
time="2022-08-07T22:21:07+08:00" level=debug msg="Required level for the URL https://<redacted>.duckdns.org/ is 2" method=POST path=/api/firstfactor remote_ip=<redacted>
time="2022-08-07T22:21:07+08:00" level=warning msg="https://<redacted>.duckdns.org/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=<redacted>
time="2022-08-07T22:21:09+08:00" level=debug msg="Check authorization of subject username=<redacted> groups=admins,usr ip=<redacted> and object https://<redacted>.duckdns.org/ (method )."
time="2022-08-07T22:21:09+08:00" level=info msg="Access to https://<redacted>.duckdns.org/ (method unknown) is not authorized to user <redacted>, responding with status code 401" method=GET path=/api/verify remote_ip=<redacted>
time="2022-08-07T22:21:14+08:00" level=debug msg="Sending an email to user <redacted> (<redacted>@gmail.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip=<redacted>
time="2022-08-07T22:21:14+08:00" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:587"
time="2022-08-07T22:21:19+08:00" level=error msg="error dialing the SMTP server: dial tcp 108.177.126.108:587: i/o timeout" method=POST path=/api/secondfactor/totp/identity/start remote_ip=<redacted> stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:66       (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:106 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15   Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                 (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.10/router.go:414                                  (*Router).Handler\ngithub.com/valyala/fasthttp@v1.38.0/http.go:153                                   (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.38.0/server.go:2308                                (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:224                             (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:196                             (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571                                                          goexit"
```

### configuration.yml
```
# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark
jwt_secret: <redacted> #any text or number you want to add here to create jwt Token

default_redirection_url: https://google.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: <redacted>.duckdns.org #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain:
        - "auth.<redacted>.duckdns.org" #This should be your authentication URL
      policy: bypass
    - domain: "<redacted>.duckdns.org" #example domain to protect
      policy: two_factor
    - domain: "<redacted>.duckdns.org" #example domain to protect
      policy: one_factor
        #    - domain: "sub1.yourdomain.com" #example subdomain to protect
        #policy: one_factor
        # - domain: "sub2.yourdomain.com" #example subdomain to protect
        #policy: one_factor
        # - domain: "*.yourdomain.com" #example to protect all subdomains under top-level domain
        #policy: one_factor
      #add or remove additional subdomains as necessary. currenlty only supports ONE top-level domain
      #any time you add a new subdomain, you will need to restart the Authelia container to recognize the new settings/rules

session:
  name: authelia_session
  secret: unsecure_session_secret #any text or number you want to add here to create jwt Token
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: <redacted>.duckdns.org  # Should match whatever your root protected domain is

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: <redacted> #added Dec 5 2021

ntp:
  address: "time.cloudflare.com:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

notifier:
  disable_startup_check: true #true/false
  smtp:
    username: <redacted>@gmail.com #your email address
    password: <redacted> #your email password
    host: smtp.gmail.com #email smtp server
    port: 587 #email smtp port
    sender: <redacted>@gmail.com
    identifier: linode_docker
    subject: "[Authelia] {title}" #email subject
    startup_check_address: <redacted>@gmail.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
...
```
