### ISSUE TITLE
Authelia not recognizing the group authentication.

### ISSUE THREAD

**Issue by Stoffe** [authelia/authelia#3832]
### Description

When using the following setup in authelia:

Please note, I have replaced the domain with the tag [DOMAIN].

```yaml
  access_control:
    default_policy: deny
    networks: []
    rules:
      - domain:
          - 'auth.[DOMAIN]'
        policy: bypass
      - domain:
          - 'control.[DOMAIN]'
        policy: two_factor
        subject:
          - 'group:admins'
      - domain:
          - '*.[DOMAIN]'
        policy: one_factor
        subject:
          - 'group:admins'
          - 'group:devs'
```

According to your documentation (https://www.authelia.com/configuration/security/access-control/#policies), it should read the list from the top down, and the first match will be the one that is dominant.
But, I am a little confused as in the detailed example, here:
https://www.authelia.com/configuration/security/access-control/#detailed-example
You are putting the *.[DOMAIN] very high up??...  Right under the bypass...

Anyway,

In this case, I would read it as the control.[DOMAIN] requires a user with the group "admins" and 2 factors to access.
And the domain nginx-test.[DOMAIN] would require only one factor and the group "devs" OR "admins".

However, when I first login to the test site, nginx-test.[DOMAIN] I will first read the bottom one, and login.
The user in this case, TestUser3 only have "users, devs" group authority. (no admins)
So, the user will access nginx-test.[DOMAIN] all fine.

But, after that I try to access control.[DOMAIN] and Im let straight thru.
This is the authelia log that clearly says that my user is only in the groups "users,devs" AND it states that the control.[DOMAIN] seems be fine with that and only 1 factor???
Why is this?
Please note again, I have changed the domain with the tag [DOMAIN] and the ip with the tag [IP]

time="2022-08-12T07:03:18Z" level=debug msg="Check authorization of subject username=TestUser groups=users,admins ip=[IP] and object https://control.[DOMAIN]/api/v1/namespaces/authelia/pods/authelia-4vndj/log?previous=false&follow=true&timestamps=true&pretty=true&container=authelia&sinceSeconds=1800&sockId=7 (method GET)."
time="2022-08-12T07:04:06Z" level=debug msg="Check authorization of subject username= groups= ip=[IP] and object https://nginx-test.[DOMAIN]/ (method GET)."
time="2022-08-12T07:04:06Z" level=info msg="Access to https://nginx-test.[DOMAIN]/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.[DOMAIN]/?rd=https%3A%2F%2Fnginx-test.[DOMAIN]%2F&rm=GET" method=GET path=/api/verify remote_ip=[IP]
time="2022-08-12T07:04:26Z" level=debug msg="Mark 1FA authentication attempt made by user 'TestUser3'" method=POST path=/api/firstfactor remote_ip=[IP]
time="2022-08-12T07:04:26Z" level=debug msg="Successful 1FA authentication attempt made by user 'TestUser3'" method=POST path=/api/firstfactor remote_ip=[IP]
time="2022-08-12T07:04:26Z" level=debug msg="Check authorization of subject username=TestUser3 groups=users,devs ip=[IP] and object https://nginx-test.[DOMAIN]/ (method GET)."
time="2022-08-12T07:04:26Z" level=debug msg="Required level for the URL https://nginx-test.[DOMAIN]/ is 1" method=POST path=/api/firstfactor remote_ip=[IP]
time="2022-08-12T07:04:26Z" level=debug msg="Redirection URL https://nginx-test.[DOMAIN]/ is safe" method=POST path=/api/firstfactor remote_ip=[IP]
time="2022-08-12T07:04:27Z" level=debug msg="Check authorization of subject username=TestUser3 groups=users,devs ip=[IP] and object https://nginx-test.[DOMAIN]/ (method GET)."
time="2022-08-12T07:04:59Z" level=debug msg="Check authorization of subject username=TestUser3 groups=users,devs ip=[IP] and object https://control.[DOMAIN]/ (method GET)."
time="2022-08-12T07:05:00Z" level=debug msg="Required level for the URL https://control.[DOMAIN]/ is 1" method=POST path=/api/firstfactor remote_ip=[IP]
time="2022-08-12T07:05:01Z" level=debug msg="Check authorization of subject username=TestUser3 groups=users,devs ip=[IP] and object https://control.[DOMAIN]/dashboard/ (method GET)."

### Expected Behaviour

I would expect that the list is read from top down with every new url request and if the user is not matched, either the user is given a forbidden page, or the user will need to reauthenticate.

### Additional Information

It seems it is something to do with the access list or how its read, the current version im using is authelia helm 0.8.38.

or am I missing something?

**Comment by james-d-elliott** [comment]
This rule is matching as expected:

`groups=users,devs` means the first matching rule is the third one, which is on factor.

**Comment by Stoffe** [comment]
So, then its a documentation bug?
Since thats not what the documentation states...

**Comment by james-d-elliott** [comment]
The documentation clearly states exactly what I said. The first rule which completely matches is the rule applied. The only rule that matches is the third one.

**Comment by james-d-elliott** [comment]
Documentation:

The rules have many configuration options. **_A rule matches when all criteria of the rule match the request_** excluding the policy which is the [policy](https://www.authelia.com/configuration/security/access-control/#policies) applied to the request.


Request:

- Method: GET
- URL: https://control.[DOMAIN]/ 
    - Domain: control.[DOMAIN]
    - Path: /
- Subject:
    - Username: TestUser3
    - Groups:
        - users
        - dev
        
Rules:

```yaml
  access_control:
    default_policy: deny
    networks: []
    rules:
      ## Rule #1
      ##
      ## Does not match criteria: domain
      ## The domain control.[DOMAIN] is not auth.[DOMAIN]
      - domain:
          - 'auth.[DOMAIN]'
        policy: bypass
        
      ## Rule #2
      ##
      ## Does not match criteria: subject
      ## User is not in the group admins.
      - domain:
          - 'control.[DOMAIN]'
        policy: two_factor
        subject:
          - 'group:admins'

      ## Rule #3
      ##
      ## Does match! All further rules are skipped. Policy applied.
      - domain:
          - '*.[DOMAIN]'
        policy: one_factor
        subject:
          - 'group:admins'
          - 'group:devs'
```

**Comment by Stoffe** [comment]
ok, I read the rules as if the domain matches, this rules apply (meaning you need to have these groups) but I see now, I missed that part of the documentation.
Sorry, my bad, thank you for the clarification.

**Comment by james-d-elliott** [comment]
No worries at all. It's so you can match any part of the request dynamically. You can add  rules with `deny` as well. Like this:


```yaml
  access_control:
    default_policy: deny
    networks: []
    rules:
      ## Rule #1
      ##
      ## Does not match criteria: domain
      ## The domain control.[DOMAIN] is not auth.[DOMAIN]
      - domain:
          - 'auth.[DOMAIN]'
        policy: bypass
        
      ## Rule #2
      ##
      ## Does not match criteria: subject
      ## User is not in the group admins.
      - domain:
          - 'control.[DOMAIN]'
        policy: two_factor
        subject:
          - 'group:admins'

      ## Rule #3
      ##
      ## Does match! All further rules are skipped. Policy applied.
      - domain:
          - 'control.[DOMAIN]'
        policy: deny
          
      ## Rule #4
      ##
      ## Skipped.
      - domain:
          - '*.[DOMAIN]'
        policy: one_factor
        subject:
          - 'group:admins'
          - 'group:devs'
```
