### ISSUE TITLE
U2F Not Working in Chrome

### ISSUE THREAD

**Issue by SilverBut** [authelia/authelia#384]
Browser version: Version 75.0.3770.142 (Official Build) Arch Linux (64-bit)

Docker image version: 
```
clems4ever/authelia       latest              5c6366e938e6        3 months ago        107MB
```

The following info is shown in the console:
```
Uncaught (in promise) Error: Sign failed
    at l (u2f-api.js:74)
    at u2f-api.js:147
    at o.responseHandler_ (generated-google-u2f-api.js:627)
    at generated-google-u2f-api.js:384
```

I set a break point to see the error code and this is the result:
```
response.errorCode = 2
```

And I also noticed when calling `u2f.register`, the following parameters are used:
```
appId: undefined
challenge: undefined
registeredKeys: undefined
```

So seems those parameters are not correctly set?

Here is the configuration file:
```yaml
root@authserver:~# cat config.yml |grep -v '^ *#'                                      
port: 8080
logs_level: debug
default_redirection_url: https://www.domain.com/
totp:
  issuer: domain.com
authentication_backend:
  file:
    path: /var/lib/authelia/users_database.yml
access_control:
  default_policy: deny
  rules:
    - domain: '*.domain.com'
      policy: two_factor
session:
  name: authelia_session
  secret: [removed]
  expiration: 36000000 # 10 hours
  inactivity: 7200000 # 2 hours
  domain: domain.com
  redis:
    host: redis
    port: 6379
    password: [removed]
storage:
  local:
    path: /var/lib/authelia/store
notifier:
  filesystem:
    filename: /var/lib/authelia/notification.txt
```

Please tell me if you need any other information.
