### ISSUE TITLE
Unable to use Redis Sentinel with Redis v7

### ISSUE THREAD

**Issue by onedr0p** [authelia/authelia#3856]
### Description

Authelia and redis v7 do not appear to be working great together.

```authelia-5ff7d6b689-k8z6h authelia time="2022-08-15T22:33:43Z" level=trace msg="sentinel: GetMasterAddrByName master=\"redis-master\" failed: ERR unknown command 'sentinel', with args beginning with: 'get-master-addr-by-name' 'redis-master' "```

I have Authelia configured to use Redis Sentinel with the following mix of configuration:

```yaml
# env
AUTHELIA_SESSION_REDIS_DATABASE_INDEX: 14
AUTHELIA_SESSION_REDIS_HOST: redis.default.svc.cluster.local
AUTHELIA_SESSION_REDIS_PORT: 6379
```

```yaml
# configuration file
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.default.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.default.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.default.svc.cluster.local
          port: 26379
```

I can verify the db index 14 that I chose is not showing up via redis-cli:

```sh
❯ redis-cli -h 10.42.152.237
10.42.152.237:6379> INFO keyspace
# Keyspace
db0:keys=21,expires=5,avg_ttl=2638721
db15:keys=4,expires=3,avg_ttl=2898
```

Looks like the fix might come in the next version of https://github.com/go-redis/redis
