### ISSUE TITLE
Documentation request: basic auth with ingress-nginx (k8s)

### ISSUE THREAD

**Issue by samip5** [authelia/authelia#3860]
I would like to request documentation snippet example for ingress-nginx with basic auth.

I could not find one, and the existing ones don't make it simple to create one.

**Comment by james-d-elliott** [comment]
Try the following:

```yaml
annotations:
  nginx.ingress.kubernetes.io/auth-method: GET
  nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify?auth=basic
  nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
  nginx.ingress.kubernetes.io/auth-snippet: |
    proxy_set_header X-Forwarded-Method $request_method;
```

**Comment by samip5** [comment]
> Try the following:
> 
> ```yaml
> annotations:
>   nginx.ingress.kubernetes.io/auth-method: GET
>   nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify?auth=basic
>   nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
>   nginx.ingress.kubernetes.io/auth-snippet: |
>     proxy_set_header X-Forwarded-Method $request_method;
> ```

Results in error regarding authorization header missing.

**Comment by james-d-elliott** [comment]
That's expected, basic auth requires the authorization header with the basic scheme to be present. You may want to elaborate on what you want or supply more than "results in an error".

**Comment by samip5** [comment]
Ah, I apperantly did something wrong as the needed ones was just:

```
              +(nginx.ingress.kubernetes.io/auth-method): GET
              +(nginx.ingress.kubernetes.io/auth-url): http://[2001:db8::1]:40119/api/verify?auth=basic
              +(nginx.ingress.kubernetes.io/auth-response-headers): Remote-User,Remote-Groups
              +(nginx.ingress.kubernetes.io/auth-snippet): proxy_set_header X-Forwarded-Method $request_method;
```

I tried to do it with the server snippets and like that, but yeah it's resolved.

**Comment by samip5** [comment]
> That's expected, basic auth requires the authorization header with the basic scheme to be present. You may want to elaborate on what you want or supply more than "results in an error".

This is what I meant:

```
me="2022-08-19T02:11:15+03:00" level=error msg="Error caught when verifying user authorization: unable to check credentials extracted from Authorization header: authentication failed. Cause: bind failed with error LDAP Result Code 49 \"Invalid Credentials\"
```

**Comment by samip5** [comment]
This is what I had for Traefik where it worked:

```
  forwardAuth:
    address: http://[2001:db8::1]:40119/api/verify?auth=basic
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
    authRequestHeaders:
      - X-Fowarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-URI
      - Authorization
```
