### ISSUE TITLE
Feat: Allow custom access control policies

### ISSUE THREAD

**Issue by dominic-p** [authelia/authelia#3922]
## Feature Request
Allow custom access control policies to be defined in the configuration.

### Description
I'm fairly new to Authelia, so I apologize if I'm missing something obvious. I'll describe my use case below and how I think a custom policy could satisfy it.

### Use Case
I want to allow my users to use a short (i.e. weak) password when logging in from our main location. We have several shared workstations and I want to make it quick and easy for users to sign out/in throughout the day.

But, when the same users access services from outside of our main location I want to require their normal (i.e. strong) password.

My idea to enable this is to add a short password to some custom attribute in the user's LDAP record. Then, I could define a  network for our location (by the way it would be nice if we could use a domain instead of hard coded IPs to handle dynamic IP addresses) and then apply a custom policy to requests that match that network.

The custom policy could specify how to lookup the user's password in various authentication backends. Maybe something like:

```
access_control:

  # Define custom access control polices to use in addition to the defaults ('bypass', 'one_factor', etc.)
  custom_policies:
  - name: weak_password
    password_attribute:
      file: weak_password
      ldap: 'employeeNumber'

  networks:
  - name: internal
    networks:
    - myoffice.com/32 # It would be cool to allow this for dynamic DNS
    - 10.9.0.0/32 # Failing that we can always hard code the dynamic IP and update it regularly

  rules:

  # For internal traffic, allow a weak password to be used
  - domain: secure.example.com
    policy: weak_password
    networks:
    - internal

  # By default, require the normal password
  - domain: secure.example.com
    policy: one_factor
```

### Alternatives
- If Passwordless WebAuthn lands (#2827), that could be a substitute since it should enable quick logins via a hardware token at our location. Although I'm not sure people will want to carry around a YubiKey all day.
- Maybe I could juggle two instances of Authelia that talk to two different LDAP backends (with different versions of the user's passwords) and then somehow decide which one to use on the fly based on the request? Sounds kind of difficult.
- Maybe there's some other way to achieve this that I haven't thought of?
