### ISSUE TITLE
Can't register 2FA device

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [authelia/authelia#4010]
### Description

Can't register 2FA device, I'm definitely using the same browser without closing it and I'm getting the following message:
"You must open the link from the same device and browser that initiated the registration process" (see screenshot https://imgur.com/a/5wiXnDg )
Notably the URL in the email is different from the authelia URL. 

### Expected Behaviour

Generation of url & qr code which actually allows registering 2FA device

### Reproduction Steps

1. invoke web1.xxx.domain.org
2. log into authelia, authelia authenticates and forwards to web1.xxx.domain.org
3. invoke auth.xxx.domain.org in same session, authelia shows me logged in
4. click on button with id "register-link" and receive email (notification.txt in my case)
5. content of email:
```
...
To setup your 2FA please visit the following URL: http://docker.host.numeric.ip:9091/one-time-password/register?token=longtokenwithmanyrandomcharacters
...
```
6. Click on link in email, browser shows image from screenshot https://imgur.com/a/5wiXnDg
7. Another try: copy "/one-time-password/register?token=..." part from URL and manually construct URL http://auth.xxx.domain.org/one-time-password/register?token=... - result: Browser stays white, return code from that call: 200, no errors in logs 

### Additional Information
Groups of authenticated user: admins, dev
https configured and working (Let's encrypt)
Schema of setup: one DSL router, one docker server
```
xxx.domain.org+-------+
auth.xxx.domain.org---+-----80---|DSL router|---13080---|dockerhost|
                      +----443---|DSL router|---13443---|dockerhost|

---13080---|nginx container |
---13443---|nginx container |
    9091---|authelia container|
```
port mapping in nginx container: `13080:80, 13443:443`

#### authelia configuration.yml:
```
server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
  file_path: /logs/authelia.log
jwt_secret: secretinsidehere
default_redirection_url: https://auth.xxx.domain.org
totp:
  issuer: xxx.dyndns.org
  period: 30
  skew: 1

authentication_backend:
  # disable_reset_password: false
  password_reset:
    disable: false
  file:
    path: /config/users_database.yml # Make sure this file exists
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: 
        - 'web1.xxx.domain.org'
        - 'web3.xxx.domain.org'
        - 'web4.xxx.domain.org'
      policy: one_factor
    - domain:
        - 'web2.xxx.domain.org'
      policy: two_factor
         
session:
  name: authelia_session
  secret: anothersecretinsidehere
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: xxx.domain.org # Needs to be your root domain

  redis:
    host: authelia_redis_1
    port: 6379

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: dark  

storage:
  encryption_key: yetanothersecretinsidehere
  local:
    path: /config/db.sqlite3
    
notifier:
  filesystem:
    filename: /config/notification.txt
```

#### nginx config:
```
server {
    listen 443 ssl reuseport;
    listen [::]:443 ssl reuseport;

    server_name web1.xxx.domain.org;

    ssl_certificate         /etc/letsencrypt/live/xxx.domain.org/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/xxx.domain.org/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/xxx.domain.org/chain.pem;
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

location /authelia {
    internal;
    set $upstream_authelia http://docker.host.numeric.ip:9091/api/verify;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;    
    proxy_set_header Content-Length "";
 
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr; 
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;
 
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
 
    location / {
 	root /var/www/html/web1.xxx.domain.org;
        auth_request /authelia;
        auth_request_set $target_url https://$http_host$request_uri;
        auth_request_set $user $upstream_http_remote_user;
        auth_request_set $groups $upstream_http_remote_groups;
        proxy_set_header Remote-User $user;
        proxy_set_header Remote-Groups $groups;
        error_page 401 =302 https://auth.xxx.domain.org/?rd=$target_url;
 
        client_body_buffer_size 128k;
 
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
 
        send_timeout 5m;
        proxy_read_timeout 360;
        proxy_send_timeout 360;
        proxy_connect_timeout 360;
 
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_redirect  http://  $scheme://;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_cache_bypass $cookie_session;
        proxy_no_cache $cookie_session;
        proxy_buffers 64 256k;
 

        set_real_ip_from ip.range.from.dockerhost.0/24;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
    }
    
}

```
