### ISSUE TITLE
2FA, TOTP, Failed to register device

### ISSUE THREAD

**Issue by Bouni** [authelia/authelia#4054]
### Version

v4.36.8

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.6.1

### Description

When I try to register a device for TOTP 2FA the link is always expired, even if I open it seconds after the request:

![image](https://user-images.githubusercontent.com/948965/191912319-c9181b40-8a4d-4fac-adba-ece3774dd059.png)

![image](https://user-images.githubusercontent.com/948965/191912331-045b7834-5429-47fb-9b34-4f95e7fb6ebb.png)

1FA works fine. I also verified that Timezone and date are correct.

### Reproduction

1. Go to https://2fa.test.example.com
2. Get redirected to the Authelia login page
3. Login using username and password
4. Get the register device screen
5. Click the register device link
6. Open the link from notifications.txt
7. See the error shown in the screenshots

### Expectations

Being able to register a device for 2FA via TOTP

### Logs

```shell
authelia  | time="2022-09-23T09:52:15+02:00" level=debug msg="Check authorization of subject username= groups= ip=123.456.789.123 and object https://2fa.test.example.com/ (method GET)."
authelia  | time="2022-09-23T09:52:15+02:00" level=info msg="Access to https://2fa.test.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.test.example.com/?rd=https%3A%2F%2F2fa.test.example.com%2F&rm=GET" method=GET path=/api/verify remote_ip=
123.456.789.123
authelia  | time="2022-09-23T09:52:21+02:00" level=debug msg="Mark 1FA authentication attempt made by user '<redacted>'" method=POST path=/api/firstfactor remote_ip=123.456.789.123
authelia  | time="2022-09-23T09:52:21+02:00" level=debug msg="Successful 1FA authentication attempt made by user '<redacted>'" method=POST path=/api/firstfactor remote_ip=123.456.789.123
authelia  | time="2022-09-23T09:52:21+02:00" level=debug msg="Check authorization of subject username=<redacted> groups=mygroup ip=123.456.789.123 and object https://2fa.test.example.com/ (method GET)."
authelia  | time="2022-09-23T09:52:21+02:00" level=debug msg="Required level for the URL https://2fa.test.example.com/ is 2" method=POST path=/api/firstfactor remote_ip=123.456.789.123
authelia  | time="2022-09-23T09:52:21+02:00" level=warning msg="https://2fa.test.example.com/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=123.456.789.123
authelia  | time="2022-09-23T09:52:24+02:00" level=debug msg="Sending an email to user user1 (example@example.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip=123.456.789.123
authelia  | time="2022-09-23T09:52:39+02:00" level=error msg="Cannot parse token" method=POST path=/api/secondfactor/totp/identity/finish remote_ip=123.456.789.123 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:66       (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middle
wares/identity_verification.go:143 IdentityVerificationFinish.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15   Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                 (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/inter
nal/middlewares/headers.go:25                SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                SecurityHeaders.func1\ngithub.com/fasthttp/router@v
1.4.12/router.go:414                                  (*Router).Handler\ngithub.com/valyala/fasthttp@v1.40.0/http.go:154                                   (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2311                                (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.40.0/wo
rkerpool.go:224                             (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:196                             (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                          goexit"
```

### Configuration

```yaml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

theme: dark

#jwt_secret: a_very_important_secret ---> set via ENV VAR AUTHELIA_JWT_SECRET
default_redirection_url: https://auth.test.example.com

totp:
  issuer: authelia.com

authentication_backend:
  # Password reset through authelia works normally.
  password_reset:
    disable: false
  # How often authelia should check if there is an user update in LDAP
  refresh_interval: 1m

  ldap:
    implementation: custom
    # Pattern is ldap://HOSTNAME-OR-IP:PORT
    # Normal ldap port is 389, standard in LLDAP is 3890
    url: ldap://lldap:3890
    # The dial timeout for LDAP.
    timeout: 5s
    # Use StartTLS with the LDAP connection, TLS not supported right now
    start_tls: false
    #tls:
    #  skip_verify: false
    #  minimum_version: TLS1.2
    # Set base dn, like dc=google,dc.com
    # base_dn: dc=example,dc=com ---> Set via ENV VAR AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN
    username_attribute: uid
    # You need to set this to ou=people, because all users are stored in this ou!
    additional_users_dn: ou=people
    # To allow sign in both with username and email, one can use a filter like
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: (&({username_attribute}={input})(objectClass=person))
    # Set this to ou=groups, because all groups are stored in this ou
    additional_groups_dn: ou=groups
    # Only this filter is supported right now
    groups_filter: (member={dn})
    # The attribute holding the name of the group.
    group_name_attribute: cn
    # Email attribute
    mail_attribute: mail
    # The attribute holding the display name of the user. This will be used to greet an authenticated user.
    display_name_attribute: displayName
    # The username and password of the admin user.
    # "admin" should be the admin username you set in the LLDAP configuration
    #user: uid=admin,ou=people,dc=example,dc=com  ---> Set via ENV VAR AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER
    #password: "REPLACE_ME" ---> Set via ENV VAR AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: public.test.example.com
      policy: bypass
    - domain: 1fa.test.example.com
      policy: one_factor
    - domain: 2fa.test.example.com
      policy: two_factor

session:
  name: authelia_session
  # secret: unsecure_session_secret ---> Set via ENV VAR AUTHELIA_SESSION_SECRET
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: example.com # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```

### Documentation

Here's the Caddyfile

```Caddyfile
{
    debug
    log {
        format console
    }
}

(trusted_proxy_list) {
    ## Uncomment & adjust the following line to configure specific ranges which should be considered as trustworthy.
    trusted_proxies 10.0.0.0/8 172.16.0.0/16 192.168.0.0/16 fc00::/7
}

(authelia) {
    forward_auth authelia:9091 {
        uri /api/verify?rd=https://auth.test.example.com/
        copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
        ## This import needs to be included if you're relying on a trusted proxies configuration.
        import trusted_proxy_list
    }
}

auth.test.example.com {
    reverse_proxy authelia:9091 {
        ## This import needs to be included if you're relying on a trusted proxies configuration.
        import trusted_proxy_list
    }
}

lldap.test.example.com {
    reverse_proxy lldap:17170
}

public.test.example.com {
    import authelia
    respond "Public"
}

1fa.test.example.com {
    import authelia
    respond "1FA"
}

2fa.test.example.com {
    import authelia
    respond "2FA"
}
```
