### ISSUE TITLE
Basic auth leads to a HTTP 500 error

### ISSUE THREAD

**Issue by ArthurMitchell42** [authelia/authelia#4168]
### Version

v4.36.9

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.9.1

### Description

I've setup Traefik and Authelia, all seems well except for routing Authelia basic auth which comes back with a 500 error on the browser.
I've attached some shrunk versions of the appropriate files.

I'd be very grateful for your advice.
Thanks,
Arthur

[configuration.yml.txt](https://github.com/authelia/authelia/files/9759632/configuration.yml.txt)
[services.yml.txt](https://github.com/authelia/authelia/files/9759633/services.yml.txt)
[traefik.yml.txt](https://github.com/authelia/authelia/files/9759635/traefik.yml.txt)

### Reproduction

This is running on docker on a Synology NAS
The YAML for composer is as attached:
[docker-compose.yml.txt](https://github.com/authelia/authelia/files/9759660/docker-compose.yml.txt)

### Expectations

I would expect to be prompted for user name and password using the standard credentials request and the normal LDAP credentials should pass to the destination address.

### Logs

```shell
time="2022-10-11T21:10:03+01:00" level=error msg="An unknown error occurred while handling a request from client." 
error="error when reading request headers: read tcp 192.168.10.6:9091->192.168.10.4:40968: i/o timeout. Buffer size=274, 
contents: \"\\x16\\x03\\x01\\x01\\r\\x01\\x00\\x01\\t\\x03\\x03\\x82f\\x85|@\\x8a\\xe3q\\x04>Ԉu\\xb2\\xc4\\x174}
\\xc6=`1p\\xb2\\x9d\\x18)\\xa1V\\x87\\xf2\\xbe \\xdc|\\xc9\\x17\\xdf\\xdbV\\xa0f\\f\\xb8<\\x9e\\xf0=\\xbb\\xaa\\\"
\\vDYɃ\\x95\\x8c\\xbeFqV\\x1dL\\xe5\\x00&\\xc0+\\xc0/\\xc0,\\xc00̨̩\\xc0\\t\\xc0\\x13\\xc0\\n\\xc0\\x14\\x00\\x9c\\
x00\\x9d\\x00/\\x005\\xc0\\x12\\x00\\n\\x13\\x01\\x13\\x02\\x13\\x03\\x01\\x00\\x00\\x9a\\x00\\x00\\x00\\r\\x00\\
v\\x00\\x00\\bauthelia\\x00\\x05\\x00\\x05\\x01\\x00\\x00\\x00\\x00\\x00\\n\\x00\\n\\x00\\b\\x00\\x1d\\x00\\x17\\
x00\\x18\\x00\\x19\\x00\\v\\x00\\x02\\x01\\x00\\x00\\r\\x00\\x1a\\x00\\x18\\b\\x04\\x04\\x03\\b\\a\\b\\x05\\b\\x06
\\x04\\x01\\x05\\x01\\x06\\x01\\x05\\x03\\x06\\x03\\x02\\x01\\x02\\x03\\xff\\x01\\x00\\x01\\x00\\x00\\x10\\x00\\x0e
\\x00\\f\\x02h2\\bhttp/1.1\\x00\\x12\\x00\\x00\\x00+\\x00\\x05\\x04\\x03\\x04\\x03\\x03\\x003\\x00&\\x00$\\x00\\x1d
\\x00 \\xb0*4\\xb2\\x84\\x15\\xf6\\xaf\\x981\\x15\\xad\\x95\\xe7l^\\xfa\\xd9D\\xf3\\xb8H.\\xb3\\xe3\\xe5\\x94j\\x1cc\\xf4>\""
 method=GET path=/ remote_ip=192.168.10.4 stack="github.com/authelia/authelia/v4/internal/server/handlers.go:72 
 handleError.func2\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2800             
 (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2239             
 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:224          
 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:196          
 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                       
 goexit" status_code=400
```

### Configuration

```yaml
# Authelia configuration.yml
server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

telemetry:
  metrics:
    enabled: true
    address: "tcp://0.0.0.0:9959"
    buffers:
      read: 4096
      write: 4096
    timeouts:
      read: 2s
      write: 2s
      idle: 30s

totp:
  disable: false
  issuer: xxxxxxxxxxxxxxx
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

authentication_backend:
  ldap:
    implementation: custom
    url: ldap://xx.xx.xx.xx
    timeout: 5s
    start_tls: true
    tls:
      server_name: ldap.xxxxxxx.xxxxxx
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: DC=xxxxxxxx,DC=xxxxx
    additional_users_dn: cn=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: displayName
    additional_groups_dn: cn=groups
    groups_filter: (&(member={dn})(objectClass=posixGroup))
    group_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: uid=xxxxxx,CN=users,DC=xxxxxxxx,DC=xxxx

access_control:
  default_policy: deny
  rules:
    - domain: "auth.xxxxxxx.xxx"
      policy: bypass

    - domain: "whoami1.xxxxxxx.xxx"
      policy: bypass

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  #secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: $EXTERNAL_DOMAIN  # Should match whatever your root protected domain is

  redis:
    host: 10.0.10.10
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
# Loaded from secrets
  #encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  smtp:
    host: smtp-mail.outlook.com
#=================== removed

...
```

**Comment by james-d-elliott** [comment]
This is an issue in your config with the forwradAuth address scheme.

```yaml
    authelia:
      forwardAuth:
        address: 'http://authelia:9091/api/verify?rd=https://auth.{{env "EXTERNAL_DOMAIN"}}'
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"

    authelia-basic:
      forwardAuth:
        address: "https://authelia:9091/api/verify?auth=basic"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
```
