### ISSUE TITLE
configuration.yml not all secrets work in a secret file

### ISSUE THREAD

**Issue by florianmueller** [authelia/authelia#4170]
### Version

v4.36.9

### Deployment Method

Bare-metal

### Reverse Proxy

Traefik

### Reverse Proxy Version

latest

### Description

When setting up the configuration.yml on bare metal ubuntu LXC container server, I am saving all secets in a file instead of the configuration.yml directly. It works great for some, but not for all. And it is very random on the ones where it don't work. Here is a concrete example:
These four secrets **WORK** in the configuration.yml:
```
#defined in file
jwt_secret: /etc/authelia/.secrets/AUTHELIA_JWT_SECRET_FILE

session:
  name: authelia_session
  secret: /etc/authelia/.secrets/AUTHELIA_SESSION_SECRET_FILE

storage:
  encryption_key: /etc/authelia/.secrets/STORAGE_ENCRYPTION_KEY

identity_providers:
  oidc:
    hmac_secret: /etc/authelia/.secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
```

But these four secrets DON'T WORK in remote files, you have to write them plain into the config.yml:
```
storage:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: authelia
    password: /etc/authelia/.secrets/AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE

notifier:
  disable_startup_check: false
  smtp:
    ## The SMTP host to connect to.
    password: /etc/authelia/.secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE

identity_providers:
  oidc:
    issuer_private_key: |
      /etc/authelia/.secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE
    ...
    clients:
      - id: cloudflare
        description: Cloudflare ZeroTrust
        secret: hmac_secret: /etc/authelia/.secrets/CLOUDFLARE_ZT_SECRET_FILE
```

All files are plain text and saved under `/etc/authelia/.secrets/` with `chmod 600 -R`.

Any idea what might cause the issue that some secrets can be placed in a file and some need to be plain in the config? Anything I do wrong here? 

Thank you for your support and help!

### Reproduction

Put a secret in a plain file and link the path to that file in the configuration.yml.

**Comment by james-d-elliott** [comment]
You didn't provide the ENV vars you're using. In addition OIDC client secrets are not supported. You can read the list here: https://deploy-preview-4080--authelia-staging.netlify.app/configuration/methods/secrets/

**Comment by florianmueller** [comment]
> You didn't provide the ENV vars you're using. In addition OIDC client secrets are not supported. You can read the list here: https://deploy-preview-4080--authelia-staging.netlify.app/configuration/methods/secrets/

Thanks James! yeah, I am not really using ENV vars. I am installing bare metal on Ubuntu LXC container and don't have any docker ENV vars to use. 
I use secret files and provide the path to the configuration.yml. To not get confused or have somewhat of a system in these secret files, I named them 1:1 by the docker ENV vars the documentation provides.

Or does this only work with using the exact "configuration keys"? Thanks!

**Comment by james-d-elliott** [comment]
Secrets require the env vars with the `_FILE` suffix and only the one documented work (this is automatically generated from code), if you put a path where `jwt_secret` is found, the jwt_secret will not be the content of the file it will be the  string you entered.

There is a significant complexity in implementing it within lists and as such we opted to avoid this. In a future release ([4.37](https://www.authelia.com/4.37-pre-release-notes/)) we'll be allowing hashes instead of plaintext.

**Comment by florianmueller** [comment]
Thank you for the explanation. As I understand this, the intention is to set the variables like this (example of mysql database password):
in the configuration.yaml I have this:
```
storage:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: authelia
    password: storage.mysql.password
```
So the `storage.mysql.password` key should trigger now to look for the ENV var of `AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE`, which I have defined in `/etc/environment` like this (added after the PATH env var:
```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE="/etc/authelia/.secrets/mysql"
```
And then in the file `/etc/authelia/.secrets/mysql`I have just plain the password like this:
```
AuthSQLPASSWORD123
```
All files are set to `chmod 600`. But with this above setup for mysql I only get the error, that it failed to connect as it can't use the password. Anything I am missing out?

For the `jwt_secret`for example, a direct path to a secret file in the configuration.yml worked (maybe not intended), but for SQL password, really only setting the password in the config directly worked for me so far.

Thank you for the support!

**Comment by james-d-elliott** [comment]
> Thank you for the explanation. As I understand this, the intention is to set the variables like this (example of mysql database password): in the configuration.yaml I have this:
> 
> ```
> storage:
>   mysql:
>     host: 127.0.0.1
>     port: 3306
>     user: authelia
>     password: storage.mysql.password
> ```
> 
> So the `storage.mysql.password` key should trigger now to look for the ENV var of `AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE`, which I have defined in `/etc/environment` like this (added after the PATH env var:
> 
> ```
> PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
> AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE="/etc/authelia/.secrets/mysql"
> ```
> 
> And then in the file `/etc/authelia/.secrets/mysql`I have just plain the password like this:
> 
> ```
> AuthSQLPASSWORD123
> ```
> 
> All files are set to `chmod 600`. But with this above setup for mysql I only get the error, that it failed to connect as it can't use the password. Anything I am missing out?
> 
> For the `jwt_secret`for example, a direct path to a secret file in the configuration.yml worked (maybe not intended), but for SQL password, really only setting the password in the config directly worked for me so far.
> 
> Thank you for the support!

If you set the following:

```yaml
storage:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: authelia
    password: storage.mysql.password
```

The password used for MySQL will be exactly `storage.mysql.password`.

If you do this with the `AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE` var, it will throw a error as both can't be defined (prevents bad security practices).

If you set `AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE` to `apple123` and configure:

```yaml
storage:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: authelia
    # password: storage.mysql.password
```

Then the password used for mysql will be `apple123`.

**Comment by james-d-elliott** [comment]
> For the `jwt_secret`for example, a direct path to a secret file in the configuration.yml worked (maybe not intended), but for SQL password, really only setting the password in the config directly worked for me so far.

This is because setting the jwt_secret is only expected to be a string. We then hash it to ensure it's the correct length.

**Comment by james-d-elliott** [comment]
> All files are set to `chmod 600`. But with this above setup for mysql I only get the error, that it failed to connect as it can't use the password. Anything I am missing out?

Show the error?

**Comment by florianmueller** [comment]
Thank you, that made it clear. So I set the mysql password now in that way:
In configuration.yml (no `password` defined):
```
storage:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: authelia
```
Then in `/etc/environment` I set the env var like this:
```
AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE="/etc/authelia/.secrets/mysql"
```
This file has the plain password in it, like ´ apple123`.

Interestingly in the startup check it is now fine and writes to the log that the startup mysql check worked. 
But then it fails right after that with the following error in `systemctl status authelia`:
```
level=error msg="Configuration: storage: mysql: option 'username' and 'password' are required"
```
So to me that looks like the setup is right (structure check on startup works) but then somewhat else fails when it trys to actually use the password from that file
