### ISSUE TITLE
Parameter error while nextcloud-authelia integration

### ISSUE THREAD

**Issue by cmakyz** [authelia/authelia#4172]
### Version

v4.36.9

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

latest

### Description

I want to integrate Authelia and nextcloud. When I use the configurations in the documents, I get a parameter error. You can find the configuration and parameters I used below. 

![image](https://user-images.githubusercontent.com/40693865/195468559-da16d19f-c247-4a7c-affe-062fec779267.png)

### Reproduction

I followed the steps in the documents correctly but I couldn't understand why I got this error. I don't understand why identity_providers and other parameters are giving errors. I need help on this.

### Configuration

```yaml
# authelia-configuration.yml v1

identity_providers:
  clients:
    id: nextcloud
    description: NextCloud
    secret: fo6Z2LwswoPrXTj7dgUeYHasd123bfsfgdf67567safdsadfdas5d4ad4fgds6hgfd
    authorization_policy: two_factor
    redirect_uris:
      - https://nextcloud.example.com/apps/oidc_login/oidc
    scopes:
      - openid
      - groups
      - email
      - profile
```

### Documentation

https://blog.xataz.net/posts/authelia-nextcloud-et-openid/
https://www.authelia.com/integration/openid-connect/nextcloud/

**Comment by james-d-elliott** [comment]
```yaml

identity_providers:
  clients:
    - id: nextcloud
      description: NextCloud
      secret: fo6Z2LwswoPrXTj7dgUeYHasd123bfsfgdf67567safdsadfdas5d4ad4fgds6hgfd
      authorization_policy: two_factor
      redirect_uris:
        - https://nextcloud.example.com/apps/oidc_login/oidc
      scopes:
        - openid
        - groups
        - email
        - profile
```
