### ISSUE TITLE
Regression: rules using {group} never match if the user is not already logged in

### ISSUE THREAD

**Issue by kaysond** [authelia/authelia#4186]
### Version

v4.36.9

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.8.8

### Description

In v4.36.9, if a `one_factor` rule uses `{group}` in the domain, but the user is not logged in at all, that rule is never matched, and the default policy is applied instead. A not-logged-in user must be presented with a login screen so they have an opportunity to supply credentials at which point the groups could be checked.

This was the behavior in v4.32.2, so it seems like this is a regression. I went through the docs to make sure it's not some kind of config change, but couldn't find anything relevant (except that `{user}` is deprecated, but it was unclear whether `{group}` is).

### Reproduction

Define rules as follows:

```
  default_policy: deny

  rules:
    # Allow access based on groups
    - domain: '{group}.domain.com'
      policy: one_factor
```

then try to access something matching `group.domain.com`.

### Expectations

If the user is not logged in at all, and a `{group}` rule exists, authelia should redirect to the login page, as it did in v4.32.2.

### Logs

```shell
authelia_authelia.1.wep5uf99kkrx@mercy.nub.lan    | time="2022-10-16T16:37:03-07:00" level=debug msg="No matching rule for subject username= groups= ip=10.7.7.10 and url https://whoami.domain.com/ (method GET) applying default policy"
```

### Configuration

```yaml
---
theme: light
default_redirection_url: https://authelia.domain.com
default_2fa_method: ""
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
    client_certificates: []
  headers:
    csp_template: ""
log:
  level: debug
  format: text
telemetry:
  metrics:
    enabled: false
    address: tcp://0.0.0.0:9959
totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: true
duo_api:
  disable: true
ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  ldap:
    additional_groups_dn: ou=groups
    additional_users_dn: ou=people
    base_dn: DC=nublab,DC=ca
    display_name_attribute: displayName
    group_name_attribute: cn
    groups_filter: (member={dn})
    implementation: custom
    mail_attribute: mail
    start_tls: false
    timeout: 15s
    url: ldap://lldap_lldap:3890
    user: cn=authelia,ou=people,DC=domain,DC=com
    username_attribute: uid
    users_filter: (&({username_attribute}={input})(objectClass=person))
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3
access_control:
  default_policy: deny
  rules:
    - domain: '*.domain.com'
      policy: bypass
      resources:
        - "^/api.*"
    - domain: '{group}.domain.com'
      policy: one_factor
session:
  name: authelia_session
  domain: domain.com
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  redis:
    host: authelia_redis
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: bpg2qz8EaqDn4zRHS7g85BRRayE9mCIJfs0Lrooo 
  mysql:
    host: authelia_db
    port: 3306
    database: authelia
    username: authelia
    timeout: 10s
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
```
