### ISSUE TITLE
mysql: error: storage error loading authelia due to schema collation change

### ISSUE THREAD

**Issue by YouveGotMeowxy** [authelia/authelia#4245]
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Description

Trying to start Authelia errors out, and naturally none of the containers I protect with Authelia are usable/accessible.

### Reproduction

All I did was pull the latest Authelia image.

### Logs

```shell
From the log:


time="2022-10-23T02:16:06-05:00" level=warning msg="Configuration: configuration key 'server.read_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.read': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-10-23T02:16:06-05:00" level=warning msg="Configuration: configuration key 'server.write_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.write': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-10-23T02:16:06-05:00" level=warning msg="Configuration: configuration key 'authentication_backend.disable_reset_password' is deprecated in 4.36.0 and has been replaced by 'authentication_backend.password_reset.disable': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-10-23T02:16:06-05:00" level=info msg="Authelia v4.37.0 is starting"
time="2022-10-23T02:16:06-05:00" level=info msg="Log severity set to debug"
{"level":"debug","msg":"Registering client [oc]-portainer with policy two_factor (2)","time":"2022-10-23T02:16:06-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-10-23T02:16:06-05:00"}
{"level":"info","msg":"Storage schema migration from 5 to 6 is being attempted","time":"2022-10-23T02:16:06-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 6 to version 5 for rollback: schema migration 6 (ConsentPreConfiguration) failed: Error 1051: Unknown table 'authelia.oauth2_authorization_code_session'. rollback caused by: schema migration 6 (ConsentPreConfiguration) failed: Error 3780: Referencing column 'subject' and referenced column 'identifier' in foreign key constraint 'oauth2_consent_preconfiguration_subjct_fkey' are incompatible.","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":277,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":1040,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client attempting connection to smtp.gmail.com:465","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client using submissions port 465. Make sure the mail server you are connecting to is configured for submissions and not SMTPS.","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client connected successfully","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP connection is already encrypted, skipping STARTTLS","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client attempting AUTH PLAIN with server","time":"2022-10-23T02:16:06-05:00"}
{"level":"debug","msg":"Notifier SMTP client authenticated successfully with the server","time":"2022-10-23T02:16:06-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":305,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":1040,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.0/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-10-23T02:16:07-05:00"}
```
```


### Configuration

_No response_

### Documentation

_No response_

**Comment by crypticviper** [comment]
I too get errors post 4.37 (docker image version) update. Switching back to 4.36 worked for me.

`time="2022-10-23T09:56:33+02:00" level=error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* error decoding 'identity_providers.oidc.clients[1].secret': could not decode '$plaintext$XXXXX*' to a *schema.PasswordDigest: plaintext decode error: provided encoded hash has an invalid format"
time="2022-10-23T09:56:33+02:00" level=fatal msg="Can't continue due to the errors loading the configuration"`

**Comment by james-d-elliott** [comment]
> I too get errors post 4.37 (docker image version) update. Switching back to 4.36 worked for me.
> 
> `time="2022-10-23T09:56:33+02:00" level=error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* error decoding 'identity_providers.oidc.clients[1].secret': could not decode '$plaintext$XXXXX*' to a *schema.PasswordDigest: plaintext decode error: provided encoded hash has an invalid format" time="2022-10-23T09:56:33+02:00" level=fatal msg="Can't continue due to the errors loading the configuration"`
> 
> Not sure if the errors are related to OP (but are definitely related to 4.37).

Unrelated, fill out an issue.

**Comment by james-d-elliott** [comment]
Database?

**Comment by ntimo** [comment]
I am also having this issue with a mariadb database. I had to restore a backup of the database to get the old version running again.

**Comment by newkindofworld** [comment]
Same here with 4.37, revert to 4.6.9 solves it.

`23/10/2022 10:29:13
time="2022-10-23T10:29:13+02:00" level=warning msg="Configuration: configuration key 'server.read_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.read': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
23/10/2022 10:29:13
time="2022-10-23T10:29:13+02:00" level=warning msg="Configuration: configuration key 'authentication_backend.disable_reset_password' is deprecated in 4.36.0 and has been replaced by 'authentication_backend.password_reset.disable': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
23/10/2022 10:29:13
time="2022-10-23T10:29:13+02:00" level=warning msg="Configuration: configuration key 'server.write_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.write': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
23/10/2022 10:29:13
time="2022-10-23T10:29:13+02:00" level=error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* error decoding 'notifier.smtp.tls.minimum_version': could not decode 'StartTLS' to a schema.TLSVersion: supplied tls version isn't supported"
23/10/2022 10:29:13
time="2022-10-23T10:29:13+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
23/10/2022 10:29:13
time="2022-10-23T10:29:13+02:00" level=fatal msg="Can't continue due to the errors loading the configuration"`

**Comment by james-d-elliott** [comment]
@newkindofworld  unrelated. Open a new issue.

**Comment by james-d-elliott** [comment]
> I am also having this issue with a mariadb database. I had to restore a backup of the database to get the old version running again.

Does upgrading again cause the same error?

**Comment by james-d-elliott** [comment]
@ntimo can you confirm the collation of your current tables and the collation when you create a new table in that database? That  error is most common when the database has been upgraded automatically changing the default collation (FK collations must match). Maybe we have to perform yet another workaround to get MySQL to remain happy, uhg.

**Comment by ntimo** [comment]
@james-d-elliott yes the collations are the same here is a screenshot:
![Screenshot from 2022-10-23 12-44-35](https://user-images.githubusercontent.com/6145026/197387997-b6bb3fc6-c921-4388-8f05-62724337480c.png)

**Comment by ntimo** [comment]
@james-d-elliott okay with the restored database the upgrade worked just fine. Maybe as you mentioned before they where not the same collation which I can't check anymore since I restored the db.

**Comment by james-d-elliott** [comment]
> @james-d-elliott okay with the restored database the upgrade worked just fine. Maybe as you mentioned before they where not the same collation which I can't check anymore since I restored the db.

Yeah I'm suspecting it is. The type for the column in question has always been CHAR(36), same as the FK. It can throw that specific error if the types are incompatible or if the collation mismatch exists. I think we will just have to figure out a way to force all of the table collations to `utf8_unicode_ci` or `utf8mb4_unicode_ci` at a future date.

If MySQL/MariaDB allows upgrading in this context we're just forced to pick a collation and shoehorn people into using it I guess.

**Comment by james-d-elliott** [comment]
Can you confirm that you've done a significant upgrade to your database in the last few months @ntimo ?

**Comment by YouveGotMeowxy** [comment]
> Database? You forgot the config also.

Sorry, I posted and went right to sleep.

I'm using the latest MySQL.

![image](https://user-images.githubusercontent.com/39491297/197404859-c1742c1a-f205-4b78-a232-27fc5d47d61b.png)

![image](https://user-images.githubusercontent.com/39491297/197405014-9f7056ab-56df-4305-935f-164ab4165387.png)

I've tried upgrading the container several times but the result is the same.

If you still need the config, can you tell me specifically which part? (the docker compose? to .conf file? Specific section in conf file?)

**Comment by nearcatch** [comment]
> can you confirm the collation of your current tables and the collation when you create a new table in that database? That error is most common when the database has been upgraded automatically changing the default collation (FK collations must match). Maybe we have to perform yet another workaround to get MySQL to remain happy, uhg.

Not ntimo, but also having this issue, collation of new table (test) is same other tables. `utf8mb4_general_ci` instead of `utf8mb4_unicode_ci` though. Authelia 4.37.0 and MariaDB 10.6.10 (linuxserver/mariadb)
![image](https://user-images.githubusercontent.com/692914/197406425-de3ff3fb-1b5c-4cbf-8088-a0ee07e86cea.png)

<details>
  <summary>docker compose - authelia</summary>

```yml
  authelia: &authelia
    container_name: authelia
    # image: authelia/authelia
    image: ghcr.io/authelia/authelia:4.37.0
    restart: unless-stopped
    networks:
      t2_proxy:
    # ports:
    #   - "9091:9091"
    depends_on:
      - mariadb
      - redis
    volumes: &authelia_volumes
      - $CONTDIR/authelia:/config
      # - type: bind
        # source: $CONTDIR/authelia
        # target: /config
    environment:
      - TZ=$TZ
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/authelia_session_redis_password
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
    secrets:
      - authelia_duo_api_secret_key
      - authelia_jwt_secret
      - authelia_notifier_smtp_password
      - authelia_session_secret
      - authelia_session_redis_password
      - authelia_storage_encryption_key
      - authelia_storage_mysql_password
    labels:
     ## Diun
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=^latest$$"
     ## Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=websecure"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAIN1`)"
      # Middlewares
      # - "traefik.http.routers.authelia-rtr.middlewares=authelia-headers@file,chain-authelia@file"
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
     ## unRAID
      - "net.unraid.docker.icon=$CONTDIR/_unraid-icons/authelia.png"
```
</details>
<details>
  <summary>docker compose - mariadb</summary>

```yml
  mariadb:
    # After starting container for first time dexec and mysqladmin -u root password <password>
    container_name: mariadb
    image: ghcr.io/linuxserver/mariadb:10.6.10
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CONTDIR/mariadb/data:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password # no effect after initial run
      - FILE__MYSQL_AUTHELIA_PASSWORD=/run/secrets/mysql_authelia_password
      - FILE__MYSQL_PHPMYADMIN_PASSWORD=/run/secrets/mysql_phpmyadmin_password
      # - MYSQL_DATABASE=database
      # - MYSQL_USER=username
      # - MYSQL_PASSWORD=password
    secrets:
      - mysql_root_password
      - mysql_authelia_password
      - mysql_phpmyadmin_password
    labels:
     ## Diun
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=^(\\d+\\.\\d+\\.\\d+|alpine)$$"
     ## unRAID
      - "net.unraid.docker.icon=$CONTDIR/_unraid-icons/mariadb.png"
```
</details>

</details>
<details>
  <summary>authelia - configuration.yml</summary>

```yml
###############################################################
#                   Authelia configuration                    #
###############################################################

## The theme to display: light, dark, grey, auto.
theme: auto

# I used this site to generate the secret: https://www.grc.com/passwords.htm
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://authelia.DOMAIN.COM

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info
  # format: text # or json
  # file_path: /config/authelia.log

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024 # blocks this much of the RAM. Tune this.

regulation:
  max_retries: 3
  find_time: 120 # 2 minutes
  ban_time: 300 # 5 minutes

ntp:
  address: "router.lan:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

totp:
  issuer: authelia.com
  period: 30
  skew: 0

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
duo_api:
  hostname: api-XXXXXXXX.duosecurity.com
  integration_key: YYYYYYYYYYYYYYYYYYYY
  # secret_key: # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  networks:
  - name: docker
    networks:
    - 192.168.84.200 # heimdall
  rules:
    # Rules applied to everyone
    - domain: authelia.DOMAIN.COM
      policy: bypass
    # - domain: radarr.DOMAIN.COM
    #   policy: bypass
    #   subject: "group:admins"
    #   resources:
    #   - "^/api/.*$"      
    - domain: ["DOMAIN.COM", "*.DOMAIN.COM"]
      policy: two_factor

session:
  name: authelia_session
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: DOMAIN.COM # Should match whatever your root protected domain is

# Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
  redis:
    host: redis
    port: 6379
    # password: authelia # use docker secret file instead AUTHELIA_SESSION_REDIS_PASSWORD_FILE

storage:
  # encryption_key: a_very_important_secret # use docker secret file instead AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
# For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
 # local:
   # path: /config/db.sqlite3
  mysql:
  # MySQL allows running multiple authelia instances. Create database and enter details below.
    host: mariadb
    port: 3306
    database: authelia
    username: authelia
    # password: use docker secret file instead AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE

notifier:
  disable_startup_check: false
  smtp:
    # You can disable the notifier startup check by setting this to true.
    username: EMAIL@gmail.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: smtp.gmail.com
    port: 587 #465
    sender: EMAIL@gmail.com
    subject: "[Authelia] {title}"
    startup_check_address: test@authelia.com
    disable_require_tls: false
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
  # filesystem:
    # filename: /config/notifications.txt
```
</details>
