### ISSUE TITLE
4.37 fails to connect to postgres database

### ISSUE THREAD

**Issue by TastyPi** [authelia/authelia#4249]
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.6.2

### Description

Authelia fails to connect to my postgres database on startup, when the exact same setup works with 4.36.9.

It sounds related to https://github.com/authelia/authelia/issues/4245, except that's a mariadb. It is potentially related to https://github.com/authelia/authelia/issues/4247 as I use a secret for the storage password, but I'm not seeing the same error message.

### Reproduction

All I have to do to reproduce is update to 4.37.0, but obviously there might be something specific to my setup causing the issue. I've provided both my `docker-compose.yml` and `configuration.yml`, hopefully that will help with finding a minimal reproduction.

### Expectations

Minor version bumps of Authelia should work with the same setup.

### Logs

```shell
time="2022-10-23T12:36:08Z" level=error msg="Failure running the storage provider startup check: error pinging database: failed to connect to `host=db user=authelia database=authelia`: dial error (dial tcp 172.27.0.3:4321: connect: connection refused)" stack="github.com/authelia/authelia/v4/internal/commands/root.go:277 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.0/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.0/command.go:1040                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.0/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
time="2022-10-23T12:36:08Z" level=fatal msg="The following providers had fatal failures during startup: storage" stack="github.com/authelia/authelia/v4/internal/commands/root.go:305 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.0/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.0/command.go:1040                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.0/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"


Here's those stacktraces formatted:

github.com/authelia/authelia/v4/internal/commands/root.go:277 doStartupChecks
github.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun
github.com/spf13/cobra@v1.6.0/command.go:920                  (*Command).execute
github.com/spf13/cobra@v1.6.0/command.go:1040                 (*Command).ExecuteC
github.com/spf13/cobra@v1.6.0/command.go:968                  (*Command).Execute
github.com/authelia/authelia/v4/cmd/authelia/main.go:10       main
runtime/proc.go:250                                           main
runtime/asm_amd64.s:1594                                      goexit

github.com/authelia/authelia/v4/internal/commands/root.go:305 doStartupChecks
github.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun
github.com/spf13/cobra@v1.6.0/command.go:920                  (*Command).execute
github.com/spf13/cobra@v1.6.0/command.go:1040                 (*Command).ExecuteC
github.com/spf13/cobra@v1.6.0/command.go:968                  (*Command).Execute
github.com/authelia/authelia/v4/cmd/authelia/main.go:10       main
runtime/proc.go:250                                           main
runtime/asm_amd64.s:1594                                      goexit
```

### Configuration

```yaml
theme: auto
# jwt_secret: secrets/jwt_secret
totp:
  issuer: <my.domain>
webauthn:
  disable: true
authentication_backend:
  ldap:
    url: ldap://lldap
    base_dn: dc=lldap
    username_attribute: uid
    additional_users_dn: ou=people
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    ## The username and password of the admin user.
    user: uid=admin,ou=people,dc=lldap
    # password: secrets/lldap_admin_password
access_control:
  rules:
    - domain: "*.<my.domain>"
      policy: two_factor
      subject: "user:<me>"
session:
  name: <my.domain>
  domain: <my.domain>
  # secret: secrets/session_secret
  redis:
    host: authelia-redis
    port: 6379
storage:
  # encryption_key: secrets/encryption_key
  postgres:
    host: db
    database: authelia
    username: authelia
    # password: secrets/storage_password
notifier:
  filesystem:
    filename: /config/notification-public.txt
```

### Documentation

My docker-compose.yml:

```yml
version: "3.8"
services:
  authelia:
    # Switching to 4.36 works
    image: authelia/authelia:4.37
    container_name: authelia
    depends_on:
      - db
      - redis
    environment:
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/lldap_admin_password
      - AUTHELIA_JWT_SECRET_FILE=/secrets/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage_encryption_key
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/secrets/storage_password
    volumes:
      - ./config:/config
      - ./secrets:/secrets
    secrets:
      - lldap_admin_password
    restart: unless-stopped
  db:
    image: postgres:14-alpine
    container_name: authelia-db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/storage_password
      POSTGRES_USER: authelia
      POSTGRES_DB: authelia
    secrets:
      - storage_password
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: authelia-redis
    volumes:
      - ./redis:/data
    restart: unless-stopped
secrets:
  lldap_admin_password:
    file: ../lldap/secrets/admin_password
```

**Comment by otaconix** [comment]
As can be seen by the log messages, Authelia tries to connect on port 4321 (which I'm guessing is a typo). 

As a workaround, you can explicitly set the port to connect to (which is 5432 by default) in your `configuration.yml`:

```yaml
// Snip...
storage:
  postgres:
    port: 5432
// Snip...
```
