### ISSUE TITLE
OpenID Connect: Groups are not passed to app/jwt token

### ISSUE THREAD

**Issue by dakky** [authelia/authelia#4257]
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.9.1

### Description

I configured an OpenID client with scope `groups`. This scope is not asked for access when logging in and the JWT token contains an empty array.

Authelia asking for permission to pass userinfos:
![grafik](https://user-images.githubusercontent.com/579584/197577766-db7ef713-e5d8-4b0c-9f97-c8345fedc7c4.png)

JWT Token from the cookie tab of the browser after logging in:
```
{
  "id": 4,
  "email": "user@domain.com",
  "name": "Username",
  "av": "",
  "tz": "America/New_York",
  "lc": "de",
  "df": "",
  "ap": "",
  "permissions": [],
  "groups": [],
  "iat": 1666629099,
  "exp": 1666630899,
  "aud": "urn:wiki.js",
  "iss": "urn:wiki.js"
}
```

### Reproduction

Configure an OICD provider with groupo scope and use it in an app (wiki.js in my case)

### Configuration

```yaml
identity_providers:
  oidc:
    # hmac_secret: provided via secret file
    # issuer_private_key: provided via secret file
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: true
    # clients using openid auth
    clients:
      - id: wikijs
        description: wiki JS
        secret: XXXXXXXX
        public: false
        authorization_policy: two_factor
        audience: []
        scopes:
          - openid
          - email
          - profile
          - groups
        redirect_uris:
        # this URL is given by wiki.js on the OpenID Connect config page as callback URL
          - https://wiki.domain.com/login/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/callback
        userinfo_signing_algorithm: none
        response_modes:
          - form_post
```
