### ISSUE TITLE
Accents in groups base DN causes LDAP search error (NO_OBJECT)

### ISSUE THREAD

**Issue by nhannebicque-imsa** [authelia/authelia#4274]
### Version

v4.36.9

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.2.11

### Description

Our Authelia instance is connected to our AD where some of our groups contains accented characters.

We were planning to upgrade from version 4.25.2 where groups retrieval was working fine to 4.36.9.

For diagnostic purposes, we have tested search against a group base DN without any accented character and it works fine.

### Reproduction

Specify an additional group DN with accented characters in it, then try to log in. Group search fails with error : 

Could not obtain profile details during 1FA authentication for user 'x.xyz': unable to retrieve groups of user 'x.xyz'. Cause: LDAP Result Code 32 \"No Such Object\": 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=XXX,DC=com'\n\x00

### Logs

```shell
time="2022-10-26T15:37:46+02:00" level=trace msg="Detected user filter is (&(sAMAccountName=x.xyz)(objectClass=user))"
time="2022-10-26T15:37:46+02:00" level=debug msg="Mark 1FA authentication attempt made by user 'x.xyz'" method=POST path=/api/firstfactor remote_ip=10.0.2.15
time="2022-10-26T15:37:46+02:00" level=debug msg="Successful 1FA authentication attempt made by user 'x.xyz'" method=POST path=/api/firstfactor remote_ip=10.0.2.15
time="2022-10-26T15:37:46+02:00" level=trace msg="Detected user filter is (&(sAMAccountName=x.xyz)(objectClass=user))"
time="2022-10-26T15:37:46+02:00" level=trace msg="Computed groups filter is (&(member=CN=X XYZ,OU=BLABLA,OU=Utilisateurs,DC=XXX,DC=com)(objectClass=group))"
time="2022-10-26T15:37:46+02:00" level=error msg="Could not obtain profile details during 1FA authentication for user 'x.xyz': unable to retrieve groups of user 'n.hannebicque'. Cause: LDAP Result Code 32 \"No Such Object\": 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=XXX,DC=com'\n\x00" method=POST path=/api/firstfactor remote_ip=10.0.2.15 stack="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:113 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54            (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25           SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35           SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16           SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.12/router.go:414                             (*Router).Handler\ngithub.com/valyala/fasthttp@v1.40.0/http.go:154                              (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2311                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:224                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:196                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                     goexit"
time="2022-10-26T15:37:46+02:00" level=trace msg="Timing Attack Delay successful: false, exec duration: 248, avg execution duration: 1000, random delay ms: 73, total delay ms: 1073, actual delay ms: 825" method=POST path=/api/firstfactor remote_ip=10.0.2.15
```

### Configuration

```yaml
ldap:
    implementation: activedirectory
    url: ldap://10.x.y.z
    timeout: 5s
    start_tls: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
    base_dn: dc=XXX,dc=com
    username_attribute: sAMAccountName
    additional_users_dn: OU=BLABLA,OU=Utilisateurs
    users_filter: (&({username_attribute}={input})(objectClass=user))
    additional_groups_dn: "OU=Groupes de sécurité"
    groups_filter: (&(member={dn})(objectClass=group))
    permit_referrals: false
    user: cn=xxx,OU=XXXX,OU=Utilisateurs,DC=XXX,DC=com
    password: xxxx
```
