### ISSUE TITLE
"authelia could not be resolved" : authelia with swag

### ISSUE THREAD

**Issue by jeromeSH26** [authelia/authelia#4275]
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

latest

### Description

When adding authelia to the swag configuration for one service, calling this service from internal or external network failed in HTTP 500 although the rule is "bypass". (Re) commenting the authelia lines in the swag service config file fix the problem.

Looking at the SWAG NGinx logs, it shows `" [error] 281#281: *28 authelia could not be resolved (3: Host not found), client: 141.101.68.186, server: jens.*, request: "GET / HTTP/2.0", subrequest: "/authelia/api/verify", host: "jens.myd.com""`

Authelia and Swag are both docker containers, in the same network ("bridge").
The jens service to be secured is located in another device and this is not a docker container. 

path is "authelia" in the config file and the container name is also "authelia"

### Reproduction

call the service "jens.myd.com" with authelia 
error HTTP

### Logs

```shell
No error in authelia logs
Error in swag :  `" [error] 281#281: *28 authelia could not be resolved (3: Host not found), client: 141.101.68.186, server: jens.*, request: "GET / HTTP/2.0", subrequest: "/authelia/api/verify", host: "jens.myd.com""`
```

### Configuration

```yaml
theme: light

jwt_secret: fddfdf

default_2fa_method: ""

server:
  host: 0.0.0.0
  port: 9091
  path: "authelia"
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

log:
  level: debug

telemetry:
  metrics:
    enabled: false
    address: tcp://0.0.0.0:9959

webauthn:
  disable: true

duo_api:
  disable: true

totp:
  disable: true
  issuer: myd.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ""
  refresh_interval: 5m
  file:
     path: /config/users_database.yml
     watch: false
     search:
       email: false
       case_insensitive: false
     password:
       algorithm: argon2
       argon2:
         variant: argon2id
         iterations: 3
         memory: 65536
         parallelism: 4
         key_length: 32
         salt_length: 16
       scrypt:
         iterations: 16
         block_size: 8
         parallelism: 1
         key_length: 32
         salt_length: 16
       pbkdf2:
         variant: sha512
         iterations: 310000
         salt_length: 16
       sha2crypt:
         variant: sha512
         iterations: 50000
         salt_length: 16
       bcrypt:
         variant: standard
         cost: 12

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3


access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - 192.168.1.0/24
    # - name: VPN
    #   networks: 10.9.0.0/16
  rules:
    ## Rules applied to everyone
    # - domain: 'public.example.com'
    #   policy: bypass
    - domain: '*.myd.com'
      policy: bypass
      networks:
        - internal

    - domain: '*.myd.com'
      policy: bypass

## The available providers are: `memory`, `redis`. Memory is the provider unless redis is defined.
session:
  ## The name of the session cookie.
  name: authelia_session
  domain: myd.com
  same_site: lax
  secret: xcxcxw
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
   encryption_key: scxwsdfsdq
   local:
     path: /config/db.sqlite3
```

### Documentation

**swag conf file for service jen**
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name jen.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    # enable for Authelia (requires authelia-location.conf in the location block)
    include /config/nginx/authelia-server.conf;

    location / {
        # enable for Authelia (requires authelia-server.conf in the server block)
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.1.40;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

```

containers and their networks :
![image](https://user-images.githubusercontent.com/51024915/198074740-744f53f8-fa99-4fbc-9c79-a7234bc80dfa.png)

![image](https://user-images.githubusercontent.com/51024915/198074944-9870eb20-c292-4c5f-af4e-c1a94133986f.png)

![image](https://user-images.githubusercontent.com/51024915/198075114-2af36891-f5e0-4236-91e2-1b31d14ba39b.png)
