### ISSUE TITLE
Configured Portal URL does not appear to be able to write cookies for domain - Since update

### ISSUE THREAD

**Issue by philhagger** [authelia/authelia#4287]
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

v2.9.4

### Description

Authelia and Traefik have been working perfectly together. As of the latest update when I am unauthorised sites are not redirecting to the authelia portal and are simply producing a 401 error.

The authelia logs state:
Configured Portal URL 'https://auth.mydomain' does not appear to be able to write cookies for the 'my domain' domain

### Reproduction

Visit any site whilst not logged in via authelia

### Expectations

Visiting sites whilst unauthorised should redirect to the authelia portal as before.

### Logs

```yaml
28/10/2022 8:52:29
time="2022-10-28T08:52:29+01:00" level=error msg="Configured Portal URL 'https://auth.<domain>' does not appear to be able to write cookies for the '.<domain>' domain" method=GET path=/api/verify remote_ip=192.168.1.160 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:215 handleUnauthorized\ngithub.com/authelia/authelia/v4/internal/handlers/handler_verify.go:490 VerifyGET.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54       (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16      SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.12/router.go:414                        (*Router).Handler\ngithub.com/valyala/fasthttp@v1.40.0/http.go:154                         (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.40.0/server.go:2311                      (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:224                   (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.40.0/workerpool.go:196                   (*workerPool).getCh.func1\nruntime/asm_arm64.s:1172                                                goexit"
```

##### Authelia docker compose
```version: '3'

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - $APPPATH/authelia/appdata/config:/config
    networks:
      - proxy_net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.mydomain`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.mydomain'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    healthcheck:
      disable: true

networks:
  proxy_net:
    external: true
```

##### Authelia configuration.yml
```
theme: dark

jwt_secret: *********

server:
    host: 0.0.0.0
    port: 9091
 
log:
    level: debug

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
    

authentication_backend:
    file:
        path: /config/users_database.yml
        password:
          algorithm: argon2id
          iterations: 3
          key_length: 32
          salt_length: 16
          parallelism: 4
          memory: 64
            
access_control:
    default_policy: deny
    rules:
      - domain: '*.local.mydomain'
        policy: bypass

      - domain: '*.mydomain'
        networks: '192.168.1.0/24'
        policy: one_factor

      - domain: '*.mydomain'
        policy: two_factor

session:
    domain: .mydomain #putting the dot at the beginning allows for subdomains
    
storage:
    encryption_key: ***********
    local:
        path: /config/db.sqlite3
        
notifier:
    filesystem:
        filename: /config/notification.txt
```

**Comment by philhagger** [comment]
This has been working perfectly for months now. The only change was Watchtower updated my authelia image and the redirect stopped working.

**Comment by james-d-elliott** [comment]
You've not provided enough information to replicate this, the functionality is tested, and no one else is having issues.

**Comment by philhagger** [comment]
What additional information can I provide to assist?

**Comment by james-d-elliott** [comment]
The information requested in the template, logs, config, etc. Also please follow https://www.authelia.com/reference/guides/troubleshooting-sanitizaiton/

**Comment by philhagger** [comment]
Updated issue with docker compose and configuration.

**Comment by james-d-elliott** [comment]
Replace `.mydomain.com` with `mydomain.com`.

**Comment by SoulEater45** [comment]
I am having the exact same problem as @philhagger 
I am running watchtower to keep the containers up-to-date, and for 3-4 weeks I am having the problem of not being redirected to the login page, but stuck with a `401 Unauthorized`.
My log output and docker-compose configuration is the same. My authelia configuration is as follows:
```yml
theme: light

jwt_secret: <jwt secret>

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m
  ldap:
    <ldap_config>

access_control:
  default_policy: bypass
  rules:
    - domain: analytics.example.com
      policy: bypass
    - domain: "*.example.com"
      policy: one_factor

session:
  name: authelia_session
  secret: <secret>
  expiration: 3600
  inactivity: 300
  domain: example.com

  redis:
    host: redis_authelia
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: <encryption_key>
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

```
