### ISSUE TITLE
LDAP + groups cause bad gateway 

### ISSUE THREAD

**Issue by boredjo** [authelia/authelia#4378]
### Version

v4.37.1

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.5.7

### Description

When I access a domain protected by a subject group subject rule, I get a bad gateway error. When I use a file backend instead of the LDAP server it works. When I remove the subject rule, it also works. Authelia reads the group from the LDAP server correctly. 

### Reproduction

Here is my traefik middleware file:

```
http:   
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.example.com%2F
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
    authelia-basic:
      forwardAuth:
        address: http://authelia:9091/api/verify?auth=basic
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
        
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
        
 tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       
```

### Logs

```shell
time="2022-11-14T10:49:45+01:00" level=debug msg="Check authorization of subject username= groups= ip=157.97.134.67 and object https://flame.jokaendler.eu/ (method GET)."
time="2022-11-14T10:49:45+01:00" level=info msg="Access to https://flame.jokaendler.eu/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.jokaendler.eu/?rd=https%3A%2F%2Fflame.jokaendler.eu%2F&rm=GET" method=GET path=/api/verify remote_ip=157.97.134.67
```

### Configuration

```yaml
authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8
#  ldap:
#    implementation: custom
#    url: ldap://openldap:389
#    timeout: 5s
#    start_tls: false
#    tls:
#      server_name: openldap.jokaendler.eu
#      skip_verify: true
#      minimum_version: TLS1.2
#    base_dn: DC=example,DC=com
#    additional_users_dn: OU=users
#    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
#    username_attribute: uid
#    mail_attribute: Email
#    display_name_attribute: displayName
#    additional_groups_dn: OU=groups
#    groups_filter: (&(member={dn})(objectClass=groupOfNames))
#    group_name_attribute: cn
#    user: cn=admin,DC=example,DC=com
#    password: "…"

access_control:
  default_policy: deny
  rules:
    - domain: "auth.example.com" #This should be your authentication URL
      policy: bypass
    - domain:
        - "api.example.com"
      policy: bypass
      
      # admin rights:
    - domain:
        - "flame.example.com“
      policy: two_factor
      subject:
        - ['group:admins']

session:
  name: authelia_session
  secret: "…"
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  remember_me_duration: 24h
  domain: example.com # Should match whatever your root protected domain is
  redis:
    host: redis
    port: 6379
    password: "…"
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 4h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: "…"
```
