### ISSUE TITLE
Portal URL is not able to write cookies for domain -> no redirection to `login.example.com`

### ISSUE THREAD

**Issue by SoulEater45** [authelia/authelia#4442]
### Version

v4.37.2

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.9.5

### Description

When visiting a site, I am getting the message `401 Unauthorized` without being redirected. I would  need to open a new tab, go to the login URL and login in. Afterwards, refreshing the site would bring up the wanted website.

In the logs below, I am trying to access `app.example.com` using a machine with IP `10.11.12.13`.
Maybe it is relevant, but the domain is behind a cloudflare proxy.

A similar issue was #4287, but I wasn't able to fix it with the provided solution, i.e., my config never had `.example.com`, but `example.com` was already set as the session domain.

### Reproduction

- Configure traefik and authelia as described [here](https://www.authelia.com/integration/proxies/traefik/)
- Make the relevant changes in the authelia config as described in the config provided below
- Run the traefik, authelia, and redis instance using docker compose
- Visit a site, for example `app.example.com`
- Getting a `401 Unauthorized` message and the log in authelia, as shown below

### Expectations

Being redirected to the login page `login.example.com` instead of getting the 401 error.

### Configuration (Authelia)

```yaml
theme: light

jwt_secret: <jwt secret>

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m
  ldap:
    <ldap_config>

access_control:
  default_policy: bypass
  rules:
    - domain: analytics.example.com
      policy: bypass
    - domain: "*.example.com"
      policy: one_factor

session:
  name: authelia_session
  secret: <secret>
  expiration: 3600
  inactivity: 300
  domain: example.com

  redis:
    host: redis_authelia
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: <encryption_key>
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```

### Logs (Authelia)

```shell
time="2022-11-28T13:49:56+01:00" level=info msg="Authelia v4.37.2 is starting"
time="2022-11-28T13:49:56+01:00" level=info msg="Log severity set to debug"
time="2022-11-28T13:49:56+01:00" level=info msg="Storage schema is being checked for updates"
time="2022-11-28T13:49:56+01:00" level=info msg="Storage schema is already up to date"
time="2022-11-28T13:49:56+01:00" level=debug msg="LDAP Supported OIDs. Control Types: 2.16.840.1.113730.3.4.18, 2.16.840.1.113730.3.4.2, 1.3.6.1.4.1.4203.1.10.1, 1.3.6.1.1.22, 1.2.840.113556.1.4.319, 1.2.826.0.1.3344810.2.3, 1.3.6.1.1.13.2, 1.3.6.1.1.13.1, 1.3.6.1.1.12. Extensions: 1.3.6.1.4.1.1466.20037, 1.3.6.1.4.1.4203.1.11.1, 1.3.6.1.4.1.4203.1.11.3, 1.3.6.1.1.8"
time="2022-11-28T13:49:56+01:00" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
time="2022-11-28T13:49:56+01:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2022-11-28T13:50:34+01:00" level=debug msg="Check authorization of subject username= groups= ip=10.11.12.13 and object https://app.example.com/ (method GET)."
time="2022-11-28T13:50:34+01:00" level=error msg="Configured Portal URL 'http://login.example.com/' does not appear to be able to write cookies for the 'example.com' domain" method=GET path=/api/verify remote_ip=10.11.12.13 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:215 handleUnauthorized\ngithub.com/authelia/authelia/v4/internal/handlers/handler_verify.go:490 VerifyGET.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54       (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16      SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.12/router.go:414                        (*Router).Handler\ngithub.com/valyala/fasthttp@v1.41.0/http.go:154                         (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.41.0/server.go:2324                      (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.41.0/workerpool.go:224                   (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.41.0/workerpool.go:196                   (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                goexit"
```

### Logs (Proxy / Application)

```json
{
  "ClientAddr":"198.41.242.154:49362",
  "ClientHost":"10.11.12.13",
  "ClientPort":"49362",
  "ClientUsername":"-",
  "DownstreamContentSize":16,
  "DownstreamStatus":401,
  "Duration":6494850,
  "OriginContentSize":16,
  "OriginDuration":6387552,
  "OriginStatus":401,
  "Overhead":107298,
  "RequestAddr":"app.example.com",
  "RequestContentSize":0,
  "RequestCount":628,
  "RequestHost":"app.example.com",
  "RequestMethod":"GET",
  "RequestPath":"/",
  "RequestPort":"-",
  "RequestProtocol":"HTTP/2.0",
  "RequestScheme":"https",
  "RetryAttempts":0,
  "RouterName":"app@docker",
  "StartLocal":"2022-11-28T14:32:33.15023779+01:00",
  "StartUTC":"2022-11-28T13:32:33.15023779Z",
  "TLSCipher":"TLS_AES_128_GCM_SHA256",
  "TLSVersion":"1.3",
  "entryPointName":"websecure",
  "level":"info","msg":"",
  "time":"2022-11-28T14:32:33+01:00"
}
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
