### ISSUE TITLE
Authelia Crashes After v4.37.3 Update: Schema Migration Failed

### ISSUE THREAD

**Issue by droans** [authelia/authelia#4520]
### Version

v4.37.3

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.8.8

### Description

Schema migration fails after update to v4.37.3, causing Authelia to crash. Despite the log suggesting corruption, the tables are fine.

It does not appear like any of the migration occurred. I am able to roll back to v4.37.2 without any issue and none of the tables appear to have been altered since 12/6, verified by last date flag of table files, through the timestamps on the rows, and as the Migrations table does not list Schema v7 nor do any of the CREATE/DROP requests appear to be processed. 

Appears related to #4262 

### Reproduction

Occurs on start in v4.37.3

### Configuration (Authelia)

```yaml
server:
    host: 0.0.0.0
    port: 9091

log:
    level: warn

default_redirection_url: "https://authelia.XXXX.YYYY"

totp:
    issuer: XXXX.YYYY
    period: 30
    skew: 1

authentication_backend:

    ldap:
        implementation: custom
        url: ldap://192.168.XX.XX
        timeout: 5s
        base_dn: DC=XXXX,DC=XXXX
        username_attribute: uid
        additional_users_dn: ou=users
        users_filter: (&({username_attribute}={input})(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (&(member={dn})(objectClass=group))
        group_name_attribute: cn
        mail_attribute: mail
        display_name_attribute: displayName
        permit_referrals: false
        user: cn=XXXX,dc=XXXX,dc=XXXX

access_control:
    default_policy: deny
    rules:
    - domain: authelia.XXXX.YYYY
      policy: bypass
    - domain: "*.XXXX.YYYY"
      policy: two_factor
    - domain: "XXXX.YYYY"
      policy: deny
    - domain: "*.ZZZZ.AAAA"
      policy: two_factor

session:
    name: authelia_session
    expiration: 30d #3600
    inactivity: 1d

    domain: XXXX.YYYY

    redis:
        host: 192.168.XX.XX
        port: 6379

regulation:
    max_retries: 3
    find_time: 120
    ban_time: 300

storage:

    mysql:
        host: mariadb
        port: 3306
        database: authelia
        username: authelia

notifier:
    smtp:
        username: XXXX@gmail.com
        host: smtp.gmail.com
        port: 587
        sender: xxxx@gmail.com

identity_providers:
    oidc:
        access_token_lifespan: 1h
        authorize_code_lifespan: 1m
        id_token_lifespan: 1h
        refresh_token_lifespan: 90m
        enforce_pkce: public_clients_only
        enable_client_debug_messages: false
        cors:
            endpoints:
                - authorization
                - token
                - revocation
                - introspection
            allowed_origins:
                - https://XXXX.YYYY
            allowed_origins_from_client_redirect_uris: false
        clients:
            - id: portainer
              description: Log In to Portainer
              secret: XXXX
              public: false
              authorization_policy: two_factor
              audience: []
              scopes:
                  - openid
                  - profile
                  - groups
                  - email
              redirect_uris:
                  - https://portainer.XXXX.YYYY
              userinfo_signing_algorithm: none

            - id: pitainer
              description: Log In to Pitainer
              secret: XXXX
              authorization_policy: two_factor
              audience: []
              scopes:
                  - openid
                  - profile
                  - groups
                  - email
              redirect_uris:
                  - https://pitainer.XXXX.YYYY
              userinfo_signing_algorithm: none

            - id: nextcloud
              description: Nextcloud
              secret: LE6I2Vp921ayEzKgHjc11gjSRbwgvoUE91IzZARpJnpjL3rwiLn7TRFHwkiSokcf
              public: false
              authorization_policy: two_factor
              audience: []
              scopes:
                  - openid
                  - profile
                  - groups
                  - email
              redirect_uris:
                  - https://cloud.XXXX.YYYY/apps/oidc_login/oidc
                  - https://cloud.XXXX.YYYY/apps/sociallogin/custom_oidc/nextcloud
              grant_types:
                  - refresh_token
                  - authorization_code
              response_types:
                  - code
              userinfo_signing_algorithm: none
```

### Logs (Authelia)

```shell
0m time="2022-12-08T08:00:03-05:00" level=info msg="Authelia v4.37.3 is starting"
0m time="2022-12-08T08:00:03-05:00" level=error msg="Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted" stack="github.com/authelia/authelia/v4/internal/commands/root.go:281 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
0m time="2022-12-08T08:00:03-05:00" level=error msg="Your LDAP Server supports TLS but you don't appear to be utilizing it. We strongly recommend using the scheme 'ldaps://' or enabling the StartTLS option to secure connections with your LDAP Server." stack="github.com/authelia/authelia/v4/internal/commands/root.go:323 doStartupCheck\ngithub.com/authelia/authelia/v4/internal/commands/root.go:286 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
time="2022-12-08T08:00:03-05:00" level=fatal msg="The following providers had fatal failures during startup: storage" stack="github.com/authelia/authelia/v4/internal/commands/root.go:309 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
