### ISSUE TITLE
Incorrect username or password | 401 | AxiosError | ERR_BAD_REQUEST

### ISSUE THREAD

**Issue by DerivativeMarmot** [authelia/authelia#4628]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.23.3

### Description

Failed to login in an amount of time (10h ~ 24h), showing incorrect username or password.
I've been suffering for a week.

### Reproduction

1. Start authelia docker container.
2. Type the correct username and password in login page, successfully logged in.
3. Wait for an amount of time (10h ~ 24h)
4. Type the correct username and password in login page, failed to login due to incorrect username or password.
5. Restart authelia docker container.
6. Type the correct username and password in login page, successfully logged in.
7. Back to step 3

### Expectations

Succesfully logged in.

### Configuration (Authelia)

```yaml
jwt_secret: u6Nn1rDfaVNlMzSDI1p3GCZpXkkylitb
default_redirection_url: https://<my_domain>

server:
  host: 0.0.0.0
  port: 9091

log:
  level: error

totp:
  disable: false
  issuer: <my_domain>
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "login.<my_domain>"
        - "komga.<my_domain>"
        - "kms.<my_domain>"
        - "mail.<my_domain>"
        - "cors-anywhere.<my_domain>"
        - "jellyfin.<my_domain>"
      policy: bypass
    - domain: # Proxies only requiring username and password
        - ""
      policy: one_factor
    - domain: # Proxies needing 2 factor below
        - "<my_domain>"
        - "qb.<my_domain>"
        - "dav.<my_domain>"
        - "ariang.<my_domain>"
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: 7qaBI7BidF28pbpiz38h5nda8DW26Xkv
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: <my_domain> # Needs to be your root domain

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
#    password: authelia

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: dark   # options: dark, light

storage:
  encryption_key: Gfxnf3vWkigYhPZyRqbUmQyT6mOqQnot
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
#  smtp:
#     username: <your-user@your-email-domain.org>
#     password: <your-user-email-password-for-smtp>
#     host: <your-email-host-url-or-ip>
#     port: <your-email-port-for-smtp>  # 25 non-ssl, 443 ssl, 587 tls
#     sender: <sender@your-email-domain.org>
#     subject: "[Authelia] {title}"
#     disable_require_tls: false # set to true if your domain uses no tls or ssl only
#     disable_html_emails: false # set to true if you don't want html in your emails
#    tls:
#      server_name: <your-email-host-url-or-ip>
#      skip_verify: false
#      minimum_version: TLS1.2

ntp:
  address: "time.cloudflare.com:123"
  version: 3
  # max_desync: 24h
  disable_startup_check: true
  disable_failure: true
```

### Logs (Authelia)

```shell
redis     | 1:S 22 Dec 2022 19:03:00.359 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:00.359 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:07.847 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:08.103 * Master replied to PING, replication can continue...
redis     | 1:S 22 Dec 2022 19:03:08.573 * Partial resynchronization not possible (no cached master)
redis     | 1:S 22 Dec 2022 19:03:10.004 * Full resync from master: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ:1
redis     | 1:S 22 Dec 2022 19:03:10.004 * MASTER <-> REPLICA sync: receiving 55664 bytes from master to disk
redis     | 1:S 22 Dec 2022 19:03:11.225 * MASTER <-> REPLICA sync: Flushing old data
redis     | 1:S 22 Dec 2022 19:03:11.225 * MASTER <-> REPLICA sync: Loading DB in memory
redis     | 1:S 22 Dec 2022 19:03:11.226 # Wrong signature trying to load DB from file
redis     | 1:S 22 Dec 2022 19:03:11.226 # Failed trying to load the MASTER synchronization DB from disk: Invalid argument
redis     | 1:S 22 Dec 2022 19:03:11.227 * Reconnecting to MASTER 185.246.90.205:8886 after failure
redis     | 1:S 22 Dec 2022 19:03:11.227 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:11.464 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:12.408 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:13.403 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:13.403 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:13.630 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:13.900 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:14.407 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:14.407 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:14.670 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:15.772 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:16.413 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:16.413 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:16.671 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:16.913 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:17.416 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:17.416 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:17.684 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:19.511 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:20.426 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:20.426 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:20.653 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:20.871 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:21.430 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:21.430 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:21.648 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:21.909 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:22.433 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:22.434 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:23.660 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:23.897 # Error reply to PING from master: '-Reading from master: Connection reset by peer'
redis     | 1:S 22 Dec 2022 19:03:24.440 * Connecting to MASTER 185.246.90.205:8886
redis     | 1:S 22 Dec 2022 19:03:24.440 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:03:27.945 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:03:28.184 * Master replied to PING, replication can continue...
redis     | 1:S 22 Dec 2022 19:04:30.641 # Timeout connecting to the MASTER...
redis     | 1:S 22 Dec 2022 19:04:30.641 * Reconnecting to MASTER 185.246.90.205:8886 after failure
redis     | 1:S 22 Dec 2022 19:04:30.641 * MASTER <-> REPLICA sync started
redis     | 1:S 22 Dec 2022 19:04:30.881 * Non blocking connect for SYNC fired the event.
redis     | 1:S 22 Dec 2022 19:04:31.128 * Master replied to PING, replication can continue...
```

### Logs (Proxy / Application)

```shell
[22/Dec/2022:18:52:02 +0100] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0b6pre) Gecko/20100907 Firefox/4.0b6pre Camino/2.2a1pre"
[22/Dec/2022:18:52:02 +0100] "GET / HTTP/1.1" 400 657 "-" "Mozilla/1.22 (compatible; MSIE 5.01; PalmOS 3.0) EudoraWeb 2.1"
[22/Dec/2022:18:52:03 +0100] "GET / HTTP/1.1" 302 145 "http://<my_domain>:80" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0b6pre) Gecko/20100907 Firefox/4.0b6pre Camino/2.2a1pre"
[22/Dec/2022:18:52:05 +0100] "GET /?rd=https://<my_domain>/ HTTP/1.1" 200 561 "https://<my_domain>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0b6pre) Gecko/20100907 Firefox/4.0b6pre Camino/2.2a1pre"
[22/Dec/2022:18:52:06 +0100] "GET / HTTP/1.1" 404 125 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0b6pre) Gecko/20100907 Firefox/4.0b6pre Camino/2.2a1pre"
[22/Dec/2022:19:02:22 +0100] "GET / HTTP/2.0" 200 544 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:22 +0100] "GET /static/js/index.ab3c4fdc.js HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:22 +0100] "GET /static/css/index.40feef90.css HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:23 +0100] "GET /locales/zh-CN/portal.json HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:23 +0100] "GET /locales/en/portal.json HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:23 +0100] "GET /locales/zh/portal.json HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:23 +0100] "GET /api/state HTTP/2.0" 200 110 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:23 +0100] "GET /manifest.json HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:02:57 +0100] "POST /api/firstfactor HTTP/2.0" 401 74 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:03:00 +0100] "GET /static/css/index.40feef90.css HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:03:00 +0100] "GET /manifest.json HTTP/2.0" 304 0 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:03:34 +0100] "POST /api/firstfactor HTTP/2.0" 401 74 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:04:13 +0100] "POST /api/firstfactor HTTP/2.0" 401 74 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:04:29 +0100] "POST /api/firstfactor HTTP/2.0" 401 74 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
[22/Dec/2022:19:05:56 +0100] "POST /api/firstfactor HTTP/2.0" 401 74 "https://login.<my_domain>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [x] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [x] I have checked for related proxy or application logs and included them if available
- [x] I have checked for related issues and checked the documentation
