### ISSUE TITLE
panic: runtime error: index out of range [3773] with length 3773

### ISSUE THREAD

**Issue by Herbs851** [authelia/authelia#4709]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.18.0

### Description

Hi all,

Since I updated to version 4.37.5, authelia crashes randomly.

I have to restart the systemd service to get it working again.

Authelia is installed on a lxc container (debian 11) next to my reverse proxy (nginx).

No error message in the authelia log, only messages in the syslog.

I found 2 issues here but they don't seem to be exactly the same

https://github.com/authelia/authelia/issues/2349
https://github.com/authelia/authelia/issues/1451

### Reproduction

I can't reproduce the crash

So I don't know how to tell you to do it.

### Configuration (Authelia)

```yaml
server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 4096
    write: 4096
  path: ""

theme: dark

log:
  ## Level of verbosity for logs: info, debug, trace.
  level: debug
  file_path: /var/log/authelia.log

jwt_secret: <my_secret>

default_redirection_url: https://wiki.my.domain

authentication_backend:
  password_reset:
    disable: true

  refresh_interval: 5m

  file:
    path: /etc/authelia/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 64
      parallelism: 8

access_control:
  default_policy: deny

  networks:
    - name: internal
      networks:
        - 10.0.0.0/24
        - 192.168.0.0/24

  rules:

### here are my rules list ###

session:
  name: authelia_session
  domain: my_domain
  same_site: lax
  secret: <my_secret>
  expiration: 1h
  inactivity: 5m
  remember_me_duration: -1

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: <my_key>
  local:
    path: /var/lib/authelia/db.sqlite3

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: discouraged
  timeout: 120s

#notifier:
#  disable_startup_check: false
#  filesystem:
#    filename: /etc/authelia/notifications/notification.txt

notifier:
  disable_startup_check: false
  template_path: /etc/authelia/templates
  smtp:
    host: ssl0.ovh.net
    port: 465
    timeout: 5s
    username: userr
    password: passwd
    sender: <the_sender>
    identifier: identifier
    subject: "[Authelia] {title}"
    startup_check_address: my_address_mail
    disable_require_tls: false
    disable_html_emails: true
    tls:
      server_name: ssl0.ovh.net
      skip_verify: false
      minimum_version: TLS1.2
```

### Logs (Authelia)

```shell
### From Debian Syslog ###

authelia[1542]: panic: runtime error: index out of range [3773] with length 3773
authelia[1542]: goroutine 821 [running]:
authelia[1542]: github.com/savsgio/dictpool.(*Dict).indexOf(0xc00118dc60, {0xc0011e0640, 0x20})
authelia[1542]: #011github.com/savsgio/dictpool@v0.0.0-20220406081701-03de5edb2e6d/dict.go:40 +0x165
authelia[1542]: github.com/savsgio/dictpool.(*Dict).Set(0xc00118dc60, {0xc0011e0640, 0x20}, {0x55d8e0965500?, 0xc00124ecc0})
authelia[1542]: #011github.com/savsgio/dictpool@v0.0.0-20220406081701-03de5edb2e6d/dict.go:86 +0x3e
authelia[1542]: github.com/savsgio/dictpool.(*Dict).SetBytes(...)
authelia[1542]: #011github.com/savsgio/dictpool@v0.0.0-20220406081701-03de5edb2e6d/dict.go:101
authelia[1542]: github.com/fasthttp/session/v2/providers/memory.(*Provider).Save(0xc0005a4160, {0xc0011e0640, 0x20, 0x55d8e0ada740?}, {0xc000f79400, 0x27c, 0x27c}, 0x34630b8a000)
authelia[1542]: #011github.com/fasthttp/session/v2@v2.4.13/providers/memory/provider.go:58 +0x13a
authelia[1542]: github.com/fasthttp/session/v2.(*Session).Save(0xc0003f17a0, 0x55d8dfa8bdcc?, 0xc00104e4c0)
authelia[1542]: #011github.com/fasthttp/session/v2@v2.4.13/session.go:204 +0x117
authelia[1542]: github.com/authelia/authelia/v4/internal/session.(*Provider).SaveSession(0xc001037de8, 0x1c?, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
authelia[1542]: #011github.com/authelia/authelia/v4/internal/session/provider.go:112 +0xf0
authelia[1542]: github.com/authelia/authelia/v4/internal/middlewares.(*AutheliaCtx).SaveSession(...)
authelia[1542]: #011github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:243
authelia[1542]: github.com/authelia/authelia/v4/internal/handlers.updateActivityTimestamp(0xc0000fb600, 0x0?)
authelia[1542]: #011github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:268 +0x138
authelia[1542]: github.com/authelia/authelia/v4/internal/handlers.VerifyGET.func1(0xc0000fb600)
authelia[1542]: #011github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:495 +0x6da
authelia[1542]: github.com/authelia/authelia/v4/internal/middlewares.(*BridgeBuilder).Build.func1.1(0xc000c36330?)
authelia[1542]: #011github.com/authelia/authelia/v4/internal/middlewares/bridge.go:54 +0xe9
authelia[1542]: github.com/authelia/authelia/v4/internal/middlewares.SecurityHeaders.func1(0xc000c36000)
authelia[1542]: #011github.com/authelia/authelia/v4/internal/middlewares/headers.go:16 +0x149
authelia[1542]: github.com/fasthttp/router.(*Router).Handler(0xc000446070, 0xc000c36000)
authelia[1542]: #011github.com/fasthttp/router@v1.4.14/router.go:427 +0x871
authelia[1542]: github.com/authelia/authelia/v4/internal/middlewares.LogRequest.func1(0xc000c36000)
authelia[1542]: #011github.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 +0xb1
authelia[1542]: github.com/valyala/fasthttp.(*Server).serveConn(0xc0000dc6c0, {0x55d8e0bacf10?, 0xc000416008})
authelia[1542]: #011github.com/valyala/fasthttp@v1.43.0/server.go:2338 +0x1268
authelia[1542]: github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000033860, 0xc000477100)
authelia[1542]: #011github.com/valyala/fasthttp@v1.43.0/workerpool.go:224 +0xa9
authelia[1542]: github.com/valyala/fasthttp.(*workerPool).getCh.func1()
authelia[1542]: #011github.com/valyala/fasthttp@v1.43.0/workerpool.go:196 +0x38
authelia[1542]: created by github.com/valyala/fasthttp.(*workerPool).getCh
authelia[1542]: #011github.com/valyala/fasthttp@v1.43.0/workerpool.go:195 +0x1b0
systemd[1]: authelia.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Duplicate of #3751, though looks like a user basically hijacked that issue with another issue and I didn't realize. I'll reopen the issue and close this one.

This is due to an absurd number of requests when not using `redis` I believe, I could not replicate it with 500 million requests but our hardware may differ. Allegedly this is fixed upstream but they made a breaking change to the session lib which we're in the middle of a change freeze on (for a major feature). I'll see how complex it is to implement the change however.

**Comment by james-d-elliott** [comment]
Side node, adjusting the server timeouts may help alleviate this issue, but no one with the original issue confirmed it.

**Comment by Herbs851** [comment]
Thank you for the answer.

I will read the documentation to determine if I can easily install redis.

If so, I'll install it and let you know.

**Comment by Herbs851** [comment]
Can you confirm that this configuration is sufficient ?

```
session:
  name: authelia_session
  domain: my_domain
  same_site: lax
  secret: "my_secret"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: -1
  redis:
    host: /var/run/redis/redis.sock
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
```

I just set up like this, authelia works.

I will tell you in a few days if it has crashed again.
