### ISSUE TITLE
Page auto refresh when login to minio admin console with authelia

### ISSUE THREAD

**Issue by catfishlty** [authelia/authelia#4798]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

https://hub.docker.com/layers/jc21/nginx-proxy-manager/latest/images/sha256-78e8921a7dac14fc8f3ba74f71bb06b91328ae0cf4d9bd1d49d6854c889218e0?context=explore

### Description

1. add protected minio admin console domain `admin-minio.mydomain.com` to authelia configuration.yml->access_control->rules->domain, and add policy `one_factor`
2. setup `Nginx Proxy Manager`, add custom ssl cert and custom nginx conf base on authelia document.

When login to minio admin login page, it show up normally, then type in user/pass and login, the page auto refresh and then goto minio admin login page again. I'm pretty sure the config for minio and authelia is correct. Other domain site can works fine under the config.

## Deployed by docker compose

1. deploy `jc21/nginx-proxy-manager:latest`
```yml
version: '3'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    hostname: npm.internal
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /root/data/npm:/data
      - /root/data/letsencrypt:/etc/letsencrypt
      - /root/data/nginx/snippets:/config/nginx/snippets:ro
    networks:
      local_net:
        aliases:
          - npm.mydomain.com
          - auth.mydomain.com
networks:
  local_net:
    external: true
```
2. deploy `authelia/authelia:latest`
```yml
version: '3'
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    hostname: auth.internal
    ports:
      - 9091:9091
    volumes:
      - /root/data/authelia:/data
      - /root/data/authelia/config:/config
    environment:
      - TZ=Asia/Shanghai
    networks:
      local_net:
        aliases:
          - auth.internal
networks:
  local_net:
    external: true
```
```yml
...
access_control:
  default_policy: deny
  rules:
    - domain: 
        - auth.mydomain.com
        - npm.mydomain.com
      policy: bypass
    - domain:
        - admin-minio.mydomain.com
      policy: bypass
      resources:
        - 'manifest.json'
    - domain: 
        - minio.cloud.catfish.top
        - admin-minio.cloud.catfish.top
      policy: one_factor
...
```

3. deploy `minio/minio:RELEASE.2023-01-18T04-36-38Z`
```yml
version: '3.0'
services:
  minio:
    image: minio/minio:RELEASE.2023-01-18T04-36-38Z
    container_name: minio
    hostname: minio.internal
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address ":9001" --address ":9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: test12345678
    logging:
      options:
        max-size: "2000M"
        max-file: "10"
      driver: json-file
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /root/data/minio:/data
    networks:
      local_net:
        aliases:
          - "minio.internal"
networks:
  local_net:
    external: true
```
4. add proxy settings in Nginx Proxy Manager and authelia settings.
`auth.mydomain.com` -> `http://authelia:9091`
`admin-minio.mydomain.com` -> `http://minio:9001`

5. access to `admin-minio.mydomain.com`, login page show up, type in username/password, then click login button, the page seems login successful, but then it refresh quickly and go to login page again.

### Configuration (Authelia)

```yaml
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: <encrypted>
default_redirection_url: http://auth.mydomain.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

totp:
  disable: false
  issuer: mydomain.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

access_control:
  default_policy: deny
  rules:
    - domain: 
        - auth.mydomain.com
        - npm.mydomain.com
      policy: bypass
    - domain:
        - admin-minio.mydomain.com
      policy: bypass
      resources:
        - 'manifest.json'
    - domain: 
        - admin-minio.mydomain.com
      policy: one_factor

authentication_backend:
  ldap:
    implementation: custom
    url: ldap://ldap.mydomain.com:3890
    timeout: 5s
    start_tls: false
    base_dn: DC=mydomain,DC=com
    additional_users_dn: ou=people
    #users_filter: (|({username_attribute}={input})({mail_attribute}={input}))
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: cn
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: uid=service,ou=people,DC=mydomain,DC=com
    password: 12345678

session:
  name: authelia_session
  secret: <encrypted>
  expiration: 3600  # 1 hour
  inactivity: 600  # 5 minutes
  domain: mydomain.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: <encrypted>
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```

### Logs (Authelia)

```shell
time="2023-01-19T17:31:53+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/login (method POST)."
time="2023-01-19T17:31:56+08:00" level=info msg="Access to https://admin-minio.mydomain.com/manifest.json (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.18.0.1
time="2023-01-19T17:31:56+08:00" level=debug msg="Check authorization of subject username= groups= ip=172.18.0.1 and object https://admin-minio.mydomain.com/manifest.json (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/styles/fonts/Lato/Lato-Bold.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/styles/fonts/Lato/Lato-Regular.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/static/media/videoBG.17363418b3c2246a0e27.mp4 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/static/media/Inter-Bold.ec64ea577b0349e055ad.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/static/media/Inter-Light.2d5198822ab091ce4305.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/static/media/Inter-Black.15ca31c0a2a68f76d2d1.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=info msg="Access to https://admin-minio.mydomain.com/manifest.json (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=172.18.0.1
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username= groups= ip=172.18.0.1 and object https://admin-minio.mydomain.com/manifest.json (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/login (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/check-version (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/static/media/Inter-Regular.c8ba52b05a9ef10f4758.woff2 (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/buckets (method GET)."
time="2023-01-19T17:31:55+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/login (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/admin/site-replication (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/subnet/info (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/session (method GET)."
time="2023-01-19T17:31:54+08:00" level=debug msg="Check authorization of subject username=service groups=lldap_strict_readonly ip=172.18.0.1 and object https://admin-minio.mydomain.com/api/v1/login (method POST)."
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
