### ISSUE TITLE
can't connect to redis instance

### ISSUE THREAD

**Issue by fnayou** [authelia/authelia#4880]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Description

after an update made by `watchtower` the application crashes.
i tried to roll back to ther version but no success
it appear that can't connect to redis instance, even that instance work properly.

i have to precise that everything work properly before the update. no issue with the proxy or anything.

### Reproduction

just try to run the `docker-compose.yml` :

```yaml
version: '3.3'

services:
    authelia:
        image: authelia/authelia:latest
        volumes:
            - ./docker/authelia:/config
        labels:
            traefik.enable: true
            traefik.http.routers.authelia.tls: true
            traefik.http.routers.authelia.tls.certresolver: letsencrypt
            traefik.http.routers.authelia.rule: Host(`authelia.domain.tld`)
            traefik.http.routers.authelia.entrypoints: websecure
        expose:
            - 9091
        restart: unless-stopped
        environment:
            - TZ=Europe/Paris
        networks:
            authelia:
                ipv4_address: 110.0.2.3
    redis:
        image: redis:alpine
        user: "1000:1000"
        volumes:
            - ./docker/data/redis:/data
        expose:
            - 6379
        restart: unless-stopped
        environment:
            - TZ=Europe/Paris
        networks:
            authelia:
                ipv4_address: 110.0.2.4
networks:
     authelia:
         ipam:
             driver: default
             config:
                 - subnet: "110.0.2.0/24"
```

### Expectations

`Authelia` container up normally and work properly

### Configuration (Authelia)

```yaml
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: xxxxxxxx
default_redirection_url: https://yy1.domain.tld

server:
    host: 0.0.0.0
    port: 9091

log:
    level: debug
#  This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE

totp:
    issuer: authelia.domain.tld

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
    file:
        path: /config/users_database.yml

access_control:
    default_policy: deny
    rules:
        # Rules applied to everyone
        - domain: xx1.domain.tld
          policy: bypass
        - domain: xx2.domain.tld
          policy: bypass
        - domain: yy1.domain.tld
          policy: one_factor
        - domain: yy2.domain.tld
          policy: one_factor
        - domain: yy3.domain.tld
          policy: two_factor

session:
    name: authelia_session
    # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
    secret: xxxxxxxx
    expiration: 3600 # 1 hour
    inactivity: 300 # 5 minutes
    domain: aymen.fr # Should match whatever your root protected domain is

    redis:
        host: redis
        port: 6379
        # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
        # password: authelia

regulation:
    max_retries: 3
    find_time: 120
    ban_time: 300

storage:
    encryption_key: xxxxxxxx
    local:
        path: /config/db.sqlite3

notifier:
    smtp:
        [...]
```

### Logs (Authelia)

```shell
authelia_1  | time="2023-02-05T13:07:29+01:00" level=fatal msg="Redis connection error: dial tcp 110.0.2.4:6379: i/o timeout" stack="github.com/authelia/authelia/v4/internal/commands/helpers.go:84 getProviders\ngithub.com/authelia/authelia/v4/internal/commands/root.go:72    cmdRootRun\ngithub.com/spf13/cobra@v1.6.0/command.go:920                    (*Command).execute\ngithub.com/spf13/cobra@v1.6.0/command.go:1040                   (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.0/command.go:968                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10         main\nruntime/proc.go:250                                             main\nruntime/asm_amd64.s:1594                                        goexit"
authelia_1  | time="2023-02-05T13:07:31+01:00" level=info msg="Authelia v4.37.0 is starting"
authelia_1  | time="2023-02-05T13:07:31+01:00" level=info msg="Log severity set to debug"
authelia_1  | time="2023-02-05T13:07:51+01:00" level=fatal msg="Redis connection error: dial tcp 110.0.2.4:6379: i/o timeout" stack="github.com/authelia/authelia/v4/internal/commands/helpers.go:84 getProviders\ngithub.com/authelia/authelia/v4/internal/commands/root.go:72    cmdRootRun\ngithub.com/spf13/cobra@v1.6.0/command.go:920                    (*Command).execute\ngithub.com/spf13/cobra@v1.6.0/command.go:1040                   (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.0/command.go:968                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10         main\nruntime/proc.go:250                                             main\nruntime/asm_amd64.s:1594                                        goexit"
authelia_authelia_1 exited with code 1
```

### Logs (Proxy / Application)

```shell
logs of redis instance :


redis_1     | 1:C 05 Feb 2023 12:44:00.656 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 05 Feb 2023 12:44:00.656 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 05 Feb 2023 12:44:00.656 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1     | 1:M 05 Feb 2023 12:44:00.658 * monotonic clock: POSIX clock_gettime
redis_1     | 1:M 05 Feb 2023 12:44:00.666 * Running mode=standalone, port=6379.
redis_1     | 1:M 05 Feb 2023 12:44:00.666 # Server initialized
redis_1     | 1:M 05 Feb 2023 12:44:00.666 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 05 Feb 2023 12:44:00.672 * Ready to accept connections
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
