### ISSUE TITLE
TOTP rejected, cannot re-register

### ISSUE THREAD

**Issue by instantlinux** [authelia/authelia#4941]
### Version

v4.37.5

### Deployment Method

Kubernetes

### Reverse Proxy

HAProxy

### Reverse Proxy Version

2.7.1

### Description

I'm a longtime authelia user last 3+ years. My latest upgrade was from `4.32.2` to `4.37.5`. (The intervening version 4.33 introduced encryption, which is perhaps where things went wrong with a schema update). 

Auth proceeds through 1FA fine but when it asks for second factor, it claimed TOTP was wrong. Then I invoked
```
authelia storage user totp delete richb
```
and attempted `Register device`. The on-screen message is "There was a problem initiating the registration process" and if I set log level to trace, I see this message:
```
time="2023-02-16T22:27:55Z" level=trace msg="Request hit" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.244.4.1
time="2023-02-16T22:27:55Z" level=trace msg="Replied (status=403)" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.244.4.1
```

### Reproduction

I have an haproxy running under k8s with this config:
```
global
	log 127.0.0.1	local1 notice
	maxconn		4096
	user		haproxy
	group		haproxy
	daemon

defaults
	log		global
	option		dontlognull
	option		dontlog-normal
	retries		3
	option		redispatch
	maxconn		2000
	timeout connect	5000
	timeout	client	50000
	timeout server	50000
listen http
  bind 192.168.2.59:80
  mode tcp
  maxconn 500
  balance roundrobin
  server aconcagua 192.168.2.98:30080 check inter 30000

listen https
  bind 192.168.2.59:443
  mode tcp
  maxconn 500
  balance roundrobin
  server aconcagua 192.168.2.98:30443 check inter 30000
```
I have ingress set up using image `k8s.gcr.io/ingress-nginx/controller:v1.4.0`. My standard set of annotations for each service is:
```
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Values.authelia.ip }}/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.authelia.fqdn }}
    nginx.ingress.kubernetes.io/use-regex: "true"
```
where the IP is 10.101.1.5 and fqdn is authtotp.ci.net.

### Expectations

When I do an upgrade, schema updates and other breaking changes should result in a prompt for any required manual configuration.

### Configuration (Authelia)

```yaml
server:
  port: 80
# set to trace for troubleshooting
log:
  level: trace

authentication_backend:
  ldap:
    url: ldap://ldap
    base_dn: dc=ci,dc=net
    users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
    username_attribute: uid
    additional_users_dn: ou=users
    additional_groups_dn: ou=groups
    display_name_attribute: sn
    groups_filter: (&(member={dn})(objectclass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    user: cn=admin,dc=ci,dc=net

# Access Control
access_control:
  default_policy: bypass
  rules:
  # TODO - deal with
  # level=error msg="Policy [bypass] for rule #1 domain
  # [xxx.ci.net] with subjects [[user:xxx]] is invalid. It
  # is not supported to configure both policy bypass and
  # subjects. For more information see:
  # https://www.authelia.com/docs/configuration/access-control.html#combining-subjects-and-the-bypass-policy"
  # - domain: monitor.ci.net
  #   policy: bypass
  #   subject: user:richb
  - domain:
    - "*.ci.net"
    - "*.instantlinux.net"
    policy: two_factor

# Configuration of session cookies
session:
  expiration: 1.2096e+09
  inactivity: 300000
  domain: ci.net
  redis:
    host: redis
    port: 6379

# Configuration of the authentication regulation mechanism.
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

# The directory where the DB files will be saved
storage:
  mysql:
    host: db00
    port: 3306
    database: authelia
    username: authelia

# Configuration of the notification system.
notifier:
  smtp:
    username: richard.k.braun@gmail.com
    host: smtp.gmail.com
    port: 587
    sender: admin@pioneer.ci.net
```

### Logs (Authelia)

```shell
time="2023-02-16T22:15:53Z" level=info msg="Authelia v4.37.5 is starting"
time="2023-02-16T22:15:53Z" level=info msg="Log severity set to trace"
time="2023-02-16T22:15:54Z" level=trace msg="Starting scan of directory  for certificates"
time="2023-02-16T22:15:54Z" level=trace msg="Finished scan of directory  for certificates"
time="2023-02-16T22:15:54Z" level=trace msg="Dynamically generated users filter is (&(uid={input})(objectClass=inetOrgPerson))"
time="2023-02-16T22:15:54Z" level=trace msg="Dynamically generated users BaseDN is ou=users,dc=ci,dc=net"
time="2023-02-16T22:15:54Z" level=trace msg="Detected user filter replacements that need to be resolved per lookup are: {input}=true"
time="2023-02-16T22:15:54Z" level=trace msg="Dynamically generated groups BaseDN is ou=groups,dc=ci,dc=net"
time="2023-02-16T22:15:54Z" level=trace msg="Detected group filter replacements that need to be resolved per lookup are: input=false, username=false, dn=true"
time="2023-02-16T22:15:54Z" level=info msg="Storage schema is being checked for updates"
time="2023-02-16T22:15:54Z" level=info msg="Storage schema is already up to date"
time="2023-02-16T22:15:54Z" level=debug msg="LDAP Supported OIDs. Control Types: 2.16.840.1.113730.3.4.18, 2.16.840.1.113730.3.4.2, 1.3.6.1.4.1.4203.1.10.1, 1.3.6.1.1.22, 1.2.840.113556.1.4.319, 1.2.826.0.1.3344810.2.3, 1.3.6.1.1.13.2, 1.3.6.1.1.13.1, 1.3.6.1.1.12. Extensions: 1.3.6.1.4.1.4203.1.11.1, 1.3.6.1.4.1.4203.1.11.3, 1.3.6.1.1.8"
time="2023-02-16T22:15:54Z" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:587"
time="2023-02-16T22:15:54Z" level=debug msg="Notifier SMTP client connected successfully"
time="2023-02-16T22:15:54Z" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: smtp.gmail.com), attempting"
time="2023-02-16T22:15:54Z" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2023-02-16T22:15:54Z" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"
time="2023-02-16T22:15:54Z" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2023-02-16T22:15:54Z" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2023-02-16T22:15:55Z" level=info msg="Initializing server for non-TLS connections on '[::]:80' path '/'"
time="2023-02-16T22:16:22Z" level=trace msg="Request hit" method=GET path=/ remote_ip=10.244.4.1
time="2023-02-16T22:16:22Z" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=10.244.4.1
time="2023-02-16T22:16:22Z" level=trace msg="Request hit" method=GET path=/static/js/index.fad9e36b.js remote_ip=10.244.4.1
time="2023-02-16T22:16:22Z" level=trace msg="Request hit" method=GET path=/static/css/index.40feef90.css remote_ip=10.244.4.1
time="2023-02-16T22:16:22Z" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.40feef90.css remote_ip=10.244.4.1
time="2023-02-16T22:16:22Z" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.fad9e36b.js remote_ip=10.244.4.1
time="2023-02-16T22:16:23Z" level=trace msg="Request hit" method=GET path=/locales/en-US/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:23Z" level=trace msg="Replied (status=200)" method=GET path=/locales/en-US/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:23Z" level=trace msg="Request hit" method=GET path=/locales/en/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:23Z" level=trace msg="Replied (status=200)" method=GET path=/locales/en/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:23Z" level=trace msg="Request hit" method=GET path=/manifest.json remote_ip=192.168.2.87
time="2023-02-16T22:16:23Z" level=trace msg="Replied (status=200)" method=GET path=/manifest.json remote_ip=192.168.2.87
time="2023-02-16T22:16:23Z" level=trace msg="Request hit" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:16:23Z" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:16:35Z" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:35Z" level=trace msg="Detected user filter is (&(uid=richb)(objectClass=inetOrgPerson))"
time="2023-02-16T22:16:35Z" level=trace msg="Performing user search" attr="[uid mail sn]" base_dn="ou=users,dc=ci,dc=net" deref=0 filter="(&(uid=richb)(objectClass=inetOrgPerson))" scope=2
time="2023-02-16T22:16:35Z" level=debug msg="Mark 1FA authentication attempt made by user 'richb'" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:35Z" level=debug msg="Successful 1FA authentication attempt made by user 'richb'" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:35Z" level=trace msg="Detected user filter is (&(uid=richb)(objectClass=inetOrgPerson))"
time="2023-02-16T22:16:35Z" level=trace msg="Performing user search" attr="[uid mail sn]" base_dn="ou=users,dc=ci,dc=net" deref=0 filter="(&(uid=richb)(objectClass=inetOrgPerson))" scope=2
time="2023-02-16T22:16:35Z" level=trace msg="Computed groups filter is (&(member=uid=richb,ou=users,dc=ci,dc=net)(objectclass=groupOfNames))"
time="2023-02-16T22:16:35Z" level=trace msg="Performing group search" attr="[cn]" base_dn="ou=groups,dc=ci,dc=net" deref=0 filter="(&(member=uid=richb,ou=users,dc=ci,dc=net)(objectclass=groupOfNames))" scope=2
time="2023-02-16T22:16:35Z" level=trace msg="Profile details for user 'richb' => groups: [], emails [richb@instantlinux.net]" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:35Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 71, avg execution duration: 1000, random delay ms: 31, total delay ms: 1031, actual delay ms: 960" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:36Z" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:36Z" level=trace msg="Request hit" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:16:36Z" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:16:45Z" level=trace msg="Request hit" method=GET path=/ remote_ip=10.244.4.1
time="2023-02-16T22:16:45Z" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=10.244.4.1
time="2023-02-16T22:16:45Z" level=trace msg="Request hit" method=GET path=/static/js/index.fad9e36b.js remote_ip=10.244.4.1
time="2023-02-16T22:16:45Z" level=trace msg="Replied (status=304)" method=GET path=/static/js/index.fad9e36b.js remote_ip=10.244.4.1
time="2023-02-16T22:16:45Z" level=trace msg="Request hit" method=GET path=/static/css/index.40feef90.css remote_ip=10.244.4.1
time="2023-02-16T22:16:45Z" level=trace msg="Replied (status=304)" method=GET path=/static/css/index.40feef90.css remote_ip=10.244.4.1
time="2023-02-16T22:16:47Z" level=trace msg="Request hit" method=GET path=/locales/en-US/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:47Z" level=trace msg="Replied (status=200)" method=GET path=/locales/en-US/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:47Z" level=trace msg="Request hit" method=GET path=/locales/en/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:47Z" level=trace msg="Replied (status=304)" method=GET path=/locales/en/portal.json remote_ip=10.244.4.1
time="2023-02-16T22:16:47Z" level=trace msg="Request hit" method=GET path=/manifest.json remote_ip=192.168.2.87
time="2023-02-16T22:16:47Z" level=trace msg="Replied (status=304)" method=GET path=/manifest.json remote_ip=192.168.2.87
time="2023-02-16T22:16:47Z" level=trace msg="Request hit" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:16:47Z" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:16:54Z" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:54Z" level=trace msg="Detected user filter is (&(uid=richb)(objectClass=inetOrgPerson))"
time="2023-02-16T22:16:54Z" level=trace msg="Performing user search" attr="[uid mail sn]" base_dn="ou=users,dc=ci,dc=net" deref=0 filter="(&(uid=richb)(objectClass=inetOrgPerson))" scope=2
time="2023-02-16T22:16:54Z" level=debug msg="Mark 1FA authentication attempt made by user 'richb'" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:54Z" level=debug msg="Successful 1FA authentication attempt made by user 'richb'" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:54Z" level=trace msg="Detected user filter is (&(uid=richb)(objectClass=inetOrgPerson))"
time="2023-02-16T22:16:54Z" level=trace msg="Performing user search" attr="[uid mail sn]" base_dn="ou=users,dc=ci,dc=net" deref=0 filter="(&(uid=richb)(objectClass=inetOrgPerson))" scope=2
time="2023-02-16T22:16:54Z" level=trace msg="Computed groups filter is (&(member=uid=richb,ou=users,dc=ci,dc=net)(objectclass=groupOfNames))"
time="2023-02-16T22:16:54Z" level=trace msg="Performing group search" attr="[cn]" base_dn="ou=groups,dc=ci,dc=net" deref=0 filter="(&(member=uid=richb,ou=users,dc=ci,dc=net)(objectclass=groupOfNames))" scope=2
time="2023-02-16T22:16:54Z" level=trace msg="Profile details for user 'richb' => groups: [], emails [richb@instantlinux.net]" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:54Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 41, avg execution duration: 907, random delay ms: 67, total delay ms: 974, actual delay ms: 933" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:55Z" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:16:55Z" level=trace msg="Request hit" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:16:55Z" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:18:03Z" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:18:03Z" level=trace msg="Detected user filter is (&(uid=richb)(objectClass=inetOrgPerson))"
time="2023-02-16T22:18:03Z" level=trace msg="Performing user search" attr="[uid mail sn]" base_dn="ou=users,dc=ci,dc=net" deref=0 filter="(&(uid=richb)(objectClass=inetOrgPerson))" scope=2
time="2023-02-16T22:18:04Z" level=debug msg="Mark 1FA authentication attempt made by user 'richb'" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=debug msg="Successful 1FA authentication attempt made by user 'richb'" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Detected user filter is (&(uid=richb)(objectClass=inetOrgPerson))"
time="2023-02-16T22:18:04Z" level=trace msg="Performing user search" attr="[uid mail sn]" base_dn="ou=users,dc=ci,dc=net" deref=0 filter="(&(uid=richb)(objectClass=inetOrgPerson))" scope=2
time="2023-02-16T22:18:04Z" level=trace msg="Computed groups filter is (&(member=uid=richb,ou=users,dc=ci,dc=net)(objectclass=groupOfNames))"
time="2023-02-16T22:18:04Z" level=trace msg="Performing group search" attr="[cn]" base_dn="ou=groups,dc=ci,dc=net" deref=0 filter="(&(member=uid=richb,ou=users,dc=ci,dc=net)(objectclass=groupOfNames))" scope=2
time="2023-02-16T22:18:04Z" level=trace msg="Profile details for user 'richb' => groups: [], emails [richb@instantlinux.net]" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 54, avg execution duration: 811, random delay ms: 35, total delay ms: 846, actual delay ms: 792" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Request hit" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Request hit" method=POST path=/api/user/info remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Request hit" method=GET path=/api/configuration remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Replied (status=200)" method=POST path=/api/user/info remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Available methods are [totp webauthn]" method=GET path=/api/configuration remote_ip=10.244.4.1
time="2023-02-16T22:18:04Z" level=trace msg="Replied (status=200)" method=GET path=/api/configuration remote_ip=10.244.4.1
time="2023-02-16T22:18:17Z" level=trace msg="Request hit" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.244.4.1
time="2023-02-16T22:18:17Z" level=trace msg="Replied (status=403)" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.244.4.1
time="2023-02-16T22:19:29Z" level=trace msg="Request hit" method=GET path=/static/css/index.40feef90.css remote_ip=10.244.4.1
time="2023-02-16T22:19:29Z" level=trace msg="Replied (status=304)" method=GET path=/static/css/index.40feef90.css remote_ip=10.244.4.1
time="2023-02-16T22:19:29Z" level=trace msg="Request hit" method=GET path=/manifest.json remote_ip=192.168.2.87
time="2023-02-16T22:19:29Z" level=trace msg="Replied (status=304)" method=GET path=/manifest.json remote_ip=192.168.2.87
time="2023-02-16T22:19:37Z" level=trace msg="Request hit" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.244.4.1
time="2023-02-16T22:19:37Z" level=trace msg="Replied (status=403)" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.244.4.1
```

### Logs (Proxy / Application)

```shell
# From nginx-ingress
10.244.4.1 - - [16/Feb/2023:22:27:55 +0000] "POST /api/secondfactor/totp/identity/start HTTP/2.0" 403 13 "https://authtotp.ci.net/2fa/one-time-password" "Mozilla/5.0 (X11; 
Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 452 0.001 [instantlinux-authelia-80] [] 10.244.2.96:80 13 0.004 403 2fd06145ec5239a3a2f
f8153ef524e04
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
