### ISSUE TITLE
Authelia app keeps redirecting to Authelia login page after successfully authentication

### ISSUE THREAD

**Issue by shailendra4dev** [authelia/authelia#4975]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Description

I deployed Authelia using Docker and tried to authenticate the user and it keeps on redirecting to itself (login page).

Steps:
1. Client app redirects to Authelia for authentication.
2. After successful authentication Authelia should redirect back to the Client app but it loads the login page again.

The client app is also running in another container and accessible via public IP like Authelia.

### Reproduction

Deploy Client app (node js app) also in the container and should be able to reproduce.

const express = require('express');
const session = require('express-session');
const cookieParser = require('cookie-parser');
const helmet = require('helmet');
const passport = require('passport');
const https = require("https");
const fs = require("fs");

const { Issuer,Strategy } = require('openid-client');
const path = require("path");
const app = express();

app.use(cookieParser());
app.use(express.urlencoded({
  extended: true,
}));
app.use(express.json({ limit: '15mb' }));
app.use(session({secret: 'secret', 
                 resave: false, 
                 saveUninitialized: true,}));
app.use(helmet());
app.use(passport.initialize());
app.use(passport.session());

passport.serializeUser(function(user, done) {
    console.log('-----------------------------');
    console.log('serialize user');
    console.log(user);
    console.log('-----------------------------');
    done(null, user);
});
passport.deserializeUser(function(user, done) {
    console.log('-----------------------------');
    console.log('deserialize user');
    console.log(user);
    console.log('-----------------------------');
    done(null, user);
});

Issuer.discover('http://<public-ip-of-authelia-app>:9091/.well-known/openid-configuration')
  .then(function (oidcIssuer) {
    var client = new oidcIssuer.Client({
      client_id: 'MyApp',
      client_secret: 'my$3cret',
      redirect_uris: ["https://<public-ip-of-client-app>:3000/login/callback"],
      scope: 'openid',
      response_types: ['code'],
      response_mode:'form_post'
    });

    passport.use(
      'oidc',
      new Strategy({ client,passReqToCallback: true}, (req, tokenSet, userinfo, done) => {
        console.log("tokenSet",tokenSet);
        console.log("userinfo",userinfo);
        req.session.tokenSet = tokenSet;
        req.session.userinfo = userinfo;
        return done(null, tokenSet.claims());
      }
      
      )
    );
  });

app.get('/login',
function (req, res, next) {
    console.log('-----------------------------');
    console.log('/Start login handler');
    next();
},
passport.authenticate('oidc',{scope:"openid"}));

app.get('/login/callback',(req,res,next) =>{
  console.log('-----------------------------');
  console.log('/login/callback');
  passport.authenticate('oidc',{ successRedirect: '/user',
  failureRedirect: '/' })(req, res, next)
}
  
)

app.get("/",(req,res) =>{
   res.send(" <a href='/login'>Authelia Server </a>")
})
app.get ("/user",(req,res) =>{
    res.header("Content-Type",'application/json');
    res.end(JSON.stringify({tokenset:req.session.tokenSet,userinfo:req.session.userinfo},null,2));
})

const options = {
  key: fs.readFileSync("server.key"),
  cert: fs.readFileSync("server.cert"),
};

https.createServer(options, app)
.listen(3000, function (req, res) {
  console.log("Server started at port 3000");
});

### Expectations

Authelia should redirects to client app after successfull authentication.

### Configuration (Authelia)

```yaml
server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
jwt_secret: RcmxfUOBEPme0bkAkRtyrLo1szLM8zaQz8KkqvP7UmUg4rlAOzf4AKZ7xePeMRAT
default_redirection_url: https://<public-ip-of-client-app>:3000
 
authentication_backend:
  file:
    path: /config/users_database.yml
 
access_control:
  default_policy: deny
  rules:
    - domain:
        - "https://<public-ip-of-client-app>:3000"
      policy: one_factor
 
session:
  name: authelia_session
  secret: RcmxfUOBEPme0bkAkRtyrLo1szLM8zaQz8KkqvP7UmUg4rlAOzf4AKZ7xePeMMAT
  expiration: 12h           # 12 hours
  inactivity: 5m           # 45 minutes
  remember_me_duration: 1M  # 1 month
  domain: https://<public-ip-of-client-app>:3000
 
  redis:
    host: redis_authelia
    port: 6379
 
regulation:
  max_retries: 3
  find_time: 5m
  ban_time: 15m
 
storage:
  encryption_key: RcmxfUOBEPme0bkAkRtyrLo1szLM8zaQz8KkqvP7UmUg4rlAOzf4AKZ7xePeMBAT
  local:
    path: /config/db.sqlite3
 
notifier:
  disable_startup_check: true
  smtp:
    username: test@gmail.com
    password: <gmail_password>
    host: smtp.gmail.com
    port: 587
    sender: test@gmail.com

identity_providers:
  oidc:
    hmac_secret: RcmxfUOBEPme0bkAkRtyrLo1szLM8zaQz8KkqvP7UmUg4rlAOzf4AKZ7xePeMBAA
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
				KEY
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - "*"
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: MyApp
        description: MyApp Application
        secret: 'my$3cret'
        sector_identifier: ''
        public: false
        authorization_policy: one_factor
        consent_mode: explicit
        pre_configured_consent_duration: 1w
        audience: []        
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://<public-ip-of-client-app>:3000/login/callback
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```

### Logs (Authelia)

```shell
time="2023-02-21T14:09:25+05:30" level=info msg="Authelia v4.37.5 is starting"
time="2023-02-21T14:09:25+05:30" level=info msg="Log severity set to debug"
time="2023-02-21T14:09:26+05:30" level=debug msg="Registering client MyApp with policy one_factor (one_factor)"
time="2023-02-21T14:09:26+05:30" level=info msg="Storage schema is being checked for updates"
time="2023-02-21T14:09:26+05:30" level=info msg="Storage schema is already up to date"
time="2023-02-21T14:09:26+05:30" level=debug msg="notification provider: startup check skipped as it is disabled"
time="2023-02-21T14:09:26+05:30" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
time="2023-02-21T14:09:26+05:30" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2023-02-21T14:09:37+05:30" level=debug msg="Authorization Request with id 'ca0968bc-f70e-4fe7-aee4-05b388a0a5f7' on client with id 'MyApp' is being processed" method=GET path=/api/oidc/authorization remote_ip=103.251.211.12
time="2023-02-21T14:09:42+05:30" level=debug msg="Mark 1FA authentication attempt made by user 'shailendra'" method=POST path=/api/firstfactor remote_ip=103.251.211.12
time="2023-02-21T14:09:43+05:30" level=debug msg="Successful 1FA authentication attempt made by user 'shailendra'" method=POST path=/api/firstfactor remote_ip=103.251.211.12
time="2023-02-21T14:09:44+05:30" level=debug msg="Authorization Request with id '96d04be1-a0ac-4579-99c5-5c622c2b9e3c' on client with id 'MyApp' is being processed" method=GET path=/api/oidc/authorization remote_ip=103.251.211.12
time="2023-02-21T14:10:04+05:30" level=debug msg="Authorization Request with id '36afae9a-9a3b-476d-9bd1-d10bdcbab689' on client with id 'MyApp' is being processed" method=GET path=/api/oidc/authorization remote_ip=103.251.211.12
time="2023-02-21T14:10:08+05:30" level=debug msg="Mark 1FA authentication attempt made by user 'shailendra'" method=POST path=/api/firstfactor remote_ip=103.251.211.12
time="2023-02-21T14:10:08+05:30" level=debug msg="Successful 1FA authentication attempt made by user 'shailendra'" method=POST path=/api/firstfactor remote_ip=103.251.211.12
time="2023-02-21T14:10:09+05:30" level=debug msg="Authorization Request with id 'cfd59e4c-8ca2-4ac0-9fe5-5d4dd4bb44ed' on client with id 'MyApp' is being processed" method=GET path=/api/oidc/authorization remote_ip=103.251.211.12
time="2023-02-21T14:10:31+05:30" level=debug msg="Mark 1FA authentication attempt made by user 'shailendra'" method=POST path=/api/firstfactor remote_ip=103.251.211.12
time="2023-02-21T14:10:31+05:30" level=debug msg="Successful 1FA authentication attempt made by user 'shailendra'" method=POST path=/api/firstfactor remote_ip=103.251.211.12
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Your session config is invalid.

**Comment by xrehpicx** [comment]
im getting this with nextcloud as a client 

```
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: "<secret>"
default_redirection_url: https://door.exampledomain.tech/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: door.exampledomain.tech
  period: 30
  skew: 1

identity_providers:
  oidc:
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - "*"
      allowed_origins_from_client_redirect_uris: false
    hmac_secret: "<your_hmac_secret>"
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      <your_private_key_here>
      -----END RSA PRIVATE KEY-----
    clients:
      - id: nextcloud
        description: NextCloud
        secret: "<your_nextcloud_secret>"
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://cloud.exampledomain.tech/apps/oidc_login/oidc
          - https://cloud.exampledomain.tech/index.php/apps/oidc_login/oidc
        scopes:
          - openid
          - profile
          - email
          - groups

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldap://ldap001
    timeout: 5s
    start_tls: false
    tls:
      server_name: exampledomain.tech
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: DC=exampledomain,DC=tech
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: CN=admin,DC=exampledomain,DC=tech
    password: "<your_ldap_password>"

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain:
        - "auth.domain.com"
      policy: bypass
    ## catch-all
    - domain:
        - "*.domain.com"
      subject:
        - "group:admins"
      policy: one_factor

session:
  name: authelia_session
  domain: exampledomain.tech
  same_site: lax
  secret: "$#vR9@3X6A7wP5DqY8Zb0"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M
  redis:
    host: redis
    port: 6379
    password: "ciaadmin"
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: "$#vR9@3X6A7wP5DqY8Zb0"
  mysql:
    host: mariadb
    port: 3306
    database: authelia
    username: authelia
    password: "ciaadmin"

notifier:
  disable_startup_check: false
  smtp:
    username: <your_email_username>
    password: "<your_email_password>"
    host: smtp.gmail.com
    port: 465
    sender: "Ark Authentication <ark@exampledomain.tech>"
    subject: "{title}"
    startup_check_address: ark@exampledomain.tech
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2

```

after successfull auth its just stuck at loading and checking logs im getting same as the above issue where it says its authorizing with nextcloud but just does not move forward
