### ISSUE TITLE
Webauthn doesn't work anymore.

### ISSUE THREAD

**Issue by Herbs851** [authelia/authelia#4984]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.18.0

### Description

I don't know how long or which version, but webauthn doesn't work anymore.

### Reproduction

Try to login with two_factor rules and yubikey 5 NFC usb-a.

I specify that it work with one_facto rules.

Then i get this : 

![image](https://user-images.githubusercontent.com/51154851/220996306-afa7d3ab-2272-472f-b510-b2b5304c5199.png)

And from the brave console (the same with firefox, edge) : 

![image](https://user-images.githubusercontent.com/51154851/220996247-3fbbfbf1-693e-409d-b8d1-969dbd8f403f.png)

### Configuration (Authelia)

```yaml
server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 4096
    write: 4096
  path: ""

theme: dark

log:
  ## Level of verbosity for logs: info, debug, trace.
  level: debug
  file_path: /var/log/authelia.log

jwt_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

default_redirection_url: xxxxxxxxxxxxxxxxxxxxxxxxx

authentication_backend:
  password_reset:
    disable: true

  refresh_interval: 5m

  file:
    path: /etc/authelia/users.yml
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

access_control:
  default_policy: deny

  networks:
    - name: internal
      networks:
        - xx.xx.xx.xx/24
        - xx.xx.xx.xx/24

  rules:

    - domain: xxxxxxxxxxxxxxxxxxx
      policy: two_factor
      subject:
      - ['user:admin']

session:
  name: authelia_session
  domain: xxxxxxxxxxx
  same_site: lax
  secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: -1

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  local:
    path: /var/lib/authelia/db.sqlite3

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s
```

### Logs (Authelia)

```shell
time="2023-02-23T19:07:48+01:00" level=debug msg="Check authorization of subject username= groups= ip=xxx.xxx.x.xx and object https://xxxx.xxxxxx.fr/ (method GET)."
time="2023-02-23T19:07:48+01:00" level=info msg="Access to https://xxxx.xxxxxx.fr/ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=xxx.xxx.x.xx
time="2023-02-23T19:08:02+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'admin'" method=POST path=/api/firstfactor remote_ip=xxx.xxx.x.xx
time="2023-02-23T19:08:02+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'admin'" method=POST path=/api/firstfactor remote_ip=xxx.xxx.x.xx
time="2023-02-23T19:08:02+01:00" level=debug msg="Check authorization of subject username=admin groups=admins ip=xxx.xxx.x.xx and object https://xxxx.xxxxxx.fr/ (method )."
time="2023-02-23T19:08:02+01:00" level=debug msg="Required level for the URL https://xxxx.xxxxxx.fr/ is 2" method=POST path=/api/firstfactor remote_ip=xxx.xxx.x.xx
time="2023-02-23T19:08:02+01:00" level=warning msg="https://xxxx.xxxxxx.fr/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=xxx.xxx.x.xx
```

### Logs (Proxy / Application)

```shell
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F HTTP/2.0" 200 537 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /static/js/index.a382c1d5.js HTTP/2.0" 304 0 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /static/css/index.40feef90.css HTTP/2.0" 200 2818 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /locales/en/portal.json HTTP/2.0" 200 1257 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /locales/fr-FR/portal.json HTTP/2.0" 200 2036 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /locales/fr/portal.json HTTP/2.0" 200 2036 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /api/state HTTP/2.0" 200 121 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /favicon.ico HTTP/2.0" 304 0 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "POST /api/user/info HTTP/2.0" 200 120 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /manifest.json HTTP/2.0" 200 211 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /api/configuration HTTP/2.0" 200 64 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
xxxx.xxxxxx.fr:443 xxx.xxx.x.xx - - [23/Feb/2023:19:16:03 +0100] TLSv1.3 "GET /api/secondfactor/webauthn/assertion HTTP/2.0" 200 296 "https://xxxx.xxxxxx.fr/2fa/webauthn?rd=https%3A%2F%2Fxxxx.xxxxxx.fr%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" "-"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
