### ISSUE TITLE
After upgrading to 4.37, when application redirects to authelia it gives 401

### ISSUE THREAD

**Issue by niwla23** [authelia/authelia#4988]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.8.5

### Description

I upgraded authelia from 4.36 to 4.37.5

I can go to the authelia portal directly and login there, once I have done this I am logged in to other apps as well.

When I am not logged in and go to an app, it just shows 401 Unauthorized. 

These are the logs produced when I go to any app I am not logged in to:

### Reproduction

1. Run authelia with traefik
2. Make sure you are not logged in
3. Go to an app
4. You should see a 401 error

### Expectations

It should redirect to the portal to login

### Configuration (Authelia)

```yaml
jwt_secret: a_very_important_secret
default_redirection_url: https://smartdashboard.sweet
theme: dark

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 3
      key_length: 32
      salt_length: 16
      parallelism: 4
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: public.example.com
      policy: bypass

      # fbtickets administrator
    - domain: fbtickets.b49.cloudserver.click
      policy: one_factor
      resources:
        - "^/admin.*"

    # other paths of fbtickets are public
    - domain: fbtickets.b49.cloudserver.click
      policy: bypass

    - domain: pihole.b49.cloudserver.click
      policy: one_factor

    - domain: traefik.b49.cloudserver.click
      policy: one_factor

    - domain: rezepte.b49.cloudserver.click
      policy: one_factor

    - domain: finanzen.b49.cloudserver.click
      policy: one_factor

    - domain: photos.b49.cloudserver.click
      policy: one_factor
      subject:
        - "group:photos"

    - domain: octoprint.b49.cloudserver.click
      policy: one_factor
      subject:
        - "group:3dprinter"

identity_providers:
  oidc:
    hmac_secret: {{ authelia_hmac_secret }}
    clients:
      - id: grafana
        secret: {{ grafana_client_secret }}
        public: false
        authorization_policy: one_factor
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://monitoring.b49.cloudserver.click/login/generic_oauth
        userinfo_signing_algorithm: none

      - id: portainer
        secret: {{ portainer_client_secret }}
        public: false
        authorization_policy: one_factor
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://portainer.b49.cloudserver.click/
        userinfo_signing_algorithm: none


session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: b49.cloudserver.click # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: secret
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
```

### Logs (Authelia)

```shell
time="2023-02-25T14:11:21Z" level=debug msg="Check authorization of subject username= groups= ip=192.168.178.78 and object https://photos.b49.cloudserver.click/browse (method GET)."
time="2023-02-25T14:11:21Z" level=error msg="Configured Portal URL 'http://auth.b49.cloudserver.click' does not appear to be able to write cookies for the 'b49.cloudserver.click' domain" method=GET path=/api/verify remote_ip=192.168.178.78 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:215 handleUnauthorized\ngithub.com/authelia/authelia/v4/internal/handlers/handler_verify.go:490 VerifyGET.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54       (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16      SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:427                        (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                         (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                      (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                   (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                   (*workerPool).getCh.func1\nruntime/asm_arm64.s:1172                                                goexit"
```

### Logs (Proxy / Application)

```shell
192.168.178.78 - - [25/Feb/2023:14:18:14 +0000] "GET /browse HTTP/2.0" 401 16 "-" "-" 15546 "photoprism@docker" "-" 2ms
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
