### ISSUE TITLE
SMTP auth failure when using Docker secrets

### ISSUE THREAD

**Issue by domisjustanumber** [authelia/authelia#5114]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.9.9

### Description

It looks like something may have broken with the way SMTP password secrets are loaded between v4.37.4 and v4.37.5

I am using an SMTP password specified in a Docker secret, then loaded into AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE environment variable

I've been able to confirm:
- The secret file is getting mounted in the container, and has the correct password in it
- `env` from inside the container is showing the correct env name, and points to the correct secret file location (AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/mailgun_smtp_password)

When launching v4.37.5 I get an error in the log saying SMTP AUTH failed on startup (see log snippet), which blocks the rest of the startup process.

Rolling back to v4.37.4 without making any other changes works without errors.

### Reproduction

Relevant section of my compose file:

 authelia:
    container_name: authelia
    # image: authelia/authelia:latest
    image: authelia/authelia:latest
    restart: always
    depends_on:
      - traefik
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/authelia:/config
    environment:
      TZ: $TZ
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia_session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE:  /run/secrets/mailgun_smtp_password
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_encryption_key
      - mailgun_smtp_password
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=HostHeader(`authelia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"

### Configuration (Authelia)

```yaml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# I used this site to generate the secret: https://www.grc.com/passwords.htm

default_redirection_url: https://authelia.example.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: error

totp:
  issuer: authelia.com
  period: 30
  skew: 1

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 3
      salt_length: 16
      parallelism: 4
      key_length: 32
      memory: 65536 # blocks this much of the RAM. Tune this.

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.example.com
      policy: bypass
#    - domain: radarr.example.com
#      policy: bypass
#      subject: "group:admins"
#      resources:
#      - "^/api/.*$"      
    - domain: "frigate.example.com"
      policy: one_factor
    - domain: "*.example.com"
      policy: two_factor
    - domain: "example.com"
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: unsecure_session_secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  # encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: <sender demail>.mailgun.org
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: smtp.mailgun.org
    port: 587 #465
    sender: authelia@example.com
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
  # filesystem:
   #  filename: /tmp/authelia/notification.txt
...
```

### Logs (Authelia)

```shell
2023-03-22T11:35:06.592104812-04:00 time="2023-03-22T11:35:06-04:00" level=info msg="Authelia v4.37.5 is starting"
2023-03-22T11:35:07.075718284-04:00 time="2023-03-22T11:35:07-04:00" level=error msg="Failure running the notification provider startup check: error performing AUTH with the SMTP server: 535 Authentication failed" stack="github.com/authelia/authelia/v4                                                                 /internal/commands/root.go:293 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                                                                                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\                                                                 nruntime/asm_amd64.s:1594                                      goexit"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation
