### ISSUE TITLE
V4: redirect after sucessful auth not working

### ISSUE THREAD

**Issue by mamema** [authelia/authelia#520]
Hi,

coming from V3, where the topic in question has worked flawlessly, i have this now on V4

- can login at the authelia login screen
- get push via duo solution
- get authenticated
- get the green checkmark about success

...but stays there
what i can do is, to rerenter the destination url which should be redirected to in the first place. Then i can access the page.

But i want the automatic redirection after auth coming back....

**Comment by nightah** [comment]
@mamema can you provide your nginx/treafik config please?

**Comment by mamema** [comment]
Sure!
first: the login (authelia frontend)
_____
server {
    listen 80;
    server_name somesubdomain.whatever.com;

    location / {
        include /etc/nginx/sites-enabled/header;
        return 301 https://$server_name$request_uri;
    }


		# Include this if you want to get a letsencrypt certificate for the domain you're using
		location ^~ /.well-known/acme-challenge/ {
			auth_basic off;
			root /var/lib/letsencrypt;
			default_type "text/plain";
		}

}

server {
    listen 443 ssl http2;
    server_name somesubdomain.whatever.com;

    access_log /var/log/nginx/somesubdomain.whatever.com/access.log;
    error_log /var/log/nginx/somesubdomain.whatever.com/error.log;


ssl_certificate /usr/syno/etc/certificate/_archive/aSCmK1/fullchain.pem;
ssl_certificate_key /usr/syno/etc/certificate/_archive/aSCmK1/privkey.pem;



# Authelia's API for requests coming from external Nginx servers

    location = /api/verify {
        include /etc/nginx/sites-enabled/header;

        # Set original requested Host from X-Forwared-Host.
        # Of course, the external Nginx server protecting his resources
        # must have properly set this header, as configured in this how-to.
        proxy_set_header Host $http_x_forwarded_host;
        proxy_pass http://192.168.0.30:9091;
    }

    # Authelia's frontend

    location /secondfactor/totp/identity/finish {
        # We don't want the user web browser to cache
        # TOTP secrets / QR codes, for security purposes.
        add_header Cache-Control "no-store";
        add_header Pragma "no-cache";
        include /etc/nginx/sites-enabled/header;
        include /etc/nginx/sites-enabled/proxy_params;
        # Pass to Authelia's backend
        proxy_pass http://192.168.0.30:9091;
        proxy_intercept_errors on;
        if ($request_method !~ ^(POST)$){
            error_page 401 = /error/401;
            error_page 403 = /error/403;
            error_page 404 = /error/404;
        }
    }

    location / {
        include /etc/nginx/sites-enabled/header;
        include /etc/nginx/sites-enabled/proxy_params;
        # Pass to Authelia's backend
        proxy_pass http://192.168.0.30:9091;
        proxy_intercept_errors on;
        if ($request_method !~ ^(POST)$){
            error_page 401 = /error/401;
            error_page 403 = /error/403;
            error_page 404 = /error/404;
        }
    }
}
_____

Second: the header config
_____
#####################################
#  filename /etc/nginx/header.conf  #
#####################################

add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
add_header X-Robots-Tag none;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "same-origin" always;
fastcgi_hide_header X-Powered-By;
add_header Expect-CT 'enforce; max-age=3600';
add_header Feature-Policy "geolocation none;midi none;notifications none;push none;sync-xhr none;microphone none;camera none;magnetometer none;gyroscope none;speaker self;vibrate none;fullscreen self;payment none;";
add_header X-Frame-Options "SAMEORIGIN" always; 
____

Third: included proxy params
_____

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_cache_bypass $http_upgrade;

_____
Forth: the actual chosen web site
_____
server {
	listen 80;
#	ssl on;
	server_name destination.whatever.com; #change this
	#root /var/www; #change this


#access_log /var/log/nginx/nas_access.log;
        error_page 401 403 404 /404.html;
		
		 location = /robots.txt {
			         allow all;
					         log_not_found off;
							         access_log off;
									     }
		
		# Include this if you want to get a letsencrypt certificate for the domain you're using
		location ^~ /.well-known/acme-challenge/ {
			auth_basic off;
			root /var/lib/letsencrypt;
			default_type "text/plain";
		}
	 
		# Include this if you want to automatically redirect to HTTPS
		location / {
			return 301 https://$server_name$request_uri;
		}
	 }


server {
	listen 443 ssl;
#	ssl on;
	server_name destination.whatever.com; #change this
	#root /var/www; #change this


ssl_certificate /etc/nginx/cert/l9jSLy/fullchain.pem;
	ssl_certificate_key /etc/nginx/cert/l9jSLy/privkey.pem;

		
		location / {

		proxy_set_header        Host                $http_host;
		proxy_set_header        X-Real-IP           $remote_addr;
		proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
		proxy_set_header        X-Forwarded-Proto   $scheme;
		proxy_intercept_errors  on;
		proxy_http_version      1.1;

		proxy_pass https://192.168.0.30:18889/;

		proxy_redirect default;

								                    }
					                   }

**Comment by nightah** [comment]
@mamema I can't seem to see the auth_request section on your protected website.

Can I suggest you have a look at https://github.com/authelia/authelia/issues/466#issuecomment-559943747

There's example nginx configurations in that post which are working, give that a go and let me know if you have issues.

**Comment by mamema** [comment]
@nightah 
Sorry i'm lost. My nginx config worked with V3 and it was a lot of work because of an nginx behind nginx situation. The only difference now is, that a V4 authelia container is running.
Can you help me to point me there, where the redirection should happening?
I'm sure that your config is working on your side, as my config did, up to the change to V4.

**Comment by nightah** [comment]
@mamema I'm glad that helped you sort out the issue, the hash router was indeed part of the v3 solution and isn't required in v4. The nginx proxy doc hasn't been updated to reflect this, however, it was called out in the BREAKING.md.

**Comment by bgalvao** [comment]
Hey, I am having the same issue with Authelia 4. I am using Authelia with Traefik, and am using the official Authelia example compose file with the domains set to `localhost` - Docker Compose file and Authelia's config are in this gist.

I go to `nextcloud.localhost`, get redirected to the login page, put my credentials in, get logged in... but not redirected to nextcloud after login. The logs (`docker logs authelia`) give me this message.

```
authelia   | time="2022-01-02T22:43:59+11:00" level=info msg="Access to https://nextcloud.localhost/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://login.localhost/?rd=https%3A%2F%2Fnextcloud.localhost%2F&rm=GET" method=GET path=/api/verify remote_ip=172.21.0.1
```

So, it seems to me that my credentials are not passed on, and still remain `<anonymous>` after login... What can I do?

**Comment by nightah** [comment]
This is because you're using the domain localhost.

Per the [cookie spec](https://curl.se/rfc/cookie_spec.html):

> Only hosts within the specified domain can set a cookie for a domain and domains must have at least two (2) or three (3) periods in them to prevent domains of the form: ".com", ".edu", and "va.us". **Any domain that fails within one of the seven special top level domains listed below only require two periods**. Any other domain requires at least three. The seven special top level domains are: "COM", "EDU", "NET", "ORG", "GOV", "MIL", and "INT".

Use a different domain name like `example.com`.

**Comment by bgalvao** [comment]
Well 😮‍💨 I tried using `example.com`, among other things.

<details>
<summary>.env</summary>

```
COMPOSE_PROJECT_NAME=mlops
DOMAIN=example.co
TIMEZONE=Europe/Lisbon
```
</details>

<details>
  <summary>docker-compose.yml</summary>
  
  ```yaml
version: '3'

networks:
  net:
    driver: bridge

services:

  traefik:
    image: traefik:v2.2
    depends_on:
      - authelia
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=$${COMPOSE_PROJECT_NAME}_net'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--log=true'
      - '--log.level=INFO'
      - '--log.filepath=/var/log/traefik.log'

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./config/authelia:/config
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.${DOMAIN}`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      # two authelia's middlewares are defined down below
      # authelia and authelia-basic
      # however, they could be defined in the labels of the traefik service
      # for instance
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN}/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    # restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/secrets/storage_encryption
      - AUTHELIA_JWT_SECRET_FILE=/config/secrets/jwt


  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    volumes:
      - /path/to/nextcloud/config:/config
      - /path/to/nextcloud/data:/data
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)'
      - 'traefik.http.routers.nextcloud.entrypoints=https'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.middlewares=authelia@docker'
    expose:
      - 443
    # restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /path/to/heimdall/config:/config
    networks:
      - net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.heimdall.rule=Host(`heimdall.${DOMAIN}`)'
      - 'traefik.http.routers.heimdall.entrypoints=https'
      - 'traefik.http.routers.heimdall.tls=true'
      - 'traefik.http.routers.heimdall.middlewares=authelia-basic@docker'
    expose:
      - 443
    # restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
  ```
</details>




<details>
  <summary>/etc/hosts</summary>
  
  ```
# Host addresses
127.0.0.1  localhost
127.0.0.1  docker.localdev traefik.docker.localdev heimdall.docker.localdev nextcloud.docker.localdev login.docker.localdev
127.0.0.1  example.com traefik.example.com heimdall.example.com nextcloud.example.com login.example.com
::1        localhost ip6-localhost ip6-loopback
ff02::1    ip6-allnodes
ff02::2    ip6-allrouters
```
</details>

<details>
  <summary>authelia-configuration.yml</summary>
  
  ```yaml
theme: grey
default_redirection_url: https://heimdall.example.com

# cookie management - (can and should be replaced by redis eventually)
# non-trivial when setting up your domain, if there is a mismatch you'll get a msg like
# msg="Target URL [Traefik router rule] is not under the protected domain [session.domain]"
session:
  name: authelia_session
  domain: example.com
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

# ----------------------------------------------------- container specification
# https://www.authelia.com/docs/configuration/server.html
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

# --------------------------------------------------- application specification
# spec subdomains (and/or resources, methods, etc)
# that are accessible under authentication
access_control:
  default_policy: one_factor
  # rules:
  #   - domain: traefik.docker.localdev
  #     policy: one_factor
  #     subject:
  #     - ['group:admin']
  #   - domain: portainer.docker.localdev
  #     policy: one_factor
  #     subject:
  #     - ['group:admin']
  #   - domain: heimdall.docker.localdev
  #     policy: one_factor
  #   - domain: nextcloud.docker.localdev
  #     policy: one_factor
  #   - domain: jupyter.docker.localdev  # suggestive, jupyter only accessible
  #     policy: bypass               # by vpn
  #     networks:
  #     - 192.168.0.0/24

# user database
authentication_backend:
  disable_reset_password: true
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

# ----------------------------------------------------- other authelia backends
log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: true

# `storage` handles user preferences, 2FA device handles and secrets,
# authentication logs, etc
storage:
  local:
    path: /config/db.sqlite3

# `notifier` send confirmation emails to users
notifier:
  filesystem:  # only for testing purposes
    filename: /config/notification.txt
  # smtp:
  #   username: test
  #   host: 'smtp'
  #   port: 1025
  #   sender: auth@mlops.mricons.eu
  ```
</details>

---
#### Outcome

<details>
  <summary>Nextcloud is still not accessible and is now telling me that there are too many redirects.
</summary>

![image](https://user-images.githubusercontent.com/17158288/147942036-489ce71c-d298-48b0-8410-8a543553cb00.png)

</details>

But everything else is working.
