### ISSUE TITLE
Allow secure redirectURI to be a safeTargetURL

### ISSUE THREAD

**Issue by lltr** [authelia/authelia#5368]
### Description

Currently `https://auth.example.com/logout?rd=https://example2.com` will not redirect to https://example2.com, even if https://example2.com is configured to be a redirectURI in Authelia, as https://example2.com is not a `safeTargetURL`.

### Use Case

To allow /api/logout `targetURL` to be marked as a `safeTargetURL` for domains other than the session domain if the domain is set as a redirectURI, hence allowing the redirect to happen. 

### Details

As per discussion: https://github.com/authelia/authelia/discussions/5353

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by mind-ar** [comment]
Hi @lltr , as a workaround, you can configure a second domain:
```
session:
. . .
  cookies:
    - name: 'authelia_session'
      domain: 'example.com'
      authelia_url: 'https://login.example.com:8080'
    - name: 'example2_session'
      domain: 'example2.com'
      authelia_url: 'https://login.example2.com:8080'
```
With this, you can use example2.com as a safe redirect URL
