### ISSUE TITLE
access_control depending on the uri-path

### ISSUE THREAD

**Issue by mozdi** [authelia/authelia#542]
It would be great, if you could implement the possibility to do access-control depending on a specific path (like networks).

xyz.com with bypass and xyz.com/admin with two_factor:

    - domain: xyz.com
      path: "/"
      policy: bypass

    - domain: xyz.com
      policy: two_factor
      path: "/admin"

Thanks a lot! :)

**Comment by nightah** [comment]
This already exists today with the `resources` key.

Here's an example of some configuration I have which has explicit bypasses, network based bypasses and then two_factor requirements:

```yaml
# Note: the order of the rules is important. The first policy matching
# (domain, resource, subject) applies.
access_control:
  # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
  # It is the policy applied to any resource if there is no policy to be applied
  # to the user.
  default_policy: deny

  rules:
    # Rules applied to everyone
    - domain: auth.xyz.com
      policy: bypass

    # Rules for API bypassing
    - domain: 'xyz.com'
      resources:
        - '^/.*/api.*$'
      policy: bypass
    - domain: 'unifi.xyz.com'
      resources:
        - '^/api.*$'
        - '^/status.*$'
      policy: bypass

    # Rules for Network bypassing
    - domain: 'xyz.com'
      networks:
        - 10.10.0.0/16
      policy: bypass
    - domain: '*.xyz.com'
      networks:
        - 10.10.0.0/16
      policy: bypass

    # Rules applied to Groups for
    # xyz.com
    - domain: 'xyz.com'
      subject: 'group:phpMyAdmin'
      resources:
        - '^/phpmyadmin.*$'
      policy: two_factor
    - domain: 'xyz.com'
      subject: 'group:phpLDAPAdmin'
      resources:
        - '^/phpldapadmin.*$'
      policy: two_factor
    - domain: 'xyz.com'
      subject: 'group:ZNC'
      resources:
        - '^/znc.*$'
      policy: two_factor
    # *.xyz.com
    - domain: 'grafana.xyz.com'
      subject: 'group:Grafana'
      policy: two_factor
    - domain: 'kibana.xyz.com'
      subject: 'group:Kibana'
      policy: two_factor
    - domain: 'portainer.xyz.com'
      subject: 'group:Portainer'
      policy: two_factor
    - domain: 'unifi.xyz.com'
      subject: 'group:UniFi'
      policy: two_factor
```

To achieve what you want this is what your configuration needs to look like:

```yaml
    - domain: 'xyz.com'
      resources:
        - '^/admin.*$'
      policy: two_factor
    - domain: 'xyz.com'
      policy: bypass
```

The order matters per the configuration template because the first matched rule is what it will select.
