### ISSUE TITLE
2fa device registration link is sent as http --> cannot register device

### ISSUE THREAD

**Issue by thimplicity** [authelia/authelia#5521]
Hi, 
I set up authelia today together with HAProxy on pfSense based on [this](https://dkict.com/pfsense-haproxy-authelia/) tutorial. It works well for one_factor, but when I use two_factor, I can log in and request the device registration link. When I try to open the link (which has http, not https), I get the message that I need to register the device from the same device I sent the link on. Based on what I read in other issues, it seems that HTTPS/SSL is the problem with the link. As I am using HAproxy, I also checked the logs there. I am using an SSL certificate of my domain through LetsEncrypt.

Here is my authelia config:
````
theme: dark #matches yoursystem theme
jwt_secret: 123 #any text or number you want to add here to create jwt Token

default_redirection_url: https://google.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: local.mydomain.com #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 
        - "auth.local.mydomain.com" #This should be your authentication URL
      policy: bypass
    - domain: "filebrowser.local.mydomain.com" #example domain to protect
      policy: one_factor
    - domain: "test.local.mydomain.com" #example subdomain to protect
      policy: two_factor #could also be two_factor

session:
  name: authelia_session
  secret: unsecure_session_secret #any text or number you want to add here to create jwt Token
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: local.mydomain.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 
  encryption_key: GENERATE_STRING_MORETHAN20_CHARS
  
notifier:
  filesystem:
    filename: /config/notification.txt
````

I am not sure whether this is an authelia or HA proxy issue, maybe someone can help.

Thanks!
