### ISSUE TITLE
Configuration: session: option 'domain' is required after starting Container

### ISSUE THREAD

**Issue by holema** [authelia/authelia#5855]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Description

I want to start the container with the setup script but the containers are not starting.

### Reproduction

1. clone the repo
2. go into examples/compose/local
3. execute
4. ./setup.sh

### Expectations

The System ist starting

### Configuration (Authelia)

```yaml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret
default_redirection_url: https://public.authelia.local

server:
  address: 'tcp://:9091'

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: public.authelia.local
      policy: bypass
    - domain: traefik.authelia.local
      policy: one_factor
    - domain: secure.authelia.local
      policy: two_factor

session:
  secret: unsecure_session_secret

  cookies:
    - name: authelia_session
      domain: authelia.local  # Should match whatever your root protected domain is
      expiration: 3600  # 1 hour
      inactivity: 300  # 5 minutes

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
...
```

### Logs (Authelia)

```shell
me="2023-08-16T19:24:28+10:00" level=error msg="Configuration: session: option 'domain' is required"
time="2023-08-16T19:24:28+10:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2023-08-16T19:24:28+10:00" level=error msg="Configuration: configuration key not expected: server.address"
time="2023-08-16T19:24:28+10:00" level=error msg="Configuration: configuration key not expected: session.cookies"
time="2023-08-16T19:24:28+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].domain"
time="2023-08-16T19:24:28+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].expiration"
time="2023-08-16T19:24:28+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].inactivity"
time="2023-08-16T19:24:28+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].name"
time="2023-08-16T19:24:28+10:00" level=error msg="Configuration: session: option 'domain' is required"
time="2023-08-16T19:24:28+10:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2023-08-16T19:24:29+10:00" level=error msg="Configuration: configuration key not expected: server.address"
time="2023-08-16T19:24:29+10:00" level=error msg="Configuration: configuration key not expected: session.cookies"
time="2023-08-16T19:24:29+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].expiration"
time="2023-08-16T19:24:29+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].inactivity"
time="2023-08-16T19:24:29+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].name"
time="2023-08-16T19:24:29+10:00" level=error msg="Configuration: configuration key not expected: session.cookies[].domain"
time="2023-08-16T19:24:29+10:00" level=error msg="Configuration: session: option 'domain' is required"
time="2023-08-16T19:24:29+10:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
