### ISSUE TITLE
Support loading secrets from file

### ISSUE THREAD

**Issue by dstar4138** [authelia/authelia#602]
This feature request is to support loading any configured secret from file.

Doing so would allow support for Docker Secrets via Compose [1,2].

This request effectively reopens #310 for v4 so as to enhance support for the Docker ecosystem.

### Examples

One way would be to extend #569 with `_FILE` suffixed alternatives similar to how mariadb does [3].

```yaml
# Example docker-compose.yml
service:
  authelia:
    # ...
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secret/jwt_secret
    secrets:
      - jwt_secret
      - # ...
# ...
```

Alternatively, this could be done in the configuration file in a similar way (suffix name with `_file`):

```yaml
# Example /etc/authelia/configuration.yml
#jwt_secret: disabled
jwt_secret_file: /run/secrets/jwt_secret
# ...
```

References:
[1] - https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
[2] - https://docs.docker.com/compose/compose-file/#secrets
[3] - https://github.com/docker-library/docs/tree/master/mariadb#docker-secrets
