### ISSUE TITLE
Unable to get standalone demo working

### ISSUE THREAD

**Issue by aeneasr** [authelia/authelia#610]
Thank you for open sourcing this great project! I tried setting up the [standalone suite](https://github.com/authelia/authelia/blob/master/docs/getting-started.md) but unfortunately failed to do so at several stages:

- The [listed commands](https://github.com/authelia/authelia/blob/master/docs/getting-started.md#getting-started) do not work for me because, if I understand correctly, `authelia scripts` is not `go install`'ed which means that I have to do `cmd/authelia-scripts/authelia-scripts suites setup Standalone`. If this is intended behavior maybe the docs could be updated here?
- The Dockerfiles fail to build ([a](https://github.com/authelia/authelia/blob/master/example/compose/authelia/Dockerfile.backend), [b](https://github.com/authelia/authelia/blob/master/example/compose/authelia/Dockerfile.frontend#L7)) because `addgroup` does not accept `--guid` but `-G` instead. I was still unable to get this working with updating the the commands so I (for local testing) removed the user features from the Dockerfiles.
- And finally `docker-compose` did not come up but instead timed out after 300 seconds. I have a pretty beefy system and never have seen `docker-compose up` time out like that. I believe the problem is that `npm ci` and `npm run start` are used [at the entrypoint](https://github.com/authelia/authelia/blob/master/example/compose/authelia/resources/entrypoint-frontend.sh). Both processes, especially when dealing with webpack, are very time intense and cause this issue in my understanding.

What is the best way of checking out a demo of this project?

I was also wondering if there was more documentation on the architecture of Authelia (e.g. "Why Authelia stores users in LDAP"), API documentation, the portal.

I understand if this is not something you / the maintainers want to spend their time on, but it would be cool to get the project working and give it a ride :)

**Comment by clems4ever** [comment]
Hello @aeneasr , thank you for reporting this issue.

`authelia-scripts` is a command line that becomes available when running `source bootstrap.sh`.
Now the question is, are you on MS or on a UNIX system? I'm asking because the dev workflow has not been extensively tested on MS.

Regarding the documentation, it's in our short list. We have a complete stream around this: https://github.com/authelia/authelia/projects/3. And https://github.com/authelia/authelia/issues/480 might be of direct interest to you.

For the architecture documentation, I've just added a card in our Kanban. I'll keep you updated on this so that you can tell whether the produced document meets your expectation.

So, next step, please try `source bootstrap.sh` and the `authelia-scripts` command should be available.

**Comment by aeneasr** [comment]
Thank you for the quick reply, looks like I overlooked that you’re sourcing it, which now makes sense. I’m on latest macOS.

**Comment by aeneasr** [comment]
I `git reset --hard HEAD` and `source bootstrap.sh && authelia-scripts suites setup Standalone` and made the following observations:

- zsh does not work with bootstrap.sh: 
    ```
    % source bootstrap.sh 
    bootstrap.sh:24: = not found
    ```
- `authelia-scripts suites setup Standalone` fails during build stage:
    ```
    $ authelia-scripts suites setup Standalone
    INFO[0000] Setup environment for suite Standalone...    
    Creating network "authelia_authelianet" with driver "bridge"
    Building authelia-backend
    Step 1/10 : FROM golang:1.13-alpine
     ---> 57ce7b9daa9b
    Step 2/10 : ARG USER_ID
     ---> Using cache
     ---> c98afbbd5efa
    Step 3/10 : ARG GROUP_ID
     ---> Using cache
     ---> ac9a8efee64c
    Step 4/10 : RUN addgroup --gid ${GROUP_ID} dev &&     adduser --uid ${USER_ID} -G dev -D dev &&     apk --no-cache add gcc musl-dev
     ---> Running in 71feea782556
    addgroup: gid '20' in use
    ERROR: Service 'authelia-backend' failed to build: The command '/bin/sh -c addgroup --gid ${GROUP_ID} dev &&     adduser --uid ${USER_ID} -G dev -D dev &&     apk --no-cache add gcc musl-dev' returned a non-zero code: 1
    ERRO[0004] Failure during environment deployment.       
    Removing network authelia_authelianet
    INFO[0005] Environment has been cleaned!                
    FATA[0005] exit status 1                                
    exit status 1
    INFO[0006] Tear down environment for suite Standalone... 
    Removing network authelia_authelianet
    WARNING: Network authelia_authelianet not found.
    INFO[0000] remove .suite: no such file or directory     
    INFO[0000] Environment has been cleaned!                
    FATA[0007] exit status 1                                 
    ```

**Comment by nightah** [comment]
The first issue is interesting and odd because I use zsh and do not have any problems on Linux, I'll have a look at this on my my MacBook tomorrow.

OSX uses lower GID's for primary groups hence the second issue, looks like users start in ~500 too as opposed to 1000 like in Linux variants.
I have to admit I haven't tested this on OSX at all, we can adjust the bootstrap to detect OSX and treat accordingly, alternatively you can `export GROUP_ID=1000` or something higher that will not conflict in the interim.

**Comment by james-d-elliott** [comment]
Here's a compose I used for testing recently with traefik 2.1. It has the two files configuration.yml and users.yml sitting in the authelia folder below it. Also you'll need to replace example.com with your domain. Additionally you should be able to add just the following label to any container in the compose to make it use the Authelia middleware (see the example of this under the traefik container): traefik.http.routers.api.middlewares=authelia

```
---
version: "3.4"
networks:
  net:
    driver: bridge
services:
  traefik:
    container_name: traefik
    image: traefik:2.1.3
    restart: always
    networks:
      - net
    command:
      - "--api"
      - "--providers.docker=true"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--log=true"
      - "--log.level=DEBUG"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.api.rule=Host(`traefik.example.com`)"
    - "traefik.http.routers.api.entrypoints=https"
    - "traefik.http.routers.api.tls=true"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.middlewares=authelia"
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
#    - ./traefik/config/:/etc/traefik/
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
  redis:
    container_name: redis
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - net
  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: always
    networks:
      - net
    expose:
    - 9091
    volumes:
    - ../authelia/config/configuration.yml:/etc/authelia/configuration.yml
    - ../authelia/config/users.yml:/etc/authelia/users.yml
    - authelia-data:/var/lib/authelia
    environment:
      TZ: Australia/Melbourne
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.authelia.rule=Host(`auth.example.com`)"
    - "traefik.http.routers.authelia.entrypoints=https"
    - "traefik.http.routers.authelia.tls=true"
    - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.example.com"
    - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
volumes:
  authelia-data:
    external: true
```

./authelia/configuration.yml:
```
###############################################################
#                Authelia minimal configuration               #
###############################################################

port: 9091

logs_level: info

jwt_secret: unsecure_secret

authentication_backend:
  file:
    path: /etc/authelia/users.yml

totp:
  issuer: frigg.ellionett.com

session:
  secret: unsecure_session_secret
  domain: example.com
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  redis:
    host: redis
    port: 6379

storage:
  local:
    path: /var/lib/authelia/db.sqlite

# The Duo Push Notification API configuration

access_control:
  default_policy: bypass
  rules:
    - domain: "public.example.com"
      policy: bypass
    - domain: "traefik.example.com"
      policy: one_factor

notifier:
  smtp:
    host: smtp
    port: 1025
    sender: admin@example.com
    disable_require_tls: true
```

./authelia/users.yml (passwords are all 'password'):
```
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  john:
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"
    email: john.doe@authelia.com
    groups:
      - admins
      - dev

  harry:
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"
    email: harry.potter@authelia.com
    groups: []

  bob:
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"
    email: bob.dylan@authelia.com
    groups:
      - dev

  james:
    password: "$6$rounds=500000$jgiCMRyGXzoqpxS3$w2pJeZnnH8bwW3zzvoMWtTRfQYsHbWbD/hquuQ5vUeIyl9gdwBIt6RWk2S6afBA0DPakbeWgD/4SZPiS0hYtU/"
    email: james.dean@authelia.com
```
