### ISSUE TITLE
TOTP codes from Google Authenticator always rejected.

### ISSUE THREAD

**Issue by Rookeh** [authelia/authelia#6121]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

2.7.0-ls244

### Description

I have observed TOTP codes being consistently rejected for users using Google Authenticator.

I have an instance of Authelia deployed as part of a SWAG reverse proxy, with TOTP enabled as the second factor. There are only two users, myself and one other.

When creating my user, I was able to set up TOTP successfully using [Yubico Authenticator](https://www.yubico.com/products/yubico-authenticator/) as my 2FA application.

When the second user joined, they used [Google Authenticator](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2). However, they were unable to log in as the codes being generated by Authenticator were consistently being rejected. I reproduced this by creating a third account for testing, scanned the registration QR code in Google Authenticator, and observed the same problem.

The user has since switched over to using [Aegis](https://getaegis.app/), this seems to work fine as a workaround.

`totp` section from my `configuration.yaml`:

```
totp:
  disable: false
  issuer: redacted.domain
  algorithm: sha1
  digits: 6
  period: 60
  skew: 1
  secret_size: 32
```

Steps taken to investigate/reproduce:

- Verify clocks are synced between server and all devices - Yes
- Install Google Authenticator on another device and reproduce issue - Yes
- Confirm TOTP successful for same user using alternative application - Yes

Both myself and the other user are using Android devices - a Pixel 6 and a Pixel 7A, respectively. The issue was reproducible on both devices.

Authelia is being hosted in an ARM64 Docker environment on a Raspberry Pi 4.

Full config and log output at time of issue occurring provided below.

### Reproduction

- Configure TOTP in Authelia as per the settings above
- Create a new user
- Sign in as that user
- When prompted to set up 2FA, download Google Authenticator and scan the presented QR code
- Attempt to sign in using the TOTP generated by Google Authenticator
- Login always fails due to incorrect TOTP code

### Expectations

- TOTP codes created by Google Authenticator should be accepted.

### Configuration (Authelia)

```yaml
theme: light
jwt_secret: redacted
default_redirection_url: https://redacted.domain/
default_2fa_method: "totp"

server:
  host: 0.0.0.0
  port: 9091
  path: "authelia"
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
    client_certificates: []
  headers:
    csp_template: ""
log:
  level: debug
 
telemetry:
  metrics:
    enabled: false
    address: tcp://0.0.0.0:9959

totp:
  disable: false
  issuer: redacted.domain
  algorithm: sha1
  digits: 6
  period: 60
  skew: 1
  secret_size: 32

webauthn:
  disable: true
  timeout: 60s
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: true
    custom_url: ""
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    watch: false
    search:
      email: true
      case_insensitive: false
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

password_policy:
  standard:
    enabled: false    
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

access_control:
  default_policy: deny
  rules:   
    - domain: '*.redacted.domain'
      policy: two_factor        
    - domain: 'redacted.domain'
      policy: two_factor
  
session:
  name: authelia_session
  domain: redacted.domain
  same_site: lax
  secret: redacted
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: redacted
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
...
```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: arm64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2023-10-11T12:06:00+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'redacted'" method=POST path=/api/firstfactor remote_ip=redacted.redacted.redacted.redacted
time="2023-10-11T12:06:00+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'redacted'" method=POST path=/api/firstfactor remote_ip=redacted.redacted.redacted.redacted
time="2023-10-11T12:06:00+01:00" level=debug msg="Check authorization of subject username=redacted groups=admins ip=redacted.redacted.redacted.redacted and object https://redacted.domain/ (method )."
time="2023-10-11T12:06:00+01:00" level=debug msg="Required level for the URL https://redacted.domain/ is 2" method=POST path=/api/firstfactor remote_ip=redacted.redacted.redacted.redacted
time="2023-10-11T12:06:00+01:00" level=warning msg="https://redacted.domain/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=redacted.redacted.redacted.redacted
time="2023-10-11T12:06:16+01:00" level=debug msg="Mark TOTP authentication attempt made by user 'redacted'" method=POST path=/api/secondfactor/totp remote_ip=redacted.redacted.redacted.redacted
time="2023-10-11T12:06:16+01:00" level=error msg="Unsuccessful TOTP authentication attempt by user 'redacted'" method=POST path=/api/secondfactor/totp remote_ip=redacted.redacted.redacted.redacted stack="github.com/authelia/authelia/v4/internal/handlers/response.go:270               markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_sign_totp.go:41       TimeBasedOneTimePasswordPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15 Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54               (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25              SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35              SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16              SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                 (*Response).StatusCode\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:22           StripPath.func1.1\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                              (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                           (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                           (*workerPool).getCh.func1\nruntime/asm_arm64.s:1172                                                        goexit"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
