### ISSUE TITLE
 Shows Hi User, Logout / Authenticated instead of forwarding/loading the actual application

### ISSUE THREAD

**Issue by distributev** [authelia/authelia#6144]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.25

### Description

Using nginx as a reverse proxy when browsing to an application which is authenticated by Authelia, if the user is already signed in, it shows a form with Hi User, Logout / Authenticated instead of forwarding/loading the actual application.

![image](https://github.com/authelia/authelia/assets/19224635/b2e74ab9-8575-4321-a001-3ff3295eaa9e)

### Reproduction

Have few apps behind nginx, all being protected by authelia - login in app1 and using the same user browse (using the direct URL of app2) to app2 and instead of forwarding to the app it will show (authenticated/logout)

### Expectations

Show/forward/load app2 when the user is already logged in.

### Configuration (Authelia)

```yaml
theme: light

jwt_secret: {{ authelia_jwt_secret }}

default_redirection_url: 'https://{{ infra_arg_top_level_domain_1 }}'

server:
  host: 0.0.0.0
  port: 9091
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: "authelia"
  headers:
    csp_template: "default-src 'self'; frame-src 'none'; object-src 'none'; style-src 'self' 'nonce-${NONCE}'; base-uri 'self'; frame-ancestors 'self' http://localhost:3000 https://johny.bkstg.domain.org;"

log:
  level: debug

telemetry:
  metrics:
    enabled: false

totp:
  disable: false
  issuer: authelia.com
  algorithm: SHA1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false

ntp:
  version: 4
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
  # How often authelia should check if there is an user update in LDAP
  refresh_interval: 1m
  ldap:
    implementation: custom
    # Pattern is ldap://HOSTNAME-OR-IP:PORT
    # Normal ldap port is 389, standard in LLDAP is 3890
    url: ldap://lldap:3890
    # The dial timeout for LDAP.
    timeout: 5s
    # Use StartTLS with the LDAP connection, TLS not supported right now
    start_tls: false
    #tls:
    #  skip_verify: false
    #  minimum_version: TLS1.2
    # Set base dn, like dc=google,dc.com
{% if proxy_name %}
    base_dn: dc={{ proxy_name }}.{{ app_top_level_domain_no_extension }},dc={{ app_top_level_domain_extension }}
{% else %}
    base_dn: dc=dc={{ app_top_level_domain_no_extension }},dc={{ app_top_level_domain_extension }}
{% endif %}
    username_attribute: uid
    # You need to set this to ou=people, because all users are stored in this ou!
    additional_users_dn: ou=people
    # To allow sign in both with username and email, one can use a filter like
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    # Set this to ou=groups, because all groups are stored in this ou
    additional_groups_dn: ou=groups
    # Only this filter is supported right now
    groups_filter: "(member={dn})"
    # The attribute holding the name of the group.
    group_name_attribute: cn
    # Email attribute
    mail_attribute: mail
    # The attribute holding the display name of the user. This will be used to greet an authenticated user.
    display_name_attribute: displayName
    # The username and password of the admin user.
    # "admin" should be the admin username you set in the LLDAP configuration
{% if proxy_name %}
    user: uid={{ ldap_app_user_name }},ou=people,dc={{ proxy_name }}.{{ app_top_level_domain_no_extension }},dc={{ app_top_level_domain_extension }}
{% else %}
    user: uid={{ ldap_app_user_name }},ou=people,dc=dc={{ app_top_level_domain_no_extension }},dc={{ app_top_level_domain_extension }}
{% endif %}
    # Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    password: {{ ldap_app_password }}

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

access_control:
  default_policy: deny
  rules:
{% if proxy_name %}
    - domain: 'auth.{{ proxy_name }}.{{ app_top_level_domain }}'
{% else %}
    - domain: 'auth.{{ app_top_level_domain }}'
{% endif %}
      policy: "bypass"
{% if proxy_name %}
    - domain: '{{ proxy_name }}.{{ app_top_level_domain }}'
{% else %}
    - domain: '{{ app_top_level_domain }}'
{% endif %}
      policy: "one_factor"
{% if proxy_name %}
    - domain: '*.{{ proxy_name }}.{{ app_top_level_domain }}'
{% else %}
    - domain: '*.{{ app_top_level_domain }}'
{% endif %}
      policy: "one_factor"

session:
  secret: {{ authelia_session_secret }}
  name: 'authelia_session'
{% if proxy_name %}
  domain: '{{proxy_name}}.{{ app_top_level_domain }}'
{% else %}
  domain: '{{ app_top_level_domain }}'
{% endif %}
  same_site: 'lax'
  inactivity: '15m'
  expiration: '1h'
  remember_me_duration: '1M'

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: {{ authelia_encryption_key }}
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /notifications/notification.txt
```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2023-10-16T22:25:13+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/fonts/Open_Sans-italic-400.a2b91622ef405f9df440.woff (method GET)."
time="2023-10-16T22:26:18+02:00" level=debug msg="Checking the authentication backend for an updated profile for user francisco46" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:26:18+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/ciphers/c0a3af26-0036-4bf4-8761-133edc3a3f9f (method PUT)."
time="2023-10-16T22:28:52+02:00" level=debug msg="Checking the authentication backend for an updated profile for user francisco46" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:28:52+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/ciphers (method POST)."
time="2023-10-16T22:29:47+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/ciphers (method POST)."
time="2023-10-16T22:31:24+02:00" level=debug msg="Checking the authentication backend for an updated profile for user francisco46" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:31:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/session (method GET)."
time="2023-10-16T22:52:49+02:00" level=warning msg="Session destroyed for user 'francisco46' after exceeding configured session inactivity and not being marked as remembered" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:52:49+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/accounts/revision-date (method GET)."
time="2023-10-16T22:52:49+02:00" level=info msg="Access to https://vaultwarden.bkstg.domain.org/api/accounts/revision-date (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:52:49+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/notifications/hub?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE2OTc0ODc2MjgsImV4cCI6MTY5NzQ5NDgyOCwiaXNzIjoiaHR0cHM6Ly92YXVsdHdhcmRlbi5mbG93a3JhZnQub3JnfGxvZ2luIiwic3ViIjoiYmM0MGE0MWEtZWY4Yi00ZmRhLWFhZjktNTYzMWQ3OTQxZmJhIiwicHJlbWl1bSI6dHJ1ZSwibmFtZSI6IlZpcmdpbCIsImVtYWlsIjoidmlyZ2lsLnRyYXNjYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwib3Jnb3duZXIiOltdLCJvcmdhZG1pbiI6W10sIm9yZ3VzZXIiOltdLCJvcmdtYW5hZ2VyIjpbXSwic3N0YW1wIjoiY2I1MGNjNmUtYjhmMy00MTVmLTliMTMtODA0OTNkNzYyOTlmIiwiZGV2aWNlIjoiMWJlYmFjMDktMjc0NS00NGYxLWIxNDgtYjI1YmE1NmI5YjMyIiwic2NvcGUiOlsiYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbIkFwcGxpY2F0aW9uIl19.O0CR0tMWpu_JzxYrgVR-e5DdRN_BVWZWWWh_DZRE9Aa3S3-wQlry2STZNDqpaSohdE4pxlkc75fT1vCyIXWE48eXE9DBzcm2eir3JZJQbZ3rhdY_Hk0VA2QJfRnkMGLG7TIiXbGPNxskYMSRpSHlsXQorGKp3QeFZA9Oq3fhgh5U11fFriXHK8K0xhoeUNdxVWP2aJxwyC9_IVj0p0faPNNWGGL7vQ08t-0zgNJmXA3ogEXvyoURyOu9TXz-xcVp50OG0pI186c3dec3iaC3JI7WI3sE7Z6cHizxpMDwkKnM0Qg-CXwaE7e8IVZfbpdb2kSmwtzhsEs2S71pU8nSIQ (method GET)."
time="2023-10-16T22:52:49+02:00" level=info msg="Access to https://vaultwarden.bkstg.domain.org/notifications/hub?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE2OTc0ODc2MjgsImV4cCI6MTY5NzQ5NDgyOCwiaXNzIjoiaHR0cHM6Ly92YXVsdHdhcmRlbi5mbG93a3JhZnQub3JnfGxvZ2luIiwic3ViIjoiYmM0MGE0MWEtZWY4Yi00ZmRhLWFhZjktNTYzMWQ3OTQxZmJhIiwicHJlbWl1bSI6dHJ1ZSwibmFtZSI6IlZpcmdpbCIsImVtYWlsIjoidmlyZ2lsLnRyYXNjYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwib3Jnb3duZXIiOltdLCJvcmdhZG1pbiI6W10sIm9yZ3VzZXIiOltdLCJvcmdtYW5hZ2VyIjpbXSwic3N0YW1wIjoiY2I1MGNjNmUtYjhmMy00MTVmLTliMTMtODA0OTNkNzYyOTlmIiwiZGV2aWNlIjoiMWJlYmFjMDktMjc0NS00NGYxLWIxNDgtYjI1YmE1NmI5YjMyIiwic2NvcGUiOlsiYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbIkFwcGxpY2F0aW9uIl19.O0CR0tMWpu_JzxYrgVR-e5DdRN_BVWZWWWh_DZRE9Aa3S3-wQlry2STZNDqpaSohdE4pxlkc75fT1vCyIXWE48eXE9DBzcm2eir3JZJQbZ3rhdY_Hk0VA2QJfRnkMGLG7TIiXbGPNxskYMSRpSHlsXQorGKp3QeFZA9Oq3fhgh5U11fFriXHK8K0xhoeUNdxVWP2aJxwyC9_IVj0p0faPNNWGGL7vQ08t-0zgNJmXA3ogEXvyoURyOu9TXz-xcVp50OG0pI186c3dec3iaC3JI7WI3sE7Z6cHizxpMDwkKnM0Qg-CXwaE7e8IVZfbpdb2kSmwtzhsEs2S71pU8nSIQ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:52:49+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/config (method GET)."
time="2023-10-16T22:52:49+02:00" level=info msg="Access to https://vaultwarden.bkstg.domain.org/api/config (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:57:11+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/notifications/hub?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE2OTc0ODc2MjgsImV4cCI6MTY5NzQ5NDgyOCwiaXNzIjoiaHR0cHM6Ly92YXVsdHdhcmRlbi5mbG93a3JhZnQub3JnfGxvZ2luIiwic3ViIjoiYmM0MGE0MWEtZWY4Yi00ZmRhLWFhZjktNTYzMWQ3OTQxZmJhIiwicHJlbWl1bSI6dHJ1ZSwibmFtZSI6IlZpcmdpbCIsImVtYWlsIjoidmlyZ2lsLnRyYXNjYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwib3Jnb3duZXIiOltdLCJvcmdhZG1pbiI6W10sIm9yZ3VzZXIiOltdLCJvcmdtYW5hZ2VyIjpbXSwic3N0YW1wIjoiY2I1MGNjNmUtYjhmMy00MTVmLTliMTMtODA0OTNkNzYyOTlmIiwiZGV2aWNlIjoiMWJlYmFjMDktMjc0NS00NGYxLWIxNDgtYjI1YmE1NmI5YjMyIiwic2NvcGUiOlsiYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbIkFwcGxpY2F0aW9uIl19.O0CR0tMWpu_JzxYrgVR-e5DdRN_BVWZWWWh_DZRE9Aa3S3-wQlry2STZNDqpaSohdE4pxlkc75fT1vCyIXWE48eXE9DBzcm2eir3JZJQbZ3rhdY_Hk0VA2QJfRnkMGLG7TIiXbGPNxskYMSRpSHlsXQorGKp3QeFZA9Oq3fhgh5U11fFriXHK8K0xhoeUNdxVWP2aJxwyC9_IVj0p0faPNNWGGL7vQ08t-0zgNJmXA3ogEXvyoURyOu9TXz-xcVp50OG0pI186c3dec3iaC3JI7WI3sE7Z6cHizxpMDwkKnM0Qg-CXwaE7e8IVZfbpdb2kSmwtzhsEs2S71pU8nSIQ (method GET)."
time="2023-10-16T22:57:11+02:00" level=info msg="Access to https://vaultwarden.bkstg.domain.org/notifications/hub?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE2OTc0ODc2MjgsImV4cCI6MTY5NzQ5NDgyOCwiaXNzIjoiaHR0cHM6Ly92YXVsdHdhcmRlbi5mbG93a3JhZnQub3JnfGxvZ2luIiwic3ViIjoiYmM0MGE0MWEtZWY4Yi00ZmRhLWFhZjktNTYzMWQ3OTQxZmJhIiwicHJlbWl1bSI6dHJ1ZSwibmFtZSI6IlZpcmdpbCIsImVtYWlsIjoidmlyZ2lsLnRyYXNjYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwib3Jnb3duZXIiOltdLCJvcmdhZG1pbiI6W10sIm9yZ3VzZXIiOltdLCJvcmdtYW5hZ2VyIjpbXSwic3N0YW1wIjoiY2I1MGNjNmUtYjhmMy00MTVmLTliMTMtODA0OTNkNzYyOTlmIiwiZGV2aWNlIjoiMWJlYmFjMDktMjc0NS00NGYxLWIxNDgtYjI1YmE1NmI5YjMyIiwic2NvcGUiOlsiYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbIkFwcGxpY2F0aW9uIl19.O0CR0tMWpu_JzxYrgVR-e5DdRN_BVWZWWWh_DZRE9Aa3S3-wQlry2STZNDqpaSohdE4pxlkc75fT1vCyIXWE48eXE9DBzcm2eir3JZJQbZ3rhdY_Hk0VA2QJfRnkMGLG7TIiXbGPNxskYMSRpSHlsXQorGKp3QeFZA9Oq3fhgh5U11fFriXHK8K0xhoeUNdxVWP2aJxwyC9_IVj0p0faPNNWGGL7vQ08t-0zgNJmXA3ogEXvyoURyOu9TXz-xcVp50OG0pI186c3dec3iaC3JI7WI3sE7Z6cHizxpMDwkKnM0Qg-CXwaE7e8IVZfbpdb2kSmwtzhsEs2S71pU8nSIQ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:58:01+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/session (method GET)."
time="2023-10-16T22:58:01+02:00" level=info msg="Access to https://johny.bkstg.domain.org/api/auth/session (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:58:02+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/_log (method POST)."
time="2023-10-16T22:58:02+02:00" level=info msg="Access to https://johny.bkstg.domain.org/api/auth/_log (method POST) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:58:04+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/providers (method GET)."
time="2023-10-16T22:58:04+02:00" level=info msg="Access to https://johny.bkstg.domain.org/api/auth/providers (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:58:04+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/_log (method POST)."
time="2023-10-16T22:58:04+02:00" level=info msg="Access to https://johny.bkstg.domain.org/api/auth/_log (method POST) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:58:04+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/error (method GET)."
time="2023-10-16T22:58:04+02:00" level=info msg="Access to https://johny.bkstg.domain.org/api/auth/error (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:58:18+02:00" level=debug msg="Mark 1FA authentication attempt made by user 'francisco46'" method=POST path=/api/firstfactor remote_ip=188.115.7.41
time="2023-10-16T22:58:18+02:00" level=debug msg="Successful 1FA authentication attempt made by user 'francisco46'" method=POST path=/api/firstfactor remote_ip=188.115.7.41
time="2023-10-16T22:58:18+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/error (method )."
time="2023-10-16T22:58:18+02:00" level=debug msg="Required level for the URL https://johny.bkstg.domain.org/api/auth/error is 1" method=POST path=/api/firstfactor remote_ip=188.115.7.41
time="2023-10-16T22:58:18+02:00" level=debug msg="Redirection URL https://johny.bkstg.domain.org/api/auth/error is safe" method=POST path=/api/firstfactor remote_ip=188.115.7.41
time="2023-10-16T22:58:19+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/error (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://johny.bkstg.domain.org/ (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/session (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/ (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/css/index.css (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/css/xterm.css (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/css/xterm_customize.css (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/auth_token.js (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/config.js (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/js/gotty.js (method GET)."
time="2023-10-16T22:58:24+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://emacs.bkstg.domain.org/ws (method GET)."
time="2023-10-16T22:58:32+02:00" level=debug msg="Check authorization of subject username= groups= ip=188.115.7.41 and object https://johny.bkstg.domain.org/ (method GET)."
time="2023-10-16T22:58:32+02:00" level=info msg="Access to https://johny.bkstg.domain.org/ (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=188.115.7.41
time="2023-10-16T22:58:34+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/ (method GET)."
time="2023-10-16T22:58:35+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/config (method GET)."
time="2023-10-16T22:58:35+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/config (method GET)."
time="2023-10-16T22:58:43+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/devices/knowndevice (method GET)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/identity/accounts/prelogin (method POST)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/identity/connect/token (method POST)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/config (method GET)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/config (method GET)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/identity/connect/token (method POST)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/sync?excludeDomains=true (method GET)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/notifications/hub?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE2OTc0ODk5MjksImV4cCI6MTY5NzQ5NzEyOSwiaXNzIjoiaHR0cHM6Ly92YXVsdHdhcmRlbi5mbG93a3JhZnQub3JnfGxvZ2luIiwic3ViIjoiYmM0MGE0MWEtZWY4Yi00ZmRhLWFhZjktNTYzMWQ3OTQxZmJhIiwicHJlbWl1bSI6dHJ1ZSwibmFtZSI6IlZpcmdpbCIsImVtYWlsIjoidmlyZ2lsLnRyYXNjYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwib3Jnb3duZXIiOltdLCJvcmdhZG1pbiI6W10sIm9yZ3VzZXIiOltdLCJvcmdtYW5hZ2VyIjpbXSwic3N0YW1wIjoiY2I1MGNjNmUtYjhmMy00MTVmLTliMTMtODA0OTNkNzYyOTlmIiwiZGV2aWNlIjoiMWJlYmFjMDktMjc0NS00NGYxLWIxNDgtYjI1YmE1NmI5YjMyIiwic2NvcGUiOlsiYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbIkFwcGxpY2F0aW9uIl19.oV-iO5NAf4eGv7VtGmccHI3l1W4bJliZNM8iNInNYe3wNkd9Gm6M0gt_rkBlP4xtkpHRl0skAXV2mwM2BYXNt0rY7gle3khjKW337PGolJU_1I2gU2rHD2_Zmk-Y7K1DcW7DT1ZPa9c8-QVjJh1Ime_3PPSMLOkGL9fodCIATek0CB1ftEiEHo338VOBtVlDMfDNwHSfHBsMSf74q1ZX_6LJRVWRF4_bvpotCOVDvRNCjCk-TBMDYUYL2jy4oR07z5Pf9dDDqQE5Tc_vKYukvY5Q8nHPJH-w8HkcPjullhUelZ3PUjDfOVmW-TD-5mMKXWmixV0AQxoYmS2IbJjyEQ (method GET)."
time="2023-10-16T22:58:49+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://vaultwarden.bkstg.domain.org/api/config (method GET)."
time="2023-10-16T22:58:53+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=188.115.7.41 and object https://johny.bkstg.domain.org/api/auth/session (method GET)."
root@internalsystems:/home/infraworker/ru
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
