### ISSUE TITLE
Good credentials result into api/auth/error instead of forwarding/loading the app

### ISSUE THREAD

**Issue by distributev** [authelia/authelia#6166]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Description

I try to login to one of the applications protected by authelia (which are behind plain nginx reverse proxy), I provide good credentials and instead of forwarding me to the application which I need to access I get a grey screen with the URL /api/auth/error
and and Error message on the screen. I then manually remove the part of the URL which says /api/auth/error and by doing so I get to access the application which I initially wanted to load (this proves that the provided API credentials were good otherwise I could not access the app after I manually remove /api/auth/error from the URL)

![image](https://github.com/authelia/authelia/assets/19224635/9ff76655-01aa-4a31-9e0b-555de9bd1250)

### Reproduction

do what I described above.

### Expectations

Given good credentials are provided auth should authenticate and forware users to the actual applications being protected instead of showing and error page with and /api/auth/error URL which, when manually removed, loads the actual application.

### Configuration (Authelia)

```yaml
: light

jwt_secret: WYjiu9I50hf7TrLUxA5fSuJo1kBFJIjFENAdAW80Mi3rlDjjSMVfnOMqULe1GE4f

default_redirection_url: 'https://domain.org'

server:
  host: 0.0.0.0
  port: 9091
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: "authelia"
  headers:
    csp_template: "default-src 'self'; frame-src 'none'; object-src 'none'; style-src 'self' 'nonce-${NONCE}'; base-uri 'self'; frame-ancestors 'self' http://localhost:3000 https://virgil.>

log:
  level: debug

telemetry:
  metrics:
    enabled: false

totp:
  disable: false
  issuer: authelia.com
  algorithm: SHA1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false

ntp:
  version: 4
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
  # How often authelia should check if there is an user update in LDAP
  refresh_interval: 1m
  ldap:
    implementation: custom
 # Pattern is ldap://HOSTNAME-OR-IP:PORT
    # Normal ldap port is 389, standard in LLDAP is 3890
    url: ldap://lldap:3890
    # The dial timeout for LDAP.
    timeout: 5s
    # Use StartTLS with the LDAP connection, TLS not supported right now
    start_tls: false
    #tls:
    #  skip_verify: false
    #  minimum_version: TLS1.2
    # Set base dn, like dc=google,dc.com
    base_dn: dc=bkstg.domain,dc=org
    username_attribute: uid
    # You need to set this to ou=people, because all users are stored in this ou!
    additional_users_dn: ou=people
    # To allow sign in both with username and email, one can use a filter like
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    # Set this to ou=groups, because all groups are stored in this ou
    additional_groups_dn: ou=groups
    # Only this filter is supported right now
    groups_filter: "(member={dn})"
    # The attribute holding the name of the group.
    group_name_attribute: cn
    # Email attribute
    mail_attribute: mail
    # The attribute holding the display name of the user. This will be used to greet an authenticated user.
    display_name_attribute: displayName
    # The username and password of the admin user.
    # "admin" should be the admin username you set in the LLDAP configuration
    user: uid=lisagilbert,ou=people,dc=bkstg.domain,dc=org
    # Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    password: FokdeNeorBly

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

access_control:
  default_policy: deny
  rules:
    - domain: 'auth.bkstg.domain.org'
      policy: "bypass"
    - domain: 'bkstg.domain.org'
      policy: "one_factor"
    - domain: '*.bkstg.domain.org'
      policy: "one_factor"

session:
  secret: UEBNCYAe0U96j23qp0aWSJF2sNHfosv8F0W0yIAH05Mfw9qPVKxaDtAHeyY6ww4y
  name: 'authelia_session'
  domain: 'bkstg.domain.org'
  same_site: 'lax'
  inactivity: '15m'
  expiration: '1h'
  remember_me_duration: '1M'

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: lERasLc4lDwOQicpH29SeEWH
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /notifications/notification.txt
```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2023-10-20T12:39:05+02:00" level=trace msg="Request hit" method=GET path=/favicon.ico remote_ip=81.209.179.153
time="2023-10-20T12:39:05+02:00" level=trace msg="Replied (status=200)" method=GET path=/favicon.ico remote_ip=81.209.179.153
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Headers=GET /api/verify HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0\r\nHost: authelia:9091\r\nContent-Type: application/json\r\nX-Original-Url: https://subdomain2.subdomain.domain.org/api/auth/providers\r\nX-Original-Method: GET\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Host: subdomain2.subdomain.domain.org\r\nX-Forwarded-Uri: /api/auth/providers\r\nX-Forwarded-For: 196.183.490.70\r\nAccept: */*\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nReferer: https://subdomain2.subdomain.domain.org/\r\nSec-Fetch-Dest: empty\r\nSec-Fetch-Mode: cors\r\nSec-Fetch-Site: same-origin\r\nCookie: __Host-next-auth.csrf-token=38fea70d2b2f78ba9f38ad35f4f7832791b8b7243d70b2f962ea7257776cd007%7Ca55f8a7df4bd2fe5575c70cf3e029bbf1435c512fbaf57459bfec7c4100181c7; __Secure-next-auth.callback-url=https%3A%2F%2Fsubdomain2.subdomain.domain.org%2F; __Secure-next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Nz3RhHaIMXY4rC3l.Ox0wI3Nb1haE_50VSuUYah8tiwt3nQJaViTrLcm64oFB4OnSxD3p4J7TDLX3Zul5G958vdYkg-2iCJBwLn9yZUOy5kIisEuSvgXkPegJkbgfApvTdBEk7gYXzVexQGxSc8Y3oXmFV79gX6MivyJ2vmZ7oOb7yoclv50ghJOH615Nv_VjdY6Nen5aVrzyIa9Y7FjebxW9GDcJmd06ohHDyqwTy0vrsabQ89fy9YA_I_p9sSqelyHmU9GakZMrRsr4siDS1WQU31jT3wFi_yH8uozXIdaAgPPxcHWJ4k9dTXZgSYic7ZnOiE_cJL453Fs5EoTv14amepzXqEwdY5mtQWYTjKSzGugCkSt7yN-M.W3ckFYk-eITVvQcEfZps-Q\r\n\r\n" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Using X-Original-URL header content as targeted site URL" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=debug msg="Check authorization of subject username= groups= ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/providers (method GET)."
time="2023-10-20T12:39:12+02:00" level=trace msg="ACL HIT Position 1 for subject username= groups= ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/providers (method GET)"
time="2023-10-20T12:39:12+02:00" level=info msg="Access to https://subdomain2.subdomain.domain.org/api/auth/providers (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=401)" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=OPTIONS path=/ remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=200)" method=OPTIONS path=/ remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Headers=GET /api/verify HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0\r\nHost: authelia:9091\r\nContent-Type: application/x-www-form-urlencoded;charset=UTF-8\r\nX-Original-Url: https://subdomain2.subdomain.domain.org/api/auth/_log\r\nX-Original-Method: POST\r\nX-Forwarded-Method: POST\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Host: subdomain2.subdomain.domain.org\r\nX-Forwarded-Uri: /api/auth/_log\r\nX-Forwarded-For: 196.183.490.70\r\nAccept: */*\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nReferer: https://subdomain2.subdomain.domain.org/\r\nOrigin: https://subdomain2.subdomain.domain.org\r\nSec-Fetch-Dest: empty\r\nSec-Fetch-Mode: no-cors\r\nSec-Fetch-Site: same-origin\r\nCookie: __Host-next-auth.csrf-token=38fea70d2b2f78ba9f38ad35f4f7832791b8b7243d70b2f962ea7257776cd007%7Ca55f8a7df4bd2fe5575c70cf3e029bbf1435c512fbaf57459bfec7c4100181c7; __Secure-next-auth.callback-url=https%3A%2F%2Fsubdomain2.subdomain.domain.org%2F; __Secure-next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Nz3RhHaIMXY4rC3l.Ox0wI3Nb1haE_50VSuUYah8tiwt3nQJaViTrLcm64oFB4OnSxD3p4J7TDLX3Zul5G958vdYkg-2iCJBwLn9yZUOy5kIisEuSvgXkPegJkbgfApvTdBEk7gYXzVexQGxSc8Y3oXmFV79gX6MivyJ2vmZ7oOb7yoclv50ghJOH615Nv_VjdY6Nen5aVrzyIa9Y7FjebxW9GDcJmd06ohHDyqwTy0vrsabQ89fy9YA_I_p9sSqelyHmU9GakZMrRsr4siDS1WQU31jT3wFi_yH8uozXIdaAgPPxcHWJ4k9dTXZgSYic7ZnOiE_cJL453Fs5EoTv14amepzXqEwdY5mtQWYTjKSzGugCkSt7yN-M.W3ckFYk-eITVvQcEfZps-Q\r\n\r\n" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Using X-Original-URL header content as targeted site URL" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=debug msg="Check authorization of subject username= groups= ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/_log (method POST)."
time="2023-10-20T12:39:12+02:00" level=trace msg="ACL HIT Position 1 for subject username= groups= ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/_log (method POST)"
time="2023-10-20T12:39:12+02:00" level=info msg="Access to https://subdomain2.subdomain.domain.org/api/auth/_log (method POST) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=401)" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Headers=GET /api/verify HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0\r\nHost: authelia:9091\r\nX-Original-Url: https://subdomain2.subdomain.domain.org/api/auth/error\r\nX-Original-Method: GET\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Host: subdomain2.subdomain.domain.org\r\nX-Forwarded-Uri: /api/auth/error\r\nX-Forwarded-For: 196.183.490.70\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nReferer: https://subdomain2.subdomain.domain.org/\r\nUpgrade-Insecure-Requests: 1\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: same-origin\r\nSec-Fetch-User: ?1\r\nIf-None-Match: \"13a2lkf979x3sq\"\r\nCookie: __Host-next-auth.csrf-token=38fea70d2b2f78ba9f38ad35f4f7832791b8b7243d70b2f962ea7257776cd007%7Ca55f8a7df4bd2fe5575c70cf3e029bbf1435c512fbaf57459bfec7c4100181c7; __Secure-next-auth.callback-url=https%3A%2F%2Fsubdomain2.subdomain.domain.org%2F; __Secure-next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Nz3RhHaIMXY4rC3l.Ox0wI3Nb1haE_50VSuUYah8tiwt3nQJaViTrLcm64oFB4OnSxD3p4J7TDLX3Zul5G958vdYkg-2iCJBwLn9yZUOy5kIisEuSvgXkPegJkbgfApvTdBEk7gYXzVexQGxSc8Y3oXmFV79gX6MivyJ2vmZ7oOb7yoclv50ghJOH615Nv_VjdY6Nen5aVrzyIa9Y7FjebxW9GDcJmd06ohHDyqwTy0vrsabQ89fy9YA_I_p9sSqelyHmU9GakZMrRsr4siDS1WQU31jT3wFi_yH8uozXIdaAgPPxcHWJ4k9dTXZgSYic7ZnOiE_cJL453Fs5EoTv14amepzXqEwdY5mtQWYTjKSzGugCkSt7yN-M.W3ckFYk-eITVvQcEfZps-Q\r\n\r\n" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Using X-Original-URL header content as targeted site URL" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=debug msg="Check authorization of subject username= groups= ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/error (method GET)."
time="2023-10-20T12:39:12+02:00" level=trace msg="ACL HIT Position 1 for subject username= groups= ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/error (method GET)"
time="2023-10-20T12:39:12+02:00" level=info msg="Access to https://subdomain2.subdomain.domain.org/api/auth/error (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=401)" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/ remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/ remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/static/js/index.fad9e36b.js remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=304)" method=GET path=/static/js/index.fad9e36b.js remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/static/css/index.40feef90.css remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=304)" method=GET path=/static/css/index.40feef90.css remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/locales/en/portal.json remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en/portal.json remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/locales/en-US/portal.json remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en-US/portal.json remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/favicon.ico remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=200)" method=GET path=/favicon.ico remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=196.183.490.70
time="2023-10-20T12:39:12+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=196.183.490.70
time="2023-10-20T12:39:19+02:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:39:19+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:39:45+02:00" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:45+02:00" level=trace msg="Detected user filter is (&(uid=francisco46)(objectClass=person))"
time="2023-10-20T12:39:45+02:00" level=trace msg="Performing user search" attr="[uid mail displayName]" base_dn="ou=people,dc=subdomain.domain,dc=org" deref=0 filter="(&(uid=francisco46)(objectClass=person))" scope=2
time="2023-10-20T12:39:46+02:00" level=debug msg="Mark 1FA authentication attempt made by user 'francisco46'" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=debug msg="Successful 1FA authentication attempt made by user 'francisco46'" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Detected user filter is (&(uid=francisco46)(objectClass=person))"
time="2023-10-20T12:39:46+02:00" level=trace msg="Performing user search" attr="[uid mail displayName]" base_dn="ou=people,dc=subdomain.domain,dc=org" deref=0 filter="(&(uid=francisco46)(objectClass=person))" scope=2
time="2023-10-20T12:39:46+02:00" level=trace msg="Computed groups filter is (member=uid=francisco46,ou=people,dc=subdomain.domain,dc=org)"
time="2023-10-20T12:39:46+02:00" level=trace msg="Performing group search" attr="[cn]" base_dn="ou=groups,dc=subdomain.domain,dc=org" deref=0 filter="(member=uid=francisco46,ou=people,dc=subdomain.domain,dc=org)" scope=2
time="2023-10-20T12:39:46+02:00" level=trace msg="Profile details for user 'francisco46' => groups: [lldap_strict_readonly], emails [francisco@domain.org]" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/error (method )."
time="2023-10-20T12:39:46+02:00" level=trace msg="ACL HIT Position 1 for subject username=francisco46 groups=lldap_strict_readonly ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/error (method )"
time="2023-10-20T12:39:46+02:00" level=debug msg="Required level for the URL https://subdomain2.subdomain.domain.org/api/auth/error is 1" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=debug msg="Redirection URL https://subdomain2.subdomain.domain.org/api/auth/error is safe" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Timing Attack Delay successful: true, exec duration: 341, avg execution duration: 355, random delay ms: 22, total delay ms: 377, actual delay ms: 36" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Headers=GET /api/verify HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0\r\nHost: authelia:9091\r\nX-Original-Url: https://subdomain2.subdomain.domain.org/api/auth/error\r\nX-Original-Method: GET\r\nX-Forwarded-Method: GET\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Host: subdomain2.subdomain.domain.org\r\nX-Forwarded-Uri: /api/auth/error\r\nX-Forwarded-For: 196.183.490.70\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nReferer: https://auth.subdomain.domain.org/\r\nUpgrade-Insecure-Requests: 1\r\nSec-Fetch-Dest: document\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-Site: same-site\r\nSec-Fetch-User: ?1\r\nCookie: __Host-next-auth.csrf-token=38fea70d2b2f78ba9f38ad35f4f7832791b8b7243d70b2f962ea7257776cd007%7Ca55f8a7df4bd2fe5575c70cf3e029bbf1435c512fbaf57459bfec7c4100181c7; __Secure-next-auth.callback-url=https%3A%2F%2Fsubdomain2.subdomain.domain.org%2F; __Secure-next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Nz3RhHaIMXY4rC3l.Ox0wI3Nb1haE_50VSuUYah8tiwt3nQJaViTrLcm64oFB4OnSxD3p4J7TDLX3Zul5G958vdYkg-2iCJBwLn9yZUOy5kIisEuSvgXkPegJkbgfApvTdBEk7gYXzVexQGxSc8Y3oXmFV79gX6MivyJ2vmZ7oOb7yoclv50ghJOH615Nv_VjdY6Nen5aVrzyIa9Y7FjebxW9GDcJmd06ohHDyqwTy0vrsabQ89fy9YA_I_p9sSqelyHmU9GakZMrRsr4siDS1WQU31jT3wFi_yH8uozXIdaAgPPxcHWJ4k9dTXZgSYic7ZnOiE_cJL453Fs5EoTv14amepzXqEwdY5mtQWYTjKSzGugCkSt7yN-M.W3ckFYk-eITVvQcEfZps-Q; authelia_session=yCpI$dnGlRcelgu#iEQ4GdDTbeobtP#u\r\n\r\n" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Using X-Original-URL header content as targeted site URL" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Inactivity report for user 'francisco46'. Current Time: 1697798386, Last Activity: 1697798386, Maximum Inactivity: 900." method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=trace msg="Checking if we need check the authentication backend for an updated profile for francisco46." method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:46+02:00" level=debug msg="Check authorization of subject username=francisco46 groups=lldap_strict_readonly ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/error (method GET)."
time="2023-10-20T12:39:46+02:00" level=trace msg="ACL HIT Position 1 for subject username=francisco46 groups=lldap_strict_readonly ip=196.183.490.70 and object https://subdomain2.subdomain.domain.org/api/auth/error (method GET)"
time="2023-10-20T12:39:46+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/verify remote_ip=196.183.490.70
time="2023-10-20T12:39:49+02:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:39:49+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:40:19+02:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:40:19+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:40:49+02:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:40:49+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:41:19+02:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:41:19+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:41:49+02:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:41:49+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-10-20T12:42:19+02:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
