### ISSUE TITLE
Invalid memory address using Arch package

### ISSUE THREAD

**Issue by ejparker12** [authelia/authelia#622]
It's been a while and I'm working on rebuilding my authelia server. I saw that there's a package in the AUR now, so I decided to give that a shot and I ran into the below issue w/ both the authelia and authelia-bin packages.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x770986]

goroutine 1 [running]:
github.com/authelia/authelia/internal/configuration/validator.ValidateSQLStorage(0x0, 0xc00014d7a0)
        github.com/authelia/authelia@/internal/configuration/validator/storage.go:11 +0x26
github.com/authelia/authelia/internal/configuration/validator.Validate(0xc0000ae700, 0xc00014d7a0)
        github.com/authelia/authelia@/internal/configuration/validator/configuration.go:44 +0x163
github.com/authelia/authelia/internal/configuration.Read(0x7ffcfa3b3dd4, 0x1f, 0x0, 0x0, 0xc00014d850, 0x8)
        github.com/authelia/authelia@/internal/configuration/reader.go:46 +0x647
main.startServer()
        github.com/authelia/authelia@/cmd/authelia/main.go:36 +0x93
main.main.func1(0xc000205680, 0xc000283080, 0x0, 0x2)
        github.com/authelia/authelia@/cmd/authelia/main.go:109 +0x20
github.com/spf13/cobra.(*Command).execute(0xc000205680, 0xc000020190, 0x2, 0x2, 0xc000205680, 0xc000020190)
        github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000205680, 0xc00014df38, 0x3, 0x3)
        github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        github.com/authelia/authelia@/cmd/authelia/main.go:124 +0x186
```

My config file:
```
host: 0.0.0.0
port: 8080

logs_level: debug

jwt_secret: [secret]

default_redirection_url: https://portal.[mydomain].com/

totp:
  issuer: authelia.[mydomain].com

authentication_backend:
  ldap:
    url: ldap://ipa.[mydomain].com
    skip_verify: false
    base_dn: dc=[mydomain],dc=com

    additional_users_dn: cn=users,cn=accounts
    users_filter: uid={0}

    additional_groups_dn: cn=groups,cn=accounts
    groups_filter: (&(member=uid={0},cn=users,cn=accounts,dc=[mydomain],dc=com)(objectclass=groupofnames))
    group_name_attribute: cn

    mail_attribute: mail

    user: uid=authelia_admin,cn=users,cn=accounts,dc=[mydomain],dc=com
    password: [password]

access_control:
  default_policy: deny
  any:
     - domain: 'x'
       policy: deny
  groups:
    domain_admins:
       - domain: '*.[mydomain].com'
         policy: allow
    video_admins:
      - domain: '[server].[mydomain].com'
         policy: allow
       - domain: '[server].[mydomain].com'
         policy: allow
       - domain: '[server].[mydomain].com'
         policy: allow
       - domain: '[server].[mydomain].com'
         policy: allow
  users:
     none:
       - domain: 'none'
         policy: deny

session:
  name: authelia_session
  secret: [secret]
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: [mydomain].com

  redis:
    host: 127.0.0.1
    port: 6379
    password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  smtp:
    username: notifications@[mydomain].com
    password: [password]
    secure: true
    host: 'smtp.zoho.com'
    port: 465
    sender: '[mydomain] Authelia <notifications@[mydomain].com>'
```

I pulled the duo section entirely since I wasn't planning on using duo at all and the rest I migrated from my old configuration.

sqlite is installed (I'll be moving to mysql once I've got it working again, but sqlite is easier for testing) and redis is both installed and running.
