### ISSUE TITLE
Issue authenticating against freeipa - cannot parse valid group

### ISSUE THREAD

**Issue by NunoHiggs** [authelia/authelia#6268]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

nginx version: nginx/1.14.1

### Description

Hello All,

I have been following the Howtos on how to connect authelia to freeipa, and can now connect an authenticate without any issue.
However, if i set the filter for a particular ldap group i get permission denied. 

At first i thought this could be an configuration error on my part until i found that authelia is unable to parse the group names from freeipa, as shown in the logs: **groups=** 

```
time="2023-11-13T08:56:25Z" level=trace msg="Inactivity report for user 'nuno'. Current Time: 1699865785, Last Activity: 1699865784, Maximum Inactivity: 7200." method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=trace msg="Checking if we need check the authentication backend for an updated profile for nuno." method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=debug msg="Check authorization of subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/ (method )."

```

### Reproduction

Fresh install of authelia, i am able authenticate against freeipa (also can bind against it), but cannot not see groups from that user as reported in the logs.

### Expectations

To be able to use ACL's in authelia, freeipa/ldap groups

### Configuration (Authelia)

```yaml
server:

  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: "/config/key.pem"
    certificate: "/config/cert.pem"

log.level: trace
jwt_secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
default_redirection_url: https://auth.mysite.com
totp:
  issuer: auth.mysite.com
  period: 30
  skew: 1

#duo_api:     ## If you want push notifictions of login attempts you can pay for this feature
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  secret_key: yet-another-long-string-of-characters-and-numbers-and-symbols

authentication_backend:
  disable_reset_password: false
  ldap:
    implementation: custom
    url: ldaps://ipa.internal.xpto:33636
    timeout: 5s
    start_tls: false
    tls:
      server_name: ipa.internal.xpto
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: dc=net,DC=xpto
    username_attribute: uid
    additional_users_dn: CN=users,CN=accounts
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    additional_groups_dn: OU=groups
    groups_filter: (&(member=uid={input},cn=users,cn=accounts,dc=internal,dc=xpto)(objectclass=groupofnames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: uid=query_bind,cn=users,cn=accounts,dc=internal,dc=xpto
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXX"

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "auth.mysite.com"
      policy: bypass

    - domain: lab.mysite.com
      subject: 'group:netshare_blog.mysite.com'
      policy: one_factor

#      networks:
#        - 192.168.1.0/24
    - domain: # Proxies needing 2 factor below
        - "proxmox.yourdomain.com"
      policy: two_factor
#      networks:
#         - 192.168.1.0/24
         
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: XXXXXXXXXXXXXXXXXXXXXXXX
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: mysite.com # Needs to be your root domain

#
#   host: authelia_redis_1
#   port: 6379
#   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
#    password: authelia

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: light   # options: dark, light

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  mysql:
  # MySQL allows running multiple authelia instances. Create database and enter details below.
    host: mysql.internal.xpto
    port: 3306
    database: mya
    username: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
    password: XXXXXXXXXXXXXXXXXXXXXXXXXX

    
notifier:
  filesystem:
    filename: /config/notification.txt
```

### Build Information

```shell
# docker run authelia/authelia:latest authelia build-info         
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2023-11-13T08:56:19Z" level=info msg="Access to https://lab.mysite.com/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:19Z" level=trace msg="Replied (status=401)" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:19Z" level=trace msg="Request hit" method=GET path=/ remote_ip=85.245.39.215
time="2023-11-13T08:56:19Z" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=85.245.39.215
time="2023-11-13T08:56:20Z" level=trace msg="Request hit" method=GET path=/locales/en/portal.json remote_ip=85.245.39.215
time="2023-11-13T08:56:20Z" level=trace msg="Replied (status=200)" method=GET path=/locales/en/portal.json remote_ip=85.245.39.215
time="2023-11-13T08:56:20Z" level=trace msg="Request hit" method=GET path=/api/state remote_ip=85.245.39.215
time="2023-11-13T08:56:20Z" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=85.245.39.215
time="2023-11-13T08:56:24Z" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:24Z" level=trace msg="Detected user filter is (&(|(uid=nuno)(mail=nuno))(objectClass=person))"
time="2023-11-13T08:56:24Z" level=trace msg="Performing user search" attr="[uid mail displayName]" base_dn="CN=users,CN=accounts,dc=internal,DC=xpto" deref=0 filter="(&(|(uid=nuno)(mail=nuno))(objectClass=person))" scope=2
time="2023-11-13T08:56:24Z" level=debug msg="Mark 1FA authentication attempt made by user 'nuno'" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:24Z" level=debug msg="Successful 1FA authentication attempt made by user 'nuno'" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:24Z" level=trace msg="Detected user filter is (&(|(uid=nuno)(mail=nuno))(objectClass=person))"
time="2023-11-13T08:56:24Z" level=trace msg="Performing user search" attr="[uid mail displayName]" base_dn="CN=users,CN=accounts,dc=net,DC=xpto" deref=0 filter="(&(|(uid=nuno)(mail=nuno))(objectClass=person))" scope=2
time="2023-11-13T08:56:24Z" level=trace msg="Computed groups filter is (&(member=uid=nuno,cn=users,cn=accounts,dc=internal,dc=xpto)(objectclass=groupofnames))"
time="2023-11-13T08:56:24Z" level=trace msg="Performing group search" attr="[cn]" base_dn="OU=groups,dc=net,DC=xpto" deref=0 filter="(&(member=uid=nuno,cn=users,cn=accounts,dc=net,dc=xpto)(objectclass=groupofnames))" scope=2
time="2023-11-13T08:56:24Z" level=trace msg="Profile details for user 'nuno' => groups: [], emails [nuno@mysite.com]" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:24Z" level=debug msg="Check authorization of subject username=nuno groups= ip=85.245.39.215 and object https://lab.mysite.com/ (method )."
time="2023-11-13T08:56:24Z" level=trace msg="ACL MISS Position 1 for subject username=nuno groups= ip=85.245.39.215 and object https://lab.mysite.com/ (method )"
time="2023-11-13T08:56:24Z" level=trace msg="ACL MISS Position 2 for subject username=nuno groups= ip=85.245.39.215 and object https://lab.mysite.com/ (method )"
time="2023-11-13T08:56:24Z" level=trace msg="ACL MISS Position 3 for subject username=nuno groups= ip=85.245.39.215 and object https://lab.mysite.com/ (method )"
time="2023-11-13T08:56:24Z" level=debug msg="No matching rule for subject username=nuno groups= ip=85.245.39.215 and url https://lab.mysite.com/ (method ) applying default policy"
time="2023-11-13T08:56:24Z" level=debug msg="Required level for the URL https://lab.mysite.com/ is 3" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:24Z" level=debug msg="Redirection URL https://lab.mysite.com/ is safe" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:24Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 145, avg execution duration: 1000, random delay ms: 33, total delay ms: 1033, actual delay ms: 888" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:25Z" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=85.245.39.215
time="2023-11-13T08:56:25Z" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=trace msg="Headers=GET /api/verify HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36\r\nHost: lab.mysite.com\r\nX-Original-Url: https://lab.mysite.com/\r\nX-Real-Ip: 127.0.0.1\r\nX-Forwarded-For: 127.0.0.1\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Host: lab.mysite.com\r\nX-Forwarded-Uri: /\r\nX-Forwarded-Ssl: on\r\nAccept-Encoding: gzip\r\nCf-Ray: 8255cd2789b89570-DUB\r\nCf-Visitor: {\"scheme\":\"https\"}\r\nSec-Ch-Ua: \"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Windows\"\r\nUpgrade-Insecure-Requests: 1\r\nDnt: 1\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\nSec-Fetch-Site: same-site\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-User: ?1\r\nSec-Fetch-Dest: document\r\nReferer: https://auth.mysite.com/\r\nAccept-Language: en\r\nCookie: DokuWiki=067bb9b7e5gbrsp2p47kl79dh7; authelia_session=EOqN3OZ_po%KN2Cy#E#F_sOvLglHiF6k\r\nPriority: u=0, i\r\nCdn-Loop: cloudflare\r\nCf-Connecting-Ip: 85.245.39.215\r\nCf-Ipcountry: PT\r\nVia: 1.1 lab.mysite.com\r\nX-Forwarded-Server: lab.mysite.com\r\n\r\n" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=trace msg="Using X-Original-URL header content as targeted site URL" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=trace msg="Inactivity report for user 'nuno'. Current Time: 1699865785, Last Activity: 1699865784, Maximum Inactivity: 7200." method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=trace msg="Checking if we need check the authentication backend for an updated profile for nuno." method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=debug msg="Check authorization of subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/ (method )."
time="2023-11-13T08:56:25Z" level=trace msg="ACL MISS Position 1 for subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/ (method )"
time="2023-11-13T08:56:25Z" level=trace msg="ACL MISS Position 2 for subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/ (method )"
time="2023-11-13T08:56:25Z" level=trace msg="ACL MISS Position 3 for subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/ (method )"
time="2023-11-13T08:56:25Z" level=debug msg="No matching rule for subject username=nuno groups= ip=127.0.0.1 and url https://lab.mysite.com/ (method ) applying default policy"
time="2023-11-13T08:56:25Z" level=info msg="Access to https://lab.mysite.com/ is forbidden to user nuno" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:25Z" level=trace msg="Replied (status=403)" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:26Z" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:26Z" level=trace msg="Headers=GET /api/verify HTTP/1.1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36\r\nHost: lab.mysite.com\r\nX-Original-Url: https://lab.mysite.com/favicon.ico\r\nX-Real-Ip: 127.0.0.1\r\nX-Forwarded-For: 127.0.0.1\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Host: lab.mysite.com\r\nX-Forwarded-Uri: /favicon.ico\r\nX-Forwarded-Ssl: on\r\nAccept-Encoding: gzip\r\nCf-Ray: 8255cd297cc59570-DUB\r\nCf-Visitor: {\"scheme\":\"https\"}\r\nSec-Ch-Ua: \"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\"\r\nDnt: 1\r\nSec-Ch-Ua-Mobile: ?0\r\nSec-Ch-Ua-Platform: \"Windows\"\r\nAccept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8\r\nSec-Fetch-Site: same-origin\r\nSec-Fetch-Mode: no-cors\r\nSec-Fetch-Dest: image\r\nReferer: https://lab.mysite.com/\r\nAccept-Language: en\r\nCookie: DokuWiki=067bb9b7e5gbrsp2p47kl79dh7; authelia_session=EOqN3OZ_po%KN2Cy#E#F_sOvLglHiF6k\r\nPriority: u=1, i\r\nCdn-Loop: cloudflare\r\nCf-Connecting-Ip: 85.245.39.215\r\nCf-Ipcountry: PT\r\nVia: 1.1 lab.mysite.com\r\nX-Forwarded-Server: lab.mysite.com\r\n\r\n" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:26Z" level=trace msg="Using X-Original-URL header content as targeted site URL" method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:26Z" level=trace msg="Inactivity report for user 'nuno'. Current Time: 1699865786, Last Activity: 1699865785, Maximum Inactivity: 7200." method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:26Z" level=trace msg="Checking if we need check the authentication backend for an updated profile for nuno." method=GET path=/api/verify remote_ip=127.0.0.1
time="2023-11-13T08:56:26Z" level=debug msg="Check authorization of subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/favicon.ico (method )."
time="2023-11-13T08:56:26Z" level=trace msg="ACL MISS Position 1 for subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/favicon.ico (method )"
time="2023-11-13T08:56:26Z" level=trace msg="ACL MISS Position 2 for subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/favicon.ico (method )"
time="2023-11-13T08:56:26Z" level=trace msg="ACL MISS Position 3 for subject username=nuno groups= ip=127.0.0.1 and object https://lab.mysite.com/favicon.ico (method )"
time="2023-11-13T08:56:26Z" level=debug msg="No matching rule for subject username=nuno groups= ip=127.0.0.1 and url https://lab.mysite.com/favicon.ico (method ) applying default policy"
time="2023-11-13T08:56:26Z" level=info msg="Access to https://lab.mysite.com/favicon.ico is forbidden to user nuno" method=GET path=/api/verify remote_ip=127.0.0.1
```

### Logs (Proxy / Application)

```shell
N/A
```

### Documentation

N/A

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
