### ISSUE TITLE
Unable to setup stand-alone configuration for testing.

### ISSUE THREAD

**Issue by Roiki-design** [authelia/authelia#634]
Im trying to integrate authelia into a mobile server running centos7 that serves a web-based user interface. The trick is that this is an IoT type setup with IP coming from DHCP on a random network and no domains pointing to it. Bare metal install with nginx and with file databases and user configs. Configs are from the [deployment-dev guide](https://github.com/authelia/authelia/blob/master/docs/proxies/nginx.md).

The authelia itself works and i can connect to the auth portal if i only run the portal, in which case the login window shows and you can log in, at which point authelias logs show the server authenticatiing the user. And it stops there.

When i add the protected endpoint config to the mix(and set upstream to a demo site living at localhost:8000) the address tries to redirect, doesn't show the login portal,  logs show "is not authorized user"(logs below)  and then returns the error_page 401 from `auth.conf`. which either is a url that doesn't work without DNS or an IP that causes a redirect loop.

Is this kind of use case even supported or possible to make it work?

> `TRAC[0004] Request hit                                   method=GET path=/api/verify remote_ip=192.168.3.35
TRAC[0004] Headers=GET /api/verify HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
Host: 192.168.2.136
X-Original-Url: https://192.168.2.136/
X-Real-Ip: 192.168.3.35
X-Forwarded-For: 192.168.3.35
X-Forwarded-Proto: https
X-Forwarded-Uri: /
X-Forwarded-Ssl: on
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-gb
Accept-Encoding: gzip, deflate, br
  method=GET path=/api/verify remote_ip=192.168.3.35
ERRO[0004] Access to https://192.168.2.136/ is not authorized to user   method=GET path=/api/verify remote_ip=192.168.3.35 stack="/opt/authelia/internal/handlers/handler_verify.go:242                         VerifyGet\n/opt/authelia/internal/middlewares/authelia_context.go:46                     AutheliaMiddleware.func1.1\n/home/admin/work/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/home/admin/work/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/home/admin/work/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/home/admin/work/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/home/admin/work/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                                    goexit"
TRAC[0004] Replied (status=401)                          method=GET path=/api/verify remote_ip=192.168.3.35
`

Config.yml is below:

```

host: 127.0.0.1
port: 9091
logs_level: trace
jwt_secret: secret
default_redirection_url: https://127.0.0.1:8000/

totp:
  issuer: authelia.com

authentication_backend:
   file:
     path: /etc/authelia/users/users_database.yml


access_control:
  default_policy: two_factor


session:

  name: authelia_session
  secret: secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes

  domain: example.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:

   local:
     path: /opt/authelia/database/authelia.db

notifier:

  smtp:
    username: test
    password: password
    host: 127.0.0.1
    port: 1025
    sender: admin@example.com

```
