### ISSUE TITLE
Redirect Timeout

### ISSUE THREAD

**Issue by joseftsch** [authelia/authelia#635]
Dear knowledgeable Authelia people :)

I tried all sorts of different configurations during the last couple of weeks but I am a bit lost ...

When I run my docker-compose (see below) and access the domain ide.exmaple.com from the public Internet I am redirected to authelia just fine (auth and redirect afterwards works perfectly fine) and can then reach the IDE app.
When I do that (ide.exmaple.com) from my internal network (home wifi; docker server also lives there) I am redirected to authelia (URL https://auth.example.com/?rd=https%3A%2F%2Fide.example.com%2F) but then the loading indicator keeps spinning and Chrome dev tools display TIMEOUT after some time during loading of some js files.

I am suspecting some redirect issue along with some network issue (maybe?) ... Can you please help me with that? Not even sure if this is a Authelia or more a Traefik issue tbh ...

I have the following files in use:
**docker-compose.yml**

```
version: "3.4"
services:
  traefik:
    image: "traefik:v2.1"
    container_name: traefik
    restart: unless-stopped
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik.toml:/traefik.toml" # Traefik configuration file
      - "./acme.json:/acme.json" # certificate stuff
      - "./tls:/tls" # dynamic tls config
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # access docker socket
  ide:
    image: containous/whoami:latest
    container_name: ide
    restart: unless-stopped
    ports:
      - "3000:80"
    container_name: ide
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ide.rule=Host(`ide.example.com`)"
      - "traefik.http.routers.ide.tls=true"   
      - "traefik.http.routers.ide.tls.options=default"
      - "traefik.http.routers.ide.tls.certresolver=le"
      - "traefik.http.routers.ide.middlewares=ide-auth@docker"
      - "traefik.http.routers.ide.entrypoints=web-secure"
      - "traefik.http.middlewares.ide-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.example.com"
      - "traefik.http.middlewares.ide-auth.forwardauth.trustForwardHeader=true"
      - "namespace=ide"
  authelia:
    image: authelia/authelia:master
    container_name: authelia
    restart: unless-stopped
    volumes:  
      - "./authelia/config.minimal.yml:/etc/authelia/configuration.yml:ro"
      - "./authelia/users_database.yml:/etc/authelia/users_database.yml:rw"
    environment:
      - TZ="Europe/Vienna"
      - NODE_TLS_REJECT_UNAUTHORIZED=1
      - AUTHELIA_JWT_SECRET=secretstuff
      - AUTHELIA_SESSION_SECRET=secretstuff
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD=secretstuff
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.authelia.entrypoints=web-secure"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.example.com"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
    expose:
      - 9091
```
**config.minimal.yml:**
```
host: 0.0.0.0
port: 9091
logs_level: debug
# jwt_secret: supersecret # set via env
authentication_backend:
  file:
    path: /etc/authelia/users_database.yml
storage:
  local:
    path: /etc/authelia/storage
totp:
  issuer: example.com
access_control:
  default_policy: one_factor
regulation: 
  max_retries: 5
  find_time: 120
  ban_time: 180
session:
  name: authelia_session
  expiration: 604800000 # 1 week
  inactivity: 300000 # 5 minutes
  domain: example.com
default_redirection_url: https://google.com
notifier:
  smtp:
    username: info@example.com
    #password: pw set via AUTHELIA_NOTIFIER_SMTP_PASSWORD
    secure: true
    host: mail.example.com
    port: 25
    sender: auth@example.com
```
