### ISSUE TITLE
2FA (one time passwd) won't register 

### ISSUE THREAD

**Issue by gemorgan** [authelia/authelia#6366]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.10.6

### Description

One factor login works fine. 2FA (one time password) fails with popup error "There was a problem initiating the registration process".  This is completely fresh install, new mariaDB, new mariaDB user with full privs for the authelia DB. Running in docker on Unraid and custom network. 

### Reproduction

Navigate to authelia login page. Log in (which is successful) dropping user on the "requires 2FA" warning page with a Register Device link. Clicking the link causes the fail. 

### Expectations

I expect to have the 2FA email sent in order to set up an authenticator app. 

### Configuration (Authelia)

```yaml
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark
jwt_secret: "redacted"
default_redirection_url: https://authelia.somedomain.com/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: trace
  format: text
  file_path: /config/authelia.log
  keep_stdout: false

totp:
  disable: false
  issuer: Authelia
  algorithm: sha512
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain:
        - "authelia.somedomain.com"
      policy: bypass
    ## catch-all
    - domain:
        - "*.somedomain.com"
      subject:
        - "group:admins"
      policy: two_factor

session:
  name: authelia_session
  domain: somedomain.com
  same_site: lax
  secret: "redacted"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 2M
  redis:
    host: redis
    port: 6379
    password: "redacted"
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: "redacted"
  mysql:
    host: mariadb
    port: 3306
    database: authelia
    username: authelia
    password: "redacted"

notifier:
  disable_startup_check: false
  smtp:
    username: noreply@somedomain.com
    password: "redacted"
    host: mx.somedomain.com
    port: 587
    sender: noreply@somedomain.com
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: noreply@somedomain.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
...
```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2023-12-02T11:09:34-07:00" level=trace msg="Starting scan of directory  for certificates"
time="2023-12-02T11:09:34-07:00" level=trace msg="Finished scan of directory  for certificates"
time="2023-12-02T11:09:34-07:00" level=info msg="Storage schema is being checked for updates"
time="2023-12-02T11:09:34-07:00" level=info msg="Storage schema migration from 0 to 7 is being attempted"
time="2023-12-02T11:09:39-07:00" level=debug msg="Storage schema migrated from version 0 to 1"
time="2023-12-02T11:09:40-07:00" level=debug msg="Storage schema migrated from version 1 to 2"
time="2023-12-02T11:09:42-07:00" level=debug msg="Storage schema migrated from version 2 to 3"
time="2023-12-02T11:10:07-07:00" level=debug msg="Storage schema migrated from version 3 to 4"
time="2023-12-02T11:10:11-07:00" level=debug msg="Storage schema migrated from version 4 to 5"
time="2023-12-02T11:10:41-07:00" level=debug msg="Storage schema migrated from version 5 to 6"
time="2023-12-02T11:11:31-07:00" level=debug msg="Storage schema migrated from version 6 to 7"
time="2023-12-02T11:11:31-07:00" level=info msg="Storage schema migration from 0 to 7 is complete"
time="2023-12-02T11:11:31-07:00" level=debug msg="Notifier SMTP client attempting connection to smtp.somedomain.com:587"
time="2023-12-02T11:11:31-07:00" level=debug msg="Notifier SMTP client connected successfully"
time="2023-12-02T11:11:31-07:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: smtp.somedomain.com), attempting"
time="2023-12-02T11:11:31-07:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2023-12-02T11:11:31-07:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: PLAIN LOGIN"
time="2023-12-02T11:11:31-07:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2023-12-02T11:11:31-07:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2023-12-02T11:11:31-07:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2023-12-02T11:11:36-07:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-12-02T11:11:36-07:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-12-02T11:12:06-07:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-12-02T11:12:06-07:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-12-02T11:12:19-07:00" level=trace msg="Request hit" method=GET path=/ remote_ip="<nil>"
time="2023-12-02T11:12:19-07:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip="<nil>"
time="2023-12-02T11:12:19-07:00" level=trace msg="Request hit" method=GET path=/static/css/index.40feef90.css remote_ip="<nil>"
time="2023-12-02T11:12:19-07:00" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.40feef90.css remote_ip="<nil>"
time="2023-12-02T11:12:19-07:00" level=trace msg="Request hit" method=GET path=/static/js/index.fad9e36b.js remote_ip="<nil>"
time="2023-12-02T11:12:19-07:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.fad9e36b.js remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Request hit" method=GET path=/locales/en-US/portal.json remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en-US/portal.json remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Request hit" method=GET path=/locales/en/portal.json remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Replied (status=200)" method=GET path=/locales/en/portal.json remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Request hit" method=GET path=/manifest.json remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Replied (status=200)" method=GET path=/manifest.json remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip="<nil>"
time="2023-12-02T11:12:20-07:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip="<nil>"
time="2023-12-02T11:12:30-07:00" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip="<nil>"
time="2023-12-02T11:12:30-07:00" level=debug msg="Mark 1FA authentication attempt made by user 'someuser'" method=POST path=/api/firstfactor remote_ip="<nil>"
time="2023-12-02T11:12:30-07:00" level=debug msg="Successful 1FA authentication attempt made by user 'someuser'" method=POST path=/api/firstfactor remote_ip="<nil>"
time="2023-12-02T11:12:30-07:00" level=trace msg="Profile details for user 'someuser' => groups: [admins], emails [someuser@somedomain.com]" method=POST path=/api/firstfactor remote_ip="<nil>"
time="2023-12-02T11:12:30-07:00" level=trace msg="Timing Attack Delay successful: true, exec duration: 141, avg execution duration: 1000, random delay ms: 43, total delay ms: 1043, actual delay ms: 902" method=POST path=/api/firstfactor remote_ip="<nil>"
time="2023-12-02T11:12:31-07:00" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip="<nil>"
time="2023-12-02T11:12:31-07:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip="<nil>"
time="2023-12-02T11:12:31-07:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip="<nil>"
time="2023-12-02T11:12:31-07:00" level=trace msg="Request hit" method=POST path=/api/user/info remote_ip="<nil>"
time="2023-12-02T11:12:31-07:00" level=trace msg="Request hit" method=GET path=/api/configuration remote_ip="<nil>"
time="2023-12-02T11:12:31-07:00" level=trace msg="Available methods are [totp webauthn]" method=GET path=/api/configuration remote_ip="<nil>"
time="2023-12-02T11:12:31-07:00" level=trace msg="Replied (status=200)" method=GET path=/api/configuration remote_ip="<nil>"
time="2023-12-02T11:12:32-07:00" level=trace msg="Replied (status=200)" method=POST path=/api/user/info remote_ip="<nil>"
time="2023-12-02T11:12:36-07:00" level=trace msg="Request hit" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-12-02T11:12:36-07:00" level=trace msg="Replied (status=200)" method=GET path=/api/health remote_ip=127.0.0.1
time="2023-12-02T11:12:44-07:00" level=trace msg="Request hit" method=POST path=/api/secondfactor/totp/identity/start remote_ip="<nil>"
time="2023-12-02T11:12:44-07:00" level=error msg="error inserting identity verification for user 'someuser' with uuid 'redacted': sql: converting argument $3 type: cannot value model type 'model.IP' with value nil to driver.Value" method=POST path=/api/secondfactor/totp/identity/start remote_ip="<nil>" stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:65      (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:62 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15  Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25               SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35               SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16               SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                 (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                  (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                               (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                            (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                            (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                         goexit"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
