### ISSUE TITLE
Use wildcard resource

### ISSUE THREAD

**Issue by Joniator** [authelia/authelia#637]
I have a service that I want to hide behind one factor auth, but the services provides an API which requires an API token anyways, so I want to exclude it.

But I can't seem to get the pattern right. This is my setup:
```
access_control:
  default_policy: one_factor
  rules:
    - domain: example.com
      policy: bypass
      resources: 
        - "^/api"
```

I also tried `^/api/?.*`, `^/api/?.*$`, `^/api/.*`, but it always allows `example.com/api` and `example.com/api/`, but asks for auth for `example.com/api/resource` etc.

I can't seem to find any help on the regex capabilities, but in the sample config this looks like the right way to do it.

How can I achieve this without unblocking every endpoint?

**Comment by clems4ever** [comment]
Hello @Joniator , I've tested your configuration in unit tests and seems all fine from a code perspective. The problem is probably somewhere else but it's not clear yet from your description.

 added some trace logs in https://github.com/authelia/authelia/pull/638. If you use docker to run Authelia you can try the following image when available in few minutes and set the log level to trace: `docker pull authelia/authelia:troubleshoot-authorization` , it will give us more visibility on what's happening.

**Comment by nightah** [comment]
I have a similar rule setup for a number of services, here's an example:

```
# Rules for bypassing
    - domain: 'ci.example.com'
      resources:
        - '^/api.*$'
        - '^/assets.*$'
        - '^/avatar-cache.*$'
        - '^/bitbucket-scmsource-hook.*$'
        - '^/blue.*$'
        - '^/cli.*$'
        - '^/ghprbhook.*$'
        - '^/git.*$'
        - '^/github-webhook.*$'
        - '^/instance-identity.*$'
        - '^/jnlpJars.*$'
        - '^/jwt-auth.*$'
        - '^/mercurial.*$'
        - '^/project.*$'
        - '^/subversion.*$'
        - '^/userContent.*$'
        - '^/whoAmI.*$'
        - '^/.*/api.*$'
      policy: bypass
```

**Comment by Joniator** [comment]
I managed to fix it, it wasn't a problem with authelia but with me and the api.

The api simply redirected any call it didn't know to the main page (which requires auth) instead of returning an error text, so the regex works fine. Sorry for the trouble

**Comment by jonasteuwen** [comment]
Just for my understanding, is this suppose to work @clems4ever? I.e. data.website.com is one_factor, while all api calls shouldn't require authentication. It doesn't work, as the api endpoint also requires authentication. Would it require something like `^(?!api)` to exclude api calls from the main domain? 

```
access_control:
  default_policy: deny
  rules:
    - domain: data.website.com
      policy: one_factor
    - domain: data.website.com
      resources:
      - "^/api.*$"
      policy: bypass
```
