### ISSUE TITLE
Failing http-post requests because of automatic preflight-requests

### ISSUE THREAD

**Issue by rostchri** [authelia/authelia#648]
We are using traefik 2.x and authelia using forwardAuth in traefik, which is working fine for many internal websites now... 

But we have one website (behind traefik/authelia) which is doing a 
javascript-XMLHttpRequest() against an other http-rest-api-site 
(running behind traefik/authelia too) using:

```javascript
var url = 'https://<http-rest-api-site>/....';
var xhr = new XMLHttpRequest();
xhr.open("POST", url, true);
xhr.withCredentials = true;
xhr.setRequestHeader("Content-Type", "application/json");
...
```

This will cause a browser to send a http-options-request (so called preflight)
see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS before the actual  http-post-request.
This http-options-request can't contain the credentials/cookies (by definition), 
so traefik/authelia will always responds with an HTTP-302 (redirect), which is not allowed as answer for a preflight so the browser will completely fail here ...

We are using other requests (get) too. These reqeusts are working fine, so I think we have
set everything related to CORS in a proper way ...

We are wondering how this problem can be solved?
- in general don't use authelia in front of the http-rest-api-site (using access-tokens instead)?
- define more complex traefik-rules to not use forwardAuth/authelia if a preflight/http-options-request is detected (how to define such a traefik-rule?)
- maybe a function in authelia to detect if an http-options-request is done?

Maybe I'm completely wrong here, but perhaps you have an idea here?

**Comment by clems4ever** [comment]
Hello @rostchri , thank you for reporting. That's an interesting case and your analysis seems completely right. Regarding the proposed solutions:

1/ Authelia should be usable in any case and using a access token seems like a workaround to me.
2/ Define more complex rules to avoid OPTIONS to go through Authelia seems like the best workaround for now and as long as Authelia does not support the use case. But I'm for Authelia supporting it and keep the integration layer minimal. I don't know how to define such rules though but there seems to exist a `Method` matcher that you could leverage to do what you want as a workaround: https://docs.traefik.io/v2.0/routing/routers/.
3/ I vote for a generic option in the ACLs. Why not add a `method` attribute to the rules that could be set to OPTIONS? That way we could apply a `bypass` policy for OPTIONS request targeting a specific backend.

I'll put option 3 in my todo if other maintainers agree with the proposal but in the meantime you can check how you can bypass Authelia for that specific request.

**Comment by clems4ever** [comment]
@nightah , @james-d-elliott , what's your opinion on the above proposal?

**Comment by nightah** [comment]
I’m for option 3 too.

Having said that, are these websites hosted as containers or own their own servers?

Could you not bypass that site from the IP address of the originating service? Even if they’re containers, perhaps by either hardcoding that specific containers IP or bypassing the whole subnet (less favourable).

**Comment by james-d-elliott** [comment]
I agree on option 3. Additionally for your information you should be able configure Traefik 2 to completely skip Authelia in this situation. 

K8S CRD IngressRoute Example:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: example
  namespace: default
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`example.example.com`) && Method(`GET`, `POST`, `PUT`, `DELETE`, `PATCH`)
      kind: Rule
      middlewares:
        - name: compress
          namespace: default
        - name: authelia
          namespace: default
      services:
        - name: example
          port: 80
    - match: Host(`example.example.com`)
      kind: Rule
      middlewares:
        - name: compress
          namespace: default
      services:
        - name: example
          port: 80
```
