### ISSUE TITLE
user not found in user_database.yml

### ISSUE THREAD

**Issue by simonwibberley** [authelia/authelia#6558]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.18.0

### Description

Occasionally, when a new user X is added to the user_database.yml a different user A will report they are unable to log in. On inspected the log A is reported to be not found, however are clearly existent in the file. The situation can be recovered by modifying user A name, then back again.

### Reproduction

This doesn't always occur, as such I can't provide deterministic steps to recreate. 

### Configuration (Authelia)

```yaml
---
theme: light

jwt_secret: XXX

#default_redirection_url: https://home.example.com/

## Set the default 2FA method for new users and for when a user has a preferred method configured that has been
## disabled. This setting must be a method that is enabled.
## Options are totp, webauthn, mobile_push.
default_2fa_method: "totp"

##
## Server Configuration
##
server:

  ## The address to listen on.
  host: 0.0.0.0

  ## The port to listen on.
  port: 9091

  ## Set the single level path Authelia listens on.
  ## Must be alphanumeric chars and should not contain any slashes.
  path: ""

  ## Set the path on disk to Authelia assets.
  ## Useful to allow overriding of specific static assets.
  # asset_path: /config/assets/

  ## Enables the pprof endpoint.
  enable_pprof: false

  ## Enables the expvars endpoint.
  enable_expvars: false

  ## Disables writing the health check vars to /app/.healthcheck.env which makes healthcheck.sh return exit code 0.
  ## This is disabled by default if either /app/.healthcheck.env or /app/healthcheck.sh do not exist.
  disable_healthcheck: false

    #headers:

    ## The CSP Template. Read the docs.
    # csp_template: ""

  ## Server Buffers configuration.
  # buffers:

    ## Buffers usually should be configured to be the same value.
    ## Explanation at https://www.authelia.com/c/server#buffer-sizes
    ## Read buffer size adjusts the server's max incoming request size in bytes.
    ## Write buffer size does the same for outgoing responses.

    ## Read buffer.
    # read: 4096

    ## Write buffer.
    # write: 4096

  ## Server Timeouts configuration.
  # timeouts:

    ## Read timeout.
    # read: 2s

    ## Write timeout.
    # write: 2s

    ## Idle timeout.
    # idle: 30s

##
## Log Configuration
##
log:
  ## Level of verbosity for logs: info, debug, trace.
  level: info

  ## Format the logs are written as: json, text.
  format: text

  ## File path where the logs will be written. If not set logs are written to stdout.
  file_path: /var/log/authelia.log

  ## Whether to also log to stdout when a log_file_path is defined.
  # keep_stdout: false


##
## TOTP Configuration
##
## Parameters used for TOTP generation.
totp:
  ## Disable TOTP.
  disable: false

  ## The issuer name displayed in the Authenticator application of your choice.
  issuer: XXX

  ## The TOTP algorithm to use.
  ## It is CRITICAL you read the documentation before changing this option:
  ## https://www.authelia.com/c/totp#algorithm
  algorithm: sha1

  ## The number of digits a user has to input. Must either be 6 or 8.
  ## Changing this option only affects newly generated TOTP configurations.
  ## It is CRITICAL you read the documentation before changing this option:
  ## https://www.authelia.com/c/totp#digits
  digits: 6

  ## The period in seconds a one-time password is valid for.
  ## Changing this option only affects newly generated TOTP configurations.
  period: 30

  ## The skew controls number of one-time passwords either side of the current one that are valid.
  ## Warning: before changing skew read the docs link below.
  skew: 1
  ## See: https://www.authelia.com/c/totp#input-validation to read
  ## the documentation.

  ## The size of the generated shared secrets. Default is 32 and is sufficient in most use cases, minimum is 20.
  secret_size: 32

webauthn:
  disable: true
  timeout: 60m
  display_name: XXX

  ## Conveyance preference controls if we collect the attestation statement including the AAGUID from the device.
  ## Options are none, indirect, direct.
  attestation_conveyance_preference: indirect

  ## User verification controls if the user must make a gesture or action to confirm they are present.
  ## Options are required, preferred, discouraged.
  user_verification: preferred


## NTP Configuration
## This is used to validate the servers time is accurate enough to validate TOTP.
ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:

  ## Password Reset Options.
  password_reset:
    ## Disable both the HTML element and the API for reset password functionality.
    disable: false

    custom_url: ""

  refresh_interval: always

  file:
     path: /etc/authelia/user_database.yml
     watch: true
     password:
       algorithm: argon2id
       iterations: 1
       key_length: 32
       salt_length: 16
       memory: 64
       parallelism: 8

password_policy:

  standard:
    enabled: false

    ## Require a minimum length for passwords.
    min_length: 12

    ## Require a maximum length for passwords.
    max_length: 0

    ## Require uppercase characters.
    require_uppercase: false

    ## Require lowercase characters.
    require_lowercase: false

    ## Require numeric characters.
    require_number: false

    ## Require special characters.
    require_special: false

  ## zxcvbn is a well known and used password strength algorithm. It does not have tunable settings.
  zxcvbn:
    enabled: true
    min_score: 4

access_control:
  default_policy: deny

 
  rules:

    XXX

session:
  name: authelia_session
  domain: XXX
  same_site: lax
  secret: 
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

  redis:
    host: 127.0.0.1
    port: 6379
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0



regulation:
  max_retries: 10
  find_time: 2m
  ban_time: 30m

storage:
  encryption_key: XXX

  postgres:
    host: 127.0.0.1
    port: 5432
    database: authelia
    schema: public
    username: authelia
    ## Password can also be set using a secret: https://www.authelia.com/c/secrets
    password: 
    timeout: 60s
    ssl:
      mode: disable
      root_certificate: disable
      certificate: disable
      key: disable

notifier:
  disable_startup_check: false
  #filesystem:
  #  filename: /etc/authelia/notification.txt


  smtp:
    host: smtp.gmail.com
    port: 587
    timeout: 60s
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2


...
```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2023-05-09T16:22:30Z" level=error msg="Unsuccessful 1FA authentication attempt by user 'andy': user not found" method=POST path=/api/firstfactor remote_ip=139.184.223.218 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:266           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:54 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54           (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                            (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                             (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                    goexit"
time="2023-05-09T16:22:38Z" level=debug msg="Mark 1FA authentication attempt made by user 'andy'" method=POST path=/api/firstfactor remote_ip=139.184.223.218
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
