### ISSUE TITLE
OIDC callback is always HTTPS, even when entered as HTTP

### ISSUE THREAD

**Issue by Forceu** [authelia/authelia#6559]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

nginx/1.18.0

### Description

I am testing a local application, that has the callback set to `http://127.0.0.1:53842/oauth-callback`
Authelia however redirects the output after granting the login to `httpS://127.0.0.1:53842/oauth-callback`

According to the OIDC draft specs, http may be allowed:

> redirect_uri
> REQUIRED. Redirection URI to which the response will be sent. This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider, with the matching performed as described in Section 6.2.1 of [[RFC3986]](https://openid.net/specs/openid-connect-core-1_0.html#RFC3986) (Simple String Comparison). When using this flow, the Redirection URI SHOULD use the https scheme; however, it MAY use the http scheme, provided that the Client Type is confidential, as defined in Section 2.1 of OAuth 2.0, and provided the OP allows the use of http Redirection URIs in this case. The Redirection URI MAY use an alternate scheme, such as one that is intended to identify a callback into a native application.

This would be a problem for applications not running on a webserver, e.g. on the users device

My configuration is below.

I am not sure if Authelia itself is actually responsible for this or if the problem is caused by fosite. I opened an issue at their tracker as well: https://github.com/ory/fosite/issues/784

### Reproduction

- Create a client with a HTTP callback
- Get redirected to HTTPS

### Configuration (Authelia)

```
identity_providers:
  oidc:
    hmac_secret: xxxxxxx
    issuer_private_key: |
      -----BEGIN PRIVATE KEY-----
  xxxxxx
      -----END PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - "https://*.xxxxxx"
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: gokapi-dev
        description: Gokapi dev account
        secret: 'xxxxxxxx'
        sector_identifier: ''
        public: false
        authorization_policy: two_factor
        consent_mode: explicit
        pre_configured_consent_duration: 1w
        audience: []
        scopes:
          - openid
          - email
          - profile
          - groups
        redirect_uris:
          - http://127.0.0.1:53842/oauth-callback
        userinfo_signing_algorithm: none

```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2024-01-17T16:43:14+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2024-01-17T16:43:14+01:00" level=info msg="Log severity set to debug"
time="2024-01-17T16:43:14+01:00" level=debug msg="Registering client gokapi-dev with policy two_factor (two_factor)"
time="2024-01-17T16:43:14+01:00" level=info msg="Storage schema is being checked for updates"
time="2024-01-17T16:43:14+01:00" level=info msg="Storage schema is already up to date"
time="2024-01-17T16:43:14+01:00" level=debug msg="Notifier SMTP client attempting connection to xxxxxxx:465"
time="2024-01-17T16:43:14+01:00" level=debug msg="Notifier SMTP client using submissions port 465. Make sure the mail server you are connecting to is configured for submissions and not SMTPS."
time="2024-01-17T16:43:14+01:00" level=debug msg="Notifier SMTP client connected successfully"
time="2024-01-17T16:43:14+01:00" level=debug msg="Notifier SMTP connection is already encrypted, skipping STARTTLS"
time="2024-01-17T16:43:14+01:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: PLAIN LOGIN"
time="2024-01-17T16:43:14+01:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2024-01-17T16:43:14+01:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2024-01-17T16:43:15+01:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2024-01-17T16:43:28+01:00" level=debug msg="Authorization Request with id '51d850f5-1bec-4920-8d8b-2c7288f5f050' on client with id 'gokapi-dev' is being processed" method=GET path=/api/oidc/authorization remote_ip=xxxx
time="2024-01-17T16:43:28+01:00" level=debug msg="Authorization Request with id '51d850f5-1bec-4920-8d8b-2c7288f5f050' on client with id 'gokapi-dev' using consent mode 'explicit' proceeding to generate a new consent session" method=GET path=/api/oidc/authorization remote_ip=xxxxx
time="2024-01-17T16:43:28+01:00" level=debug msg="Authorization Request with id '51d850f5-1bec-4920-8d8b-2c7288f5f050' on client with id 'gokapi-dev' using consent mode 'explicit' authentication level 'two_factor' is sufficient for client level 'two_factor'" method=GET path=/api/oidc/authorization remote_ip=xxxxx
time="2024-01-17T16:43:28+01:00" level=debug msg="Authorization Request with id '51d850f5-1bec-4920-8d8b-2c7288f5f050' on client with id 'gokapi-dev' using consent mode 'explicit' is being redirected to 'https://auth.xxxxxxx/consent?id=21a6216c-01d3-4f37-ba1a-ba7398e7acf6'" method=GET path=/api/oidc/authorization remote_ip=xxxxxxx
time="2024-01-17T16:43:30+01:00" level=debug msg="Authorization Request with id 'f6475347-49f0-4704-94e4-2990a467f9d4' on client with id 'gokapi-dev' is being processed" method=GET path=/api/oidc/authorization remote_ip=xxxxxx
time="2024-01-17T16:43:30+01:00" level=debug msg="Authorization Request with id 'f6475347-49f0-4704-94e4-2990a467f9d4' on client with id 'gokapi-dev' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=xxxxx
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
