### ISSUE TITLE
Configure Access Control Via Environment Variables

### ISSUE THREAD

**Issue by darkpixelftw** [authelia/authelia#6574]
### Description

Enable configuring the access control list from the environment variables instead of hardcoded in a config file

### Use Case

As all other config options (except OpenID) can be done via the environment variables
As I don't use OpenID (not sure how niche I feature it is generally though), the only thing in my config.yml is is the access control list. Being able to remove this would improve portability and mean domain names aren't hardcoded in a config file. This also allows domains to be set through variables in a .env file, shared with other docker containers instead of being manually set for each compose file

### Details

I do not know how difficult it would be to do on a technical level but I believe this would be a good method for the end user:

take this example file-based configuration
```
access_control:
  default_policy: deny
  rules:
    - domain: auth.example.com
      policy: bypass
    - domain:
        - 'example.com'
        - 'subdomain1.example.com'
      policy: two_factor
    - domain:
        - 'subdomain2.example.com'
      policy: one_factor
```
With the suggested enhancement, it could be replaced with the following environment variables in docker:
```
environment:
 - AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY: deny # or bypass etc
 - AUTHELIA_ACCESS_CONTROL_RULES_DOMAIN_BYPASS: auth.example.com # comma seperated list of domains to bypass authelia
 - AUTHELIA_ACCESS_CONTROL_RULES_DOMAIN_TWO_FACTOR: example.com, subdomain1.example.com # comma seperated list of domains that need 2fa to access
 - AUTHELIA_ACCESS_CONTROL_RULES_DOMAIN_ONE_FACTOR: subdomain2.example.com # comma seperated list of domains that only need password to access
```
or you could replace subdomain1.example.com with subdoman1.${DOMAIN_VARIABLE} from a .env file for improved portability. There are enough time domain names come up in the config that it's worth replacing with a variable to be set from a single file to prevent mistakes and improve portability between systems like below:
```
environment:
 - AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY: deny # or bypass etc
 - AUTHELIA_ACCESS_CONTROL_RULES_DOMAIN_BYPASS: auth.${DOMAIN_VARIABLE} # comma seperated list of domains to bypass authelia
 - AUTHELIA_ACCESS_CONTROL_RULES_DOMAIN_TWO_FACTOR: ${DOMAIN_VARIABLE}, subdomain1.${DOMAIN_VARIABLE} # comma seperated list of domains that need 2fa to access
 - AUTHELIA_ACCESS_CONTROL_RULES_DOMAIN_ONE_FACTOR: subdomain2.${DOMAIN_VARIABLE} # comma seperated list of domains that only need password to access
```

### Documentation

A similar feature request: https://github.com/authelia/authelia/issues/870
They propose configuration via lables whereas I believe it would be better via environment variables like the other config options

Current docs show that nearly everything else can be set via environment variables: https://www.authelia.com/configuration/methods/environment/

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation
