### ISSUE TITLE
Can't register device

### ISSUE THREAD

**Issue by Tartiflette-glpi** [authelia/authelia#6590]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

2.11.1

### Description

Hello,
I'm trying to configure Authelia for my personnal network but i got an error when i'm registering the device
![Capture d’écran 2024-01-24 111055](https://github.com/authelia/authelia/assets/109726235/d1d4c6e5-0427-4ffe-aa19-800054fe6590)

![Capture d’écran 2024-01-24 111041](https://github.com/authelia/authelia/assets/109726235/8a1ce702-1d83-4fd4-aa59-c7f8793d8b40)
I checked my configuration.yml file but can't find where the problem is...
I'm using a gmail account for the notifier

> notifier:
>   disable_startup_check: true #true/false
>   smtp:
>     username: myaddress@gmail.com
>     password: mypassword
>     host: smtp.gmail.com
>     port: 587
>     sender: myaddress@gmail.com
>     identifier: localhost
>     subject: "[Authelia] 2FA Login"
>     startup_check_address: myaddress@gmail.com
>     disable_require_tls: false
>     disable_html_emails: false
>     tls:
>       skip_verify: false
>       minimum_version: TLS1.2

Do you have any idea ?

### Reproduction

I followed this tutorial: https://www.youtube.com/watch?v=4UKOh3ssQSU
based on these configuration files: https://dbt3ch.com/books/authelia-for-nginx-proxy-manager

### Configuration (Authelia)

```yaml
# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark
jwt_secret: 1234567890abcdefghifjkl #any text or number you want to add here to create jwt Token

default_redirection_url: https://google.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: yourdomain.com #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 
        - "auth.yourdomain.com" #This should be your authentication URL
      policy: bypass
    - domain: "yourdomain.com" #example domain to protect
      policy: one_factor
    - domain: "sub1.yourdomain.com" #example subdomain to protect
      policy: one_factor
    - domain: "sub2.yourdomain.com" #example subdomain to protect
      policy: one_factor
    - domain: "*.yourdomain.com" #example to protect all subdomains under top-level domain
      policy: one_factor
      #add or remove additional subdomains as necessary. currenlty only supports ONE top-level domain
      #any time you add a new subdomain, you will need to restart the Authelia container to recognize the new settings/rules

session:
  name: authelia_session
  secret: unsecure_session_secret #any text or number you want to add here to create jwt Token
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: yourdomain.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this #added Dec 5 2021
  
notifier:
disable_startup_check: true #true/false
smtp:
username: myaddress@gmail.com
password: mypassword
host: smtp.gmail.com
port: 587
sender: myaddress@gmail.com
identifier: localhost
subject: "[Authelia] 2FA Login"
startup_check_address: myaddress@gmail.com
disable_require_tls: false
disable_html_emails: false
tls:
skip_verify: false
minimum_version: TLS1.2
...
```

### Build Information

```shell
-bash: authelia : commande introuvable
```

### Logs (Authelia)

```shell
time="2024-01-24T11:31:19+01:00" level=debug msg="Sending an email to user myuser (myaddress@outlook.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip=192.168.1.254

time="2024-01-24T11:31:19+01:00" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:587"

time="2024-01-24T11:31:19+01:00" level=debug msg="Notifier SMTP client connected successfully"

time="2024-01-24T11:31:19+01:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: smtp.gmail.com), attempting"

time="2024-01-24T11:31:19+01:00" level=debug msg="Notifier SMTP STARTTLS completed without error"

time="2024-01-24T11:31:19+01:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"

time="2024-01-24T11:31:19+01:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"

time="2024-01-24T11:31:19+01:00" level=warning msg="Notifier SMTP client encountered error during cleanup: use of closed network connection"

time="2024-01-24T11:31:19+01:00" level=error msg="error performing AUTH with the SMTP server: 535 5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials c6-20020a5d4f06000000b0033930068ca8sm8596908wru.21 - gsmtp" method=POST path=/api/secondfactor/totp/identity/start remote_ip=192.168.1.254 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:65       (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:106 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15   Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                 (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                  (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                   (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                                (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                             (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                             (*workerPool).getCh.func1\nruntime/asm_arm.s:831                                                             goexit"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
