### ISSUE TITLE
Option 'sector_identifier_uri' with value '': must be a URL with only the host component but appears to be invalid

### ISSUE THREAD

**Issue by zhzy0077** [authelia/authelia#6889]
### Version

v4.38.1, v4.38.0

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.7.6

### Description

Upgrading to 4.38.0 or later stops authelia from starting. With this error:
```
level=error msg="Configuration: identity_providers: oidc: clients: client 'xxx': 
option 'sector_identifier_uri' with value '': must be a URL with only the host component but appears to be invalid" 
stack="github.com/authelia/authelia/v4/internal/commands/context.go:312 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:183 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"

level=fatal msg="Can't continue due to the errors loading the configuration" 
stack="github.com/authelia/authelia/v4/internal/commands/context.go:315 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:183 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.0/command.go:968                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
```

### Reproduction

Here's the configuration that works for 4.37.x but not for 4.38.x
```
      - id: xxx
        description: xxx
        secret: ' <<redacted>>'
        sector_identifier: ''
        public: false
        authorization_policy: two_factor
        consent_mode: auto
        pre_configured_consent_duration: 1w
        scopes:
          - openid
          - profile
          - email
        redirect_uris:
          - <<redacted>>
```

### Expectations

Authelia should start, potentially with a few warnings asking me to update the config.

### Configuration (Authelia)

```yaml
- id: xxx
        description: xxx
        secret: ' <<redacted>>'
        sector_identifier: ''
        public: false
        authorization_policy: two_factor
        consent_mode: auto
        pre_configured_consent_duration: 1w
        scopes:
          - openid
          - profile
          - email
        redirect_uris:
          - <<redacted>>
```

### Build Information

```shell
docker build.
```

### Logs (Authelia)

```shell
See above.
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
