### ISSUE TITLE
Traefik - No X-Original-URL header detected

### ISSUE THREAD

**Issue by Akruidenberg** [authelia/authelia#691]
Which header is needed to fix this massage? This error is present with Traefik v1 and v2.

Edit (original title, should be body): how to fix the "No X-Original-URL header detected, fallback to combination of X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers" method=GET path=/api/verify remote_ip=*, time="2020-03-08T11:46:16Z" level=debug msg="No X-Original-URL header detected, fallback to combination of X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers" method=GET path=/api/verify remote_ip=* massage with traefik?

**Comment by clems4ever** [comment]
https://docs.authelia.com/deployment/supported-proxies/traefik1.x.html

**Comment by clems4ever** [comment]
@Akruidenberg , please rephrase the title so that it's comprehensible like other issues. Then, we'll help you out solving your issue.

**Comment by james-d-elliott** [comment]
@Akruidenberg your issue is typically one that can be ignored. If you really want to fix it then we need to know more about your setup. Could you answer the following questions:

1. Which Traefik version are you using?
2. How are you running Traefik and Authelia? Docker Compose? Just Docker? Something else?
3. Are you running a reverse proxy in front of Traefik?

**Comment by kassyss** [comment]
Hi, hi have these exact same logs from authelia used with Traefik. 

A incredible number of these : `time="2020-03-18T12:14:06Z" level=debug msg="No X-Original-URL header detected, fallback to combination of X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers" method=GET path=/api/verify remote_ip=xxx.xxx.xxx.xxx`

- Traefik image used : "traefik:v2.0"

- authelia : docker image "authelia/authelia:4" so version 4.7

Everything is working as expected but these numerous lines make authelia debugging very difficult.

About my configuration i am sure about it, i have spent hours to check it. It's similar to my old configuration with authelia 3.x but of course adapted to the new version of Authelia. Also i have modified Traefik forwardAuth address, before it ended with /%23/, no it's not anymore necessary.

Any hints on these Authelia logs?

Thank you in advance.

Best regards,

**Comment by james-d-elliott** [comment]
@kassyss As previously stated this can be ignored. It's a debug message for a reason. As long as you have X-Original-Url OR the X-Forwarded-* headers everything will work correctly. 

You can manually add the X-Original-Url header if you wish to remove the debug message though. See the docs: https://docs.traefik.io/v2.0/middlewares/headers/ Basically you want to add a custom request header of the full original URL.

**Comment by kassyss** [comment]
@james-d-elliott Hello,
Thank you very much for your explanations that now make everything clear to me. And also thanks a lot for the hint with Traefik custom header to make disappear this debug information from Authelia logs.

Wish you a good day :)

Best regards,

**Comment by rostchri** [comment]
I tried following traefik-settings in traefik 2.x with authelia 4.7.2:

```
  middlewares:
    authelia:
        forwardAuth:
            address: http://authelia.proxy-network:9091/api/verify?rd=https://authelia.<MYDOMAIN>/#/
            authRequestHeaders:
            - X-Original-URL
            - X-Fowarded-Proto
            - X-Forwarded-Host
            - X-Forwarded-URI
            authResponseHeaders:
            - Remote-User
            - Remote-Groups
            trustForwardHeader: true
```

Still got the message: "No X-Original-URL header detected, fallback to combination of X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers"

The following seems to be the traefik-default for authRequestHeaders:
```
            - X-Fowarded-Proto
            - X-Forwarded-Host
            - X-Forwarded-URI
```
Adding ``- X-Original-URL`` does not change anything ...

So for now the only option seems to ignore this message ....
