### ISSUE TITLE
lifespan_name cannot be changed do a different custom name

### ISSUE THREAD

**Issue by C8opmBM** [authelia/authelia#6939]
### Version

v4.38.3

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Description

As per https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#custom
I understand that the custom lifespan can be edited and assigned to different clients, therefore one can define multiple custom lifespans.

However, unless you use the exact `lifespan_name` name, authelia throws an error.
My use case: I want to configure multiple clients with different custom token lifespans (eg OCIS)

So if I put say:

```
    lifespans:
      access_token: 1h
      authorize_code: 1m
      id_token: 1h
      refresh_token: 90m
      custom:
        owncloud_web:  # needs to be exactly _lifespan_name_ in order to work, therefore only 
          access_token: 2d
          refresh_token: 3d
```

it throws errors, since it only accepts `lifespan_name`

```
      - client_id: ownCloud-web
        client_name: ownCloud web client
        public: true
        authorization_policy: two_factor
        redirect_uris:
          - https://cloud.REDACTED.net/
          - https://cloud.REDACTED.net/oidc-callback.html
          - https://cloud.REDACTED.net/oidc-silent-redirect.html
        lifespan: lifespan_name  #_owncloud_web_ errors out
        consent_mode: implicit
```

Did I misunderstand and there can be only 1 custom client? Or this is a bug indeed?
Thanks

### Reproduction

See above

### Build Information

```shell
authelia build-info
```

### Logs (Authelia)

```shell
log
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
