### ISSUE TITLE
Bypass all domains without apply the two-factor rules

### ISSUE THREAD

**Issue by Shad0w67** [authelia/authelia#6991]
### Version

v4.38.6, v4.38.5, v4.38.4, v4.38.3, v4.38.2, v4.38.1, v4.38.0

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

2.9.0-ls288

### Description

I use docker compose. I updated to the most recent versions of:

- reverse proxy swag to version: 2.9.0-ls288

- authelia to version: authelia: 4.38.6

However, authelia no longer does its job. When I enter the URL of the service in question for example; portainer.mysite.duckdns.org I arrive directly on the portainer connection page and not on the authelia authentication page.

Whereas I have the default rule: deny, then depending on the service, either bypass or two-factor. 
When I enter the direct authelia URL: auth.mysite.duckdns.org, I arrive on the authentication page, and the two-factor login works.
When i stop authelia service, and try to access, swag return me error 500

### Reproduction

no idea

### Configuration (Authelia)

```yaml
theme: 'dark'

default_2fa_method: ''
server:
  address: 'tcp://:9091/'
  disable_healthcheck: false
  headers:
    csp_template: ''

log:

  level: 'error'
  format: 'text'
  file_path: '/config/authelia.log'
  keep_stdout: false

telemetry:
  metrics:
    enabled: false
    address: 'tcp://:9959/metrics'

totp:
  disable: false
  issuer: 'mysite.duckdns.org'
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: '60 seconds'
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  user_verification: 'preferred'

identity_validation:
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
    jwt_secret: 'xiO3erMfYsUFS3ipA5W8Q0a0NB16o183TaHb0NNI5oOv60jg80GikvZgrVxKue2v'

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  refresh_interval: '5 minutes'

  file:
    path: '/config/users_database.yml'
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

access_control:
  default_policy: 'deny'

  networks:
    - name: internal
      networks:
        - 10.10.0.0/16
        - 192.168.1.0/24
  rules:
    - domain: '*.mysite.duckdns.org'
      policy: one_factor
      networks: internal

    - domain: 
      - 'nextcloud.mysite.duckdns.org'
      - 'collabora.mysite.duckdns.org'
      policy: bypass

    - domain: 
      - '*.mysite.duckdns.org'
      - 'portainer.mysite.duckdns.org'
      policy: two_factor


session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'mysite.duckdns.org'
      authelia_url: 'https://auth.mysite.duckdns.org'
      # default_redirection_url: 'https://duckdns.org'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: 'pQzrRC5HtZeYkOKLr1ohuPrlduJZTPuKOUxYRzJu4n2iZvpafrvS55RF7M2pFN5Q'
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp.free.fr:587'
    timeout: '5 seconds'
    username: 'myaccount@free.fr'
    password: 'myaccountpasswd'
    sender: "Authelia <myaccount@free.fr>"
    subject: '[Authelia] {title}'
    startup_check_address: 'myaccount@free.fr'
...
```

### Build Information

```shell
time="2024-03-21T19:12:20+01:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-03-21T19:12:20+01:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format=text keep_stdout=false
time="2024-03-21T19:12:20+01:00" level=debug msg="Process user information" gid=998 uid=998
time="2024-03-21T19:12:20+01:00" level=info msg="Authelia v4.38.6 is starting"
time="2024-03-21T19:12:20+01:00" level=info msg="Log severity set to debug"
time="2024-03-21T19:12:27+01:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-03-21T19:12:27+01:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format=text keep_stdout=false
time="2024-03-21T19:12:27+01:00" level=debug msg="Process user information" gid=998 uid=998
time="2024-03-21T19:12:27+01:00" level=info msg="Authelia v4.38.6 is starting"
time="2024-03-21T19:12:27+01:00" level=info msg="Log severity set to debug"
time="2024-03-21T19:16:56+01:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-03-21T19:16:56+01:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format=text keep_stdout=false
time="2024-03-21T19:16:56+01:00" level=debug msg="Process user information" gid=998 uid=998
time="2024-03-21T19:16:56+01:00" level=info msg="Authelia v4.38.6 is starting"
time="2024-03-21T19:16:56+01:00" level=info msg="Log severity set to debug"
```

### Logs (Authelia)

```shell
time="2024-03-21T19:12:20+01:00" level=info msg="Storage schema is being checked for updates"
time="2024-03-21T19:12:20+01:00" level=info msg="Storage schema migration from 0 to 15 is being attempted"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 0 to 1"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 1 to 2"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 2 to 3"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 3 to 4"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 4 to 5"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 5 to 6"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 6 to 7"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 7 to 8"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 8 to 9"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 9 to 10"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 10 to 11"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 11 to 12"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 12 to 13"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 13 to 14"
time="2024-03-21T19:12:20+01:00" level=debug msg="Storage schema migrated from version 14 to 15"
time="2024-03-21T19:12:20+01:00" level=info msg="Storage schema migration from 0 to 15 is complete"
time="2024-03-21T19:12:21+01:00" level=debug msg="Create Server Service (metrics) skipped"
time="2024-03-21T19:12:21+01:00" level=info msg="Startup complete"
time="2024-03-21T19:12:21+01:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2024-03-21T19:12:27+01:00" level=debug msg="Shutdown initiated due to process signal" signal=terminated
time="2024-03-21T19:12:27+01:00" level=info msg="Shutdown initiated"
time="2024-03-21T19:12:27+01:00" level=info msg="Shutdown complete"
time="2024-03-21T19:12:27+01:00" level=info msg="Storage schema is being checked for updates"
time="2024-03-21T19:12:27+01:00" level=info msg="Storage schema is already up to date"
time="2024-03-21T19:12:28+01:00" level=debug msg="Create Server Service (metrics) skipped"
time="2024-03-21T19:12:28+01:00" level=info msg="Startup complete"
time="2024-03-21T19:12:28+01:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2024-03-21T19:16:56+01:00" level=debug msg="Shutdown initiated due to process signal" signal=terminated
time="2024-03-21T19:16:56+01:00" level=info msg="Shutdown initiated"
time="2024-03-21T19:16:56+01:00" level=info msg="Shutdown complete"
time="2024-03-21T19:16:56+01:00" level=info msg="Storage schema is being checked for updates"
time="2024-03-21T19:16:56+01:00" level=info msg="Storage schema is already up to date"
time="2024-03-21T19:16:56+01:00" level=debug msg="Create Server Service (metrics) skipped"
time="2024-03-21T19:16:56+01:00" level=info msg="Startup complete"
time="2024-03-21T19:16:56+01:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2024-03-21T19:19:29+01:00" level=debug msg="Shutdown initiated due to process signal" signal=terminated
time="2024-03-21T19:19:29+01:00" level=info msg="Shutdown initiated"
time="2024-03-21T19:19:29+01:00" level=info msg="Shutdown complete"
```

### Documentation

portainer.subdomain.conf

## Version 2023/05/31

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name portainer.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app portainer;
        set $upstream_port 9000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_hide_header X-Frame-Options; # Possibly not needed after Portainer 1.20.0
    }

    location ~ (/portainer)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app portainer;
        set $upstream_port 9000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_hide_header X-Frame-Options; # Possibly not needed after Portainer 1.20.0
    }
}

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Looks like you didn't configure the server path correctly per the SWAG default snippets, if your configuration before was:

```yaml
server:
  port: 9091
  path: authelia
```

It should be:

```yaml
server:
  address: 'tcp://:9091/authelia'
```
