### ISSUE TITLE
Allow specifying cookies config with environment variables

### ISSUE THREAD

**Issue by jonasgeiler** [authelia/authelia#6993]
### Description

Right now the only way to configure the cookies is to use a config file, and since the cookies are required to be configured this is basically makes a config file the only possible configuration method and environment variables / secrets only useful **on top** of a config file.
Earlier versions of Authelia allowed me to completely configure everything using environment variables, which was super convenient since I could put those in my docker-compose.yml file, but with the deprecation of environment variables like `AUTHELIA_SESSION_DOMAIN` this isn't possible anymore and it sucks...

I have looked into the configuration library Authelia uses, `koanf`, and it actually supports configuring maps and arrays with environment variables, which would look like this: 
```env
AUTHELIA_COOKIES=[map[domain:example.com authelia_url:https://auth.example.com]]
```
Unfortunately Authelia doesn't seem to use this feature of `koanf` at this point in time :/

So, TL;DR: my feature request is to add support for setting maps and arrays in environment variables by using the `koanf` feature mentioned above.

### Use Case

Completely configure Authelia in a docker-compose.yml file, like below, without the need to manually create and maintain a config file:
```yaml
authelia:
  image: authelia/authelia:4.38.6
  container_name: authelia
  volumes:
    - authelia_config:/config
  environment:
    # ... a bunch of other envs ...
    AUTHELIA_COOKIES: '[map[domain:example.com authelia_url:https://auth.example.com]]'
    # ... a bunch of other envs ...
```

### Documentation

- https://github.com/knadh/koanf#reading-environment-variables
- https://github.com/knadh/koanf/blob/master/parsers/dotenv/dotenv_test.go

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
I'm afraid it is a lot harder than it sounds: https://github.com/james-d-elliott/koanf-example

These tests fail to produce any usable result Feel free to suggest any edits, if we get it working in any usable way we'd consider it. The only complication is if we feel it's something we can provide support for at that point 

Per #3249 and #6574 it's just not practical for us to maintain something like this.

**Comment by jonasgeiler** [comment]
@james-d-elliott Okay so I've looked into it further and also tried to get your example working for an hour or two but without success... I think those weird arrays and maps are only parsed when working with `dotenv.Parser()`, which is intended for `.env` files and not environment variables in general and doesn't work. I don't know. But it won't work without much modification :/

But on the other hand I've just looked into the config file filters feature of Authelia and it might work for my use case. I just have to use a custom Dockerfile that extends from Authelia's base image and create a little config file with templating enabled.
For future reference, and for other people looking for this:

- `authelia/configuration.yml`:
  ```yaml
  session:
    cookies:
      - domain: '{{ mustEnv "MY_DOMAIN" }}'
        authelia_url: '{{ mustEnv "MY_AUTHELIA_URL" }}'
  ```
- `authelia/Dockerfile`:
  ```dockerfile
  FROM authelia/authelia:4.38.6

  COPY ./configuration.yml /app/configuration.yml

  # Here I usually copy an initial users.yml file into the config folder,
  # but I'll leave it out for this demo.
  #COPY ./users.yml /config/users.yml

  ENV X_AUTHELIA_CONFIG_FILTERS="template" \
      X_AUTHELIA_CONFIG="/app/configuration.yml"
  ```
- `docker-compose.yml`:
  ```yaml
  authelia:
    build: ./authelia
    image: authelia/authelia:4.38.6
    container_name: authelia
    #volumes:
    #  - authelia_config:/config
    environment:
      # ... a bunch of other envs ...
      MY_DOMAIN: example.com
      MY_AUTHELIA_URL: https://auth.example.com
      # ... a bunch of other envs ...
  ```
