### ISSUE TITLE
Help needed with Authelia on Traefik 2

### ISSUE THREAD

**Issue by frenchvandal** [authelia/authelia#704]
Hello,

I am trying to set up Authelia with Traefik to secure access to some services. I have been doing some tests on the Traefik dashboard, the Containous whoami service and one of my actual services and each time I have the same issue: after a successful authentification, I remain on the Authelia login page and I am not redirected to the protected service.

This is a bit frustrating because, while being a newbie, the provided examples of Authelia/Traefik are pretty straightforward and I do not understand what I am missing.

Here is my Authelia Docker Compose file:

```yml
version: "3.7"
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: always
    labels:
      traefik.http.routers.authelia.rule: Host(`login.itsallsotireso.me`)
      traefik.http.routers.authelia.entrypoints: websecure
      traefik.http.routers.authelia.tls: true
      traefik.http.routers.authelia.tls.certresolver: letsencrypt
      traefik.http.routers.authelia.tls.domains[0].main: login.itsallsotireso.me
      traefik.http.routers.authelia.tls.options: modern@file
      #traefik.http.services.authelia.loadbalancer.server.port: 9091
    ports:
      - 9091:9091
    volumes:
      - ./lib:/var/lib/authelia
      - ./authelia:/etc/authelia/
    env_file:
      - ./env/authelia.env
    networks:
      - "traefik_traefik"

networks:
  traefik_traefik:
    external: true
```

The Authelia configuration file:

```yml
host: 0.0.0.0
port: 9091

logs_level: debug

default_redirection_url: https://itsallsotireso.me/

authentication_backend:
  file:
     path: /etc/authelia/users_database.yml
     password_options:
       algorithm: argon2id
       iterations: 1
       key_length: 32
       salt_length: 16
       memory: 1024
       parallelism: 8

access_control:
  default_policy: one_factor

  rules:
    - domain: whoami.itsallsotireso.me
      policy: one_factor

session:
  name: authelia_session
  expiration: 604800000
  inactivity: 300000
  domain: whoami.itsallsotireso.me

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
     path: /var/lib/authelia/db.sqlite3

notifier:
  smtp:
    username: REDACTED
    host: REDACTED
    port: 587
    sender: Authelia
```

The logs upon Authelia service start:
```
authelia    | time="2020-03-14T12:28:03Z" level=info msg="Logging severity set to debug"
authelia    | time="2020-03-14T12:28:03Z" level=debug msg="Notifier SMTP client initializing TLS configuration"
authelia    | time="2020-03-14T12:28:03Z" level=info msg="Selected public_html directory is ./public_html"
authelia    | time="2020-03-14T12:28:03Z" level=info msg="Authelia is listening on 0.0.0.0:9091 and do not use TLS"

```

Then the Authelia middleware in my Traefik Docker Compose file:

```yml
    labels:
      traefik.http.middlewares.authelia.forwardauth.trustforwardheader: true
      traefik.http.middlewares.authelia.forwardauth.authresponseheaders: X-Forwarded-User
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/verify?rd=https://login.itsallsotireso.me/
```

And finally my whoami Docker Compose file:

```yml
version: "3.7"

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.itsallsotireso.me`)
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.tls.certresolver: letsencrypt
      traefik.http.routers.whoami.tls.domains[0].main: whoami.itsallsotireso.me
      traefik.http.routers.whoami.tls.options: modern@file
      traefik.http.routers.whoami.middlewares: authelia
    networks:
      - "traefik_traefik"

networks:
  traefik_traefik:
    external: true
```

The authentification itself seems to be functional:
- when I use a wrong user or password, `I get the There was a problem. Username or password might be incorrect.` message.
- when I use the Authelia login page without a referrer, upon successful authentification, I am redirected to the default destination URL.

Here are the Traefik logs when I go to the whoami URL and try an auth:
- when I land on the login page after entering the whoami url: [gist](https://gist.github.com/frenchvandal/0768a59483517af817cb69fd38af7ede)
- when I try a successfull auth and remain on the login page: [gist](https://gist.github.com/frenchvandal/1acff258d465641de9c784074831f9bf)

I see this recurring error:
`traefik    | time="2020-03-14T11:24:57Z" level=debug msg="Remote error http://authelia:9091/api/verify?rd=https://login.itsallsotireso.me/. StatusCode: 302" middlewareType=ForwardedAuthType middlewareName=authelia@docker`

The Authelia logs:
```
authelia    | time="2020-03-14T12:30:34Z" level=debug msg="Credentials validation of user test is ok" method=POST path=/api/firstfactor remote_ip=xxx
authelia    | time="2020-03-14T12:30:34Z" level=debug msg="Mark authentication attempt made by user test" method=POST path=/api/firstfactor remote_ip=xxx
authelia    | time="2020-03-14T12:30:34Z" level=debug msg="Required level for the URL https://whoami.itsallsotireso.me/ is 1" method=POST path=/api/firstfactor remote_ip=xxx
authelia    | time="2020-03-14T12:30:34Z" level=debug msg="Redirection URL https://whoami.itsallsotireso.me/ is safe" method=POST path=/api/firstfactor remote_ip=xxx
authelia    | time="2020-03-14T12:30:34Z" level=debug msg="No X-Original-URL header detected, fallback to combination of X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers" method=GET path=/api/verify remote_ip=xxx
```

It seems that I am getting the same issue as #691 

Can you please give me some hints on how to debug this issue and figure out the problem (and a solution haha)? I can provide any extra info.

Thank you in advance for the kind help.
