### ISSUE TITLE
Not able to login unless using localhost

### ISSUE THREAD

**Issue by JacksonHub2** [authelia/authelia#7453]
### Version

v4.38.9, v4.38.8

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Reverse Proxy Version

nginx/1.27.0

### Description

There's found that the Authelia configuration with cookies settings, would impact the result of Authelia able to login or not.
Authelia configuration here is chosen to use simplified version here.

Here i'm putting the settings to a local-resolved domain for the test purpose, and add it into the below lines of configuration:
 ```
  cookies:
   - domain: 'auth.abc.com'
     authelia_url: 'https://auth.abc.com'
 ```

When starting Authelia, the user can't login into, where the authentication of username/password is success, it **can't bring user into the next page**.
**There's also no explicit error message in Web page notification, or from Authelia trace logs** 

![Screen Capture_select-area_20240623110224](https://github.com/authelia/authelia/assets/71587680/31c7e612-68a1-465a-8dac-80522f62d29b)

Here's the Authelia trace logs for the comparison, **after user click the 'Sign In' button**, in both failed and success scenario:

**Failed**

```
time="2024-06-23T13:46:41+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:46:41+08:00" level=debug msg="Mark 1FA authentication attempt made by user 'authelia'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:249 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:46:42+08:00" level=debug msg="Successful 1FA authentication attempt made by user 'authelia'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:271 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:46:42+08:00" level=trace msg="Profile details for user 'authelia' => groups: [admins dev], emails [authelia@authelia.com]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:135 handleRouter.FirstFactorPOST.func10" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:46:42+08:00" level=trace msg="Timing Attack Delay successful: true, exec duration: 170, avg execution duration: 1000, random delay ms: 2, total delay ms: 1002, actual delay ms: 832" caller="github.com/authelia/authelia/v4/internal/middlewares/timing_attack_delay.go:71 calculateActualDelay" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:46:42+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:46:42+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=GET path=/api/state remote_ip=127.0.0.1
time="2024-06-23T13:46:42+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/api/state remote_ip=127.0.0.1
```

**Success**
```
time="2024-06-23T13:37:07+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:37:07+08:00" level=debug msg="Mark 1FA authentication attempt made by user 'authelia'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:249 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:37:07+08:00" level=debug msg="Successful 1FA authentication attempt made by user 'authelia'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:271 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:37:07+08:00" level=trace msg="Profile details for user 'authelia' => groups: [admins dev], emails [authelia@authelia.com]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:135 handleRouter.FirstFactorPOST.func10" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:37:07+08:00" level=trace msg="Timing Attack Delay successful: true, exec duration: 154, avg execution duration: 1000, random delay ms: 66, total delay ms: 1066, actual delay ms: 912" caller="github.com/authelia/authelia/v4/internal/middlewares/timing_attack_delay.go:71 calculateActualDelay" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=POST path=/api/firstfactor remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=GET path=/api/state remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/api/state remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=POST path=/api/user/info remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=POST path=/api/user/info remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=GET path=/api/configuration remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Available methods are []" caller="github.com/authelia/authelia/v4/internal/handlers/handler_configuration.go:17 ConfigurationGET" method=GET path=/api/configuration remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/api/configuration remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=GET path=/static/js/portal.AuthenticatedView.CYciAk6z.js remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/static/js/portal.AuthenticatedView.CYciAk6z.js remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=GET path=/static/js/layouts.Minimal.gY5DCeCv.js remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/static/js/layouts.Minimal.gY5DCeCv.js remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=GET path=/static/js/portal.Authenticated.BIQxh389.js remote_ip=127.0.0.1
time="2024-06-23T13:37:08+08:00" level=trace msg="Replied (status=200)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/static/js/portal.Authenticated.BIQxh389.js remote_ip=127.0.0.1
```

Right now we can only login into Authelia, after modify the cookies domain and authelia_url, into **127.0.0.1**
 ```
  cookies:
   - domain: '127.0.0.1'
     authelia_url: 'https://127.0.0.1'
 ```
![Screen Capture_select-area_20240623142250](https://github.com/authelia/authelia/assets/71587680/bd6c5eb2-5a1f-450b-8796-4468d9392366)

Both Local 9091 port and Nginx reverse proxy was tried, and the scenario is the all same.

### Reproduction

0. OS is Debian latest 12
1. Download latest 4.38.9 version of Authelia application
2. Use this post of .yml configuration, to start Authelia
3. Ensure local machine have auth.abc.com write into hostfile, point to 127.0.0.1
4. User login into auth.abc.com page, using default authelia user account
5. It can't login into the next page, after few seconds of wait, the 'Sign In' button shows again

### Expectations

Auehtlia should able to bring user login into, instead of login page has no response with any login failure info..

### Configuration (Authelia)

```yaml
default_2fa_method: ''
server:
  address: 'tcp://:9091'
  disable_healthcheck: false
  headers:
    csp_template: ''

log:
  level: 'trace'

telemetry:
  metrics:
    enabled: false
    address: 'tcp://:9959/metrics'

totp:
  disable: false
  issuer: '127.0.0.1'
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

webauthn:
  disable: false
  timeout: '60 seconds'
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  user_verification: 'preferred'

identity_validation:
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
    jwt_secret: 'xiO3erMfYsUFS3ipA5W8Q0a0NB16o183TaHb0NNI5oOv60jg80GikvZgrVxKue2v'

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset:
    disable: false
    custom_url: ''
  refresh_interval: '5 minutes'

  file:
    path: 'users_database.yml'
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

password_policy:
  standard:
    enabled: false
    min_length: 1
    max_length: 0
    require_uppercase: false
    require_lowercase: false
    require_number: false
    require_special: false
  zxcvbn:
    enabled: false
    min_score: 3

access_control:
  default_policy: 'one_factor'

session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'auth.abc.com'
      authelia_url: 'https://auth.abc.com'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: 'pQzrRC5HtZeYkOKLr1ohuPrlduJZTPuKOUxYRzJu4n2iZvpafrvS55RF7M2pFN5Q'
  local:
    path: 'db.sqlite3'

notifier:
  disable_startup_check: false
  filesystem:
    filename: 'notification.txt'
...
```

### Build Information

```shell
Last Tag: v4.38.9
State: tagged clean
Branch: v4.38.9
Commit: 2798576ee25a56fd4c14814acd087b6e92f3978b
Build Number: 30034
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Jun 2024 19:47:16 +1000
Extra: 

Go:
    Version: go1.22.4
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
Already pasted in the Description
```

### Logs (Proxy / Application)

```shell
After click the 'Sign In' button, nginx access log is:
127.0.0.1 - - [23/Jun/2024:13:58:54 +0800] "POST /api/firstfactor HTTP/1.1" 200 15 "http://auth.abc.com:44300/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0" "-"
127.0.0.1 - - [23/Jun/2024:13:58:54 +0800] "GET /api/state HTTP/1.1" 200 92 "http://auth.abc.com:44300/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0" "-"

Other necessary logs have already posted.
```

### Documentation

https://www.authelia.com/configuration/session/introduction/
https://www.authelia.com/integration/proxies/nginx/

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
