### ISSUE TITLE
Enrollment of WebAuthn fails - mismatch in url

### ISSUE THREAD

**Issue by domingo13** [authelia/authelia#7533]
### Version

v4.38.9

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Description

When trying to enroll WebAuthn credentials it fails to due mismatch in hostname.

It seem to want the hostname to be "http://" but it receives "https://".

### Reproduction

Just enroll a WebAuthn credentials, nothing special.

### Configuration (Authelia)

```yaml
services:

  lldap:
    container_name: lldap
    hostname: lldap
    image: lldap/lldap:stable
    restart: unless-stopped
    networks:
      - auth-net
    ports:
    #  - 3890:3890
      - 17170:17170
    env_file:
      - stack.env
    volumes:
      - /opt/auth/lldap/data:/data
      - /opt/auth/lldap/secrets:/secrets

  redis:
      container_name: redis
      hostname: redis
      image: redis:latest
      restart: unless-stopped
      networks:
        - auth-net
      
      volumes:
        - /opt/auth/redis/data:/data

  authelia:
    container_name: authelia
    hostname: authelia
    image: authelia/authelia:4.38.9
    restart: unless-stopped
    networks:
      - auth-net
    ports:
      - 9091:9091
    env_file:
      - stack.env
    volumes:
      - /opt/auth/authelia/config:/config
      - /opt/auth/authelia/secrets:/secrets

networks:
  auth-net:
    



LLDAP_LDAP_BASE_DN=dc=xxx,dc=xx
UID=0
GID=0
LLDAP_JWT_SECRET_FILE=/secrets/JWT_SECRET
LLDAP_LDAP_USER_PASS_FILE=/secrets/LDAP_USER_PASS
AUTHELIA_SESSION_DOMAIN=auth.xxx.xx
AUTHELIA_TOTP_ISSUER=auth.xxx.xx
AUTHELIA_WEBAUTHN_DISPLAY_NAME=Authelia
AUTHELIA_NOTIFIER_SMTP_ADDRESS=submission://xxxx:587
AUTHELIA_NOTIFIER_SMTP_USERNAME=xxx
AUTHELIA_NOTIFIER_SMTP_SENDER="Authelia <authelia@dxxx>"
AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS=ldap://lldap:3890
AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN=dc=xxx,dc=xx
AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER=uid=admin,ou=people,dc=xxx,dc=xx
AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/JWT_SECRET
AUTHELIA_SESSION_SECRET_FILE=/secrets/SESSION_SECRET
AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/STORAGE_ENCRYPTION_KEY
AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/secrets/NOTIFIER_SMTP_PASSWORD
AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/secrets/AUTHENTICATION_BACKEND_LDAP_PASSWORD

---
theme: auto
default_2fa_method: totp
server:
  address: tcp://0.0.0.0:9091/
log:
  level: debug
totp:
  disable: false
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: false
  display_name: 'Authelia'
  timeout: 60s
  attestation_conveyance_preference: indirect
  user_verification: preferred
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    timeout: 5s
    start_tls: false
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
    additional_users_dn: ou=people
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: false
access_control:
  default_policy: two_factor
session:
  name: authelia_session
  redis:
    host: redis
    port: 6379
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
```

### Build Information

```shell
Last Tag: v4.38.9
State: tagged clean
Branch: v4.38.9
Commit: 2798576ee25a56fd4c14814acd087b6e92f3978b
Build Number: 30034
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Jun 2024 19:47:16 +1000
Extra: 

Go:
    Version: go1.22.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
2024-07-17T13:16:13.982995180Z time="2024-07-17T13:16:13Z" level=error msg="Error occurred validating a WebAuthn registration challenge for user 'admin': error comparing the response to the WebAuthn session data" error="Error validating origin (verification_error): Expected Values: [http://auth.xxx.xx], Received: https://auth.xxx.xx" method=POST path=/api/secondfactor/webauthn/credential/register remote_ip=x.x.x.x
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
