### ISSUE TITLE
Authelia with traefik 2.1.6 => Too many redirection

### ISSUE THREAD

**Issue by m4dm4rtig4n** [authelia/authelia#759]
Hi,

I am trying to configure authelia with traefik 2.1.6 but I am blocking on a redirection loop problem with jackett...

_I take jackett in exemple, but i have same problem with all domain._

When i'm connect directly in authelia, i'm correctly redirect to my "default_redirection_url" 
When i'm previously login, jackett work fine.
When i'm connect to http://jackett.exemple.com without login session, i'm enter in "too many redirection" with authelia error : Too big request header.

router.yml

```
# HTTP
http:
  routers:
    jackett-http:
      rule: "Host(`jackett.exemple.com`)"
      service: jackett
      passHostHeader: true
      entryPoints:
        - http
      middlewares:
        - authelia-jackett
    jackett-https:
      rule: "Host(`jackett.exemple.com`)"
      service: jackett
      passHostHeader: true
      entryPoints:
        - https
      tls:
        certResolver: mydomain
      middlewares:
        - authelia-jackett
  middlewares:
    authelia-jackett:
      forwardAuth:
        address: http://192.168.X.X:9091/api/verify?rd=https://jackett.exemple.com/#/
        authRequestHeaders:
        - X-Original-URL
        - X-Fowarded-Proto
        - X-Forwarded-Host
        - X-Forwarded-URI
        authResponseHeaders:
        - Remote-User
        - Remote-Groups
        trustForwardHeader: true
    https_redirect-jackett:
      redirectScheme:
        scheme: https
        permanent: true
  services:
    jackett:
      loadBalancer:
        servers:
          - url: "http://192.168.X.X:9117/"
```

When i look authelia log, redirect loop on rd in URL :

```
https://jackett.exemple.com/?rd=https%3A%2F%2Fjacket
t.exemple.com%2F%3Frd%3Dhttps%253A%252F%252Fjackett.exemple.com%252F%253Frd%253Dhttps%25253A%25252F%25252Fjackett.exemple.com%25252F%25253Frd%25253Dhttps%2525253A%2525252F%2525252Fjackett.exemple.com%2525252F%2525253F
rd%2525253Dhttps%252525253A%252525252F%252525252Fjackett.exemple.com%252525252F%252525253Frd%252525253Dhttps%25252525253A%25252525252F%25252525252Fjackett.exemple.com..........
```

Any idea ?

**Comment by james-d-elliott** [comment]
So the issue is how you have it configured. 

Try this:


```
# HTTP
http:
  routers:
    jackett-http:
      rule: "Host(`jackett.exemple.com`)"
      service: jackett
      passHostHeader: true
      entryPoints:
        - http
      middlewares:
        - authelia-jackett
    jackett-https:
      rule: "Host(`jackett.exemple.com`)"
      service: jackett
      passHostHeader: true
      entryPoints:
        - https
      tls:
        certResolver: mydomain
      middlewares:
        - authelia-jackett
  middlewares:
    authelia-jackett:
      forwardAuth:
        address: http://192.168.X.X:9091/api/verify?rd=https://authelia.exemple.com/#/
        authRequestHeaders:
        - X-Original-URL
        - X-Fowarded-Proto
        - X-Forwarded-Host
        - X-Forwarded-URI
        authResponseHeaders:
        - Remote-User
        - Remote-Groups
        trustForwardHeader: true
    https_redirect-jackett:
      redirectScheme:
        scheme: https
        permanent: true
  services:
    jackett:
      loadBalancer:
        servers:
          - url: "http://192.168.X.X:9117/"
```
