### ISSUE TITLE
BUG: `AUTHELIA_TOPT_DISABLE`  environment variable not respected in place of configuration.yml setting

### ISSUE THREAD

**Issue by MrChadMWood** [authelia/authelia#7606]
### Version

v4.38.9

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Description

AUTHELIA_TOPT_DISABLE env var is not being recognized in place of configuration.yml -> `totp.disable` setting.

```
authelia-1  | time="2024-07-30T21:22:25Z" level=warning msg="Configuration: configuration environment variable not expected: AUTHELIA_TOPT_DISABLE"
```

Based on my interpretation of how configuration settings should map to environment variables (https://www.authelia.com/configuration/methods/environment/) this is the incorrect behavior. The setting should be applied without error.

### Reproduction

Simply remove totp.disable from configuration.yml and try using an environment variable.

### Configuration (Authelia)

```yaml
certificates_directory: '/config/certificates/'
theme: 'light'

## Server Configuration
server:
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'  

## Password Policy Configuration.
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

## Access Control Configuration
access_control:
  default_policy: 'deny'
  rules:
    - domain: 'secure.demo.internal'
      policy: 'one_factor'
    - domain: 'unsecure.demo.internal'
      policy: 'bypass'

## Session Provider Configuration
session:
  cookies:
    - name: 'authelia_session'
      domain: 'demo.internal'
      authelia_url: 'https://auth.demo.internal'
  ## Default values
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
```

### Build Information

```shell
Last Tag: v4.38.9
State: tagged clean
Branch: v4.38.9
Commit: 2798576ee25a56fd4c14814acd087b6e92f3978b
Build Number: 30034
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Jun 2024 19:47:16 +1000
Extra:

Go:
    Version: go1.22.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2024-07-30T21:22:25Z" level=warning msg="Configuration: configuration environment variable not expected: AUTHELIA_TOPT_DISABLE"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
