### ISSUE TITLE
Error while deploying authelia

### ISSUE THREAD

**Issue by Eli-Src** [authelia/authelia#7655]
### Version

v4.38.10

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

3.1.1

### Description

I have 2 bugs in my docker logs. The first is the fatal warning that restarts the container and the second is the error that says that i have postgres and local configured in my config. But this is not the case. 

### Reproduction

My steps were the following:
1. Added authelia compose file as stack.
2. Created the directories and added the configs and secrets.
3. Started the containers with docker compose up -d

### Expectations

Should not crash.

### Configuration (Authelia)

```yaml
theme: dark
log.level=debug
totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 1
        memory: 2097152
        parallelism: 4
        key_length: 32
        salt_length: 16
      
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: service1.domain.com
      policy: bypass
    - domain: service2.domain.com
      policy: one_factor
    - domain: service3.domain.com
      policy: two_factor

session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  cookies:
    - domain: domain.com
      authelia_url: https://authelia.domain.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: '/config/db.sqlite3'

notifier:
  # For testing purpose, notifications can be sent in a file.
  # filesystem:
  #   filename: /config/notification.txt
  smtp:
    address: smtp://mail.domain.com
    timeout: 5s
    username: admin
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: password
    sender: authelia@authelia.com
```

### Build Information

```shell
Container is restarting and not available.
```

### Logs (Authelia)

```shell
time="2024-08-09T17:33:40+02:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-08-09T17:33:40+02:00" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2024-08-09T17:33:40+02:00" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
time="2024-08-09T17:33:40+02:00" level=error msg="Configuration: storage: option 'local', 'mysql' and 'postgres' are mutually exclusive but 'local' and 'postgres' have been configured" stack="github.com/authelia/authelia/v4/internal/commands/context.go:324 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
time="2024-08-09T17:33:40+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\nruntime/internal/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1695                                         goexit"
```

### Logs (Proxy / Application)

```shell
no logs because authelia restarts before it even comes to routing
```

### Documentation

authelia compose config.

...
authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /mnt/data/authelia/config:/config
    expose:
      - 9091
    restart: unless-stopped
    #healthcheck:
      ## In production the healthcheck section should be commented.
      #disable: true
    secrets: ['AUTHELIA_JWT_SECRET', 'AUTHELIA_SESSION_SECRET', 'AUTHELIA_STORAGE_PASSWORD', 'AUTHELIA_STORAGE_ENCRYPTION_KEY']
    environment:
      TZ: Europe/Amsterdam
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/AUTHELIA_JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/AUTHELIA_SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/run/secrets/AUTHELIA_STORAGE_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY'
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.rule: Host(`authelia.domain.com`)
      traefik.http.routers.authelia.entrypoints: https
      traefik.http.routers.authelia.tls: true
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/authz/forward-auth  # yamllint disable-line rule:line-length
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email  # yamllint disable-line rule:line-length
    networks:
      - proxy

secrets:
  AUTHELIA_JWT_SECRET:
    file: /mnt/data/authelia/secrets/jwt_secret.txt
  AUTHELIA_SESSION_SECRET:
    file: /mnt/data/authelia/secrets/session_secret.txt
  AUTHELIA_STORAGE_PASSWORD:
    file: /mnt/data/authelia/secrets/storage_password.txt
  AUTHELIA_STORAGE_ENCRYPTION_KEY:
    file: /mnt/data/authelia/secrets/encryption_key.txt

networks:
  proxy:
    external: true

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Sorry but this is a support issue, not a bug. You quite clearly have both local storage and postgres configured:

configuration.yml:

```yaml
storage:
  local:
    path: '/config/db.sqlite3'
```

authelia compose config:

```yaml
services:
  authelia:
    environment:
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/run/secrets/AUTHELIA_STORAGE_PASSWORD'
```
