### ISSUE TITLE
SMTP - Authelia does not atempt to authenticate on custom mail server

### ISSUE THREAD

**Issue by abaurens** [authelia/authelia#7664]
### Version

v4.38.10

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

2.11.0-ls314

### Description

It seems like Authelia does not try to authenticate to custom SMTP servers during startup check.

The connection is opened, but no authentication attempt was performed which blocks Authelia startup process before it finishes the startup check and results in the mail server closing the connection after 3 minutes of inactivity, crashing Authelia's app.

I'm using [mailu](https://mailu.io) as my custom mail server and it is installed as a docker container on the same host.

On mailu side, the log clearly states that the connection was closed for inactivity after 3 minutes and that no authentication was attempted.

The fact that the connection is established confirms that the server is reachable. And I also managed to setup the same kind of email notification on another service (nextcloud) using this same SMTP server.

The error does not change if I purposefully inputs wrong credentials for the SMTP server which seems to confirm the "no authentication attempts" hypothesis.

Truncated logs are given in the step by step reproduction below as well as complete ones to the end.

### Reproduction

1. Install a [mailu](https://mailu.io) server following [their guide](https://mailu.io/2024.06/setup.html#prepare-the-environment)

2. Create a user for Authelia to use in the mailu admin page.
On the left pannel, under the `Administration` section, go into `Domains`. Then, under the `manage` column for the domain, click the envelope icon to access the user management page.

3. Configure Authelia's `notifier.smtp` section to use this server.
```yaml
notifier:
disable_startup_check: false
smtp:
  address: 'smtp://mail.example.com:465'
  username: '<REDACTED>@example.com'
  # password: password is provided as a secret

  timeout: '10s'
  disable_require_tls: false
  sender: 'Authelia Notifier <auth@example.com>'
  subject: "[Notification example.com] {title}"
  startup_check_address: 'test@example.com'
```

4. Restart Authelia's container and check it's logs. The SMTP startup check should hang for 3 minutes before failing
Authelia's SMTP startup check log (trace level)
```
...

time="2024-08-05T00:52:51+02:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:115 doStartupChecks" provider=user
time="2024-08-05T00:52:51+02:00" level=debug msg="LDAP Supported OIDs. Control Types: none. Extensions: 1.3.6.1.4.1.4203.1.11.1" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:82 (*LDAPUserProvider).getServerSupportedFeatures"
time="2024-08-05T00:52:51+02:00" level=trace msg="Startup Check Completed Successfully" caller="github.com/authelia/authelia/v4/internal/commands/root.go:122 doStartupChecks" provider=user

time="2024-08-05T00:52:51+02:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:125 doStartupChecks" provider=notification
time="2024-08-05T00:52:51+02:00" level=trace msg="Creating Startup Check Client" caller="github.com/authelia/authelia/v4/internal/notification/smtp_notifier.go:113 (*SMTPNotifier).StartupCheck" hostname=example.com provider=notifier

... THE APP HANGS THERE FOR 3 MINUTES ...

time="2024-08-05T00:55:51+02:00" level=error msg="Error occurred running a startup check"
    caller="github.com/authelia/authelia/v4/internal/commands/root.go:128 doStartupChecks"
    error="failed to dial connection: EOF" provider=notification
    stack="github.com/authelia/authelia/v4/internal/commands/root.go:128
        doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88 
        (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985
        (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117
        (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041
        (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10
        main\nruntime/internal/atomic/types.go:194
        (*Uint32).Load\nruntime/asm_amd64.s:1695
        goexit"
```

In mailu's `front` container logs, we find the following line:
> ```
> Aug 05 01:10:57 submission-login: Info: Disconnected: Disconnected for inactivity. (no auth attempts in 180 secs): user=<>, rip=172.19.0.12, rport=51508, lip=172.19.0.11, lport=465, TLS handshaking
> ```

### Expectations

The startup check should pass nearly instantly and authelia should successfully start.

### Configuration (Authelia)

```yaml
---
###############################################################################
##                           Authelia Configuration                          ##
###############################################################################

theme: 'dark'
# default_2fa_method: ''

#
# Server Configuration
#
server:
  address: "tcp://:9091/authelia"
  disable_healthcheck: false
  tls:
    key: ''
    certificate: ''
    client_certificates: []
  headers:
    csp_template: ''

#
# Log Configuration
#
log:
  level: 'trace'
  format: 'text'
  file_path: '/config/authelia.log'
  keep_stdout: true

#
# Telemetry Configuration
#
telemetry:
  metrics:
    enabled: false

#
# TOTP Configuration
#
totp:
  disable: false
  issuer: 'example.com'
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  allowed_algorithms:
  - 'SHA1'
  allowed_digits:
  - 6
  - 8
  allowed_periods:
  - 30
  disable_reuse_security_policy: false

#
# WebAuthn Configuration
#
webauthn:
  disable: false
  timeout: '60 seconds'
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  user_verification: 'preferred'

#
# Identity Validation Configuration
#
identity_validation:
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'

#
# NTP Configuration
#
ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false

#
# Authentication Backend Provider Configuration
#
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m
  ldap:
    address: 'ldap://lldap:3890'
    implementation: 'lldap'
    timeout: '5s'
    start_tls: false
    base_dn: 'dc=ldap,dc=example,dc=com'
    additional_users_dn: 'ou=people'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))'
    additional_groups_dn: 'ou=groups'
    groups_filter: '(member={dn})'
    group_search_mode: 'filter'
    user: 'uid=admin,ou=people,dc=ldap,dc=example,dc=com'
    attributes:
      username: 'uid'
      display_name: 'displayName'
      mail: 'mail'
      group_name: 'cn'

#
# Password Policy Configuration.
#
password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

#
# Privacy Policy Configuration
#
# Parameters used for displaying the privacy policy link and drawer.
privacy_policy:
  enabled: false
  require_user_acceptance: false
  policy_url: ''

#
# Access Control Configuration
#
access_control:
  default_policy: 'deny'
  networks:
    - name: 'local'
      networks:
        - '192.168.1.0/24'
    - name: 'internal'
      networks:
        - '192.168.1.254'
  rules:
    <REDACTED>

#
# Session Provider Configuration
#
session:
  cookies:
    -
      name: 'authelia_session'
      domain: 'example.com'
      authelia_url: 'https://auth.example.com'
      same_site: 'lax'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'

#
# Regulation Configuration
#
regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

#
# Storage Provider Configuration
#
storage:
  mysql:
    address: 'tcp://mariadb:3306'
    database: 'authelia'
    username: 'authelia'
    timeout: '5 seconds'

#
# Notification Provider
#
notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp://mail.example.com:465'
    timeout: '10s'
    identifier: 'localhost'
    username: 'auth@example.com'
    disable_require_tls: false
    sender: 'Authelia Notifier <auth@example.com>'
    subject: "[Notification example.com] {title}"
    startup_check_address: 'test@example.com'
    disable_starttls: false
    disable_html_emails: false

#
# Identity Providers
#
identity_providers:
  oidc:
    jwks:
    -
      use: 'sig'
      key: {{ secret "/secrets/oidc/jwks/private.pem" | mindent 10 "|" | msquote }}
      certificate_chain: {{ secret "/secrets/oidc/jwks/public.crt" | mindent 10 "|" | msquote }}
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: 'public_clients_only'
    authorization_policies:
      custom_two_factors:
        default_policy: 'two_factor'
        rules:
          - policy: 'one_factor'
            subject: 'group:test'
    lifespans:
      access_token: '1 hour'
      authorize_code: '1 minute'
      id_token: '1 hour'
      refresh_token: '90 minutes'
    cors:
      endpoints:
         - 'authorization'
         - 'pushed-authorization-request'
         - 'token'
         - 'revocation'
         - 'introspection'
         - 'userinfo'
      allowed_origins_from_client_redirect_uris: false
    clients:
      <REDACTED>
...
```

### Build Information

```shell
Last Tag: v4.38.10
State: tagged clean
Branch: v4.38.10
Commit: b7d5e3ff29917bd0842c8509b4a8338d19f2934e
Build Number: 31324
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 04 Aug 2024 22:15:26 +1000
Extra: 

Go:
    Version: go1.22.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2024-08-12T01:20:50+02:00" level=trace msg="Starting scan of directory  for certificates" caller="github.com/authelia/authelia/v4/internal/utils/crypto.go:350 NewX509CertPool"
time="2024-08-12T01:20:50+02:00" level=trace msg="Dynamically generated users filter is (&(|(uid={input})(mail={input}))(objectClass=person))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:94 (*LDAPUserProvider).parseDynamicUsersConfiguration"
time="2024-08-12T01:20:50+02:00" level=trace msg="Dynamically generated users BaseDN is ou=people,dc=ldap,dc=example,dc=com" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:120 (*LDAPUserProvider).parseDynamicUsersConfiguration"
time="2024-08-12T01:20:50+02:00" level=trace msg="Detected user filter replacements that need to be resolved per lookup are: {input}=true" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:138 (*LDAPUserProvider).parseDynamicUsersConfiguration"
time="2024-08-12T01:20:50+02:00" level=trace msg="Dynamically generated groups BaseDN is ou=groups,dc=ldap,dc=example,dc=com" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:159 (*LDAPUserProvider).parseDynamicGroupsConfiguration"
time="2024-08-12T01:20:50+02:00" level=trace msg="Detected group filter replacements that need to be resolved per lookup are: input=false, username=false, dn=true" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:181 (*LDAPUserProvider).parseDynamicGroupsConfiguration"
time="2024-08-12T01:20:50+02:00" level=trace msg="Configuring with Mandatory TLS" caller="github.com/authelia/authelia/v4/internal/notification/smtp_notifier.go:60 NewSMTPNotifier" provider=notifier
time="2024-08-12T01:20:50+02:00" level=trace msg="Configuring Provider" caller="github.com/authelia/authelia/v4/internal/notification/smtp_notifier.go:87 NewSMTPNotifier" domain=example.com helo=localhost port=465 provider=notifier timeout=10 tls="&{<nil> <nil> [] map[] <nil> <nil> <nil> <nil> <nil> 0xc0009127b0 [] mail.example.com NoClientCert <nil> false [] false false [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] <nil> <nil> <nil> 771 772 [] false 0 <nil> {{0 0} 0 0 {{} 0} {{} 0}} [] []}"
time="2024-08-12T01:20:50+02:00" level=debug msg="Registering client GTqpnM15nZOjyeDICzeGwvRWW6TIyUPdHdGkZGb53XXdRwfvcMDwLgcy8Sh00G3I with policy one_factor (one_factor)" caller="github.com/authelia/authelia/v4/internal/oidc/store.go:40 NewMemoryClientStore"
time="2024-08-12T01:20:50+02:00" level=debug msg="Registering client 7BxHq6PketwRIDZpiioffaBY-QM.BNqz-UCtbo5CsnqkxU7XH8MIGzum5EjVEUxTJ3DdscIU with policy custom_two_factors (deny)" caller="github.com/authelia/authelia/v4/internal/oidc/store.go:40 NewMemoryClientStore"
time="2024-08-12T01:20:50+02:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:105 doStartupChecks" provider=storage
time="2024-08-12T01:20:50+02:00" level=info msg="Storage schema is being checked for updates" caller="github.com/authelia/authelia/v4/internal/storage/sql_provider.go:338 (*SQLProvider).StartupCheck"
time="2024-08-12T01:20:50+02:00" level=info msg="Storage schema is already up to date" caller="github.com/authelia/authelia/v4/internal/storage/sql_provider.go:356 (*SQLProvider).StartupCheck"
time="2024-08-12T01:20:50+02:00" level=trace msg="Startup Check Completed Successfully" caller="github.com/authelia/authelia/v4/internal/commands/root.go:112 doStartupChecks" provider=storage
time="2024-08-12T01:20:50+02:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:115 doStartupChecks" provider=user
time="2024-08-12T01:20:50+02:00" level=debug msg="LDAP Supported OIDs. Control Types: none. Extensions: 1.3.6.1.4.1.4203.1.11.1" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:82 (*LDAPUserProvider).getServerSupportedFeatures"
time="2024-08-12T01:20:50+02:00" level=trace msg="Startup Check Completed Successfully" caller="github.com/authelia/authelia/v4/internal/commands/root.go:122 doStartupChecks" provider=user
time="2024-08-12T01:20:50+02:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:125 doStartupChecks" provider=notification
time="2024-08-12T01:20:50+02:00" level=trace msg="Creating Startup Check Client" caller="github.com/authelia/authelia/v4/internal/notification/smtp_notifier.go:113 (*SMTPNotifier).StartupCheck" hostname=mail.example.com provider=notifier
time="2024-08-12T01:20:50+02:00" level=trace msg="Dialing Startup Check Connection" caller="github.com/authelia/authelia/v4/internal/notification/smtp_notifier.go:121 (*SMTPNotifier).StartupCheck" provider=notifier
time="2024-08-12T01:23:50+02:00" level=error msg="Error occurred running a startup check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:128 doStartupChecks" error="failed to dial connection: EOF" provider=notification stack="github.com/authelia/authelia/v4/internal/commands/root.go:128 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-08-12T01:23:50+02:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:135 doStartupChecks" provider=ntp
time="2024-08-12T01:23:50+02:00" level=trace msg="Startup Check Completed Successfully" caller="github.com/authelia/authelia/v4/internal/commands/root.go:146 doStartupChecks" provider=ntp
time="2024-08-12T01:23:50+02:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" caller="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
```

### Logs (Proxy / Application)

```shell
Aug 12 01:23:50 submission-login: Info: Disconnected: Disconnected for inactivity. (no auth attempts in 180 secs): user=<>, rip=172.19.0.12, rport=43760, lip=172.19.0.11, lport=465, TLS handshaking
```

### Documentation

The mail server I use is [mailu](https://mailu.io/2024.06/) and is installed as a docker container on the same host.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
