### ISSUE TITLE
After login the "Loading" page keeps refreshing every seconds

### ISSUE THREAD

**Issue by maxime1992** [authelia/authelia#7669]
### Version

v4.38.9

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

2.11.0 (I think, one of the latest)

### Description

I recently upgraded everything SWAG related and Authelia too.

Everything works perfectly on like 15 or 20 apps I've got but **one** app where after login in Authelia, it's stuck on the Authelia loading page. It shows the sort of vertical loader/spinner and I can see that the page is being reloaded in the browser like every second.

The URL looks like this:

https://myapp.mydomain.duckdns.org/authelia/?rd=https%3A%2F%2Fmyapp.mydomain.duckdns.org%2F

The app in question is [Kopia](https://kopia.io).

### Reproduction

Absolutely unsure but if you have an idea I'm happy to assist.

### Expectations

Have Authelia working for Kopia like all the others.

### Configuration (Authelia)

```yaml
server:
  address: "tcp://:9091/authelia"
  buffers:
    read: 4096
    write: 4096
log:
  level: info
  file_path: /config/logs/authelia.log
jwt_secret: my-secret
totp:
  issuer: authelia.mydomain.duckdns.org
authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 8
access_control:
  default_policy: deny
  rules:
    - domain:
      - mydomain.duckdns.org
      - "*.mydomain.duckdns.org"
      policy: two_factor
      subject:
      - 'user:my-user'
session:
  name: authelia_session
  secret: some-secret
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - domain: mydomain.duckdns.org
      authelia_url: https://authelia.mydomain.duckdns.org
      default_redirection_url: https://www.mydomain.duckdns.org
      name: authelia_session
      same_site: lax
      inactivity: 5m
      expiration: 1h
      remember_me: 1d
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: my-encryption-key
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
```
```


### Build Information


```shell
Last Tag: v4.38.9
State: tagged clean
Branch: v4.38.9
Commit: 2798576ee25a56fd4c14814acd087b6e92f3978b
Build Number: 30034
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Jun 2024 19:47:16 +1000
Extra: 

Go:
    Version: go1.22.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```
```


### Logs (Authelia)


```shell
I see this for Kopia


time="2024-08-12T19:41:30+02:00" level=warning msg="https://kopia.mydomain.duckdns.org/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor path_raw=/authelia/api/firstfactor remote_ip=192.168.1.254
```

But I have 2FA and I did enter my 2FA code before the issue showed up.
```


### Logs (Proxy / Application)


```shell
This is the block of logs that happens every second pretty much when Authelia keeps refreshing the loading page:


192.168.1.254 - - [12/Aug/2024:20:11:59 +0200] "GET /authelia/manifest.json HTTP/2.0" 304 0 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:11:59 +0200] "GET /authelia/locales/en/settings.json HTTP/2.0" 304 0 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:11:59 +0200] "GET /authelia/api/state HTTP/2.0" 200 128 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:11:59 +0200] "GET /authelia/api/configuration HTTP/2.0" 200 64 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:11:59 +0200] "POST /authelia/api/checks/safe-redirection HTTP/2.0" 200 34 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:11:59 +0200] "POST /authelia/api/user/info HTTP/2.0" 200 117 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "POST /authelia/api/checks/safe-redirection HTTP/2.0" 200 34 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET / HTTP/2.0" 499 0 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET / HTTP/2.0" 302 138 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET /authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F HTTP/2.0" 200 1084 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET /authelia/static/css/index.CUtFyfWw.css HTTP/2.0" 304 0 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET /authelia/static/js/index.R_EEPxQb.js HTTP/2.0" 304 0 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET /authelia/locales/en-GB/portal.json HTTP/2.0" 200 2 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET /authelia/locales/en-GB/settings.json HTTP/2.0" 200 2 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET /authelia/locales/en/portal.json HTTP/2.0" 304 0 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
192.168.1.254 - maxime [12/Aug/2024:20:12:00 +0200] "GET /authelia/locales/en/settings.json HTTP/2.0" 304 0 "https://kopia.dmy-domain.duckdns.org/authelia/?rd=https%3A%2F%2Fkopia.dmy-domain.duckdns.org%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
```
```


### Documentation


_No response_

### Pre-Submission Checklist


- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
