### ISSUE TITLE
LDAP group attribute is now case sensitive (unexpected/breaking change?)

### ISSUE THREAD

**Issue by aureq** [authelia/authelia#7791]
### Version

v4.38.9

### Deployment Method

Kubernetes

### Reverse Proxy

NGINX

### Reverse Proxy Version

n/a

### Description

Hi,

After upgrading to the latest version of Authelia (from `4.37.5` to `4.38.9`), it appears Authelia isn't processing the value `group_name` as it used to.
Previously `group_name_attribute: "CN"` was processed in a case insensitive way. However, after upgrading to `4.38.9`, group_name: 'CN' is now case sensitive.
I read (`BREAKING.md)[https://github.com/authelia/chartrepo/blob/master/charts/authelia/BREAKING.md] but it's not mentioned there.

With this attribute is now case sensitive, LDAP groups maybe be empty. I'm unsure if the change was intentional.
I'm also wondering if other attributes (`username`, `display_name`, `mail`, ...) may also be affected by this.

As a result, `rules` that rely on group membership to grand access and enforce specific requirement do not work anymore.
```yaml
    rules:
    - domain: 'pilot.k8s.local.example.net'
      resources:
        - '^/.*$'
      subject:
        - ["group:Administrators"]
      policy: 'two_factor'
```

🌿 For now, I've removed that value from my deployment so the default value is used instead. However, I'm opening this issue if this helps someone with the same problem.

### Reproduction

1. Setup an LDAP server
2. Create a LDAP user (`objectClass=inetOrgPerson`)
3. Create a LDAP group named `Administrators` (`objectclass=groupOfUniqueNames`) and add the user's `dn` to the attribute `uniqueMember`
4. Setup Authelia to user LDAP (See configs provided)
5. Open Authelia's login page to authenticate
6. Authentication works as expected ✅
7. Check the logs, the traces indicate that `groups=` is empty ❌
8. Access the website `pilot.k8s.local.example.net` which relies on group membership, 403 Access denied is returned. ❌

### Expectations

I think either the documentation could be updated to show which attribute is case sensitive, or the attribute should be reverted to case-insensitive perhaps.

### Configuration (Authelia)

Chart configuration (ldap section only, Version: 4.38.9, Chart: 0.9.5)
```yaml
configMap:
  authentication_backend:
    ldap:
      enabled: true
      implementation: 'activedirectory'
      address: 'ldap://ldap.identity-services.svc'
      timeout: '5 seconds'
      start_tls: false
     
      tls:
        server_name: ''
        skip_verify: false
        minimum_version: 'TLS1.2'
        maximum_version: 'TLS1.3'

      base_dn: 'DC=example,DC=net'
      additional_users_dn: 'OU=Users'
      users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=inetOrgPerson))" # (21)
      additional_groups_dn: 'OU=Authelia,OU=Groups'
      groups_filter: "(&(uniquemember={dn})(objectclass=groupOfUniqueNames))"
      permit_referrals: false
      permit_unauthenticated_bind: false
      permit_feature_detection_failure: false
      user: 'CN=authelia,OU=Services,DC=example,DC=net'

      password:
        disabled: false
        secret_name: ~
        value: ''
        path: 'authentication.ldap.password.txt'

      attributes:
        distinguished_name: ''
        username: 'uid'
        display_name: 'displayName'
        mail: 'mail'
        member_of: ''
        group_name: 'CN'
```

Chart configuration (ldap section only, Version: 4.37.5, Chart: 0.8.57)
```yaml
configMap:
  authentication_backend:
    ldap:
      enabled: true
      implementation: activedirectory
      url: "ldap://ldap.identity-services.svc"
      timeout: 5s
      start_tls: false
      tls:
        server_name: ""
        skip_verify: false
        minimum_version: TLS1.2
        maximum_version: TLS1.3

      base_dn: DC=example,DC=net # (19)
      username_attribute: "uid" # (20)
      additional_users_dn: OU=Users
      users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=inetOrgPerson))"
      additional_groups_dn: OU=Authelia,OU=Groups
      groups_filter: "(&(uniquemember={dn})(objectclass=groupOfUniqueNames))"
      group_name_attribute: "CN"
      mail_attribute: "mail"
      display_name_attribute: ""
      permit_referrals: false
      permit_unauthenticated_bind: false
      permit_feature_detection_failure: false
      user: CN=authelia,OU=Services,DC=example,DC=net
```

### Build Information

```
Last Tag: v4.38.9
State: tagged clean
Branch: v4.38.9
Commit: 2798576ee25a56fd4c14814acd087b6e92f3978b
Build Number: 30034
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Jun 2024 19:47:16 +1000
Extra: 

Go:
    Version: go1.22.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

Logs for Version: 4.38.9, Chart: 0.9.5 - Not showing groups with upper-case `group_name`
```
time="2024-08-31T20:33:31Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T20:33:31Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T20:33:31Z" level=debug msg="Mark 1FA authentication attempt made by user 'someuser'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:249 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T20:33:31Z" level=debug msg="Successful 1FA authentication attempt made by user 'someuser'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:271 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T20:33:31Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T20:33:31Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T20:33:31Z" level=trace msg="Computed groups filter is (&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:575 (*LDAPUserProvider).resolveGroupsFilter"
time="2024-08-31T20:33:31Z" level=trace msg="Performing group search" attributes="[CN]" base_dn="OU=Authelia,OU=Groups,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:412 (*LDAPUserProvider).getUserGroups" deref=0 filter="(&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))" mode=filter scope=2
time="2024-08-31T20:33:31Z" level=trace msg="Profile details for user 'someuser' => groups: [], emails [someuser@example.net]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:135 handleRouter.FirstFactorPOST.func10" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T20:33:31Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 35, avg execution duration: 1000, random delay ms: 78, total delay ms: 1078, actual delay ms: 1043" caller="github.com/authelia/authelia/v4/internal/middlewares/timing_attack_delay.go:71 calculateActualDelay" method=POST path=/api/firstfactor remote_ip=192.168.2.2
```

Logs for Version: 4.38.9, Chart: 0.9.5 - Showing groups with lower-case `group_name`
```
time="2024-08-31T21:41:12Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T21:41:12Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T21:41:12Z" level=debug msg="Mark 1FA authentication attempt made by user 'someuser'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:249 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T21:41:12Z" level=debug msg="Successful 1FA authentication attempt made by user 'someuser'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:271 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T21:41:12Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T21:41:12Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T21:41:12Z" level=trace msg="Computed groups filter is (&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:575 (*LDAPUserProvider).resolveGroupsFilter"
time="2024-08-31T21:41:12Z" level=trace msg="Performing group search" attributes="[cn]" base_dn="OU=Authelia,OU=Groups,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:412 (*LDAPUserProvider).getUserGroups" deref=0 filter="(&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))" mode=filter scope=2
time="2024-08-31T21:41:12Z" level=trace msg="Profile details for user 'someuser' => groups: [Users Administrators], emails [someuser@example.net]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:135 handleRouter.FirstFactorPOST.func10" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T21:41:12Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 99, avg execution duration: 1000, random delay ms: 78, total delay ms: 1078, actual delay ms: 979" caller="github.com/authelia/authelia/v4/internal/middlewares/timing_attack_delay.go:71 calculateActualDelay" method=POST path=/api/firstfactor remote_ip=192.168.2.2
```

Logs for Version: 4.37.5, Chart: 0.8.57 - showing groups with upper-case `group_name_attribute`
```
time="2024-08-31T20:18:03Z" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T20:18:03Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))"
time="2024-08-31T20:18:03Z" level=trace msg="Performing user search" attr="[uid mail displayName]" base_dn="OU=Users,DC=example,DC=net" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T20:18:03Z" level=debug msg="Mark 1FA authentication attempt made by user 'someuser'" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T20:18:03Z" level=debug msg="Successful 1FA authentication attempt made by user 'someuser'" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T20:18:03Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))"
time="2024-08-31T20:18:03Z" level=trace msg="Performing user search" attr="[uid mail displayName]" base_dn="OU=Users,DC=example,DC=net" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T20:18:03Z" level=trace msg="Computed groups filter is (&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))"
time="2024-08-31T20:18:03Z" level=trace msg="Performing group search" attr="[CN]" base_dn="OU=Authelia,OU=Groups,DC=example,DC=net" deref=0 filter="(&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))" scope=2
time="2024-08-31T20:18:03Z" level=trace msg="Profile details for user 'someuser' => groups: [Users Administrators], emails [someuser@example.net]" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T20:18:03Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 36, avg execution duration: 1000, random delay ms: 53, total delay ms: 1053, actual delay ms: 1017" method=POST path=/api/firstfactor remote_ip=192.168.2.2
```

### Logs (Proxy / Application)

```shell
n/a
```

### Documentation

https://www.authelia.com/configuration/first-factor/ldap/#group_name

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Please show the actual configs.

**Comment by aureq** [comment]
This `/configuration.yaml` returns empty groups.

```yaml
authentication_backend:
  password_reset:
    disable: true
    custom_url: ''
  ldap:
    implementation: 'rfc2307bis'
    address: 'ldap://ldap.identity-services.svc'
    timeout: '5 seconds'
    start_tls: false
    tls:
      server_name: ''
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
    base_dn: 'DC=example,DC=net'
    additional_users_dn: 'OU=Users'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=inetOrgPerson))'
    additional_groups_dn: 'OU=Authelia,OU=Groups'
    groups_filter: '(&(uniquemember={dn})(objectclass=groupOfUniqueNames))'
    permit_referrals: false
    permit_unauthenticated_bind: false
    permit_feature_detection_failure: false
    user: 'CN=authelia,OU=Services,DC=example,DC=net'
    attributes:
      distinguished_name: ''
      username: ''
      display_name: ''
      mail:  ''
      member_of:  ''
      group_name:  'CN'
```

At the logs...
```
time="2024-08-31T23:23:51Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T23:23:51Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T23:23:51Z" level=debug msg="Mark 1FA authentication attempt made by user 'someuser'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:249 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T23:23:51Z" level=debug msg="Successful 1FA authentication attempt made by user 'someuser'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:271 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T23:23:51Z" level=trace msg="Detected user filter is (&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T23:23:51Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=someuser)(mail=someuser))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T23:23:51Z" level=trace msg="Computed groups filter is (&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:575 (*LDAPUserProvider).resolveGroupsFilter"
time="2024-08-31T23:23:51Z" level=trace msg="Performing group search" attributes="[CN]" base_dn="OU=Authelia,OU=Groups,DC=example,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:412 (*LDAPUserProvider).getUserGroups" deref=0 filter="(&(uniquemember=uid=someuser,ou=Users,dc=example,dc=net)(objectclass=groupOfUniqueNames))" mode=filter scope=2
time="2024-08-31T23:23:51Z" level=trace msg="Profile details for user 'someuser' => groups: [], emails [someuser@example.net]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:135 handleRouter.FirstFactorPOST.func10" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T23:23:51Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 94, avg execution duration: 1000, random delay ms: 39, total delay ms: 1039, actual delay ms: 945" caller="github.com/authelia/authelia/v4/internal/middlewares/timing_attack_delay.go:71 calculateActualDelay" method=POST path=/api/firstfactor remote_ip=192.168.2.2
```

If I uneset `group_name` or set its value to `cn`, the groups are loaded correctly.

```yaml
authentication_backend:
  password_reset:
    disable: true
    custom_url: ''
  ldap:
    implementation: 'rfc2307bis'
    address: 'ldap://ldap.identity-services.svc'
    timeout: '5 seconds'
    start_tls: false
    tls:
      server_name: ''
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
    base_dn: 'DC=example,DC=net'
    additional_users_dn: 'OU=Users'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=inetOrgPerson))'
    additional_groups_dn: 'OU=Authelia,OU=Groups'
    groups_filter: '(&(uniquemember={dn})(objectclass=groupOfUniqueNames))'
    permit_referrals: false
    permit_unauthenticated_bind: false
    permit_feature_detection_failure: false
    user: 'CN=authelia,OU=Services,DC=example,DC=net'
    attributes:
      distinguished_name: ''
      username: ''
      display_name: ''
      mail:  ''
      member_of:  ''
      group_name:  'cn'
```

```
time="2024-08-31T23:28:55Z" level=trace msg="Detected user filter is (&(|(uid=aureq)(mail=aureq))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T23:28:55Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=menfin,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=aureq)(mail=aureq))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T23:28:55Z" level=debug msg="Mark 1FA authentication attempt made by user 'aureq'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:249 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T23:28:55Z" level=debug msg="Successful 1FA authentication attempt made by user 'aureq'" caller="github.com/authelia/authelia/v4/internal/handlers/response.go:271 markAuthenticationAttempt" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T23:28:55Z" level=trace msg="Detected user filter is (&(|(uid=aureq)(mail=aureq))(objectClass=inetOrgPerson))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:531 (*LDAPUserProvider).resolveUsersFilter"
time="2024-08-31T23:28:55Z" level=trace msg="Performing user search" attr="[uid mail displayName memberOf]" base_dn="OU=Users,DC=menfin,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:318 (*LDAPUserProvider).getUserProfile" deref=0 filter="(&(|(uid=aureq)(mail=aureq))(objectClass=inetOrgPerson))" scope=2
time="2024-08-31T23:28:55Z" level=trace msg="Computed groups filter is (&(uniquemember=uid=aureq,ou=Users,dc=menfin,dc=net)(objectclass=groupOfUniqueNames))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:575 (*LDAPUserProvider).resolveGroupsFilter"
time="2024-08-31T23:28:55Z" level=trace msg="Performing group search" attributes="[cn]" base_dn="OU=Authelia,OU=Groups,DC=menfin,DC=net" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider.go:412 (*LDAPUserProvider).getUserGroups" deref=0 filter="(&(uniquemember=uid=aureq,ou=Users,dc=menfin,dc=net)(objectclass=groupOfUniqueNames))" mode=filter scope=2
time="2024-08-31T23:28:55Z" level=trace msg="Profile details for user 'aureq' => groups: [Users Administrators], emails [aurelien@requiem.fr]" caller="github.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:135 handleRouter.FirstFactorPOST.func10" method=POST path=/api/firstfactor remote_ip=192.168.2.2
time="2024-08-31T23:28:55Z" level=trace msg="Timing Attack Delay successful: true, exec duration: 67, avg execution duration: 1000, random delay ms: 35, total delay ms: 1035, actual delay ms: 968" caller="github.com/authelia/authelia/v4/internal/middlewares/timing_attack_delay.go:71 calculateActualDelay" method=POST path=/api/firstfactor remote_ip=192.168.2.2
```
