### ISSUE TITLE
Set password expiration policy

### ISSUE THREAD

**Issue by tpemeja** [authelia/authelia#7799]
### Description

Implement a password expiration policy within Authelia to enhance account security by requiring users to change their passwords periodically.

### 1. System Administrator Configures Policy:
The system administrator configures Authelia with a password expiration policy, specifying parameters such as expiration interval (e.g., 90 days), grace period for password changes, and notification settings.

### 2. Authelia Monitors Password Ages:
Authelia continuously tracks the age of each user’s password based on the last update timestamp.

### 3. Notification to Users:
Authelia sends periodic reminders (e.g., 14 days, 7 days, and 1 day before expiration) to users whose passwords are nearing expiration.

### 4. User Changes Password:
The user receives a notification and logs into the system to update their password before the expiration date.

### 5. Password Successfully Updated:
Authelia validates the new password according to security guidelines (e.g., complexity requirements) and updates the user’s password record. The expiration counter resets.

### 6. Access Maintained:
The user continues to access services without interruption after updating the password.

### Details

The administrator sets the following parameters:

- **Expiration Interval:** Defines how long a password is valid before expiring (e.g., 90 days).
- **Grace Period:** Specifies the time allowed for a user to change their password after it has expired (e.g., 7 days).
- **Notification Settings:** Configures the schedule and content of notifications sent to users (e.g., email reminders 14 days, 7 days, and 1 day before expiration).
- **Security Requirements:** Sets the password complexity rules (e.g., minimum length, inclusion of special characters, numbers, and mixed case).
- **Action on Expiration:** Defines what happens when a password expires (e.g., restrict access, redirect to a password reset page).

### Configuration Example:
```yaml
password_policy:
  expiration_days: 90
  grace_period_days: 7
  notification_schedule:
    - 14 # days before expiration
    - 7
    - 1
  action_on_expiration:
    restrict_access: true
    redirect_to_reset_page: true
    display_warning: false
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation
