### ISSUE TITLE
authn_strategies only seems to use the last strategy

### ISSUE THREAD

**Issue by terrytw** [authelia/authelia#7986]
### Version

v4.38.15

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.8.4

### Description

```
access_control:
  rules:
  - domain:
    - 'example.com'
    resources:
    - '^/test(/.*)?$'
    subject:
    - 'group:admin'
    - 'group:user'
    policy: 'two_factor'

  - domain:
    - 'example.com'
    resources:
    - '^/file(/.*)?$'
    subject:
    - 'group:admin'
    - 'group:basic_auth'
    policy: 'one_factor'

server:
  address: 'tcp://:9091/auth'
  # disable_healthcheck: false
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
          - name: 'CookieSession'
```
I am using this server configuration. When my client send request without credentials, I got the following log:

```
time="2024-10-05T13:38:26-07:00" level=trace msg="Request hit" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:12 handleRouter.LogRequest.func40" method=GET path=/api/authz/forward-auth remote_ip=*.*.*.*
time="2024-10-05T13:38:26-07:00" level=debug msg="Check authorization of subject username= groups= ip=*.*.*.* and object https://example.com/file/1.txt (method GET)." caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:52 (*Authorizer).GetRequiredLevel"
time="2024-10-05T13:38:26-07:00" level=trace msg="ACL MISS Position 1 for subject username= groups= ip=*.*.*.* and object https://example.com/file/1.txt (method GET, policy two_factor)" caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:62 (*Authorizer).GetRequiredLevel"
time="2024-10-05T13:38:26-07:00" level=trace msg="ACL HIT Position 2 for subject username= groups= ip=*.*.*.* and object https://example.com/file/1.txt (method GET, policy one_factor)" caller="github.com/authelia/authelia/v4/internal/authorization/authorizer.go:57 (*Authorizer).GetRequiredLevel"
time="2024-10-05T13:38:26-07:00" level=info msg="Access to https://example.com/file/1.txt (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://example.com/auth?rd=https%3A%2F%2Fexample.com%2Ffile%2F1.txt&rm=GET" caller="github.com/authelia/authelia/v4/internal/handlers/handler_authz_impl_forwardauth.go:53 handleAuthzUnauthorizedForwardAuth" method=GET path=/api/authz/forward-auth remote_ip=*.*.*.*
time="2024-10-05T13:38:26-07:00" level=trace msg="Replied (status=401)" caller="github.com/authelia/authelia/v4/internal/middlewares/log_request.go:16 handleRouter.LogRequest.func40" method=GET path=/api/authz/forward-auth remote_ip=*.*.*.*
```

But based on https://www.authelia.com/reference/guides/proxy-authorization/#headerauthorization authelia should send out [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) header and a [401 Unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) status code. But I'm not seeing any of that in the log. 

Also https://www.authelia.com/reference/guides/proxy-authorization/#authn-strategies this part of the documentation seems to have some errors which further complicated things.

### Reproduction

Configuration is provided in above description. 

### Build Information

```shell
Last Tag: v4.38.15
State: tagged clean
Branch: v4.38.15
Commit: 0d312c5ef3b623ec6fa50b3cb475f632d3dc5f5e
Build Number: 33643
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Mon, 30 Sep 2024 21:24:54 +1000
Extra:

Go:
    Version: go1.23.1
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
Provided above
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
