### ISSUE TITLE
Enforcing Content Security Policy

### ISSUE THREAD

**Issue by kassyss** [authelia/authelia#815]
Hello,

I am actually working on enforcing security of my proxified containers by adding important security headers as CSP. CSP is not easy to implement but it's worth the pain.
For now i am focused on Authelia CSP as it's essential piece of the puzzle. To help me generate Authelia CSP i have used a helpful Firefox plugin : https://addons.mozilla.org/fr/firefox/addon/laboratory-by-mozilla/.

Here is my current configuration (Traefik yaml file) to implement this security headers:
```
http:
  middlewares:
    AutheliaHeaders:
      headers:
        sslRedirect: true
        stsPreload: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        contentSecurityPolicy: "default-src 'none'; connect-src 'self'; img-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
        referrerPolicy: "same-origin"
        featurePolicy: "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'self'"
```

Testing the security of my Authelia installation with https://securityheaders.com, i can get a A score, that is already good but... to make Authelia working as we can see in the CSP i needed to implement  script-src 'self' 'unsafe-inline' and that's not a good idea. 

I have found this interesting resource about how to include inline javascript but still being able to protect with more restrictive CSP (using nonce or hash): https://barryvanveen.nl/blog/47-how-to-prevent-the-use-of-unsafe-inline-in-csp

Just my 2 cents, i don't know about html/css/js dev at all :)

Have a nice day.

Best regards,
