### ISSUE TITLE
Upgrade from 4.38.16 to 4.38.17, SMTP authentication fails at startup.

### ISSUE THREAD

**Issue by mwinters-stuff** [authelia/authelia#8196]
### Version

v4.38.17

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Reverse Proxy Version

Latest

### Description

Upgrading authelia from 4.38.16 to 4.38.17, the authentication to smtp fails at startup.

Rolling back to the prior version succeeds.

Upgrade/Downgrade is done via the authelia helm chart, by upgrading the image tag.

### Reproduction

Upgrade with config as shown below

### Expectations

Authelia should startup properly.

### Configuration (Authelia)

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: authelia-winters-org-nz
    namespace: web-auth
spec:
    chart:
        spec:
            chart: authelia
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: authelia
            version: 0.9.9
    interval: 12h
    values:
        ## @formatter:off
        ## values.yaml
        ##
        ## Repository: authelia https://charts.authelia.com
        ## Chart: authelia
        ##
        ## This values file is a baseline for other values files.
        ## Version Override allows changing some chart characteristics that render only on specific versions.
        ## This does NOT affect the image used, please see the below image section instead for this.
        ## If this value is not specified, it's assumed the appVersion of the chart is the version.
        ## The format of this value  is x.x.x, for example 4.100.0.
        ##
        ## Important Points:
        ##   - No guarantees of support for prior versions is given. The chart is intended to be used with the AppVersion.
        ##   - Does not and will not support any version prior to 4.38.0 due to a significant refactor of the configuration
        ##     system.
        versionOverride: ""
        ## Kubernetes Version Override allows forcibly overriding the detected KubeVersion for fallback capabilities assessment.
        ## The fallback capabilities assessment only occurs if the APIVersions Capabilities list does not include a known
        ## APIVersion for a manifest which occurs with some CI/CD tooling. This value will completely override the value
        ## detected by helm.
        kubeVersionOverride: ""
        ## Kubernetes DNS Domain Override allows forcibly overriding the default DNS Domain for Kubernetes 'cluster.local'.
        kubeDNSDomainOverride: ""
        ## Image Parameters
        ## ref: https://hub.docker.com/r/authelia/authelia/tags/
        ##
        image:
            # registry: docker.io
            registry: ghcr.io
            repository: authelia/authelia
            tag: 4.38.17
            pullPolicy: IfNotPresent
            pullSecrets: []
            # pullSecrets:
            #   - myPullSecretName
        # nameOverride: 'authelia-deployment-name'
        # appNameOverride: 'authelia'
          

*** removed for privacy

            ##
            ## Notification Provider
            ##
            ##
            ## Notifications are sent to users when they require a password reset, a u2f registration or a TOTP registration.
            ## The available providers are: filesystem, smtp. You must use one and only one of these providers.
            notifier:
                ## You can disable the notifier startup check by setting this to true.
                disable_startup_check: false
                ##
                ## File System (Notification Provider)
                ##
                ## Important: Kubernetes (or HA) users must read https://www.authelia.com/overview/authorization/statelessness/
                ##
                filesystem:
                    enabled: false
                    filename: /config/notification.txt
                ##
                ## SMTP (Notification Provider)
                ##
                ## Use a SMTP server for sending notifications. Authelia uses the PLAIN or LOGIN methods to authenticate.
                ## [Security] By default Authelia will:
                ##   - force all SMTP connections over TLS including unauthenticated connections
                ##      - use the disable_require_tls boolean value to disable this requirement
                ##        (only works for unauthenticated connections)
                ##   - validate the SMTP server x509 certificate during the TLS handshake against the hosts trusted certificates
                ##     (configure in tls section)
                smtp:
                    enabled: true
                    enabledSecret: false
                    address: submission://internal.winters.org.nz:587/
                    timeout: 5 seconds
                    sender: Authelia <authelia@internal.winters.org.nz>
                    ## HELO/EHLO Identifier. Some SMTP Servers may reject the default of localhost.
                    identifier: authelia
                    ## Subject configuration of the emails sent.
                    ## {title} is replaced by the text from the notifier
                    subject: '[Authelia] {title}'
                    ## This address is used during the startup check to verify the email configuration is correct.
                    ## It's not important what it is except if your email server only allows local delivery.
                    startup_check_address: authelia@internal.winters.org.nz
                    ## Disables sending HTML formatted emails.
                    disable_html_emails: false
                    ## By default we require some form of TLS. This disables this check though is not advised.
                    disable_require_tls: false
                    ## Some SMTP servers ignore SMTP specifications and claim to support STARTTLS when they in fact do not. For
                    ## security reasons Authelia refuses to send messages to these servers. This option disables this measure and is
                    ## enabled AT YOUR OWN RISK. It’s strongly recommended that instead of enabling this option you either fix the
                    ## issue with the SMTP server’s configuration or have the administrators of the server fix it. If the issue can’t
                    ## be fixed by configuration we recommend lodging an issue with the authors of the SMTP server. See [security] for
                    ## more information.
                    disable_starttls: false
                    username: authelia
                    password:
                        ## Disables this secret and leaves configuring it entirely up to you.
                        disabled: false
                        ## The secret name. The ~ name is special as it is the secret we generate either automatically or via the
                        ## secret_value option below.
                        secret_name: null
                        ## The value of a generated secret when using the ~ secret_name.
                        value: ""
                        ## The path to the secret. If it has a '/' prefix it's assumed to be an absolute path within the pod. Otherwise
                        ## it uses the format '{mountPath}/{secret_name}/{path}' where '{mountPath}' refers to the 'secret.mountPath'
                        ## value, '{secret_name}' is the secret_name above, and '{path}' is this value.
                        path: notifier.smtp.password.txt
                    tls:
                        ## The server subject name to check the servers certificate against during the validation process.
                        ## This option is not required if the certificate has a SAN which matches the host option.
                        server_name: ""
                        ## Skip verifying the server certificate entirely. In preference to setting this we strongly recommend you add the
                        ## certificate or the certificate of the authority signing the certificate to the certificates directory which is
                        ## defined by the `certificates_directory` option at the top of the configuration.
                        ## It's important to note the public key should be added to the directory, not the private key.
                        ## This option is strongly discouraged but may be useful in some self-signed situations where validation is not
                        ## important to the administrator.
                        skip_verify: false
                        ## Minimum TLS version for the connection.
                        minimum_version: TLS1.2
                        ## Maximum TLS version for the connection.
                        maximum_version: TLS1.3
            identity_providers:


*** Here down removed.
```

### Build Information

```shell
Last Tag: v4.38.17
State: tagged clean
Branch: v4.38.17
Commit: 592ab519b4167dfe4462ee0a613d38d3e4b8efa0
Build Number: 35061
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Thu, 31 Oct 2024 09:37:31 +1100
Extra: 

Go:
    Version: go1.23.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
Logs from 4.38.17
time="2024-11-07T15:19:50+13:00" level=info msg="Authelia v4.38.17 is starting"
time="2024-11-07T15:19:50+13:00" level=info msg="Log severity set to info"
time="2024-11-07T15:19:50+13:00" level=info msg="Storage schema is being checked for updates"
time="2024-11-07T15:19:50+13:00" level=info msg="Storage schema is already up to date"
time="2024-11-07T15:19:51+13:00" level=error msg="Error occurred running a startup check" error="failed to dial connection: SMTP AUTH failed: 535 5.7.8 Error: authentication failed: authentication failure" provider=notification
time="2024-11-07T15:19:51+13:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88 (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985 (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10 main\ninternal/runtime/atomic/types.go:194 (*Uint32).Load\nruntime/asm_amd64.s:1700 goexit"


Logs from prior version
time="2024-11-07T12:59:36+13:00" level=info msg="Authelia v4.38.16 is starting"
time="2024-11-07T12:59:36+13:00" level=info msg="Log severity set to info"
time="2024-11-07T12:59:36+13:00" level=info msg="Storage schema is being checked for updates"
time="2024-11-07T12:59:36+13:00" level=info msg="Storage schema is already up to date"
time="2024-11-07T12:59:37+13:00" level=info msg="Startup complete"
time="2024-11-07T12:59:37+13:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
