### ISSUE TITLE
Access Control help

### ISSUE THREAD

**Issue by mqmq0** [authelia/authelia#834]
Hello Good People of Authelia,

I'm using this wonderful tool since January, just recently updated the the latest release and now I decided to set up some Access Control rules but I just cannot figure out what am I doing wrong.
What I want to achieve that I do not have to use the second factor when "I'm home" e.g. from LAN
Let me show you my full Config.yml right now
```
root@asd:/var/www/public_html# cat /etc/authelia/config.yml

host: 0.0.0.0
port: 9091

log_level: debug

jwt_secret: asdasd

default_redirection_url: https://proteced.domain.com/


totp:
  issuer: asd
  period: 30
  skew: 1

duo_api:
  hostname: asdasd
  integration_key: asdasd
  secret_key: asdasd


authentication_backend:
  file:
     path: /etc/authelia/users.yml


access_control:
  default_policy: two_factor

    rules:
    - domain: protected.domain.com
      policy: one_factor
      networks:
      - 192.168.0.0/24

session:
  name: authelia_session

  secret: asasd

  expiration: 1h

  inactivity: 5m

  remember_me_duration: 1M

  domain: domain.com


regulation:
  max_retries: 3

  find_time: 2m

  ban_time: 5m

storage:
   local:
    path: /etc/authelia/db.sqlite3

notifier:

    smtp:
     username: asd@gmail.com
     password: asd
     host: smtp.gmail.com
     port: 587
     sender: asd@gmail.com
     secure: false
```
Everything works fine until I add the 'rules: ' part to the config.
Either I got the logic wrong, or I'm just making some kind of typo, bad indentation or something...

**Comment by clems4ever** [comment]
Hello @mqmq0 , we need more info on what kind of error you're facing to help you out. Can you elaborate by describing your scenario and tell us what's the actual issue?

I think some logs in debug mode would be useful too since your config looks good to me.

**Comment by nightah** [comment]
@mqmq0 it does look to me like your indenting is slightly off in the configuration you have provided, you need to outdent rules so that this:
```
access_control:
  default_policy: two_factor

    rules:
    - domain: protected.domain.com
      policy: one_factor
      networks:
      - 192.168.0.0/24
```

Becomes like this:
```
access_control:
  default_policy: two_factor

  rules:
    - domain: protected.domain.com
      policy: one_factor
      networks:
      - 192.168.0.0/24
```
