### ISSUE TITLE
Configuration: session: domain config errors using Docker

### ISSUE THREAD

**Issue by F1zzyD** [authelia/authelia#8514]
### Version

v4.38.17

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

2.12.1

### Description

when trying to start Authelia with Docker, the logs complain that there is an issue with my domain and authelia url not appearing to be a valid cookie domain or an ip address even after following the documentation. See logs below.

### Reproduction

1. Define session domain and autherlia url for cookie sessions in configuration.yml
2. Save and run `docker compose up`
3. Authelia complains that both do not appear to be a valid cookie domain, ip address, or share a cookie scope.
4. Authelia loops with these errors, refusing to start. 

### Expectations

Authelia should start...

### Configuration (Authelia)

```yaml
## Session Provider Configuration
##
## The session cookies identify the user once logged in.
## The available providers are: `memory`, `redis`. Memory is the provider unless redis is defined.
session:
  ## The secret to encrypt the session data. This is only used with Redis / Redis Sentinel.
  ## Secret can also be set using a secret: https://www.authelia.com/c/secrets
  # secret: 'insecure_session_secret'

  ## Cookies configures the list of allowed cookie domains for sessions to be created on.
  ## Undefined values will default to the values below.
  cookies:
    -
      ## The name of the session cookie.
      name: 'authelia_session'

      ## The domain to protect.
      ## Note: the Authelia portal must also be in that domain.
      domain: 'https://domain.com'

      ## Required. The fully qualified URI of the portal to redirect users to on proxies that support redirections.
      ## Rules:
      ##   - MUST use the secure scheme 'https://'
      ##   - The above 'domain' option MUST either:
      ##      - Match the host portion of this URI.
      ##      - Match the suffix of the host portion when prefixed with '.'.
      authelia_url: 'https://authelia.domain.com'

      ## Optional. The fully qualified URI used as the redirection location if the portal is accessed directly. Not
      ## configuring this option disables the automatic redirection behaviour.
      ##
      ## Note: this parameter is optional. If not provided, user won't be redirected upon successful authentication
      ## unless they were redirected to Authelia by the proxy.
      ##
      ## Rules:
      ##   - MUST use the secure scheme 'https://'
      ##   - MUST not match the 'authelia_url' option.
      ##   - The above 'domain' option MUST either:
      ##      - Match the host portion of this URI.
      ##      - Match the suffix of the host portion when prefixed with '.'.
      # default_redirection_url: 'https://www.example.com'

      ## Sets the Cookie SameSite value. Possible options are none, lax, or strict.
      ## Please read https://www.authelia.com/c/session#same_site
      same_site: 'lax'

      ## The value for inactivity, expiration, and remember_me are in seconds or the duration common syntax.
      ## All three of these values affect the cookie/session validity period. Longer periods are considered less secure
      ## because a stolen cookie will last longer giving attackers more time to spy or attack.

      ## The inactivity time before the session is reset. If expiration is set to 1h, and this is set to 5m, if the user
      ## does not select the remember me option their session will get destroyed after 1h, or after 5m since the last
      ## time Authelia detected user activity.
      inactivity: '5 minutes'

      ## The time before the session cookie expires and the session is destroyed if remember me IS NOT selected by the
      ## user.
      expiration: '1 hour'

      ## The time before the cookie expires and the session is destroyed if remember me IS selected by the user. Setting
      ## this value to -1 disables remember me for this session cookie domain. If allowed and the user uses the remember
      ## me checkbox this overrides the expiration option and disables the inactivity option.
      remember_me: '1 month'

  ## Cookie Session Domain default 'name' value.
  name: 'authelia_session'

  ## Cookie Session Domain default 'same_site' value.
  same_site: 'lax'

  ## Cookie Session Domain default 'inactivity' value.
  inactivity: '5m'

  ## Cookie Session Domain default 'expiration' value.
  expiration: '1h'

  ## Cookie Session Domain default 'remember_me' value.
  remember_me: '1M'
```

### Build Information

```shell
Cannot provide as Authelia refuses to start.
```

### Logs (Authelia)

```shell
[+] Running 1/0
 ✔ Container authelia  Created                                                                                                                            0.0s
Attaching to authelia
authelia  | time="2024-12-26T19:46:06Z" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
authelia  | time="2024-12-26T19:46:06Z" level=error msg="Configuration: session: domain config #1 (domain 'https://domain.com'): option 'domain' does not appear to be a valid cookie domain or an ip address"
authelia  | time="2024-12-26T19:46:06Z" level=error msg="Configuration: session: domain config #1 (domain 'https://domain.com'): option 'authelia_url' does not share a cookie scope with domain 'https://domain.com' with a value of 'https://authelia.domain.com'"
authelia  | time="2024-12-26T19:46:06Z" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
```

### Logs (Proxy / Application)

```shell
N/A
```

### Generative AI

No

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation
