### ISSUE TITLE
Samba LDAP cannot be reached due to "x509: negative serial number" error

### ISSUE THREAD

**Issue by konjas** [authelia/authelia#8767]
### Version

v4.38.13, v4.38.14, v4.38.15, v4.38.16, v4.38.17, v4.38.18, v4.38.19

### Deployment Method

Bare-metal

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.7.6-r7

### Description

Starting from v4.38.13, Authelia cannot use LDAP provided by Samba AD DC. My setup probably does not use any certificates (I'm just learning), so Authelia fails to connect to LDAP, reporting "x509: negative serial number". Quick googling reports negative serial number are allowed and should be accepted/ignored by the application, which Authelia did until v4.38.12.

### Reproduction

1. Install Samba Active Directory Domain Controller (Samba AD DC)
2. Install Alpine LXC container
3. Inside the container, download, configure and start Authelia

### Expectations

Authelia should start, ignoring the "x509: negative serial number" error.

### Configuration (Authelia)

```yaml
---
theme: 'auto'
server:
  address: 'tcp://:80/'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies: []
log:
  level: 'trace'
  format: 'text'
  file_path: '/var/log/authelia.log'
totp:
  issuer: 'example.eu'
identity_validation:
  reset_password:
    jwt_secret: 'superSecret'
authentication_backend:
  password_reset:
    disable: true
  ldap:
    address: 'ldaps://dc.home.example.eu'
    implementation: 'activedirectory'
    timeout: '5 seconds'
    start_tls: false
    tls:
      skip_verify: true
    base_dn: 'DC=home,DC=example,DC=eu'
    additional_users_dn: 'CN=Users'
    users_filter: '(&({username_attribute}={input})(objectClass=user))'
    additional_groups_dn: 'CN=Users'
    groups_filter: '(&(member={dn})(objectClass=group))'
    group_search_mode: 'filter'
    user: 'CN=Administrator,CN=Users,DC=home,DC=example,DC=eu'
    password: 'superPassword'
access_control:
  networks:
    - name: 'internal'
      networks:
        - '192.168.22.0/24'
        - '192.168.200.0/24'
  rules:
    - domain: 'jellyfin.example.eu'
      policy: 'bypass'
    - domain: 'jellyfin.home.example.eu'
      policy: 'bypass'
    - domain: '*.example.eu'
      policy: 'one_factor'
session:
  cookies:
    -
      name: 'authelia_session'
      domain: 'example.eu'
      authelia_url: 'https://auth.example.eu'
      default_redirection_url: 'https://www.example.eu'
regulation:
  max_retries: 3
  find_time: '30 minutes'
  ban_time: '180 minutes'
storage:
  encryption_key: 'superEncryption'
  local:
    path: '/etc/authelia/db.sqlite3'
notifier:
  filesystem:
    filename: '/etc/authelia/notification.txt'
...
```

### Build Information

```shell
Last Tag: v4.38.19
State: tagged clean
Branch: v4.38.19
Commit: 321195866cb56672cc24011a757c3c30b3d5b69b
Build Number: 39531
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Feb 2025 21:09:28 +1100
Extra: 

Go:
    Version: go1.23.6
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-02-16T12:53:01+01:00" level=trace msg="Starting scan of directory  for certificates" caller="github.com/authelia/authelia/v4/internal/utils/crypto.go:350 NewX509CertPool"
time="2025-02-16T12:53:01+01:00" level=trace msg="Dynamically generated users filter is (&(sAMAccountName={input})(objectClass=user))" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:94 (*LDAPUserProvider).parseDynamicUsersConfiguration"
time="2025-02-16T12:53:01+01:00" level=trace msg="Dynamically generated users BaseDN is CN=Users,DC=home,DC=example,DC=eu" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:120 (*LDAPUserProvider).parseDynamicUsersConfiguration"
time="2025-02-16T12:53:01+01:00" level=trace msg="Detected user filter replacements that need to be resolved per lookup are: {input}=true" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:138 (*LDAPUserProvider).parseDynamicUsersConfiguration"
time="2025-02-16T12:53:01+01:00" level=trace msg="Dynamically generated groups BaseDN is CN=Users,DC=home,DC=example,DC=eu" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:159 (*LDAPUserProvider).parseDynamicGroupsConfiguration"
time="2025-02-16T12:53:01+01:00" level=trace msg="Detected group filter replacements that need to be resolved per lookup are: input=false, username=false, dn=true" caller="github.com/authelia/authelia/v4/internal/authentication/ldap_user_provider_startup.go:181 (*LDAPUserProvider).parseDynamicGroupsConfiguration"
time="2025-02-16T12:53:01+01:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:105 doStartupChecks" provider=storage
time="2025-02-16T12:53:01+01:00" level=info msg="Storage schema is being checked for updates" caller="github.com/authelia/authelia/v4/internal/storage/sql_provider.go:338 (*SQLProvider).StartupCheck"
time="2025-02-16T12:53:01+01:00" level=info msg="Storage schema is already up to date" caller="github.com/authelia/authelia/v4/internal/storage/sql_provider.go:356 (*SQLProvider).StartupCheck"
time="2025-02-16T12:53:01+01:00" level=trace msg="Startup Check Completed Successfully" caller="github.com/authelia/authelia/v4/internal/commands/root.go:112 doStartupChecks" provider=storage
time="2025-02-16T12:53:01+01:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:115 doStartupChecks" provider=user
time="2025-02-16T12:53:01+01:00" level=error msg="Error occurred running a startup check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:118 doStartupChecks" error="dial failed with error: LDAP Result Code 200 \"Network Error\": tls: failed to parse certificate from server: x509: negative serial number" provider=user stack="github.com/authelia/authelia/v4/internal/commands/root.go:118 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.9.0/command.go:1014                 (*Command).execute\ngithub.com/spf13/cobra@v1.9.0/command.go:1150                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.0/command.go:1070                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\ninternal/runtime/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1700                                      goexit"
time="2025-02-16T12:53:01+01:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:125 doStartupChecks" provider=notification
time="2025-02-16T12:53:01+01:00" level=trace msg="Startup Check Completed Successfully" caller="github.com/authelia/authelia/v4/internal/commands/root.go:132 doStartupChecks" provider=notification
time="2025-02-16T12:53:01+01:00" level=trace msg="Performing Startup Check" caller="github.com/authelia/authelia/v4/internal/commands/root.go:135 doStartupChecks" provider=ntp
time="2025-02-16T12:53:01+01:00" level=trace msg="Startup Check Completed Successfully" caller="github.com/authelia/authelia/v4/internal/commands/root.go:146 doStartupChecks" provider=ntp
time="2025-02-16T12:53:01+01:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" caller="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks" providers="[user]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.9.0/command.go:1014                 (*Command).execute\ngithub.com/spf13/cobra@v1.9.0/command.go:1150                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.0/command.go:1070                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\ninternal/runtime/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1700                                      goexit"
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
