### ISSUE TITLE
Remote error: tls: bad certificate with traefik v2 key + cert

### ISSUE THREAD

**Issue by J7mbo** [authelia/authelia#877]
I am using the keys generated by traefik v2 for authelia with a basic whoami example.

With traefik set up and working with https from the letsencrypt staging environment, I dump the cert and key files:

> docker run -v /volumes/traefik/certs:/certs --rm ldez/traefik-certs-dumper file --version v2 --source /certs/acme.json --dest /certs/dump

This creates some cert files in `/certs/dump`. I copy both the key and crt files (wildcard ones) generated for authelia to use.

Authelia boots up, but when visiting whoami.mydomain.com I get a 500 and "Remote error: tls: bad certificate".

**Comment by nightah** [comment]
@J7mbo thanks for using Authelia, we're going to need a little more information to help you out here.

When dumping the certs I assume you mean for Authelia itself to be TLS enabled?

Could you please provide a description of the actual workflow, ie order of sites visited and your expected outcome along with an output of your Traefik and Authelia configuration and logs.

Please redact any sensitive information.

**Comment by james-d-elliott** [comment]
Does your middlewares.[middleware-name].forwardauth.address match a host name in the certificate you've provided Authelia? I'm assuming not. I believe the correct way to handle this is to self sign and tell Traefik to trust the self signed cert.

**Comment by J7mbo** [comment]
Thanks for the responses. 

@james-d-elliott My middleware forwardauth address is: 

`https://authelia:9091/api/verify?rd=https://login.mydomain.com`. 

I have a wildcard cert from traefik, but I'm guessing the problem is `https://authelia` here? Is the only way to go about this to generate a self-signed certificate?

@nightah I will first post my working configuration for traefik, https, https redirect and **authelia with http**, and then the change I made to try and get it to https.

-------

Traefik, https, with global http -> https redirect, wildcard certs (dns challenge)
--

```
traefik:
        image: traefik:v2.2
        hostname: ${TRAEFIK_DIGITALOCEAN_NAME}
        environment:
            - DO_AUTH_TOKEN=${DIGITALOCEAN_ACCESS_TOKEN}
        command:
            # General configuration
            - --log.level=WARN

            # Docker configuration
            - --providers.docker.swarmMode=true
            - --providers.docker.exposedByDefault=false
            - --providers.docker.network=${DOCKER_NETWORK_NAME}
            - --providers.docker.endpoint=tcp://socket-proxy:2375
            - --providers.docker.watch=true

            # Entrypoints
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443

            # Letsencrypt setup
            - --certificatesresolvers.letsencrypt.acme.caServer=${LETSENCRYPT_ACME_ENDPOINT}
            - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
            - --certificatesresolvers.letsencrypt.acme.storage=${TRAEFIK_HOST_VOLUME_CERTS}/acme.json
            - --certificatesresolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=15
            - --certificatesresolvers.letsencrypt.acme.dnsChallenge=true
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=digitalocean
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
        ports:
            - 80:80
            - 443:443
        networks:
            - ${DOCKER_NETWORK_NAME}
            - socket-proxy
        volumes:
            - /volumes/traefik/certs/:/volumes/traefik/certs/
        deploy:
            placement:
                constraints:
                    - node.hostname==${TRAEFIK_DIGITALOCEAN_NAME}
            labels:
                # General configuration - needs to be here for the http-catchall router to fire
                - traefik.enable=true
                - traefik.http.services.traefik.loadbalancer.server.port=80

                # Middlewares
                - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
                - traefik.http.routers.http-catchall.entrypoints=http
                - traefik.http.routers.http-catchall.middlewares=https-redirect,hsts-header
                - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
                - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
                - traefik.http.middlewares.hsts-header.headers.sslredirect=true

                 # Global wildcard certificates
                - traefik.http.routers.wildcard-certs.tls.certresolver=letsencrypt
                - traefik.http.routers.wildcard-certs.entrypoints=http
                - traefik.http.routers.wildcard-certs.tls.domains[0].main=${DOMAIN}
                - traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.${DOMAIN}
```

Whoami, with authelia middleware
--

```
whoami:
        image: "containous/whoami"
        hostname: ${TRAEFIK_DIGITALOCEAN_NAME}
        networks:
            - ${DOCKER_NETWORK_NAME}
        deploy:
            placement:
                constraints:
                    - node.hostname==${TRAEFIK_DIGITALOCEAN_NAME}
            labels:
                # General configuration
                - traefik.enable=true
                - traefik.http.services.whoami.loadbalancer.server.port=80

                # Https
                - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)
                - traefik.http.routers.whoami.entrypoints=https
                - traefik.http.routers.whoami.tls=true
                - traefik.http.routers.whoami.tls.certresolver=letsencrypt
                - traefik.http.routers.whoami.middlewares=authelia@docker
```

Authelia, currently running on http
--

```
authelia:
        image: authelia/authelia
        hostname: ${TRAEFIK_DIGITALOCEAN_NAME}
        environment:
            - TZ=Europe/Madrid
        ports:
            - 9091:9091
        volumes:
            - /etc/authelia:/etc/authelia/
        networks:
            - ${DOCKER_NETWORK_NAME}
        deploy:
            placement:
                constraints:
                    - node.hostname==${TRAEFIK_DIGITALOCEAN_NAME}
            labels:
                - traefik.enable=true
                - traefik.http.services.authelia.loadbalancer.server.port=9091
                - traefik.http.routers.authelia.rule=Host(`login.${DOMAIN}`)
                - traefik.http.routers.authelia.entrypoints=https
                - traefik.http.routers.authelia.tls=true
                - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN}/
                - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
                - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups'
```
*Note above I have `http://authelia`, not https://*.

There is nothing in my authelia configuration that I need to show here I think, it's the default, and it all works.

---

The parts I added to try and make this https:

Change the forwardauth.address label to https
--

```
traefik.http.middlewares.authelia.forwardauth.address=https://authelia:9091/api/verify?rd=https://login.${DOMAIN}/
```

Get the certs  from traefik
--

```
docker run -v /volumes/traefik/certs:/certs --rm ldez/traefik-certs-dumper file --version v2 --source /certs/acme.json --dest /certs/dump
```

This gives me:
- a certs and key `whoami.mydomain.com`
- a cert and key for `mydomain.com`

I copy the cert and key for `mydomain.com` (I did try the other one too) to `/etc/authelia`.

Set the authelia config for these certs:
--

```
tls_cert: /etc/authelia/mydomain.com.crt
tls_key: /etc/authelia/mydomain.com.key
```

------

The error I get in the logs is:

> Remote error: tls: bad certificate

----

My question:

- From a security perspective, I should probably have authelia on https. Can I have authelia running with my wildcard certificate rather than a self-signed cert? How can I achieve this?

**Comment by nightah** [comment]
You should be able to replace:
> `https://authelia:9091/api/verify?rd=https://login.mydomain.com`

With `https://login.mydomain.com/api/verify?rd=https://login.mydomain.com` this means that all internal communications from Traefik to Authelia go via Traefik, and it already can verify the wildcard cert.

**Comment by J7mbo** [comment]
I set the url as instructed to:

> https://login.${DOMAIN}/api/verify?rd=https://login.${DOMAIN}/

I now get the following error reported:

> error when serving connection "<x.x.x.x>:9091"<->"<x.x.x.x>:54364": tls: first record does not look like a TLS handshake

**Comment by nightah** [comment]
Ah I see you're also missing the following label on your Authelia container:
```
'traefik.http.services.authelia.loadbalancer.server.scheme=https'

**Comment by J7mbo** [comment]
@nightah I have also added this and I still get a 500 in my browser with no logs when visiting `whoami.mydomain.com`.

When visiting `login.mydomain.com`, it shows "Internal Server Error" in the browser and this in the logs:

> error when serving connection "10.0.1.91:9091"<->"10.0.1.13:44810": remote error: tls: bad certificate

**Comment by nightah** [comment]
Yep sorry my mistake, it looks like there's no way for Traefik to ignore verification of a certificate for a single backend.

You could set [`insecureSkipVerify`](https://docs.traefik.io/routing/overview/#insecureskipverify) to true, but that's probably not what you want because it ignores verification for everything.

If you want this working properly with Authelia TLS enabled you will need to ensure that the cert matches the address that Traefik is routing to the backend with and Traefik trusts the cert, per @james-d-elliott's comment earlier.

**Comment by james-d-elliott** [comment]
While disabling TLS checking is not a desired end result, it may be useful in the process to figure out if Authelia is setup correctly prior to enabling it. Generally when setting up software like this I'd set it up in a few stages.

1. Basic Config without TLS at all (disabled in Authelia).
2. Authelia with TLS but using insecureSkipVerify.
3. Full TLS security.

Each of these stages tells you something. In stage 1 you can test the underlying Authelia functionality is sane and working as expected. In stage 2 you verify enabling TLS in Authelia didn't break anything. In stage 3 it all comes together and you're only diagnosing one possible problem, certificate trust.

**Comment by nightah** [comment]
So stage 1 has obviously been confirmed by @J7mbo and I'm sure stage 2 also would be fine, I tested this scenario myself when debugging yesterday.

containous/traefik/issues/3038 is also relevant to the ability of being able to ignore TLS verification per backend.

@J7mbo https://docs.traefik.io/routing/overview/#rootcas is relevant to your stage 3 step.

**Comment by james-d-elliott** [comment]
I'll see if I can get my TLS config working with traefik 2.2 and sort out a guide.

**Comment by james-d-elliott** [comment]
Okay so, from what I can tell.. it just flat out doesn't support it. As it's an optional feature of Authelia I'd recommend disabling it provided that Authelia exists in the same docker as traefik.

The only theoretical security implication is that a man-in-the-middle attack occurs between traefik and authelia. However since they're both in docker if that occurs the attacker has a lot of access to docker and can very likely bypass TLS. Which means the only element you're possibly adding to prevent the attack is an easily understood obscurity barrier. 

Unless @nightah or @clems4ever can see another security implication.

**Comment by nightah** [comment]
Just to be clear Traefik doesn't support this.

Traefik seems to communicate with all backends via IP.
So you would need to create a self-signed cert against the IP address of your Authelia backend, which by container design can and very likely will change, unless of course you decide to hardcode it.

You can put the self-signed certificate or even your wildcard certificate on Authelia and just ignore verification of the certificate, until the Traefik issue I posted above is resolved and then you can ignore it only on this specific backend.

Alternatively you could look at another reverse proxy which has the flexibility to specify what hostname it can communicate with the backend on.

**Comment by J7mbo** [comment]
> The only theoretical security implication is that a man-in-the-middle attack occurs between traefik and authelia. 

Precisely. There are a few reasons I can think of for why one might want https on an internal docker network - same reasons as why the IPSEC encryption option can be useful - in case one of the containers will be public. An example - big company has new employees joining, and the new guys can add their own docker container to the network. Encryption and https might be valuable here.

But this isn't my use-case. I was just aiming for https everywhere.

For @nightah's suggestion, I don't think docker swarm yet supports static IPs for services or containers. With traefik I can ignore verification of all certificates or none as explained until they take a look at that feature request which will probably be a long while.

I thought traefik could communicate with backends (in the "service" configuration) by address, which can be the hostname too? [Docs here](https://docs.traefik.io/routing/services/#configuration-examples). Would this work or am I misunderstanding?

```
tcp:
  services:
    my-service:
      loadBalancer:
        servers:
        - address: "<hostname-would-go-here>:<private-port-server-1>"
```

**Comment by nightah** [comment]
This might look somewhat familiar: https://community.containo.us/t/how-can-i-use-loadbalancer-servers-address-in-labels/5363

You can but that means your definition for Authelia won't be label based it will need to be file based.

**Comment by nightah** [comment]
Something like this should work, though I haven't personally tested it myself:

Create a self-signed certificate for `authelia`:
```
docker run -v /volumes/traefik/certs:/tmp/certs authelia/authelia authelia certificates generate --host authelia --dir /tmp/certs/
```

Add this to your Traefik command configuration:
```
- "--providers.file.filename=/etc/traefik/authelia.yml"
```

**authelia.yml**
```
http:
  routers:
    authelia:
      rule: "Host(`login.${DOMAIN}`)""
      entryPoints: "https"
      tls: true
      service: "authelia"

http:
  middlewares:
    authelia:
      forwardAuth:
      	address: https://authelia:9091/api/verify?rd=https://login.${DOMAIN}/
        trustForwardHeaders: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups

http:
  services:
    authelia:
      loadBalancer:
        servers:
          - url: "https://authelia:9091/"

tls:
  certificates:
    - certFile: /volumes/traefik/certs/authelia.cert
      keyFile: /volumes/traefik/certs/authelia.key
      stores:
        - default
```

Also make sure you change any of the middleware definitions in your labels from `authelia@docker` to `authelia@file`.

Given that this is really a Traefik issue I think we've probably done all that we can to support you @J7mbo, so I'm going to close off this issue.

If you have any other problems or questions, please don't hesitate to reach out.
