### ISSUE TITLE
More comprehensive theme switching and custom theming

### ISSUE THREAD

**Issue by Crowley723** [authelia/authelia#8839]
### Description

Add a user-selectable theme switcher to Authelia that allows users to choose between available themes on the client side while also allowing admins to set global defaults. The theme defaults should apply globally but allow users to set a per browser preference.

### Use Case

1. Users want to switch between light and dark modes based on their preferences or time of day
2. Users working in different lighting conditions need appropriate themes for visibility and eye comfort

### Details

The proposed implementation would:
- Add a new "Customization" or "Appearance" section to the user settings page
- Allow configuration of available theme pairs in the Authelia configuration
- Support theme pairs that define both light and dark variants
- Store user preference in browser local storage
- Respect system light/dark mode preference by default
- Maintain backward compatibility with existing theme settings

The new configuration might look something like this:
```yaml
themes:
  ## The 'theme' option would be mutually exclusive with the 'default_mode' and 'choices' options and behave the same as the current theme setting.
  theme: 'auto' # Options: 'auto', 'light', 'dark', 'grey', 'oled'

  default_mode: 'auto'  # Options: 'auto', 'light', 'dark'
  choices:
    - name: Default
      light: 'light'
      dark: 'dark'
    - name: OLED
      light: 'light'
      dark: 'oled'
  
```

### Generative AI

Yes

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] I have checked for related issues and checked the documentation
