### ISSUE TITLE
Can't use passkey to login in OIDC workflow

### ISSUE THREAD

**Issue by tcx4c70** [authelia/authelia#8950]
### Version

v4.38.19

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Description

When using the latest master authelia docker image, passkey login will fail in OIDC workflow but will succeed in the general login. For example, if my authelia domain is `https://login.mydomain.com`, then passkey login will succeed if I login directly into `https://login.mydomain.com` but it will fail if I login in an OIDC workflow, such as `https://login.mydomain.com/?workflow=openid_connect&workflow_id=<workflow_id>`.

### Reproduction

1. enable passkey login
2. generate a OIDC client configuration and use it to configure a OIDC client (such as gitlab)
3. use authelia to login the OIDC client, then in the authelia login page, choose "SIGN IN WITH A PASSKEY"

### Expectations

Can login authelia successfully then redirect to the OIDC client.

### Configuration (Authelia)

```yaml
# Sorry I doesn't generate a minimum configuration. But I think setting `enable_passkey_login` should reproduce the problem.
theme: 'auto'
server:
  address: 'tcp://:9091/'
webauthn:
  disable: false
  enable_passkey_login: true
  experimental_enable_passkey_uv_two_factors: true
  attestation_conveyance_preference: 'direct'
  filtering:
    prohibit_backup_eligibility: false
  metadata:
    enabled: false
authentication_backend:
  file:
    path: '/config/users_database.yml'
    watch: true
    search:
      email: true
      case_insensitive: true
storage:
  local:
    path: '/config/db.sqlite3'
identity_providers:
  oidc:
    jwks:
    - key_id: 'example'
      algorithm: 'RS256'
      use: 'sig'
      key: |
        <secret>
    clients:
    - client_name: 'Gitlab'
      client_id: 'gitlab'
      client_secret: '<secret>'
      public: false
      authorization_policy: 'two_factor'
      require_pkce: true
      pkce_challenge_method: 'S256'
      redirect_uris:
      - <redirect_uri>
      scopes:
      - 'openid'
      - 'profile'
      - 'groups'
      - 'email'
      userinfo_signed_response_alg: 'none'
      token_endpoint_auth_method: 'client_secret_basic'
      pre_configured_consent_duration: '1 year'
```

### Build Information

```shell
Last Tag: v4.38.19
State: untagged clean
Branch: master
Commit: 8721eab1995bc772b72975c9299e477c3d0f208a
Build Number: 40989
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Thu, 13 Mar 2025 17:48:46 +1100
Extra:

Go:
    Version: go1.24.1
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-03-13T22:01:19+08:00" level=debug msg="Authorization Request with id '34de0e79-ff31-41e0-8977-1ea3fd5cc8a0' on client with id '<client_id>' is being processed" method=GET path=/api/oidc/authorization remote_ip=192.168.2.16
time="2025-03-13T22:01:33+08:00" level=debug msg="Mark Passkey authentication attempt made by user '<username>'" method=POST path=/api/firstfactor/passkey remote_ip=192.168.2.16
time="2025-03-13T22:01:34+08:00" level=debug msg="Successful Passkey authentication attempt made by user '<username>'" method=POST path=/api/firstfactor/passkey remote_ip=192.168.2.16
time="2025-03-13T22:01:34+08:00" level=debug msg="Passkey Login" hardware=false method=POST path=/api/firstfactor/passkey presence=true remote_ip=192.168.2.16 verified=true
time="2025-03-13T22:01:34+08:00" level=error msg="unable to parse consent session challenge id '': invalid UUID length: 0" method=POST path=/api/firstfactor/passkey remote_ip=192.168.2.16 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:78          (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/response.go:149                    handleOIDCWorkflowResponse\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor_passkey.go:344 FirstFactorPasskeyPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                    handlerMain.(*BridgeBuilder).Build.func7.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:65                   SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                  SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                   SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                      (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14               handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/metrics.go:23                   handlerMain.NewMetricsRequest.func33.1\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                    RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2380                                   (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225                                (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197                                (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

Yes

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
