### ISSUE TITLE
Logging in on another device clears active session

### ISSUE THREAD

**Issue by Shagon94** [authelia/authelia#8980]
### Version

v4.39.0

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Description

When logging in on another device it clears the currently active session(s)

### Reproduction

1. Login to device 1
2. Login to device 2 
3. Observe as device 1 is logged out

### Expectations

User should stay logged in

### Configuration (Authelia)

```yaml
theme: 'dark'
default_2fa_method: 'webauthn'

server:
  buffers:
    read: 10240
    write: 10240

log:
  level: 'debug'

telemetry:
  metrics:
    enabled: false

totp:
  disable: true

webauthn:
  disable: false


identity_validation:
  reset_password:
    jwt_secret: 'asdf'

authentication_backend:
  password_reset:
    disable: false

  file:
    path: '/config/users_database.yml'
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 2
        memory: 20000
        parallelism: 1
        key_length: 32
        salt_length: 16

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

  zxcvbn:
    enabled: false
    min_score: 3

privacy_policy:
  enabled: false
  require_user_acceptance: false
  policy_url: ''

access_control:
  default_policy: 'deny'
  networks:
  - name: 'internal'
    networks:
    - '10.0.0.0/8'
    - '172.16.0.0/12'
    - '192.168.0.0/24'

  rules:
    - domain: '*.domain.example'
      policy: 'one_factor'


session:
  secret: 'asdf'
  cookies:
  - domain: 'domain.example'
    authelia_url: 'https://auth.domain.example'
    default_redirection_url: 'https://home.domain.example'

  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '30m'
  expiration: '1h'
  remember_me: '1M'

storage:
  encryption_key: 'asdf'
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'
```

### Build Information

```shell
# docker exec -it authelia authelia build-info
Last Tag: v4.39.0
State: tagged clean
Branch: v4.39.0
Commit: bbfa41712ce1b3e39b4798b18bd5f78e68470720
Build Number: 41111
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Mar 2025 21:05:57 +1100
Extra:

Go:
    Version: go1.24.1
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-03-16T22:38:49+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'shagon'" method=POST path=/api/firstfactor remote_ip=192.168.0.5
time="2025-03-16T22:38:49+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'shagon'" method=POST path=/api/firstfactor remote_ip=192.168.0.5
time="2025-03-16T22:38:49+01:00" level=debug msg="Check authorization of subject username=shagon groups=admins,admin,dev ip=192.168.0.5 and object https://tau.domain.example/ (method GET)."
time="2025-03-16T22:38:49+01:00" level=debug msg="Required level for the URL https://tau.domain.example/ is one_factor" method=POST path=/api/firstfactor remote_ip=192.168.0.5
time="2025-03-16T22:38:49+01:00" level=debug msg="Redirection URL https://tau.domain.example/ is safe" method=POST path=/api/firstfactor remote_ip=192.168.0.5


time="2025-03-16T22:39:42+01:00" level=debug msg="Check authorization of subject username= groups= ip=192.168.0.5 and object https://tau.domain.example/get_activity?_=1742161110126 (method GET)."
time="2025-03-16T22:39:42+01:00" level=info msg="Access to https://tau.domain.example/get_activity?_=1742161110126 (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://auth.domain.example/?rd=https%3A%2F%2Ftau.domain.example%2Fget_activity%3F_%3D1742161110126&rm=GET" method=GET path=/api/authz/forward-auth remote_ip=192.168.0.5
time="2025-03-16T22:39:44+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'shagon'" method=POST path=/api/firstfactor remote_ip=192.168.0.8
time="2025-03-16T22:39:44+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'shagon'" method=POST path=/api/firstfactor remote_ip=192.168.0.8
time="2025-03-16T22:39:44+01:00" level=debug msg="Check authorization of subject username=shagon groups=admins,admin,dev ip=192.168.0.8 and object https://tau.domain.example/ (method GET)."
time="2025-03-16T22:39:44+01:00" level=debug msg="Required level for the URL https://tau.domain.example/ is one_factor" method=POST path=/api/firstfactor remote_ip=192.168.0.8
time="2025-03-16T22:39:44+01:00" level=debug msg="Redirection URL https://tau.domain.example/ is safe" method=POST path=/api/firstfactor remote_ip=192.168.0.8
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation

**Comment by Shagon94** [comment]
Seems that this happens with the password as well, most likely related to something in 4.39.0

**Comment by james-d-elliott** [comment]
Please submit the required information.

**Comment by Shagon94** [comment]
@james-d-elliott done; I can confirm this worked as expected on 4.38.0; Rolling back the container to that version fixes the issue.

**Comment by james-d-elliott** [comment]
There were no passkeys in 4.38.0.

**Comment by Shagon94** [comment]
Correct, this issue can be reproduced with only username and password

**Comment by james-d-elliott** [comment]
I can't reproduce this at the moment. I've managed to sign into multiple devices.

**Comment by Shagon94** [comment]
I can confirm that docker version `authelia/authelia:4.38` does not have this issue while `authelia/authelia:latest` does. Reverse proxy is caddy with the bare minimum it requires: 

```yaml
# cat services/authelia.caddy
@authelia host auth.{$DOMAIN}

handle @authelia {
  reverse_proxy authelia:9091
}
# cat Caddyfile
{
  servers {
    max_header_size 10MB
  }
}

*.{$DOMAIN} {$DOMAIN} {
  import services/*

  header {
    -Server
  }

  handle {
                abort
        }
}
```

**Comment by LadySmith** [comment]
I encountered similar problems with Traefik v3.3.4 and Authelia 4.39.0. Completely reinstalling Authelia version 4.38 resolved the issue. My symptoms were:

1. Authelia requested login, and after successfully completing the login, I could access services protected by Authelia, such as Dozzle, Sonarr, Whoami, and gethomepage (as expected).
2. However, when I opened a different Authelia-protected service in a new browser tab or window (for example, a different service, or the Raspberry Pi web interface which is on another device), the session immediately expired and redirected me to the login page.
3. This immediate expiration resulted in being logged out of all Authelia-protected services.

I initially suspected Traefik as the source of the issue and spent approximately 2 hours attempting to debug the problem; still not sure, but downgrading Authelia solved it, so here I am.

**Comment by james-d-elliott** [comment]
Can you confirm your session config please?

**Comment by Kornelius777** [comment]
Same problem here!
Additionally, logging in via Firefox works, Edge doesn't!

**Comment by james-d-elliott** [comment]
https://github.com/authelia/authelia/issues/8980#issuecomment-2727811877

**Comment by LadySmith** [comment]
> Can you confirm your session config please?

Before I sent anything, I've tried to replicate the problem. I truncated logs everytime I started but as you know, debug generates a lot of stuff. Should I paste logs and config here with codeblock, use add files thing below or pastebin it?

**Comment by james-d-elliott** [comment]
Right now I'm just interested in session configurations, I suspect that will reveal a pattern which I'm almost already certain of and will help guide any further debugging.

**Comment by LadySmith** [comment]
> Right now I'm just interested in session configurations, I suspect that will reveal a pattern which I'm almost already certain of and will help guide any further debugging.

configuration.yml
```yml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

theme: 'dark'
server:
  address: 'tcp://0.0.0.0:9091/'
  disable_healthcheck: false
  buffers:
    read: 4096
    write: 4096
  endpoints:
    enable_pprof: false
    enable_expvars: false
log:
  level: 'debug'
  format: 'text'
  file_path: '/config/authelia.log'
  keep_stdout: true
totp:
  issuer: 'example.xyz'
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: '5 minutes'
  file:
    path: '/config/users_database.yml'
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 256
        parallelism: 4
        key_length: 32
        salt_length: 16
access_control:
  default_policy: 'deny'
  rules:
    - domain: 
        - 'authelia.example.xyz'
      policy: 'bypass'
    - domain:
        - '*.example.xyz'
        - 'example.xyz'
      policy: 'two_factor'
session:
  cookies:
    - name: 'authelia_session'
      domain: 'example.xyz'
      authelia_url: 'https://authelia.example.xyz'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1M'
regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '30 minutes'
storage:
  local:
    path: '/config/db.sqlite3'
notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'
...
```

Alright, I think this is the one you want. Also, for some reason the authelia.log file doesn't capture the initial startup phase. It begins logging after 'Storage schema is being checked for updates', missing the 'Authelia v4.38.19 is starting' message, which is visible in Dozzle. If you need logs from the application's very beginning, I'll need to provide the Dozzle logs which is currently missing and have to be re-generated. Probably take some time.

**Comment by Shagon94** [comment]
Seems that this issue cannot be reproduced if you use redis instead of the built-in session manager. I'm able to 100% reproduce it without redis:

```yaml
session:
  secret: 'asdf'
  cookies:
  - domain: 'example.domain`
    authelia_url: 'https://auth.example.domain'
    default_redirection_url: 'https://home.example.domain'
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '30m'
  expiration: '1h'
  remember_me: '1M'
```

However with redis it works as expected:

```yaml
session:
  secret: 'asdf'
  cookies:
  - domain: 'example.domain`
    authelia_url: 'https://auth.example.domain'
    default_redirection_url: 'https://home.example.domain'
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '30m'
  expiration: '1h'
  remember_me: '1M'
  redis:
    host: 'redis'
    port: 6379
```

**Comment by shamoon** [comment]
I am experiencing the same problem, and because the sessions are essentially immediately invalidated it breaks almost all apps (all subsequent requests they make seem to fail). Downgrading to `4.38` got things working again, so it certainly seems related to a change here. Of course it is in no way my call but I would also respectfully suggest this isnt `priority/6/very-low` as it is a fairly debilitating bug (or a breaking change) of some kind.

Just like noted above, my session config didn't use redis:

```yaml
session:
  name: authelia_session
  secret: ***
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: example.com
```

And indeed, the moment I added redis things work as expected (so thank you Shagon94 for the fix!)

I would also be happy to help try to track things down if I can be of use somehow.
