### ISSUE TITLE
OIDC Login Stopped Working

### ISSUE THREAD

**Issue by ajb3932** [authelia/authelia#9003]
### Version

v4.39.0

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

Version 2024/07/16

### Description

My Authelia OIDC has stopped working with Gucamole. No matter what I have tried I still get the following error:
```
time="2025-03-17T21:04:16Z" level=info msg="Authelia v4.39.0 is starting"
time="2025-03-17T21:04:16Z" level=info msg="Log severity set to debug"
time="2025-03-17T21:04:16Z" level=debug msg="Registering OpenID Connect 1.0 client with client id 'bookstack' and policy 'two_factor'"
time="2025-03-17T21:04:16Z" level=debug msg="Registering OpenID Connect 1.0 client with client id 'guacamole' and policy 'two_factor'"
time="2025-03-17T21:04:16Z" level=info msg="Storage schema is being checked for updates"
time="2025-03-17T21:04:16Z" level=info msg="Storage schema is already up to date"
time="2025-03-17T21:04:16Z" level=debug msg="webauthn-metadata provider: startup check skipped as it is disabled"
time="2025-03-17T21:04:16Z" level=info msg="Startup complete"
time="2025-03-17T21:04:16Z" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2025-03-17T21:04:35Z" level=error msg="Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy." method=GET path=/api/oidc/authorization remote_ip=100.114.150.99 stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:46           OpenIDConnectAuthorization\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:114 RegisterOpenIDConnectRoutes.NewHTTPToAutheliaHandlerAdaptor.func9\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                            RegisterOpenIDConnectRoutes.(*BridgeBuilder).Build.func2.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                          SecurityHeadersNoStore.func1\ngithub.com/valyala/fasthttp@v1.59.0/userdata.go:57                                           (*userData).Get\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                           SecurityHeadersBase.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             RegisterOpenIDConnectRoutes.(*CORSPolicy).Middleware.func10\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                            RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2380                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                                     goexit"
```

### Reproduction

Using the Unraid Guacamole template with the OIDC plugin enabled. 

### Expectations

Able to log in to Guacamole using Authelia

### Configuration (Authelia)

```yaml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  address: 'tcp://:9091'

log:
  level: 'debug'

totp:
  issuer: 'authelia.com'

identity_validation:
  reset_password:
    jwt_secret: 'redacted'

duo_api:
  hostname: api-e60ccddc.duosecurity.com
  integration_key: redacted
  secret_key: redacted

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    # Rules applied to everyone
    #- domain: 'public.example.com'
    #  policy: 'bypass'
    - domain: '*.example.uk'
      policy: 'one_factor'
    #- domain: 'secure.example.com'
    #  policy: 'two_factor'

session:
  secret: 'redacted'

  cookies:
    - name: 'authelia_session'
      domain: 'example.uk'
      authelia_url: 'https://auth.example.uk'
      expiration: '1 hour'
      inactivity: '5 minutes'

  redis:
    host: '100.103.142.25'
    port: 6379
    password: 'redacted'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: 'redacted'
  local:
    path: '/config/db.sqlite3'

notifier:
  smtp:
    username: 'redacted'
    password: 'redacted'
    address: 'smtp://smtp:9025'
    sender: 'admin@example.uk'
    tls:
      skip_verify: true

identity_providers:
  oidc:
    hmac_secret: 'redacted'
    jwks:
      - key_id: 'example'
        algorithm: 'RS256'
        use: 'sig'
        key: |
          -----BEGIN PRIVATE KEY-----
          redacted
          -----END PRIVATE KEY-----
    enable_client_debug_messages: true
    minimum_parameter_entropy: 8
    enable_pkce_plain_challenge: true  # Add this
    enforce_pkce: 'never'
    enable_jwt_access_token_stateless_introspection: false
    discovery_signed_response_alg: 'none'
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    claims_policies:
      policy_name:
        id_token:
          - name
          - email
          - groups
        access_token:
          - name
          - email
          - groups
        id_token_audience_mode: 'specification'
        custom_claims:
          name:
            attribute: 'display_name'
          email:
            attribute: 'email'
          groups:
            attribute: 'groups'

    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins:
        - 'https://example.uk'
      allowed_origins_from_client_redirect_uris: false

    clients:
      - client_id: 'bookstack'
        client_name: 'BookStack'
        client_secret: 'redacted'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://wiki.example.uk/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'

      - client_id: 'guacamole'
        client_name: 'Apache Guacamole'
        client_secret: 'redacted'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://rdp.example.uk'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        response_types:
          - 'id_token'
        grant_types:
          - 'implicit'
        userinfo_signed_response_alg: 'none'
        pkce_challenge_method: 'plain'
...
```

### Build Information

```shell
root@HP-Z640:~# docker exec -it Authelia /bin/sh


BusyBox v1.36.1 (Ubuntu 1:1.36.1-6ubuntu3.1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

/app # authelia build-info
Last Tag: v4.39.0
State: tagged clean
Branch: v4.39.0
Commit: bbfa41712ce1b3e39b4798b18bd5f78e68470720
Build Number: 41111
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Mar 2025 21:05:57 +1100
Extra: 

Go:
    Version: go1.24.1
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
/app #
```

### Logs (Authelia)

```shell
time="2025-03-17T21:04:16Z" level=info msg="Authelia v4.39.0 is starting"
time="2025-03-17T21:04:16Z" level=info msg="Log severity set to debug"
time="2025-03-17T21:04:16Z" level=debug msg="Registering OpenID Connect 1.0 client with client id 'bookstack' and policy 'two_factor'"
time="2025-03-17T21:04:16Z" level=debug msg="Registering OpenID Connect 1.0 client with client id 'guacamole' and policy 'two_factor'"
time="2025-03-17T21:04:16Z" level=info msg="Storage schema is being checked for updates"
time="2025-03-17T21:04:16Z" level=info msg="Storage schema is already up to date"
time="2025-03-17T21:04:16Z" level=debug msg="webauthn-metadata provider: startup check skipped as it is disabled"
time="2025-03-17T21:04:16Z" level=info msg="Startup complete"
time="2025-03-17T21:04:16Z" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2025-03-17T21:04:35Z" level=error msg="Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy." method=GET path=/api/oidc/authorization remote_ip=100.114.150.99 stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:46           OpenIDConnectAuthorization\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:114 RegisterOpenIDConnectRoutes.NewHTTPToAutheliaHandlerAdaptor.func9\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                            RegisterOpenIDConnectRoutes.(*BridgeBuilder).Build.func2.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                          SecurityHeadersNoStore.func1\ngithub.com/valyala/fasthttp@v1.59.0/userdata.go:57                                           (*userData).Get\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                           SecurityHeadersBase.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             RegisterOpenIDConnectRoutes.(*CORSPolicy).Middleware.func10\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                            RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2380                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                                     goexit"
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Apache Guacamole does not require the entropy requirement for the state parameter. You will have to provide your accompanying guacamole config.

**Comment by SHOzturk-PV** [comment]
Did this issue take place after upgrading from 4.38 to 4.39?

Did you go over the release notes? https://www.authelia.com/blog/4.39-release-notes/
It contains changes to OIDC and its default claims configuration. On my own instance I had to revert the claims for my OpenWeb UI instance, dont remember the errors I got if any at all.

Try adding the following parameters as the release notes links to https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter

identity_providers:
  oidc:
    claims_policies:
      default:
        id_token: ['groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
    clients:
      - client_id: 'client_example_id'
        claims_policy: 'default'

**Comment by james-d-elliott** [comment]
His error is related to the `state` parameter being absent or not long enough. Unless you had this log message as well it's not related:

```
level=error msg="Authorization Request failed with error: The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy."
```

**Comment by SHOzturk-PV** [comment]
I reverted to check. On Authellia i didnt have an error at all and for OpenWebUI it crashes on a HTTP 500 return for /oauth/oidc/callback?code=***.
Authelia log even states:
- Authorization Request with id '***' on client with id 'open-webui' was successfully processed
- Access Request with id '***' on client with id 'open-webui' has successfully
- User Info Request with id '***' on client with id 'open-webui' was successfully processed

**Comment by james-d-elliott** [comment]
Yep yours is just related to the privacy enhancement as you figured out from the release notes, this is something else. Are you having success with Guacamole and AUthelia 4.39 after your original changes? If so I can close this as it's probably a config issue for the OP.

**Comment by shuricksumy** [comment]
Hi,
I also recently updated to 4.39 and my OIDC connected to NextCloud stopped working also. Moreover I use AUthelia with Traefik to protect my internal recourses and after update to 4.39 it asks relogining each time I open my pages and also does not work like previously to me.
So I backup my 4.38.19 and it works again.

Will try new release 4.39.1 - maybe it works now

**Comment by ajb3932** [comment]
Thanks I think I was messing with my config trying to get it working which is why I posted the original error message, as many of you have said I think the issue is 4.39. 

My containers auto-update so I guess I didn't realise. Thanks for your help. I will revert to 4.38 for now. 👍

**Comment by shuricksumy** [comment]
> Hi, I also recently updated to 4.39 and my OIDC connected to NextCloud stopped working also. Moreover I use AUthelia with Traefik to protect my internal recourses and after update to 4.39 it asks relogining each time I open my pages and also does not work like previously to me. So I backup my 4.38.19 and it works again.
> 
> Will try new release 4.39.1 - maybe it works now

No, 4.39.1 does not work also to me

![Image](https://github.com/user-attachments/assets/27a3f9d4-7d3a-498c-81de-29bc7740db09)

**Comment by james-d-elliott** [comment]
As per the [release notes](https://www.authelia.com/blog/4.39-release-notes/) you'll need to follow [this guide](https://www.authelia.com/integration/openid-connect/openid-connect-1.0-claims/#restore-functionality-prior-to-claims-parameter).

Support for non-bugs can be requested via [discussions](https://github.com/authelia/authelia/discussions)

**Comment by ajb3932** [comment]
Thanks for your help @james-d-elliott I followed the release notes and (Claude) got it working.

```
identity_providers:
  oidc:
    # Your existing OIDC configuration remains here
    
    claims_policies:
      # Add this new claims policy to restore the previous behavior
      legacy_claims:
        id_token: ['groups', 'email', 'email_verified', 'preferred_username', 'name']
    
    clients:
      
      - client_id: 'guacamole'
        client_name: 'Apache Guacamole'
        client_secret: 'redacted'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://rdp.example.uk'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        response_types:
          - 'id_token'
        grant_types:
          - 'implicit'
        userinfo_signed_response_alg: 'none'
        claims_policy: 'legacy_claims'  # Apply the new claims policy to this client
```
