### ISSUE TITLE
notifier.disable_startup_check does not seem to be working

### ISSUE THREAD

**Issue by TheHYPO35** [authelia/authelia#9006]
### Version

v4.39.0

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

3.3.4

### Description

As of yesterday, Authelia seems to be failing to load. This appears to coincide with the update to 4.39.0

The logs show a fatal error in respect of my SMTP server (which is valid, there is no server set). However, I have notifier.disable_startup_check = true

It seems that this disable is not working as intended in 4.39.0

No changes to the config file have occurred and Authelia was working yesterday.

I've also tried disabling the NTP check just to test and it also seems to report that bypass works. Unfortunately, I don't have access to my Authelia container logs before yesterday to see if the bypass was properly being reported (I've changed it to log to a file going forward), but this seems to be the problem.

PS: I am aware that I have some depreciated settings that I need to change in the future, but I don't think any relate to this

### Reproduction

If it's a universal issue, I expect that setting notifier.disable_startup_check = true and restarting the container will result in Authelia still doing the notifier check.

### Expectations

I expect that the notifier check will be bypassed.

### Configuration (Authelia)

```yaml
---


theme: light

jwt_secret: [REMOVED]


default_2fa_method: ""

server:

  host: 0.0.0.0

  port: 9091

  path: "authelia"


  buffers:
    read: 4096
    write: 4096

  enable_pprof: false

  enable_expvars: false

  disable_healthcheck: false

  tls:
    key: ""

    certificate: ""

    client_certificates: []

  headers:

    csp_template: ""

log:
  level: debug

   format: json

  file_path: /config/authelia.log

  keep_stdout: true

telemetry:

  metrics:
    enabled: false

    address: tcp://0.0.0.0:9959

totp:
  disable: false

  issuer: authelia.com

  algorithm: sha1

  digits: 6

  period: 30

  skew: 1

  secret_size: 32

webauthn:
  disable: false
  
  enable_passkey_login: false

  display_name: Authelia

  attestation_conveyance_preference: indirect
  
  timeout: 60s


  selection_criteria:


    user_verification: 'preferred'









duo_api:
  disable: false
  hostname: api-123456789.example.com
  integration_key: [REMOVED]
  secret_key: [REMOVED]
  enable_self_enrollment: false

ntp:
  address: "time.cloudflare.com:123"

  version: 4

  max_desync: 3s

  disable_startup_check: false

  disable_failure: false

authentication_backend:

  password_reset:
    disable: false

    custom_url: ""

  refresh_interval: 5m


  file:
    path: /config/users.yml

password_policy:

  standard:
    enabled: false

    min_length: 8

    max_length: 0

    require_uppercase: true

    require_lowercase: true

    require_number: true

    require_special: true

  zxcvbn:
    enabled: false

    min_score: 3

access_control:
  default_policy: deny

  networks:
    - name: internal
      networks:
        - 10.10.0.0/16
        - 192.168.0.0/16

  rules:
    - domain: '*.thefoguls.com'
      policy: one_factor


session:
  name: authelia_session

  domain: [REMOVED]
  same_site: lax

  secret: [REMOVED]


  expiration: 2h


  remember_me_duration: 1M

  redis:
    host: redis
    port: 6379



    database_index: 0

    maximum_active_connections: 8

    minimum_idle_connections: 0










regulation:
  max_retries: 3

  find_time: 2m

  ban_time: 5m

storage:
  encryption_key: [REMOVED]

  local:
    path: /config/db.sqlite3



notifier:
  disable_startup_check: true


  smtp:
    host: 127.0.0.1

    port: 1025

    timeout: 5s

    username: test

    password: password

    sender: "Authelia <admin@example.com>"

    identifier: localhost

    subject: "[Authelia] {title}"

    startup_check_address: test@authelia.com

    disable_require_tls: false

    disable_html_emails: false

    tls:

      skip_verify: false

      minimum_version: TLS1.2

...
```

### Build Information

```shell
Forgive me, but I'm not sure how to obtain this/run this comment in the docker version of authelia
```

### Logs (Authelia)

```shell
time="2025-03-17T21:39:21-04:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2025-03-17T21:39:21-04:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format= keep_stdout=true
time="2025-03-17T21:39:21-04:00" level=debug msg="Process user information" gid=0 name=root uid=0 username=root
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'server.enable_expvars' is deprecated in 4.38.0 and has been replaced by 'server.endpoints.enable_expvars': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'server.enable_pprof' is deprecated in 4.38.0 and has been replaced by 'server.endpoints.enable_pprof': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'session.remember_me_duration' is deprecated in 4.38.0 and has been replaced by 'session.remember_me': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration keys 'notifier.smtp.host' and 'notifier.smtp.port' are deprecated in 4.38.0 and has been replaced by 'notifier.smtp.address' in the format of '[tcp://]<hostname>[:<port>]': you are not required to make any changes as this has been automatically mapped for you to the value 'smtp://127.0.0.1:1025', but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration keys 'server.host', 'server.port', and 'server.path' are deprecated in 4.38.0 and has been replaced by 'server.address' in the format of '[tcp[(4|6)]://]<hostname>[:<port>][/<path>]' or 'tcp[(4|6)://][hostname]:<port>[/<path>]': you are not required to make any changes as this has been automatically mapped for you to the value 'tcp://0.0.0.0:9091/authelia', but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'session.remember_me_duration' is deprecated in 4.38.0 and has been replaced by 'session.remember_me': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'server.enable_pprof' is deprecated in 4.38.0 and has been replaced by 'server.endpoints.enable_pprof': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration key 'server.enable_expvars' is deprecated in 4.38.0 and has been replaced by 'server.endpoints.enable_expvars': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration keys 'notifier.smtp.host' and 'notifier.smtp.port' are deprecated in 4.38.0 and has been replaced by 'notifier.smtp.address' in the format of '[tcp://]<hostname>[:<port>]': you are not required to make any changes as this has been automatically mapped for you to the value 'smtp://127.0.0.1:1025', but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: configuration keys 'server.host', 'server.port', and 'server.path' are deprecated in 4.38.0 and has been replaced by 'server.address' in the format of '[tcp[(4|6)]://]<hostname>[:<port>][/<path>]' or 'tcp[(4|6)://][hostname]:<port>[/<path>]': you are not required to make any changes as this has been automatically mapped for you to the value 'tcp://0.0.0.0:9091/authelia', but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0"
time="2025-03-17T21:39:21-04:00" level=warning msg="Configuration: session: option 'domain' is deprecated in v4.38.0 and has been replaced by a multi-domain configuration: this has automatically been mapped for you but you will need to adjust your configuration to remove this message and receive the latest messages"
time="2025-03-17T21:39:21-04:00" level=info msg="Authelia v4.39.0 is starting"
time="2025-03-17T21:39:21-04:00" level=info msg="Log severity set to debug"
time="2025-03-17T21:39:21-04:00" level=info msg="Storage schema is being checked for updates"
time="2025-03-17T21:39:21-04:00" level=info msg="Storage schema is already up to date"
time="2025-03-17T21:39:21-04:00" level=error msg="Error occurred running a startup check" error="failed to dial connection: dial tcp 127.0.0.1:1025: connect: connection refused" provider=notification stack="github.com/authelia/authelia/v4/internal/middlewares/startup.go:70 doStartupCheck\ngithub.com/authelia/authelia/v4/internal/middlewares/startup.go:26 (*Providers).StartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:90       (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.9.1/command.go:1015                      (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                      (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                      (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10            main\ninternal/runtime/atomic/types.go:194                               (*Uint32).Load\nruntime/asm_arm64.s:1223                                           goexit"
time="2025-03-17T21:39:22-04:00" level=debug msg="webauthn-metadata provider: startup check skipped as it is disabled"
time="2025-03-17T21:39:22-04:00" level=fatal msg="One or more providers had fatal failures performing startup checks, for more details check the error level logs" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:94 (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.9.1/command.go:1015                (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10      main\ninternal/runtime/atomic/types.go:194                         (*Uint32).Load\nruntime/asm_arm64.s:1223                                     goexit"
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
