### ISSUE TITLE
Inactivity delay elapsed => unauthorized

### ISSUE THREAD

**Issue by abretaud** [authelia/authelia#909]
Hi,
A little question regarding the `inactivity` config value: when I reach the given delay, I get a page only saying "Unauthorized". I have to refresh the page to actually be redirected to the login page.
Is there a reason why I'm not redirected instantly to the login page instead of having this "Unauthorized" page?
My users just don't know what to do when they see a message like this

**Comment by james-d-elliott** [comment]
I've seen this before I think, but can you tell me which proxy you're using?

**Comment by abretaud** [comment]
I'm using traefik, on a swarm cluster, with this config:

```
version: '3.7'
services:
  traefik:
    image: traefik:2.1.6
    command:
      - "--api"
      - "--api.dashboard"
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=traefik"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,127.0.0.1"
      - "--entryPoints.webs.address=:443"
      - "--entryPoints.webs.forwardedHeaders.trustedIPs=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,127.0.0.1"
    ports:
      - 8888:80
      - 8889:443
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.http.routers.traefik-api.rule=PathPrefix(`/traefik`)"
        - "traefik.http.routers.traefik-api.tls=true"
        - "traefik.http.routers.traefik-api.entryPoints=webs"
        - "traefik.http.routers.traefik-api.service=api@internal"
        - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"
        - "traefik.http.middlewares.traefik-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.example.org/"
        - "traefik.http.middlewares.traefik-auth.forwardauth.trustForwardHeader=true"
        - "traefik.http.routers.traefik-api.middlewares=traefik-auth,traefik-strip"
        - "traefik.http.services.traefik-svc.loadbalancer.server.port=9999"
```

(there's also a tiny nginx between my browser and traefik, but the message comes from traefik+authelia)
