### ISSUE TITLE
/api/user/session/elevation Operation failed

### ISSUE THREAD

**Issue by chain710** [authelia/authelia#9098]
### Version

v4.39.1

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.22.1

### Description

First of all, thank you for the great work!

I tried to delete one-time password on `/settings/two-factor-authentication`

Chrome devtools shows elevation error

https://auth.example.com/api/user/session/elevation return `{
  "status": "KO",
  "message": "Operation failed."
}`

In authelia log, I found this: `Error occurred creating user session elevation One-Time Code challenge for user 'example': error occurred sending the user the notification" error="notifier: smtp: failed to send message: sending SMTP RESET command: failed to send RSET to SMTP client: short response: \x00\x00\x00\x18\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\x00250 OK, affected message ID`

However, I did receive the one-time code email just seconds later.

How can I resolve this issue?

### Reproduction

Delete one-time password on /settings/two-factor-authentication

### Expectations

Expect a pop-up dialog to enter the one-time code?

### Configuration (Authelia)

```yaml
server:
  address: "tcp://0.0.0.0:9092"

log:
  level: info
identity_validation:
  reset_password:
    jwt_secret: "secret"
totp:
  issuer: auth.example.com

authentication_backend:
  password_reset:
    disable: true
  # How often authelia should check if there is an user update in LDAP
  refresh_interval: 20s
  ldap:
    implementation: lldap
    address: ldap://lldap:3890
    # The dial timeout for LDAP.
    timeout: 5s
    # Use StartTLS with the LDAP connection, TLS not supported right now
    start_tls: false
    #tls:
    #  skip_verify: false
    #  minimum_version: TLS1.2
    # Set base dn, like dc=google,dc.com
    base_dn: dc=example,dc=dev
    # You need to set this to ou=people, because all users are stored in this ou!
    additional_users_dn: ou=people
    # To allow sign in both with username and email, one can use a filter like
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    # old: "(&({username_attribute}={input})(objectClass=person))"
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    # Set this to ou=groups, because all groups are stored in this ou
    additional_groups_dn: ou=groups
    # Only this filter is supported right now
    groups_filter: "(member={dn})"
    # The username and password of the admin user.
    # "admin" should be the admin username you set in the LLDAP configuration
    user: uid=user,ou=people,dc=example,dc=dev
    # Password can also be set using a secret: https://www.authelia.com/docs/configuration/secrets.html
    password: "password"
    attributes:
      distinguished_name: 'distinguishedName'
      member_of: 'memberOf'
      # Email
      mail: mail
      # The attribute holding the name of the group.
      group_name: cn
      username: uid
      # The attribute holding the display name of the user. This will be used to greet an authenticated user.
      display_name: displayName

access_control:
  default_policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: "secret"
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  # domain: example.com  # Should match whatever your root protected domain is
  redis:
    host: redis
    port: 6379
    database_index: 1
  cookies:
    - domain: "example.com"
      authelia_url: "https://auth.example.com"

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: "key"
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: true
  smtp:
    username: user
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: password
    address: "submissions://smtp.qq.com:465"
    sender: user@qq.com
    identifier: auth.example.com
```

### Build Information

```shell
/app $ authelia build-info
Last Tag: v4.39.1
State: tagged clean
Branch: v4.39.1
Commit: 9a22f5c30b216b6d1aa1f80b6a36fac62e9f7727
Build Number: 41283
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Tue, 18 Mar 2025 14:49:44 +1100
Extra:

Go:
    Version: go1.24.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
Error occurred creating user session elevation One-Time Code challenge for user 'example': error occurred sending the user the notification" error="notifier: smtp: failed to send message: sending SMTP RESET command: failed to send RSET to SMTP client: short response: \x00\x00\x00\x18\x00\x00\x00\b\x00\x00\x00\x00\x00\x00\x00\x00250 OK, affected message ID: xxxx
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

Yes

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
