### ISSUE TITLE
LDAP groups cache

### ISSUE THREAD

**Issue by abretaud** [authelia/authelia#910]
A little problem when doing the following:
 - one user logins to my webapp as user `foobar` defined in my ldap server
 - I (the admin) modify the ldap record for user `foobar`, adding him to a new ldap group `xyz`
 - user `foobar` tries to access a sub section of the webapp restricted to group `xyz`
 - the access is denied
 - the only way for `foobar` to access the page is to logout, and login again

I guess there is some sort of cache of groups used by authelia to determine if a user can access a page. Is there a way to make authelia refresh the group list for this user automatically?

**Comment by james-d-elliott** [comment]
I do not believe there is a cache, what LDAP provider are you using? I've got a feeling it's a distribution issue. Additionally can you post your authentication_backend config minus username/password, anything else sensitive?

**Comment by abretaud** [comment]
I'm using openldap, with this authelia conf (using version 4.12.0):
```
  ldap:
    url: ldap://ldap-hostname
    skip_verify: false
    base_dn: dc=example,dc=org
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(isActive=TRUE))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectclass=myGroupClass))
    group_name_attribute: cn
    mail_attribute: mail
    user: cn=admin,dc=example,dc=org
    password: xxxxxx
```
