### ISSUE TITLE
Failed to decode AAGUID

### ISSUE THREAD

**Issue by aureq** [authelia/authelia#9133]
### Version

v4.39.1

### Deployment Method

Kubernetes

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.12.1

### Description

Hi,

I've installed Authelia 4.39.1 and enabled MDS as recommended. ✔
I've registered 3 tokens. 2 are Yubikey 5C NFC and 1 is a [Yubikey NEO](https://support.yubico.com/hc/en-us/articles/360013714579-YubiKey-NEO).
The token registration process for the user went smoothly for the 3 devices. ✔

However, it looks like it's not possible to use the Yubikey NEO for authentication when MDS is enabled ❌ but all good with the 2 more recent Yubikey 5C. ✔
Authelia shows the following error in the logs:

```
time="2025-03-30T02:35:26Z" level=error msg="Unsuccessful WebAuthn authentication attempt by user 'xxxxx'" error="Failed to decode AAGUID (invalid_request): Error occurred decoding AAGUID from the credential record: invalid UUID (got 0 bytes)" method=POST path=/api/secondfactor/webauthn remote_ip=192.168.8.197
```

The MDS configuration is as follows (from the Chart)

```yaml
    # [...]

    ## Configures the metadata service which is used to check the authenticity of authenticators. Useful if company
    ## policy requires only conformant authenticators.
    metadata:

      ## Enables metadata service validation of authenticators and credentials. This requires the download of the
      ## metadata service blob which will utilize about 5MB of data in your configured storage backend.
      enabled: true # (22)

      ## Enables validation of the attestation certificate against the Certificate Authority certificate in the
      ## validated MDS3 blob. It’s recommended this value is always the default value.
      validate_trust_anchor: true

      ## Enables validation that an entry exists for the authenticator in the MDS3 blob. It’s recommended that this
      ## option is the default value, however this may exclude some authenticators which DO NOT have FIDO compliance
      ## certification or have otherwise not registered with the MDS3. The recommendation is based on the fact that the
      ## authenticity of a particular authenticator cannot be validated without this.
      validate_entry: true

      ## Allows authenticators which have provided an empty Authenticator Attestation GUID. This may be required for
      ## certain authenticators which DO NOT have FIDO compliance certification.
      validate_entry_permit_zero_aaguid: true

      ## Enables validation of the attestation entry statuses. There is generally never a reason to disable this as the
      ## authenticators excluded by default are likely compromised.
      validate_status: true

      ## A list of exclusively required statuses for an authenticator to pass validation.
      validate_status_permitted: []

      ## A list of authenticator statuses which for an authenticator that are prohibited from being registered.
      validate_status_prohibited: []
```

As noted in the YAML extract above, I also tried with `validate_entry_permit_zero_aaguid: true` (thinking maybe the older device doesn't send or have the AAGUID) but I get the exact same error message.

The Webauthn Credential Information reported by Authelia
```
Description: Yubikey NEO
Relying Party ID: login.example.com
Authenticator GUID: Unknown
Attestation Type: fido-u2f
Attachment: Cross-Platform
Discoverable: No
User Verified: No
Backup State: Not Eligible
Transports: USB
Clone Warning: No
Usage Count: 0
Added: March 30, 2025 at 1:35 PM
Last Used: Never
```

For the 2 other (more recent) tokens, the `Authenticator GUID` contains a GUID. ✔

### Reproduction

- Have Authelia installed
- Enable MDS and 2FA
- Have a user registered already
- Register a Yubikey NEO ✔
- Logout
- Authenticate and use the token as 2FA. 1st FA works ✔ but the 2nd FA fails ❌. The UI shows `Failed to initiate security key sign in process` and an error is shown in the container logs (as noted above).

### Expectations

If Authelia's behavior is within design range, then maybe the token registration should yield a warning or an error indicating to the end user the token won't be usable during the subsequent authentication process.

If this issue is a bug, then Authelia should authenticate the user with the 2FA when `validate_entry_permit_zero_aaguid: true`. (provided that my understanding of this option is correct).

### Configuration (Authelia)

```yaml
---
# yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39/json-schema/configuration.json
theme: 'dark'
default_2fa_method: 'webauthn'
server:
  address: 'tcp://0.0.0.0:9091/'
  asset_path: ''
  headers:
    csp_template: ''
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6 seconds'
    write: '6 seconds'
    idle: '30 seconds'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz:
      auth-request:
        implementation: 'AuthRequest'
      ext-authz:
        implementation: 'ExtAuthz'
      forward-auth:
        implementation: 'ForwardAuth'
log:
  level: 'info'
  format: 'text'
  file_path: ''
  keep_stdout: true
telemetry:
  metrics:
    enabled: true
    address: 'tcp://0.0.0.0:9959'
    buffers:
      read: 4096
      write: 4096
    timeouts:
      read: '6 seconds'
      write: '6 seconds'
      idle: '30 seconds'
definitions:
  network:
    home:
    - '192.168.0.0/16'
    k8s:
    - '10.0.0.0/8'
identity_validation:
  elevated_session:
    code_lifespan: '5 minutes'
    elevation_lifespan: '10 minutes'
    characters: 8
    require_second_factor: false
    skip_second_factor: false
  reset_password:
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'
totp:
  disable: true
  issuer: 'Authelia'
  skew: 1
  secret_size: 32
  algorithm: 'SHA1'
  digits: 6
  period: 30
  allowed_algorithms:
    - 'SHA1'
  allowed_digits:
    - 6
  allowed_periods:
    - 30
webauthn:
  disable: false
  enable_passkey_login: false
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  timeout: '60 seconds'
  filtering:
    permitted_aaguids: []
    prohibited_aaguids: []
    prohibit_backup_eligibility: false
  selection_criteria:
    attachment: ''
    discoverability: 'preferred'
    user_verification: 'preferred'
  metadata:
    enabled: true
    validate_trust_anchor: true
    validate_entry: true
    validate_entry_permit_zero_aaguid: true
    validate_status: true
    validate_status_permitted: []
    validate_status_prohibited: []
ntp:
  address: 'udp://ntp.local.example.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false
authentication_backend:
  password_reset:
    disable: true
    custom_url: ''
  password_change:
    disable: false
  ldap:
    implementation: 'rfc2307bis'
    address: 'ldap://ldap.identity-services.svc'
    timeout: '5 seconds'
    start_tls: false
    tls:
      server_name: ''
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
    pooling:
      enable: false
      count: 5
      retries: 2
      timeout: '10 seconds'
    base_dn: 'DC=example,DC=com'
    additional_users_dn: 'OU=Users'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=inetOrgPerson))'
    additional_groups_dn: 'OU=Authelia,OU=Groups'
    groups_filter: '(&(uniquemember={dn})(objectclass=groupOfUniqueNames))'
    group_search_mode: 'filter'
    permit_referrals: false
    permit_unauthenticated_bind: false
    permit_feature_detection_failure: false
    user: 'CN=authelia,OU=Services,DC=example,DC=com'
    attributes:
      distinguished_name: ''
      username: ''
      display_name: ''
      family_name: ''
      given_name: ''
      middle_name: ''
      nickname: ''
      gender: ''
      birthdate: ''
      website: ''
      profile: ''
      picture: ''
      zoneinfo: ''
      locale: ''
      phone_number: ''
      phone_extension: ''
      street_address: ''
      locality: ''
      region: ''
      postal_code: ''
      country: ''
      mail:  ''
      member_of:  ''
      group_name:  ''
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: false
    require_lowercase: false
    require_number: false
    require_special: false
  zxcvbn:
    enabled: false
    min_score: 0
session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '12 hours'
  expiration: '14 hours'
  remember_me: '1 month'
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://login.example.com'
      default_redirection_url: 'https://www.example.com'
regulation:
  modes:
  - 'user'
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'
storage:
  local:
    path: '/config/db.sqlite3'
notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp://smtp.mail-services.svc.cluster.local'
    timeout: '5 seconds'
    username: ''
    sender: 'Authelia <authelian@example.com>'
    identifier: 'localhost'
    subject: '[Authelia] {title}'
    startup_check_address: 'test@authelia.com'
    disable_html_emails: false
    disable_require_tls: false
    disable_starttls: false
    tls:
      server_name: 'www.example.com'
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
identity_providers:
  oidc:
    lifespans:
      access_token: '1 hour'
      authorize_code: '1 minute'
      id_token: '1 hour'
      refresh_token: '1 hour and 30 minutes'
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_client_debug_messages: false
    enable_jwt_access_token_stateless_introspection: false
    minimum_parameter_entropy: 8
    discovery_signed_response_alg: ''
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/secrets/authelia-secrets/oidc.private.key" | mindent 10 "|" | msquote }}
    cors:
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_id: 'grafana-monitoring-services'
        client_name: 'Grafana'
        client_secret: '{{ secret "/secrets/authelia-secrets/oidc.client.grafana-monitoring-services.txt" }}'
        public: false
        redirect_uris:
          - 'https://monitoring.k8s.local.example.com/login/generic_oauth'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        grant_types:
          - 'authorization_code'
        response_types:
          - 'code'
        authorization_policy: 'two_factor'
        consent_mode: 'auto'
        require_pushed_authorization_requests: false
        require_pkce: false
        pkce_challenge_method: ''
        authorization_signed_response_alg: 'none'
        authorization_signed_response_key_id: ''
        authorization_encrypted_response_key_id: ''
        authorization_encrypted_response_alg: ''
        authorization_encrypted_response_enc: ''
        id_token_signed_response_alg: 'RS256'
        id_token_signed_response_key_id: ''
        id_token_encrypted_response_key_id: ''
        id_token_encrypted_response_alg: ''
        id_token_encrypted_response_enc: ''
        access_token_signed_response_alg: 'none'
        access_token_signed_response_key_id: ''
        access_token_encrypted_response_key_id: ''
        access_token_encrypted_response_alg: ''
        access_token_encrypted_response_enc: ''
        userinfo_signed_response_alg: 'none'
        userinfo_signed_response_key_id: ''
        userinfo_encrypted_response_key_id: ''
        userinfo_encrypted_response_alg: ''
        userinfo_encrypted_response_enc: ''
        introspection_signed_response_alg: 'none'
        introspection_signed_response_key_id: ''
        introspection_encrypted_response_key_id: ''
        introspection_encrypted_response_alg: ''
        introspection_encrypted_response_enc: ''
        introspection_endpoint_auth_method: 'client_secret_basic'
        introspection_endpoint_auth_signing_alg: 'RS256'
        request_object_signing_alg: ''
        request_object_encryption_alg: 'none'
        request_object_encryption_enc: ''
        token_endpoint_auth_method: 'client_secret_basic'
        token_endpoint_auth_signing_alg: ''
        revocation_endpoint_auth_method: 'client_secret_basic'
        revocation_endpoint_auth_signing_alg: 'RS256'
        pushed_authorization_request_endpoint_auth_method: 'client_secret_basic'
        pushed_authorization_request_endpoint_auth_signing_alg: 'RS256'
access_control:
  default_policy: 'deny'
  rules:
    - policy: two_factor
      domain:
        - 'docs.example.com'
      subject:
        - ['group:Administrators']
      resources:
        - '^/restricted/.*'
...
```

### Build Information

```shell
Last Tag: v4.39.1
State: tagged clean
Branch: v4.39.1
Commit: 9a22f5c30b216b6d1aa1f80b6a36fac62e9f7727
Build Number: 41283
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Tue, 18 Mar 2025 14:49:44 +1100
Extra: 

Go:
    Version: go1.24.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-03-30T03:17:22Z" level=debug msg="Registering OpenID Connect 1.0 client with client id 'grafana-monitoring-services' and policy 'two_factor'"
time="2025-03-30T03:17:22Z" level=info msg="Storage schema is being checked for updates"
time="2025-03-30T03:17:22Z" level=info msg="Storage schema is already up to date"
time="2025-03-30T03:17:22Z" level=debug msg="LDAP Supported OIDs. Control Types: 2.16.840.1.113730.3.4.18, 2.16.840.1.113730.3.4.2, 1.3.6.1.4.1.4203.1.10.1, 1.3.6.1.1.22, 1.2.840.113556.1.4.319, 1.2.826.0.1.3344810.2.3, 1.3.6.1.1.13.2, 1.3.6.1.1.13.1, 1.3.6.1.1.12. Extensions: 1.3.6.1.4.1.4203.1.11.1, 1.3.6.1.4.1.4203.1.11.3, 1.3.6.1.1.8, 1.3.6.1.1.21.3, 1.3.6.1.1.21.1"
time="2025-03-30T03:17:26Z" level=info msg="Startup complete"
time="2025-03-30T03:17:26Z" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2025-03-30T03:17:26Z" level=info msg="Listening for non-TLS connections on '[::]:9959' path '/metrics'" server=metrics service=server
time="2025-03-30T03:17:47Z" level=debug msg="Mark 1FA authentication attempt made by user 'aureq'" method=POST path=/api/firstfactor remote_ip=192.168.8.197
time="2025-03-30T03:17:47Z" level=debug msg="Successful 1FA authentication attempt made by user 'aureq'" method=POST path=/api/firstfactor remote_ip=192.168.8.197
time="2025-03-30T03:17:49Z" level=debug msg="Mark WebAuthn authentication attempt made by user 'aureq'" method=POST path=/api/secondfactor/webauthn remote_ip=192.168.8.197
time="2025-03-30T03:17:49Z" level=error msg="Unsuccessful WebAuthn authentication attempt by user 'aureq'" error="Failed to decode AAGUID (invalid_request): Error occurred decoding AAGUID from the credential record: invalid UUID (got 0 bytes)" method=POST path=/api/secondfactor/webauthn remote_ip=192.168.8.197 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:272              doMarkAuthenticationAttemptWithRequest\ngithub.com/authelia/authelia/v4/internal/handlers/response.go:258              doMarkAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_sign_webauthn.go:209 WebAuthnAssertionPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/require_auth.go:19        Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66              handlerMain.(*BridgeBuilder).Build.func8.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:65             SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105            SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30             SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14         handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/metrics.go:23             handlerMain.NewMetricsRequest.func33.1\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38              RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2380                             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225                          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197                          (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                       goexit"
```

### Logs (Proxy / Application)

```shell
n/a
```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
