### ISSUE TITLE
Datetime format in log doesn't work

### ISSUE THREAD

**Issue by christaikobo** [authelia/authelia#9158]
### Version

v4.39.1

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.8.0

### Description

Back in 4.38, when using `file_path: '/config/authelia.{datetime:2006-01-02}.log'`, the log files authelia output will be generated based on date: authelia.2025-03-29.log, authelia.2025-03-30.log, authelia.2025-03-31.log

However after upgrading to 4.39.0 as well as 4.39.1, sometimes after restarting the authelia docker, the log file will be stuck at the day the docker container was spawned, for example authelia.2025-03-29.log, and then even now it is 04-01, all the logs are still written to authelia.2025-03-29.log.

### Reproduction

Use the following config, and see the log files.

### Configuration (Authelia)

```yaml
# yamllint disable rule:comments-indentation
---
authentication_backend:

  file:
    path: '/config/users_database.yml'

totp:
  issuer: 'Authelia'

access_control:

  rules:

  - domain:
    - 'REDACTED'
    resources:
    - '^/media(/.*)?$'
    subject:
    - 'group:basic_auth'
    policy: 'one_factor'

regulation:
  modes:
    - 'user'
    - 'ip'
  max_retries: 3
  find_time: '1 minutes'
  ban_time: '2 minutes'

password_policy:

  zxcvbn:
    enabled: true
    min_score: 3

identity_validation:

  reset_password:
    jwt_secret: 'REDACTED'

session:
  inactivity: '5m'
  expiration: '2h'
  remember_me: '1d'

  cookies:
    - domain: 'REDACTED'
      authelia_url: 'https://REDACTED/auth'

storage:
  encryption_key: 'REDACTED'

  local:
    path: '/config/db.sqlite3'

notifier:

  smtp:
    address: 'smtp://smtp.gmail.com:587'
    username: 'REDACTED'
    password: 'REDACTED'
    sender: 'Authelia <REDACTED>'

server:
  address: 'tcp://:9091/auth'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'CookieSession'
      basic-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'

log:
  level: 'debug'
  format: 'text'
  file_path: '/config/authelia.{datetime:2006-01-02}.log'
```

### Build Information

```shell
Last Tag: v4.39.1
State: tagged clean
Branch: v4.39.1
Commit: 9a22f5c30b216b6d1aa1f80b6a36fac62e9f7727
Build Number: 41283
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Tue, 18 Mar 2025 14:49:44 +1100
Extra:

Go:
    Version: go1.24.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
N/A
Log will not show the creation of log file itself.
```

### Logs (Proxy / Application)

```shell
N/A
```

### Documentation

https://www.authelia.com/configuration/miscellaneous/logging/#file_path

I have followed the instructions here and it used to work. 

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
