### ISSUE TITLE
OIDC client auth methods not defaulting to `none` for public type

### ISSUE THREAD

**Issue by emsearcy** [authelia/authelia#9328]
### Version

v4.39.1

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Description

A minimally-configured `public: true` client throws configuration-loading errors for revocation_endpoint_auth_method, introspection_endpoint_auth_method, and pushed_authorization_request_endpoint_auth_method, saying they must be none but are configured as "client_secret_basic", _even when they are not present in the configuration._

### Reproduction

Add to `configMap.identity_providers.oidc.clients` in helm "values" file:

```yaml
- client_id: my_spa
  client_name: My SPA
  public: true
```

Re-deploy:

```bash
helm repo add authelia https://charts.authelia.com
helm repo update
kubectl create namespace authelia
kubectl create secret generic jwks-keys \
        --from-literal="jwks-key-1.pem=$(openssl genrsa 2048)" \
        -n authelia
helm upgrade --install authelia authelia/authelia -n authelia -f values-authelia.yaml
```

### Expectations

Authelia should start and adopt default value of "none" for these 3 parameters when not provided for a public client, as described in the documentation.

### Configuration (Authelia)

```yaml
# values-authelia.yaml
# note this uses a Kubernetes secret `jwks-keys` from the reproduction steps.
---
image:
  tag: 4.39.1
configMap:
  log:
    level: 'debug'
  session:
    cookies:
      - domain: k8s.orb.local
        subdomain: auth
  totp:
    disable: true
  webauthn:
    disable: true
  authentication_backend:
    file:
      enabled: true
  access_control:
    default_policy: one_factor
  storage:
    local:
      enabled: true
  notifier:
    smtp:
      enabled: true
      address: 'smtp://mailpit-smtp.default.svc.cluster.local:25'
      username: ""
      password:
        disabled: true
      disable_require_tls: true
  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key_id: '1'
          algorithm: 'RS256'
          key:
            path: /secrets/jwks-keys/jwks-key-1.pem
      clients:
        - client_id: my_spa
          client_name: My SPA
          public: true
          redirect_uris:
            - 'http://localhost:55001/callback'
          scopes:
            - openid
            - email
            - profile
          audience:
            - 'http://lfx-api.k8s.orb.local/'
          grant_types:
            - authorization_code
          authorization_policy: one_factor
          # Uncomment next 3 lines to allow startup; however this is expected to be the default for `public`.
          # revocation_endpoint_auth_method: none
          # introspection_endpoint_auth_method: none
          # pushed_authorization_request_endpoint_auth_method: none
ingress:
  enabled: true
secret:
  additionalSecrets:
    jwks-keys: {}
persistence:
  enabled: true
```

### Build Information

```shell
Last Tag: v4.39.1
State: tagged clean
Branch: v4.39.1
Commit: 9a22f5c30b216b6d1aa1f80b6a36fac62e9f7727
Build Number: 41283
Build OS: linux
Build Arch: arm64
Build Compiler: gc
Build Date: Tue, 18 Mar 2025 14:49:44 +1100
Extra:

Go:
    Version: go1.24.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-04-23T17:52:55Z" level=debug msg="Loaded Configuration Sources" files="[/configuration.yaml]" filters="[template]"
time="2025-04-23T17:52:55Z" level=debug msg="Logging Initialized" fields.level=debug file= format=text keep_stdout=true
time="2025-04-23T17:52:55Z" level=debug msg="Process user information" gid=0 name=root uid=0 username=root
time="2025-04-23T17:52:55Z" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
time="2025-04-23T17:52:55Z" level=error msg="Configuration: identity_providers: oidc: clients: client 'my_spa': option 'revocation_endpoint_auth_method' must be 'none' when configured as the public client type but it's configured as 'client_secret_basic'" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
time="2025-04-23T17:52:55Z" level=error msg="Configuration: identity_providers: oidc: clients: client 'my_spa': option 'introspection_endpoint_auth_method' must be 'none' when configured as the public client type but it's configured as 'client_secret_basic'" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
time="2025-04-23T17:52:55Z" level=error msg="Configuration: identity_providers: oidc: clients: client 'my_spa': option 'pushed_authorization_request_endpoint_auth_method' must be 'none' when configured as the public client type but it's configured as 'client_secret_basic'" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
time="2025-04-23T17:52:55Z" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_arm64.s:1223                                         goexit"
```

### Logs (Proxy / Application)

```shell
n/a
```

### Documentation

>  If no method is defined the confidential client type will default to client_secret_basic as this is required by the specification. **The public client type defaults to none as this is required by the specification.**

(emphasis mine; from <https://www.authelia.com/configuration/identity-providers/openid-connect/clients/#revocation_endpoint_auth_method>)

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
