### ISSUE TITLE
When not using OIDC, configuration error that OIDC configuration is required

### ISSUE THREAD

**Issue by NekoLuka** [authelia/authelia#9364]
### Version

v4.39.1

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

2.8.4

### Description

As the title says, I get a configuration error during startup that I need to configure an oidc client and jwks is required. 
This is while I don't have the `identity_providers` section in my config file.

### Reproduction

Use version 4.39.1 and create a config without the `identity_providers` section. Then start Authelia.

### Expectations

Regular startup behaviour without any oidc clients/configurations.

### Configuration (Authelia)

```yaml
server:
  address: tcp://0.0.0.0:9091/
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

storage:
  local:
    path: /config/authelia.db

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'

log:
  level: info
  format: text
  file_path: '/config/logs/authelia.%d.log'
  keep_stdout: true

authentication_backend:
  ldap:
    address: ldap://lldap:3890
    implementation: lldap
    base_dn: ${LDAP_BASE_DN}
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    groups_filter: "(&(member={dn})(objectClass=groupOfNames))"
    user: uid=authelia_bind_user,ou=people,${LDAP_BASE_DN}
    attributes:
      picture: jpegPhoto

totp:
  issuer: Authelia

webauthn:
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

regulation:
  max_retries: 3
  find_time: '2m'
  ban_time: '5m'

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: 'two_factor'
  rules:
    # Protect the dashboard
  - domain: 'dash.${DOMAIN}'
    policy: 'one_factor'
    # Protect gatus
  - domain: 'gatus.${DOMAIN}'
    policy: 'bypass'
    resources:
    - '^/api/v1/endpoints/[a-z\-_]+/uptimes/24h/badge\.svg$'

session:
  cookies:
    - domain: ${DOMAIN}
      authelia_url: https://auth.${DOMAIN}
      inactivity: 10m
      expiration: 2h
      remember_me: 1d
```

### Build Information

```shell
None, container is stuck in a restart loop
```

### Logs (Authelia)

```shell
authelia-1  | time="2025-04-29T10:19:29Z" level=warning msg="Experimental file filter 'expand-env' is deprecated in favor of the 'template' filter and will be removed in v4.40.0"
authelia-1  | time="2025-04-29T10:19:29Z" level=warning msg="Configuration: configuration key 'webauthn.user_verification' is deprecated in 4.39.0 and has been replaced by 'webauthn.selection_criteria.user_verification': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
authelia-1  | time="2025-04-29T10:19:29Z" level=warning msg="Configuration: configuration key 'webauthn.user_verification' is deprecated in 4.39.0 and has been replaced by 'webauthn.selection_criteria.user_verification': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
authelia-1  | time="2025-04-29T10:19:29Z" level=error msg="Configuration: identity_providers: oidc: option `jwks` is required"
authelia-1  | time="2025-04-29T10:19:29Z" level=error msg="Configuration: identity_providers: oidc: option 'clients' must have one or more clients configured"
authelia-1  | time="2025-04-29T10:19:29Z" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
