### ISSUE TITLE
Cannot use JWT access token for auth to UserInfo endpoint

### ISSUE THREAD

**Issue by felix** [authelia/authelia#9382]
### Version

v4.39.1

### Deployment Method

Binary

### Reverse Proxy

None

### Description

Configured to support rfc 9068 JWT access tokens, which are produced correctly, but when used to authenticate against the UserInfo endpoint they produce an error. The endpoint works find with the non-JWT access tokens.

It seems the handling of session types only accounts for `oidc.Session` and not `oauth2.JWTSession`. OR, I could be doing something wrong.

### Reproduction

- Do PKCE dance
- Get JWT access token
- Use JWT access token to auth against UserInfo endpoint

### Expectations

- UserInfo response JSON

### Configuration (Authelia)

```yaml
---
theme: auto
default_2fa_method: totp
server:
  address: 'tcp://:8080/'
log:
  level: debug
totp:
  disable: false
  issuer: XXX
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: false
  timeout: 60s
  attestation_conveyance_preference: indirect
  selection_criteria:
    user_verification: preferred
telemetry:
  metrics:
    enabled: true
    address: 'tcp://localhost:9959/metrics'
authentication_backend:
  password_reset:
    disable: false
  ldap:
    #password: in envvar from SSM
    address: 'ldap://ldap.iam:3890'
    implementation: lldap
    base_dn: 'dc=idetrust,dc=com'
    user: 'uid=authelia,ou=people,dc=XXX,dc=com'
    users_filter: '(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))'
    additional_groups_dn: 'OU=groups'
    groups_filter: '(member={dn})'
    attributes:
      distinguished_name: distinguishedName
      username: uid
      mail: mail
      member_of: memberOf
      group_name: cn
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: false
session:
  secret: some_random_session_secret
  cookies:
    - name: auth_session
      domain: XXX.com
      authelia_url: 'https://auth.XXX.com'
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
notifier:
  disable_startup_check: true
  smtp:
    #username: in envvar from SSM
    #password: in envvar from SSM
    address: 'smtp://XXX:587'
    sender: 'XXX <no-reply@XXX.com>'
    disable_html_emails: true
    subject: '[XXX] {title}'
    tls:
      skip_verify: true
access_control:
  default_policy: two_factor
identity_providers:
  oidc:
    #hmac_secret: in envvar from SSM
    jwks:
      - key_id: xxx-console
        key: {{ secret "/run/secrets/jwks-private-key" | mindent 10 "|" | msquote }}
    authorization_policies:
      xxx_console_dev:
        default_policy: deny
        rules:
          - policy: one_factor
            subject: 'group:xxx_console_dev'
    cors:
      allowed_origins: '*'
      endpoints:
        - userinfo
        - authorization
        - pushed-authorization-request
        - token
        - revocation
        - introspection
    enable_jwt_access_token_stateless_introspection: true
    clients:
      - client_name: 'XXX Console (Development)'
        client_id: xxx-console-dev
        authorization_policy: xxx_console_dev
        consent_mode: implicit
        public: true
        require_pkce: true
        access_token_signed_response_key_id: xxx-console
        access_token_signed_response_alg: RS256
        redirect_uris:
          - 'http://localhost:4200/'
```

### Build Information

```shell
# authelia build-info
Last Tag: v4.39.1
State: tagged clean
Branch: v4.39.1
Commit: 9a22f5c30b216b6d1aa1f80b6a36fac62e9f7727
Build Number: 41283
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Tue, 18 Mar 2025 14:49:44 +1100
Extra:

Go:
    Version: go1.24.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
User Info Request with id '53aba96d-a467-432d-94f4-40ae9d38ede0' on client with id 'XXX' failed to handle session with type '*oauth2.JWTSession'"
method=POST
path=/api/oidc/userinfo
remote_ip=XX.XX.XX.XX
stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_userinfo.go:86 
OpenIDConnectUserinfo\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:114 
RegisterOpenIDConnectRoutes.NewHTTPToAutheliaHandlerAdaptor.func20\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66 
RegisterOpenIDConnectRoutes.(*BridgeBuilder).Build.func2.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105
SecurityHeadersNoStore.func1\ngithub.com/valyala/fasthttp@v1.59.0/userdata.go:57
 (*userData).Get\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30
...
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
