### ISSUE TITLE
Unsuccessful 1FA authentication attempt by user

### ISSUE THREAD

**Issue by AurelienGuenerie** [authelia/authelia#9388]
### Version

v4.39.1

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Reverse Proxy Version

4.0.0-ls379

### Description

I have this log in authelia : level=error msg="Unsuccessful 1FA authentication attempt by user 'username'" method=GET path=/api/authz/auth-request remote_ip=xx.xx.xx.xx

The ip is another nas which connect its cloud sync service on my nextcloud nas (with authelia). This habitualy works, but since an update maybe, I get this log (It's in production so I did not change any config, just update services).

Cloud sync service works even if there is this log error. It just fill my logs with errors, and I was obliged to change my regulation:  max_retries to 0 because  It was configured to blocks my  normal access after 5 tries.

### Reproduction

It should be reproducible if you connect a cloud service using the same configuration : cloud sync connect using webdav via https://nextcloud.xxx.xxx.xx/remote.php/dav/files/username

### Expectations

Expected no error as before an unknown change

### Configuration (Authelia)

```yaml
access_control:
  ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  ## resource if there is no policy to be applied to the user.
  default_policy: deny

  networks:
    - name: internal
      networks:
        - '10.0.0.0/8'
        - '172.16.0.0/12'
        - '192.168.0.0/18'
        - 'xx.xxx.xxx.xxx'  # l'IP de ton serveur CloudSync 
    # - name: VPN
    #   networks: 10.9.0.0/16

  rules:

    # Rules applied to everyone
    - domain: 'nextcloud.xxx.xxx.xx'
      policy: 'bypass'
 
    
    - domain: '*.xxx.xxx.xx'
      policy: 'bypass'
      networks:
        - 'internal'
```

### Build Information

```shell
Last Tag: v4.39.1
State: tagged clean
Branch: v4.39.1
Commit: 9a22f5c30b216b6d1aa1f80b6a36fac62e9f7727
Build Number: 41283
Build OS: linux
Build Arch: arm64
Build Compiler: gc
Build Date: Tue, 18 Mar 2025 14:49:44 +1100
Extra: 

Go:
    Version: go1.24.1 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
2025-05-02T20:51:42.072777531Z time="2025-05-02T22:51:42+02:00" level=info msg="Storage schema is being checked for updates"
2025-05-02T20:51:42.089995863Z time="2025-05-02T22:51:42+02:00" level=info msg="Storage schema is already up to date"
2025-05-02T20:51:42.743632710Z time="2025-05-02T22:51:42+02:00" level=info msg="Startup complete"
2025-05-02T20:51:42.743738597Z time="2025-05-02T22:51:42+02:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/' and '/authelia'" server=main service=server
2025-05-02T20:51:58.305195989Z time="2025-05-02T22:51:58+02:00" level=error msg="Unsuccessful 1FA authentication attempt by user 'username'" method=GET path=/api/authz/auth-request remote_ip=xx.xxx.xxx.xxx
```

### Logs (Proxy / Application)

```shell
nothing inhabitual in swag logs
```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation

**Comment by Crowley723** [comment]
Duplicate of #9113 

This behavior is expected. One solution would be to define a second authorization endpoint that you use for applications that need the full header-based authorization checking and modify the default `auth-request` endpoint as below to use with nextcloud.

The example shown [here](https://www.authelia.com/integration/proxies/swag/#prerequisite-steps) shows the default auth-request endpoint usage in swag (which would be what you want). 
But to use the `auth-request/basic` endpoint (for other apps) you would need to create another location in swag.

```yaml
server:
  endpoints:
    authz:
      # This would ignore any authentication headers and only look at the authelia cookie
      # You would use this for nextcloud
      auth-request: 
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'CookieSession'
      # This would additionally use any authentication headers.
      # You would use this for any applications that require full Authelia protection
      # with both header-based and cookie-based authentication methods
      auth-request/basic:
        implementation: 'AuthRequest'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
            scheme_basic_cache_lifespan: 0
          - name: 'CookieSession'
 ```

If you run into any issue with this solution, feel free to open a discussion or ask in one of our [support channels](https://www.authelia.com/information/contact/).
