### ISSUE TITLE
Breaking change in 4.39.4

### ISSUE THREAD

**Issue by mlow** [authelia/authelia#9684]
### Version

v4.39.4

### Deployment Method

Kubernetes

### Reverse Proxy

NGINX

### Description

I have been using Authelia to service as an OAuth2 provider for Mattermost by way of its GitLab SSO mechanism (we're a small team, Mattermost locks generic OpenID behind a license).

This has been working fine, I had configured Authelia to provide the custom `id` and `username` claims that Mattermost requests. Notable, however, is that Mattermost  *does not* request the `openid` scope when (ab)using its GitLab SSO feature in this way,

However, commit [4a4c497d](https://github.com/authelia/authelia/commit/4a4c497d736d5e447789339bcf2da9e37523e123#diff-a12d41fbc22abfec08352e41569f35c9964ceb874c9dae5ce8464f82b896c31bR78-R88) which is included in Authelia 4.39.4 introduces the following check:

```go
	if !requester.GetGrantedScopes().Has(oidc.ScopeOpenID) {
		ctx.Logger.Errorf("User Info Request with id '%s' on client with id '%s' failed with error: bearer authorization failed as the Access Token was not granted the appropriate scope", requestID, client.GetID())

		errorsx.WriteRFC6750Error(
			rw,
			oauthelia2.ErrInsufficientScope.WithHint("The granted scope was missing the 'openid' scope."),
			map[string]string{oidc.FormParameterScope: oidc.ScopeOpenID},
		)

		return
	}
```

Which now gets triggered when using Mattermost with Authelia in the fashion described above. Configuring Mattermost *to* request the `openid` scope breaks things on their end.

While I do realize that my use case here is an abuse of Authelia as OIDC provider, is there any possibility to introduce an explicitly-configured escape hatch that would continue to allow these requests to be accepted?

### Reproduction

Configure Mattermost's Gitlab SSO provider as such:

```json
    ....
    "GitLabSettings": {
        "Enable": true,
        "Secret": "<client secret>",
        "Id": "<client id>",
        "Scope": "profile email id username",
        "AuthEndpoint": "https://<authelia>/api/oidc/authorization",
        "TokenEndpoint": "https://<authelia>/api/oidc/token",
        "UserAPIEndpoint": "https://<authelia>/api/oidc/userinfo",
        "DiscoveryEndpoint": "https://<authelia>/.well-known/openid-configuration",
    },
    ....
```

Note: I tried the obvious thing here of including `openid` in the Scope string above, but this results in Mattermost not even attempting to redirect to Authelia as if there is an attempt made to prevent using generic OIDC providers with their GitLab SSO feature.

And an Authelia provider:

```yaml
identity_providers:
  oidc:
    ...
    scopes:
      id:
        claims:
          - id
      username:
        claims:
          - username
    ...
    clients:
      - client_id: '<client id>'
        client_name: 'Mattermost'
        client_secret: ...
        public: false
        redirect_uris:
          - 'https://<mattermost URL>/signup/gitlab/complete'
        scopes:
          - openid
          - profile
          - email
          # The id and username scopes are required by Mattermost's Gitlab SSO
          # provider
          - id
          - username
        claims_policy: mm_claims  # not shown
        authorization_policy: external
        token_endpoint_auth_method: client_secret_post
        introspection_endpoint_auth_method: client_secret_post
        pushed_authorization_request_endpoint_auth_method: client_secret_post
```

The above works with Authelia 4.39.3, but fails with the provided log message with 4.39.4.

### Configuration (Authelia)

```yaml

```

### Build Information

```shell
Last Tag: v4.39.4
State: tagged clean
Branch: v4.39.4
Commit: 3f173e1cd1acda592dcb4aa161f43823d6df1110
Build Number: 44639
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 25 May 2025 12:19:36 +1000
Extra: 

Go:
    Version: go1.24.3 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-06-18T15:01:10Z" level=error msg="User Info Request with id 'abad0de5-2eb2-46a4-a06c-7e8dfb8fcd9f' on client with id '<client id>' failed with error: bearer authorization failed as the Access Token was not granted the appropriate scope" method=GET path=/api/oidc/userinfo path_raw=/auth/api/oidc/userinfo remote_ip=10.97.133.2 stack="github.com/authelia/authelia/v4/internal/handlers/handler_oauth2_oidc_userinfo.go:79         OpenIDConnectUserinfo\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:114 RegisterOpenIDConnectRoutes.NewHTTPToAutheliaHandlerAdaptor.func19\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                            RegisterOpenIDConnectRoutes.(*BridgeBuilder).Build.func2.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                          SecurityHeadersNoStore.func1\ngithub.com/valyala/fasthttp@v1.62.0/server.go:773                                            (*RequestCtx).UserValue\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                           SecurityHeadersBase.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             RegisterOpenIDConnectRoutes.(*CORSPolicy).Middleware.func20\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:23                        handlerMain.StripPath.func32.1\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                            RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.62.0/server.go:2455                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:225                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:197                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                                     goexit"
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

Yes

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
