### ISSUE TITLE
Can not use "http://example.com/myclaim" as the name for a custom claim

### ISSUE THREAD

**Issue by deonspengler** [authelia/authelia#9687]
### Version

v4.39.4

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.28.0

### Description

Our company uses a third-party application that recently introduced OAuth 2.0 authentication support. During configuration, we need to create a custom claim named "http://example.com/myclaim". However, when we attempt to configure this custom claim in Authelia using the full URL as the claim name, Authelia fails to start. While changing the claim name to something simpler like "myclaim" allows Authelia to start successfully, the third-party application specifically requires the URL format for the claim name and this requirement cannot be modified on their end.

I have also attempted several different methods to escape the special characters within the URL, but none of these approaches have been successful.

### Reproduction

Add the following configuration to Authelia's config file:

```yaml
identity_providers:
  oidc:
    claims_policies:
      3rdparty_policy:
        custom_claims:
          "http://example.com/myclaim":
            attribute: 'ioadmin'
    clients:
      - client_id: '3rdparty'
        client_secret: ''
        public: true
        authorization_policy: 'one_factor'
        consent_mode: 'implicit'
        redirect_uris:
          - 'http://localhost:42420/3rdparty.UIL.Shell'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        token_endpoint_auth_method: 'none'
        claims_policy: '3rdparty_policy'
        audience:
          - 'https://example.com/api'
```

When Authelia attempts to start with this configuration, it fails due to the URL format used in the custom claim name "http://example.com/myclaim". The issue specifically occurs when using a full URL (including the protocol and domain) as the claim identifier.

This format is required by our third-party application and cannot be changed to a simpler claim name like "myclaim", which would otherwise allow Authelia to start successfully.

### Expectations

I expect to be able to use "http://example.com/myclaim" as a custom claim name.

### Configuration (Authelia)

```yaml

```

### Build Information

```shell
Last Tag: v4.39.4
State: tagged clean
Branch: v4.39.4
Commit: 3f173e1cd1acda592dcb4aa161f43823d6df1110
Build Number: AUR
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Thu, 19 Jun 2025 08:38:11 +0200
Extra: 

Go:
    Version: go1.24.3
    Module Path: 
    Executable Path: command-line-arguments
```

### Logs (Authelia)

```shell
Started Authelia authentication and authorization server.
time="2025-06-19T14:02:22+02:00" level=debug msg="Loaded Configuration Sources" files="[/etc/authelia/configuration.yml]" filters="[]"
time="2025-06-19T14:02:22+02:00" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2025-06-19T14:02:22+02:00" level=debug msg="Process user information" gid=957 gids=958 name="Authelia Daemon User" uid=957 username=authelia
time="2025-06-19T14:02:22+02:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.claims_policies.justenough_policy.custom_claims.http://example.com/myclaim.attribute" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-19T14:02:22+02:00" level=error msg="Configuration: identity_providers: oidc: claims_policies: justenough_policy: claim with name 'http://example' has an attribute name 'http://example' which is not a known attribute" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-19T14:02:22+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
authelia.service: Main process exited, code=exited, status=1/FAILURE
authelia.service: Failed with result 'exit-code'.
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
This effectively isn't a scenario we had planned for unfortunately. I think this may require some additional parsing logic since the configuration library doesn't seem to support this specific function. Was there any format you used where the error changed?

What's effectively happening is our key separator is `.`, which means the key with a period in it can't be unmarshalled to the data structure and also can't be validated. We may have to support a composite type here where it can either be an array or dictionary, or we may have to add a field to override the claim name derived from the dictionary key.

So if the key names mentioned in the errors change it may be a sign we can work around it (maybe some of the below examples will work? I doubt it and my syntax may also be incorrect but I believe both are valid YAML), but otherwise it may not be and may require additional implementation.

```yaml
identity_providers:
  oidc:
    claims_policies:
      3rdparty_policy:
        custom_claims: {"http://example.com/myclaim": "attribute": "ioadmin"}
```

```yaml
identity_providers:
  oidc:
    claims_policies:
      3rdparty_policy:
        ["http://example.com/myclaim"]: 
          attribute: 'ioadmin'
```

**Comment by deonspengler** [comment]
Hi when I try the first suggestion this is the startup log
```
Started Authelia authentication and authorization server.
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: failed to load configuration from file path(/etc/authelia/configuration.yml) source: yaml: line 108: did not find expected ',' or '}'"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: failed to load configuration from file path(/etc/authelia/configuration.yml) source: yaml: line 108: did not find expected ',' or '}'"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: session: option 'cookies' is required"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: storage: option 'encryption_key' is required"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"
time="2025-06-22T22:40:15+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
time="2025-06-22T22:40:15+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
authelia.service: Main process exited, code=exited, status=1/FAILURE
authelia.service: Failed with result 'exit-code'.
```
The second one results in the following startup log
```
Started Authelia authentication and authorization server.
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: failed to load configuration from file path(/etc/authelia/configuration.yml) source: yaml: invalid map key: []interface {}{\"http://example.com/myclaim\"}"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: failed to load configuration from file path(/etc/authelia/configuration.yml) source: yaml: invalid map key: []interface {}{\"http://example.com/myclaim\"}"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: session: option 'cookies' is required"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: storage: option 'encryption_key' is required"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided"
time="2025-06-22T22:48:09+02:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
time="2025-06-22T22:48:09+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
authelia.service: Main process exited, code=exited, status=1/FAILURE
authelia.service: Failed with result 'exit-code'.
```
When using "http://example" as the custom claim name, it results in the following startup error
```
time="2025-06-22T22:53:41+02:00" level=debug msg="Shutdown initiated due to process signal" signal=terminated
time="2025-06-22T22:53:41+02:00" level=info msg="Shutdown initiated"
Stopping Authelia authentication and authorization server...
time="2025-06-22T22:53:41+02:00" level=info msg="Shutdown complete"
authelia.service: Deactivated successfully.
Stopped Authelia authentication and authorization server.
Started Authelia authentication and authorization server.
time="2025-06-22T22:53:41+02:00" level=debug msg="Loaded Configuration Sources" files="[/etc/authelia/configuration.yml]" filters="[]"
time="2025-06-22T22:53:41+02:00" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2025-06-22T22:53:41+02:00" level=debug msg="Process user information" gid=957 gids=958 name="Authelia Daemon User" uid=957 username=authelia
time="2025-06-22T22:53:41+02:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.claims_policies.justenough_policy.custom_claims.http://example.attribute" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-22T22:53:41+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
authelia.service: Main process exited, code=exited, status=1/FAILURE
authelia.service: Failed with result 'exit-code'.
```
When using "http//example" it starts without any problems.

Is there anything else that you would like me to test or assist with?

**Comment by james-d-elliott** [comment]
No that's perfect. I'll have to think on how to solve it. I may get you to test a few things to make sure everything works once I've made a more concrete decision.

**Comment by Crowley723** [comment]
Would it be easier to allow the use of troublesome keys like so:

```yaml
the_list:
  - key: "troublesome_key"
    value: "foo"
```

**Comment by james-d-elliott** [comment]
The above PR should fix this issue. The following lists artifacts in the green `Artifacts` section including a deb: https://buildkite.com/authelia/authelia/builds/45461

It requires an additional config to resolve it:

```yaml
identity_providers:
  oidc:
    claims_policies:
      3rdparty_policy:
        example:
          name: 'http://example.com/myclaim'
          attribute: 'ioadmin'
```

**Comment by deonspengler** [comment]
Hi James, thanks for your pull request. I have applied the patch to version 4.39.4 of Authelia. It no longer fails to start when using the following 😃 

```
    claims_policies:
      example_policy:
        custom_claims:
          example:
            name: 'http://example.com/myclaim'
            attribute: 'ioadmin'
```
However when using a more complete configuration
```
    claims_policies:
      example_policy:
        custom_claims:
          example:
            name: 'http://example.com/myclaim'
            attribute: 'ioadmin'

    scopes:
      example_scope:
        claims:
          - 'http://example.com/myclaim'

    clients:
      - client_id: 'example_client'
        client_secret: ''
        public: true
        authorization_policy: 'one_factor'
        consent_mode: 'implicit'
        redirect_uris:
          - 'http://localhost:42420/3rdparty.UIL.Shell'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
          - 'example_scope'
        token_endpoint_auth_method: 'none'
        claims_policy: 'example_policy'
```
I get the following error when trying to start Authelia
```
Started Authelia authentication and authorization server.
time="2025-06-26T14:17:23+02:00" level=debug msg="Loaded Configuration Sources" files="[/etc/authelia/configuration.yml]" filters="[]"
time="2025-06-26T14:17:23+02:00" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2025-06-26T14:17:23+02:00" level=debug msg="Process user information" gid=953 gids=970 name="Authelia Daemon User" uid=953 username=authelia
time="2025-06-26T14:17:23+02:00" level=error msg="Configuration: identity_providers: oidc: clients: client 'example_client': option 'scopes' contains value 'example_scope' which requires claim 'http://example.com/myclaim' but the claim is not a claim provided by 'claims_policy' with the name 'example_policy' or a standard claim" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-26T14:17:23+02:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\n./main.go:10                                                     main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
authelia.service: Main process exited, code=exited, status=1/FAILURE
authelia.service: Failed with result 'exit-code'.
```
It appears to be related. Is there anything else that I could assist with.
