### ISSUE TITLE
Multiple Configuration bugs/issues preventing initial app startup.

### ISSUE THREAD

**Issue by abjoseph** [authelia/authelia#9700]
### Version

v4.39.4

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

v2.12.3

### Description

I'm a first-time user of Authelia and I would like to deploy an MVP instance to test with and integrate with my existing Self Hosted services.

Using the docker _`compose.yml`_ and the authelia _`configuration.yml`_ referenced in this issue, I've been consistently encountering the errors shown below.

Specifically, I would like to highlight the following issues which I find to be either inconsistent or outright bugs.

1. Despite having `notifier.disable_startup_check: true` the logs _**still**_ throw an error regarding a valid value being set for notifications.
2. I'm getting an error regarding `jwt_secret` despite it being declared with a template filter same as other secrets, yet only this particular setting is erroring out. All other secret references seem to be working/populating just fine.
3. I've configured the logs to write to both `stdout` _**and**_ `log file`, yet an `authelia.log` file is never created in the config folder. I would expect the file to be created and populated with the exact same log content shown here.
4. I don't understand why the following warning `time="2025-06-23T14:49:54-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret'` is being shown when I'm clearly using a newer version and also having the new/update configuration.

```bash
time="2025-06-23T14:49:47-04:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[template]"
time="2025-06-23T14:49:47-04:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format=text keep_stdout=true
time="2025-06-23T14:49:47-04:00" level=debug msg="Process user information" gid=1000 uid=1000
time="2025-06-23T14:49:47-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T14:49:47-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T14:49:47-04:00" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
time="2025-06-23T14:49:47-04:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T14:49:47-04:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T14:49:47-04:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T13:50:36-04:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[template]"
time="2025-06-23T13:50:36-04:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format=text keep_stdout=true
time="2025-06-23T13:50:36-04:00" level=debug msg="Process user information" gid=1000 uid=1000
time="2025-06-23T13:50:36-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T13:50:36-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T13:50:36-04:00" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
time="2025-06-23T13:50:36-04:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T13:50:36-04:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T13:50:36-04:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
```

### Reproduction

Attempt deployment of a new instance of Authelia using the both the docker _`compose.yml`_ and the authelia _`configuration.yml`_ referenced below.

> The deployed docker compose.yml file.
```yaml
---
services:
  authelia:
    image: authelia/authelia:4.39.4
    container_name: authelia
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    env_file:
      - stack.env
    networks:
      - sso-net
    ports:
      - "9091:9091"
    volumes:
      - "/root/docker/mounts/authelia/config:/config:rw"
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - COOKIE_SESSION_DOMAIN=example.com
      - AUTHELIA_TOTP_ISSUER=sso.example.com
      - X_AUTHELIA_CONFIG_FILTERS=template
      - AUTHELIA_JWT_SECRET
      - AUTHELIA_STORAGE_ENCRYPTION_KEY
      - AUTHELIA_SESSION_SECRET
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD

networks:
  sso-net:
    external: false
```

### Expectations

My expectations are that the Authelia application would deploy and run without issue as I've consulted the official docs numerous times over and nothing stands out to me as out of place or incorrect.

### Configuration (Authelia)

```yaml
---
theme: 'grey'
default_2fa_method: 'totp'
server:
  address: 'tcp://0.0.0.0:9091/'
  disable_healthcheck: false
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: '6s'
    write: '6s'
    idle: '30s'
  endpoints:
    enable_pprof: false
    enable_expvars: false
    authz: {}
    rate_limits: {}

log:
  level: 'debug'
  format: 'text'
  file_path: '/config/authelia.log'
  keep_stdout: true

totp:
  disable: false
  issuer: '{{ env "AUTHELIA_TOTP_ISSUER" }}'
  algorithm: 'sha1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  allowed_algorithms:
    - 'SHA1'
    - 'SHA256'
  allowed_digits:
    - 6
    - 8
  disable_reuse_security_policy: false

webauthn:
  enable_passkey_login: true
  attestation_conveyance_preference: 'indirect'
  timeout: '60 seconds'
  filtering:
    permitted_aaguids: []
    prohibited_aaguids: []
    prohibit_backup_eligibility: true
  selection_criteria:
    attachment: ''
    discoverability: 'preferred'
    user_verification: 'preferred'
  metadata:
    enabled: true
    validate_trust_anchor: true
    validate_entry: true
    validate_status: true
    validate_entry_permit_zero_aaguid: false

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: '1m'
  ldap:
    implementation: 'lldap'
    address: 'ldap://lldap:3890'
    timeout: '5s'
    start_tls: false
    pooling:
      enable: false
      count: 5
      retries: 2
      timeout: '10 seconds'
    base_dn: 'dc=example,dc=com'
    additional_users_dn: 'ou=people'
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    additional_groups_dn: 'ou=groups'
    groups_filter: '(member={dn})'
    group_search_mode: 'filter'
    user: 'uid=authelia_bind_user,ou=people,dc=example,dc=com'
    password: '{{ env "AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD" }}'
    attributes:
      username: 'uid'
      display_name: 'displayName'
      family_name: 'sn'
      given_name: 'givenName'
      group_name: 'cn'
      member_of: 'memberOf'
      mail: 'mail'

password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: false

identity_validation:
  reset_password:
    jwt_secret: '{{ env "AUTHELIA_JWT_SECRET" }}'
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'

access_control:
  default_policy: 'one_factor' ## https://www.authelia.com/configuration/security/access-control/#policies

session:
  secret: '{{ env "AUTHELIA_SESSION_SECRET" }}'
  name: 'authelia_session'
  cookies:
    - domain: '{{ env "COOKIE_SESSION_DOMAIN" }}'
      authelia_url: 'https://sso.{{ env "COOKIE_SESSION_DOMAIN" }}'

regulation:
  modes:
    - 'user'
    - 'ip'
  max_retries: 3
  find_time: '2m'
  ban_time: '5m'

storage:
  encryption_key: '{{ env "AUTHELIA_STORAGE_ENCRYPTION_KEY" }}'
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: true
```

### Build Information

```shell
root@<REDACTED>:~# docker run --rm authelia/authelia:4.39.4 authelia build-info
Unable to find image 'authelia/authelia:4.39.4' locally
4.39.4: Pulling from authelia/authelia
Digest: sha256:64b356c30fd817817a4baafb4dbc0f9f8702e46b49e1edb92ff42e19e487b517
Status: Downloaded newer image for authelia/authelia:4.39.4
Last Tag: v4.39.4
State: tagged clean
Branch: v4.39.4
Commit: 3f173e1cd1acda592dcb4aa161f43823d6df1110
Build Number: 44639
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 25 May 2025 12:19:36 +1000
Extra:

Go:
    Version: go1.24.3 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-06-23T14:49:47-04:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[template]"
time="2025-06-23T14:49:47-04:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format=text keep_stdout=true
time="2025-06-23T14:49:47-04:00" level=debug msg="Process user information" gid=1000 uid=1000
time="2025-06-23T14:49:47-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T14:49:47-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T14:49:47-04:00" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
time="2025-06-23T14:49:47-04:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T14:49:47-04:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T14:49:47-04:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T13:50:36-04:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[template]"
time="2025-06-23T13:50:36-04:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format=text keep_stdout=true
time="2025-06-23T13:50:36-04:00" level=debug msg="Process user information" gid=1000 uid=1000
time="2025-06-23T13:50:36-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T13:50:36-04:00" level=warning msg="Configuration: configuration key 'jwt_secret' is deprecated in 4.38.0 and has been replaced by 'identity_validation.reset_password.jwt_secret': this has not been automatically mapped for you because the replacement key also exists and you will need to adjust your configuration to remove this message"
time="2025-06-23T13:50:36-04:00" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
time="2025-06-23T13:50:36-04:00" level=error msg="Configuration: identity_validation: reset_password: option 'jwt_secret' is required when the reset password functionality isn't disabled" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T13:50:36-04:00" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
time="2025-06-23T13:50:36-04:00" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:157 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
