### ISSUE TITLE
Passkey registration error on non standard ssl port

### ISSUE THREAD

**Issue by NeoXTof** [authelia/authelia#9709]
### Version

v4.39.4

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

2.12.3

### Description

Hello,

when trying to register a passkey on an Authelia instance used behind Nginx Proxy Manager on a non standard ssl port, I have an error message indicating "Unable to register your security key"

where to configure the non standard ssl port ?

### Reproduction

100% reproductible on my setup when I try to register a passkey (windows hello and yubikey)

### Configuration (Authelia)

```yaml
webauthn:
  disable: false
  enable_passkey_login: true
  experimental_enable_passkey_uv_two_factors: true
  experimental_enable_passkey_upgrade: true
  display_name: authelia.example.tld
  attestation_conveyance_preference: indirect
  timeout: 60s
  filtering:
    permitted_aaguids: []
    prohibited_aaguids: []
    prohibit_backup_eligibility: false
  selection_criteria:
    attachment: ''
    discoverability: preferred
    user_verification: preferred
  metadata:
    enabled: true
    validate_trust_anchor: true
    validate_entry: true
    validate_entry_permit_zero_aaguid: true
    validate_status: true
    validate_status_permitted: []
    validate_status_prohibited:
      - 'REVOKED'
      - 'USER_KEY_PHYSICAL_COMPROMISE'
      - 'USER_KEY_REMOTE_COMPROMISE'
      - 'USER_VERIFICATION_BYPASS'
      - 'ATTESTATION_KEY_COMPROMISE'
```

### Build Information

```shell
Last Tag: v4.39.4
State: tagged clean
Branch: v4.39.4
Commit: 3f173e1cd1acda592dcb4aa161f43823d6df1110
Build Number: 44639
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 25 May 2025 12:19:36 +1000
Extra: 

Go:
    Version: go1.24.3 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-06-25T12:17:17+02:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server
time="2025-06-25T12:18:06+02:00" level=error msg="Error occurred validating a WebAuthn registration challenge for user 'xxxxx': error comparing the response to the WebAuthn session data" error="Error validating origin (verification_error): Expected Values: [https://authelia.example.tld], 
Received: https://authelia.example.tld:12345" method=POST path=/api/secondfactor/webauthn/credential/register remote_ip=xxx.xxx.xxx.xxx stack=
        "github.com/authelia/authelia/v4/internal/handlers/handler_register_webauthn.go:214 
         WebAuthnRegistrationPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/require_auth.go:55            
         RequireElevated.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:66                  
         handlerMain.(*BridgeBuilder).Build.func9.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:65                 
         SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:105                
         SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:30                 
         SecurityHeadersBase.func1\ngithub.com/fasthttp/router@v1.5.4/router.go:441                                    
         (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14             
         handlerMain.LogRequest.func31\ngithub.com/authelia/authelia/v4/internal/middlewares/errors.go:38                  
         RecoverPanic.func1\ngithub.com/valyala/fasthttp@v1.62.0/server.go:2455                                 
         (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:225                              
         (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.62.0/workerpool.go:197                              
         (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                                           
         goexit"
```

### Logs (Proxy / Application)

```shell

```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
