### ISSUE TITLE
Default deny policy does not work for OIDC, as rules cannot be detected.

### ISSUE THREAD

**Issue by tim-connect** [authelia/authelia#9736]
### Version

v4.39.4

### Deployment Method

Docker

### Reverse Proxy

HAProxy

### Reverse Proxy Version

3.0.10

### Description

default deny policy in authorization_policies is not supported, even when other rules are specified.

### Reproduction

create an authorization policy for OIDC

### Expectations

Rules should worked as required by documentation

### Configuration (Authelia)

```yaml
...
identity_providers:
  oidc:
    authorization_policies:
      groups_policy:
        default_policy: 'deny'
        rules:
          - policy: 'one_factor'
            subject: "group:jellyfin_admin" #also attempted in list format


... (continued)
```

### Build Information

```shell
Last Tag: v4.39.4
State: tagged clean
Branch: v4.39.4
Commit: 3f173e1cd1acda592dcb4aa161f43823d6df1110
Build Number: 44639
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 25 May 2025 12:19:36 +1000
Extra: 

Go:
    Version: go1.24.3 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
authelia  | time="2025-06-28T12:42:47Z" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'" stack="github.com/authelia/authelia/v4/internal/commands/context.go:189 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.9.1/command.go:1000                    (*Command).execute\ngithub.com/spf13/cobra@v1.9.1/command.go:1148                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.9.1/command.go:1071                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700
```

### Logs (Proxy / Application)

```shell
None
```

### Documentation

example configuration: 
```
identity_providers:
  oidc:
    authorization_policies:
      policy_name:
        default_policy: 'two_factor'
        rules:
          - policy: 'deny'
            subject: 'group:services'
            networks:
              - '192.168.1.0/24'
              - '192.168.2.51'
    clients:
      - client_id: 'client_with_policy_name'
        authorization_policy: 'policy_name'
```

subject
list(list(string)) situational

Situational Note: Either this option or the [networks](https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#networks) must be configured or this rule is considered invalid.

### Generative AI

Yes

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
