### ISSUE TITLE
bug: warning in log message does not match OIDC client configuration

### ISSUE THREAD

**Issue by georglauterbach** [authelia/authelia#9769]
### Version

v4.39.4

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Reverse Proxy Version

3.4.1

### Description

I get the following log messages:

```ini
time="---" level=warning msg="Configuration: identity_providers: oidc: clients: client 'OpenCloudWeb': option 'grant_types' should only have the 'refresh_token' value if the client is also configured with the 'offline_access' scope"
time="---" level=warning msg="Configuration: identity_providers: oidc: clients: warnings for clients above indicate deprecated functionality and it's strongly suggested these issues are checked and fixed if they're legitimate issues or reported if they are not as in a future version these warnings will become errors"
```

### Reproduction

Configure Authelia in the `identity_providers.oidc.clients[]` section with these clients:

```yaml
      - # https://docs.opencloud.eu/docs/admin/configuration/authentication-and-user-management/external-idp/

        client_id: OpenCloudWeb
        client_name: OpenCloud Web
        public: true
        redirect_uris:
          - https://cloud.georglauterbach.com/
          - https://cloud.georglauterbach.com/oidc-callback.html
          - https://cloud.georglauterbach.com/oidc-silent-redirect.html
        scopes:
          - openid
          - profile
          - email
          - groups
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        consent_mode: implicit
        require_pkce: true
        pkce_challenge_method: S256
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: none

      - client_id: OpenCloudDesktop
        client_name: OpenCloud Desktop
        public: true
        redirect_uris:
          - http://127.0.0.1
          - http://localhost
        scopes:
          - openid
          - email
          - profile
          - groups
          - offline_access
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        lifespan: opencloud
        consent_mode: implicit
        userinfo_signed_response_alg: none

      - client_id: OpenCloudIOS
        client_name: OpenCloud iOS
        public: true
        redirect_uris:
          - oc://ios.opencloud.eu
        scopes:
          - openid
          - email
          - profile
          - groups
          - offline_access
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        lifespan: opencloud
        consent_mode: implicit
        userinfo_signed_response_alg: none
```

### Expectations

I would expect the warnings to show for the two clients `OpenCloudDesktop` and `OpenCloudIOS`, but not for `OpenCloudWeb` as `OpenCloudWeb` does not have the `offline_access` scope.

I also tried to only use `grant_types: [ refresh_token ]` on the clients that actually use the `offline_access` scope, but the client would not work then.

### Configuration (Authelia)

```yaml
##
## Identity Providers
##
identity_providers:

  ##
  ## OpenID Connect (Identity Provider)
  ##
  ## It's recommended you read the documentation before configuration of this section.
  ## See: https://www.authelia.com/c/oidc/provider
  oidc:
    ## The hmac_secret is used to sign OAuth2 tokens (authorization code, access tokens and refresh tokens).
    ## HMAC Secret can also be set using a secret: https://www.authelia.com/c/secrets
    #hmac_secret: env:AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET

    ## The JWK's issuer option configures multiple JSON Web Keys. It's required that at least one of the JWK's
    ## configured has the RS256 algorithm. For RSA keys (RS or PS) the minimum is a 2048 bit key.
    jwks:
      -
        ## Key ID embedded into the JWT header for key matching. Must be an alphanumeric string with 7 or less characters.
        ## This value is automatically generated if not provided. It's recommended to not configure this.
        # key_id: 'example'

        ## The key algorithm used with this key.
        # algorithm: 'RS256'

        ## The key use expected with this key. Currently only 'sig' is supported.
        # use: 'sig'

        ## Required Private Key in PEM DER form.
        key: XXX

        ## Optional matching certificate chain in PEM DER form that matches the key. All certificates within the chain
        ## must be valid and current, and from top to bottom each certificate must be signed by the subsequent one.
        # certificate_chain: |
          # -----BEGIN CERTIFICATE-----
          # ...
          # -----END CERTIFICATE-----
          # -----BEGIN CERTIFICATE-----
          # ...
          # -----END CERTIFICATE-----

    ## Enables additional debug messages.
    enable_client_debug_messages: false

    ## SECURITY NOTICE: It's not recommended changing this option and values below 8 are strongly discouraged.
    # minimum_parameter_entropy: 8

    ## SECURITY NOTICE: It's not recommended changing this option, and highly discouraged to have it set to 'never'
    ## for security reasons.
    # enforce_pkce: 'public_clients_only'

    ## SECURITY NOTICE: It's not recommended changing this option. We encourage you to read the documentation and fully
    ## understanding it before enabling this option.
    # enable_jwt_access_token_stateless_introspection: false

    ## The signing algorithm used for signing the discovery and metadata responses. An issuer JWK with a matching
    ## algorithm must be available when configured. Most clients completely ignore this and it has a performance cost.
    # discovery_signed_response_alg: 'none'

    ## The signing key id used for signing the discovery and metadata responses. An issuer JWK with a matching key id
    ## must be available when configured. Most clients completely ignore this and it has a performance cost.
    # discovery_signed_response_key_id: ''

    ## Authorization Policies which can be utilized by clients. The 'policy_name' is an arbitrary value that you pick
    ## which is utilized as the value for the 'authorization_policy' on the client.
    authorization_policies:
      allow_users:
        default_policy: deny
        rules:
          - policy: two_factor
            subject: group:admin
          - policy: two_factor
            subject: group:user

    ## The lifespans configure the expiration for these token types in the duration common syntax. In addition to this
    ## syntax the lifespans can be customized per-client.
    lifespans:
      ## Configures the default/fallback lifespan for given token types. This behaviour applies to all clients and all
      ## grant types but you can override this behaviour using the custom lifespans.
      access_token: 1 hour
      authorize_code: 1 minute
      id_token: 1 hour
      refresh_token: 2 hours

      custom:
        opencloud:
          access_token: 1 hour
          authorize_code: 1 minute
          id_token: 1 hour
          refresh_token: 7 days

    ## Cross-Origin Resource Sharing (CORS) settings.
    cors:
      ## List of endpoints in addition to the metadata endpoints to permit cross-origin requests on.
      endpoints:
        - authorization
        - pushed-authorization-request
        - token
        - revocation
        - introspection
        - userinfo

      ## List of allowed origins.
      ## Any origin with https is permitted unless this option is configured or the
      ## allowed_origins_from_client_redirect_uris option is enabled.
      allowed_origins:
        - XXX

      ## Automatically adds the origin portion of all redirect URI's on all clients to the list of allowed_origins,
      ## provided they have the scheme http or https and do not have the hostname of localhost.
      allowed_origins_from_client_redirect_uris: true

    ## Clients is a list of registered clients and their configuration.
    ## It's recommended you read the documentation before configuration of a registered client.
    ## See: https://www.authelia.com/c/oidc/registered-clients
    clients:
      - # https://docs.opencloud.eu/docs/admin/configuration/authentication-and-user-management/external-idp/

        client_id: OpenCloudWeb
        client_name: OpenCloud Web
        public: true
        redirect_uris:
          - https://cloud.georglauterbach.com/
          - https://cloud.georglauterbach.com/oidc-callback.html
          - https://cloud.georglauterbach.com/oidc-silent-redirect.html
        scopes:
          - openid
          - profile
          - email
          - groups
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        consent_mode: implicit
        require_pkce: true
        pkce_challenge_method: S256
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: none

      - client_id: OpenCloudDesktop
        client_name: OpenCloud Desktop
        public: true
        redirect_uris:
          - http://127.0.0.1
          - http://localhost
        scopes:
          - openid
          - email
          - profile
          - groups
          - offline_access
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        lifespan: opencloud
        consent_mode: implicit
        userinfo_signed_response_alg: none

      - client_id: OpenCloudIOS
        client_name: OpenCloud iOS
        public: true
        redirect_uris:
          - oc://ios.opencloud.eu
        scopes:
          - openid
          - email
          - profile
          - groups
          - offline_access
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        lifespan: opencloud
        consent_mode: implicit
        userinfo_signed_response_alg: none
```

### Build Information

```shell
Last Tag: v4.39.4
State: tagged clean
Branch: v4.39.4
Commit: 3f173e1cd1acda592dcb4aa161f43823d6df1110
Build Number: 44639
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 25 May 2025 12:19:36 +1000
Extra:

Go:
    Version: go1.24.3 X:nosynchashtriemap
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2025-06-29T12:33:20+02:00" level=warning msg="Configuration: identity_providers: oidc: clients: client 'OpenCloudWeb': option 'grant_types' should only have the 'refresh_token' value if the client is also configured with the 'offline_access' scope"
time="2025-06-29T12:33:20+02:00" level=warning msg="Configuration: identity_providers: oidc: clients: warnings for clients above indicate deprecated functionality and it's strongly suggested these issues are checked and fixed if they're legitimate issues or reported if they are not as in a future version these warnings will become errors"
```

### Logs (Proxy / Application)

```shell
not applicable
```

### Generative AI

No

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [x] This is a bug report and not a support request

- [x] I have read the security policy and this bug report is not a security issue or security related issue

- [x] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [x] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [x] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [x] I have checked for related proxy or application logs and included them if available

- [x] I have checked for related issues and checked the documentation
