### ISSUE TITLE
middleware authelia@docker not found

### ISSUE THREAD

**Issue by deeztek** [authelia/authelia#997]
Using the example docker-compose.yml file for the "authelia" service below:

https://github.com/authelia/authelia/blob/master/compose/lite/docker-compose.yml

Traefik complains that the authelia@docker middleware is not found.

The only way I can stop that error is to add the following label in the "authelia" service config:

 - 'traefik.http.middlewares.authelia=authelia'

Am I missing something or did I stumble on a bug?

**Comment by james-d-elliott** [comment]
What version are you running @deeztek ? My recollection is you don't have to add that, but maybe I'm wrong or it changed in a specific version.

**Comment by deeztek** [comment]
I'm running v2.1

**Comment by deeztek** [comment]
So it looks like v2.2 does not seem to require it.

**Comment by james-d-elliott** [comment]
Hi @deeztek thanks for letting us know. I think we need to document that, so we'll reopen this for now.

**Comment by fredericrous** [comment]
I had a similar, issue, my understanding was that it was due to traefik and my protected containers popping before authelia (which defined the middleware).
The middleware was not found because it didn't exist yet. What I ended up doing is to create a traefik.d/ yaml file like the following

```
http:
  middlewares:
    forward-auth:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://auth.myserver.com
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"

```

and then I reference the middleware on my container with a label like so:

```
traefik.http.routers.myapp.middlewares=forward-auth@file
```
